### ISSUE TITLE
Low fps with 3 car compared to older versions.

### ISSUE THREAD

**Issue by Max98** [RigsOfRods/rigs-of-rods#1]
Using 0.4.0.7, i have 74 fps with 3 Gavril bandits spawned, using the NextStable version, i have around 16 fps. 
I believe that this could be a multi-threading problem.

![screenshot_3](https://cloud.githubusercontent.com/assets/4823878/5562891/d2173064-8e44-11e4-829f-c609d427d9ff.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/4823878/5562893/da3c88b6-8e44-11e4-9d59-9bb8e79d5228.png)

**Comment by Max98** [comment]
For some reasons this seems to be fixed on latest's Aperion edits: http://prntscr.com/6ahtx9
Will try again when the upstream gets updated.

**Comment by Speciesx** [comment]
You can find the solution for this problem here. http://www.rigsofrods.com/threads/119110-Test-Build-Rigs-of-rods-0-4-5-0-dev?p=1377981&viewfull=1#post1377981

**Comment by Hiradur** [comment]
Is this still valid?

**Comment by only-a-ptr** [comment]
@Hiradur : Ulteq's fix looks good - is it in upstream yet?
If yes, we can close this as resolved.

**Comment by Hiradur** [comment]
It isn't, I'll add it to my repo.

**Comment by Max98** [comment]
This is not fixed yet.
http://i.imgur.com/EgxAcpO.jpg

**Comment by Hiradur** [comment]
@Max98 Have you tried to play around with the #defines?
