### ISSUE TITLE
remove zoom in limit

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1000]
Currently this here is the maximum.
![ror_2016_05_30_19_45_15_060](https://cloud.githubusercontent.com/assets/1196375/15655650/4888e0dc-269f-11e6-9bc6-aa54945c32ed.jpg)

**Comment by ulteq** [comment]
Press: `RSHIFT + SPACE`

**Comment by Speciesx** [comment]
Nice!
