### ISSUE TITLE
Broken/malfunctioning vehicles (aka 'parser issues')

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1008]
**[EDIT by _only_a_ptr_]** See up-to date [TODO list](https://github.com/RigsOfRods/rigs-of-rods/issues/1008#issuecomment-293416905)

**Comment by ulteq** [comment]
Adding to the soup:

```
20:10:02: Cache: Parsing vehicle '78ea1UID-liebherr.truck' yielded following messages:

ERROR (Section rotators)
    Line (# 2114): 170, 171, 83, 87, 88, 84, 174, 178, 180, 176, 0.02, 1, 2, 0.5,0.9, smoothcrane revprogressiv
    Message: Invalid line, ignoring...
```

```
20:10:02: Cache: Parsing vehicle 'interstate_8ST_beta.load' yielded following messages:

ERROR (Section flares2)
    Line (# 975): 10, 6, 12,  1.015, 0.7, 0.6., f, -1, 0, 0.4  8ST_runninglight
    Message: Invalid line, ignoring it...
ERROR (Section flares2)
    Line (# 998): 26, 28, 30,  0.5, 0.8, 0.5, r, -l, 400, 0.8, tracks/brakeflare
    Message: Invalid line, ignoring it...
ERROR (Section flares2)
    Line (# 999): 27, 25, 31,  0.5, 0.8, 0.5, l, -l, 400, 0.8, tracks/brakeflare
    Message: Invalid line, ignoring it...
```

```
20:10:02: Cache: Parsing vehicle 'af25UID-aaadodgeviper.truck' yielded following messages:

ERROR (Section guisettings)
    Line (# 1972): usemaxrpm 1
```

```
20:10:02: Cache: Parsing vehicle 'F650Crawler.truck' yielded following messages:

ERROR (Section <truck name>)
    Line (# 2): fileformatversion <Version 2>
    Message: Invalid line, ignoring...
```

```
20:10:03: Cache: Parsing vehicle 'Allis_Chalmers_HD11.truck' yielded following messages:

ERROR (Section globals)
    Line (# 6): author chassis coelho87
    Message: Invalid line, ignoring...
ERROR (Section globals)
    Line (# 7): author texture coelho87
    Message: Invalid line, ignoring...
ERROR (Section commands)
    Line (# 1815): 17,   12,  0.1,  0.5,     1.2,  6,    5,   i n, blade_up_down
    Message: Invalid line, ignoring...
```

```
20:10:03: Cache: Parsing vehicle 'miurap400.truck' yielded following messages:

ERROR (Section shocks)
    Line (# 3394): 448, 168. 0, 100, 0, 0.6, 1, i
    Message: Invalid line, ignoring...
```

```
20:10:03: Cache: Parsing vehicle 'di-gokartv4.truck' yielded following messages:

WARNING (Section submesh)
    Line (# 665): contactors
    Message: Syntax check failed, parsing by legacy unsafe method...
ERROR (Section submesh)
    Line (# 665): contactors
    Message: Too few arguments, minimum is: 3
WARNING (Section submesh)
    Line (# 665): contactors
    Message: Too few arguments, required number is 3
WARNING (Section submesh)
    Line (# 666): 0
    Message: Syntax check failed, parsing by legacy unsafe method...
ERROR (Section submesh)
    Line (# 666): 0
    Message: Too few arguments, minimum is: 3
...
...
...
```

```
20:10:04: Cache: Parsing vehicle 'konecrane.truck' yielded following messages:

ERROR (Section managedmaterials)
    Line (# 20): GKBlack                  mesh_standard   `        KGblack.jpg                                   KG1crane-spec.jpg
    Message: Invalid line, ignoring...
```

```
20:10:04: Cache: Parsing vehicle '2008_KME_Predator.truck' yielded following messages:

ERROR (Section globals)
    Line (# 10): author Engine_tweak Eminox
    Message: Invalid line, ignoring...
```

```
20:10:05: Cache: Parsing vehicle 'Audi80Quattro.truck' yielded following messages:

ERROR (Section shocks)
    Line (# 3206): 286,17, 500.0, 500.0, 0.01, 0.02. 1.0, i
    Message: Invalid line, ignoring...
ERROR (Section shocks)
    Line (# 3207): 286,19, 500.0, 500.0, 0.01, 0.02. 1.0, i
    Message: Invalid line, ignoring...
ERROR (Section shocks)
    Line (# 3208): 287,16, 500.0, 500.0, 0.01, 0.02. 1.0, i
    Message: Invalid line, ignoring...
ERROR (Section shocks)
    Line (# 3209): 287,18, 500.0, 500.0, 0.01, 0.02. 1.0, i
    Message: Invalid line, ignoring...
ERROR (Section shocks)
    Line (# 3211): 286,80, 1000.0, 500.0, 0.01, 0.02. 1.0, i
    Message: Invalid line, ignoring...
ERROR (Section shocks)
    Line (# 3212): 287,79, 1000.0, 500.0, 0.01, 0.02. 1.0, i
    Message: Invalid line, ignoring...
```

```
20:10:05: Cache: Parsing vehicle 'John-Deere-310SJ.truck' yielded following messages:

ERROR (Section commands2)
    Line (# 1921): 186, 201,       0.1.5,      0.1.5,   1.00,    2.00,    12,    11,      i rear_coupler_in_out
    Message: Invalid line, ignoring...
ERROR (Section commands2)
    Line (# 1922): 187, 200,       0.1.5,      0.1.5,   1.00,    2.00,    12,    11,      i rear_coupler_in_out
    Message: Invalid line, ignoring...
```

```
20:10:05: Cache: Parsing vehicle 'Pete379.truck' yielded following messages:

ERROR (Section guisettings)
    Line (# 59): speedoMax 136.794
    Message: Invalid line, ignoring...
ERROR (Section props)
    Line (# 1320): 1, 0, 28,    0.50,    0.48,     0.69,   180,    180,    ;0,1999Peterbilt379-Sleeperclamps.mesh
    Message: Invalid line, ignoring...
```

```
20:10:06: Cache: Parsing vehicle 'volvofmx-6x6Sbassis.truck' yielded following messages:

ERROR (Section props)
    Line (# 1135): add_animation 5, 0, 0, source:tacho, mode:y-rotation, autoanimat
    Message: Directive 'add_animation': Unrecognized/misplaced token ' autoanimat', ignoring....
```

```
20:10:07: Cache: Parsing vehicle 'BoxSamurai.truck' yielded following messages:

WARNING (Section meshwheels)
    Line (# 883): -6
    Message: Encountered node with illegal negative number: '-6', parsing as positive '6' for backwards compatibility. Please fix as soon as possible.
ERROR (Section axles)
    Line (# 888): 3 6 7 1
    Message: Invalid property, ignoring whole line...
ERROR (Section axles)
    Line (# 889): 2 4 5 0
    Message: Invalid property, ignoring whole line...
```

```
20:10:08: Cache: Parsing vehicle 'Bobcat-S770-pipe.load' yielded following messages:

ERROR (Section globals)
    Line (# 5): importcommands\
    Message: Invalid line, ignoring...
```

```
20:10:09: Cache: Parsing vehicle 'mercedes benz tractor trailer.truck' yielded following messages:

ERROR (Section managedmaterials)
    Line (# 90): material Material.011/TEXFACE/mercedes-mirrors.dds mesh_standard    mercedes-mirrors.dds    mercedes-shiny-high.dds
    Message: Invalid line, ignoring...
```

```
20:10:10: Cache: Parsing vehicle 'CH-54-Skycrane.airplane' yielded following messages:

WARNING (Section shocks)
    Line (# 1796): 297, 305, 1, 100, 1.0, 15.0, 1.00, v
    Message: Invalid option: 'v', ignoring...
WARNING (Section shocks)
    Line (# 1797): 298, 306, 1, 100, 1.0, 15.0, 1.00, v
    Message: Invalid option: 'v', ignoring...
WARNING (Section shocks)
    Line (# 1798): 299, 307, 1, 100, 1.0, 15.0, 1.00, v
    Message: Invalid option: 'v', ignoring...
WARNING (Section shocks)
    Line (# 1799): 300, 308, 1, 100, 1.0, 15.0, 1.00, v
    Message: Invalid option: 'v', ignoring...
WARNING (Section shocks2)
    Line (# 1941): 301, 162, 1, 25, 0, 0, 1, 25, 0, 0, 0.0, 50, 1.00, io
    Message: Invalid option: 'o', ignoring...
ERROR (Section props)
    Line (# 2482): add_animation  1,  0,   0, source: rpm1, rpm2, mode: x-rotation, autoanimate
    Message: Directive 'add_animation': Unrecognized/misplaced token ' rpm2', ignoring....
ERROR (Section props)
    Line (# 2485): add_animation  1,  0,   0, source: rpm1, rpm2, mode: x-rotation, autoanimate
    Message: Directive 'add_animation': Unrecognized/misplaced token ' rpm2', ignoring....
ERROR (Section props)
    Line (# 2496): add_animation  0.4,  0,   0, source: rpm1, rpm2, mode: x-rotation, autoanimate
    Message: Directive 'add_animation': Unrecognized/misplaced token ' rpm2', ignoring....
ERROR (Section props)
    Line (# 2500): add_animation  0.1,  0,   0, source: rpm1, rpm2, mode: x-rotation, autoanimate
    Message: Directive 'add_animation': Unrecognized/misplaced token ' rpm2', ignoring....
ERROR (Section props)
    Line (# 2503): add_animation  0.3,  0,   0, source: rpm1, rpm2, mode: x-rotation, autoanimate
    Message: Directive 'add_animation': Unrecognized/misplaced token ' rpm2', ignoring....
ERROR (Section props)
    Line (# 2670): add_animation  -0.0005,  -19,   9, source: event, mode: x-rotation, autoanimate, noflip, nobounce, event:COMMANDS_03
    Message: Directive 'add_animation': Unrecognized/misplaced token ' nobounce', ignoring....
ERROR (Section props)
    Line (# 2671): add_animation   0.0005,  -19,   9, source: event, mode: x-rotation, autoanimate, noflip, nobounce, event:COMMANDS_04
    Message: Directive 'add_animation': Unrecognized/misplaced token ' nobounce', ignoring....
ERROR (Section props)
    Line (# 2672): add_animation  -0.00025,  -10,  10, source: event, mode: y-rotation, autoanimate, noflip, nobounce, event:COMMANDS_05
    Message: Directive 'add_animation': Unrecognized/misplaced token ' nobounce', ignoring....
ERROR (Section props)
    Line (# 2673): add_animation   0.00025,  -10,  10, source: event, mode: y-rotation, autoanimate, noflip, nobounce, event:COMMANDS_06
    Message: Directive 'add_animation': Unrecognized/misplaced token ' nobounce', ignoring....
```

```
20:10:10: Cache: Parsing vehicle '95_C2_LMS.truck' yielded following messages:

WARNING (Section engine)
    Line (# 22): 995.0, 2575.0, 4300.0, 4.25, 3.75,  3.20,  2.70, 1.90, 1.60, 1.45, 1.38, 1.33
    Message: Forward gears list is not terminated using '-1.0'. Please fix.
ERROR (Section shocks)
    Line (# 1093): 57, 128, 250, 100,  1.0,        0.06,       1.0,i //flaps
    Message: Invalid line, ignoring...
```

```
20:10:11: Cache: Parsing vehicle 'BoxDodgeRamTruggy.truck' yielded following messages:

WARNING (Section meshwheels)
    Line (# 758): -27
    Message: Encountered node with illegal negative number: '-27', parsing as positive '27' for backwards compatibility. Please fix as soon as possible.
ERROR (Section axles)
    Line (# 761): 21 23 22 20
    Message: Invalid property, ignoring whole line...
ERROR (Section axles)
    Line (# 762): 25 27 26 24
    Message: Invalid property, ignoring whole line...
```

```
20:10:19: Cache: Parsing vehicle 'J3SuperCub.airplane' yielded following messages:

ERROR (Section wings)
    Line (# 948): 48, 49, 48, 49, 11, 20, 11, 20, 0, 0, 0, 0, 0, 0, 0, n, 1, 0, 0, NACA0009.afl
    Message: Invalid line, ignoring...
```

```
20:10:20: Cache: Parsing vehicle 'accord.truck' yielded following messages:

ERROR (Section flares)
    Line (# 3627): position_nodes
    Message: Invalid line, ignoring...
ERROR (Section flares)
    Line (# 3628): include 0-123
    Message: Invalid line, ignoring...
ERROR (Section flares)
    Line (# 3629): exclude 90-113
    Message: Invalid line, ignoring...
```

```
20:10:21: Cache: Parsing vehicle 'DG-100.airplane' yielded following messages:

ERROR (Section soundsources2)
    Line (# 40): soundsources1
    Message: Invalid line, ignoring...
ERROR (Section soundsources2)
    Line (# 41): 30, DG-100-windout
    Message: Invalid line, ignoring...
ERROR (Section props)
    Line (# 501): AoA
    Message: Invalid source for directive 'add_animation', ignoring...
```

```
20:10:23: Cache: Parsing vehicle 'Ottawa Yard Tractor 2.0.truck' yielded following messages:

WARNING (Section engoption)
    Line (# 6): 1.7,    t,  2000,   0.25,   0.5,    0.25,
    Message: Illegal text after parameters: ",", please remove.
ERROR (Section flares)
    Line (# 1297): 74,77,75,0.6.2,0.23,l,-1,390,0.40 default
    Message: Invalid line, ignoring...
ERROR (Section flares)
    Line (# 1298): 74,77,75,0.6.2,0.91,r,-1,390,0.40 default
    Message: Invalid line, ignoring...
ERROR (Section props)
    Line (# 1346): add_animation  0.0001, 0.00001,0.4.6, source:event,mode:x-offset, autoanimate, event:COMMANDS_36,noflip
    Message: Invalid directive 'add_animation', ignoring...
```

**Comment by Lonni88** [comment]
I have the same problem as the ML-200 in the 1st picture, 
![screenshot_2016-06-06_11-13-03_1](https://cloud.githubusercontent.com/assets/17706020/15849962/8d02ae86-2c95-11e6-9866-9541fbde5fbc.jpg)

Truck used: CKD Trollback :https://stack.anotherfoxguy.com/index.php/s/kCfJWqQx153r5AP/download?path=%2F&files=%5B%22728020dee28e239dae58901489bb7aac6cb894e9_CKDTrollback.zip%22%5D

Rear suspension just go crazy jumping.

**Comment by only-a-ptr** [comment]
Okay, let me compose a TODO-list:
* https://www.dropbox.com/s/2pcsf4xojfc1pyl/55bf61f6fdab132c555dcbd4590e33a992223533_international4400trucks.zip?dl=0
* https://www.dropbox.com/s/c7klm3rg43cr9y9/182bUID-MML201.zip?dl=0
* https://www.dropbox.com/s/jy3ny8abc54f73i/4696fa1550e171f99cb4f30afd1e3da5baae6d14_c3e3UID-kurzhauber.zip?dl=0
* https://www.dropbox.com/s/kre983h5zf0uhq4/p38lightning_1.zip?dl=0
* 78ea1UID-liebherr.truck
* interstate_8ST_beta.load
* af25UID-aaadodgeviper.truck
* F650Crawler.truck
* Allis_Chalmers_HD11.truck
* miurap400.truck
* di-gokartv4.truck
* konecrane.truck
* 2008_KME_Predator.truck
* Audi80Quattro.truck
* John-Deere-310SJ.truck
* Pete379.truck
* volvofmx-6x6Sbassis.truck
* BoxSamurai.truck
* Bobcat-S770-pipe.load
* mercedes benz tractor trailer.truck
* CH-54-Skycrane.airplane
* 95_C2_LMS.truck
* BoxDodgeRamTruggy.truck
* J3SuperCub.airplane
* accord.truck
* DG-100.airplane
* Ottawa Yard Tractor 2.0.truck
* CKD Trollback :https://stack.anotherfoxguy.com/index.php/s/kCfJWqQx153r5AP/download?path=%2F&files=%5B%22728020dee28e239dae58901489bb7aac6cb894e9_CKDTrollback.zip%22%5D

**Comment by DirtGamer301** [comment]
If I'm not mistaken the Mercedes W460 had some problems somewhere after RoR 0.4.0.7: http://www.rigsofrods.org/old-forum/forums/117-Light-Vehicles/71945/page-0008.html
All the "openable parts" (beams which are supposed to extent/break for example in a crash) open automatically when spawning or driving (so the beams either extent even if there's not enough force applied to them or break to easily, but I don't know much about that so it might be something else).
Also, the wheels are nearly white, but that's a know bug with the parser making materials nearly entirely white when the material is in the managedmaterials section but doesn't have any specular file.

The Lotus Esprit may also have some bugs, but it, by what I read, is made a bit differently, so that's most likely bugs you won't encounter with any other vehicle (I can't exactly remember what happaned here, and sadly can't test it right now, I just wanted to post those two vehicles now before I forget about it again): http://www.rigsofrods.org/old-forum/forums/117-Light-Vehicles/98617/page-0001.html

**Comment by tritonas00** [comment]
Coloring problems and sound glitch with [1990 Chevy k2500 Blazer](https://www.dropbox.com/s/077fz45ot892ev2/ChevyK3500.zip?dl=1):
https://cloud.githubusercontent.com/assets/2660424/19081006/7e9d1b5e-8a61-11e6-86fb-b3d2e0647f97.png

[K100 Lowboy](https://www.dropbox.com/s/r0w233aus8o78pb/K100lowboy.zip?dl=1):
https://cloud.githubusercontent.com/assets/2660424/19082359/7b2b7dbc-8a66-11e6-8d8d-bf11b00839ae.png

**Comment by DarthCainRor** [comment]
The color on the blazer issue is a missing specular image.  And what is exactly wrong with the lowboy? That appears to be how it's always spawned, so you can load stuff up on it, as soon as it's spawned.
![screenshot_271](https://cloud.githubusercontent.com/assets/10333582/19105356/1e07c988-8aa7-11e6-81af-e5698d632a83.jpg)

**Comment by tritonas00** [comment]
Oh, i thought those two parts must be united... Ok ignore that :+1:

**Comment by ulteq** [comment]
[2012 Salf-T-Liner HDX](https://www.dropbox.com/s/yu104o1wugt3qki/a4f210f9f88e78ccaf4cac3a51d7c114b1d78ff1_HDX5.19.12b.zip?dl=1):
https://cloud.githubusercontent.com/assets/2660424/19080727/9e923b66-8a60-11e6-8b27-4f9ba943451a.png (from here: https://github.com/RigsOfRods/rigs-of-rods/pull/1123#issuecomment-251425969)

**Comment by tritonas00** [comment]
I just tested with the new parser

All fixed except P-38. Now it spawns with working engines but there is no hud and you can't control it.

**Comment by only-a-ptr** [comment]
@tritonas00 Thanks for all the testing.

I'll check it out: https://www.dropbox.com/s/kre983h5zf0uhq4/p38lightning_1.zip?dl=0

**Comment by ulteq** [comment]
Needs to be retested ones this one is merged: https://github.com/RigsOfRods/rigs-of-rods/pull/1137

**Comment by tritonas00** [comment]
About only-a-ptr list above:

BoxSamurai.truck
CH-54-Skycrane.airplane
Pete379.truck

seem to work just fine

**Comment by ulteq** [comment]
`BoxSamurai.truck` & `CH-54-Skycrane.airplane` still produce alarming warning messages in the log file.

**Comment by tritonas00** [comment]
P-38 is ok now, but as soon you accelerate, it breaks: https://www.dropbox.com/s/d4gfb3zju0lfjj0/p-38.mpg?dl=0

Other than that and 2012 Salf-T-Liner HDX, the new parser rocks for me :+1:

**Comment by ulteq** [comment]
And it did not break in 0.4.0.7?

**Comment by tritonas00** [comment]
Hm, i remembered that it worked in 0.38. But it doesn't... too many years :p 

Ok, forget P-38, probably is broken by design

**Comment by ulteq** [comment]
> Ok, forget P-38, probably is broken by design

It doesn't break if you accelerate slowly.

**Comment by tritonas00** [comment]
Also this has problems: https://www.dropbox.com/s/0kazidh61bzyd5u/TJ_s_WTJ__V5.zip?dl=1

**Comment by ulteq** [comment]
Rear axle issue when you accelerate:
`1747b3b8deb2fed6ee7d50f397e322fa78ee9d66_dakardaf.zip`
-> `6f52UID-daf.truck`

**Comment by ulteq** [comment]
`Parser::GetArgPropulsion` is different than before:

New: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/resources/rig_def_fileformat/RigDef_Parser.cpp#L4000-L4011
Old: https://github.com/only-a-ptr/ror-legacy-svn-trunk/blob/master/source/main/physics/input_output/SerializedRig.cpp#L2478

**Comment by only-a-ptr** [comment]
@ulteq You're right about `Parser::GetArgPropulsion` 
The original code propagated the truckfile value in simulation and did 3 types of check: [equality to 1](https://github.com/only-a-ptr/ror-legacy-svn-trunk/blob/0a55a993899d6a06cdc58fd98b5b675b371eb89a/source/main/physics/BeamForcesEuler.cpp#L1464), [equality to 2](https://github.com/only-a-ptr/ror-legacy-svn-trunk/blob/0a55a993899d6a06cdc58fd98b5b675b371eb89a/source/main/physics/BeamForcesEuler.cpp#L1453) and `> 0` (many different places.)

My logic resets invalid truckfile value to 0, which means all those `>0` checks behave different.

**Comment by only-a-ptr** [comment]
@tritonas00 
> Message: Argument [1] ("wrangler") is not valid float

This is just a warning, actually. The old parser silently processed text as zero, and so does this new parser. I should change the message type to WARNING. And yes, the truckfile is wrong.

**Comment by only-a-ptr** [comment]
Crane collapses on spawn: https://archives.rigsofrods.org/repo/repofiles-2nd-batch/c05175dcdb356a539164a59f57d4ba7f1fdf3775_Craneman-Liebherr-630-ECH-final.zip
![screenshot_2017-04-12_00-12-59_1](https://cloud.githubusercontent.com/assets/491088/24933225/8796ffb0-1f15-11e7-9f8d-0e583a1f372f.jpg)

**Comment by only-a-ptr** [comment]
Problem introduced in https://github.com/RigsOfRods/rigs-of-rods/pull/1271#issuecomment-306873472

**Skyvan** - spawns with incomplete cab mesh
![2017-02-14-190943_1366x768_scrot](https://cloud.githubusercontent.com/assets/2660424/22940042/3fb0db56-f2e9-11e6-99a9-18f752bcb046.png)
![obrazek](https://cloud.githubusercontent.com/assets/491088/26068612/556acd98-399e-11e7-912a-02976e59e88e.png)
Skyvan download: https://www.dropbox.com/s/8d8o3isw3rlsxys/Skyvan.zip?dl=1

**Comment by tritonas00** [comment]
Loading the first vehicle (2012 Saf-T-Liner HDX) crashes the current master: https://pastebin.com/4BaZKCzt

The fps version 2012 Saf-T-Liner HDX (FPS) works fine

https://www.dropbox.com/s/3clcpvol3jxm80b/a4f210f9f88e78ccaf4cac3a51d7c114b1d78ff1_HDX5.19.12b.zip?dl=1

**Comment by only-a-ptr** [comment]
@tritonas00 Looks like the tracking videocamera is causing issues. Testing...

**Comment by tritonas00** [comment]
latest master segfaults with those vehicles:

https://www.dropbox.com/s/klfr8gei7z41wug/dhc-3-Otter-040.zip?dl=1
https://www.dropbox.com/s/lbi9udq54a2jgwa/Lenni-MAN-TGS32350LTF1060-3434UID.zip?dl=1

**Comment by tritonas00** [comment]
mirrors don't seem to work with this: https://www.dropbox.com/s/r36vra8loxtt41d/3ff95049cf01fb9779d0d3e1f1fbe61878b194e7_tat8x8.zip?dl=1


![2017-07-05-215234_1366x768_scrot](https://user-images.githubusercontent.com/2660424/27880123-8b514f1c-61cc-11e7-8e62-14295beda826.png)

**Comment by Michael10055** [comment]
They work if you press CTRL+V to re-enable videocameras. 
![screenshot_2017-07-05_15-42-16_1](https://user-images.githubusercontent.com/11002490/27881990-ddce058e-6198-11e7-8f96-3c126aa24225.png)

**Comment by tritonas00** [comment]
Didn't know that, thanks!

**Comment by tritonas00** [comment]
Latest master crashes when skidmarks are activated and you try to create skidmarks using vehicle with flexbodywheels:

Load nhelens, spawn desperado and spin around:

>Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
RoR::Skidmark::updatePoint (this=0x0)
    at /home/babis/Downloads/rigsofrods-next-build-debug/rigsofrods-debug/src/rigs-of-rods/source/main/gfx/Skidmark.cpp:238
238	    Vector3 thisPoint = m_wheel->lastContactType ? m_wheel->lastContactOuter : m_wheel->lastContactInner;

https://pastebin.com/hVXAT86K

Disabling skidmarks in RoRConfig fixes the issue. They  are also broken ( i can't see any)

**Comment by tritonas00** [comment]
658072fbbb31316f19ef8f4a4490e9e7ef23543a doesn't have the above issue

**Comment by only-a-ptr** [comment]
> 658072f doesn't have the above issue, so #1362 broke it

@tritonas00 Thanks for checking, but it's not true - I've experienced it earlier. The trick is, the commit history isn't linear:
![image](https://user-images.githubusercontent.com/491088/28962692-c5b611be-7906-11e7-9d52-1e97ad89cd02.png)

I'm pretty sure I broke it with the 'cinecam-weight' branch where I made refactors to parser/spawner.
So far I checked the "AnotherFoxGuy/directionArrowFix" - working.

**Comment by tritonas00** [comment]
https://www.dropbox.com/s/0kazidh61bzyd5u/TJ_s_WTJ__V5.zip?dl=1 

spawns like:

![2017-08-10-133832_1920x1080_scrot](https://user-images.githubusercontent.com/2660424/29167141-eb5fae8c-7dd1-11e7-8db2-2f739b1eaaa7.png)

**Comment by Michael10055** [comment]
Renaming `ddescription` to `description` fixes the issue.

**Comment by tritonas00** [comment]
The skyvan issue is solved in latest master
![2017-08-16-144924_1920x1080_scrot](https://user-images.githubusercontent.com/2660424/29361941-5fcf4060-8292-11e7-8698-1ed13d728d95.png)

**Comment by tritonas00** [comment]
Otter and Lenni FlexObj.cpp crash also fixed in latest master
![2017-08-16-205034_1920x1080_scrot](https://user-images.githubusercontent.com/2660424/29377604-00830af0-82c5-11e7-8de8-ba8ee568d070.png)

**Comment by tritonas00** [comment]
try spawn this: https://www.dropbox.com/s/wdx2mm6y2mi8v3a/b6688609f0581c05114049e8bb578a11344ed752_tatangjosesLilgtiToyotaFJ40strechedtruggy.zip?dl=1

**Comment by tritonas00** [comment]
something is wrong with this https://www.dropbox.com/s/5isu0wka5ehn18l/SDSArgo_1.zip?dl=1

![2017-12-13-192305_1366x768_scrot](https://user-images.githubusercontent.com/2660424/33952741-67c2be8a-e03b-11e7-89ed-d9bed5fb6a09.png)
![2017-12-13-192320_1366x768_scrot](https://user-images.githubusercontent.com/2660424/33952742-67e5ae5e-e03b-11e7-8e7c-0fc21a1cf42e.png)

**Comment by only-a-ptr** [comment]
@tritonas00 Strange - OGRE can't find material `tracks/SDSargo` although it parses the script file 'SDSargo.material' without reporting problems. Anyway, this got broken in the "materialflare/skinzip/videocamera/whatever" patch, I need to resolve it.

**Comment by only-a-ptr** [comment]
@tritonas00 I found the problem with SDSArgo - there's an error in it's .material file - a missin `}` in the first material definition. Apparently OGRE tolerated this before but doesn't anymore.

Closing this because all other things are old - Skyvan is totally fine now.

**Comment by tritonas00** [comment]
please check this https://github.com/RigsOfRods/rigs-of-rods/issues/1008#issuecomment-307080609 also

**Comment by only-a-ptr** [comment]
@tritonas00 Allright

**Comment by only-a-ptr** [comment]
Allright, the mirrors are working, but not the way I wanted :laughing: 
![obrazek](https://user-images.githubusercontent.com/491088/36449344-d757f316-168a-11e8-8954-c567b50dda8e.png)

**Comment by tritonas00** [comment]
Is this a parser or vehicle issue?
![2018-03-02-165015_1920x1080_scrot](https://user-images.githubusercontent.com/2660424/36905032-ea08fbba-1e3a-11e8-949b-523e2af62547.png)

**Comment by tritonas00** [comment]
Load simple test terrain with water and the c1boat. Press UP and let it drive. After a while the game will crash. Backtrace leads to https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/physics/collision/PointColDetector.cpp#L180

Full bt: https://pastebin.com/fkWx72Qb
Boat: [C1boat.zip](https://github.com/RigsOfRods/rigs-of-rods/files/1776107/C1boat.zip)

**Comment by tritonas00** [comment]
https://www.dropbox.com/s/irv2zlinsadbuct/UnimogU5000Dakar.zip?dl=1 crashes the game:

> error loading mesh: dashboard1.mesh: OGRE EXCEPTION(2:InvalidParametersException): Couldn't read 16 bit header value from input stream. in Serializer::determineEndianness at /home/babis/Downloads/rigsofrods-next-build/ogre/src/ogre_src_v1-8-1/OgreMain/src/OgreSerializer.cpp (line 75)

**Comment by only-a-ptr** [comment]
@tritonas00 UnimogU5000Dakar.zip - Either the ZIP is corrupted or the dashboard1.mesh format is so outdated that OGRE no longer recognizes it.

**Comment by Michael10055** [comment]
`dashboard1.mesh` is supposed to be a blank dashboard mesh used for the steering wheel, OGRE apparently now has issues loading it. 
Here's a fixed mesh (in zip format since GitHub does not allow `.mesh` filetype):
[dashboard1.zip](https://github.com/RigsOfRods/rigs-of-rods/files/2033528/dashboard1.zip)

**Comment by tritonas00** [comment]
Closing this
