### ISSUE TITLE
Vehicles become broken when entering (Linux)

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#101]
Hi!

I compiled this in Archlinux, all went smooth. But when i load simple terrain and a vehicle, when i enter the vehicle it becomes broken and undrivable. This happens with all vehicles and maps i tried.

Screenshot
http://postimg.org/image/i0au02im1/

RoR.log
http://pastebin.com/N0cCsgmF

Any help please?

**Comment by schmatzler** [comment]
Probably related to this:
https://github.com/RigsOfRods/rigs-of-rods/pull/79

The latest commit that works fine for me is 570d85c, you should give that a try.

**Comment by Hiradur** [comment]
Also see #28

**Comment by Max98** [comment]
Here's a temporary fix: 
@Hiradur : I think I found the problem: calcBeams is called twice: One time in calcForcesEulerCompute and once in calcForcesEulerPrepare. Commenting out in calcForcesEulerPrepare fixed it for me.

**Comment by tritonas00** [comment]
Thanks, reverting to 570d85c fixes the issue.

**Comment by Aperion** [comment]
stability is looking good
![ror_stability](https://cloud.githubusercontent.com/assets/155682/6479701/81a2b0b6-c1fe-11e4-993e-f9ecaf6f594e.png)

**Comment by tritonas00** [comment]
Good, thank you for fixing this.
