### ISSUE TITLE
Altimeter or truck info shows wrong altitude

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#102]
I don't know which is wrong, but 2780 feet = 847,344 m or 1000m = 3280,8399 feet
![ror_2015_03_01_14_26_45_672](https://cloud.githubusercontent.com/assets/1196375/6430919/d229e4cc-c01f-11e4-9bb2-f88f04bd3016.png)

**Comment by Max98** [comment]
I noticed that with boat's depth also. Will fix.

**Comment by Max98** [comment]
Should be fixed.
