### ISSUE TITLE
aircrafts will not completely removed by "Remove current vehicle" 

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#104]
Engine sound is also active.
This was a Mig-25.
![ror_2015_03_02_19_07_23_826](https://cloud.githubusercontent.com/assets/1196375/6447120/310cf484-c110-11e4-9b4a-9e65d2d5174c.png)
red: brake dust

**Comment by Max98** [comment]
Lol'd so hard on this one xDD. Will fix!

**Comment by Max98** [comment]
Fixed!

**Comment by Speciesx** [comment]
"Remove current vehicle" is broken now.

**Comment by Max98** [comment]
How come? It's working fine for me.

**Comment by Speciesx** [comment]
when i try to remove mig25, i get second one.

**Comment by Max98** [comment]
It's working fine for me (the mig25) Can you post RoR.log?
My fix didn't involve anything that could have done that.

**Comment by Speciesx** [comment]
After recompile ror mig 25 works, but airbrakes and brake dust will still not removed .
![ror_2015_03_05_17_17_21_052](https://cloud.githubusercontent.com/assets/1196375/6509045/daa4e51c-c35c-11e4-9666-48659f5fd8b8.png)

And here Antonov 12
![ror_2015_03_05_17_16_11_176](https://cloud.githubusercontent.com/assets/1196375/6509053/eabd7c84-c35c-11e4-983f-eed649fbf8f8.png)




su-37 still crash the game
17:21:39: Added resource location 'c:\users\xxx\docume~1\rigs of rods 0.4\vehicles\su-37_2.1.zip' of type 'Zip' to resource group 'General-Reloaded-2'
17:21:39: Initialising resource group General-Reloaded-2
17:21:39: Parsing scripts for resource group General-Reloaded-2
17:21:39: Parsing script 45e43UID_SU-37.material
17:21:39: Parsing script 45e43UID_aviation_smoke.particle
17:21:39: Compiler error: unknown error in 45e43UID_aviation_smoke.particle(1): token class, tracks/particles/SUsmokeRed, unrecognized.
17:21:39: Compiler error: unknown error in 45e43UID_aviation_smoke.particle(49): token class, tracks/particles/SUsmokeBlue, unrecognized.
17:21:39: Compiler error: unknown error in 45e43UID_aviation_smoke.particle(97): token class, tracks/particles/SUsmokeWhite, unrecognized.
17:21:39: Compiler error: unknown error in 45e43UID_aviation_smoke.particle(146): token class, tracks/particles/SUtracer, unrecognized.
17:21:39: Finished parsing scripts for resource group General-Reloaded-2
17:21:39: Creating resources for group General-Reloaded-2
17:21:39: All done
17:21:39:  ===== LOADING VEHICLE: 45e43UID_SU-37.airplane
17:21:39:  == Parsing vehicle file: 45e43UID_SU-37.airplane
17:21:39:  == Parsing done OK
17:21:39:  == Parsing done OK


17:21:39:  == Validating vehicle: SU-37
17:21:39:  == Validating done OK
17:21:39:  == Validating done OK
17:21:39:  == Spawning vehicle: SU-37
17:21:39: Mesh: Loading beam.mesh.
17:21:39: D3D9 : Loading 2D Texture, image name : 'RustySteel.dds' with 5 mip map levels
17:21:39: Mesh: Loading SU-37-frontrim.mesh.
17:21:39: Texture: 45e43UID_SU-37-wheel.jpg: Loading 1 faces(PF_R8G8B8,256x64x1) Internal format is PF_X8R8G8B8,256x64x1.
17:21:39: Mesh: Loading SU-37-rearrim.mesh.
17:21:39: D3D9 : Loading 2D Texture, image name : 'flare.dds' with 5 mip map levels
17:21:39: Mesh: Loading SU-37-wingpod.mesh.
17:21:39: FLEXBODY Warning: at least one part of this mesh does not have texture coordinates, switching off texturing!
17:21:39: FLEXBODY Vertices in mesh SU-37-wingpod.mesh: 144
17:21:39: FLEXBODY show mesh
17:21:39: FLEXBODY ready
17:21:39: FLEXBODY Warning: at least one part of this mesh does not have texture coordinates, switching off texturing!
17:21:39: FLEXBODY Vertices in mesh SU-37-wingpod.mesh: 144
17:21:39: FLEXBODY show mesh
17:21:39: FLEXBODY ready
17:21:39: Mesh: Loading SU-37-engine.mesh.
17:21:39: FLEXBODY Warning: at least one part of this mesh does not have texture coordinates, switching off texturing!
17:21:39: FLEXBODY Vertices in mesh SU-37-engine.mesh: 50
17:21:39: FLEXBODY show mesh
17:21:39: FLEXBODY ready
17:21:39: FLEXBODY Warning: at least one part of this mesh does not have texture coordinates, switching off texturing!
17:21:39: FLEXBODY Vertices in mesh SU-37-engine.mesh: 50
17:21:39: FLEXBODY show mesh
17:21:39: FLEXBODY ready
17:21:39: Mesh: Loading SU-37-Body.mesh.
17:21:39: D3D9 : Loading 2D Texture, image name : '45e43UID_SU-37-windows.dds' with 5 mip map levels
17:21:39: Can't assign material SU-37-dash to SubEntity of flexbody-t0-4 because this Material does not exist. Have you forgotten to define it in a .material script?
17:21:39: FLEXBODY Vertices in mesh SU-37-Body.mesh: 1306
17:21:39: FLEXBODY show mesh
17:21:39: FLEXBODY ready
17:21:39: D3D9 : Loading 2D Texture, image name : 'greenflare.dds' with 5 mip map levels
17:21:39: D3D9 : Loading 2D Texture, image name : 'redflare.dds' with 5 mip map levels
17:21:39: Mesh: Loading nozzle.mesh.
17:21:39: D3D9 : Loading 2D Texture, image name : 'nozzle.dds' with 5 mip map levels
17:21:39: Mesh: Loading abflame.mesh.
17:21:39: D3D9 : Loading 2D Texture, image name : 'abflame.dds' with 5 mip map levels
17:21:39: Mesh: Loading SU-37-Canopy.mesh.
17:21:39: Mesh: Loading SU-37-LRBaydoor.mesh.
17:21:39: Mesh: Loading SU-37-RRBaydoor.mesh.
17:21:39: Mesh: Loading SU-37-FBaydoor.mesh.
17:21:39: Mesh: Loading SU-37-Airbrake.mesh.
17:21:39: Mesh: Loading SU-37-rearstrut-cover.mesh.
17:21:39: Texture: 45e43UID_SU-37-struts.jpg: Loading 1 faces(PF_R8G8B8,512x512x1) Internal format is PF_X8R8G8B8,512x512x1.
17:21:39: Mesh: Loading SU-37-rearstrut.mesh.
17:21:39: Mesh: Loading SU-37-frontstrut.mesh.
17:21:39: Mesh: Loading SU-37-frontstrut-c.mesh.
17:21:39: Texture: 45e43UID_SU-37-light_0.png: Loading 1 faces(PF_R8G8B8,110x110x1) with 5 generated mipmaps from Image. Internal format is PF_X8R8G8B8,110x110x1.
17:21:39: Texture: 45e43UID_SU-37-light_1.png: Loading 1 faces(PF_R8G8B8,110x110x1) with 5 generated mipmaps from Image. Internal format is PF_X8R8G8B8,110x110x1.
17:21:39: MaterialFunctionMapper: replaced mesh material SU-37-lights with new new material SU-37-lights_mfb_t0 on entity Ogre/MO11
17:21:39: MaterialFunctionMapper: replaced entity material SU-37-lights with new new material SU-37-lights_mfb_t0 on entity Ogre/MO11
17:21:39: OGRE EXCEPTION(2:InvalidParametersException): Cannot find required template 'tracks/particles/SUsmokeRed' in ParticleSystemManager::createSystem at ..\..\OgreMain\src\OgreParticleSystemManager.cpp (line 327)
17:21:39:  == RigSpawner: ERROR (Keyword particles) An unknown exception has occured
17:21:39: OGRE EXCEPTION(2:InvalidParametersException): Cannot find required template 'tracks/particles/SUsmokeRed' in ParticleSystemManager::createSystem at ..\..\OgreMain\src\OgreParticleSystemManager.cpp (line 327)
17:21:39:  == RigSpawner: ERROR (Keyword particles) An unknown exception has occured
17:21:39:  == RigSpawner: WARNING (Keyword ~Unknown~) vehicle uses no GUID, skinning will be impossible
17:21:39: TOTAL VEHICLE MASS: 20920 kg

**Comment by Max98** [comment]
The Su-37 that you are using is very old. I've updated it in the repository and I'm waiting for it to get approved. Will fix the air breaks but the dust thing, It will go by it self if i'm not wrong.

**Comment by Speciesx** [comment]
Even after few minutes the dust is still active. 

![ror_2015_03_05_18_04_08_379](https://cloud.githubusercontent.com/assets/1196375/6509927/f4b1df7c-c362-11e4-973b-95fef85cd624.png)
![ror_2015_03_05_18_07_33_722](https://cloud.githubusercontent.com/assets/1196375/6509926/f4b1e562-c362-11e4-8c08-841bfd12f1c7.png)

**Comment by Speciesx** [comment]
I must correct me again, sometimes airplanes like 767, Concorde and mig25 will be duplicated, instead of removed and after enter Antonov 12 or PittsSpecial the screen is black.

**Comment by Max98** [comment]
Hmm interesting.

**Comment by Max98** [comment]
I spawned around 5 mig 25s and 2 Su37s and I didn't get the duplicated thing, are you sure you are pressing "Remove current vehicle" and not the button over it "Reload current vehicle"?

**Comment by Speciesx** [comment]
Ups, it was indeed "Reload current vehicle" :D

**Comment by Max98** [comment]
Hahahah. :P

**Comment by Speciesx** [comment]
But the bug with the black screen remains.

**Comment by Max98** [comment]
The bug with the black screen is something else related to the physics engine which started happening after the merges of @Aperion 
It will be fixed soon.
