### ISSUE TITLE
Ingame keymapping not working

### ISSUE THREAD

**Issue by Hiradur** [RigsOfRods/rigs-of-rods#1049]
Ingame keymapping is unfinished and doesn't work. We should either make it unaccessible, fix it,remove it or make clear it doesn't work.

**Comment by Hotrod55** [comment]
It's also deceiving since the Configurator's `Config` tab says you can edit the controls using it::
![config](http://i.imgur.com/EoSnuKH.png)

**Comment by Hiradur** [comment]
Thanks for pointing that out.

**Comment by tritonas00** [comment]
no rorconfig now as far i can tell

**Comment by tritonas00** [comment]
>remove it

It is removed, there isn't ingame keymapping, is it?

**Comment by CuriousMike56** [comment]
> 
> 
> > remove it
> 
> It is removed, there isn't ingame keymapping, is it?

Correct, the settings UI does not include anything for keymapping.

**Comment by tritonas00** [comment]
https://github.com/RigsOfRods/rigs-of-rods/pull/2749
