### ISSUE TITLE
lose connection to server causing crash

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1052]

**Comment by only-a-ptr** [comment]
How does the "crash" look like? Does RoR just drop dead, or is there any error dialog?

Also, please post RoR.log

**Comment by AnotherFoxGuy** [comment]
Reproducing is very easy:
* Start a LAN ror-server.
* Connect to the server.
* Shut down the server while the game is connected to it.

**Comment by AnotherFoxGuy** [comment]
**Screenshot:**
![csrss_2016-08-22_11-03-30](https://cloud.githubusercontent.com/assets/9480940/17849233/2632769c-6858-11e6-84ed-50656f5cad3b.png)
The game crashes after that

**RoR log**:  http://pastebin.com/60AEeTrB

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy Thanks. Makes sense.

Afaik RoRNet doesn't have any message to notify clients about server shutdown. I'll need to add that.

Furthermore, there isn't really a reason for RoR to shutdown after server disconnects, it's just programmed that way. I'll make it go back to menu instead (with an error message).

**Comment by only-a-ptr** [comment]
> only-a-ptr assigned only-a-ptr just now
Clicked too fast :laughing:

**Comment by ulteq** [comment]
-> https://github.com/RigsOfRods/rigs-of-rods/commit/77e1ef08ecb31d1efb4c8fe627fda81e244ffc04
