### ISSUE TITLE
Sound Repeating Random Glitch

### ISSUE THREAD

**Issue by Stewie140** [RigsOfRods/rigs-of-rods#1054]
I hear this constant buzzing that comes out of the back whenever I drive for 1 minute in any vehicle in NightBuilds 81 and up, as well as 0.4.6

**Comment by ulteq** [comment]
Did you also have that issue in 0.4.5.1?

**Comment by Stewie140** [comment]
No I did not. In 0.4.5.1, the sound is perfectly fine; no glitches whatsoever.

**Comment by SPCvergenens2190** [comment]
Having a similar problem when it comes to sound with NightBuild 104. Whenever I kick certain vehicles into reverse the backup alarm has a tendency glitch and replay the first bit of the sound over and over and not play as specified in the zip. I've tried replacing the files and no good. Might be a .truck issue but didn't give me problems in previous NightBuilds.

**Comment by Stewie140** [comment]
Strange. I've had problems in builds 81+, but in previous ones it was fine.

**Comment by WillyB1337** [comment]
I've also had this issue for a while.

It actually fixed itself when I cleaned the cache then regen manually by the Configurator.
The Wahoo boat I used for testing is working fine now.
Ty @Hotrod55 for the reference.

**Comment by Michael10055** [comment]
For me, this glitch happens a lot. For example, the 2014 Ford I'm working on loops the break sound: https://streamable.com/j44g It stops looping if i reload the vehicle (CTRL+SHIFT+R)

**Comment by ulteq** [comment]
We need to find out which commit introduced this bug.
