### ISSUE TITLE
Allow vehicles to rope to themselves

### ISSUE THREAD

**Issue by RustyMonster** [RigsOfRods/rigs-of-rods#1055]
As seen in this bugfix:
https://github.com/RigsOfRods/rigs-of-rods/pull/589
Mods can no longer tie down to themselves. This feature being disabled breaks some mods, one being a Model T convertible that has ties between the folding windshield and roof that keep them from flopping around. The feature was seemingly added to keep Gabester's vehicles from roping to themselves. Wouldn't a better idea be to just remove the offending ties from his vehicles vs changing the entire game for one modder's creations? I can provide screenshots of the Model T mentioned above if needed.

**Comment by Hotrod55** [comment]
Maybe there could be a extra ties/ropes/nodes option that allows it to tie to itself?

**Comment by ulteq** [comment]
> Maybe there could be a extra ties/ropes/nodes option that allows it to tie to itself?

Yes, but that way old vehicle remain broken.
