### ISSUE TITLE
Mouse cursor goes behind the aircraft dashboard overlay

### ISSUE THREAD

**Issue by Aivar-RoR** [RigsOfRods/rigs-of-rods#1063]
Using 0.4.6 with the latest nightbuild (105).
When in an aircraft, the mouse cursor is behind the dashboard overlay, but should be on top. 
All the buttons can be pressed with the mouse, but it is quite annoying as you can't exactly see where the cursor is.

![cursor_bug1](https://cloud.githubusercontent.com/assets/11720273/16357862/18222888-3b0b-11e6-922e-595a381d39af.jpg)

**Comment by Speciesx** [comment]
https://github.com/RigsOfRods/rigs-of-rods/issues/697

**Comment by Aivar-RoR** [comment]
@Speciesx For some reason the issue didn't pop up while searching. Closing as it is a duplicate.
