### ISSUE TITLE
Move Hydrax out of the source tree

### ISSUE THREAD

**Issue by Hiradur** [RigsOfRods/rigs-of-rods#1065]
Right now Hydrax is included in the source tree. This is bad design because it means we have to maintain it ourselves and can not profit from upstream changes without incorporating them in ourselves. Hence I propose to move Hydrax outside of the RoR source tree. The problem is that there doesn't seem to be an actively developed Hydrax fork right now and Max98 applied various patches to our Hydrax which are not in the latest official release.

IMO the best way to deal with this would be:
- create our own Hydrax fork inside the ORG like we did for Caelum and Paged Geometry
- For this fork we should import a Hydrax repo with full history so one can see which changes are in that fork and which are only available in the version included in RoR's source tree
- Apply any missing patches manually

**Comment by Speciesx** [comment]
https://bitbucket.org/ogreaddons/hydrax
https://github.com/imperative/CommunityHydrax

**Comment by Hiradur** [comment]
The problem with the OgreAddons repository is that they pulled out Hydrax of the Ogitor source tree where it was integrated just like it's in RoR. So there is no history and without history we can't really tell which version it is and which patches it received. CommunityHydrax also has no commit history but it's probably based on the latest release of Hydrax with a few patches applied.

**Comment by Speciesx** [comment]
As far i know, Hydrax was never available in repo.

**Comment by Hiradur** [comment]
In this case CommunityHydrax is probably the way to go.
