### ISSUE TITLE
Angelscript broken in NB 113

### ISSUE THREAD

**Issue by WillyB1337** [RigsOfRods/rigs-of-rods#1067]
Hello there!

I've recently updated my RoR from 0.4.6 RC3 to Night Build 113.

The script  PolicePursuit.as taken from AImapsTest.zip doesn't work anymore.
The script worked fine in the other version!

In the Angelscript.log here, I get few errors.
[Angelscript.txt](https://github.com/RigsOfRods/rigs-of-rods/files/351180/Angelscript.txt)

**Comment by Hotrod55** [comment]
@AnotherFoxGuy reworked his AI (#995) which is why the old AI doesn't work anymore. He hasn't uploaded any new maps yet.

**Comment by Hiradur** [comment]
Closing as 3rd party content bug.

**Comment by AnotherFoxGuy** [comment]
@Hotrod55 I've uploaded an updated version of your bajarama-ai.as [here] (https://gist.github.com/AnotherFoxGuy/8171bf3f6e7456f7dc5a96836c4df910)

**Comment by Hotrod55** [comment]
Thanks! 👍

**Comment by WillyB1337** [comment]
I've tried the new AI thingy for Bajarama V2.

Unfortunately, Nothing is happening when I load the BajaramaV2.terrn2.
I'm using NB 113. Should I wait for the next Night Build to get the script to work?

Anyway. This thing look promising ;)

**Comment by Hotrod55** [comment]
You need to wait for #1056 to be merged into the master branch for the next NightBuild or compile from source yourself with that pull request merged.
