### ISSUE TITLE
Vehicle Info not showing completly

### ISSUE THREAD

**Issue by WillyB1337** [RigsOfRods/rigs-of-rods#1068]
Hello again...

This issue is actually there since a few Night Build.

I want you developers to make this issue a priority.
![image](https://cloud.githubusercontent.com/assets/16364065/16639430/962bc10c-43bd-11e6-818f-018653128b64.png)

There's a few information such as damage %.

**Comment by Hotrod55** [comment]
Looks fine on my source builds:
![ror_2016-07-06_22-05-09](https://cloud.githubusercontent.com/assets/11002490/16640434/06a133b0-43c6-11e6-9b3e-01ea758c89cd.png)
I think there is a font issue in the way @AnotherFoxGuy builds his binaries.

**Comment by WillyB1337** [comment]
He should take a look at that then.

Is your build more recent than the Night Build?

**Comment by Hotrod55** [comment]
It's actually 1 commit behind atm as I haven't bothered to rebuild. The text in the vehicle info screen has always been the same for me.

**Comment by Hiradur** [comment]
Perhaps related to the font and how it's used? You can see the fonts are different when looking at the 'l'. I think @AnotherFoxGuy uses a different font for NightBuilds.

**Comment by AnotherFoxGuy** [comment]
It seems to be caused by the font used by the translations that have too much [line spacing](http://practicaltypography.com/line-spacing.html).
The translations need to use a different font since the standard font doesn't support special characters.

**Comment by WillyB1337** [comment]
@AnotherFoxGuy I already know that especially to show accents in French language.
At least, try to add a slider or optimize the size of the box for the whole text ;)
