### ISSUE TITLE
separating wheel N/B on N/B count

### ISSUE THREAD

**Issue by chester819** [RigsOfRods/rigs-of-rods#1069]
it is possible to separate the wheels N/B on the N/B count  so that it cannot affect Maximum limit of N/B when creating a vehicle?

**Comment by disloyalpick** [comment]
I'm pretty sure the max. n/b limit pertains to the number of nodes in the frames n/b I'm not sure if I'm right. Someone please correct me if I'm wrong.

**Comment by chester819** [comment]
Maximum Beam Count is 5000 and the Maximum Node Count is 1000

**Comment by ulteq** [comment]
We should probably just increase the maximum node and beam counts.

**Comment by chester819** [comment]
do you think you can increase the node count up to 10000 or higher? but i think it will affect the performance of the game itself...

**Comment by Michael10055** [comment]
Afaik, RoR always allocates memory for 1k nodes and 5k beams regardless of how many your structure has. So increasing the limit would make the game use a lot more memory, but I could be wrong.

**Comment by only-a-ptr** [comment]
Michael10055 is right - RoR uses pre-allocated arrays for nodes (1000 items) and beams (5000 items).

I'll create a test build where I'll replace the static-sized arrays with dynamic ones. It shouldn't have any side effects

**Comment by Michael10055** [comment]
Fixed by #1343
