### ISSUE TITLE
Restore the old controls configuration

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1070]
I don't know why it was removed, but the old ror 0.36 controls configuration still works pretty good.

![1](https://cloud.githubusercontent.com/assets/1196375/16728792/d1f9192e-4768-11e6-9be2-053ec7e9616a.PNG)
![2](https://cloud.githubusercontent.com/assets/1196375/16728793/d2b987d6-4768-11e6-9fd3-496e48758044.PNG)
![3](https://cloud.githubusercontent.com/assets/1196375/16728794/d39c7cb2-4768-11e6-98ef-b5af02910184.PNG)

**Comment by disloyalpick** [comment]
:+1:

**Comment by only-a-ptr** [comment]
> I don't know why it was removed, but the old ror 0.36 controls configuration still works pretty good.

IDK, really, but it probably got removed when main menu was introduced and we thought RoRConfig will get obsoleted soon.

And yes, it shouldn't have been removed, at least not until there's a replacement.

**Comment by Speciesx** [comment]
@only-a-ptr 
>IDK, really, but it probably got removed when main menu was introduced and we thought RoRConfig will get obsoleted soon.

I think tdev has removed this ror in ror 0.38.

**Comment by disloyalpick** [comment]
0.37.126 was the last version to have the functional controller remapping .

**Comment by only-a-ptr** [comment]
I'll try restoring the code. It should be still working.

**Comment by only-a-ptr** [comment]
BUMP! https://github.com/only-a-ptr/rigs-of-rods/commit/e64f124635f46c899eed29964e6b31f87412994b

**Comment by only-a-ptr** [comment]
It's going pretty well, I just needed to reconnect a few wires.
![rorconfig-input-wip](https://cloud.githubusercontent.com/assets/491088/18491029/dc2f6406-7a04-11e6-82da-8476a6dba194.png)


The add/delete buttons are not working yet, and I'm not quite certain what should they do. I'm installing 0.35 to take a look how it worked back then.

**Comment by Michael10055** [comment]
The add/delete buttons simply allowed you to add/delete any event to your input.map: (0.36.0)
![1](http://i.imgur.com/2jSuXD8.png)

**Comment by tritonas00** [comment]
no rorconfig now so is this valid?
