### ISSUE TITLE
Sound glitches

### ISSUE THREAD

**Issue by WillyB1337** [RigsOfRods/rigs-of-rods#1073]
I found out in multiple vehicles that whatever sound can get glitched out. 

Unfortunately, I'm unable to upload a ZIP here.

I uploaded it on my OneDrive : https://1drv.ms/u/s!Av9BygMxjH5Ewwd2dgrGLtL4iKv4

The boat I used to demonstrate this : Wahoo.

Sorry for the inconvenience :(

**Comment by Hotrod55** [comment]
#1054
