### ISSUE TITLE
non-straight Skidmarks

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#1079]
![screenshot_2016-07-16_18-16-29_1](https://cloud.githubusercontent.com/assets/12358849/16895842/7073ec3e-4b81-11e6-9521-f53e20c1a5d4.jpg)
Happens with every vehicle on every map, latest using 0.4.6 with the latest NightBuild. Others experience this issue, too.

**Comment by Hotrod55** [comment]
Related to #539

**Comment by DirtGamer301** [comment]
I'm just going to add it here as it's also related to skidmarks and therefore related to both issues and unimportant (I guess), just so you know about it.
Skidmarks will be saved with the terrain.
To reproduce:
Load a terrain, do some skidmarks, go back to main menu/change map, load the same terrain again, the skidmarks from before are still there.

**Comment by Michael10055** [comment]
@DirtGamer301 Please create a new issue ticket for this.
