### ISSUE TITLE
TOD lag

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#1080]
There's some huge lag when changing the time of the day, mainly when you use shift to accelerate the change.

**Comment by Hiradur** [comment]
This only happens when OGRE is built without boost and may not be an issue in RoR itself.

**Comment by DirtGamer301** [comment]
Ok.
Is that a problem I can fix on my PC myself by installing something for example?

**Comment by Hotrod55** [comment]
No, you have to build RoR + OGRE (with Boost) yourself.

**Comment by tritonas00** [comment]
old ogre 1.9 issue without boost

its fixed now
