### ISSUE TITLE
Recieved this crit error upon opening my game.

### ISSUE THREAD

**Issue by shadeslayer240** [RigsOfRods/rigs-of-rods#1083]
![rigs error](https://cloud.githubusercontent.com/assets/20520615/16922579/2cf115a4-4ce4-11e6-91fc-6e3f2b1ed278.PNG)

**Comment by Hiradur** [comment]
`worldofwarships.exe`? Are you at the correct place?

**Comment by shadeslayer240** [comment]
sorry, I sent the wrong error pic.

**Comment by Hiradur** [comment]
You need to run RoRConfig at least once.

**Comment by shadeslayer240** [comment]
Oh, ok, thanks. Am I allowed to ask where to find more maps/vehicles? I only have two test maps and two vehicles.

**Comment by AnotherFoxGuy** [comment]
Here: http://forum.rigsofrods.org/forum-6.html
And here: http://forum.rigsofrods.org/thread-107.html
