### ISSUE TITLE
Linux Water Upside Down

### ISSUE THREAD

**Issue by adriansnetlis** [RigsOfRods/rigs-of-rods#1084]
Just recorded a video of a little issue that I have in Rigs of Rods since I first download it a few months ago. This issue is still there today.

https://www.youtube.com/watch?v=sVn1EqRTGTs&feature=youtu.be

Basicly the water reflection and refraction textures are flipped upside down.

**Comment by Hiradur** [comment]
Closing as duplicate of #986
