### ISSUE TITLE
Crash when going back to menu when DOF is enabled

### ISSUE THREAD

**Issue by WillyB1337** [RigsOfRods/rigs-of-rods#1086]
`When I press Return to menu immediately after spawning on the map, the game takes me back to the menu but 1 second later, the game crashes without any error.

The Change Map button does also the same thing.

The RoR.log doesn't show fatal errors during the sequence.

[RoR.txt](https://github.com/RigsOfRods/rigs-of-rods/files/372155/RoR.txt)

**Comment by ulteq** [comment]
> When I press Return to menu

Is it a button that you press? Which one is it by default?

**Comment by tritonas00** [comment]
Can't reproduce it.

**Comment by Michael10055** [comment]
I can't reproduce it either.

**Comment by only-a-ptr** [comment]
This issue refers to an old nightly. Apparently the issue was resolved already.

**Comment by AnotherFoxGuy** [comment]
This only happens when DOF (depth of field) is enabled
