### ISSUE TITLE
Dynamic Signs are broken

### ISSUE THREAD

**Issue by DarthCainRor** [RigsOfRods/rigs-of-rods#1088]
So I've been experimenting with an old, ancient function to try and get street name signs on the Community map, without needing to texture every single sign individually. I've gotten the signs to work on version .38, but when I try with the exact same set up in .4.6 I get an error that states `ODEF: problem with drawTextOnMeshTexture command: mesh texture not found: DCsign-road.odef : drawTextOnMeshTexture  0.1, .9, .6, .6,   1, 1, 1, 1,    l, BlueHighway {{argument1}}`

I only know of one old "official" map, North Saint Helens, that used the concept way back, but the font it used was removed. I talked with Secondking about it, and he said the font was removed due to copywrite issue, and that the function uses Angelscript, which could be the cause of the issue

**Comment by Hiradur** [comment]
I removed BlueHighway for licensing reasons (see #450) but I think dynamic signs were already broken before that. I'm not sure though (it could also be a problem with the OpenGL renderer), could someone check in which version they last worked?

**Comment by DarthCainRor** [comment]
The font I used is still inside the OgreCore for my experimental build at least, but it also still gives the same error when using VeraMono. 
`11:27:45: Mesh: Loading DCsign-road.mesh.
11:27:45: WARNING: DCsign-road.mesh is an older format ([MeshSerializer_v1.41]); you should upgrade it as soon as possible using the OgreMeshUpgrade tool.
11:27:45: ODEF: problem with drawTextOnMeshTexture command: mesh texture not found: DCsign-road.odef : drawTextOnMeshTexture  0.1, .9, .6, .6,   1, 1, 1, 1,    l, VeraMono {{argument1}}` I only have .38, .4.6 and an off branch of .4.6 using some of the experimental things installed, but it works in .38 and not the newest ones. I'm using directX not openGL

**Comment by DarthCainRor** [comment]
Also it'd be nice if once this got working again if there was a way to specify the exact font size, rather than being forced to use the default tiny text on normal 1024 or 2048 square textures.

**Comment by AnotherFoxGuy** [comment]
I will take a look at it, do you have an example?

**Comment by DarthCainRor** [comment]
I can send you a sample sign I was working on that works in .38 to test with, if you'd like.

**Comment by DarthCainRor** [comment]
http://www.mediafire.com/download/915tj5hulbi6eaa/signtest.zip

it wont let me upload the .zip here so here it is.

hould look similar to this once placed. Texture is temporary, and tiny for this test, as font size is relative to texture dimensions.
![screenshot_270](https://cloud.githubusercontent.com/assets/10333582/18160505/6ced3c46-6ff3-11e6-8424-a9888fa496d0.jpg)
