### ISSUE TITLE
Could not open Rigs of Rods 0.4.5.1

### ISSUE THREAD

**Issue by Toyota-Camry** [RigsOfRods/rigs-of-rods#1097]
Hi, I am having an issue whilst trying to open RoR 0.4.5.1. despite trying to open up RoRConfig.exe, the game did not open. I suspect that the program may be missing a configuration file. Can anyone help me in solving this issue?

**Comment by Dogy144** [comment]
Does it give any error messages?

**Comment by Toyota-Camry** [comment]
It did not show any error message, but the program did not start.

**Comment by only-a-ptr** [comment]
Hello.

RoRConfig.exe writes it's own log: MyDocuments/Rigs of Rods 0.4/logs/configurator.log. Look for it please.

**Comment by Toyota-Camry** [comment]
My current OS is Windows 10 Home Edition 64-bit

**Comment by Toyota-Camry** [comment]
The Following is what the log showed me:
7:20:41 PM: log started
7:20:41 PM: searching languages in languages
7:20:41 PM: no Languages found!
7:20:41 PM: asking system for default language.
7:20:41 PM:  error getting language information!

**Comment by only-a-ptr** [comment]
Very interesting, I don't think anyone experienced this before. Thanks for the info.
