### ISSUE TITLE
Right side turning signals not blinking

### ISSUE THREAD

**Issue by Aivar-RoR** [RigsOfRods/rigs-of-rods#1098]
As the title says, right turning signals do not blink in the latest Nightbuild (120). Once you turn the right blinker on it does not blink, but is a solid light instead. The left one works correctly.
Materialflares are not affected by this bug.

Try the Scania wrecker, Agora bus, DAF semi.

**Comment by Aivar-RoR** [comment]
Managed to fix the issue with a workaround by adding the controlnumber, blinkdelay, size and material to the flares line. 
Before:
0, 1, 2, 0.80, 0.05, r
After:
0, 1, 2, 0.80, 0.05, r, -1, 500, -1 default

**Comment by ulteq** [comment]
Might be fixed by this: https://github.com/RigsOfRods/rigs-of-rods/pull/1093
