### ISSUE TITLE
Visible shocks and hydros invisible at spawn

### ISSUE THREAD

**Issue by Aivar-RoR** [RigsOfRods/rigs-of-rods#1099]
When spawning a vehicle that has visible shocks or hydros (either have no tag or have an 'n' tag in the .truck file), the shocks and hydros are invisible. Once you repair the vehicle (either with Backspace or I) the shocks/hydros become visible. See attached screenshot.
Happens with all spawning methods (menu, truckshop, terrain file). Using latest Nightbuild (120).

Try the Scania wrecker, Agora bus, DAF semi.
![1](https://cloud.githubusercontent.com/assets/11720273/17649339/a773c274-623b-11e6-9b21-a04edd9c4dee.jpg)

**Comment by only-a-ptr** [comment]
@Aivar-RoR Does AgoraBus or DafSemi even have any visible shocks/hydros? I never noticed any.

**Comment by Aivar-RoR** [comment]
@only-a-ptr They do. 
Attached a few detailed screenshots to this comment:
![agora-issue1](https://cloud.githubusercontent.com/assets/11720273/17849928/ac6af72e-6863-11e6-86b6-3bdd630e8259.png)
![dafsemi-issue1](https://cloud.githubusercontent.com/assets/11720273/17849938/b07859e2-6863-11e6-8257-0bd6f89f9db1.png)

**Comment by only-a-ptr** [comment]
@Aivar-RoR thanks, I'm on it.
