### ISSUE TITLE
Steering wheel not rotating when animators are used

### ISSUE THREAD

**Issue by Aivar-RoR** [RigsOfRods/rigs-of-rods#1100]
When a truck has the default dashboard (dashboard.mesh or dashboard-small.mesh), the steering wheel does not rotate.
Using latest Nightbuild (120).

Tried with the Agora bus from this thread:
http://forum.rigsofrods.org/thread-424.html
Also attached to the next post.

**Comment by Aivar-RoR** [comment]
This issue seems to be caused by animators. The 0.4 version of the bus causes the issue.
As soon as the animators line gets commented out, the steering wheel rotates correctly.

animators
;extends with actual vehicle speed
31, 265, 0.8, airspeed | inv

I'm attaching the buses .zip from the aforementioned thread over here, because I'm scrapping the version with animators until this issue gets fixed.
[Aivar-agora-d3-ver2.zip](https://github.com/RigsOfRods/rigs-of-rods/files/428428/Aivar-agora-d3-ver2.zip)

**Comment by ulteq** [comment]
Most likely caused by this: https://github.com/RigsOfRods/rigs-of-rods/pull/904

**Comment by ulteq** [comment]
What is the animator line supposed to do?
```
31, 265, 0.8, airspeed | inv
```

**Comment by Aivar-RoR** [comment]
Once the vehicle is in motion, the animator extends with the vehicle's actual speed (i.e. airspeed). The animator then extends a trigger (defined between the same nodes as the animator) that blocks the bus doors from being opened. 
There were no problems with the steering wheel in 0.39.5 and 0.4.0.7 (the versions I have installed atm) with this animator line.
