### ISSUE TITLE
Camera keys are inverted in the lastest build

### ISSUE THREAD

**Issue by WillyB1337** [RigsOfRods/rigs-of-rods#1105]
Hello there.
I found out really clearly that the keys for the Camera on the Numpad are Inverted
**EX : Pressing NUMPAD 4 (Turn camera left) turn right instead**

This issue also happens with the input file for my XBOX 360 controller.
I've tried to copy the default input.map from the Programs Files Directory.
I also tried a backup input.map I always keep, it still does the same thing.

Here's what in the **original input.map**

> CAMERA_ROTATE_DOWN             Keyboard             NUMPAD2 
> CAMERA_ROTATE_LEFT             Keyboard             NUMPAD4 
> CAMERA_ROTATE_RIGHT            Keyboard             NUMPAD6
> CAMERA_ROTATE_UP               Keyboard             NUMPAD8

**Comment by FuturzMinion** [comment]
I don't like the way it works now, if I'm in the outside view and I press 4 on the numberpad, it moves right now. If I'm inside and I press 4, it moves right.

**Comment by ulteq** [comment]
And how should it be like?

**Comment by FuturzMinion** [comment]
It should be like: 4 is look left, 8 is look up, 2 is look down, and 6 is look right. That is not how it is in the game right now. It doesn't feel right being inverted.

**Comment by vido89** [comment]
Its been fixed in latest build

**Comment by ulteq** [comment]
I'm confused now.

**Comment by ulteq** [comment]
@WillyB1337, what is wrong with the way it currently is?

If the camera is on the rotation center, then right means turn camera right (e.g. look to the right).

If the camera is off the rotation center, then right means rotate the camera to the right (e.g. look to the left).

I will leave it as is, unless most people vote against it.

**Comment by Michael10055** [comment]
The camera rotation works exactly the same as all previous versions of RoR. I don't understand why it needs to be changed.

**Comment by Michael10055** [comment]
Old issue, there's nothing wrong with the current camera keys.
