### ISSUE TITLE
Ogre Exception: "No state found for animation named '...' "

### ISSUE THREAD

**Issue by Dogy144** [RigsOfRods/rigs-of-rods#1106]
### Steps to reproduce
Using NightBuild(?) from http://forum.rigsofrods.org/thread-2-post-3.html#pid3 (bottom of post).

1. Joined the "Official: AFG CommunityMap server" from the network tab of the RoRConfig.
2. Spawn any vehicle with RoRBot. (Ex. DAF Semi)

### Expected behaviour
Game crashes with this error. (Image below.)

### System configuration
OS: Windows 10 Pro 64-Bit
Renderer used: DirectX

### Additional information, logs and screenshots (optional)
RoR.log: http://pastebin.com/LvmHAz0k
http://i.imgur.com/FAESAur.png

---
Edit:
It appears to be more than one animation. From Gitter:
>WillyB @WillyB1337 13:04
>Well A soon as I do a side step, the game crashes. Seem like the animations is broken/missing

>No state found for animation named 'Side_step' in AnimationStateSet::getAnimationState at D:\ror\dev\dependencies\src\Ogre\ogre_src_v1-9\OgreMain\src\OgreAnimationState.cpp (line 330)

**Comment by vido89** [comment]
Same here, to reproduce 
`No state found for animation named 'Driving'`
just use Daf Semi truck

**Comment by AnotherFoxGuy** [comment]
I assume that you are using 0.4.6.0-NB-7-dwdvemwt ?
That means that you are using the pull requests build from #1076

**Comment by Dogy144** [comment]
>I assume that you are using 0.4.6.0-NB-7-dwdvemwt ?
Yes

**Comment by AnotherFoxGuy** [comment]
From the Gitter chat:
> AnotherFoxGuy Could you try to delete all the content of the Nightbuild folder and unzip the Build.zip again and see if you get the same error?

> Dogy144  that fixes the error

>WillyB1337 Me either! 
**Problem solved**
