### ISSUE TITLE
0.37 "Error 7" when spawning a certain truck

### ISSUE THREAD

**Issue by Mr-Self-Destruct** [RigsOfRods/rigs-of-rods#1107]
In Rigs of Rods 0.37, I have 2 trucks that, when spawned in 0.37, give this error message.

![image](https://cloud.githubusercontent.com/assets/21160971/17839506/cc55719c-67b7-11e6-8e67-5d699a0ea751.png)

I've posted help questions on Sim Monsters but have gotten no luck. It works perfectly in 0.4.6, but the file is posted in 0.37 and I don't want broken trucks. Any help?

Here are the files.

http://www.mediafire.com/download/a1ql1htdecldbqn/Blacksmith.zip
http://www.mediafire.com/download/bgl2lwnzb4520py/Perpetual_Destruction.zip

**Comment by Hotrod55** [comment]
The meshes were converted using 0.4's XMLConverter, which uses OGRE 1.8.x. You'll have to convert the meshes back to xml using 0.4's XMLConverter then use 0.37's to convert it to an older OGRE format.

**Comment by only-a-ptr** [comment]
Like Hotrod55 said, the problem is simply that you're using content made for RoR 0.4+ with version 0.3x. We don't support those versions anymore. We're releasing 0.4.7 soon.
