### ISSUE TITLE
The configurator (RoRConfig) drops values from ror.cfg

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#1112]
There's at least one setting which gets lost from RoR.cfg when you run rorconfig and press [save*]
- MainMenuMusic (boolean, default Yes)

**Comment by Hotrod55** [comment]
Edits to `ror.cfg` always get overwritten by RoRConfig. According to the gitter chat a while back, someone said this doesn't happen on Linux.

**Comment by only-a-ptr** [comment]
@Hotrod55 Yes, but RoRConfig SHOULD populate the GUI with values from the RoR.cfg, no matter how they got there, and other values should be at least remembered and put back.

The first part hopefully works.
The second part apparently has gaps.

**Comment by ulteq** [comment]
> Edits to `ror.cfg` always get overwritten by RoRConfig.

Even when you close RoRConfig with the Cancel button?

**Comment by tritonas00** [comment]
so maybe this is not an issue anymore?
