### ISSUE TITLE
Change version number?

### ISSUE THREAD

**Issue by Max98** [RigsOfRods/rigs-of-rods#112]
I know that this is useless but shouldn't we change the version number to 0.4.5.0? :P

**Comment by Hiradur** [comment]
More like 0.4.5-dev, this will prevent confusion in case you want to look at the code of an older release in the future.

**Comment by Max98** [comment]
You didn't get me, or I didn't get you. What i mean is simply to increase the version numbers here: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/RoRVersion.h

How will we put the -dev tag thing? Unless we put a boolean variable in RoRVersion.h and make it do the work for the -dev tag.

**Comment by Hiradur** [comment]
I got you.
IMO it should be 0.4.5 only for the release tag and 0.4.5-dev before the tag to differentiate between release and dev build. Everytime a release gets tagged we remove the -dev suffix for the tag and afterwards increase the version number and attach -dev again.

**Comment by Max98** [comment]
Done.
