### ISSUE TITLE
Props and Wheel Glitches in NB #23 (Pull Request #1123)

### ISSUE THREAD

**Issue by FuturzMinion** [RigsOfRods/rigs-of-rods#1126]
Hello,

I installed the latest AppVeyor build and it crippled one of the vehicles I drive. Here's a video: https://youtu.be/1ddK60-MCzE

How to recreate:

1. Download GraysonK95's Thomas Saf-T-Liner HDX

2. Download latest AppVeyor NB 23, PR 1123

3. Spawn Thomas_HDX-School_fps.truck

4. Error as I showed in video.

Thank you,

Brady

*EDIT* Version used is also called fafgnldo. I will try installing frdluckd #23/1113 to see if this fixes the issue.

**Comment by only-a-ptr** [comment]
Thanks for reporting. I'll look into it.

**Comment by ulteq** [comment]
I can't reproduce it on linux.

**Comment by only-a-ptr** [comment]
Might be already fixed. @FuturzMinion Can you re-test?

**Comment by FuturzMinion** [comment]
I downloaded the most recent greenlit build, and as soon as I spawned on simple terrain with the problem vehicle (Thomas_HDX-School_FPS.truck, I also had it preselected) and hopped into it via Enter, it gave me this error: http://i.imgur.com/aLMKN3B.png

**Comment by only-a-ptr** [comment]
@FuturzMinion Thanks for testing, but I can't access the image (I'm at work). Can you repost directly to here please?

**Comment by vido89** [comment]
Here it is
![almkn3b](https://cloud.githubusercontent.com/assets/3700226/19070817/65e06c1c-8a2d-11e6-8594-51c16f2e0b41.png)

**Comment by only-a-ptr** [comment]
Umm... I thought this was already resolved?

Which build was it, exactly?

**Comment by FuturzMinion** [comment]
D142693

**Comment by only-a-ptr** [comment]
@FuturzMinion Sorry but I couldn't find that build. I scrolled all the way down the build history page and used page search, but no hits.

Please find me the build yourself and post a link. If it isn't there anymore, please test again and post build info immediately.

Thanks.

**Comment by ulteq** [comment]
> it gave me this error: http://i.imgur.com/aLMKN3B.png

You need to update your `/resources/` folder: https://github.com/ulteq/rigs-of-rods/tree/master/bin/resources
