### ISSUE TITLE
RoRConfig: Some fixes needed

### ISSUE THREAD

**Issue by AntoniD330** [RigsOfRods/rigs-of-rods#1134]
1.- Well, in this tab we have a lot of things that needs to be looked at:
- _Authors_ paragraph: I think we can remove the `Authors` hyperlink. The rest looks OK to me.
- _Missing someone?_ paragraph: I think we can hyperlink `support@rigsofrods.org` and delete the `Missing someone?` text link.

![rorconfig](https://cloud.githubusercontent.com/assets/15718991/18960272/7bc6c4bc-8669-11e6-9619-9cd33edfb572.PNG)<hr>2.- In the _Settings_ - _Advanced_ tab, the `Regen cache` and `Clear cache` buttons dosen't work (if I click on the buttons, nothing happens).

**Comment by AnimosusTheWolf** [comment]
The Regen cache and Clear cache buttons work for me. Regen cache immediately launches the game and shows the progress of regenerating the cache. Clear cache button brings up a dialog that says the cache has been cleared.
