### ISSUE TITLE
Pause menu interferes with animations.

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#1139]
Pause menu makes pistonprop animation visible, even if the airplane is off.

![ror-glitch-pause-pistonprop](https://cloud.githubusercontent.com/assets/491088/19193809/e3a5583a-8cab-11e6-9c98-2d9535e2f25b.png)

**Comment by AnimosusTheWolf** [comment]
This also affects [exhausts.](http://docs.rigsofrods.org/vehicle-creation/fileformat-truck/#exhausts)

![948840462](https://cloud.githubusercontent.com/assets/10286567/19379684/746f5524-91b0-11e6-9b91-89c87bfda046.jpg)

**Comment by wilkgr76** [comment]
I'm not sure if this is the correct 'thread', but for some vehicles (e.g. Voulk's busses such as the monster bus or some police cars), the lights' animations continue after paused.

**Comment by only-a-ptr** [comment]
@AnimosusTheWolf @wilkgr76 Both of these issues were observed before, but thanks for the reminders, it's easy to forget.

I'm quite close to fixing all these and similar issues, stay tuned.

**Comment by only-a-ptr** [comment]
Closing as outdated, both issues are already fixed.
