### ISSUE TITLE
no swim animation

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#114]
ror 0.38 had a swim animation, why 0.4 doesn't?

**Comment by Max98** [comment]
The current Character model's animation needs to be redone, but I can't find anyone that has enough experience with it.

**Comment by Hiradur** [comment]
hagdervriese did some new animations, they are buried in one of the dev threads. Best to ask him about it.

**Comment by Max98** [comment]
I've added hagdervriese's new animation, they are much much better and does have swim animations. :)
