### ISSUE TITLE
Particles aren't working

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#1147]
Particles (Custom, smoke, dirt and water splashes) aren't working.
Tested with [Rigs of rods 0.4.7.0-truckparser-final](https://forum.rigsofrods.org/thread-605.html)

**Comment by ulteq** [comment]
Did you double check that your RoR.cfg isn't messed up?

This branch: https://github.com/RigsOfRods/rigs-of-rods/pull/1113 is a RoR.cfg killer in its current state.

**Comment by Michael10055** [comment]
All particles work fine for me.

**Comment by AnotherFoxGuy** [comment]
>Did you double check that your RoR.cfg isn't messed up?
This branch: #1113 is a RoR.cfg killer in its current state.

Yes, I forgot to ```Schakel deeltjes Systeem in```
