### ISSUE TITLE
Back to menu makes counters not working

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1148]
Load any map and a car with counters in dashboard (gavril omega).
Press Back to menu, reload the map and car. [Counters](https://cloud.githubusercontent.com/assets/2660424/19351116/1e593ab2-9163-11e6-8c6e-11176a0d5257.png) no longer work.

Same happens if you dont load a car, press Back to menu and then load it.

**Comment by AnimosusTheWolf** [comment]
Confirmed that custom dashboards stop functioning after exiting back to the menu. They display the values that existed during the exiting.

**Comment by ulteq** [comment]
Those overlays are handled by the OverlayWrapper: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/gui/OverlayWrapper.cpp
