### ISSUE TITLE
Seperate TruckHUD from OverlayWrapper

### ISSUE THREAD

**Issue by ulteq** [RigsOfRods/rigs-of-rods#1157]
The is no reason to access the `TruckHUD` through the OverlayWrapper.

Reference: https://github.com/RigsOfRods/rigs-of-rods/blob/07cde790d9e375c0f956e7f41ecb3337d3540971/source/main/gui/OverlayWrapper.cpp#L413-L414

**Comment by only-a-ptr** [comment]
I'd actually like to get rid of OGRE overlays (and thus `OverlayWrapper`) altogether... they're clumsy to work with and inferior to a GUI solution (like MyGUI we're already using)

Most importantly, the `TruckHUD` is a total deadcode, nobody ever accesses the instance. The old truckHUD has been obsoleted by the new MyGUI-based system. Issue already exists: https://github.com/RigsOfRods/rigs-of-rods/issues/1130

I'm closing this one in favor of the other.
