### ISSUE TITLE
RoR.cfg saving issues

### ISSUE THREAD

**Issue by Michael10055** [RigsOfRods/rigs-of-rods#1163]
Some options do not get saved properly on RoR exit:

- ~~Replay Mode~~ (#1160)
- ~~Disable Overview Map~~ (#1161)
- ~~"Preselected Map"~~ (1191)
- ~~"FOV External" value is overwritten by the current ingame value.~~ (#1192)
- ~~Vegetation resets to "None" after loading a terrain with vegetation.~~ (#1164)

**Comment by only-a-ptr** [comment]
@Michael10055 Please look at this table: https://github.com/RigsOfRods/rigs-of-rods/wiki/Console-variables and tell me which GVars should be saved on exit and which not.

**Comment by Michael10055** [comment]
Everything looks fine to me besides the preselected map and the FOV issue.

**Comment by disloyalpick** [comment]
The FOV issue is also present on Linux. But can you tell me how you would reproduce the preselected map issue, please?

**Comment by Michael10055** [comment]
In RoRConfig, go to the `Debug` menu, and type a terrain name in the "Preselected Map:" textbox (ex. simple2) and start RoR. It should automatically load the preselected map. Now close RoR and check the textbox in RoRConfig again, the value will be empty.

**Comment by only-a-ptr** [comment]
I assume the "Preselected Truck" settings should also persist between sessions, like "Preselected Map"

Currently, all these settings would get reset:
 * "Preselected Truck";
 * "Preselected TruckConfig";
 * "Enter PreselectedTruck";

**Comment by Michael10055** [comment]
Yes, both the Preselected Truck/Map options should be persistent.

**Comment by Michael10055** [comment]
👍
