### ISSUE TITLE
Custom AngelScript scripts not loading

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#1172]
In the latest master, the custom AngelScript scripts from maps aren't loading

You can test it with the Tutorial map: https://github.com/AnotherFoxGuy/Content

**Comment by tritonas00** [comment]
Last commit with working AS: https://github.com/RigsOfRods/rigs-of-rods/commit/2ea247f2624bb577f39bfce4cac3d8809562d6bbu

(thanks @ulteq for testing)
