### ISSUE TITLE
All out blackout on exit

### ISSUE THREAD

**Issue by techxpert211** [RigsOfRods/rigs-of-rods#1186]
Hi

Upon using the exit option in the main menu of the latest build, the game exits, and both monitors will go blank. Sound still works however. CTRL+ALT+Del, Alt+F4, and Alt Tab does not work either after this happens. I need to restart the computer in order to operate again. Thanks.

IT_Worx

**Comment by only-a-ptr** [comment]
Huh?

Somehow I completely missed this bug report...

Anyway, try again with latest RoR and post RoR.log please. It's in MyDocuments\Rigs of Rods 0.4\logs if you're on windows.

thanks

**Comment by Michael10055** [comment]
Unless someone can confirm this, closing.
