### ISSUE TITLE
In-game serverlist not loading 

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#1193]
The in-game server list isn't woking yet, I would like to see it finished before releasing 0.4.7.
The server list is already able to return the list in JSON: http://multiplayer.rigsofrods.org/server-list?json=true

**Comment by ulteq** [comment]
> I would like to see it finished before releasing 0.4.7

:+1:

**Comment by only-a-ptr** [comment]
Working on it: https://github.com/only-a-ptr/rigs-of-rods/commit/1c1bacc167f25d24c47da0add3f3c721d5d085e9

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy Fields "current-users" and "max-clients" are being sent as strings instead of ints. Can you fix it please?

I moved the MP repo under RigsOfRods org, since it's already online and almost integrated.

**Comment by only-a-ptr** [comment]
We have a problem with MyGUI. The "MultiListBox" widget used for MP selector is broken. You can only assign items to the first column: https://github.com/MyGUI/mygui/blob/master/MyGUIEngine/src/MyGUI_MultiListBox.cpp#L450-L454. The translation of the russian comment says it all: https://translate.google.com/#auto/en/%D0%B2%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%20%D0%B2%D0%BE%20%D0%B2%D1%81%D0%B5%20%D0%BF%D0%BE%D0%BB%D1%8F%20%D0%BF%D1%83%D1%81%D1%82%D1%8B%D0%B5%2C%20%D0%B0%20%D0%BF%D0%BE%D1%82%D0%BE%D0%BC%20%D0%BF%D1%80%D0%B8%D1%81%D0%B2%D0%B0%D0%B8%D0%B2%D0%B0%D0%B5%D0%BC%20%D0%BF%D0%B5%D1%80%D0%B2%D0%BE%D0%BC%D1%83

**Comment by AnotherFoxGuy** [comment]
> Fields "current-users" and "max-clients" are being sent as strings instead of ints. Can you fix it, please?

I fixed that, but the "has-password",  "verified" and "is-official" are now also send as an int.
```
  {
    "has-password": 0,
    "current-users": 0,
    "max-clients": 20,
    "verified": 1,
    "is-official": 1,
    "ip": "138.68.41.141",
    "port": 12000,
    "terrain-name": "any",
    "name": "Server 1: any"
  }
```
