### ISSUE TITLE
Skidmarks are saved on the terrain

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#1198]
When you do some skids on a terrain and then reload the terrain via Change Map or Main Menu the skidmarks will still be there.
To reproduce, load any map where you can do skidmarks.
![screenshot_2016-10-20_10-01-23_1](https://cloud.githubusercontent.com/assets/12358849/19551665/a7d89f32-96ac-11e6-9382-31c64fdf8d8a.jpg)
Make some skids.
![screenshot_2016-10-20_10-03-25_1](https://cloud.githubusercontent.com/assets/12358849/19551666/a7daebfc-96ac-11e6-9640-e687d18198a6.jpg)
Change the map and select the same map again. The skidmarks are still there.
![screenshot_2016-10-20_10-03-47_1](https://cloud.githubusercontent.com/assets/12358849/19551667/a7debf66-96ac-11e6-96c8-edfd081b8ceb.jpg)

Related to:
https://github.com/RigsOfRods/rigs-of-rods/issues/1079
https://github.com/RigsOfRods/rigs-of-rods/issues/539

**Comment by only-a-ptr** [comment]
:smile: 

Skidmarks in RoR is a separate dynamic mesh. And apparently it's not cleared when you unload a map. So no matter what map you load next, the skidmarks will be on the exact same coordinates - if you can find them.
