### ISSUE TITLE
Verify cause of 'VY/VX node not found' errors

### ISSUE THREAD

**Issue by ulteq** [RigsOfRods/rigs-of-rods#1206]
Compare the log output of the following trucks between version `0.38.67` and `upstream`:

[`Liebherr-630-ECH.truck`](https://repofiles.avrintech.net/repofiles-2nd-batch/c05175dcdb356a539164a59f57d4ba7f1fdf3775_Craneman-Liebherr-630-ECH-final.zip)
[`LotusEsprit_JB.truck`](http://www.mediafire.com/file/ka4uruepf2ko4uo/LotusEsprit_JB.zip)

Related with: https://github.com/RigsOfRods/rigs-of-rods/issues/1058
Related with: https://github.com/RigsOfRods/rigs-of-rods/issues/171

**Comment by ulteq** [comment]
The `Lotus Esprit S1` uses `nodes2` and the `SequentialImporter::ResolveFlexbodyForset` method almost always returns an incorrect flexbody node list, when `nodes2` are used: https://github.com/ulteq/rigs-of-rods/blob/a3aef4075511cbd537a52a89c2fcbbc17efd9029/source/main/resources/rig_def_fileformat/RigDef_SequentialImporter.cpp#L235-L307

Poor attempt to fix it: https://github.com/ulteq/rigs-of-rods/commit/a3aef4075511cbd537a52a89c2fcbbc17efd9029

0.38.67 `forset` code: https://github.com/only-a-ptr/ror-legacy-svn-trunk/blob/master/source/main/physics/flex/FlexBody.cpp#L52-L76

The `forset` node numbers directly index the node array. No matter if `nodes` or `nodes2` are used.

**Comment by tritonas00** [comment]
0.38 logs

Liebherr-630-ECH: http://pastebin.com/B8zuNSFY

LotusEsprit_JB: http://pastebin.com/VQAVCXGZ

**Comment by tritonas00** [comment]
from DarthCain on discord:

> I added more nodes on forset for the crane mentioned there and it removed the spam in the log and fixed the issue

```
VY node error

A VY node error can be seen in console as the following error :

FLEXBODY ERROR on mesh MeshName: VY node not found

This means that the physics engine is unable to properly map the flexbody to the defined set of nodes; This has a few possible causes.

The first one is not enough nodes. The physics engine needs at the very least 3 nodes, preferably more, assigned to each flexbody to calculate deformation properly.

An other possible issue is the position of the nodes relative to each other. If the nodes are all in line or on a flat plane, the game might be unable to map the flexbody to the nodes, and give out a VY error.

And the last possible issue is if the nodes don’t properly cover the flexbody. If parts of the flexbody are located far away from any of the assigned node, the game will be unable to properly interpolate their position based on node coordinates.

In all cases, the best solution is to include more nodes into the flexbodies 
```

Related: https://github.com/RigsOfRods/rigs-of-rods/issues/2923, so closing this.
