### ISSUE TITLE
Ability to open the RoR.log or any logs via RoRConfig

### ISSUE THREAD

**Issue by disloyalpick** [RigsOfRods/rigs-of-rods#1217]
Title says it all.  Would make stuff much easier.  

It could be set up like this

Have a dropdown menu, listing all the log files.

We choose one, and on the side of it, says open. Click open and the log file opens. 

No hassle.

What do you guys think?

**Comment by only-a-ptr** [comment]
Interesting idea...

> Would make stuff much easier.

What stuff, exactly? Modding? Testing? Player support? I'd like to know what use case(s) exactly you have in mind.
Also, we'd need to sort out how exactly the file opens. On windows, we could use Notepad or a System default text editor. I'm not sure about Linux.

**Comment by disloyalpick** [comment]
Well, Basically would make everything easier. Game is started from rorconfig. Central place for all logs and stuff, instead of having to browse folders and such. They would be right there for the user to get.

Also I think Linux has a default text editor. I'm not too certain on this though. May @ulteq can clarify.

**Comment by tritonas00** [comment]
no rorconfig anymore
