### ISSUE TITLE
trailer's broke

### ISSUE THREAD

**Issue by wickedchikin** [RigsOfRods/rigs-of-rods#1219]
ok i know their is a post already about this... but their was never a solution besides a link to  build 4 which is no longer avaible. sooooo. my problem is when i hook my truck to the trailer the trailer just stays in place and the truck dangles from the hitch. please help, i havent played this game in more then a year and decide to get back into it

**Comment by Michael10055** [comment]
Fixed in 0.4.6RC3. https://forum.rigsofrods.org/thread-3.html
