### ISSUE TITLE
Main menu sound

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1230]
Some commits before there was a sound playing in the background when you start RoR.

In latest master there isn't any sound.

I'm not a big fan of background sound anyway, just wanted to report :smile:

**Comment by only-a-ptr** [comment]
It's configurable via RoR.cfg: "MainMenuMusic" (Yes/No)
I changed the default to "No" while working at it - I'm also not a fan of it, really.

**Comment by tritonas00** [comment]
nothing to see here i think, so closing
