### ISSUE TITLE
"Allow DirectX9Ex" option causing terrain loading crashes

### ISSUE THREAD

**Issue by Michael10055** [RigsOfRods/rigs-of-rods#1239]
See this post for reference: https://forum.rigsofrods.org/thread-697-post-6546.html#pid6546

What is the "Allow DirectX9Ex" option supposed to do? I always have it set to `No` - I figured it was a 'added leftover' from the OGRE 1.9 port.

**Comment by disloyalpick** [comment]
The other day I was trying to load the Greece map, and with Allow DirectX9Ex set to yes, it crashes everytime. But once I would disable it, it would work fine.

@Michael10055 My though of what it might be is some sort of experimental Dx3D9 hence the "EX"

Maybe @ulteq or @only-a-ptr would be able to clarify it some more, and figure it out.

**Comment by AnotherFoxGuy** [comment]
http://www.ogre3d.org/forums/viewtopic.php?f=4&t=71366
