### ISSUE TITLE
Random Multiplayer crashes

### ISSUE THREAD

**Issue by Michael10055** [RigsOfRods/rigs-of-rods#1241]
At random while playing multiplayer, the game will crash. This is what VS 2015 tells me:
![1](http://i.imgur.com/M9dUVcM.png)

**Comment by only-a-ptr** [comment]
How frequently does it happen? How many times in total? When did it first happen?

**Comment by Michael10055** [comment]
It's been happening ever since RoRNet2,38 was integrated. But it seems it has been happening more often now. I've noticed it only seems to happen if a server is getting traffic (players leaving/joining/spawning vehicles). I can't recreate it every time - it happens randomly. 
For example, I was driving a Omega 10 on xRoR Any on NeoQ. -> crash.
Rejoined, as soon the map loaded -> crash.
Rejoined again, spawned the same vehicle using the truckshop -> crash right after the vehicle spawned.
All of this happened while the server had a decent amount of players leaving/joining (4-8)
The VS 2015 picture above happened while I was idling on a modified N-Labs with a Zeta X.
I've also had it happen on the terrain loading screen after joining a server.
Anyways, I just had a crash while loading NeoQ on a server using RC1 - sent the report to CrashFix. Hopefully that'll be helpful :smile:

**Comment by tritonas00** [comment]
By "RC1" you mean latest master?

Multiplayer is very solid at least here.

**Comment by Michael10055** [comment]
RC1: https://forum.rigsofrods.org/thread-704.html

**Comment by Michael10055** [comment]
It looks like the crash is caused by players joining/leaving, I was on xRoR_Any2.38 alone, and the game crashed once someone joined.
![2](http://i.imgur.com/WFze2W4.png)

**Comment by tritonas00** [comment]
I will test that server tomorrow to see if i can reproduce the crash

**Comment by AnotherFoxGuy** [comment]
[This](https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/network/Network.cpp#L216) memcpy seems to crash the game.

**Comment by only-a-ptr** [comment]
Bug zapped: https://github.com/RigsOfRods/rigs-of-rods/pull/1261
