### ISSUE TITLE
0.4.7 rc1 RigSpawner: ERROR; #FFFF00 WARNING #FFFFFF

### ISSUE THREAD

**Issue by fidoj** [RigsOfRods/rigs-of-rods#1250]
0.4.7 rc1 error's on working experimental vehicle from 4.0.7, i had to look at what the limits are, from head it appears the limits are higher at 5000 beams. also comment warnings should either be silent or compounded. i had someone sugest # was the comment line but that throws the same message.
i thought i lost this vehicle and wanted to re-look at it.
[https://www.youtube.com/watch?v=ys82E3T200c](url)
[20_4_platform.zip](https://github.com/RigsOfRods/rigs-of-rods/files/601637/20_4_platform.zip)
[RoR_log.zip](https://github.com/RigsOfRods/rigs-of-rods/files/601640/RoR_log.zip)

**Comment by Michael10055** [comment]
Closing this as it is not a issue with RoR, as discussed on Discord.
