### ISSUE TITLE
Ties not connecting

### ISSUE THREAD

**Issue by DarthCainRor** [RigsOfRods/rigs-of-rods#1252]
Ties no longer connect to loads on the trailer, when you try to tie an object down from the vehicle pulling trailer.

To replicate:
Spawn any truck, and trailer with ties. 
hook the two together
Place a load on the trailer.
Enter truck, pulling trailer and hit "O" to attempt to lock load down.

If you enter the trailer from the drop down menu, and hit O, the ties work fine.

**Comment by ulteq** [comment]
I will try to look into it, sounds like an issue with `forwardcommands`.
