### ISSUE TITLE
Let's bring SkyX back

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#1262]
Based on community demand (Discord chat), I decided to research SkyX and try to finish it's support in RoR.

I'm creating this issue ticket to persist info from the chat (and as self-reminder)

## SkyX

 * Homepage (contains resource downloads, out of date): http://www.paradise-sandbox.com/#hydraxskyx.php 
* OGRE wikipage: http://www.ogre3d.org/tikiwiki/SkyX
* SkyX development repo - up to date, but without resources: https://bitbucket.org/ogreaddons/skyx

It may be old, but the code is pretty clean and simple. The volumetric clouds use OGRE 1.x geometry-manipulating API a lot, but it's still very clean and straightforward. Overall it looks fairly portable to OGRE 2.1.

## RoR integration by Max98

https://github.com/Max98/ror_nextstable_gui/tree/SkyX-Clean

it looks like it should work out-of-the-box. The SkyX sources/shaders/media are completely included, which makes sense. The library is unfeasible as dependency because it's barely surviving and the only existing repo doesn't contain the shaders, which is actually the most important piece of code (and media are also missing).

**Comment by Max98** [comment]
If I'm not mistaken, the integration I had worked on should be good to go. But that was with Ogre 1.8/1.9, not sure for Ogre 2.1, it might need some changes from here and there, as I also saw that you have changed many structure stuff.

**Comment by Speciesx** [comment]
I have everything. :)

SkyX lib + demos source and media files
https://www.dropbox.com/s/3t2lsh59l4ev06i/SkyX-v0.4.rar?dl=0

CMake package (For SkyX 0.3.0 but also compatible with 0.4)
https://www.dropbox.com/s/qcc6vib5zg1emvc/SkyX-v0.3_CMake.rar?dl=0

**Comment by only-a-ptr** [comment]
@Max98 Hi, nice to see you here again. Yes, I'm also under impression it should be good to go. For OGRE 2.1+, it'll need a major overhaul because the API is completely different. Scene entities are still there for compatibility, but geometry/shader API is new. But I'm not concerned about that right now.

@Speciesx Cool, might come in handy.

**Comment by Speciesx** [comment]
https://github.com/Speciesx/rigs-of-rods/commits/SkyX
Current upstream with working SkyX.

**Comment by only-a-ptr** [comment]
@Speciesx Testing...

**Comment by Michael10055** [comment]
Works fine for me on Windows 8.1 Pro x64 + NVIDIA GeForce GTS 360M (very outdated, I know)
![screenshot_2017-02-20_17-47-53_1](https://cloud.githubusercontent.com/assets/11002490/23144405/3f6377ac-f795-11e6-81fa-bd25d0d2ae99.png)
![screenshot_2017-02-20_17-04-01_1](https://cloud.githubusercontent.com/assets/11002490/23144407/432882e2-f795-11e6-99cf-30d9ef41a87f.png)

**Comment by tritonas00** [comment]
also works fine with opengl on linux

**Comment by Speciesx** [comment]
@only-a-ptr
 This is a sightrange bug.

**Comment by only-a-ptr** [comment]
Thanks for the research, guys!

I'll re-check my settings. And I'll post RoR.log next time 😊  Did any of you modify the SkyX config file? If yes, can you upload for me to test?

**Comment by Michael10055** [comment]
I use the default configuration with layered clouds enabled.

**Comment by only-a-ptr** [comment]
Removing from v0.4.8 because the code got out of date and integrating it would take a while.

I'll get back to it first thing after the release.

**Comment by AnotherFoxGuy** [comment]
Should we completely replace Caelum with SkyX?
Since Caelum is written 100% in CG shaders I think Caelum will only cause more problems in the future  
(See #1412)

**Comment by tritonas00** [comment]
Tested yesterday, works fine https://forum.rigsofrods.org/development-discussion/64-rigs-rods-skyx-build.html#post646

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy Makes complete sense, but in that case we should invent some fallback handling of `CaelumConfigFile` entry in `terrn2` : http://docs.rigsofrods.org/terrain-creation/old-terrn-subsystem/#caelum-sky

@tritonas00 Heh, I didn't even know about that thread, thanks!

**Comment by AnotherFoxGuy** [comment]
#1466
