### ISSUE TITLE
Truck Description File Add_animation link broken

### ISSUE THREAD

**Issue by graysonk95** [RigsOfRods/rigs-of-rods#1268]
In the truck description file (http://docs.rigsofrods.org/vehicle-creation/fileformat-truck/) the link to the Add_animations page is broken.

Here is the archived version of the page it pointed to on the old site:
https://web.archive.org/web/20150512065114/http://www.rigsofrods.com/wiki/pages/Truck_Description_File#Add_animation

**Comment by graysonk95** [comment]
Same with the Keypress Events page: https://web.archive.org/web/20150514063835/http://www.rigsofrods.com/wiki/pages/Keypress_Events

**Comment by Michael10055** [comment]
The whole wiki archive is available at https://xror.avrintech.net/rorwikibackup/index.php/Main_Page
