### ISSUE TITLE
Prop placement in the new truck editor

### ISSUE THREAD

**Issue by Dogy144** [RigsOfRods/rigs-of-rods#127]
There was a thread created about requesting a Prop Placement Program and everyone shot it down saying that he should do it the old fashioned way. However, I think that it could be a great addition to the new "in-game" truck editor.

Original Thread: http://www.rigsofrods.com/threads/118966-Prop-placement-Program

**Comment by Max98** [comment]
I saw that thread, but I was lazy to answer it back then.. x)
I believe that the rig editor will have this feature but not for 0.4.5

**Comment by only-a-ptr** [comment]
@Dogy144 : Prop-placer is planned for my RigEditor, but it's not a high priority.

**Comment by AnotherFoxGuy** [comment]
Can be closed since the rig editor has been removed

**Comment by Hiradur** [comment]
> Can be closed since the rig editor has been removed 

I'm not sure what @only-a-ptr plan is but the RigEditor may return in the far future.

**Comment by only-a-ptr** [comment]
Rigs of Rods needs a comprehensive editor. The "tune it in text editor" workflow is prehistoric. There are basically 2 ways to go:

1. Use Blender as base and develop a set of plugins.
2. Use RoR as base and develop new editor.

Both have pros and cons, and the choice depends on features offered by RoR. Right now, an experimental project 'NextSim' is in motion (http://forum.rigsofrods.org/thread-367.html) and it could re-shape RoR's featureset. So let's wait how things turn out. Until then, I'm closing this.
