### ISSUE TITLE
Create a windows installer.

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#1270]
At the moment, there's AFAIK no installer for windows contributed to RoR.

Max98 and AnotherFoxGuy had something for 0.4.5/6/7, but it was never submitted to the repo. I don't have it at hand. I have to start from scratch.

**Comment by Speciesx** [comment]
@only-a-ptr 
Is this issues the last blocker for 0.4.7.1 release?

**Comment by AnotherFoxGuy** [comment]
I never submitted the installer script file because all of the paths for the files are absolute.
But since I've bought a new hard drive I'm able to compile RoR once again.
Should I create the installer for 0.4.7.1?

**Comment by only-a-ptr** [comment]
Bang! @AnotherFoxGuy's post just materialized right in front of me 😱 

@AnotherFoxGuy That's a detail, submit the scripts even so please.
@Speciesx Yes, that's the last blocker, although I could have just built the binary and posted it to forums as DevBuild... I'm concentrating on 0.4.8 already.
