### ISSUE TITLE
Website is not working (Fixed)

### ISSUE THREAD

**Issue by mormislaw** [RigsOfRods/rigs-of-rods#1272]
forum.rigsofrods.org isn't working on latest version of Chrome.

**Comment by DevRain2500** [comment]
It is working for me. Have you tried changing your DNS settings? That is what fixed it for me when they changed servers.

**Comment by Michael10055** [comment]
I recommend switching to Google's DNS servers: http://www.howtogeek.com/164981/how-to-switch-to-opendns-or-google-dns-to-speed-up-web-browsing/

**Comment by mormislaw** [comment]
Thank you guys! It worked :)
