### ISSUE TITLE
Forum Down?

### ISSUE THREAD

**Issue by UCDHIUS** [RigsOfRods/rigs-of-rods#1275]
Is the main forum down, right now?

**Comment by only-a-ptr** [comment]
No it isn't :slightly_smiling_face:

**Comment by UCDHIUS** [comment]
@only-a-ptr I keep on getting "this site can't be reached" rigsofrods.org's server DNS could not be found"

**Comment by DevRain2500** [comment]
I had to switch to google DNS to get anything rigsofrofs.org to load. http://www.howtogeek.com/164981/how-to-switch-to-opendns-or-google-dns-to-speed-up-web-browsing/

**Comment by UCDHIUS** [comment]
@DevRain2500 

I switched to google DNS and same result?

**Comment by only-a-ptr** [comment]
OK, I'll forward this to our webhost.

The fact is, URL "http://rigsofrods.org" doesn't work, while "http://www.rigsofrods.org" does. But the browser automatically retries with "www" when it fails (my Firefox 47.x) does so.

@UCDHIUS Where are you from? Do you have fixed public IP? What's your current IP?

**Comment by Michael10055** [comment]
http://rigsofrods.org/ does not redirect to http://www.rigsofrods.org/ on the latest Firefox Developer Edition 53.0a2 (2017-02-11)

**Comment by UCDHIUS** [comment]
@only-a-ptr  Hawaii, USA Current is 72.253.10.68 and no its dynamic from my ISP.

**Comment by Michael10055** [comment]
The forum is working just fine for me on Google's DNS.
