### ISSUE TITLE
Adding set_nodes to a truck file then reloading truck causes crash

### ISSUE THREAD

**Issue by disloyalpick** [RigsOfRods/rigs-of-rods#1276]
Not sure if it only happens randomly.

Steps to reproduce.
1. Spawn any vehicle.
2. Open said vehicle's .truck file
3. while game is running with that vehicle spawned, add set_node_defaults anywhere in the file, then save the file and update it in the archive
4. Now simply press CTRL+SHIFT+R and it will cause RoR to crash.

**Comment by Michael10055** [comment]
Moving special props (ex. seat/seat2) will also cause RoR to crash.

**Comment by only-a-ptr** [comment]
I just tested with current upstream and unpacked Hillclimber Buggy (OpenGL, Win7) and nothing hapenned. I added `set_node_defaults 0.2, 1.2, 1.2, 1.2` in the middle of the `nodes` section. I also tried with ZIP, but it wasn't possible, the ZIP was locked by RoR.

Just re-open this if anything happens again. It's unlikely tho, vehicle re/loading was very much redone in upstream.
