### ISSUE TITLE
[RoRnet 2.40] timeout shouldn't shut down ror

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1279]
>19:41:17: [RoR|Globals] Updating "mp_server_port": [12013] => [12015]
19:41:17: [RoR|Networking] Trying to join server 'ror.avrintech.net' on port 12015'...
19:41:27: NET receive error 1: SWBaseSocket::waitIO() timeout

Tried to connect to ror.avrintech.net rornet 2.40 server, but after few seconds ror close without a error.

**Comment by only-a-ptr** [comment]
Is the `19:41:27: NET receive error 1: SWBaseSocket::waitIO() timeout` the last line in RoR.log? If yes, then I suspect the shutdown didn't come from RoR, but the SocketW library instead.

I need to test myself. I thought I already removed all the shutdowns.

**Comment by tritonas00** [comment]
Still valid

**Comment by only-a-ptr** [comment]
@tritonas00 😟 Thanks for reminding me.

**Comment by only-a-ptr** [comment]
Is this still valid?

**Comment by tritonas00** [comment]
i cant reproduce it

i tried even cutting the internet while RoR connects, no still issue.

i suggest close it unteil we can reproduce it again

**Comment by only-a-ptr** [comment]
Closing until further notice 🙂

**Comment by tritonas00** [comment]
Still valid

**Comment by only-a-ptr** [comment]
Applying this https://github.com/RigsOfRods/ror-server/commit/b455cec7a69745b7c854c4d701556a2e57d8a615 to SocketW dependency should fix it.
