### ISSUE TITLE
Activating the advanced reset on a trailer causes a crash

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1280]
Spawn and enter a trailer and activate advanced reset, ror will crash.
Happens with current upstream.

**Comment by only-a-ptr** [comment]
Is it even legal to enter trailers? I thought only vehicles with CINECAM could be entered.

**Comment by Speciesx** [comment]
> Is it even legal to enter trailers?

yes.

**Comment by Michael10055** [comment]
Some trailers work fine, such as the Dura-Built 176 Series.

**Comment by only-a-ptr** [comment]
Can you please give me some download links to the crashing trailers then?

**Comment by Speciesx** [comment]
https://repofiles.avrintech.net/repofiles-3rd-batch/f48e4f4fda70fd08e6381995117f1b77d95afef2_p-32.zip

**Comment by tritonas00** [comment]
any update on this?

**Comment by Speciesx** [comment]
no
