### ISSUE TITLE
Cache regeneration says it's finished while still in progress

### ISSUE THREAD

**Issue by wilkgr76** [RigsOfRods/rigs-of-rods#1283]
![image](https://cloud.githubusercontent.com/assets/12093476/23190385/3a24a726-f8e3-11e6-8a91-fbea700f9035.png)

Not sure what else to say to it. In case this is relevant, I switched to a different program while it was regenerating the cache (I pressed 'regen cache' in settings)

**Comment by Michael10055** [comment]
I recommend just using RoRConfig to regen. The in-game settings haven't been touched in a long time and most settings don't save now.

**Comment by wilkgr76** [comment]
@Michael10055 Got it. Thanks

**Comment by tritonas00** [comment]
is this still valid?

**Comment by ulteq** [comment]
> is this still valid?

Unlikely.
