### ISSUE TITLE
MP selector is lacking: password, nickname

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#1284]
Since the [network] tab was removed from RoRConfig, the MP selector (or manual editing ror.cfg) is now the way to go.

However, there are features missing ATM:
* a nickname editbox
* a password editbox

**Comment by Michael10055** [comment]
Related to: #1254

**Comment by only-a-ptr** [comment]
Closing as duplicate of #1254 - thanks to Michael10055 for pointing this out.
