### ISSUE TITLE
Vehicles with capitals in section doesn't work

### ISSUE THREAD

**Issue by TheUnknownGuyFromRoR** [RigsOfRods/rigs-of-rods#129]
The problem is simple to explain: When in the .truck file is Globals instead of globals, the parser ignores this section. Same with other sections. Vehicles with that issue are crashing the game, freezing in the air or have things placed wrong. 
![screenshot_1](https://cloud.githubusercontent.com/assets/10696803/6880836/61b03ef2-d542-11e4-814e-e433ebf0ae93.jpg)
![screenshot_3](https://cloud.githubusercontent.com/assets/10696803/6880837/61ba4604-d542-11e4-839b-d9214e45e448.jpg)
![screenshot_4](https://cloud.githubusercontent.com/assets/10696803/6880838/61c39830-d542-11e4-8d25-a753e250e575.jpg)
That's why also some maps with pre-spawned object crashes.

**Comment by only-a-ptr** [comment]
Section names are case sensitive, so only 'globals' is valid, 'Globals' is wrong.

However, I checked sources of old 0.38x and discovered it accepts both and prints a warning to RoR.log of the lettercase is wrong. Version 0.4.0.7 only accepted correct keywords.

I'll introduce this tollerance to 0.4.5, too.

**Comment by only-a-ptr** [comment]
Fixed in 0.4.5.0-dev test build 2:
http://www.rigsofrods.com/threads/119110-Test-Build-Rigs-of-rods-0-4-5-0-dev
Please download and test.

**Comment by TheUnknownGuyFromRoR** [comment]
thanks!
