### ISSUE TITLE
Build fails with Visual Studio 2017

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1295]
I get only one error.
......\rigs-of-rods\source\main\physics\BeamFactory.cpp(70): error C3861: "__cpuid": identifier not found.

**Comment by AnotherFoxGuy** [comment]
Found the documentation: https://docs.microsoft.com/en-us/cpp/intrinsics/cpuid-cpuidex

Could you try adding ```#include <intrin.h>``` to BeamFactory.cpp ?

**Comment by Speciesx** [comment]
Yeap, this fixes the error.
