### ISSUE TITLE
Host content packs from commercial service

### ISSUE THREAD

**Issue by LNFWebsite** [RigsOfRods/rigs-of-rods#1296]
Currently you guys are hosting the content packs (some in the Gigabytes of data) on a Windows 32 computer running Apache (dl.rigsofrods.org)...

Could you possibly place these files elsewhere (ie. here on GitHub or Mediafire or Dropbox).

As it stands, every time I've tried to download a content pack from the dl.rigsofrods.org site, the file is corrupted and is at least 60MB less than it's supposed to be (124MB vs 193MB to be exact, http://dl.rigsofrods.org/pack_contentpack04.zip).

This is compounded with the errors involving the 0.4.7.1 installer and people's slower internet connections.

Please clone these files to another service. It would be greatly appreciated.

Other than that, keep up the good work!

PS: I'm a longtime RoR user who started with an old Pentium Desktop and could only run the simple_terrain with the Ogre buses. It's amazing to see how far the project has come!

**Comment by only-a-ptr** [comment]
Hello and thanks for reporting.

We're aware of the situation and working to improve it. Stay tuned!

**Comment by LNFWebsite** [comment]
Okay thanks for the quick reply!

**Comment by LNFWebsite** [comment]
I can personally advocate for using GitHub, unless there is an upload limit.

**Comment by LNFWebsite** [comment]
@only-a-ptr Do you think you'll have them cloned somewhere by tonight? (America)

**Comment by only-a-ptr** [comment]
@LNFWebsite The installers can already be downloaded from our Github releases page: https://github.com/RigsOfRods/rigs-of-rods/releases

I'm uploading the contentpacks to my Dropbox as we speak.

**Comment by LNFWebsite** [comment]
@only-a-ptr Okay... thanks. Right now you have only uploaded the highquality pack without the content pack...

Does this pack include the zips from the 0.4 content pack?

**Comment by only-a-ptr** [comment]
Hi. I added contentpack0.4. Do you also need the 0.3x content? I'd like you to just play 0.4x and submit issues if you find any... :wink:

**Comment by LNFWebsite** [comment]
No, I probably don't need the 0.3x content but ideally for redundancy all of the packs should be cloned.

I appreciate your help! Thanks for taking the time to do this.

**Comment by only-a-ptr** [comment]
We got a new reliable webhost, so this is resolved.

**Comment by LNFWebsite** [comment]
@only-a-ptr Thanks! Keep up the good work!
