### ISSUE TITLE
Ingame fullscreen settings doesn't work

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1299]
> 13:40:16: OGRE EXCEPTION(2:InvalidParametersException): Option named 'Render System' does not exist. in D3D9RenderSystem::setConfigOption at D:\ror\dev\dependencies\src\Ogre\ogre_src_v1-9\RenderSystems\Direct3D9\src\OgreD3D9RenderSystem.cpp (line 397)
>13:40:16: Error setting Ogre Values

**Comment by only-a-ptr** [comment]
@ulteq @tritonas00 Can you check if this is still true with OGRE 1.11?

**Comment by AnotherFoxGuy** [comment]
There isnt a fullscreen checkbox anymore with the new imgui settings menu
