### ISSUE TITLE
Move Bugs from old Bugtracker to this issue tracker

### ISSUE THREAD

**Issue by Hiradur** [RigsOfRods/rigs-of-rods#13]
Check if they are still valid.  
Old Bugtracker: http://www.rigsofrods.com/wiki/pages/Bugtracker
some additional bugs may be found here: http://www.rigsofrods.com/threads/111967-Improvised-bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1295079

**Comment by tgp1994** [comment]
I believe this may be complete!

**Comment by Hiradur** [comment]
Excellent work. Thank you very much!
