### ISSUE TITLE
Compile error on FreeBSD after finaggling with AngelScript and WXW just to get the build system to work

### ISSUE THREAD

**Issue by janicez** [RigsOfRods/rigs-of-rods#1308]
The linker could not find "-l-lrt" and when I corrected the error in the scripts, it still didn't build.

Steps to reproduce: I would have filmed it but the discord was full of snowflakes.

**Comment by Hiradur** [comment]
librt should only be used by the Mumble plugin so building without USE_MUMBLE defined in the CMakeFiles could fix it.
