### ISSUE TITLE
Agora brake lights flash

### ISSUE THREAD

**Issue by Dogy144** [RigsOfRods/rigs-of-rods#131]
On the Agora Bus (both small and large), the tail/brake lights flash as if they are turn signals. This is in the dev 0.4.5 version posted here: http://www.rigsofrods.com/threads/119110-Test-Build-Rigs-of-rods-0-4-5-0-dev?p=1377339&viewfull=1#post1377339

**Comment by Max98** [comment]
@only-a-ptr You should take a look, I believe it's from the new parser.
