### ISSUE TITLE
Exhausts vs. SoundSources

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#1317]
I just noticed one thing in code: Soundsources relating to engine are always positioned at the old-style exhaust point (node marked with 'x' option). If the vehicle doesn't have this "smoker node", the position falls back to node 0. This means the newer truckfile section "exhausts" has no effect on sounds.

**EDIT**: This only applies if `disabledefaultsoundsources` is not used, i.e. when sounds are set-up automatically.

List of affected soundsources:
```
"tracks/default_diesel"
"tracks/default_force"
"tracks/default_car"
"tracks/default_turbo_big"
"tracks/default_turbo_small"
"tracks/default_turbo_mid"
"tracks/default_turbo_bov"
"tracks/default_wastegate_flutter"
"tracks/default_marine_large"
"tracks/default_marine_small"
```

Things to consider here:
- is the engine really most audible at the exhaust? The positioning needs a re-touch here
- what if there are multiple exhausts?

**Comment by AntoniD330** [comment]
@only-a-ptr 
> is the engine really most audible at the exhaust?

No, the engine is more audible on the engine location (more mechanical sounds, noises,...).
The exhaust do make noise, but the sounds coming from the engine is more intence.
> what if there are multiple exhausts?

As a professional car mechanic, multiple exhaust just help the engine to breath better (less restriction into the exhaust means less self braking engine).
Generaly, inline engines usualy have only one exhaust pipe and V engines uses two exhaust pipes.

**Comment by Michael10055** [comment]
@AntoniD330 Pretty sure he's talking about in RoR, not real life ;)

@only-a-ptr AFAIK the exhausts section never effects sounds/was supposed to, it's just visual. Most vehicles don't use the exhausts section.
Soundsources require a node number (http://docs.rigsofrods.org/vehicle-creation/fileformat-truck/#soundsources) that is the 'center' of the sound. The `x` and `y` node options became obsolete by the `exhausts` section as it defines the 2 nodes already. And the node options only allowed you to have one 'exhaust'.

**Comment by only-a-ptr** [comment]
@AntoniD330 Thanks for the insights, we'll need those around here. Myself, I don't even own a car. I wrote those bullet points mainly to point out how silly and limited RoR's audio options are.

@Michael10055 You-re contradicting yourself a bit... If `exhausts` lack the power of `X/Y node` and hardly anyone ever uses it, then it's not really a proper substitute.

Give me 20min to research how the `soundsources` node spec actually works...

**Comment by only-a-ptr** [comment]
I'm closing this as resolved.
