### ISSUE TITLE
Water stuck at 0 height with Hydrax

### ISSUE THREAD

**Issue by Michael10055** [RigsOfRods/rigs-of-rods#1318]
On the latest master, all water is stuck at 0 height instead of using the value specified in the `.terrn2` file.
![screenshot_2017-04-16_19-16-33_1](https://cloud.githubusercontent.com/assets/11002490/25075066/763b1734-22d9-11e7-9ed8-4b6b58a403d1.png)
To reproduce, just load a map that has water, such as North St Helens.
Changing the water type doesn't change anything. The `/setwaterlevel` console command still works though.

**Comment by AnimosusTheWolf** [comment]
Can confirm.
![screenshot_2017-04-16_08-58-25_1](https://cloud.githubusercontent.com/assets/10286567/25075081/0ca99954-22c9-11e7-96b5-b1634c7d2697.png)
![screenshot_2017-04-16_08-57-23_1](https://cloud.githubusercontent.com/assets/10286567/25075082/0cad26fa-22c9-11e7-81c7-373e49f7e920.png)

**Comment by tritonas00** [comment]
Same here

**Comment by tritonas00** [comment]
I think this is still valid, but only for hyfrax:
Normal
![2017-08-16-231412_1920x1080_scrot](https://user-images.githubusercontent.com/2660424/29383473-2ff51b02-82d9-11e7-9cd7-f33d051e9738.png)
Hydrax
![2017-08-16-231528_1920x1080_scrot](https://user-images.githubusercontent.com/2660424/29383474-2ff81d7a-82d9-11e7-8ecf-e1d63bda250f.png)
