### ISSUE TITLE
'Ingame Console' slow down cache regen

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1319]
![111](https://cloud.githubusercontent.com/assets/1196375/25086855/4bdd882c-236b-11e7-817e-bac1cc0328f0.PNG)

With active 'Ingame Console' regen cache is at least 30 times slower.

**Comment by only-a-ptr** [comment]
Give me more detailed scenario - you open RoRCOnfig, check that checkbox and then what? Do you start RoR from there? Do you click some "cache regen" button in RoRCOnfig? Do you manually wipe your cache before that? Is it a full regen or update?

I have no idea what that checkbox does, really.

**Comment by Michael10055** [comment]
It basically enables a "live view" of the `RoR.log` on the Console window:
![ror_2017-04-22_00-14-39](https://cloud.githubusercontent.com/assets/11002490/25301294/f221ed62-26f0-11e7-8628-864d7f6db3a8.png)

**Comment by Speciesx** [comment]
@only-a-ptr 
Delete the cache activate 'Ingame Console' and start ror.

**Comment by only-a-ptr** [comment]
@Michael10055 Thanks for the explanation.

This definitely isn't a bug, MyGUI is simply slow to update the console text if it's too long. From what I've seen of MyGUI's API and sources, it most definitely keeps the console text as a single instance of `MyGUI::UString` and re-allocates it on every update, causing the slowdown.

Personally I'd remove the "Debug tab -> Ingame console" checkbox from RoRConfig. I think it's useless to look into live view of RoR.log, especially during cache regen - a lot of messages (mostly OGRE) get dumped there and it happens fast. I suggest these updates:
* add an `log-echo off/on` command to the console which enables/disables the echo on runtime.
* Make cache-regen automatically print human-readable errors/warnings (such as "skipping this ZIP, failed to parse ABCD.truck") into the console.
