### ISSUE TITLE
Hydrax causes crashes in current upstream.

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#1320]
Recently, all my dev builds have been crashing due to Hydrax. It also happens for vanilla upstream: https://github.com/RigsOfRods/rigs-of-rods/tree/aa7db6d4416a5aa81ab492780490ea83c0f83d0f

Location: REPO\source\main\gfx\hydrax\Perlin.cpp, line 540

![obrazek](https://cloud.githubusercontent.com/assets/491088/25152704/372338a8-248a-11e7-9f56-c9361f52e096.png)

```
>	RoR.exe!Hydrax::Noise::Perlin::_readTexelLinearDual(const int & u, const int & v, const int & o) Line 541	C++
 	RoR.exe!Hydrax::Noise::Perlin::_getHeigthDual(float u, float v) Line 560	C++
 	RoR.exe!Hydrax::Noise::Perlin::getValue(const float & x, const float & y) Line 406	C++
 	RoR.exe!Hydrax::Module::ProjectedGrid::getHeigth(const Ogre::Vector2 & Position) Line 840	C++
 	RoR.exe!Hydrax::Hydrax::getHeigth(const Ogre::Vector2 & Position) Line 435	C++
 	RoR.exe!Hydrax::Hydrax::getHeigth(const Ogre::Vector3 & Position) Line 448	C++
 	RoR.exe!HydraxWater::getHeightWaves(Ogre::Vector3 pos) Line 151	C++
 	RoR.exe!HydraxWater::isUnderWater(Ogre::Vector3 pos) Line 89	C++
 	RoR.exe!Beam::calcNodes(int doUpdate, float dt, int step, int maxsteps) Line 1835	C++
 	RoR.exe!Beam::calcForcesEulerCompute(int doUpdate, float dt, int step, int maxsteps) Line 118	C++
 	RoR.exe!BeamFactory::UpdatePhysicsSimulation::__l17::<lambda>() Line 1182	C++
 	[External Code]	
 	RoR.exe!ThreadPool::Parallelize(const std::vector<std::function<void __cdecl(void)>,std::allocator<std::function<void __cdecl(void)> > > & task_funcs) Line 189	C++
 	RoR.exe!BeamFactory::UpdatePhysicsSimulation() Line 1200	C++
 	RoR.exe!BeamFactory::update::__l45::<lambda>() Line 1116	C++
 	[External Code]	
 	RoR.exe!ThreadPool::{ctor}::__l2::<lambda>() Line 136	C++
 	[External Code]	
```

Hardware: CPU: Intel i5-3570K, GPU: GeForce 660 GTX
Environment: Win7 x64, Visual Studio 2015, Dependencies by SpeciesX (2016-05-14)
Scenario: Open auriga, spawn Tatra-Dakar 8x8, then spawn Agora S - sooner or later, it crashes.
[logs + configs.zip](https://github.com/RigsOfRods/rigs-of-rods/files/930989/logs.configs.zip)

**Comment by only-a-ptr** [comment]
Already crashes at 39722096d2b43a27fe58dec52a75ac8e754122f2

**Comment by Michael10055** [comment]
I can't recreate this on the latest master. I've left RoR open for ~10 mins, and still no crash. Even tried driving into the water with both vehicles activated.
![ror_2017-05-01_11-32-17](https://cloud.githubusercontent.com/assets/11002490/25584158/db80f80e-2e62-11e7-8d9f-114a7f6a729f.png)

**Comment by only-a-ptr** [comment]
@Michael10055 Hmm... maybe it was caused by the "water stuck at height 0" issue and thus resolved by https://github.com/RigsOfRods/rigs-of-rods/pull/1323

Thanks for testing. I'm closing this, we can reopen if necessary.
