### ISSUE TITLE
RoR is still broken (for me it is)

### ISSUE THREAD

**Issue by Meheh** [RigsOfRods/rigs-of-rods#1321]
I don't know why, reinstalled it twice and it still does crash on me.

**Comment by vido89** [comment]
try moving repository to another dir and than lunch RoR, just guessing

**Comment by Meheh** [comment]
@vido89 Well im pretty sure is something wrong with the crashfix

**Comment by Michael10055** [comment]
CrashFix not being functional shouldn't cause RoR to crash on startup.

**Comment by Meheh** [comment]
I could send you a dxdiag @Michael10055
