### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by MggMuggins** [RigsOfRods/rigs-of-rods#1329]
Alright, so this game looked cool, so I thought I'd try and build it. I'm on Ubuntu 16.04 (don't judge, probably switching to Manjaro...), so I grabbed the buildscripts and went ahead. I edited a few things to make them work, and reviewed a PR to the buildscripts repo (really needs to get merged...)...

Anyway, I got everything build. Builds went great, no issues with make, cmake, or any of the sources for anything (although gettting Ogre was challenging...). I ran RoRConfig, like it said in the readme, and up popped a dialouge that said this:
"Unable to load the render systems. Please check if all required files are there and the plugins.cfg file is correct.
This is a fatal error and the game will not start."
Here's the last bit of output from the console:
```
Installing plugin: Caelum
Caelum plugin version 0.6.3 installed
Registering ResourceManager for type PropertyScript
Plugin successfully installed
05:56:39 PM: Root restore config

** (RoRConfig:5819): CRITICAL **: murrine_style_draw_box_gap: assertion 'height >= -1' failed
05:57:04 PM: Showing dialog

05:57:04 PM: App ready
```
I'm not sure what it means by required files, and I don't know what a correct plugins.cfg looks like either, so I'm not really sure how to diagnose the issue other than to just ask. Thanks in advance for any help. I really appreciate it.

**Comment by vido89** [comment]
Which branch did you pulled ? try tags 0.4.7.0 Im not sure :)

**Comment by MggMuggins** [comment]
I only pulled a shallow copy of this repo. Let me pull the full version and I'll get back to you.

**Comment by tritonas00** [comment]
Your plugins.cfg is wrong, check mine https://pastebin.com/3vdSMi5T, change the paths to your system and retry

**Comment by MggMuggins** [comment]
I'm wondering if it's just that I don't have the right plugins in the OGRE folder. Here's the contents of that:
![ogrecontents](https://cloud.githubusercontent.com/assets/16041213/26587098/fa742d74-4516-11e7-8b83-526f9743e6df.png)
Will an absolute path work for the liibCaelum.so or does it have to be relative? I've tried both and neither get me anywhere.

**Comment by tritonas00** [comment]
Can you post your plugins.cfg please and `ls OGRE`?

**Comment by MggMuggins** [comment]
```sh
$ ls OGRE
libCaelum.so
```
I'm fairly sure that shared library is a link of some kind, not the actual file. Here's plugins.cfg (with a few path edits, for privacy)
```
# Defines plugins to load

# Define plugin folder
PluginFolder=/home/******/rigs-of-rods/install/lib/OGRE

# Define plugins
Plugin=RenderSystem_GL
Plugin=Plugin_ParticleFX
Plugin=Plugin_OctreeSceneManager
Plugin=Plugin_CgProgramManager
Plugin=../../../../../../../../../../../../home/******/rigs-of-rods/install/lib/libCaelum.so
```

**Comment by tritonas00** [comment]
in my OGRE dir i have

> /opt/rigsofrods/lib/OGRE/Plugin_BSPSceneManager.so
/opt/rigsofrods/lib/OGRE/Plugin_BSPSceneManager.so.1.8.1
/opt/rigsofrods/lib/OGRE/Plugin_CgProgramManager.so
/opt/rigsofrods/lib/OGRE/Plugin_CgProgramManager.so.1.8.1
/opt/rigsofrods/lib/OGRE/Plugin_OctreeSceneManager.so
/opt/rigsofrods/lib/OGRE/Plugin_OctreeSceneManager.so.1.8.1
/opt/rigsofrods/lib/OGRE/Plugin_OctreeZone.so
/opt/rigsofrods/lib/OGRE/Plugin_OctreeZone.so.1.8.1
/opt/rigsofrods/lib/OGRE/Plugin_ParticleFX.so
/opt/rigsofrods/lib/OGRE/Plugin_ParticleFX.so.1.8.1
/opt/rigsofrods/lib/OGRE/Plugin_PCZSceneManager.so
/opt/rigsofrods/lib/OGRE/Plugin_PCZSceneManager.so.1.8.1
/opt/rigsofrods/lib/OGRE/RenderSystem_GL.so
/opt/rigsofrods/lib/OGRE/RenderSystem_GL.so.1.8.1

**Comment by MggMuggins** [comment]
Huh. Oh wait, I didn't build OGRE. I installed it with apt, so there may have been some things I didn't get. I was having a lot of trouble getting the source (Mercurial, eww, plus super slow internet), so I just grabbed it from the software repos, already built of course. I did grab the dev package.

**Comment by tritonas00** [comment]
so just change your plugins.cfg to:

`PluginFolder=/usr/lib/OGRE`

**Comment by MggMuggins** [comment]
Alright. That did it. Now that I've got RoR running, I'm getting segfaults whenever I try to load a world. It's unrelated, so if you'd like me to open another issue, I can. Here's the log, if there's anything useful in there:
[Log](https://pastebin.com/gn22JkPP)

**Comment by Michael10055** [comment]
Try to use Sandstorm instead of Caelum sky.

**Comment by MggMuggins** [comment]
Worked like a charm. Thanks!
