### ISSUE TITLE
Fixes not working

### ISSUE THREAD

**Issue by Aivar-RoR** [RigsOfRods/rigs-of-rods#133]
Fixes are not working. http://www.rigsofrods.com/wiki/pages/Truck_Description_File#Fixes
The vehicle/scenery object that has fixes falls through the ground.
For example try using the bridge or port crane in North St. Nelens.

**Comment by only-a-ptr** [comment]
A new, more elaborate issue was open on this topic: https://github.com/RigsOfRods/rigs-of-rods/issues/162
I'm closing this one.
