### ISSUE TITLE
RoRConfig layout broken on high-dpi displays on linux

### ISSUE THREAD

**Issue by lheckemann** [RigsOfRods/rigs-of-rods#1335]
![rorconfig text spilling out of boxes](https://user-images.githubusercontent.com/341954/27027548-cc32c464-4f59-11e7-99c3-d2189736e608.png)

Making the window bigger does not improve the situation.

**Comment by only-a-ptr** [comment]
:rofl: Wow, what a challenge!

RoRConfig is (partially) made the old-fashioned way where widgets are positioned directly by pixel offsets. So even though the wxWidgets GUI library seems to handle the DPI just right where Sizers are used, the layout gets squashed where pixels are used.

Looks like upgrading to wxWidgets 3.1.x would help -  from https://raw.githubusercontent.com/wxWidgets/wxWidgets/v3.1.0/docs/changes.txt:

> Many improvements for high DPI monitors support, notably XRC now interprets
  all pixel values as being in resolution-independent pixels.

**Comment by tritonas00** [comment]
so maybe this is not an issue anymore?

**Comment by lheckemann** [comment]
Using wxGTK 3.1 didn't fix this for me.
