### ISSUE TITLE
Increasing node/beam limit?

### ISSUE THREAD

**Issue by Michael10055** [RigsOfRods/rigs-of-rods#1336]
I know this has been talked about before, but @fidoj mentioned one of his creations crashes RoR because it goes over the node/beam limit. I increased the node limit to 5000 and the beam limit to 10000 to test. I expected the FPS to decrease and/or memory usage to increase. However, comparing the latest master to a build with the increased limits, the performance is basically identical:
latest master:
![ror_2017-06-12_17-48-06](https://user-images.githubusercontent.com/11002490/27060537-994f0ab0-4fab-11e7-826b-5e8c197096e9.png)
![taskmgr_2017-06-12_17-48-24](https://user-images.githubusercontent.com/11002490/27060541-a41d9f42-4fab-11e7-85c8-33bf7abf3394.png)
increased limit:
![ror_inbl_2017-06-12_17-49-11](https://user-images.githubusercontent.com/11002490/27060555-c2301096-4fab-11e7-9b13-eccde5c33146.png)
![taskmgr_2017-06-12_17-49-24](https://user-images.githubusercontent.com/11002490/27060560-c8357e40-4fab-11e7-8ace-15f1c9c8753f.png)
as you can see, basically identical performance.
To test this yourself, just edit the `MAX_NODES` and `MAX_BEAMS` limit in `BeamConstants.h`:
```
static const int   MAX_NODES                  = 5000;            //!< maximum number of nodes per truck
static const int   MAX_BEAMS                  = 10000;            //!< maximum number of beams per truck
```
then download the `20_4_platform.zip` file from #1250.
fps/memory usage with the platform (1143 nodes, 5596 beams total):
![ror_inbl_2017-06-12_19-51-49](https://user-images.githubusercontent.com/11002490/27060685-73349e66-4fac-11e7-9c50-e13a298663cc.png)
![taskmgr_2017-06-12_19-52-00](https://user-images.githubusercontent.com/11002490/27060692-77a8a85c-4fac-11e7-9af5-a891f12ad59b.png)
So, would it be possible to increase these limits for the next release?

**Comment by fidoj** [comment]
wow comparing these creations directly really shows how much of a impact flexibodies adds. comparing these 2 vehicles is akin to comparing a civic to the space shuttle.

**Comment by L-Tec** [comment]
definetly YES  🗡

**Comment by only-a-ptr** [comment]
Actually, there's no need to have any sort of limits anymore. They were necessary before 0.4.5 where truckfile parsing+spawning happened on-the-fly and RoR didn't know the amount of nodes/beams until the vehicle was complete. Current RoR parses first and spawns later, so we know everything and we can simply dynamically allocate exactly the amount of memory we need.

I'll create a test branch for you to build and test.
