### ISSUE TITLE
ROR crashing in the latest build

### ISSUE THREAD

**Issue by L-Tec** [RigsOfRods/rigs-of-rods#1338]
Hi folks,

using the last build downloaded today on 06-16-17, i only get one terrain running, and that loads quite odd.

![](https://cdn.discordapp.com/attachments/321324720685449219/325349805364609024/screenshot_2017-06-16_21-03-35_1.jpg)

Same terrain working in the 0.4.7 version:

![](https://cdn.discordapp.com/attachments/321324720685449219/325350294143631371/screenshot_2017-06-16_21-05-36_1.jpg)

All other terrains generate a crash while loading. RoR logs looking ok for me.

Specs: WIn10/VS 2015/Cmake3.8.2

I tested a bit togther with Michael, we get no clue, what is going wrong there.

Any ideas ?

**Comment by L-Tec** [comment]
RoR-Log attached:

[RoR_log.txt](https://github.com/RigsOfRods/rigs-of-rods/files/1081791/RoR_log.txt)

**Comment by fidoj** [comment]
![screenshot_2017-06-17_13-30-32_1](https://user-images.githubusercontent.com/12094306/27250411-7c4cf170-5361-11e7-97fe-e874851a413b.jpg)
perhaps its your copy of the map?

**Comment by L-Tec** [comment]
No, the same map is working in 0.4.7 (like all others) and is the only one not crashing but showing a simple green field in the BUILD version

**Comment by AnotherFoxGuy** [comment]
After removing the AngelScript races the map loads normally, so I think this will fix it: https://github.com/RigsOfRods/ror-dependencies/pull/15

**Comment by fidoj** [comment]
i think lifter is using vs2015 are there any differences between the 2 sets of dependencies or can he test with deps appveyor compiled here
https://ci.appveyor.com/project/AnotherFoxGuy/ror-dependencies/build/31-meoqktix/artifacts

**Comment by Michael10055** [comment]
Besides the VS version they were compiled with, the deps should be the same. I compiled the VS 2015 deps and they work without issues for me.

**Comment by Michael10055** [comment]
Caused by: #1355
