### ISSUE TITLE
Vehicles with fusedrag autocalc cannot be driven

### ISSUE THREAD

**Issue by Aivar-RoR** [RigsOfRods/rigs-of-rods#134]
A vehicle that has autocalculated fusedrag cannot be driven, the engine is running but the vehicle doesn't move. Switching gears isn't possible.
http://www.rigsofrods.com/wiki/pages/Truck_Description_File#Fusedrag
Vehicle used: http://www.rigsofrods.com/repository/view/5226
(Freightliner FS-65)

The line from the truck file:
>fusedrag
21,5, autocalc, 0.1

Everything is OK when the line is commented out.

**Comment by Hotrod55** [comment]
Bumping this as this is a bug that should be fixed ASAP. Breaks many mods.

**Comment by Max98** [comment]
@only-a-ptr You should take a look at this one.

**Comment by only-a-ptr** [comment]
*Tick* ... resolved :smiley:
