### ISSUE TITLE
Flare/Beam materials do not load if using managedmaterials

### ISSUE THREAD

**Issue by Michael10055** [RigsOfRods/rigs-of-rods#1341]
Wilkgr originally reported this on Discord, and it looks like i've found the cause of it.

On the E36 (download [here](https://drive.google.com/file/d/0B-ek0REpYlOpMTNwTFMyZ1V6cnM/view?usp=drivesdk)) there is white squares where the (invisible) flare texture would be. Happens on both versions of the vehicle.
![ror_2017-06-20_23-39-42](https://user-images.githubusercontent.com/11002490/27388418-6c0a4b72-5669-11e7-9580-30a9a4ad7801.png)

The material is defined using `managedmaterials`. Some vehicles use a invisible flare texture so they can define `materialflarebindings` without an actual flare visible.
I had used this same 'trick' on the 2014 Superduty while testing, didn't make it into the final release though. But that used the default `tracks/trans` material, which is defined in a `.material` file.
```
managedmaterials
gavrilinvis			mesh_transparent	gavrilinvis.dds		-
```
```
flares2
;RefNode,X,Y,OffsetX, OffsetY, OffsetZ, Type, ControlNumber, BlinkDelay, Size, MaterialName

;LEFT REAR BRAKES

78,77,100, 0.800, 0.090, 0.200, b, -1, 0, 0.14 gavrilinvis

etc..
```
Defining the `gavrilinvis` material in a `.material` instead of using `managedmaterials` prevents it from happening.
```
material gavrilinvis
{
	technique
	{
		pass
		{
   			alpha_rejection greater 255
   
   			texture_unit
   			{
				texture gavrilinvis.dds

			}
		}
		
	}
}
```
This does not happen on a older build (before #1271)

**Comment by only-a-ptr** [comment]
ManagedMaterial on a flare... I didn't think about this scenario 😄

It's broken because managedmaterials are now generated with unique per-vehicle name, so gavrilinvis becomes "gavrilinvis0@Actor1" or such. I need to add a post-processing step where I resolve flare mat. names against managedmaterial orig. names.

However, RoR should really provide an option to disable flares (and other gfx like meshwheels/cabs) instead of forcing modders to use invisible material tricks.

**Comment by Michael10055** [comment]
Beam materials defined using `set_beam_defaults` also don't load if its using `managedmaterials`:
```
managedmaterials
tracks/greyreflectivebeam mesh_standard greyreflectivebeam.png greyreflectivebeam-spec.png

set_beam_defaults 39000000, 2000, 1000000, 8000000, 0.05, tracks/greyreflectivebeam, 0.1

```

![image](https://user-images.githubusercontent.com/11002490/30213365-bcb02c36-9476-11e7-80fe-6a54221240bf.png)
