### ISSUE TITLE
Customizing smoke particles

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#1349]
Question by Disloyalpick (source: https://github.com/RigsOfRods/rigs-of-rods/pull/1271#issuecomment-314598172):
> I'm not sure if this is where to put it, but is there a way to change the default smoke to a gas like color exhaust smoke? I've tried everything, by putting the .material and .particle files into my vehicles zip, but I just can't get it to change the color of the exhaust. Is the black color hardcoded or something?

Well, the `textures/smoke.dds` image is white (picture from VisualStudio 2015, the green-ish checkerboard is transparency):
![obrazek](https://user-images.githubusercontent.com/491088/28095065-a01019b4-66a0-11e7-8514-e936a8b25149.png)

the `material tracks/SmokeMat` material (file: particles/particles.material) doesn't specify color.

However, the `particle_system tracks/Smoke` particle definition (file: particles/smoke.particle) contains this:
```
   	emitter Point
   	{
		angle               		11
 	      	emission_rate       		125
       		direction           		0 1 0
		velocity	2
		velocity_min	1
		velocity_max	4
		time_to_live	22
		time_to_live_min	22
		time_to_live_max	50
		colour  0.0, 0.0, 0.0, 0.4
	}
```

Try changing the `colour  0.0, 0.0, 0.0, 0.4` to see if it does the trick.

I don't have modding experience, but I assume you need to copy the particle definition, give it a new name and color and bundle it with your truck.

**Comment by disloyalpick** [comment]
I've tried changing the colour parameters and it just resulted in no change at all.

**Comment by only-a-ptr** [comment]
Interesting...

What color(s) did you try? Try changing other parameters to see what happens. Also try switching the material or texture to see if there's any effect.

**Comment by Michael10055** [comment]
Closing this as the default particles.material has `lighting off` in its pass which prevents colors from being recognized:
https://github.com/RigsOfRods/rigs-of-rods/blob/master/resources/particles/particles.material#L90
