### ISSUE TITLE
Trucks with space in filename crash RoR on multiplayer?

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#1350]
A friend on Skype just told me this story - a truck with space in filename works OK in singleplayer but crashes RoR in multiplayer.

I need to check.

**Comment by disloyalpick** [comment]
I can confirm this asking with many many others. Drop by discord sometimes and ask about a problem there and you will get a pretty big response

**Comment by Michael10055** [comment]
Spaces in the name always don't work in multiplayer. But it usually ends up in others not seeing your vehicle, not a crash.

**Comment by Michael10055** [comment]
Just tested this using https://archives.rigsofrods.org/repo/repofiles-3rd-batch/d2dd134ec2af44c1e8f50bea8205c9c9670e7909_ChevroletExpress.zip - no crash here.

**Comment by only-a-ptr** [comment]
@Michael10055 Thanks for testing!
