### ISSUE TITLE
Having Default Map Set in RoRConfig 

### ISSUE THREAD

**Issue by disloyalpick** [RigsOfRods/rigs-of-rods#1353]
Here is what happens.

You are testing a mod on Simple2.terrn2 and you get the mod to a good state to where you want to drive around on an actual map and get a more thorough testing in. Press ESC, then click Change Map. Map will unload, and then will go back to the main menu. Clicking Single Player will force RoR to load the map that is set , but IMHO I think that after the game is loaded it can ignore that parameter until a restart of the game. 
I think this would be a pretty good feature to add in case someone wants to hop from a pre-spawned map into another one without having to restart RoR.

**Comment by disloyalpick** [comment]
This is still relevant

Steps to reproduce...

1. Set a pre-Selected map in RoR-Config `EG. Simple2`

2. Save and play from RoR-Config.

3. Then Press `ESC` and click `Back to Menu`

4. Click `Single Player` and it will force you to spawn into the pre-selected terrain

IMHO I think this shouldn't happen. I think after RoR is started and the pre-selected terrain is spawned it shouldn't force it to load if you want to go back to the main menu and select a different map. Instead, it forces you to load straight back into the pre-selected map.

**Comment by only-a-ptr** [comment]
@disloyalpick You're right, this shouldn't happen. Sorry for not picking up this task earlier.

**Comment by disloyalpick** [comment]
+1
