### ISSUE TITLE
Vehicle's HUD in first person view

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1356]
Spawn a vehicle and press `c` to enter first person view. HUD disappears and that's fine. I think the user should be able to bring back the HUD by pressing `u` in first person view, like in previous versions, because in latest master that's not the case.

Thanks! :blush:

**Comment by disloyalpick** [comment]
I agree. Would be useful for the vehicles that do not have a  dashboard/ gauges present in 1st person view.

**Comment by Michael10055** [comment]
Do you know which commit prevented the HUD from showing?

**Comment by tritonas00** [comment]
#1271

**Comment by tritonas00** [comment]
is this an easy one for 0.4.8?

It's another RoR's gravestone (#1271) issue :laughing:

**Comment by tritonas00** [comment]
fixed in #1538
