### ISSUE TITLE
Tiedowns/Ropables not working with truck/trailer combo

### ISSUE THREAD

**Issue by droem** [RigsOfRods/rigs-of-rods#1358]
When I load something on any trailer with any truck and I press O to tie it down, it will not tie it down. And there is no look for the tie downs.

**Comment by Michael10055** [comment]
Are you using 0.4.7.0? If so, this a bug that was fixed already.

**Comment by only-a-ptr** [comment]
Hi @droem, please post your "RoR.log". It's in "MyDocuments\Rigs of Rods 0.4\logs\".

**Comment by Michael10055** [comment]
Almost 10 days without a reply, closing for now.
