### ISSUE TITLE
Remove flashing selection cursor from in-game settings

### ISSUE THREAD

**Issue by Aivar-RoR** [RigsOfRods/rigs-of-rods#136]
Would it be possible to disable the flashing selection cursor where it isn't needed?
The only boxes that need the selection cursor are FOV and the ones in the multiplayer tab (nickname, server address, ip, password and user token), which is currently disabled.
If you click on a drop down list the cursor starts flashing, if you want to open the list you have to click on the little orange arrow.

![3](https://cloud.githubusercontent.com/assets/11720273/6897948/744f31d0-d6ff-11e4-92ad-d936778eb37d.png)

**Comment by Max98** [comment]
I'm not sure but that's the way MyGUI handles the cursor ;(
Will take a deeper look.

**Comment by Max98** [comment]
Annnd done!
