### ISSUE TITLE
Crash when loading Dodge Magnum Drifter

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1360]
[log.txt](https://github.com/RigsOfRods/rigs-of-rods/files/1191302/log.txt)

**Comment by disloyalpick** [comment]
Seems like it crashed while loading the sound script file. Maybe check for spelling errors or mismatched for names?

**Comment by Speciesx** [comment]
> #FF3300 FATAL ERROR #FFFFFF: Missing required section 'nodes'
#FF3300 FATAL ERROR #FFFFFF: Missing required section 'beams'

I think this the reason.

**Comment by only-a-ptr** [comment]
Can you post me a download link to the vehicle?

The log indicates the vehicle uses "[sectionconfig](http://docs.rigsofrods.org/vehicle-creation/fileformat-truck/#sections)" feature and that it puts nodes and beams in a section. It looks like RoR has issues with that.

**Comment by Michael10055** [comment]
@only-a-ptr https://www.rigsofrods.org/old-forum/forums/117-Light-Vehicles/91358/attached-files/magnum.zip

**Comment by only-a-ptr** [comment]
Ok, only managedmaterials are in "sections", but the log reports otherwise... looks like a parser issue.

**Comment by tritonas00** [comment]
> Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
Beam::calc_masses2 (this=this@entry=0x8eb3300, total=64, reCalc=reCalc@entry=false)
    at /home/babis/Downloads/rigsofrods-next-build-debug/rigsofrods-debug/src/rigs-of-rods/source/main/physics/Beam.cpp:924
924	        nodes[cinecameranodepos[i]].mass = m_definition->root_module->cinecam[i].node_mass;

https://pastebin.com/CrGkiS91

**Comment by only-a-ptr** [comment]
@tritonas00 Just as I thought - the parser has a problem with sectionconfig. It misses the `end_section` keyword somehow and stuffs everything in one of the sections (I call them "modules"). As a result, the required root module is missing

**Comment by Speciesx** [comment]
@only-a-ptr 

https://github.com/RigsOfRods/rigs-of-rods/pull/1362 hasn't fixed the crash.
