### ISSUE TITLE
Heap corruption happens

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#1366]
### *******************************************************************

To laymen: heap corruption is a problem with dynamic RAM allocation and practically means: there's a bug  somewhere in RoR which trashes our data in RAM, it's extra hard to find and it can theoretically crash RoR anytime for anybody 😟 

Links:
* http://www.ogre3d.org/forums/viewtopic.php?f=4&t=93326 - OGRE forum thread about this problem.
* https://github.com/RigsOfRods/rigs-of-rods/pull/1365#issuecomment-322283414 --- user tritonas00, linux, crash spawning 'bombinette.load' from "miniredmars" map.
* https://github.com/RigsOfRods/rigs-of-rods/issues/1256#issuecomment-322307172 --- user Bob-Z, linux, spawning 'bombinette.load' from "miniredmars" map.
* (update) https://github.com/RigsOfRods/rigs-of-rods/issues/1256#issuecomment-322427494

I'm trying to use [Microsoft Application Verifier](https://technet.microsoft.com/en-us/library/bb457063.aspx) to track it down, but I'm getting stuck on renderer init - both renderers exhibit some memory issues which halt the AppVerifier.

**Comment by tritonas00** [comment]
So you can reproduce the crash with opengl renderer?

**Comment by only-a-ptr** [comment]
@tritonas00 Nope, miniredmars spawns OK for me with OpenGL. But I'm getting other weird crashes.

**Comment by tritonas00** [comment]
> Same output!

Nice, now you don't need to search the whole RoR :smile:

**Comment by only-a-ptr** [comment]
I just built 9fec1839229115da550d77b5414ae1b3645ccbdd from upstream - worked like a charm. I'll investigate from there.

**Comment by only-a-ptr** [comment]
It turned out a lot of the heap corruption issues with my "unlimited-nb" were my fault - I simply allocated less memory than was needed. There are still mysterious crashes going on, but it's no longer as freaky.

**Comment by tritonas00** [comment]
The proposed solution here https://github.com/RigsOfRods/rigs-of-rods/issues/1256#issuecomment-322307172 fixes the miniredmars issue here also.

**Comment by only-a-ptr** [comment]
> @tritonas00 The proposed solution here #1256 (comment) fixes the miniredmars issue here also.

It looks like I caused this breakage with https://github.com/RigsOfRods/rigs-of-rods/commit/8eeb0609f391da1d247de251ca9df3ede8db31a5.

**Comment by only-a-ptr** [comment]
Closing as resolved:
* There was a bug in 'wheels[2]' - if it had odd number of rays, memory corruption happened: https://github.com/RigsOfRods/rigs-of-rods/issues/1256#issuecomment-352469930 - Fixed.
* When removing the N/B limits, I made several bugs in memory size calculation, causing more corruption. Fixed.
