### ISSUE TITLE
Allow non-vehicle keys to be used during freecam

### ISSUE THREAD

**Issue by wilkgr76** [RigsOfRods/rigs-of-rods#1368]
By "non-vehicle keys", I mean keys that do not directly influence the vehicle's position/movement. This is keys such as slow-motion, headlights and horn. Other keys, that should not be included, include parking brake and reset.

It's simply annoying to have to exit freecam to disable slow motion. If I knew my way around C++, I'd do it myself, but I don't :/

**Comment by Michael10055** [comment]
Could activate fixed camera with `ALT+C` then switch back to freecam.

**Comment by wilkgr76** [comment]
Good point
