### ISSUE TITLE
Something happens when opening the game

### ISSUE THREAD

**Issue by rizicks** [RigsOfRods/rigs-of-rods#1369]
Y'know when you load up the game and you have to wait for the vehicles to load?

Well it does that but it'd take forever to load, sometimes it'd take an hour to load

I dont know what's happening.

**Comment by Michael10055** [comment]
By "vehicles to load" you mean a cache regen. It shouldn't take long, even if you have many mods. Do you have any mods installed?

**Comment by rizicks** [comment]
I never did a cache regen, but okay.

**Comment by Michael10055** [comment]
RoR will automatically do a regen for you if you add/remove a mod, it doesn't matter if you press the regen button. Only advice I have for you is to click the "Clear Cache" button and let RoR regenerate the cache from the ground up. If it still happens, remove all your mods and re-add them in groups till you begin to experience the issue.
