### ISSUE TITLE
Crash when unloading some maps

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1374]
Load Auriga and then Back to menu or Exit. Sometimes works, most of the time crashes.

gdb https://pastebin.com/59sY0v2C
valgrind https://pastebin.com/iRUbNKJD

https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/terrain/TerrainManager.cpp#L601

**Comment by only-a-ptr** [comment]
I guess I came across this as well. I'll look into it soon.

**Comment by tritonas00** [comment]
Also Exit leads to segfault with Auriga

**Comment by only-a-ptr** [comment]
@tritonas00 Please try with https://github.com/RigsOfRods/rigs-of-rods/pull/1417

**Comment by tritonas00** [comment]
unfortunately i'm away from home and i'm stuck with a tablet

i will try next week asap!

**Comment by tritonas00** [comment]
fixed in #1417
