### ISSUE TITLE
Advanced logging not working with node and beam objects

### ISSUE THREAD

**Issue by Aivar-RoR** [RigsOfRods/rigs-of-rods#138]
Although advanced logging is enabled, only logs pertaining to mesh objects appear in the logs folder.
No logs for spawned trucks or for those that are placed on a terrain.
Advanced logging is enabled in the config file (also the boxes are checked in the external Configurator and ingame debug options).

**Comment by Max98** [comment]
I believe that because of the new parser, that feature is kind of broken and should be removed, because it is replaced by the "Spawner Log"

**Comment by Aivar-RoR** [comment]
Currently clicking on *Spawner Log* seems to do nothing, The log is displayed only when the console window is also opened. 
Advanced logging had an advantage over the spawner log: it saved a .html log you could view later. The spawner log has no such functionality, if you close RoR, you still have to scroll through RoR.log (which doesn't have different colours for different errors like the .html logs did).

**Comment by Max98** [comment]
Fixed the Spawner Log not showing up: https://github.com/Max98/ror_nextstable_gui/commit/1cc9ca07cd111c64bf0fa0ab9033ee43cb63ca68

I'm not sure but maybe @only_a_ptr will improve his spawner log. :P

**Comment by only-a-ptr** [comment]
I'll look into this.
However, I think that whith development of RigEditor, the need of detailed post-analysis of beam elements will be fairly lower.

**Comment by AnotherFoxGuy** [comment]
Advanced logging has been removed in https://github.com/RigsOfRods/rigs-of-rods/commit/06fbd8960926ed29d343ce81abb9dc32fb70410c
