### ISSUE TITLE
Is this supposed to happen?

### ISSUE THREAD

**Issue by rizicks** [RigsOfRods/rigs-of-rods#1380]
![ror 2017-09-16 09-27-23-14](https://user-images.githubusercontent.com/26100468/30513985-00186b40-9ac2-11e7-84ab-d66535fc9896.png)

**Comment by tritonas00** [comment]
That's spooky...

**Comment by only-a-ptr** [comment]
@rizicks Is it even a RoR screenshot? 😆 Doesn't really look that way.

**Comment by rizicks** [comment]
@only-a-ptr It is a RoR screenshot lol... i just use fraps for screenshots.

**Comment by only-a-ptr** [comment]
@rizicks RoR screenshot of what? Which map/vehicle/ror version is that?
Please post "RoR.log", it's under MyDocuments\Rigs of Rods 0.4\logs

**Comment by Michael10055** [comment]
Almost a week without a reply, closing this for now. The only way I can see this happening is if you alt+tab while RoR is in full screen (#746).
