### ISSUE TITLE
Vehicle Selector: Mass and Load Mass doesn't show up

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1390]
![111](https://user-images.githubusercontent.com/1196375/30782503-b1a021ce-a133-11e7-80a0-b797ba644d1b.png)

https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/gui/panels/GUI_MainSelector.cpp#L814-L817

**Comment by only-a-ptr** [comment]
@Speciesx Now that you brought up the Loader UI, I'm going to remake it as part of https://github.com/RigsOfRods/rigs-of-rods/pull/1333 , so if you have any suggestions for improvement, please draw me a mockup as you did in https://github.com/RigsOfRods/rigs-of-rods/issues/1254. I think the current UI shows too much data at once, even without the mass info (I'll fix that of course).

**Comment by only-a-ptr** [comment]
The oldest working version I found (february 2011): https://github.com/only-a-ptr/ror-legacy-svn-trunk/blob/71d1ea1f31ad3eba3cdd68f454b7b2a41ec36b6a/source/main/gameplay/CacheSystem.cpp#L1613-L1614
