### ISSUE TITLE
How come the tractors dont start?

### ISSUE THREAD

**Issue by rizicks** [RigsOfRods/rigs-of-rods#1391]
For some reason one the tractors wont start. Heres what happened on one of them (watch the speedometer when starting)

![ror_2017-09-26_21-21-00-510](https://user-images.githubusercontent.com/26100468/30895854-c1fe122c-a301-11e7-8007-2b008fcde339.gif)

**Comment by disloyalpick** [comment]
This is not a support area. Please go to the forum if you want help.

**Comment by rizicks** [comment]
@disloyalpick Ok.
