### ISSUE TITLE
Collision limit for maps.

### ISSUE THREAD

**Issue by DarthCainRor** [RigsOfRods/rigs-of-rods#1395]
So when .39+ was released, it was said that the collision limit for maps, had basically been removed, and you no longer had to worry about them. As I've been working on the Community map, I've noticed that not to be the case, as there seems to be a hard coded limit, that causes the log to repeatedly say `COLL: The hashtable is full.` once the limit is reached, thus freezing the game upon attempting to load said map.

**Comment by Michael10055** [comment]
https://github.com/RigsOfRods/rigs-of-rods/blob/672cc4655c9b28cd8ac8eb6fc7559145362af434/source/main/physics/collision/Collisions.h#L68

**Comment by only-a-ptr** [comment]
Now that you brought it up, I took another look at the sourcebase. There's no sign of any attempt to lift the limits - the patches must have gotten lost, the development was somewhat fragmented between .38.XX and 0.4.0.X

Anyway, it looks like I could quite easily replace the static-size arrays with scalable ones. I'll whip up a test branch, but I don't have time to test myself, and I frankly can't be bothered to study RoR's static collision system - even though I'm not very versed in hashing and space partitioning, the code feels very wrong.

**Comment by only-a-ptr** [comment]
BUMP! Test branch ready and actually looking very good, see the PR link above.
