### ISSUE TITLE
Skinzips are not working

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#14]
Choose a vehicle that uses a Skinzip.
Vehicle: http://www.rigsofrods.com/repository/view/4340
Skin: http://www.rigsofrods.com/repository/view/5296

**Comment by Max98** [comment]
@only-a-ptr How's this coming along?

**Comment by only-a-ptr** [comment]
Fixed in 8c72d3553be549fd6b99ffca44d5f8c1192bf9a6
