### ISSUE TITLE
New truck parser ignores hookgroups in triggers

### ISSUE THREAD

**Issue by Aivar-RoR** [RigsOfRods/rigs-of-rods#140]
It seems that the new truck parser ignores hookgroups in the triggers section.
http://www.rigsofrods.com/wiki/pages/Truck_Description_File#Triggers
From the log:
>15:49:38:  ===== LOADING VEHICLE: b940UID_dhg700c.train
15:49:38:  == Parsing vehicle file: b940UID_dhg700c.train
15:49:39:  == Parsing done, report:
#FF3300 ERROR #FFFFFF (Section triggers)
	Line (1027): 83,  80, 0.900, 10.000, -32, -32, ich
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section triggers)
	Line (1028): 83,  80, 0.900, 10.000, -31, -31, icH
	Message: Invalid line, ignoring...

The same hookgroups are used in the hooks section, but they don't cause any errors.

Vehicle used: http://www.rigsofrods.com/repository/view/4340

**Comment by only-a-ptr** [comment]
Fixed in e3c47cb99577b89b01603652b83cd84ef2bfc6ac
