### ISSUE TITLE
RoRConfig crashes when Documents\Rigs of Rods 0.4 doesn't exist 

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#1400]
**Expected behaviour:** RoRConfig should create Documents\Rigs of Rods 0.4 and extract skeleton.zip 
**Actual behaviour:** RoRConfig creates Documents\Rigs of Rods 0.4 and crashes

**Comment by only-a-ptr** [comment]
I found the issue - something's wrong with the 'recursive_zipper.py' script; the generated zipfile contains only the files (with paths containing a subfolder), but no entries for the subfolders themselves. Hence the subfolders are never created and file unzipping fails.

I debugged with both auto-created 'skeleton.zip' (Windows7 SP1 64bit, Python 3.6.3) and a hand-created one (TotalCommander's internal zipper).

**Comment by only-a-ptr** [comment]
Resolved by #1401
