### ISSUE TITLE
RoR install ubuntu errors

### ISSUE THREAD

**Issue by saltzstang** [RigsOfRods/rigs-of-rods#1403]
New to Ubuntu and attempting to teach my son(and myself) there is another world out there without Microsoft. We attempted following the readme and got stuck on shell core with the following errors. I have performed search of the INTERNET but I believe my skills are lacking. I am looking for help of the error asITypeInfo’ below. Any help would be appreciated.

Downloads/ror$ sh core.sh
Already up-to-date.
-- Looking for OGRE...
-- Found Ogre Ghadamon (1.9.0)
-- Found OGRE: /home/logan/rigs-of-rods/install/lib/libOgreMain.so
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: /home/logan/rigs-of-rods/install/lib/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: /home/logan/rigs-of-rods/install/lib/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: /home/logan/rigs-of-rods/install/lib/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: /home/logan/rigs-of-rods/install/lib/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: /home/logan/rigs-of-rods/install/lib/libOgreVolume.so
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: /home/logan/rigs-of-rods/install/lib/libOgreOverlay.so
-- Looking for OIS...
-- Found OIS: /usr/lib/x86_64-linux-gnu/libOIS.so
-- Looking for OGRE...
-- Found Ogre Ghadamon (1.9.0)
-- Found OGRE: /home/logan/rigs-of-rods/install/lib/libOgreMain.so
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: /home/logan/rigs-of-rods/install/lib/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: /home/logan/rigs-of-rods/install/lib/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: /home/logan/rigs-of-rods/install/lib/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: /home/logan/rigs-of-rods/install/lib/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: /home/logan/rigs-of-rods/install/lib/libOgreVolume.so
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: /home/logan/rigs-of-rods/install/lib/libOgreOverlay.so
-- Looking for OIS...
-- Found OIS: /usr/lib/x86_64-linux-gnu/libOIS.so
-- Configuring done
CMake Warning at source/main/CMakeLists.txt:268 (add_executable):
  Cannot generate a safe runtime search path for target RoR because files in
  some directories may conflict with libraries in implicit directories:

    runtime library [libopenal.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/logan/rigs-of-rods/install/lib

  Some of these libraries may not be found correctly.

CMake Warning at source/configurator/CMakeLists.txt:46 (add_executable):
  Cannot generate a safe runtime search path for target RoRConfig because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libopenal.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/logan/rigs-of-rods/install/lib

  Some of these libraries may not be found correctly.

-- Generating done
-- Build files have been written to: /home/logan/rigs-of-rods/source/rigs-of-rods/0_build/RelWithDebInfo
[  1%] Building CXX object source/angelscript_addons/CMakeFiles/angelscript_addons.dir/scriptany/scriptany.cpp.o
[  2%] Generate files containing version information
true
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp: In member function ‘AngelScript::CScriptAny& AngelScript::CScriptAny::operator=(const AngelScript::CScriptAny&)’:
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:206:3: error: ‘asITypeInfo’ was not declared in this scope
   asITypeInfo *ti = engine->GetTypeInfoById(other.value.typeId);
   ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:206:16: error: ‘ti’ was not declared in this scope
   asITypeInfo *ti = engine->GetTypeInfoById(other.value.typeId);
                ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:206:29: error: ‘class AngelScript::asIScriptEngine’ has no member named ‘GetTypeInfoById’
   asITypeInfo *ti = engine->GetTypeInfoById(other.value.typeId);
                             ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:218:54: error: ‘class AngelScript::asIScriptEngine’ has no member named ‘GetTypeInfoById’
   engine->AddRefScriptObject(value.valueObj, engine->GetTypeInfoById(value.typeId));
                                                      ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:223:81: error: ‘class AngelScript::asIScriptEngine’ has no member named ‘GetTypeInfoById’
   value.valueObj = engine->CreateScriptObjectCopy(other.value.valueObj, engine->GetTypeInfoById(value.typeId));
                                                                                 ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp: In constructor ‘AngelScript::CScriptAny::CScriptAny(AngelScript::asIScriptEngine*)’:
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:253:58: error: ‘class AngelScript::asIScriptEngine’ has no member named ‘GetTypeInfoByName’
  engine->NotifyGarbageCollectorOfNewObject(this, engine->GetTypeInfoByName("any"));
                                                          ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp: In constructor ‘AngelScript::CScriptAny::CScriptAny(void*, int, AngelScript::asIScriptEngine*)’:
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:266:58: error: ‘class AngelScript::asIScriptEngine’ has no member named ‘GetTypeInfoByName’
  engine->NotifyGarbageCollectorOfNewObject(this, engine->GetTypeInfoByName("any"));
                                                          ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp: In member function ‘void AngelScript::CScriptAny::Store(void*, int)’:
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:284:3: error: ‘asITypeInfo’ was not declared in this scope
   asITypeInfo *ti = engine->GetTypeInfoById(refTypeId);
   ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:284:16: error: ‘ti’ was not declared in this scope
   asITypeInfo *ti = engine->GetTypeInfoById(refTypeId);
                ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:284:29: error: ‘class AngelScript::asIScriptEngine’ has no member named ‘GetTypeInfoById’
   asITypeInfo *ti = engine->GetTypeInfoById(refTypeId);
                             ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:296:54: error: ‘class AngelScript::asIScriptEngine’ has no member named ‘GetTypeInfoById’
   engine->AddRefScriptObject(value.valueObj, engine->GetTypeInfoById(value.typeId));
                                                      ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:301:64: error: ‘class AngelScript::asIScriptEngine’ has no member named ‘GetTypeInfoById’
   value.valueObj = engine->CreateScriptObjectCopy(ref, engine->GetTypeInfoById(value.typeId));
                                                                ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp: In member function ‘bool AngelScript::CScriptAny::Retrieve(void*, int) const’:
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:344:12: error: ‘class AngelScript::asIScriptEngine’ has no member named ‘RefCastObject’
    engine->RefCastObject(value.valueObj, engine->GetTypeInfoById(value.typeId), engine->GetTypeInfoById(refTypeId), reinterpret_cast<void**>(ref));
            ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:344:50: error: ‘class AngelScript::asIScriptEngine’ has no member named ‘GetTypeInfoById’
    engine->RefCastObject(value.valueObj, engine->GetTypeInfoById(value.typeId), engine->GetTypeInfoById(refTypeId), reinterpret_cast<void**>(ref));
                                                  ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:344:89: error: ‘class AngelScript::asIScriptEngine’ has no member named ‘GetTypeInfoById’
    engine->RefCastObject(value.valueObj, engine->GetTypeInfoById(value.typeId), engine->GetTypeInfoById(refTypeId), reinterpret_cast<void**>(ref));
                                                                                         ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:357:12: error: ‘class AngelScript::asIScriptEngine’ has no member named ‘AssignScriptObject’
    engine->AssignScriptObject(ref, value.valueObj, engine->GetTypeInfoById(value.typeId));
            ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:357:60: error: ‘class AngelScript::asIScriptEngine’ has no member named ‘GetTypeInfoById’
    engine->AssignScriptObject(ref, value.valueObj, engine->GetTypeInfoById(value.typeId));
                                                            ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp: In member function ‘void AngelScript::CScriptAny::FreeObject()’:
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:409:3: error: ‘asITypeInfo’ was not declared in this scope
   asITypeInfo *ti = engine->GetTypeInfoById(value.typeId);
   ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:409:16: error: ‘ti’ was not declared in this scope
   asITypeInfo *ti = engine->GetTypeInfoById(value.typeId);
                ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:409:29: error: ‘class AngelScript::asIScriptEngine’ has no member named ‘GetTypeInfoById’
   asITypeInfo *ti = engine->GetTypeInfoById(value.typeId);
                             ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp: In member function ‘void AngelScript::CScriptAny::EnumReferences(AngelScript::asIScriptEngine*)’:
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:432:3: error: ‘asITypeInfo’ was not declared in this scope
   asITypeInfo *ti = inEngine->GetTypeInfoById(value.typeId);
   ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:432:16: error: ‘ti’ was not declared in this scope
   asITypeInfo *ti = inEngine->GetTypeInfoById(value.typeId);
                ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:432:31: error: ‘class AngelScript::asIScriptEngine’ has no member named ‘GetTypeInfoById’
   asITypeInfo *ti = inEngine->GetTypeInfoById(value.typeId);
                               ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp: In member function ‘int AngelScript::CScriptAny::AddRef() const’:
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:447:29: error: ‘asAtomicInc’ was not declared in this scope
  return asAtomicInc(refCount);
                             ^
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp: In member function ‘int AngelScript::CScriptAny::Release() const’:
/home/logan/rigs-of-rods/source/rigs-of-rods/source/angelscript_addons/scriptany/scriptany.cpp:454:26: error: ‘asAtomicDec’ was not declared in this scope
  if( asAtomicDec(refCount) == 0 )
                          ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-terminate’
source/angelscript_addons/CMakeFiles/angelscript_addons.dir/build.make:86: recipe for target 'source/angelscript_addons/CMakeFiles/angelscript_addons.dir/scriptany/scriptany.cpp.o' failed
make[2]: *** [source/angelscript_addons/CMakeFiles/angelscript_addons.dir/scriptany/scriptany.cpp.o] Error 1
CMakeFiles/Makefile2:256: recipe for target 'source/angelscript_addons/CMakeFiles/angelscript_addons.dir/all' failed
make[1]: *** [source/angelscript_addons/CMakeFiles/angelscript_addons.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
true
[  2%] Built target generate_version
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Michael10055** [comment]
This is due to the recent Angelscript upgrade and the addition of RapidJSON. The build scripts need to be updated. There's a pull request that updates it but it is not merged yet: https://github.com/RigsOfRods/ror-linux-buildscripts/pull/17
For now you can download a zip of AFG's "fix" branch here: https://github.com/AnotherFoxGuy/ror-linux-buildscripts/tree/fix

**Comment by saltzstang** [comment]
Ended up with this issue below


sh game.sh
Already up-to-date.
-- Looking for OGRE...
-- Checking for module 'OGRE'
--   No package 'OGRE' found
-- Could not locate OGRE
CMake Error at cmake/3rdparty/FindPkgMacros.cmake:122 (message):
  ----------------------------------------

   Required library OGRE not found!
   If you're using 'ror-dependencies' package (https://github.com/RigsOfRods/ror-dependencies), then manually set CMAKE_PREFIX_PATH to their installation location.
   Otherwise, install the library (including dev packages) and try again. If the library is already installed, set the missing variables manually in CMake.

  ----------------------------------------
Call Stack (most recent call first):
  cmake/3rdparty/FindOGRE.cmake:248 (findpkg_finish)
  source/main/CMakeLists.txt:383 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/logan/rigs-of-rods-source/rigs-of-rods/0_build/RelWithDebInfo/CMakeFiles/CMakeOutput.log".
See also "/home/logan/rigs-of-rods-source/rigs-of-rods/0_build/RelWithDebInfo/CMakeFiles/CMakeError.log".
