### ISSUE TITLE
dependencies-Ubuntu-16.04.sh links 

### ISSUE THREAD

**Issue by saltzstang** [RigsOfRods/rigs-of-rods#1406]
Looks Like there are several folder links that are not mapped to the correct folders. How do I correct this?

Fetched 306 kB in 47s (6,426 B/s)
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/aapo-rantalainen/rigsofrods/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://ppa.launchpad.net/aapo-rantalainen/ror-038-stable/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://ppa.launchpad.net/aapo-rantalainen/ror-038/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://ppa.launchpad.net/aapo-rantalainen/ror-044-unstable/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/aapo-rantalainen/rigsofrods/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/aapo-rantalainen/ror-038-stable/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/aapo-rantalainen/ror-038/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/aapo-rantalainen/ror-044-unstable/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by Michael10055** [comment]
This should be posted in https://github.com/RigsOfRods/ror-linux-buildscripts
