### ISSUE TITLE
Setup Travis CI for autobild AppImage (as binary for Linux)

### ISSUE THREAD

**Issue by Symbian9** [RigsOfRods/rigs-of-rods#1411]
Since AppImage now is widely used for providing portable binary that could run on most widely Linux-based distributives, please, setup your `.travis.yml` for autobuild AppImages for Rigs-of-Rods.

P.S.: Not all Linux users can build games from source: https://www.linuxmintusers.de/index.php?topic=41689.0

**Comment by only-a-ptr** [comment]
Hello and thanks for the suggestion. Although I'm not familiar with the AppImage toolkit, it feels like something that RoR should consider.

Unfortunately, I've bee using only Windows in years and currently I'm unable to maintain our linux scripts/guides/CIs in any way. Your best bet is to get ahold of @AnotherFoxGuy 

> P.S.: Not all Linux users can build games from source. https://www.linuxmintusers.de/index.php?topic=41689.0

The topic you linked is rather chaotic, but the problem I see is the "v0.38" installation instructions in the 2nd post. The 0.3x versions are obsolete, all developers involved with it have left the team long ago.

**Comment by AnotherFoxGuy** [comment]
The first test build: http://prdownloads.sourceforge.net/rigs-of-rods/Rigs_of_Rods_x86_64.AppImage

**Comment by Symbian9** [comment]
> The first test build: http://prdownloads.sourceforge.net/rigs-of-rods/Rigs_of_Rods-x86_64.AppImage

Look like you should bundle `libfreeimage3` inside AppImage too:

```
$ ./Rigs_of_Rods-x86_64.AppImage
RoRConfig: error while loading shared libraries: libfreeimage.so.3: cannot open shared object file: No such file or directory
```

OS: Debian 9.x

**Comment by tritonas00** [comment]
and wxgtk also would be nice to be bundled

**Comment by probonopd** [comment]
How did you produce the AppImage? It is missing libraries:

```
$ export LD_LIBRARY_PATH=squashfs-root/usr/lib/ ; ldd squashfs-root/usr/bin/RoR | grep not
	libfreeimage.so.3 => not found
	libzzip-0.so.13 => not found
```

**Comment by AnotherFoxGuy** [comment]
New build: https://dl.bintray.com/anotherfoxguy/Rigs-of-Rods-CI-Build/RoR-V0.4.8.0-CIBuild-118.1.AppImage

This shoud fix the missing libs

**Comment by tritonas00** [comment]
Runs fine. Two issues:

- No caleum
- Going to Multi Player crashes the game. If it is a Debug build its expected. Build with Release or RelWithDebInfo will fix the issue probably.

**Comment by AnotherFoxGuy** [comment]
> No Caelum
No pagedgeometry

Caelum && pagedgeometry will return after OGRE 1.11

> Going to Multi-Player crashes the game. If it is a Debug build its expected. Build with Release or RelWithDebInfo will fix the issue probably.

This build should fix it: 
https://dl.bintray.com/anotherfoxguy/Rigs-of-Rods-CI-Build/RoR-V0.4.8.0-CIBuild-119.1.AppImage
Forgot to add the release build flag to CMake

**Comment by Symbian9** [comment]
> - https://dl.bintray.com/anotherfoxguy/Rigs-of-Rods-CI-Build/RoR-V0.4.8.0-CIBuild-119.1.AppImage
> 
> The requested path was not found.

Which one is latest build?

- https://dl.bintray.com/anotherfoxguy/Rigs-of-Rods-CI-Build

Also, add link to Bintray repo into the header of `README.md`.

**Comment by AnotherFoxGuy** [comment]
@Symbian9 There is a thread on the forums with info on how to download it
https://forum.rigsofrods.org/development-discussion/1339-rigs-rods-ci-builds-windows-linux.html

**Comment by probonopd** [comment]
`RoRConfig: error while loading shared libraries: libwx_baseu-3.0.so.0: cannot open shared object file: No such file or directory
`

**Comment by tritonas00** [comment]
@AnotherFoxGuy yes it would be nice too bundle wxgtk also

**Comment by Symbian9** [comment]
Also, need bundle *libfreeimage3*

```
$ ./RoR-V0.4.8.0-CIBuild-2790.1.AppImage
RoRConfig: error while loading shared libraries: libfreeimage.so.3: cannot open shared object file: No such file or directory
```

**Comment by tritonas00** [comment]
freeimage is already in, did you download the latest appimage?

**Comment by tritonas00** [comment]
hmm its already https://github.com/RigsOfRods/rigs-of-rods/pull/1576/files#diff-1ae3bfbdd3ef50680c8301951fd421a6R16

**Comment by probonopd** [comment]
> it would be nice to bundle wxgtk also

Actually we recommend to bundle all libraries except those explicitly listed on
https://github.com/AppImage/AppImages/blob/master/excludelist

**Comment by tritonas00** [comment]
@probonopd 
> How did you produce the AppImage?

https://github.com/RigsOfRods/rigs-of-rods/blob/master/.travis/build-and-upload-appimage.sh

**Comment by probonopd** [comment]
@tritonas00 copying in just a few libraries by hand does not make it a sufficiently self-standing AppDir; tools like [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) or [linuxdeploy](https://github.com/linuxdeploy/linuxdeploy) could help you there by automating this process.

**Comment by tritonas00** [comment]
@probonopd 

@AnotherFoxGuy made it working now and in just a plain zip archive
https://github.com/RigsOfRods/rigs-of-rods/pull/1660

**Comment by probonopd** [comment]
If the plain zip folder from @AnotherFoxGuy is working as intended, then it should be easy to turn the contents of that zip into an AppImage by running `appimagetool` on it.
