### ISSUE TITLE
Remove nvidia-cg-toolkit

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#1412]
At the moment RoR depends on the [legacy Cg Toolkit](https://developer.nvidia.com/cg-toolkit) (which was last updated in 2012)
For Linux, this means that RoR needs a custom build of OGRE to work properly

![screenshot from 2017-11-12 16-22-42](https://user-images.githubusercontent.com/9480940/33201573-666279f0-d0f9-11e7-9395-8b53467e488e.png)
(This is RoR build with the ```libogre-1.9-dev``` package from the [Ubuntu pakage repo](https://packages.ubuntu.com/artful/libogre-1.9-dev))

This probably fixes: #361 #84 #640 

ToDo
- [ ] #941 
- [ ] #942
- [ ] #943
- [ ] Remove Caelum

**Comment by only-a-ptr** [comment]
Ouch! The terrn2 system depends on Cg Toolkit - specifically, terrn2 depends on OgreTerrain component which uses generated Cg shaders. 

I assume the reason libOGRE packages are built without Cg is it's proprietary nature and not the obsolete status. Still, we need to take this in account.

**Comment by paroj** [comment]
OgreTerrain primary generates HLSL & GLSL nowadays. Also Cg is just HLSLv9. I am looking into using https://github.com/aras-p/hlsl2glslfork to replace Cg for GLSL translation on GL and just load it as HLSL on D3D.

**Comment by rebcabin** [comment]
The build instructions should be updated for Linux. I had to manually search for Cg because none of the "safe" ppa's I accessed knew about it. A few minutes' worth of Googling found me Cg-3.1_April2012_x86_64.deb and I was able to complete the build with no further drama.
