### ISSUE TITLE
Planes don't spawn correctly on second+ session

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1424]
Load simple terrain and spawn skyvan, it loads fine.
Back to menu and reload simple terrain and skyvan, wings are missing:

![2017-12-13-222946_1366x768_scrot](https://user-images.githubusercontent.com/2660424/33960998-25e3a85c-e055-11e7-9950-9a081dceb6a2.png)

**Comment by only-a-ptr** [comment]
Is it just graphics or is it also unable to fly?

**Comment by tritonas00** [comment]
just graphics

**Comment by tritonas00** [comment]
also it only happens when you reload the same map

if you spawn another map for the first time, wings appear, until the second map reload

**Comment by tritonas00** [comment]
any news on this? :stuck_out_tongue_closed_eyes:

**Comment by only-a-ptr** [comment]
Eh, it's most definitely some missing cleanup. I'll give it a few minutes, but no promises.

**Comment by only-a-ptr** [comment]
I tried pressing 'K' for skeletonview
![obrazek](https://user-images.githubusercontent.com/491088/36076365-832e8a42-0f5b-11e8-9c28-7151b09251a4.png)

**Comment by only-a-ptr** [comment]
Yep, it was a missing cleanup.

**Comment by tritonas00** [comment]
great i will test asap!

**Comment by only-a-ptr** [comment]
I glued the fix to an unrelated PR: https://github.com/RigsOfRods/rigs-of-rods/pull/1470 :blush:
