### ISSUE TITLE
Double mouse cursors + cursor doesn't hide in screenshots

### ISSUE THREAD

**Issue by Michael10055** [RigsOfRods/rigs-of-rods#1428]
This is probably already known, but there hasn't been an issue ticket created for it yet.

Two mouse cursors appear now (assuming it's MyGUI + IMGUI's cursors) and the "grey triangle" cursor does not hide when you take a screenshot.
![double-cursors](https://user-images.githubusercontent.com/11002490/34071327-ea857304-e242-11e7-9c48-d44349d5c267.png)

**Comment by only-a-ptr** [comment]
🤣 Thanks for making a ticket about it - I noticed it several times already and never got to fix it.
