### ISSUE TITLE
Game crashes when closing the settings window

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#1429]
When you close the settings window on Linux the game crashes with this error
```
RoR: /home/anotherfoxguy/Documents/rigs-of-rods/source/main/gui/imgui/imgui.cpp:2665: void ImGui::EndFrame(): Assertion `g.CurrentWindowStack.Size == 1' failed.
Aborted (core dumped)
```

**Comment by tritonas00** [comment]
hm weird, seems to work fine here

**Comment by only-a-ptr** [comment]
My mistake - I forgot to call `ImGui::End()` somewhere.

@tritonas00 this message only shows in a debug build. But it's a real issue - DearIMGUI may get corrupted.
