### ISSUE TITLE
Missing ground models 

### ISSUE THREAD

**Issue by ChaseGerton** [RigsOfRods/rigs-of-rods#1433]
Every time I load a map it gives me the error 
OGRE EXCEPTION(6:FileNotFoundException):’C\Users\Chase\Documents\Rigs of Rods 0.4\config\ground_models.cfg’ File not found. 

I don’t know what to do and then after the map loads I try to spawn a car but it crashes the game right after the car spawns in! Help me

**Comment by Michael10055** [comment]
Are you using version 0.4.7.0 or an AppVeyor/self-compiled build?
You should be able to just download the [ground_models.cfg](https://raw.githubusercontent.com/RigsOfRods/rigs-of-rods/master/resources/skeleton/config/ground_models.cfg) (Right click -> Save as) and place it into the `Rigs of Rods 0.4/config` directory.

**Comment by only-a-ptr** [comment]
This might be due to the recent changes in build scripts. Needs to be resolved before the next release.

@ChaseGerton Windows or Linux? Also please upload your 'RoR.log' if you can.

**Comment by only-a-ptr** [comment]
Removing from v0.4.8 since it's not confirmed.

**Comment by tritonas00** [comment]
same error as https://github.com/RigsOfRods/rigs-of-rods/issues/1935
