### ISSUE TITLE
"Bad UTF-8 continuation byte" Error when path or file contains special characters 

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#1436]
The game will crash when a path or file contains special characters such as  ```äûó``` 

### Steps to reproduce

1. Rename [agora.zip](https://github.com/RigsOfRods/rigs-of-rods/blob/master/resources/skeleton/packs/agora.zip) to ```ägórâ.zip```
2. Run RoR 
3. The game will crash with a ***Bad UTF-8 continuation byte*** Error

**Comment by only-a-ptr** [comment]
Eh, again? 😩 
Thanks for reporting, I'll fix it ASAP.
