### ISSUE TITLE
Back to menu crash ror on miniredmars terrain

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#144]
http://www.rigsofrods.com/attachment.php?attachmentid=530748&d=1427734686

**Comment by Max98** [comment]
The map takes years to load wow..
The debugger told me that the crash is coming from Ogre it self and not from Rigs of rods.
I think there's something special with this map, I will take a deeper look.

**Comment by Hiradur** [comment]
Still valid with Ogre 1.9?

**Comment by only-a-ptr** [comment]
This is probably caused by RoR updating some OGRE element which has already been deleted. I'll check it out.

**Comment by only-a-ptr** [comment]
@Speciesx Can you re-test this please?

**Comment by Speciesx** [comment]
@only-a-ptr 
Still crash.

**Comment by DirtGamer301** [comment]
@only-a-ptr There's quite many "special" things with this map: http://www.rigsofrods.com/repository/view/4879
Gravity (shouldn't be a problem if it's Ogre caused), particles (shouldn't be a problem either), animated textures, maybe Gifs I can't look right now, atleast in the spawn room there's some animations like on the TV screen IIRC which you should probably take a closer look at, I can't remember any other map having these features.

**Comment by Speciesx** [comment]
I'm no longer able to reproduce that bug.
