### ISSUE TITLE
Forum site Broken again

### ISSUE THREAD

**Issue by DarthCainRor** [RigsOfRods/rigs-of-rods#1444]
So, is there any word on what is going on with the forums? They've been down for about a day now it seems.

**Comment by only-a-ptr** [comment]
Dammit, my fault, I didn't pay the monthly bill in time.

I sent the payment just now. I'll contact the hosting company about what next.

**Comment by LukeEM2** [comment]
thanks for clarifying

**Comment by only-a-ptr** [comment]
The hosting company responded with "You didn't pay, you received warnings, you still didn't pay, your server was deleted, you can buy a new one". Actually, I've been paying regularly the whole year, but the past week was somewhat stressful so I forgot to top up my account and skipped reading emails. 11 days of overdue payment were enough to get the server shut down :-/

At the moment, @Michael10055, Zentro and TheWolf are already setting up a new server with a different hosting company. This time, TheWolf purchased the hosting.

**Comment by LukeEM2** [comment]
thats very unfortunate news, hope the stressful issues end up working out in you're favour. and alright thats good! whats the estimated time until the new server is all set up? do you know?

**Comment by disloyalpick** [comment]
I'm sorry for commenting on a closed issue, but I felt that @LukeEM2 should know that the new forums, are up for eveyone to use now.

Have fun   https://forum.rigsofrods.org
