### ISSUE TITLE
FOV External/Internal values updated on exit

### ISSUE THREAD

**Issue by Michael10055** [RigsOfRods/rigs-of-rods#1446]
This is probably already known, but no issue ticket has been created on it and it's been kind of bugging me 😆 

If the FOV is adjusted (which I change quite frequently) the value you set it to is written to `RoR.cfg` on exit.

**Comment by only-a-ptr** [comment]
Ummm... I already did take care of this. Changing FOV by hotkeys shouldn't propagate to RoR.cfg, only changing it in Settings should. I'll check again...
