### ISSUE TITLE
HighResWheelNodeCollisions is not editable in the Settings menu.

### ISSUE THREAD

**Issue by derbymutt** [RigsOfRods/rigs-of-rods#1447]
`HighResWheelNodeCollision`s being set to `Yes` solves a lot of handling issues with some mods that are caused by node bouncing, yet it's not able to be turned on or off without editing `RoR.cfg`. This would be at home in the` Physics` tab of the Settings menu.

**Comment by only-a-ptr** [comment]
^

Thanks for bringing it up.
