### ISSUE TITLE
Cursor appearing on minimap

### ISSUE THREAD

**Issue by Michael10055** [RigsOfRods/rigs-of-rods#1454]
If you adjust the minimap zoom, the mouse cursor may appear.
![screenshot_2018-01-30_20-56-57_1](https://user-images.githubusercontent.com/11002490/35601382-b22f9ff2-0600-11e8-9c55-d31538759354.png)
![screenshot_2018-01-30_20-57-04_1](https://user-images.githubusercontent.com/11002490/35601384-b501845c-0600-11e8-94ca-d53dee5fc819.png)
I've seen it appear without adjusting the zoom sometimes though.

**Comment by only-a-ptr** [comment]
I think you just have a jumpy 🐭

**Comment by tritonas00** [comment]
i think not anymore
