### ISSUE TITLE
texture issue in latest master

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1462]
load agora bus or gavril (happens with all vehicles)

![2018-02-05-224849_1366x768_scrot](https://user-images.githubusercontent.com/2660424/35828142-2a24c5e4-0ac7-11e8-8a05-1c3e3555b532.png)
![2018-02-05-231007_1366x768_scrot](https://user-images.githubusercontent.com/2660424/35828871-c2b52df6-0ac9-11e8-8e9e-d766b23385d8.png)

previous week everything was good :smile:

**Comment by only-a-ptr** [comment]
Looks like OpenGL issue with rendered textures.

**Comment by tritonas00** [comment]
I will find the bad commit

**Comment by Michael10055** [comment]
Also happens on Windows + OpenGL:
![screenshot_2018-02-08_18-52-03_1](https://user-images.githubusercontent.com/11002490/36004646-ab5b31f2-0d01-11e8-8d4e-aba7b23c3321.png)
