### ISSUE TITLE
Move SkyX out of the source tree

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#1468]
See #1065
If we move Hydrax we also should move SkyX to its own repo

**Comment by only-a-ptr** [comment]
I'd prefer to leave SkyX in the source tree. We're planning to port to OGRE 1.10x in a close future and continue to OGRE 2.1+. This will likely require changes to SkyX. Also our terrain graphics aren't perfect (no dynamic lights etc...) and improving them may again require changes to SkyX. Adding an artificial boundary of separate repos would only complicate this.

SkyX development is fragmented, there's no single active development repo. There's https://bitbucket.org/ogreaddons/skyx/src but it only has C++ code, no shaders or media. The original links at http://www.paradise-sandbox.com/#hydraxskyx.php are dead, I don't even know where @Speciesx got the media files from. GitHub has some individual forks. Maintaining a public repo in this situation would require active development effort, and we don't have the manpower - I have enough to do with RoR alone without separating out subsystems.
