### ISSUE TITLE
Wheels2 not loading snodes

### ISSUE THREAD

**Issue by RustyMonster** [RigsOfRods/rigs-of-rods#1474]
Mods with wheels2 aren't loading in the snode beams properly. This can be tested with the blue 6x6 Daf Dakar truck.

**Comment by disloyalpick** [comment]
I think the whole wheels2 section needs a re-do/improvement.

**Comment by RustyMonster** [comment]
It works fine as is, stability is questionable, getting them stable on my mods was like doing witchcraft, but they work great once tuned. Would like to see it work with meshed wheels/tires.

**Comment by Michael10055** [comment]
Can confirm this happens on the latest master.
http://archives.rigsofrods.net/repo/files/repofiles-1st-batch/1747b3b8deb2fed6ee7d50f397e322fa78ee9d66_dakardaf.zip
![screenshot_2018-02-18_21-39-22_1](https://user-images.githubusercontent.com/11002490/36360697-6504bffc-14f4-11e8-9cf9-b622363009f4.png)
