### ISSUE TITLE
Invalid UTF-8 sequence header value

### ISSUE THREAD

**Issue by DOMESTOSik** [RigsOfRods/rigs-of-rods#1475]
When i click "Singleplayer" game don't even start loading it just says
 "FATAL ERROR 
An internal error occured in Rigs of Rods
Technical details below : 
invalid utf-8 sequence header value" 
Please help this game was working but after i install it second time i cant play (Windows 10)
Sorry for my english.

**Comment by only-a-ptr** [comment]
Hello @DOMESTOSik 
Please post file `RoR.log` from `MyDocuments\Rigs of Rods 0.4\logs`.

**Comment by DOMESTOSik** [comment]
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/1754291/RoR.log)

**Comment by DOMESTOSik** [comment]
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/1754316/RoR.log)

**Comment by only-a-ptr** [comment]
Well this isn't going to work :laughing: 
```
21:28:44: [RoR|Globals] Updating "sys_config_dir": [] => [C:\Users\Dodzisław\Documents\Rigs of Rods 0.4\config]
21:28:44: [RoR|Globals] Updating "sys_cache_dir": [] => [C:\Users\Dodzisław\Documents\Rigs of Rods 0.4\cache]
21:28:44: [RoR|Globals] Updating "sys_screenshot_dir": [] => [C:\Users\Dodzisław\Documents\Rigs of Rods 0.4\screenshots]
21:28:44: [RoR|Globals] Updating "sys_resources_dir": [] => [C:\PROGRA~2\RIGSOF~1.0\resources]
21:28:44: [RoR|Globals] Updating "audio_device_name": [] => [OpenAL Soft on Gďż˝oďż˝niki (Conexant SmartAudio HD)]
```

RoR has chronic problems with Unicode characters in file paths. I can fix that in RoR, but I'm worried even OGRE3D engine itself doesn't get it right. Please stay around to test.

**Comment by only-a-ptr** [comment]
@DOMESTOSik 
In your case the problem is the user name (but it isn't bad, our code is bad :slightly_smiling_face:  ). It looks like the selector GUI hurls when it's supposed to display the ZIP filepath of your mods.

The audio device name may cause no sound in game or sound coming from bad device (speakers instead of headphones etc..) but it won't crash you.

**Comment by DOMESTOSik** [comment]
so, how long i will wait for you to fix this problem  ? :)

**Comment by DOMESTOSik** [comment]
Okay, nevermind i completly reset my laptop and everything is working. Thanks for help
