### ISSUE TITLE
-DownLoading Mods-

### ISSUE THREAD

**Issue by JonnyCrash** [RigsOfRods/rigs-of-rods#1478]
sometimes i try downloading a mod and it says to "Wait -amount of time- seconds before downloading another mod". so  i wait. and when it's done i click download, but then it says "you must wait 60 seconds before downloading another mod" even tho i waited alredy ;-;

(does not really matter to me but it's annoying...)

**Comment by AnimosusTheWolf** [comment]
This is not an appropriate issue of the development of the game. There is a time limit between downloading mods for guests. Just register on the forum and there will be no time limit. And keep your questions in the support sections of the forum. This is for actual game issues.

**Comment by JonnyCrash** [comment]
thx for the tip Animosus. now i will just go log in =3
