### ISSUE TITLE
Trailers don't work

### ISSUE THREAD

**Issue by HorseTrainer** [RigsOfRods/rigs-of-rods#148]
Trailer spawns in the ground, and then won't move up or down. When I get in the trailer, I hit backspace to bring the trailer off the ground to hook it up to a truck. When I do that, the trailer just stays in air and doesn't move. Tried it on 3 different trailers

**Comment by Max98** [comment]
Interesting, I've put the high-priority tag because it's one of the important thing in Rigs of rods.

**Comment by HorseTrainer** [comment]
Also checked the log and no errors show up in the trailer. Thank you

**Comment by only-a-ptr** [comment]
@HorseTrainer : Please post download link(s) to trailers which you used for testing.

**Comment by only-a-ptr** [comment]
@HorseTrainer : I just tested with DAF semi-truck and semi-trailer-37tons (default vehicles)
Everything worked - the F1/F2 commands rised/lowered the trailer legs and connecting with L was also fine.
Please re-test with test build 4 and close this issue if it works.
Thanks

**Comment by only-a-ptr** [comment]
Trailers are working again since Test Build 4
http://www.rigsofrods.com/threads/119110-Test-Build-Rigs-of-rods-0-4-5-0-dev?p=1384178&viewfull=1#post1384178
http://www.rigsofrods.com/threads/119110-Test-Build-Rigs-of-rods-0-4-5-0-dev?p=1384293&viewfull=1#post1384293
