### ISSUE TITLE
-muitiplayer not working and some mods crash the computer-

### ISSUE THREAD

**Issue by JonnyCrash** [RigsOfRods/rigs-of-rods#1480]
i try to play muitiplayer and it does not work. i tryed the only thing that does help me play witch is i restore the setting and then i set them to what i had them on. now it does not let me play muitiplayer.

for the mods. some just crash my computer so i have to force shut down. some other's don't. and the one's that crash the computer are only when i drive them for a long time.

**Comment by only-a-ptr** [comment]
Too many problems at once :smile:

First, remove all mods - leave only the default "agora.zip" in packs. Then start RoR and try the multiplayer - will it crash? If yes, post RoR.log from "MyDocuments\Rigs of Rods 0.4\logs" directory.

If everything works, start adding mods one by one - when you get a crash, immediately post RoR.log here and tell me which mod caused it.
