### ISSUE TITLE
Crash while driving boat

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1482]
Load simple test terrain with water and the c1boat. Press UP and let it drive. After a while the game will crash. Backtrace leads to https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/physics/collision/PointColDetector.cpp#L180

Full bt: https://pastebin.com/fkWx72Qb
Boat: [C1boat.zip](https://github.com/RigsOfRods/rigs-of-rods/files/1776107/C1boat.zip)

**Comment by only-a-ptr** [comment]
I knew it! No matter how hard I try, the issue count will always creep back to 200! :rofl:

**Comment by tritonas00** [comment]
Ok i will copy the issue here https://github.com/RigsOfRods/rigs-of-rods/issues/1008 and close this, because it happens only with C1boat, other boats works fine
