### ISSUE TITLE
ror crash when enter /setgravity without a value

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#149]
Btw. It would be nice, when enter /setgravity without a value will show the current gravity.

**Comment by Max98** [comment]
That would more of /getgravity but uhm, we all know that it's around -9.80..
Will fix the crash and add '/getgravity'

**Comment by Hiradur** [comment]
Many games show the value when no parameter is given to a command. It makes sense because it means you have to know only one command.

**Comment by Max98** [comment]
^ Nice one, will do.

**Comment by Max98** [comment]
Done.
