### ISSUE TITLE
latest master doesn't copy/create resources folder

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1491]
no resources folder is created and i suspect this PR https://github.com/RigsOfRods/rigs-of-rods/pull/1484

**Comment by Michael10055** [comment]
Also happens on Windows.

**Comment by AnotherFoxGuy** [comment]
This isn't a bug, there is a new target called **zip_and_copy_resources** that copies the resources folder (and soon also downloads and compiles the languages folder)

**Comment by tritonas00** [comment]
The game can't run because the resources folder missing in the bin directory, i have to copy the folder manually

**Comment by tritonas00** [comment]
So it doesn't copy the folder as it should

**Comment by tritonas00** [comment]
So add it to cmake? :p

**Comment by AnotherFoxGuy** [comment]
Updated the build instructions
