### ISSUE TITLE
rigs of rods not downloading saying that the download has failed midway

### ISSUE THREAD

**Issue by monsterjam120** [RigsOfRods/rigs-of-rods#1494]

**Comment by Michael10055** [comment]
At the moment, the content pack fails to download through the installer.  The only fix currently is to uncheck the content pack option, install & run RoR, then download the content pack from [here](http://archives.rigsofrods.net/contentpacks/pack_contentpack04.zip) and extract the contents into `Documents/Rigs of Rods 0.4/packs`.
