### ISSUE TITLE
ROR crash at start

### ISSUE THREAD

**Issue by troop129** [RigsOfRods/rigs-of-rods#1496]
I downloaded ROR a some time ago, around update 4.5 or so. It didn't work for me, so I just forgot about it. Recently, I downloaded the 4.7 update, and it worked! When I got some cars, terrains and packs, extracted, ect., I tried running it. It said, "Ani internal error occured in rigs of rods. Technical details below: Run the RORconfic program first." I did so, by clicking the ROR configurer icon. Then I messed around with some setting, tried changing the language, a solution that had worked when this happened to other users in the way past,  and restarted it. It gave me another error message, this time saying that it cannot create a file or something. I uninstalled, reinstalled, and the same thing happened. Please help!
![image](https://user-images.githubusercontent.com/34671236/38595497-054b8548-3d01-11e8-8bac-2c39f63aab60.png)
![image](https://user-images.githubusercontent.com/34671236/38595526-31f11216-3d01-11e8-9ece-4ef6fcdbd7ec.png)

**Comment by AnimosusTheWolf** [comment]
Have you ran rorconfig as admin?

**Comment by troop129** [comment]
Yes, I tried it. It does the same thing

**Comment by crdoyle03** [comment]
fatal error? OMG! am i going to die? is my new pc going to blow me up wtf?

**Comment by crdoyle03** [comment]
Lol



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by KylinSchroeder** [comment]
What trucks do you have installed? I know I have had some issues in the past with certain vehicles

**Comment by troop129** [comment]
All the vehicles I have installed: (just looking at file names)
KME Predator
Agora
Bombardier ALP-45DP
Dafsemi
Hitachi EX E
Piper J3 Supercub
Wahoov 2 w/ trailer

**Comment by Michael10055** [comment]
I just came across this same issue when experimenting with RoR in a VM by installing RoR on one user account then attempting to run it on another.

RoRConfig doesn't create all the required directories - It only creates the `Rigs of Rods 0.4` directory, [not any of the other folders](https://github.com/RigsOfRods/rigs-of-rods/tree/master/resources/skeleton) -  Resulting in it throwing the error in your screenshot, then launching normally. Then clicking `Save and Play` /  `Save and Close` throws another error about it not being able to write the config files.

To fix, [download this zip file](https://github.com/RigsOfRods/rigs-of-rods/files/1933659/RoR_0.4.7.0_skeleton.zip) and extract its contents into the `Documents\Rigs of Rods 0.4` folder. 
Hopefully RoR should function as normal. 

Note that both accounts I used have admin permissions, I haven't tested RoR with a standard account yet.

**Comment by troop129** [comment]
Thank you for your suggestion. I did what you asked, but I got the same error messages. Also, when I pressed "save and play" in RORconfig, I got this message:

**Comment by troop129** [comment]
Sorry, for some reason GitHub is not accepting my image. you can view it at this Google Drive link: [https://drive.google.com/file/d/1Tm1QjMrYDmA6NYk5BjzdY2b__bR8WGov/view?usp=sharing](url)

**Comment by troop129** [comment]
It worked! Thank you so much.
