### ISSUE TITLE
RoR Configurator has stopped working

### ISSUE THREAD

**Issue by Ghavio1516** [RigsOfRods/rigs-of-rods#1497]
So,i download version 0.4.7.0.when i try to launch the ror configurator it just crash,can someone help me??this game bring me back to the good old days XD

pc spec:
xeon x3440 @4GHz
8Gb DDR3 Ram @1600MHz
Radeon HD 5870 @1Ghz
Windows 10 Ver 1709

**Comment by Ghavio1516** [comment]
btw this is the log

16:34:58: log started
16:34:58: failed to get Language: lb
16:34:58: searching languages in languages
16:34:58: Available Languages:
16:34:58:  * Afrikaans(af_ZA)
16:34:58:  * Arabic(ar)
16:34:58:  * Bulgarian(bg_BG)
16:34:58:  * Bosnian(bs)
16:34:58:  * Catalan(ca_ES)
16:34:58:  * Czech(cs_CZ)
16:34:58:  * Welsh(cy)
16:34:58:  * Danish(da_DK)
16:34:58:  * German(de_DE)
16:34:58:  * Greek(el_GR)
16:34:58:  * Esperanto(eo)
16:34:58:  * Spanish(es_ES)
16:34:58:  * Estonian(et_EE)
16:34:58:  * Farsi(fa_IR)
16:34:58:  * Finnish(fi_FI)
16:34:58:  * French(fr_FR)
16:34:58:  * Galician(gl_ES)
16:34:58:  * Hebrew(he_IL)
16:34:58:  * Hindi(hi_IN)
16:34:58:  * Croatian(hr_HR)
16:34:58:  * Hungarian(hu_HU)
16:34:58:  * Indonesian(id_ID)
16:34:58:  * Icelandic(is_IS)
16:34:58:  * Italian(it_IT)
16:34:58:  * Japanese(ja_JP)
16:34:58:  * Korean(ko_KR)
16:34:58:  * Latin(la)
16:34:58:  * Lithuanian(lt_LT)
16:34:58:  * Latvian(lv_LV)
16:34:58:  * Norwegian (Bokmal)(nb_NO)
16:34:58:  * Dutch(nl_NL)
16:34:58:  * Norwegian (Nynorsk)(nn_NO)
16:34:58:  * Polish(pl_PL)
16:34:58:  * Portuguese(pt_PT)
16:34:58:  * Romanian(ro_RO)
16:34:58:  * Russian(ru_RU)
16:34:58:  * Slovak(sk_SK)
16:34:58:  * Slovenian(sl_SI)
16:34:58:  * Serbian(sr_RS)
16:34:58:  * Swedish(sv_SE)
16:34:58:  * Thai(th_TH)
16:34:58:  * Turkish(tr_TR)
16:34:58:  * Urdu(ur)
16:34:58:  * Chinese(zh_TW)
16:34:58: asking system for default language.
16:34:58:  system returned: English (U.S.)(en_US)
16:34:58: preferred language: English (U.S.)
16:34:58: lang file: languages\en\LC_MESSAGES\ror.mo
4:34:58 PM: language not existing, no lang_locale support!
4:34:58 PM: Creating dialog
4:35:00 PM: Known Audio Devices: 
4:35:00 PM:  *OpenAL Soft on Speakers (2- High Definition Audio Device)
4:35:00 PM:  *OpenAL Soft on Digital Audio (S/PDIF) (2- High Definition Audio Device)
4:35:00 PM: Sound Extensions: 
4:35:01 PM: Setting default values
4:35:01 PM: Loading config
4:35:01 PM: Loading RoR.cfg
4:35:01 PM: reading from Config file: C:\Users\Ghavio\DOCUME~1\Rigs of Rods 0.4\\config\RoR.cfg
4:35:01 PM: Creating Ogre root

**Comment by only-a-ptr** [comment]
Hi @Ghavio1516 , sorry for the late response.

What do you mean by "just crash"? Is there any error message or does it simply shut down silently?

Thanks for posting the log, I'll check the codebase to see if there aren't any traps.

**Comment by Ghavio1516** [comment]
Yes,its not responding and crash :(

**Comment by only-a-ptr** [comment]
RoRConfig creates 2 logfiles: configlog.txt (the one you posted) and RoRConfig.log - post that one please.

**Comment by Ghavio1516** [comment]
Im currently not at home,ill try to post it tomorrow

**Comment by Ghavio1516** [comment]
here is the rorconfig

16:51:42: Creating resource group General
16:51:42: Creating resource group Internal
16:51:42: Creating resource group Autodetect
16:51:42: SceneManagerFactory for type 'DefaultSceneManager' registered.
16:51:42: Registering ResourceManager for type Material
16:51:42: Registering ResourceManager for type Mesh
16:51:42: Registering ResourceManager for type Skeleton
16:51:42: MovableObjectFactory for type 'ParticleSystem' registered.
16:51:42: ArchiveFactory for archive type FileSystem registered.
16:51:42: ArchiveFactory for archive type Zip registered.
16:51:42: ArchiveFactory for archive type EmbeddedZip registered.
16:51:42: DDS codec registering
16:51:42: FreeImage version: 3.15.3
16:51:42: This program uses FreeImage, a free, open source image library supporting all common bitmap formats. See http://freeimage.sourceforge.net for details
16:51:42: Supported formats: bmp,ico,jpg,jif,jpeg,jpe,jng,koa,iff,lbm,mng,pbm,pbm,pcd,pcx,pgm,pgm,png,ppm,ppm,ras,tga,targa,tif,tiff,wap,wbmp,wbm,psd,cut,xbm,xpm,gif,hdr,g3,sgi,exr,j2k,j2c,jp2,pfm,pct,pict,pic
16:51:42: Registering ResourceManager for type HighLevelGpuProgram
16:51:42: Registering ResourceManager for type Compositor
16:51:42: MovableObjectFactory for type 'Entity' registered.
16:51:42: MovableObjectFactory for type 'Light' registered.
16:51:42: MovableObjectFactory for type 'BillboardSet' registered.
16:51:42: MovableObjectFactory for type 'ManualObject' registered.
16:51:42: MovableObjectFactory for type 'BillboardChain' registered.
16:51:42: MovableObjectFactory for type 'RibbonTrail' registered.
16:51:42: *-*-* OGRE Initialising
16:51:42: *-*-* Version 1.9.0 (Ghadamon)
16:51:42: Loading library .\RenderSystem_Direct3D9
16:51:42: OGRE EXCEPTION(7:InternalErrorException): Could not load dynamic library .\RenderSystem_Direct3D9.  System Error: %1 is not a valid Win32 application.

 in DynLib::load at D:\ror\dev\dependencies\src\Ogre\ogre_src_v1-9\OgreMain\src\OgreDynLib.cpp (line 109)

**Comment by only-a-ptr** [comment]
This is the problem:
```
16:51:42: Loading library .\RenderSystem_Direct3D9
16:51:42: OGRE EXCEPTION(7:InternalErrorException): Could not load dynamic library 
```
Check there is a file `RenderSystem_Direct3D9.dll` in your RoR installation - if not, try re-installing, re-downloading and eventually check your antivirus's quarantine area.

**Comment by only-a-ptr** [comment]
Closing since the configurator was removed.
