### ISSUE TITLE
Overlong UTF-8 Sequence. Fatal Error

### ISSUE THREAD

**Issue by RealIi** [RigsOfRods/rigs-of-rods#1499]
I've got a fatal error everytime I try to launch the game. What can I do? Please, help me
![screenshot1](https://user-images.githubusercontent.com/38833882/39406228-edc82f9c-4bbb-11e8-8cdd-49f0ddb55da8.png)

**Comment by Michael10055** [comment]
I haven't seen this exact error before, but I assume it's the same issue as with the `Bad UTF-8 continuation byte` error - Special characters in your Windows username.  http://docs.rigsofrods.org/gameplay/general-faq/#q-clicking-single-player-results-in-a-bad-utf-8-continuation-byte-error

**Comment by only-a-ptr** [comment]
@RealIi Sorry for a delayed response.

First of all, post your RoR.log

It looks like some of the mods you have installed contains Unicode characters in it's name or description, and there's a bug in RoR which causes crash in such situation. Try removing all of your mods and play. If you get a crash, post RoR.log here. If not, move your mods back one by one and see which one is causing it.

**Comment by insanityies** [comment]
well i also have the problem but it says"please run RORconfig app" I ran it but i still receive the same error...

**Comment by only-a-ptr** [comment]
Closing for lack of RoR.log's.
