### ISSUE TITLE
Beam materials in set_beam_defaults do not appear in-game

### ISSUE THREAD

**Issue by Aivar-RoR** [RigsOfRods/rigs-of-rods#150]
Beam materials that are defined in set_beam_defaults do not appear:
![1](https://cloud.githubusercontent.com/assets/11720273/7009866/0d70fc08-dca6-11e4-8913-902606f78c85.jpg)

There are no errors in the log.
A few examples of the lines from the truck file:
>set_beam_defaults -1, -1, -1, -1, 0.01, tracks/wheelchair-black
set_beam_defaults -1, -1, -1, -1, 0.02, tracks/chrome
set_beam_defaults -1, -1, -1, -1, 0.015, tracks/wheelchair-green

(Everything is defined correctly in the .material files and no textures are missing.)
Tried to change the default negative values to real numbers:
>set_beam_defaults 9000000, 12000, 400000, 1000000, 0.015, tracks/wheelchair-green

The vehicle still uses the default material (tracks/beam).
This happens with other mods as well.

**Comment by only-a-ptr** [comment]
Fixed in my repo.
