### ISSUE TITLE
Legacy (0.36 era) set_beam_defaults- make old vehicles deform as intended, pre 2010-11 vehicles don't deform correctly

### ISSUE THREAD

**Issue by akaikitty** [RigsOfRods/rigs-of-rods#1506]
If this is possible.

Around 0.37 to 0.38 the beamdefaults were changed. This messed up compatability with older cars.

In 0.37.126 if you set enable_advanced_deformation to gabesters citeoren DS, it collapses. In 0.38.67 and above, the car behaves somewhat like the original in 0.36 but not as weak.

In newer versions, the lexus doesnt crash anyhwere as well, and gabesters old s10s from the 0.36 contents don't work right either. Same with the stock pricorde cars.

If we add something in the truck file i.e legacytruck, and have legacy beam defaults for cars with that flag, will that be possible? 

The same with planes,boats etc. anything with legacy nb is a bit wonky on new versions.

**Comment by Michael10055** [comment]
The main reason why older vehicles don't deform as well as they used to (along with `enable_advanced_deformation`) is the lack of a [Plastic deformation coefficient](http://docs.rigsofrods.org/vehicle-creation/fileformat-truck/#set_beam_defaults) `set_beam_defaults` value.

It basically defines how well a n/b can "hold" its deformation. The default value of `0.0` will cause the n/b to "bounce back" if you hit a wall.  Setting it to a value such as `1` will fix this. 
This was the case with Squishy's [crush loads](https://forum.rigsofrods.org/downloads.php?do=file&id=218), all I had to do was set the plastic deformation coefficient value to `1` on all `set_beam_defaults` lines and now they deform exactly as they did in 0.36.

**Comment by akaikitty** [comment]
What if the n/b doesn't have other properties, like the optional ones shown? Should i use default values for the other properties that aren't included, or do i have to add everything -1, then 1 for the plastic coefficient?

**Comment by Michael10055** [comment]
If it doesn't have a `set_beam_defaults` line, add one above the beams section:
`set_beam_defaults -1, -1, -1, -1, 0.05, 1`

**Comment by Michael10055** [comment]
I'm closing this as there's no easy way to do this without breaking all newer mods. Even if a new truck file section was added, you'd still have to edit the .truck files anyway.
