### ISSUE TITLE
Reloading vehicles broken?

### ISSUE THREAD

**Issue by Michael10055** [RigsOfRods/rigs-of-rods#1515]
Reloading vehicles (`CTRL+SHIFT+R`) appears to no longer function, the vehicle remains the same even after you've made changes to the `.truck` file.

- Extract any mod archive into a folder. (e.g. `Documents\Rigs of Rods 0.4\vehicles\dafsemi`)
- Regen to add the extracted mod to the cache.
- Spawn the vehicle, then open the truck file and make any major change (e.g. comment out the wheels section) then switch back to RoR and press `CTRL+SHIFT+R`. You'll see the "Reload X of 5000" message at the top right, but no change will actually be made to the vehicle.

**Comment by only-a-ptr** [comment]
(>.<) Doh! My fault, I "optimized" loading vehicles by always re-using the parsed truckfile data. It didn't occur to me modders would always want to reload from disk.

I'll update the reload routine to always re-process the truckfile.

**Comment by only-a-ptr** [comment]
Closing, the problem was already fixed a while ago: https://github.com/RigsOfRods/rigs-of-rods/blob/b1d2d476c5988e1472a8e78f95ac6c41d77b8ee2/source/main/physics/BeamData.h#L575
