### ISSUE TITLE
Anyone know how to fix this

### ISSUE THREAD

**Issue by liamthe** [RigsOfRods/rigs-of-rods#1517]
![image](https://user-images.githubusercontent.com/40327382/41503462-474d5f58-71a3-11e8-8d08-0e453c476034.png)

copy the link to see the image

**Comment by Michael10055** [comment]
Change the Video Mode setting in the Render System tab of RoRConfig.

**Comment by liamthe** [comment]
![image](https://user-images.githubusercontent.com/40327382/41503499-2c9fbfa6-71a4-11e8-9e6d-73ae97211f4d.png)

now this is happening when i open the config

**Comment by AnimosusTheWolf** [comment]
Run RoRConfig as admin.

**Comment by Michael10055** [comment]
If running as admin doesn't work, uninstall the game, delete the `Rigs of Rods 0.4` folder from Documents,  then reinstall.

**Comment by liamthe** [comment]
ok
