### ISSUE TITLE
Invalid FOV settings breaks gameplay

### ISSUE THREAD

**Issue by 2KSam** [RigsOfRods/rigs-of-rods#1525]
ROR uploads correctly but once I have loaded the map there is only aerial view. The other views are blocked out by this pasty colored screen (see attached). I can't figure this out could someone help??? 
![screenshot_2018-06-29_13-06-31_1](https://user-images.githubusercontent.com/40699455/42105329-ed04cc8e-7b9d-11e8-8b31-729f6c287b66.jpg)

**Comment by Michael10055** [comment]
Check if your FOV is set to 0:
![image](https://user-images.githubusercontent.com/11002490/42105394-2c63a7f6-7b9e-11e8-8736-2679b2eb391f.png)

**Comment by 2KSam** [comment]
That fixed it!!! Thanks, Michael.

**Comment by Michael10055** [comment]
@only-a-ptr Doesn't #1500 fix this?

**Comment by only-a-ptr** [comment]
@Michael10055 Yes it does 😊
