### ISSUE TITLE
Crash when connecting to multiplayer (Entity with name 'Character0_mesh` already exists)

### ISSUE THREAD

**Issue by Michael10055** [RigsOfRods/rigs-of-rods#1527]
![image](https://user-images.githubusercontent.com/11002490/42608219-d4644e5a-8554-11e8-93d8-21947cd33421.png)
Screenshot says it all really. To reproduce, just join the 2.40 Dev server with two RoR clients.

**Comment by only-a-ptr** [comment]
My bad 😊
Fix pending
