### ISSUE TITLE
Auto-correction of vehicle spawn height.

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#153]
I have noticed that some vehicles spawn a few feet in the air, sometimes even a few yards, and then when they land, at least about 20 beams are deformed, causing the car to drive slightly to the side at high speeds. Some cars, however, don't have this issue. This should be fixed, and thanks for reading!

**Comment by Max98** [comment]
I believe that this is just a mistake that the modder made while making his mod. 
When the n/b isn't at y = 0, the car will spawn few meters in the air, or few meters in the ground.
It would be better if you can give us an example of a car, so I can confirm my theory.

**Comment by gigapouch** [comment]
I see now. One example is pretty much every Gavril car. They always spawn with at least 20 deformed beams, if not more.

**Comment by gigapouch** [comment]
Is this topic dead?

**Comment by Max98** [comment]
Nothing is dead when it comes to issue resolving. It's just that we ( @only-a-ptr @Aperion @Hiradur & me ) are pretty busy with few other things for the moment.

**Comment by gigapouch** [comment]
Oh, OK.

**Comment by only-a-ptr** [comment]
@gigapouch : This is indeed a mistake of the vehicle's authors, like Max98 says. The N/B (nodes & beams) positions were defined too high.

Fixing this by hand is impossible, it would require changing every single node.

However, we may create an optional "height adjuster", which would detect that a truck/car is defined too high ((axle_node_height - wheel_radius) > MAX_HEIGHT) and lower all nodes automatically.

**Comment by only-a-ptr** [comment]
@Gigapouch: please give us links to some problematic vehicles, with descriptions of the problems. I need it for testing. Thanks.

**Comment by gigapouch** [comment]
Here's one (not by Gabester): http://www.rigsofrods.com/threads/106589-2003-Ford-Windstar-LX?highlight=windstar
This one spawns in a way so that the front of the car is way too high, causing the front beams and a few in the back to be deformed, plus the door looks ajar from the inside.

Here's another one (by Gabester): http://www.rigsofrods.com/threads/71461
This one, like most other cars by Gabester (excluding the Burnside series), spawns with at least 25 deformed beams.

**Comment by gigapouch** [comment]
I'm bumping this.

**Comment by DirtGamer301** [comment]
The deforming beams are also from the mod authors (I think) as the same things happen in 0.38/0.4.0.7. It's little things that don't really matter when making a mod and are hard to fix as it takes some time (set_beam_defaults would be required for this, hope I don't give false infos). It's only happening with full flexbody cars, too, as they're more complex.

**Comment by only-a-ptr** [comment]
Tools to fine-tune vehicle spawn position will be addes as part of RigEditor - eventually.
Auto-correction of spawn height for existing vehicles may also be implemented - low priority task.

**Comment by ulteq** [comment]
Fixed as of: https://github.com/RigsOfRods/rigs-of-rods/pull/565
