### ISSUE TITLE
Game crashes when loading any vehicle

### ISSUE THREAD

**Issue by PastaBoye** [RigsOfRods/rigs-of-rods#1530]
Windows 10, tried everything I can think of so far.

Here's my [RoR.log](https://pastebin.com/6UHZi2Qh)

**Comment by Michael10055** [comment]
Try disabling force feedback:
![image](https://user-images.githubusercontent.com/11002490/42857918-ffc58d56-8a19-11e8-959a-b307965982fe.png)

**Comment by PastaBoye** [comment]
that worked! thanks much
