### ISSUE TITLE
Build error, RoRConfig can't be made!

### ISSUE THREAD

**Issue by bihhs-mk** [RigsOfRods/rigs-of-rods#1531]
I was really hoping the program is going to run, but at 96% of building, it stopped with some errors. Please help me because I really want to try this game because it looks very cool. I really want to play it with my cousin and brother.
Here is what happened:

[ 96%] Built target RoR
In file included from /usr/include/gtk-2.0/gdk/gdkscreen.h:32:0,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from /home/muhamed/prog/Games/RigsOfRods/linux/rigs-of-rods/source/configurator/wxutils.h:7,
                 from /home/muhamed/prog/Games/RigsOfRods/linux/rigs-of-rods/source/configurator/Configurator.cpp:79:
/usr/include/gtk-2.0/gdk/gdktypes.h:114:39: error: conflicting declaration ‘typedef struct _GdkDrawable GdkWindow’
 typedef struct _GdkDrawable           GdkWindow;
                                       ^~~~~~~~~
In file included from /usr/include/wx-3.0/wx/event.h:14:0,
                 from /usr/include/wx-3.0/wx/app.h:19,
                 from /home/muhamed/prog/Games/RigsOfRods/linux/rigs-of-rods/source/configurator/RoRConfig.h:29,
                 from /home/muhamed/prog/Games/RigsOfRods/linux/rigs-of-rods/source/configurator/Configurator.cpp:22:
/usr/include/wx-3.0/wx/defs.h:3412:31: note: previous declaration as ‘typedef struct _GdkWindow GdkWindow’
     typedef struct _GdkWindow GdkWindow;
                               ^~~~~~~~~
In file included from /home/muhamed/prog/Games/RigsOfRods/linux/rigs-of-rods/source/configurator/wxutils.h:8:0,
                 from /home/muhamed/prog/Games/RigsOfRods/linux/rigs-of-rods/source/configurator/Configurator.cpp:79:
/home/muhamed/prog/Games/RigsOfRods/linux/rigs-of-rods/source/configurator/wxutils.h: In function ‘size_t getOISHandle(wxWindow*)’:
/usr/include/gtk-2.0/gdk/gdkx.h:113:69: error: cannot convert ‘GdkWindow* {aka _GdkWindow*}’ to ‘GdkDrawable* {aka _GdkDrawable*}’ for argument ‘1’ to ‘XID gdk_x11_drawable_get_xid(GdkDrawable*)’
 #define GDK_WINDOW_XID(win)           (gdk_x11_drawable_get_xid (win))
                                                                     ^
/home/muhamed/prog/Games/RigsOfRods/linux/rigs-of-rods/source/configurator/wxutils.h:54:20: note: in expansion of macro ‘GDK_WINDOW_XID’
     hWnd = (size_t)GDK_WINDOW_XID(gtk_widget_get_window(window->GetHandle()));
                    ^
In file included from /usr/include/wx-3.0/wx/event.h:14:0,
                 from /usr/include/wx-3.0/wx/app.h:19,
                 from /home/muhamed/prog/Games/RigsOfRods/linux/rigs-of-rods/source/configurator/RoRConfig.h:29,
                 from /home/muhamed/prog/Games/RigsOfRods/linux/rigs-of-rods/source/configurator/Configurator.cpp:22:
/usr/include/wx-3.0/wx/defs.h:3412:20: note: class type ‘GdkWindow {aka _GdkWindow}’ is incomplete
     typedef struct _GdkWindow GdkWindow;
                    ^~~~~~~~~~
source/configurator/CMakeFiles/RoRConfig.dir/build.make:62: recipe for target 'source/configurator/CMakeFiles/RoRConfig.dir/Configurator.cpp.o' failed
make[2]: *** [source/configurator/CMakeFiles/RoRConfig.dir/Configurator.cpp.o] Error 1
CMakeFiles/Makefile2:344: recipe for target 'source/configurator/CMakeFiles/RoRConfig.dir/all' failed
make[1]: *** [source/configurator/CMakeFiles/RoRConfig.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
$ ^C
$ 

I'm using Fedora 24.
Thanks for your time!

**Comment by only-a-ptr** [comment]
Hello. This is the culprit:
```
/usr/include/gtk-2.0/gdk/gdktypes.h:114:39: *** _GdkDrawable GdkWindow’
/usr/include/wx-3.0/wx/defs.h:3412:31: *** _GdkWindow GdkWindow’
```
Something's wrong with your wxWidgets3 devel package. 
I was able to google a few other reports of this problem: https://github.com/sirjuddington/SLADE/issues/530, https://sourceforge.net/p/gnuplot/mailman/message/32937171/, https://forums.wxwidgets.org/viewtopic.php?t=43779 - but no definite solution. It looks like 2 flavors of 'wxWidgets3'exist: one using GTK+2 and other using GTK+3, and you need to use the other one. But I don't really know for sure, I work on Windows.

**Comment by ulteq** [comment]
@bihhs-mk were you able to resolve the issue?

**Comment by bihhs-mk** [comment]
I just tweaked the already existing [script for Fedora](https://github.com/vbextreme/RigsOfRodsFedora) and it worked. That means the Fedora script can be used on older Fedora versions too. Thanks for your help.
