### ISSUE TITLE
Cannot create file/unable to load the game

### ISSUE THREAD

**Issue by HockHard** [RigsOfRods/rigs-of-rods#1532]
I tried to dowload the game and everything went fine but as I click save and play in the configurator these messages appear:
11:41:26: can't open file 'C:\Users\DOCUME~1\Rigs of Rods 0.4\\cache\empty'
11:41:26: Can not create file 'C:\Users\DOCUME~1\Rigs of Rods 0.4\\cache\empty'.
Anyone knows what to do?

**Comment by AnimosusTheWolf** [comment]
Run rorconfig as an administrator.

**Comment by HockHard** [comment]
Ok, that's what I tought, I will try

**Comment by AnotherFoxGuy** [comment]
@HockHard Did it fix your issue?
