### ISSUE TITLE
Caelum Plugin not found (ror-dependencies)

### ISSUE THREAD

**Issue by ulteq** [RigsOfRods/rigs-of-rods#1540]
The path to `libCaelum.so` in the plugins.cfg is incorrect, when you build `rigs-of-rods` against `ror-dependencies`.

The `ror-dependencies` build script places `libCaelum.so` in
```
/ror-dependencies/Dependencies_Linux/lib/
```
and not in
```
/ror-dependencies/Dependencies_Linux/lib/OGRE/
```

This is where the path is set:
https://github.com/RigsOfRods/rigs-of-rods/blob/6745227efe9f4c1517ab048b75ac44f0726d1530/source/main/CMakeLists.txt#L510

**Comment by tritonas00** [comment]
Also why `Plugin=Plugin_CgProgramManager` is commented by default?
