### ISSUE TITLE
Lights(FLARES) can not be enabled/disabled in skeleton view

### ISSUE THREAD

**Issue by disloyalpick** [RigsOfRods/rigs-of-rods#1559]
Steps to reproduce...
1. Spawn any vehicles that has flares...
2. Turn flares on with N-key...
3. Press K to enable skeleton view...
4. Try pressing N-Key and flares will not turn off.

Flares will also not turn on in skeleton view.

It's not a huge issue. Just figured I would point it out

**Comment by AnimosusTheWolf** [comment]
In the latest dev build with the new skeleton view? They are working fine for me in the latest build.

**Comment by disloyalpick** [comment]
i havent checked that. ill have a look

**Comment by tritonas00** [comment]
@disloyalpick any update on this?

it works here
