### ISSUE TITLE
MyGUI 3.2.2 not supported

### ISSUE THREAD

**Issue by skybon** [RigsOfRods/rigs-of-rods#156]
Compilation of latest git snapshot fails with the following error:
```
[ 67%] Building CXX object source/main/main_sim/CMakeFiles/RoR.dir/__/gui/GUIInputManager.cpp.o
/home/artem/AUR/rigsofrods-git/src/rigs-of-rods/source/main/gui/GUIInputManager.cpp: В функции-члене «virtual bool GUIInputManager::keyPressed(const OIS::KeyEvent&)»:
/home/artem/AUR/rigsofrods-git/src/rigs-of-rods/source/main/gui/GUIInputManager.cpp:226:22: ошибка: «struct MyGUI::KeyCode» has no member named «toValue»
  int scan_code = key.toValue();
                      ^
source/main/main_sim/CMakeFiles/RoR.dir/build.make:3435: ошибка выполнения рецепта для цели «source/main/main_sim/CMakeFiles/RoR.dir/__/gui/GUIInputManager.cpp.o»
make[2]: *** [source/main/main_sim/CMakeFiles/RoR.dir/__/gui/GUIInputManager.cpp.o] Ошибка 1
CMakeFiles/Makefile2:111: ошибка выполнения рецепта для цели «source/main/main_sim/CMakeFiles/RoR.dir/all»
make[1]: *** [source/main/main_sim/CMakeFiles/RoR.dir/all] Ошибка 2
Makefile:75: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2
```

Using MyGUI 3.2.2 compiled against OGRE 1.8 on Arch Linux x86-64.

https://aur.archlinux.org/packages/my/mygui-ogre1.8/PKGBUILD
https://aur.archlinux.org/packages/ri/rigsofrods-git/PKGBUILD

**Comment by tritonas00** [comment]
libMyGUI.OgrePlatform.so should be  libMyGUI.OgrePlatform.a

also change the angelscript path, /opt/ror is for my modification https://github.com/tritonas00/rigsofrods-git/blob/master/angelscript-2.22.1/PKGBUILD, use /usr/include

**Comment by Hiradur** [comment]
MyGUI 3.2.2 is not supported. You need SVN revision 4344. Also see http://www.rigsofrods.com/wiki/pages/Compiling_3rd_party_libraries

**Comment by skybon** [comment]
@tritonas00 Thanks for spotting the error, fixed. AngelScript installation path should be fixed by angelscript-2.22.1 maintainer first.

@Hiradur Uh-huh, I see. SVN commit !(4549 http://sourceforge.net/p/my-gui/code/4549) broke the API, looks like a small patch can correct that.

**Comment by tritonas00** [comment]
No problem :)

I used this https://github.com/MyGUI/mygui/archive/MyGUI3.2.tar.gz

check PKGBUILD https://github.com/tritonas00/rigsofrods-git/blob/master/mygui-3.2/PKGBUILD

**Comment by skybon** [comment]
Rejoice! With a bit of sorcery (sedding the deprecated method) AUR package compiles now.
```sed -i 's/key.toValue/key.getValue/' ./source/main/gui/GUIInputManager.cpp ./source/main/gui/Console.cpp ./source/main/gui/LobbyGUI.cpp```

**Comment by tritonas00** [comment]
Nice, but why dont just use 3.2? :P

**Comment by skybon** [comment]
I am not really sure if RoR is more compatible with 3.2 than 3.2.2. The recommended version is SVN rev. 4344.

**Comment by tritonas00** [comment]
Fair enough :)

**Comment by Max98** [comment]
@skybon Is this fixed yet?

**Comment by skybon** [comment]
Nope.

**Comment by Hiradur** [comment]
Fixed in Ogre 2.0 branch

**Comment by Hubbitus** [comment]
In [doc](http://www.rigsofrods.com/wiki/pages/Compiling_3rd_party_libraries#MyGUI_.28GUI.29) you state: "This is available in recent Fedora repositories. If the dnf install described above has succeeded, then you will not need to build from source."

But rawhide [contains 3.2.1-7 version](https://kojipkgs.fedoraproject.org//work/tasks/6410/12586410/root.log) and build fails in same way:
```
/builddir/build/BUILD/rigs-of-rods-23c619a9010e375ea7357ef190ff683f2beac5d4/source/main/RoRPrerequisites.h:66:39: error: 'struct MyGUI::KeyCode' has no member named 'toValue'
 # define MYGUI_GET_SCANCODE(KEY) (KEY.toValue())
```

https://kojipkgs.fedoraproject.org//work/tasks/6410/12586410/build.log

Does Ogre 2.0 branch ready? Should it be used now?

**Comment by Hubbitus** [comment]
It seams just version in condition is incorrect. Should be:
```
$ cat rigsofrods-0.4.6.0-mygui-gt-2.2.1.patch
diff -NurEbBH rigs-of-rods-23c619a9010e375ea7357ef190ff683f2beac5d4.orig/source/main/RoRPrerequisites.h rigs-of-rods-23c619a9010e375ea7357ef190ff683f2beac5d4/source/main/RoRPrerequisites.h
--- rigs-of-rods-23c619a9010e375ea7357ef190ff683f2beac5d4.orig/source/main/RoRPrerequisites.h   2016-01-07 23:27:32.000000000 +0300
+++ rigs-of-rods-23c619a9010e375ea7357ef190ff683f2beac5d4/source/main/RoRPrerequisites.h        2016-01-17 20:21:46.465101398 +0300
@@ -60,7 +60,7 @@

 #include <MyGUI_Prerequest.h> // Forward declarations

-#if MYGUI_VERSION >= 0x030202
+#if MYGUI_VERSION >= 0x030201
 #      define MYGUI_GET_SCANCODE(KEY) (KEY.getValue())
 #else
 #      define MYGUI_GET_SCANCODE(KEY) (KEY.toValue())
```

**Comment by Hiradur** [comment]
@Hubbitus This has already been fixed in master: https://github.com/RigsOfRods/rigs-of-rods/pull/547

**Comment by Hubbitus** [comment]
Thank you!
