### ISSUE TITLE
Transmission indicators freeze in some vehicles when going back to menu

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1560]
~Load simple terrain and spawn this http://archives.rigsofrods.net/repo/files/repofiles-3rd-batch/df0ec67470bf500641d7f05f1a47cf0a7631b9ab_Mercedes-Benz-Actros-8x8-wrecker.zip~

~Switch to first person view (dashboard view) and drive: transmission indicators work fine~

~Press Back to menu, reload simple terrain and respawn it again: transmission indicators are stuck~

FIXED

**Comment by tritonas00** [comment]
This is still happening

@only-a-ptr is this an easy one? Probably something is not cleaned up properly

**Comment by tritonas00** [comment]
I found a almost similar issue with airplanes hud so i add it here:

Spawn [An-12.zip](https://github.com/RigsOfRods/rigs-of-rods/files/2675941/An-12.zip) and throttle up, press parking brakes etc:
![ant](https://user-images.githubusercontent.com/2660424/49939055-5bbe5900-fee4-11e8-9fe2-3298c14dcf3a.png)

remove the antonov and spawn another plane like skyvan: hud keeps the previous settings:
![sky](https://user-images.githubusercontent.com/2660424/49939161-afc93d80-fee4-11e8-9847-e9cddd169a60.png)

**Comment by only-a-ptr** [comment]
Looks dangerous, as if an invalid pointer or actorID was left hanging in the GUI code. Let me see...

**Comment by tritonas00** [comment]
The issue in the first comment is now fixed on master!

But the airplane hud still happens?

@only-a-ptr can you take a look please?

issue-> airplane hud is not reset when you spawn second (and beyond) airplane
