### ISSUE TITLE
Not All Loading Screen Wallpapers Are 16:9 or 1920x1080

### ISSUE THREAD

**Issue by graysonk95** [RigsOfRods/rigs-of-rods#158]
Wallpaper images loading_11.png through loading_16.png are not 16:9  or 1920x1080.

Loading_12.png for example has an aspect ratio of 952:501 (1904x1002) so the front wheel of the truck is shaped like a '0' when stretched to fit my 16:10 monitor (and it probably looks funny on a 16:9 monitor too).

**Comment by Max98** [comment]
Let's say that this is not a bug, because it doesn't do anything harm to the game :| 
Anyway, will fix.

**Comment by Hiradur** [comment]
They should be exported to jpeg to decrease download size. A jpeg quality level of ~90 gives good quality while still making the images much smaller.

**Comment by Hiradur** [comment]
I tried RoR on a 5:4 screen and the images get squashed significantly. Instead of resizing them RoR could cut them to match the aspect ratio of the screen. What do you think?

**Comment by Olius** [comment]
Or it could add black borders, or a mix of cropping and adding borders. Cropping seems best though, black borders arent so nice…
If I can do anything else, tell me.

**Comment by Olius** [comment]
I sent the 1920x1080 jpeg images to max98 by the way, but I have to idea how to convert them to UHD format, so I didn't do that part.
Is UHD sort of like anti-aliasing?

**Comment by Hiradur** [comment]
@Olius UHD is a higher resolution (many call it "4K" but that term is actually incorrect) and will probably replace Full-HD sooner or later.
Even if your screen doesn't support UHD resolution you can still somewhat achieve it by using super-sampling which renders the game at UHD and then resizes the image to the resolution of your screen. This creates an anti-aliasing effect. It's similar to how pictures taken with a camera at 8 megapixel look incredibly sharp on your screen even though your screen only has a fraction of the pixel count the image has.

**Comment by Olius** [comment]
Sounds like beamNG is gonna get some serious competition if you're aiming for UHD menu screenshots :)

**Comment by Hiradur** [comment]
UHD can make the screenshots look much better (have a look at how realistic some of these shots look: https://www.flickr.com/photos/15539352@N02/sets/72157632886023166/ ). 
But in the end it all boils down to the motive though.

**Comment by Olius** [comment]
That looks absolutely amazing...

**Comment by Hiradur** [comment]
@Max98 Is this is in upstream yet? I also noticed that one of the screens has a 60FPS overlay in the left upper corner. :P
