### ISSUE TITLE
C++17 not enabled by default by the build system

### ISSUE THREAD

**Issue by siradam7th** [RigsOfRods/rigs-of-rods#1582]
It will be nice to have C++17 enabled by default, so we can write C++17 code.

> **it's already supported by the compilers we use (MSVC, GCC, Clang).**

**Comment by AnotherFoxGuy** [comment]
Just place this somewere in the main `CMakeLists.txt`
```
# Set global C++ standard for all targets.
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS ON)
```
