### ISSUE TITLE
Patch Ogre to compile on C++17

### ISSUE THREAD

**Issue by siradam7th** [RigsOfRods/rigs-of-rods#1583]
I can't patch it myself since it's a dependency,so whoever can,do the following:

include/OGRE/OgreString.h
add this on line 212:
``` cpp
#elif OGRE_COMPILER == OGRE_COMPILER_MSVC && defined(_HAS_CXX17)
    typedef std::hash< _StringBase > _StringHash;
```
just before this:
``` cpp
#elif OGRE_COMPILER == OGRE_COMPILER_MSVC && OGRE_COMP_VER >= 1600 && !defined(STLPORT) // VC++ 10.0
	typedef ::std::tr1::hash< _StringBase > _StringHash;
``` 

include/OGRE/OgrePrerequisites.h
add this on line 91:
``` cpp
    #       if defined(_HAS_CXX17)
    #           define HashMap ::std::unordered_map
    #           define HashSet ::std::unordered_set
``` 
and replace the following which should be right after it:
``` cpp
    #       if _MSC_FULL_VER >= 150030729 // VC++ 9.0 SP1+
```

with this:
``` cpp
    #       elif _MSC_FULL_VER >= 150030729 // VC++ 9.0 SP1+
```

to make sure it compiles correctly,enable C++17 since it's not enabled by default.

**Comment by only-a-ptr** [comment]
Yes you can, fork OGRE and create a PR with exactly this change. 👍

**Comment by siradam7th** [comment]
@only-a-ptr what repo?

**Comment by AnotherFoxGuy** [comment]
@siradam7th This one: https://github.com/OGRECave/ogre
