### ISSUE TITLE
vehicle parts are deformed after spawn

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#16]
This issue impacts many vehicles.
![ror_2015](https://cloud.githubusercontent.com/assets/1196375/5692201/06ed2544-98ec-11e4-84f7-0b01088cfc3b.png)
http://www.rigsofrods.com/threads/83964-Gavril-Bandit-Now-with-better-roofline-and-handling

**Comment by only-a-ptr** [comment]
@Speciesx : How do I evaluate that "many vehicles" are now working well? :smile:
Please give me a specific list of issues to resolve.

**Comment by only-a-ptr** [comment]
@Speciesx : The issue displayed on your screenshots is actually an v0.4.0.7 issue, the version by Ulteq does it too. I'll try resolving it, but no promises
