### ISSUE TITLE
 Terrain Greece Hills fails to load

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1600]
![ror_2018_10_02_23_38_07_954](https://user-images.githubusercontent.com/1196375/46378677-b180b480-c69c-11e8-8992-17a5a636712a.jpg)

https://forum.rigsofrods.org/downloads.php?do=file&id=33

[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/2439805/RoR.log)

**Comment by only-a-ptr** [comment]
Curious, nothing useful in RoR.log. Try clearing your cache, maybe. What build is that?

**Comment by Speciesx** [comment]
RoR-V0.4.8.0-CIBuild-130-idlisyiu
Cleared the cache already few times.

**Comment by tritonas00** [comment]
Same on Archlinux
