### ISSUE TITLE
Cannot Run Configurator on Mapped Network Drive

### ISSUE THREAD

**Issue by CoelacanthsKill** [RigsOfRods/rigs-of-rods#1604]
I installed RoR 0.4.7.0 to a local drive, D:
I have a network drive mapped to X: and My Documents pointed to X:/Documents (assuming RoR is trying to place files in My Documents)

When RoR Configurator tried to run, it spits out the error: 
![image](https://user-images.githubusercontent.com/7817229/46452214-2e289700-c760-11e8-968a-6cc8838d137a.png)

**Comment by ThePiGuy24** [comment]
try running it as administrator

**Comment by CoelacanthsKill** [comment]
> try running it as administrator

Same thing.

**Comment by CoelacanthsKill** [comment]
![image](https://user-images.githubusercontent.com/7817229/46920163-d421a000-cfaf-11e8-9db7-16294f6fd0a0.png)

When running as Admin

**Comment by only-a-ptr** [comment]
Is your username 'DBJGBY~H' or is RoR shortening it to DOS 8-character format?

You're saying RoR's user directory should be `X:\Documents\Rigs of Rods 0.4`, but the log shows `X:\DBJGBY~H\DBJGBY~H\Rigs of Rods 0.4`, which is very different.

**Comment by CoelacanthsKill** [comment]
I'm not saying it should be, but I have windows profile directories mapped to my X: network drive and assume RoR is trying to R/W files to windows profile directories.

**Comment by only-a-ptr** [comment]
> assume RoR is trying to R/W files to windows profile directories.

Yes it does

> I have windows profile directories mapped to my X: network drive

That I understood, but I need exact details: 
* your username - is it 'DBJGBY~H'?
* The exact configured path of MyDocuments

**Comment by CoelacanthsKill** [comment]
My windows username is Pat and the exact path of My Documents is X:/Documents/Documents. I do not understand why RoR trying to use "DBJGBY~H" as a path. 

I used the "Move" feature under the Location tab of My Documents Properties

**Comment by only-a-ptr** [comment]
RoR somehow forces Windows to yield paths squeezed to DOS-8.3 format, i.e. `DOCUME~1` instead of `Documents`. The "DBJGBY~H" looked similar (8 chars), I googled and found explanation: https://stackoverflow.com/a/6471531

I need to fix RoR's file subsystem, unfortunately I won't be able to do it for next 3 weeks.

**Comment by CoelacanthsKill** [comment]
its ok, i have never played the game before and can wait a few more weeks lol.

**Comment by only-a-ptr** [comment]
Closing since configurator was removed
