### ISSUE TITLE
vehicles texture issues

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1609]
~~spawn [gavril mz2r](https://www.dropbox.com/s/28z9910o82492u2/gavrilmz2.zip?dl=1), remove it, then spawn [gavril omega 12](http://archives.rigsofrods.net/repo/files/repofiles-1st-batch/1667c2bc32fe5aef7533d5f972878ca2ca4ecb1a_gavrilomega.zip)~~

Fixed

It happens again some times (a bit hard to reproduce)

**Comment by only-a-ptr** [comment]
It works 😄  That's a managedmaterial-error marker color I implemented as part of #1271: https://github.com/RigsOfRods/rigs-of-rods/blob/master/resources/materials/ror.material#L2960

**Comment by tritonas00** [comment]
Similar issue maybe

spawn dodge magnum street (https://www58.zippyshare.com/v/Mley4RGy/file.html) and switch to dashboard view:
![2018-10-16-211408_1366x768_scrot](https://user-images.githubusercontent.com/2660424/47037840-b0fe1880-d188-11e8-811e-a2a0abf19f3f.png)

It happens with default grey color. The orange version works fine

**Comment by tritonas00** [comment]
Tatra-T813-Dakar changing colors as you drive it or move the camera around it:
![tatra](https://user-images.githubusercontent.com/2660424/48572979-a499e680-e913-11e8-8ad8-0e7694819009.png)

**Comment by only-a-ptr** [comment]
> Tatra-T813-Dakar changing colors as you drive it or move the camera around it:

Looks like a videocard/driver/corrupted download issue. Try changing settings: sky, envmap, shadows etc. and post RoR.log

**Comment by ulteq** [comment]
I also have this issue, which I never had with the previous Ogre version.

**Comment by tritonas00** [comment]
this introduced with the ogre 1.11 update (767 AA Airliner):
![767](https://user-images.githubusercontent.com/2660424/48792208-52ced300-ecfc-11e8-946b-a9f97ee67fae.png)
It varies from map to map or light changes

**Comment by only-a-ptr** [comment]
I found the issue with GavrilMZ2R/Omega -> messy truckfile. MZ2R's truckfile also contains omega's managedmaterials which fail to load (missing textures) and leave the awful pink placeholders hanging around with Omega's material names.
```
22:54:12: [RoR] Parsing truckfile 'gavrilmz2.truck'
22:54:12: Ogre::ItemIdentityException::ItemIdentityException: Unable to derive resource group for omegawheelband.dds automatically since the resource was not found. in ResourceGroupManager::findGroupContainingResource at c:\conan\.conan\data\ogre\1.11.4\anotherfoxguy\stable\build\2d13f0c58bafe8a9fae74369aea9c086e652e9f3\ogremain\src\ogreresourcegroupmanager.cpp (line 1670)
22:54:12: Ogre::ItemIdentityException::ItemIdentityException: Unable to derive resource group for omegawheel_s.dds automatically since the resource was not found. in ResourceGroupManager::findGroupContainingResource at c:\conan\.conan\data\ogre\1.11.4\anotherfoxguy\stable\build\2d13f0c58bafe8a9fae74369aea9c086e652e9f3\ogremain\src\ogreresourcegroupmanager.cpp (line 1670)
22:54:12: Ogre::ItemIdentityException::ItemIdentityException: Unable to derive resource group for omegawheel_s.dds automatically since the resource was not found. in ResourceGroupManager::findGroupContainingResource at c:\conan\.conan\data\ogre\1.11.4\anotherfoxguy\stable\build\2d13f0c58bafe8a9fae74369aea9c086e652e9f3\ogremain\src\ogreresourcegroupmanager.cpp (line 1670)
22:54:13:  == Parsing done, report:

#FFFF00 WARNING #FFFFFF (Section managedmaterials)
	Line (15): omegawheelband		mesh_standard		omegawheelband.dds	-
	Message: Missing texture file: omegawheelband.dds
#FFFF00 WARNING #FFFFFF (Section managedmaterials)
	Line (16): omegawheelb		mesh_standard		omegawheel_s.dds	omegawheel_s.dds
	Message: Missing texture file: omegawheel_s.dds
#FFFF00 WARNING #FFFFFF (Section managedmaterials)
	Line (16): omegawheelb		mesh_standard		omegawheel_s.dds	omegawheel_s.dds
	Message: Missing texture file: omegawheel_s.dds
```
However, RoR should really clean all the materials when MZ2R is unloaded. That's a bug.
