### ISSUE TITLE
vehicle parser not accepting invalid flags, old parser set all invalid flags to default

### ISSUE THREAD

**Issue by fidoj** [RigsOfRods/rigs-of-rods#161]

**Comment by fidoj** [comment]
this is the reason a lot of vehicle/loads/etc dont work

**Comment by only-a-ptr** [comment]
@fidoj: True, in the original design, bad flags were treated as syntax errors and whole lines were rejected.
However, this rule had already proven too strict. Some section already accept bad flags and print warnings only. I'll apply this logic on all remaining sections.

**Comment by fidoj** [comment]
can you make it so the log output for advanced logging is overruled in this instance, and so it outputs valid flags? so a content creator can easily correct mistakes, i know its more lines of code but you could write 1 line to read the valid flags, then output it to log

**Comment by only-a-ptr** [comment]
At this point, almost all flags behave the way they did in 0.38.
Advanced logging will be handled after 0.4.5 release.
After 0.4.5 I'm planning a major overhaul of the entire vehicle subsystem, so there is little to solve right now.
