### ISSUE TITLE
add remove button to actors menu

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1616]
![ror_2018_10_06_22_56_45_137](https://user-images.githubusercontent.com/1196375/46575841-b2c42100-c9bd-11e8-9542-142dae4b0f5d.jpg)

Maybe something like this.

**Comment by only-a-ptr** [comment]
Maybe one step further?
![image](https://user-images.githubusercontent.com/491088/46665121-3569fd80-cbc3-11e8-8663-53c437bb00f6.png)

**Comment by ulteq** [comment]
A `Remove all` button would come in handy. As suggested by @tritonas00.
