### ISSUE TITLE
Issues with .fixed objects

### ISSUE THREAD

**Issue by graysonk95** [RigsOfRods/rigs-of-rods#162]
Fixed terrain objects seem to be having issues (I believe there were placement issues in 0.4.0.7 too, so they probably have been broken for a while).
A majority of them are placed incorrectly, and a few seem to fall through the ground when activated. Examples below:

On the map Russia the hall doors fall through the ground, and the crane falls too but it lands on the ground.
The hall and hall doors are improperly placed, and the doors fall through the ground when activated. The crane falls too, but it lands on the ground.
![screenshot_458](https://cloud.githubusercontent.com/assets/10550037/7318516/ac60ff0e-ea5a-11e4-9ebc-cb858e91e4bf.png)

On North St. Helens the bridge is placed incorrectly and the beams for the bridge structure seem to be reverted to the default beam size:
![screenshot_459](https://cloud.githubusercontent.com/assets/10550037/7318530/d19e4678-ea5a-11e4-9145-6f40fee2e1be.png)
The fixed crane is spawned under the concrete dock and explodes/spazzed when activated:
![screenshot_460](https://cloud.githubusercontent.com/assets/10550037/7318598/95f0675e-ea5b-11e4-9271-6d5fe23e6b83.png)

Also, unrelated, but RoRBot does not sit in his seat (shown above).
Perhaps this is due to the supposed new character animations I have heard mentioned on the forum.

**Comment by Max98** [comment]
I heard around that fixed nodes (fixes section) doesn't work with the new parser for the moment. So it should be the problem.

**Comment by only-a-ptr** [comment]
Thanks for creating this elaborate issue ticket.
I'm already aware fixes aren't working. I'll resolve it soon.
