### ISSUE TITLE
Flares Can be Activated in Pause Menu

### ISSUE THREAD

**Issue by graysonk95** [RigsOfRods/rigs-of-rods#163]
While paused I am able to turn on one more set of flares then I cannot turn them back off until I unpause.
This only works with one set of flares at a time.
Once you activate one set while paused, you cannot activate others, nor turn off others.

This does not impact gameplay any, it is just a small glitch with the pause menu.

**Comment by Max98** [comment]
Can you tell us which vehicle did you use?

**Comment by graysonk95** [comment]
This works on any vehicle with 'u'-type user-defined flares.
I have tested at least a dozen vehicles and it does it with all of them.

**Comment by only-a-ptr** [comment]
Fixed in my repo
