### ISSUE TITLE
Set up Travis automated build testing

### ISSUE THREAD

**Issue by skybon** [RigsOfRods/rigs-of-rods#164]
This would help us instantly identify broken commits. Travis CI is free for open source projects and has tight integration with GitHub.

**Comment by Hiradur** [comment]
How easy is it to set it up with all these dependencies?

**Comment by skybon** [comment]
Check this one out:
https://github.com/etlegacy/etlegacy/blob/master/.travis.yml
https://github.com/etlegacy/etlegacy/blob/master/easybuild.sh

**Comment by Hiradur** [comment]
I'll have a deeper look at this.

**Comment by Hiradur** [comment]
Alright, I'm almost there. It's very slow because it has to download and install the dependencies every time and only offers "1.5" cores for building. The dependencies can be cached, I'll look into it another time.

**Comment by skybon** [comment]
You could also set up gitter integration, no one uses IRC anyway.

**Comment by Hiradur** [comment]
Integrate it with Travis or what do you mean?

**Comment by skybon** [comment]
Exactly.

**Comment by Hiradur** [comment]
Done.
