### ISSUE TITLE
Sight range bug

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1659]
This happens when sight range was set to 0 (i've thought 0 = unlimited).

![ror_2018_10_16_21_25_52_024](https://user-images.githubusercontent.com/1196375/47042047-9cbb1b00-d18a-11e8-9f45-91f45e658650.jpg)
![ror_2018_10_16_21_25_59_553](https://user-images.githubusercontent.com/1196375/47042048-9cbb1b00-d18a-11e8-98f2-c2553c6b3901.jpg)
![ror_2018_10_16_21_26_04_089](https://user-images.githubusercontent.com/1196375/47042049-9cbb1b00-d18a-11e8-97d5-49f8c99ef400.jpg)

**Comment by ulteq** [comment]
5000 is unlimited
