### ISSUE TITLE
Sound issues

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#166]
In the 0.4 version of Rigs of Rods, only one sound can play at a time. For example, when I put the parking brake on, the engine sounds temporarily turn off, then when the parking brake sound is finished, the engine sound continues. I also have 0.38.67 installed on my computer, but that version does not have any sound issues.

**Comment by Hiradur** [comment]
Can't reproduce on Linux.

**Comment by Max98** [comment]
Same here, never happened to me. Can you show us this page of your configurator?
http://prntscr.com/71v77h

**Comment by tritonas00** [comment]
Also no problem here (linux)

**Comment by gigapouch** [comment]
Never mind, I think I fixed it. I just had to change a sound setting.
