### ISSUE TITLE
Beam sensitivity too high

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#170]
I have noticed that in some vehicles, I can go over a fairly large curb without deforming even one beam. In others, going over that same curb at the same speed causes about 10-20 beams to become deformed. Is there a setting for the sensitivity of beams?

**Comment by Hiradur** [comment]
Please check if it is related to set_beam_defaults: http://www.rigsofrods.com/wiki/pages/Truck_Description_File#Set_beam_defaults

**Comment by gigapouch** [comment]
Ok, I think I know how to fix it now.

**Comment by only-a-ptr** [comment]
@gigapouch : Tuning the strength of beams is entirely a responsibility of the modder.
Tools for tuning the beam parameters will be created as part of Rig Editor - eventually.
