### ISSUE TITLE
Angelscript not working correctly on Linux x86_64

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#174]
Loading this server: cifpo modded ror.ezzg.be:14005 nHelens (http://www.rigsofrods.com/repository/index/Search.keywords:nHelens)

In 0.38.66 looks ok:
http://s10.postimg.org/5tfhzrdop/2015_05_09_120708_1920x1080_scrot.png

Now (latest git), colors are different and missing elements: http://s10.postimg.org/6rvv21r0p/2015_05_09_120802_1920x1080_scrot.png

[RoR.log](https://www.dropbox.com/s/qrld4bk618kf1nq/RoR-multi.log?dl=0)

Also in single player the water is above the map:
http://s10.postimg.org/tj4xogc21/2015_05_09_120906_1920x1080_scrot.png

[RoR.log](https://www.dropbox.com/s/7bg243fquco8gwj/RoR-single.log?dl=0)

Disabling waves fixes the issue. (Thanks Skybon)

**Comment by Max98** [comment]
The coloring problem is just a conversion mistake. So it's not our fault. But for me, going on the same server, all the objects load. The only problem I see is the water about the ground with enabled waves. I'll take a look at your logs.

**Comment by tritonas00** [comment]
> But for me, going on the same server, all the objects load.

In Windows?

**Comment by Max98** [comment]
Yup, so it can be a problem from AngelScript.

**Comment by tritonas00** [comment]
> Yup, so it can be a problem from AngelScript.

Is there anyway to debug this? Its a bit annoying :P

Also this map has two spawn places, and because the one isnt loading it spawn me in the other...

**Comment by tritonas00** [comment]
Maybe those angelscript logs are usefull

0.38.66
http://pastebin.com/epcwnyVX

latest git
http://pastebin.com/6SCjQvWA

**Comment by Hiradur** [comment]
Which AngelScript version do you use?

**Comment by tritonas00** [comment]
I use 2.20.3 in 0.38.66 and 2.22.1 in git

**Comment by tritonas00** [comment]
Ok i have more problems on this map in multiplayer

Sometimes the game logins fine but sometimes (most) simply crashes.

gdb:

    Program received signal SIGSEGV, Segmentation fault.
    #0  0x00007ffff7490959 in Ogre::SceneNode::setVisible(bool, bool) () from /opt/ror-next/lib/libOgreMain.so.1.8.1

dmesg:

    [ 5290.015378] RoR[5585]: segfault at 100 ip 00007f1b87680959 sp 00007ffd9dd7b940 error 4 in  libOgreMain.so.1.8.1[7f1b872ac000+5d7000]
    [ 7901.437099] traps: RoR[5332] general protection ip:7f480f9a8959 sp:7fff4284cc50 error:0 in libOgreMain.so.1.8.1[7f480f5d4000+5d7000]

Doesn't happen in 0.38.66. 

Maybe some vehicles from other players that are not compatible?

**Comment by tritonas00** [comment]
Ok, this issue is only shows in x86_64. In i686 all objects load fine:

http://s4.postimg.org/t60n4qrj1/2015_07_03_143715_1920x1080_scrot.png

I had a similar issue back then: http://www.rigsofrods.com/threads/108001-segfault-on-x86_64-and-network-(linux)

**Comment by tritonas00** [comment]
Maybe this is similar? http://www.gamedev.net/topic/620981-port-on-mac-os-and-ipad-problems-and-question/

**Comment by Hiradur** [comment]
Perhaps we should try to upgrade Angelscript first. There are some fixes for platform specific problems and compiler flags:
http://www.angelcode.com/angelscript/changes.php

**Comment by tritonas00** [comment]
Yeap, judging by the errors in log, this should be the fix:

> Added supported for native calling conventions on Linux and Android with MIPS

**Comment by Hiradur** [comment]
I fixed the waves in my repo, PR soon.

**Comment by tritonas00** [comment]
> Ok i have more problems on this map in multiplayer

> Sometimes the game logins fine but sometimes (most) simply crashes.

Ok this is due to some probably incompatible vehicles from other players. Loading only the map, without any vehicle, loads fine every time.

**Comment by Hiradur** [comment]
I always play with ```ulimit -c unlimited``` set so if a crash happens I can immediately take a look at it with gdb.

**Comment by tritonas00** [comment]
Also dmesg says:

    RoR[18842] general protection ip:7f779e4cfb99 sp:7ffca9ef11d0 error:0 in libOgreMain.so.1.8.1[7f779e110000+5bd000]

**Comment by tritonas00** [comment]
Also i have the same packs folders (symlink) with 00.38.66 and next-stable and probably some incompatible vehicles.

I will try with 0.4 content pack only.

**Comment by Hiradur** [comment]
@tritonas00 It would be great if you could make a new issue for that after you verified it's not a 0.38/0.4 compatibility problem.

**Comment by Speciesx** [comment]
Here is an updated Version of this terrain. I've changed the detail textures and disabled the contained Caelum file.

![Uploading RoR_2015_07_19_12_23_45_786.png…]()

https://www.dropbox.com/s/nnf1jm20yg1h5au/nhelens.zip?dl=0

**Comment by tritonas00** [comment]
wow thanks @Speciesx 

@Hiradur if i load with only the terrain it never crashes. Also, with content pack, it crashes after some player spawns a vehicle that i have it. If i dont have it, its ok. Many users use 0.38 in multiplayer.

**Comment by tritonas00** [comment]
for example, now i downloaded 0.4 Content Pack, and crashed after some user loaded some container (saw it in chat). Retried 2-3 times still crashed because of that. I removed ISOcontainers.zip and no crashes still now.

**Comment by Max98** [comment]
@tritonas00 The current Upstream does crash in multiplayer when something gets spawned.
It's also angelscript related, and I'm working on it.

**Comment by Hiradur** [comment]
@tritonas00 If you feel desperate you could check up to which version of AngelScript RoR compiles without modifying the code.

**Comment by tritonas00** [comment]
@Hiradur already tried that :P

If i remember correctly it fails with everything above 2.22.*

**Comment by Hiradur** [comment]
quote from only_a_ptr:
```
The AngelScript in RoR-Deps-26 [Windows] is slightly hacked. We need to download clean SRC of corresponding AngelScript version and DIFF it to see what's changed.

    The script loading (CScriptLoader IIRC) interface is modified to allow subclassing + using OGRE resource system; specifically, one function is changed to "virtual" directly in AS headers.

    One more hack I've seen involves a macro with 1 assembly instruction - I'm unable to remember where exactly this was.
```

**Comment by Hiradur** [comment]
AS update is also needed because RoR doesn't link against 2.22.1 on ARMv7

**Comment by only-a-ptr** [comment]
One are known to have platform-dependent issues is function calling-conventions: http://www.angelcode.com/angelscript/sdk/docs/manual/doc_generic.html

**Comment by Hiradur** [comment]
@only-a-ptr Yep, Angelscript.log is full of errors like this one:
```
19:48:58:  (0, 0): Error = Don't support returning type 'vector3' by value from application in native calling convention on this platform
```

There is a way to hack around them but instead we should just upgrade AS, it now even has native calling convetions on MIPS...

**Comment by only-a-ptr** [comment]
@Hiradur :+1: for doing this daunting job.

**Comment by Bob-Z** [comment]
my 2 cents: I have the multi-player crash on my x86_64 bits machine too. The crash happens in Beam::setCustomLightVisible on the client which has NOT spawned the vehicle.
netCustomLightArray[number] seems to be always set to -1 for some vehicles, which leads to the crash at this line:

if (flares[netCustomLightArray[number]].snode)

A quick workaround is as follow:

```
diff --git a/source/main/physics/Beam.cpp b/source/main/physics/Beam.cpp
index 5be63dd..46bceac 100644
--- a/source/main/physics/Beam.cpp
+++ b/source/main/physics/Beam.cpp
@@ -6742,6 +6742,11 @@ void Beam::setCustomLightVisible(int number, bool visible)
                return;
        }
 
+       if (netCustomLightArray[number] == -1)
+       {
+               return;
+       }
+
        try
        {
                if (flares[netCustomLightArray[number]].snode)
```

With this code, I have no crash anymore but some vehicles are sometimes spawned with abnormal meshes:

![screenshot_1](https://cloud.githubusercontent.com/assets/5794246/11998268/ea04e206-aa96-11e5-9c92-4033b7f93575.png)

I will test Hiradur AS update as soon as it will be available, thanks Hiradur.

**Comment by DirtGamer301** [comment]
The vehicles spawning with weird wheels are a multiplayer problem I think. It might be caused by flexbodywheels, but I'm not sure.
I remember in various MP sessions, for example with TJ Sammy this always happaned.

**Comment by Dogy144** [comment]
The flextires issue can be found here: https://github.com/RigsOfRods/rigs-of-rods/issues/253

**Comment by tritonas00** [comment]
@Bob-Z are you talking about https://github.com/RigsOfRods/rigs-of-rods/issues/459 ?

**Comment by Bob-Z** [comment]
@tritonas00 Oups yes it is #459. I didn't see it, sorry.
@Dogy144 Thanks, I will take more time reading existing bugs before reporting next time.
