### ISSUE TITLE
Crash when spawning some vehicule

### ISSUE THREAD

**Issue by Bob-Z** [RigsOfRods/rigs-of-rods#175]
I have the following crash when trying to run RoR with the "1949 Ford" on "simple test terrain" map:

```
....
Texture: littlelights.png: Loading 1 faces(PF_A8R8G8B8,512x128x1) Internal format is PF_A8R8G8B8,512x128x1.
Texture: ign-off.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) Internal format is PF_A8R8G8B8,64x64x1.
Texture: batt-off.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) Internal format is PF_A8R8G8B8,64x64x1.
Texture: lopress-off.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) Internal format is PF_A8R8G8B8,64x64x1.
Texture: clutch-off.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) Internal format is PF_A8R8G8B8,64x64x1.
Texture: secured-off.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) Internal format is PF_A8R8G8B8,64x64x1.
Texture: locked-0.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) Internal format is PF_A8R8G8B8,64x64x1.
Texture: lights-off.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) Internal format is PF_A8R8G8B8,64x64x1.
Texture: pbrake-off.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) Internal format is PF_A8R8G8B8,64x64x1.
Texture: anglo_v.png: Loading 1 faces(PF_A8R8G8B8,200x180x1) Internal format is PF_A8R8G8B8,200x180x1.
Texture: anglo_h.png: Loading 1 faces(PF_A8R8G8B8,200x180x1) Internal format is PF_A8R8G8B8,200x180x1.
 ===== DONE LOADING VEHICLE
StaticText factory is deprecated, use TextBox [MapEntity.layout]
StaticText skin is deprecated, use TextBox [MapEntity.layout]
StaticText skin is deprecated, use TextBox [MapEntity.layout]
Widget property 'Text_TextAlign' have type prefix - use 'TextAlign' instead [MapEntity.layout]
Widget property 'Text_FontHeight' have type prefix - use 'FontHeight' instead [MapEntity.layout]
StaticImage factory is deprecated, use ImageBox [MapEntity.layout]
static map icon not found: icon_truck.dds
Texture 'icon_truck_sleeping.dds' not found
Texture 'icon_truck_deactivated.dds' not found
EFL: beam instanciated
initTrucks done
radeon: Failed to allocate a buffer:
radeon:    size      : 452906064 bytes
radeon:    alignment : 4096 bytes
radeon:    domains   : 2
radeon:    flags     : 4
radeon: Failed to allocate a buffer:
radeon:    size      : 452906064 bytes
radeon:    alignment : 4096 bytes
radeon:    domains   : 2
radeon:    flags     : 4
radeon: Failed to allocate a buffer:
radeon:    size      : 452906064 bytes
radeon:    alignment : 4096 bytes
radeon:    domains   : 2
radeon:    flags     : 4
radeon: Failed to allocate a buffer:
radeon:    size      : 452906064 bytes
radeon:    alignment : 4096 bytes
radeon:    domains   : 2
radeon:    flags     : 4


An exception has occured!: OGRE EXCEPTION(7:InternalErrorException): Vertex Buffer: Out of memory in GLHardwareVertexBuffer::lock at /home/bobz/ror-deps/ogre/RenderSystems/GL/src/OgreGLHardwareVertexBuffer.cpp (line 125) / url: http://wiki.rigsofrods.com/index.php?title=Error_7#GLHardwareVertexBuffer::lock



An exception has occured!: OGRE EXCEPTION(7:InternalErrorException): Vertex Buffer: Out of memory in GLHardwareVertexBuffer::lock at /home/bobz/ror-deps/ogre/RenderSystems/GL/src/OgreGLHardwareVertexBuffer.cpp (line 125) / url: http://wiki.rigsofrods.com/index.php?title=Error_7#GLHardwareVertexBuffer::lock

AL lib: (EE) alc_cleanup: 1 device not closed
```

I took a look at the URL at the end of the log but that doesn't ring a bell.

This does not happen with all vehicules. FWIW I have the feeling it happens only with vehicules using flexbody.

I am running RoR on Ubuntu 14.10 with radeon driver on a Radeon HD 4870 graphic card with 256 Mb of video RAM.

This issue does not happen on revision 9505914a7e8ca1f2f2ff349c1522dadfd2305513.
The following revision ( 43fd0e2dfbea5c1aaf5988f66f0c0b5d9113e537 ) break the linux compilation.
The next compiling revision is 11e5e1d1f7d0e46cad4f4bca998dc445438aff17, and the issue happens on this revision.

So the regression came between 9505914a7e8ca1f2f2ff349c1522dadfd2305513 and 11e5e1d1f7d0e46cad4f4bca998dc445438aff17.

**Comment by Max98** [comment]
Can you just go ingame, press ctrl+f and take a screenshot?

What I don't get is that, the log says that your GPU doesn't have enough vRam anymore, while all the edits done have nothing to do with the graphic part of the game.

Also, can you try again using a lower resolution ? (E.g: 800x600)

**Comment by Hiradur** [comment]
Are you sure this is not a problem with the free AMD driver? Does your card really only have 256mb of VRAM?

**Comment by Bob-Z** [comment]
I tried 800x600 and also disabling all the graphics feature but the result is the same.

The screenshot for rev 9505914 (working one):
![ror_9505914](https://cloud.githubusercontent.com/assets/5794246/7635482/923d102e-fa61-11e4-8285-78e9d90a46ea.png)

And for rev 11e5e1d (crashing one):
![ror_11e5e1d](https://cloud.githubusercontent.com/assets/5794246/7635513/b89b18ec-fa61-11e4-88c3-3c8895822f1d.png)

And in case this could be useful the screenshot with working version with the car loaded:
![ror_9505914_2](https://cloud.githubusercontent.com/assets/5794246/7635527/cd546a18-fa61-11e4-8080-6e23a71a40eb.png)

The proprietary driver does not support my graphics card anymore. 

the "lshw" command seems to indicate that the card has 256 Mb. I can't say if it is the real hardware size.
```
                description: VGA compatible controller
                product: RV770 [Radeon HD 4870]
                vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                physical id: 0
                bus info: pci@0000:01:00.0
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
                configuration: driver=radeon latency=0
                resources: irq:51 memory:e0000000-efffffff memory:f7c20000-f7c2ffff ioport:e000(size=256) memory:f7c00000-f7c1ffff
```

**Comment by Hiradur** [comment]
My card also shows 256MB with the free driver with lshw. But I know for a fact that my HD7770 has 1GB. 256MB seems to be a little low for an HD4870, considering it's been a high-end card once.

Anyway, I think @only-a-ptr has to take a look at it.

**Comment by Max98** [comment]
I've seen only 512MB or 1GB versions of the HD4870, none with 256MB.
I'm wondering if this might can be the solution to the https://github.com/RigsOfRods/rigs-of-rods/issues/28 issue.
Maybe the way flexbodys are calculated causes all these problems.

**Comment by Hiradur** [comment]
"sudo dmesg | grep drm" says:
[   14.355743] [drm] radeon: 1024M of VRAM memory ready
[   14.355744] [drm] radeon: 1024M of GTT memory ready.

So lshw is showing a wrong value. Some searching revealed that this is not uncommon.

**Comment by Bob-Z** [comment]
Indeed dmesg reports 512 Mb VRAM:

```
[    1.823975] [drm] Detected VRAM RAM=512M, BAR=256M
[    1.823976] [drm] RAM width 256bits DDR
[    1.824095] [drm] radeon: 512M of VRAM memory ready
[    1.824096] [drm] radeon: 1024M of GTT memory ready.
```

Maybe the 256M limits reported by "lshw" is related to the 'BAR' value, which seems, after a short googling, to be the VRAM directly addessable by CPU.

Anyway I have the feeling that it is not related to the driver since it works or not from a commit to another commit with the same driver.

On the other hand, the multiple flexbodies generation seems pretty promising !

**Comment by Bob-Z** [comment]
I have just updated my system to Ubuntu 15.04, rebuilt all dependancies and RoR itself, and the crash is gone !

I suppose this was indeed related to some kind of GPU driver bug triggered by latest commits.

Thanks for your help.
