### ISSUE TITLE
Upgrade resources for OGRE 1.11

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#1761]
- [x] Update OGRE overlays: #2007
- [x] Upgrade all meshes: #1762
- [ ] Check materials for syntax errors

**Comment by tritonas00** [comment]
correcting material syntax warnings results in segfault so i don't think we can do more here

**Comment by only-a-ptr** [comment]
> correcting materials syntax warnings results in segfault
🤣 

Give me the changes, I'll try in debug build.

**Comment by tritonas00** [comment]
So we get
```
21:18:34: Warning: ScriptCompiler - deprecated symbol in texture_manager.material(16): 'cubic_texture ..'. Use 'texture .. cubic' instead.
```

go to
https://github.com/RigsOfRods/rigs-of-rods/blob/master/resources/managed_materials/texture/texture_manager.material#L16
and
https://github.com/RigsOfRods/rigs-of-rods/blob/master/resources/managed_materials/texture/texture_manager.material#L42
and do what it says
```
texture EnvironmentTexture combinedUVW cubic
```

load a terrain-> epic segfault
