### ISSUE TITLE
"Remove current vehicle" crashes game

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#179]
When I would like to remove a vehicle, the program does not know what to do so it crashes. I think that RoRBot should spawn just outside the vehicle BEFORE the vehicle gets removed. I am using 0.38.67.

**Comment by Max98** [comment]
>  I am using 0.38.67.
Please download the last version before reporting a bug.
http://www.rigsofrods.com/threads/119110-Test-Build-Rigs-of-rods-0-4-5-0-dev

**Comment by Hiradur** [comment]
This has been fixed and was caused by a bug in the sound system.
