### ISSUE TITLE
Caleum is broken on linux

### ISSUE THREAD

**Issue by vido89** [RigsOfRods/rigs-of-rods#1832]
Im using ubuntu 16.04 and Rigs of Rods version: 0.4.8.0-dev-3f276e2 with caleum as sky. Im on latest dev build and here is how NeoQueretaro looks like 
![caleum2](https://user-images.githubusercontent.com/3700226/49150183-638ad480-f30c-11e8-8717-ff9009c2f0c4.png)

**Comment by only-a-ptr** [comment]
RoR.log 🙏

**Comment by tritonas00** [comment]
you need to fix your plugins.cfg entry

**Comment by vido89** [comment]
Here is currnet plugins.cfg 
```
$ cat plugins.cfg 
# Defines plugins to load

# Define plugin folder
PluginFolder=/home/slobodan/rigs-of-rods/bin/

# Define plugins
Plugin=Codec_FreeImage
Plugin=RenderSystem_GL
Plugin=Plugin_ParticleFX
Plugin=Plugin_OctreeSceneManager
Plugin=Plugin_CgProgramManager
Plugin=/home/slobodan/rigs-of-rods/redist/lib/libCaelum.so
```
Originaly was 

`Plugin=libCaelum.so`

[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/2624429/RoR.log)

**Comment by tritonas00** [comment]
`/home/slobodan/rigs-of-rods/redist/lib/libCaelum.so` exists?

**Comment by only-a-ptr** [comment]
`Plugin=/home/slobodan/rigs-of-rods/redist/lib/libCaelum.so` ain't going to work, you need
```
# Define plugin folder
PluginFolder=/home/slobodan/rigs-of-rods/redist/lib/
Plugin=libCaelum.so
```

**Comment by tritonas00** [comment]
oops yes, my text editor has a bug...

**Comment by vido89** [comment]
> `/home/slobodan/rigs-of-rods/redist/lib/libCaelum.so` exists?

Yes it does

> your RoR.log is incomplete, as mine.

Will log from terminal be any help

> @only-a-ptr my RoR.log also stops at `FBO PF_UNKNOWN depth/stencil support: D` can you take a look?

@only-a-ptr 

```
$ cat rigs-of-rods/bin/plugins.cfg 
# Defines plugins to load

# Define plugin folder
PluginFolder=/home/slobodan/rigs-of-rods/bin/

# Define plugins
Plugin=Codec_FreeImage
Plugin=RenderSystem_GL
Plugin=Plugin_ParticleFX
Plugin=Plugin_OctreeSceneManager
Plugin=Plugin_CgProgramManager
Plugin=libCaelum.so
```

**Comment by tritonas00** [comment]
try `Plugin=../libCaelum.so`

**Comment by vido89** [comment]
> try `Plugin=../libCaelum.so`

nope same thing

**Comment by only-a-ptr** [comment]
🤦‍♂️ `Plugin=` doesn't accept paths, neither absolute nor relative, that's what `PluginFolder` is for.

@vido89 If `/home/slobodan/rigs-of-rods/redist/lib/libCaelum.so` exists, then you need to add this to "plugins.cfg"
```
PluginFolder=/home/slobodan/rigs-of-rods/redist/lib/
Plugin=libCaelum.so
```
Period. Try that and post RoR.log

**Comment by tritonas00** [comment]
`../libCaelum.so` works on linux with ror-dependencies

**Comment by vido89** [comment]
@only-a-ptr Yup that works
