### ISSUE TITLE
Phast Phantom rear wheels spawn broken

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1837]
As the title says, spawn [Phast_Phantom.zip](https://github.com/RigsOfRods/rigs-of-rods/files/2626359/Phast_Phantom.zip)

![pha](https://user-images.githubusercontent.com/2660424/49293363-9ffb3380-f4b8-11e8-998a-f645614e696e.png)

**Comment by only-a-ptr** [comment]
🙏 RoR.log

**Comment by tritonas00** [comment]
Sorry i forgot: [RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/2628823/RoR.log)

**Comment by ulteq** [comment]
Three physics frames into the simulation:

![shocks](https://user-images.githubusercontent.com/9437207/50740744-527a9080-11f3-11e9-9bd7-42e378a8ccb2.jpg)

**Comment by tritonas00** [comment]
mod issue
