### ISSUE TITLE
Message "Screenshot taken" only showing up occasionally

### ISSUE THREAD

**Issue by tgp1994** [RigsOfRods/rigs-of-rods#184]
> When taking a screenshot, it doesn't say so anymore in the "notification area" (bottom left side of the screen) - other notifications (eg "free camera") still shows up, though. I always found it it nice to know if a screenshot was taken, especially in low-FPS-situations when it (for me at least) didn't always take the screenshot on the first try.

*Bug was moved from the wiki tracker. [Original post](http://www.rigsofrods.com/threads/105734-Version-0-4-0-7?p=1200484&viewfull=1#post1200484)*

**Comment by Max98** [comment]
This is also fixed in 0.4.5
