### ISSUE TITLE
Compatibility with terrains with missing otc file

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1841]
Try to load a terrain with missing otc file:
```
[RoR|Terrain] Error reading main *.otc file, message: 'FileNotFoundException: Cannot locate resource Houston2013.otc in resource group General. in ResourceGroupManager::openResource at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreResourceGroupManager.cpp (line 698)', type: <Ogre::Exception>.
```
Example terrain: http://www.mediafire.com/file/nn36bdj9bo99khv/Traxxas_Stadium_Freestle_4.zip/file

It would be nice if this will work again, like older RoR versions (pre 0.4.7)

**Comment by only-a-ptr** [comment]
We already had this issue, I thought I fixed it...

**Comment by tritonas00** [comment]
Nope, and it probably affects a lot (if all) sim monsters terrains

**Comment by ulteq** [comment]
None of these maps work with our current code: http://sim-monsters.com/files/

**Comment by only-a-ptr** [comment]
Allright, but in this "Traxxas Stadium" map specifically, the OTC file is not missing, it's just named .cfg. That's not a bug 😆

**Comment by ulteq** [comment]
> That's not a bug

If 200 maps work in 0.4.6, but don't work in 0.4.8 then it is a bug. No matter how fucked up the old code was.

**Comment by only-a-ptr** [comment]
Very good point. Look, I don't mean to break old content just because it's a mess, I just don't want to mix actual backwards compatibility with tolerance to whatever glitch appears in the content.

In this case, specifically, the terrn2 file says `GeometryConfig = Houston2013.otc` but the fie is really "Houston2013.cfg", which is apparently a conversion mistake (old terrn format used .cfg here IIRC)

**Comment by tritonas00** [comment]
so renaming `Houston2013.cfg` to `Houston2013.otc` should work?

**Comment by only-a-ptr** [comment]
@tritonas00 Absolutely

**Comment by tritonas00** [comment]
It doesn't:
`[RoR|Terrain] Error reading page config *.otc file, message: 'FileNotFoundException: Cannot locate resource Houston2013-page-0-0.otc in resource group General. in ResourceGroupManager::openResource at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreResourceGroupManager.cpp (line 698)', type: <Ogre::Exception>.
[RoR|Terrain] Empty Heightmap provided in OTC, please use 'Flat=1' instead`

Instead creating just an empty file `Houston2013.otc` works:
![otc](https://user-images.githubusercontent.com/2660424/49246146-dbe0bb00-f41c-11e8-8b49-8f9da56bc482.png)

**Comment by ulteq** [comment]
> I just don't want to mix actual backwards compatibility with tolerance to whatever glitch appears in the content.

I agree, but not having an `.otc` file seems to be a very common glitch.

> [* Disabling the terrain geometry altogether is not supported, I may change that in the future.](https://github.com/RigsOfRods/rigs-of-rods/commit/2bcd89e6ea6ed07f2521596986030a798f42ad19)

I think it's time to change that.

**Comment by only-a-ptr** [comment]
OK, let's see - this TraxxasStadium terrain is broken, filename is wrong. We have 2 ways of dealing with it:
1. Report error and refuse to load a broken terrain. Makes sense to me. Users want to know they're using broken stuff and request it be fixed.
2. Load the terrain anyway, likely wrong. Makes no sense to me - then RoR will appear broken and we'll be requested to "fix" it further.

**Comment by tritonas00** [comment]
We already do 1. The problem is its just not only one map, we talk about all sim monsters content here...
And they have a lot of maps

It worked before (they say in their forum) so it should work on tge latest ror version

2 would be the best solution: load the map as written by its author and tell him to fix asap

or if you dont want people to upgrade to 0.4.8 leave it as is (1)

**Comment by only-a-ptr** [comment]
OK then, let's see:

The old parser simply ignored failure to load .otc file: https://github.com/RigsOfRods/rigs-of-rods/blob/2d8546df3f1196fb7f7093ea79a557d70e1af279/source/main/terrain/TerrainGeometryManager.cpp#L196, leaving `m_terrain_config` empty. Then it read values from there, using defaults if not specified: https://github.com/RigsOfRods/rigs-of-rods/blob/2d8546df3f1196fb7f7093ea79a557d70e1af279/source/main/terrain/TerrainGeometryManager.cpp#L262

@ulteq It'll be faster if you patch this... just fill in the defaults if reading the .otc fails here: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/terrain/TerrainGeometryManager.cpp#L288. Alternatively you can put them directly to the class: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/terrain/TerrainGeometryManager.cpp#L288

**Comment by ulteq** [comment]
I tried that yesterday, but it didn't work for some reason.
