### ISSUE TITLE
Skidmarks are broken

### ISSUE THREAD

**Issue by tgp1994** [RigsOfRods/rigs-of-rods#185]
> Not totally sure if you know about this, but that error annoys the heck out of me in mp, and it spams my server like heck if it goes long enough.
![Example 1](http://www.rigsofrods.com/attachment.php?attachmentid=410443&d=1372805816)
> Skidmarks sometimes completely cut out in .4.0.7, as well as they don't have a texture/material assigned to them.
![Example 2](http://www.rigsofrods.com/attachment.php?attachmentid=410444&d=1372806008)
> When they do work, they do skip a lot more than in .4.0.4.

**0.4.0.4**
![](http://www.rigsofrods.com/attachment.php?attachmentid=410446&d=1372806066)

**0.4.0.7**
![](http://www.rigsofrods.com/attachment.php?attachmentid=410445&d=1372806049)

*Bug was moved from the wiki tracker. [Original post.](http://www.rigsofrods.com/threads/105734-Version-0-4-0-7?p=1207981&viewfull=1#post1207981)*

**Comment by Max98** [comment]
Skidmarks are working fine on 0.4.5.
