### ISSUE TITLE
Setting collision limit not working

### ISSUE THREAD

**Issue by tgp1994** [RigsOfRods/rigs-of-rods#186]
> I am not sure, but I think raising the [collision limmits](http://www.rigsofrods.com/wiki/pages/Terrn_file_description#Collision_limits) is not working in 0.4.0.7.

*Bug was moved from the wiki tracker. [Original post.](http://www.rigsofrods.com/threads/105734-Version-0-4-0-7?p=1208334&viewfull=1#post1208334)*

**Comment by Max98** [comment]
Will take a look on this one.

**Comment by Max98** [comment]
In the code, it's coded correctly. Can someone give this an other try?

**Comment by Speciesx** [comment]
It works for me, tested on NeoQueretaro.
