### ISSUE TITLE
Mountainside terrain crashes upon loading

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1870]
Load [Mountainside](http://www.austingratzer.com/rigs/downloads.php?do=file&id=44&act=down&actionhash=guest):

```
RuntimeAssertionException: resource name must not be empty in createResource at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreResourceManager.cpp (line 50)
```

**Comment by only-a-ptr** [comment]
I found the problem: empty texture names supplied to `Ogre::Terrain`
![image](https://user-images.githubusercontent.com/491088/49801438-7d83d880-fd4a-11e8-8c5d-611e3adf5dcc.png)
Let's see how they got there....
