### ISSUE TITLE
Sounds playing on cache regeneration

### ISSUE THREAD

**Issue by tgp1994** [RigsOfRods/rigs-of-rods#188]
> The problem occurs in relation to the cache. After emptying the cache and starting the game, random sounds will play while the game loads content. Only occurs on first start after emptying the cache.
> **How to reproduce:** Clear the cache in the configurator or by emptying the cache folder. Start the game. Do not hit the "regenerate cache" button.
> **Content needed:** Happens with sound loads on maps, e.g. Desert Trails.

*This was moved from the wiki bugtracker. [Original post.](http://www.rigsofrods.com/threads/111967-Bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1307247&viewfull=1#post1307247)*

**Comment by Max98** [comment]
This is fixed in 0.4.5
