### ISSUE TITLE
snapcraft build

### ISSUE THREAD

**Issue by paroj** [RigsOfRods/rigs-of-rods#1895]
any interest in having a snapcraft build like:
https://github.com/OGRECave/ogre-meshviewer/blob/master/snapcraft.yaml

it has the advantage that ror will be findable in the snap store and run sandboxed. One could even restrict it to its own folder so malicious content downloaded from the web can not do any harm.

**Comment by only-a-ptr** [comment]
Looks very interesting to me. @AnotherFoxGuy What do you think?
