### ISSUE TITLE
Rorconfig Error

### ISSUE THREAD

**Issue by CoelacanthsKill** [RigsOfRods/rigs-of-rods#1896]
After installing the game, I get this error: 

![image](https://user-images.githubusercontent.com/7817229/49906732-b7330d00-fe38-11e8-81fa-5782cdf56a22.png)

18:06:08: can't open file 'X:\DBJGBY~H\DBJGBY~H\Rigs of Rods 0.4\\cache\empty' (error 3: the system cannot find the path specified.)
18:06:08: Can not create file 'X:\DBJGBY~H\DBJGBY~H\Rigs of Rods 0.4\\cache\empty'.

I can dismiss the message and have the RoR 0.4.7.0 configuration window pop up. Simply clicking "Save and Play" without changing settings brings up this error: 

![image](https://user-images.githubusercontent.com/7817229/49906786-f7928b00-fe38-11e8-97cf-964c3fe9193a.png)

Then 

![image](https://user-images.githubusercontent.com/7817229/49906809-109b3c00-fe39-11e8-992c-33fab06b8828.png)

Then 

![image](https://user-images.githubusercontent.com/7817229/49906815-17c24a00-fe39-11e8-9b75-3b3411f95f59.png)

**Comment by only-a-ptr** [comment]
Hello.

You've already reported the same thing here: see: https://github.com/RigsOfRods/rigs-of-rods/issues/1604 

I was thinking about fixing it, but instead we removed RORConfig entirely. In next release, you'll launch RoR directly, it should work fine on network-mapped drive.

RoRconfig in your version cannot run on network-mapped drives, you'll have to run from local drive.
