### ISSUE TITLE
Add batch counter

### ISSUE THREAD

**Issue by Hiradur** [RigsOfRods/rigs-of-rods#19]

**Comment by Max98** [comment]
Done here: https://github.com/Max98/ror_nextstable_gui/commit/7d31b029968a55fe220bfda21ce763a7ea1d6e18

**Comment by Hiradur** [comment]
You should only close issues when they get merged into upstream. You can reference issues in your commit so they will get closed automatically when they get merged.

**Comment by Max98** [comment]
Hmmm, alright, will do so next time.
