### ISSUE TITLE
Ties and beams disappearing dependent on viewing angle

### ISSUE THREAD

**Issue by tgp1994** [RigsOfRods/rigs-of-rods#190]
> Dependent on the viewing angle, ties and beams defined as visible get invisible. The bug seems to occur only on vehicles that use hooks.
**How to reproduce:** Connect the ties to another object and change the view of the external camera.
**Content needed:** Please send me a short PM for test files

*This was moved from the wiki bug tracker. [Original post.](http://www.rigsofrods.com/threads/111967-Improvised-bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1307247&viewfull=1#post1307247)*

**Comment by Max98** [comment]
https://github.com/RigsOfRods/rigs-of-rods/issues/34
