### ISSUE TITLE
Different game Font

### ISSUE THREAD

**Issue by tgp1994** [RigsOfRods/rigs-of-rods#191]
> RoR 0.4.0.7 uses a different font compared to old versions.
**How to reproduce:** Start up RoR 0.4.0.7 and compare to an older version.

*This was moved from the wiki bug tracker. [Original post.](http://www.rigsofrods.com/threads/111967-Bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1307247&viewfull=1#post1307247)*

**Comment by Max98** [comment]
This is indeed fixed in 0.4.5
