### ISSUE TITLE
Hooks with auto-lock not disabling properly by triggers

### ISSUE THREAD

**Issue by tgp1994** [RigsOfRods/rigs-of-rods#192]
> Hooks that use the option "auto-lock" do not disable properly when disabled by a "h"-trigger. They try to connect to other nodes with the correct lockgroup in the time interval defined with the "timer" option. Each time they try to connect they move closer to the node they want to connect to. If a hook is disabled by a "h"-trigger, it should not attempt to lock to it at all.
> **How to reproduce:** Stack two containers with the Reachstacker. Press Shift+F12 to disable the hooks temporarily and move the upper container a bit to the side with the mouse.
> **Content needed:** http://www.rigsofrods.com/repository/view/5294, http://www.rigsofrods.com/repository/view/4251

_This was moved from the wiki bug tracker. [Original post.](http://www.rigsofrods.com/threads/111967-Bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1307247&viewfull=1#post1307247)_

**Comment by only-a-ptr** [comment]
@tgp1994 : Was this working in 0.38?

**Comment by tgp1994** [comment]
I'm sorry @only-a-ptr , I'm afraid I don't know :(. sputnik_1 was the original poster, do you know if he has an account on GitHub and can be flagged down for verification?

**Comment by ulteq** [comment]
> If a hook is disabled by a "h"-trigger, it should not attempt to lock to it at all.

The wiki doesn't really say anything about it: http://docs.rigsofrods.org/vehicle-creation/fileformat-truck/#triggers

It would really help if we knew how 0.38 behaved like.

**Comment by only-a-ptr** [comment]
I researched this and concluded it's not a bug, autolock hooks cannot be released by triggers because they use different "hook group":
* -1: reserved as default
* -2: reserved for autolock
* -3 and lower: user-defined and controlled by triggers - see triggers options 'h' and 'H' and hooks option 'hookgroup'. It's all in the docs.
