### ISSUE TITLE
Incorrect command button assignments in "T"-screen

### ISSUE THREAD

**Issue by gbakeman** [RigsOfRods/rigs-of-rods#193]
> Commands have extension and reduction buttons assigned which can be defined by the mod creator. Those buttons are showed by pressing "T" ingame. This screen is only capable to display direct pairs of "F"-Buttons, e.g. F1 + F2. If a user sets a command to F1 for shortening and F3 for extension, that screen still shows F1 + F2 as it can only display direct pairs.
> **How to reproduce:** Choose a vehicle with commands. Hit "T".
> **Content needed:** Any vehicle that uses commands

_This was moved from the wiki bug tracker. [Original post.](http://www.rigsofrods.com/threads/111967-Improvised-bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1307247&viewfull=1#post1307247)_

**Comment by Hiradur** [comment]
Is this still valid for 0.4.5.0?

**Comment by ulteq** [comment]
Yes, and even worse. The list is incomplete for many trucks.

**Comment by AnimosusTheWolf** [comment]
![image](https://user-images.githubusercontent.com/10286567/79935963-6f9c9800-8413-11ea-9ddf-68aa8fb98f98.png)
![image](https://user-images.githubusercontent.com/10286567/79935968-73c8b580-8413-11ea-87b5-82f63e665fe4.png)

This is still an issue. It should be F5/F9 but it instead shows both pairs. Even though F6 and F10 do nothing.
