### ISSUE TITLE
Crash when loading the community map

### ISSUE THREAD

**Issue by ulteq** [RigsOfRods/rigs-of-rods#1932]
![50279099-6f028480-040e-11e9-92e5-5a2b82ef767c](https://user-images.githubusercontent.com/9437207/50281527-fde3c100-044f-11e9-9ba7-e1b46b96c795.png)

[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/2698626/RoR.log)

**Comment by only-a-ptr** [comment]
Does it happen with OpenGL?
If not, it might be the same problem as https://github.com/RigsOfRods/rigs-of-rods/issues/1878 which requires an OGRE fix https://github.com/OGRECave/ogre/pull/1003

**Comment by ulteq** [comment]
@AnotherFoxGuy how did we fix it?

**Comment by AnotherFoxGuy** [comment]
With the update to OGRE 1.11.5
