### ISSUE TITLE
[Windows] from itch latest build crash

### ISSUE THREAD

**Issue by KinG-InFeT** [RigsOfRods/rigs-of-rods#1935]
Hi all,
i run from itch for windows 10 platform. out this error before select simple terrain
![image](https://user-images.githubusercontent.com/193969/50283446-371f2f80-0456-11e9-9751-7d5c4c553a00.png)

after the game run correctly

**Comment by KinG-InFeT** [comment]
@tritonas00 follow it

**Comment by tritonas00** [comment]
@KinG-InFeT  remove your current rigsofrods profile and run the game to create a new one with missing file
