### ISSUE TITLE
[Windows] return to menu not work

### ISSUE THREAD

**Issue by KinG-InFeT** [RigsOfRods/rigs-of-rods#1936]
Hi all,

after start game (platform windows 10 , build from itch 0.4.8 dev)
into game stage -> press Esc -> select return to menu -> not work
![image](https://user-images.githubusercontent.com/193969/50284067-253e8c00-0458-11e9-978a-7b8ad809a47a.png)

**Comment by Speciesx** [comment]
works for me

**Comment by KinG-InFeT** [comment]
@speciesx win or linux?

**Comment by tritonas00** [comment]
Speciesx is on windows iirc

**Comment by Speciesx** [comment]
Windows

**Comment by KinG-InFeT** [comment]
@tritonas00 yes, nothing happens, it does not crash.

**Comment by ulteq** [comment]
Fixed with: https://github.com/RigsOfRods/rigs-of-rods/commit/1556c2a7d63cd93ff31e169a089ccd2e081bd541
