### ISSUE TITLE
Make .cfg-files optional 

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#1937]
Right now RoR crashes if a cfg isn't found (See #1935)
RoR should fallback to defaults if a cfg isn't found

**Comment by tritonas00** [comment]
>Right now RoR crashes if a cfg isn't found

this not the case anymore, RoR now recreates the file structure if something is missing
https://github.com/RigsOfRods/rigs-of-rods/pull/1994
