### ISSUE TITLE
Sections not working

### ISSUE THREAD

**Issue by tgp1994** [RigsOfRods/rigs-of-rods#194]
> Sections are not working. Choosing another configuration of a vehicle does not work, the default setup is being loaded.
**How to reproduce:** Choose the vehicle that uses sections in the vehicle chooser. Choose a different setup at the bottom and click ok.
**Content needed:** http://www.rigsofrods.com/repository/view/2272

*This was moved from the wiki bug tracker. [Original post.](http://www.rigsofrods.com/threads/111967-Bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1307247&viewfull=1#post1307247)*

**Comment by only-a-ptr** [comment]
Sections are working now.
