### ISSUE TITLE
Obsolete options in configurator

### ISSUE THREAD

**Issue by tgp1994** [RigsOfRods/rigs-of-rods#195]
> The options Direct3D11 Rendering and Hydrax Water System are selectable in the configurator. They should be disabled as they are not working.
**How to reproduce:** Start the configurator.

*This was moved from the wiki bug tracker. [Original post.](http://www.rigsofrods.com/threads/111967-Bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1307247&viewfull=1#post1307247)*

**Comment by Max98** [comment]
Added the "enhancement" tag because you can use the ingame configurator from now on. But I will update the external configurator because we might still need it for few things.

**Comment by Max98** [comment]
Updated RoRConfig.
