### ISSUE TITLE
OpenGL vegetation issues

### ISSUE THREAD

**Issue by tgp1994** [RigsOfRods/rigs-of-rods#196]
> In OpenGL mode vegetation maps are rotated by 180°.
**How to reproduce:** Load a map with vegetation in Direct3D9 and OpenGL mode. Vegetation will appear at wrong places in OpenGL mode.
**Content needed:** http://www.rigsofrods.com/repository/view/5118

*This was moved from the wiki bug tracker. [Original post.](http://www.rigsofrods.com/threads/111967-Bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1307247&viewfull=1#post1307247)*

**Comment by Max98** [comment]
Actually, we already have the fix, as @Hiradur fixed it, but we need to update the dependencies so we can include his fixed, which, I don't believe if it will happen any time soon.

**Comment by Hiradur** [comment]
It actually was bug in Ogre Paged Geometry which is fixed in my repo. It only affects Windows builds of RoR which come with outdated dependencies.

**Comment by Hiradur** [comment]
Should be fixed in 0.4.5.0... if not the Windows devs packed an old version of PagedGeometry.
