### ISSUE TITLE
Missing background images

### ISSUE THREAD

**Issue by tgp1994** [RigsOfRods/rigs-of-rods#198]
> Background images are missing at the terrain loader and while a terrain is being loaded.
**How to reproduce:** Start the game, load a terrain

*This was moved from the wiki bug tracker. [Original post.](http://www.rigsofrods.com/threads/111967-Bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1307247&viewfull=1#post1307247)*

*Side note: I see background images just fine, perhaps this is fixed?*

**Comment by Max98** [comment]
Yes it is.
