### ISSUE TITLE
Truck dashboard HUD appears when player exits vehicle with "cinecam" on

### ISSUE THREAD

**Issue by tgp1994** [RigsOfRods/rigs-of-rods#199]
> Everytime you are using a vehicle with incar camera, and exit the car, the HUD won't disappear. And if you spawn another vehicle there will be two HUD's overlapping.
**How to reproduce:** Spawn a vehicle and exit from it when in dashboard mode.

*This was moved from the wiki bug tracker. [Original post.](http://www.rigsofrods.com/threads/111967-Bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1307339&viewfull=1#post1307339)*

**Comment by tgp1994** [comment]
Note from only_a_ptr:

>Fixed in TruckParser2013 fork, not merged yet

**Comment by Max98** [comment]
Yup, fixed.
