### ISSUE TITLE
Add 'install' target for `make` (so you can run `make install`)

### ISSUE THREAD

**Issue by pkillnine** [RigsOfRods/rigs-of-rods#1991]
It would be good to be able to run `make install` so that it copies `RoR` into `<installation prefix>/bin`, etc. This makes it easier for packaging, and is fairly standard.

**Comment by pkillnine** [comment]
When I compile by hand, `make` doesn't find any `install` target. Also it shouldn't create an Appimage by default, really `appimage` should be a separate target, so you would run `make appimage` and it would create an appimage.

**Comment by tritonas00** [comment]
there is no appimage anymore, i think make install is used for the itch redist now

**Comment by pkillnine** [comment]
oh ok, that's using the ninja build system, I'm using the CMake build system.

**Comment by paroj** [comment]
I am also affected by this, see my comment in #1970. And `BUILD_REDIST_FOLDER` does not cut it as it places everything in CMAKE_BINARY_DIR instead of respecting where I want it via CMAKE_INSTALL_PREFIX.
