### ISSUE TITLE
props and vegetation light bug

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#20]
![ror_2015](https://cloud.githubusercontent.com/assets/1196375/5692387/72106fa4-98f4-11e4-8299-ab28031ba4e7.png)

**Comment by Max98** [comment]
I fixed this bug: http://www.rigsofrods.com/threads/115570-Graphic-Update-SkyX-Hydrax-(New-Sky-Water-System)-Fixed-vegetation-light-problem?p=1345831&viewfull=1#post1345831

It should lying around on my HDD or on my old repo.

**Comment by Speciesx** [comment]
with your fix from here http://sourceforge.net/u/moncef98/RoRHydrax/ci/85530237f2e69d9666757d6c99b6f04e1de9f9e3/tree/source/main/terrain/TerrainObjectManager.cpp?diff=e698266580655ebe7a116fec4b2a59c58ba09eba

![ror_2015_01_17_15_20_42_491](https://cloud.githubusercontent.com/assets/1196375/5789094/7a0883c8-9e5c-11e4-980b-eae2f8057087.png)

**Comment by Max98** [comment]
Fixed here: https://github.com/Max98/ror_nextstable_gui/commit/79bae5a9ab938e8ce8efa0f907e7dac6f9e580bf
