### ISSUE TITLE
Wheels explode when driving into a not solid groundmodel (e.g. snow, sand)

### ISSUE THREAD

**Issue by tgp1994** [RigsOfRods/rigs-of-rods#200]
> Basically when a vehicle, especially a truck goes on a not solid groundmodel, if wheels are under a certain stress, they explode and that makes the truck respawn (most of times. Just depends on the truck/vehicle). I discovered this bug on my map when I added sand.
> ![](http://www.rigsofrods.com/attachment.php?attachmentid=474857&d=1397072139)
> **How to reproduce:** Try to drive a truck on sand at a moderated speed 50/60 Km/h
> **Content needed:** Auriga, try to reproduce the bug in this area. PM me if you can't reproduce.
> ![](http://www.rigsofrods.com/attachment.php?attachmentid=474856&d=1397071985)

_This was moved from the wiki bug tracker. [Original post.](http://www.rigsofrods.com/threads/111967-Improvised-bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1312531&viewfull=1#post1312531)_

**Comment by tgp1994** [comment]
Happy 200th bug!

**Comment by Max98** [comment]
@tgp1994 Can you try this with the latest build?

**Comment by tgp1994** [comment]
I actually have no idea how to load another vehicle on top of one like that... I'll try to figure it out though.

**Comment by DODGEcharger** [comment]
I can confirm that this still happens in TB4, it's not the easiest to recreate. But it happens most often when you enter any non-solid groundmodel at decent speed.

**Comment by only-a-ptr** [comment]
Since I'm planning to overhaul map subsystem including groundmodels after 0.4.5, I'm marking this "Post-NextStable"

**Comment by ulteq** [comment]
This is usually caused by setting the `hydrodynamic friction` in the `ground_model.cfg` way too high.

The default value for sand is `0.0001`: https://github.com/RigsOfRods/rigs-of-rods/blob/master/bin/resources/skeleton/config/ground_models.cfg#L123-L127

Auriga for example uses `0.1` for sand.

**Comment by tritonas00** [comment]
they certainly dont in latest master
