### ISSUE TITLE
RorBot gets a makeover

### ISSUE THREAD

**Issue by tgp1994** [RigsOfRods/rigs-of-rods#201]
> i just got the new character model, but its in 3dsmax format. I heard that the 3dsmax exporters are quite well for ogre, but i never owned 3dsmax so i couldnt test :-/

> so if you get something to work, let me know.

> we payed 50 us dollar for this and we are free to redistribute and modify it.

> What needs to be done:

> * animations (create them in 3dsmax and export)
* or: convert 3dsmax file to blender and animate there

> ideally we could just reuse the existing animations with the model, but im not that used to blender, so idk how. If someone with experience could spend some time on it please?

> We have obtained the right of the author to make it public available, but i would like to ask you only to use it for RoR.

*This was moved from the wiki bug tracker. [Original post.](http://www.rigsofrods.com/threads/61870-new-character-3d-model)*

**Comment by Max98** [comment]
This is the 0.4 RoRbot if you didn't notice. :P 
In 0.4.5, animations are reworked but this subject still needs discussion.

**Comment by tgp1994** [comment]
Oh, no, I did not :P Obviously RorBot needs detailed facial customization with sliders, and hats :P

**Comment by gigapouch** [comment]
I think the 0.4.5 RoRBot looks good enough. Hehe, when I jumped off a building and looked down I saw RoRBot's jaws.
