### ISSUE TITLE
Fusedrags and 4 nodes wings apparently aren't working

### ISSUE THREAD

**Issue by tgp1994** [RigsOfRods/rigs-of-rods#202]
> **How to reproduce:** Try using a plane with 4 nodes wings and a fusedrag, it will fly fine on the 332 revision but won't with only_a_ptr's new truck parser.
Edit: Not really, some planes with 4 nodes wings works, some doesn't. Same for the fusedrag.
Content needed: A plane.
Edit: Send me a PM and i'll send you the plane i made.

*This was moved from the bug tracking forum topic. [Original post.](http://www.rigsofrods.com/threads/111967-Bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1339920&viewfull=1#post1339920)*

**Comment by Max98** [comment]
It's fixed.
