### ISSUE TITLE
Plane speed isn't accurate if you climb high

### ISSUE THREAD

**Issue by tgp1994** [RigsOfRods/rigs-of-rods#203]
> Plane speed isn't accurate if you climb high: When you press "T" and watch the speed, you'll notice that when taking altitude, it will start to differ than the speed showed on the GUI. And the Top speed is also bugged
**How to reproduce:** Take a plane and climb high.
**Content needed:** A plane.

*This was moved from the bug tracking topic. [Original post.](http://www.rigsofrods.com/threads/111967-Bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1339920&viewfull=1#post1339920)*
*Note to max: You said in the topic that you wrote a patch already, I'm not sure if this is merged yet though...*

**Comment by Max98** [comment]
Not fixed yet, will work on it.

**Comment by ulteq** [comment]
That's not a bug. The "T" menu shows the [true airspeed](https://en.wikipedia.org/wiki/True_airspeed) and the GUI overlay shows the [indicated airspeed](https://en.wikipedia.org/wiki/Indicated_airspeed).

![](https://upload.wikimedia.org/wikipedia/commons/a/a3/True_airspeed_indicator-FAA.SVG)
