### ISSUE TITLE
Certain flat faces are unnecessarily bright

### ISSUE THREAD

**Issue by gbakeman** [RigsOfRods/rigs-of-rods#204]
> Certain flat faces are unnecessarily bright in ~0.4.0.4+. It seems as if they are ignoring the environmental lighting. This impacts materialflares (not set to "lighting off") as well as any face that doesn't use a specular texture.
> How to reproduce: Spawn any vehicle with materials that fit this description.
> Content needed: See: [this](http://www.rigsofrods.com/threads/115570-Graphic-Update-SkyX-Hydrax-%28New-Sky-Water-System%29-Fixed-vegetation-light-problem?p=1355632&viewfull=1#post1355632)
> ![](http://www.rigsofrods.com/attachment.php?attachmentid=509772&d=1414260320)

**Comment by CuriousMike56** [comment]
I think this can be closed, link is dead.
