### ISSUE TITLE
Strange aircraft GUI

### ISSUE THREAD

**Issue by TheUnknownGuyFromRoR** [RigsOfRods/rigs-of-rods#205]
I dunno what makes this bug, but replacing aircraft overlays with older ones fixed it.
![screenshot_3](https://cloud.githubusercontent.com/assets/10696803/7777665/11c3a222-00c5-11e5-8a40-b9590bff2a0a.png)

**Comment by Max98** [comment]
I don't remember changing the aircraft's GUIs. Can you post your RoR.log?

**Comment by TheUnknownGuyFromRoR** [comment]
I didn't found any errors or even GUI loadings, sorry, you need to try it for yourself. RoR.log is terribly overflowed with nodes loading, beams loading logs

**Comment by Max98** [comment]
As I said, the GUI overlays weren't changed at all in 0.4.5
And none of us had this in the past, so we'll say that it was because of a bad download or sometihng.

**Comment by TheUnknownGuyFromRoR** [comment]
Seems that something got messed up when I was porting folder to program files, this issue can be closed
