### ISSUE TITLE
Daf Skiploader Ropes no longer work

### ISSUE THREAD

**Issue by RustyMonster** [RigsOfRods/rigs-of-rods#2058]
Would love to see this fixed, trying to update older content to more modern standards.

**Comment by CuriousMike56** [comment]
Vehicle link: http://archives.rigsofrods.net/repo/files/repofiles-3rd-batch/e8941f35fa486db9b12bfccf78f61b0bcd516f90_skiploader.zip

The rope end nodes seem to move to node 0 at spawn, causing them to break.
