### ISSUE TITLE
Crash when using pure n/b constructions

### ISSUE THREAD

**Issue by TheUnknownGuyFromRoR** [RigsOfRods/rigs-of-rods#206]
http://www.rigsofrods.com/wiki/index.php?title=Error_3#D3D9RenderWindow::reset I have this error when using for eg. de havilland vampire/venom http://www.rigsofrods.com/threads/115301-De-Havilland-Vampire-Venom It freezes few times and finally a windows notification says "access of RoR.exe to graphic card is blocked". RoRconfig says that I use intel 4600 card, although I tried to assign RoR to nvidia card earlier.

**Comment by Max98** [comment]
Can you post your RoR.log please? This does not happen for me.

**Comment by Hiradur** [comment]
Related to #175 ?

**Comment by TheUnknownGuyFromRoR** [comment]
20:53:51: D3D9 Device 0x[05DDA640] entered lost state
20:53:51: D3D9 device: 0x[05DDA640] lost. Releasing D3D9 texture: RTTTexture1
20:53:51: Released D3D9 texture: RTTTexture1
20:53:51: D3D9 device: 0x[05DDA640] lost. Releasing D3D9 texture: dashtexture
20:53:51: Released D3D9 texture: dashtexture
20:53:51: D3D9 device: 0x[05DDA640] lost. Releasing D3D9 texture: EnvironmentTexture
20:53:51: Released D3D9 texture: EnvironmentTexture
20:53:51: D3D9 device: 0x[05DDA640] lost. Releasing D3D9 texture: SceneManagerInstance2/compRTT
20:53:51: Released D3D9 texture: SceneManagerInstance2/compRTT
20:53:51: D3D9 device: 0x[05DDA640] lost. Releasing D3D9 texture: MapRttTex1
20:53:51: Released D3D9 texture: MapRttTex1
20:53:51: D3D9 device: 0x[05DDA640] lost. Releasing D3D9 texture: SceneManagerInstance1/compRTT
20:53:51: Released D3D9 texture: SceneManagerInstance1/compRTT
20:53:51: D3D9 device: 0x[05DDA640] lost. Releasing D3D9 texture: MapRttTex2
20:53:51: Released D3D9 texture: MapRttTex2
20:53:51: D3D9 device: 0x[05DDA640] lost. Releasing D3D9 texture: dashtexture
20:53:51: Released D3D9 texture: dashtexture
20:53:51: D3D9 device: 0x[05DDA640] lost. Releasing D3D9 texture: EnvironmentTexture
20:53:51: Released D3D9 texture: EnvironmentTexture
20:53:51: D3D9 Device 0x[05DDA640] entered lost state
20:53:52: !!! Direct3D Device successfully restored.
20:53:52: D3D9 device: 0x[05DDA640] was reset
20:53:56: D3D9 Device 0x[05DDA640] entered lost state
20:53:56: D3D9 device: 0x[05DDA640] lost. Releasing D3D9 texture: RTTTexture1
20:53:56: Released D3D9 texture: RTTTexture1
20:53:57: D3D9 device: 0x[05DDA640] lost. Releasing D3D9 texture: dashtexture
20:53:57: Released D3D9 texture: dashtexture
20:53:57: D3D9 device: 0x[05DDA640] lost. Releasing D3D9 texture: EnvironmentTexture
@hiradur nope

**Comment by Max98** [comment]
Can you reinstall/update your GPU's drivers and try again?

**Comment by Hiradur** [comment]
@TheUnknownGuyFromRoR Are you sure? Which commit is your build based on? Can you please try to spawn a Ford 1949 on simple terrain as in #175

**Comment by TheUnknownGuyFromRoR** [comment]
@Hiradur I use dev test build 2 (with only_a_ptr's capital error fixes), I tried to do what you said, but it didn't gave me this error. Strange thing but, when I tested Vampire on Auriga like I did earier, the game didn't gave me this error

**Comment by TheUnknownGuyFromRoR** [comment]
OK, the problem is in my intergrated graphics card (intel hd 4600)

**Comment by DODGEcharger** [comment]
After testing a wide range of N/B only vehicles with no issue, I think it's safe to say this is not a valid bug.

**Comment by Hiradur** [comment]
I can't reproduce this on an HD3000 as well. This is on Linux with OpenGL though. Perhaps a driver update will help you with this.
