### ISSUE TITLE
Props disappearing when reloading vehicle

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2067]
When you reload a vehicle, all props will disappear.
Before reload:
![screenshot_2019-01-12_19-23-27_1](https://user-images.githubusercontent.com/46073351/51079946-f9ea3e00-169f-11e9-9526-e7c9279201f6.png)
After:
![screenshot_2019-01-12_19-23-42_1](https://user-images.githubusercontent.com/46073351/51079947-feaef200-169f-11e9-9ec9-31f874c3fccb.png)
![screenshot_2019-01-12_19-23-58_1](https://user-images.githubusercontent.com/46073351/51079948-feaef200-169f-11e9-9243-b00667b09c62.png)

**Comment by ulteq** [comment]
Most likely caused by: https://github.com/RigsOfRods/rigs-of-rods/pull/2065

**Comment by ulteq** [comment]
The rim still disappears, but that seems to be a different issue. Probably caused by using sections for the props.
