### ISSUE TITLE
Ignoring flexbodies

### ISSUE THREAD

**Issue by TheUnknownGuyFromRoR** [RigsOfRods/rigs-of-rods#207]
Message: Invalid line, ignoring...
 ERROR  (Section flexbodies)
	Line (5535): forset 62,63,100,103,106,109
	Message: Invalid line, ignoring...
 ERROR  (Section flexbodies)
	Line (5537): 26,32,27 0, 0.5, 0, 0, 0, 0, XBGTspringsR.mesh
	Message: Invalid line, ignoring...
 ERROR  (Section flexbodies)
	Line (5538): forset 46,47,81,83,34,35
	Message: Invalid line, ignoring...
This is what I've had after spawning any of ford falcon cars (only a little piece, game ignored all flexbodies)
http://www.rigsofrods.com/threads/88529-1973-Ford-Falcon-XB-GT-Coupe link to the car.
for some reason, props and wheels were on place.

**Comment by Max98** [comment]
Just put space before each value and give it a try:
> forset 62, 63, 100, 103, 106, 109

**Comment by TheUnknownGuyFromRoR** [comment]
It worked, but the flexbodies on this car worked in earlier versions without mods.

**Comment by Max98** [comment]
For the simple reason that the parser didn't ignore mistakes. ;)
