### ISSUE TITLE
Broken MyGUI scaling

### ISSUE THREAD

**Issue by KinG-InFeT** [RigsOfRods/rigs-of-rods#2097]
Hi,
from itch latest sources (now) i have this bug

![image](https://user-images.githubusercontent.com/193969/51443383-42c97480-1ce8-11e9-9716-d2b797d9e43d.png)

Windows 10

**Comment by EramsorGR** [comment]
I can confirm this issue on Linux too. 

Normal Menu
https://cdn.discordapp.com/attachments/189904947649708032/540863377006657537/unknown.png

Non Normal Menu(s)
https://cdn.discordapp.com/attachments/189904947649708032/540863213710082048/unknown.png
https://cdn.discordapp.com/attachments/189904947649708032/540863577683263488/unknown.png

**Comment by tritonas00** [comment]
@AnotherFoxGuy i suggest do a zip with mygui `07da0620e0d835346452b02b7b1ba7c583429736` for people to test

**Comment by tritonas00** [comment]
@KinG-InFeT try with the latest build https://anotherfoxguy.itch.io/rigs-of-rods
