### ISSUE TITLE
Cannot access rig editor

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#210]
In the 0.4.5 version, clicking on the "Rig Editor" button causes Windows to make an error ding. Could this be because there was no "rig_editor.cfg" file in the skeleton directory?

**Comment by Hiradur** [comment]
> To clarify, RoR 0.4.5 uses directory Documents/Rigs of Rods 0.4
>
> Detailed installation instructions:
> 1. Download RoR 0.4.5.0-dev to your computer. It's a ZIP archive.
> 2. Open the ZIP archive
> 3. In the ZIP, find file /resources/skeleton/config/rig_editor.cfg
> 4. Put rig_editor.cfg to Documents/Rigs of Rods 0.4/config

source: http://www.rigsofrods.com/threads/119110-Test-Build-Rigs-of-rods-0-4-5-0-dev

**Comment by gigapouch** [comment]
Sorry, I thought you meant the rig_editor.cfg in the zip folder within resources.

**Comment by JonnyCrash** [comment]
...
