### ISSUE TITLE
Visual glitch in multiplayer with wheels2

### ISSUE THREAD

**Issue by RustyMonster** [RigsOfRods/rigs-of-rods#2113]
For anyone who remembers the old Flextire MP glitch, it's the same problem.
![text](https://i.imgur.com/cOKCaCZ.png)
Vehicle using wheels2
http://archives.rigsofrods.net/repo/files/repofiles-1st-batch/1747b3b8deb2fed6ee7d50f397e322fa78ee9d66_dakardaf.zip

**Comment by ulteq** [comment]
Which build did you use?

**Comment by CuriousMike56** [comment]
It appears that did indeed fix the bug:
![image](https://user-images.githubusercontent.com/46073351/51638881-937ddf00-1f2d-11e9-93da-d875fd093590.png)
We didn't test it on the latest build, just assumed it was still broken. 😊
