### ISSUE TITLE
Custom steering wheels don't show up

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#214]
If I drive a car in 0.4.5 that doesn't have the stock RoR steering wheel, it doesn't show up.

**Comment by Max98** [comment]
Can you be a bit more precise? I can understand what you mean.

**Comment by gigapouch** [comment]
So some cars, have a different steering wheel, like some of the trucks in Soat_Muldoon's Ford F-series pack. Those don't appear at all, but the "stock" steering wheels on other cars do. See the screenshots here:
http://69.107.87.241/Uploads/11.png
http://69.107.87.241/Uploads/22.png

**Comment by Max98** [comment]
Can you please post RoR.log?

**Comment by gigapouch** [comment]
Here it is: http://69.107.87.241/Uploads/RoR.log

I posted the whole thing, I don't know if there's a specific section you want.

**Comment by only-a-ptr** [comment]
Definitely a parser/spawner issue. I'm onto it.
