### ISSUE TITLE
Game freezes when pressing CTRL+SHIFT+DOWN while backspacing

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2151]
I mentioned this issue on Discord yesterday and apparently only 1 other person was able to reproduce it.

- Activate "repair mode" by holding backspace for 1 second
- Press CTRL+SHIFT+DOWN. The game will completely lock up.

![image](https://user-images.githubusercontent.com/46073351/51864900-fba83880-2312-11e9-8720-09d0de2d8e5b.png)
![image](https://user-images.githubusercontent.com/46073351/51864917-0367dd00-2313-11e9-821c-994130339085.png)
Happens with any vehicle on any terrain. Have been able to reproduce it every time on two different PCs.

**Comment by tritonas00** [comment]
@CuriousMike56 change CTRL to another key and try the new combo. Still happens?

**Comment by CuriousMike56** [comment]
> 
> 
> @CuriousMike56 change CTRL to another key and try the new combo. Still happens?

There are no `input.map` keys relating to the repair mode, so I can't try that. 

However, I did just figure out something related to this:
A map I'm working on was freezing during "initializing overview map subsystem" and I narrowed it down to these two placement lines:
```
64.965584,    -0.054345,   102.364738,     0.000000,    90.500000,    0.000000, load DestructibleBarricade2P.load
64.945145,    -0.061230,   100.022873,     0.000000,    90.500000,    0.000000, load DestructibleBarricade2P.load
```
The Y value is set to a negative value, changing it to `0` fixes it. This has to be what is happening here, the key combo tries to force the vehicle under the terrain.
