### ISSUE TITLE
Dodge Magnum bugs

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#216]
In NextStable, Ashes48' Dodge Magnum misses some textures, deforms randomly when repairing (sometimes more, sometimes less), It happens with all cars from this pack, the n/b is from Gavril Zeta.
Also, the outside camera is replaced, as I also noticed in another vehicle.

Pictures:
http://www.rigsofrods.com/attachment.php?attachmentid=534612&d=1433072294
http://www.rigsofrods.com/attachment.php?attachmentid=534613&d=1433072300
http://www.rigsofrods.com/attachment.php?attachmentid=534614&d=1433072307
http://www.rigsofrods.com/attachment.php?attachmentid=534615&d=1433072314
http://www.rigsofrods.com/attachment.php?attachmentid=534616&d=1433072320
http://www.rigsofrods.com/attachment.php?attachmentid=534617&d=1433072326

RoR.log:
www.rigsofrods.com/attachment.php?attachmentid=534600&d=1433064438

**Comment by only-a-ptr** [comment]
Problem is obvious from RoR.log: Syntax flaws in the truckfile. Real numbers where decimals should be. Negative numbers where only 1/0 should have been. Special characters in material names - this is what causes the texture failures. The parser is being too strict and rejects all of these.

Solution: I'll loosen the parser rules to accept these things.

**Comment by DirtGamer301** [comment]
Update/edit:

As also with Irisbus Magelys problems will appear ingame (https://github.com/RigsOfRods/rigs-of-rods/issues/241), Thomas school buses from Voulk have some (Aivar mentioned fusedrag problems, but this might only be one bug of the vehicle in NextStable) and I just tried installing Renault FR1 GTX for testing purposes wich made RoR crash in the cache regeneration time (while loading this bus) and all of those vehicles use sectionconfigs, might they make bugs like this?

**Comment by only-a-ptr** [comment]
@DirtGamer301 : The problems are usually creative syntax flaws in truckfiles. For example, the Magelys bus had real numbers like "123." which is absolutely not a valid format, but the old parser swallowed this, so I must also. Sectionconfigs are unlikely to cause trouble.

**Comment by only-a-ptr** [comment]
All working now.
