### ISSUE TITLE
My custom sounds don't work

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#217]
For fun this afternoon, I recorded the engine startup and engine idle sounds of my dad's 2004 Toyota Corolla CE. However, when I rename them to default_car_idle.wav (after converting them to wav) and default_starter_start.wav for use in Rigs of Rods, I don't hear anything. This issue exists in both 0.38.67 and Test Build 2 of 0.4.5. Here are the sounds:

http://69.107.87.241/Uploads/default_starter_start.wav
http://69.107.87.241/Uploads/default_car_idle.wav

Here's my RoR.log:

http://69.107.87.241/Uploads/soundissue/RoR.log

**Comment by Max98** [comment]
Did you convert them to mono?
Also for your information, TestBuild 2 is outdated.

**Comment by Hiradur** [comment]
They are mono. Where do you put them?

**Comment by Max98** [comment]
@Hiradur 
The logs says that the wave files are invalid:
> 15:29:43: Loading WAV file default_car_idle.wav
15:29:43: Invalid WAV file (no data/fact): default_car_idle.wav
15:29:43: SoundScriptInstance: instance created: defaults.soundscript-1-13
15:29:43: Loading WAV file default_starter_start.wav
15:29:43: Invalid WAV file (no data/fact): default_starter_start.wav

**Comment by gigapouch** [comment]
That's odd, because I could hear them with Windows Media Player. And no, they don't work in Test Build 3 either.

**Comment by Max98** [comment]
What were the settings you used when converting to wave?

**Comment by gigapouch** [comment]
I don't know if this affects anything, but somewhere in the process of converting the wav it was changed from 1536kbps bitrate to 768. Otherwise, I'm pretty sure the sample rate was 48000 Hz and I'm sure it is mono.

**Comment by Max98** [comment]
Can you try with 44100 Hz?

**Comment by gigapouch** [comment]
OK, I'll do that.

**Comment by gigapouch** [comment]
Still no difference.

**Comment by Hiradur** [comment]
> converting the wav it was changed from 1536kbps bitrate to 768

That is correct behavior, mono only needs half the bitrate.

**Comment by gigapouch** [comment]
Then what could be the issue?

**Comment by gigapouch** [comment]
Bump, I still would like to know. Changing the pitch and putting audio in a certain zip just makes the engine sound like air speeding up and down (not the wind noise, but the idle, higher pitched).

**Comment by Hiradur** [comment]
Could you reupload the sounds, please?

**Comment by gigapouch** [comment]
Oh, I know why you can't access the link. The IP of my server changed.
http://69.107.93.24/Uploads/default_starter_start.wav
http://69.107.93.24/Uploads/default_car_idle.wav

**Comment by gigapouch** [comment]
The log: http://69.107.93.24/Uploads/soundissue/RoR.log

**Comment by Hiradur** [comment]
I imported the sounds to Audacity and exported them to wave again. After this process they work. So either your software is crap (if it's by dvdvideosoft it's probably loaded with adware as well) or you did something wrong.

**Comment by gigapouch** [comment]
Yep I used dvdvideosoft's converter but declined the bundled software.

**Comment by gigapouch** [comment]
I do have Audacity though so I'll convert them now.

**Comment by gigapouch** [comment]
It works now but when I rev the engine it sounds nothing like my dad's car.

**Comment by Hiradur** [comment]
Well, to make it more realistic you have to record the car at different levels of rpm. I also noticed the sounds don't loop properly. There should be soms docs on the wiki to help you out.
The sound engine in RoR could probably be improved, too. But it's not a priority right now.

**Comment by gigapouch** [comment]
So I could just record the real car's engine revving up to about 4000 or so and then when I cut the audio, just a split second at each RPM would be good enough?

**Comment by Hiradur** [comment]
Engine sounds are a difficult topic.
I'd record 20+ seconds per sample. One sample per x*1000 RPM.
You won't be using the whole sample, you have to cut it to make it loop seamlessly and you have to find a good spot where the end of the loop doesn't differ too much from the beginning (otherwise you can clearly hear where it loops which destroys the immersion)
See here for some tips: http://www.rigsofrods.com/wiki/pages/How_to_create_a_high_quality_sound%28-loop%29

This is not as easy as it sounds. Usually it requires a lot of trial and error to get right.
