### ISSUE TITLE
Game crashing when failing to join server

### ISSUE THREAD

**Issue by EramsorGR** [RigsOfRods/rigs-of-rods#2177]
![image](https://user-images.githubusercontent.com/32240230/52163855-143c9800-26f1-11e9-9eb5-03dde52b1088.png)

`[RoR|Networking] Trying to join server 'rigsofrods.org' on port '12003' ...
NET receive error 1: SWBaseSocket::waitIO() timeout
[RoR|Networking] Failed to connect to server [rigsofrods.org:12003], message: Establishing network session: error getting server version
SWBaseSocket::waitIO() timeout!
terminate called without an active exception
Aborted (core dumped)
`

Just tried to join a server and the game crashed. I suggest making a pop-up rather than crashing the game :P

**Comment by tritonas00** [comment]
duplicate: https://github.com/RigsOfRods/rigs-of-rods/issues/1279
