### ISSUE TITLE
Camera position changes after pausing game

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#222]
So, when you're driving like in interior view with a car having more than one optionl camera settin (standard outside one isn't bugged) and pause the game, after resuming you will be in the next/another camera position then before.

**Comment by Max98** [comment]
It's not really a bug, I made it behave that way to fix a glitch.

**Comment by ulteq** [comment]
It this still a thing? I can't reproduce it.
