### ISSUE TITLE
RPM counter doesn't change with the vehicle

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#223]
Depending on the highest RPM of a vehicle, the RPM counter will change to red at the position. 

Let's say car A has a RPM of 4500. No problems. Then you spawn car 2 with a RPM of 6000, but the counter will still get red at 4500 RPM.

**Comment by gigapouch** [comment]
What's weird with my copy with RoR (0.4.5, test build 3) is that if the redline for the vehicle is say, 3800, the redline of the graphical RPM needle (not in statistics) is 8000.

**Comment by only-a-ptr** [comment]
@DirtGamer301 Details! What do you mean by "the RPM counter will change to red?"

Which HUD are you looking at? Does it have needles or just digits? What vehicles are you testing with? Links, please.

**Comment by gigapouch** [comment]
Wait, there's a digital tachometer now too?

**Comment by Max98** [comment]
@gigapouch Yup, there's one, and here's how you can enable it:
![image](https://cloud.githubusercontent.com/assets/4823878/9025139/4239c89e-38ee-11e5-8a08-29d4fade8e6a.png)

It's under speed unit. :)

**Comment by DirtGamer301** [comment]
@only-a-ptr 
I use the standard tachometer, so not the digital one (as I yet didn't fix the ingame settings bug crashing RoR (corrupted config files) as it takes so long).
By "change to red" I mean when the white lines run out and red lines beging in external camera view.

**Comment by gigapouch** [comment]
Oh, speed unit only says Imperial or Metric. I already use the Digital speedo.

**Comment by Hiradur** [comment]
@DirtGamer301 2 example vehicles please

**Comment by DirtGamer301** [comment]
It should happen with any vehicle as long as the highrest possible RPM is different.
-Spawn car A with a high RPM
-check the RPM counter
-Spawn car B with low RPM
-Check the RPM counter, it's the old one.
-Leave the game
-Spawn car B
-Check the RPM counter

**Comment by only-a-ptr** [comment]
@DirtGamer301 Thanks, I'll check it out

**Comment by wilkgr76** [comment]
Is this the same thing?

![screenshot_2016-07-29_10-40-06_1](https://cloud.githubusercontent.com/assets/12093476/17234118/21e4e080-5579-11e6-9e8b-901dd6f7d5d2.png)

**Comment by DirtGamer301** [comment]
@wilkgr76 It doesn't say 0 on the right, it says 300 (the "3" on the right means 3000, therefore three stripes away from zero it'll be 300). A thing I just noticed on your pic though is the maximum RPM is 4600 but the stripes get red at 6500. however, this seems to be a bug with Burnside itself.
I just tried to reproduce my bug with specific vehicles and don't seem to be able to do so, I must've overseen Petrs message.
I spawned a normal Burnside Sedan.
![screenshot_2016-07-29_10-18-39_1](https://cloud.githubusercontent.com/assets/12358849/17242290/b8e0d28a-5576-11e6-9f9d-e833b6df30a8.jpg)
I then spawned a '49 Ford, the RPM display on the right seems to be correct.
![screenshot_2016-07-29_10-19-07_1](https://cloud.githubusercontent.com/assets/12358849/17242291/b8e6dc98-5576-11e6-9989-d703defd1ba5.jpg)
I spawned a Cherolet S10 Drag, the RPM display on the right changed again and is correct again.
![screenshot_2016-07-29_10-20-10_1](https://cloud.githubusercontent.com/assets/12358849/17242292/b8e6f49e-5576-11e6-9e62-5808aea51189.jpg)
So I guess this can be closed. Reopen it if there's further stuff to discuss or someone has the bug again.

**Comment by wilkgr76** [comment]
That isn't a Burnside, this is a Porsche!
![screenshot_2016-07-29_21-14-41_1](https://cloud.githubusercontent.com/assets/12093476/17246821/e54f70c8-55d1-11e6-8248-d6fda7cad071.png)

**Comment by disloyalpick** [comment]
Your porsche is illegal banned content

**Comment by wilkgr76** [comment]
@disloyalpick Oops, sorry. Removing.

**Comment by Hiradur** [comment]
@wilkgr76 Create a new ticket for that, please.

**Comment by wilkgr76** [comment]
@Hiradur Will do, just wanted to ask just in case it was the same issue.
