### ISSUE TITLE
Turn signals broken

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2230]
Not really much to say about this one, only the left signal works regardless of which key you press.

**Comment by tritonas00** [comment]
maybe this https://github.com/RigsOfRods/rigs-of-rods/pull/2200

**Comment by ulteq** [comment]
-> https://github.com/RigsOfRods/rigs-of-rods/commit/8213c073d9ba7308dc4dc9a3a6048bcf8f64cf3c
