### ISSUE TITLE
Game crashes when hovering with mouse on in-game settings button

### ISSUE THREAD

**Issue by Bumbieris112** [RigsOfRods/rigs-of-rods#2231]
Game crashes when hovering with mouse on in-game settings button:
![ror_crash](https://user-images.githubusercontent.com/36187324/52541966-c2a4a500-2da3-11e9-8256-c0f656ca9a0a.png)

Terminal only shows this: Segmentation fault (core dumped)

Note to moderators - this is not duplicate with this (https://github.com/RigsOfRods/rigs-of-rods/issues/237), because it was on Windows, but this is on GNU/Linux and also there are some differences.
This is similiar to https://github.com/RigsOfRods/rigs-of-rods/issues/2122 but it is unclear what OS was used, since he/she didn't mentioned that.

System configuration:
OS: Ubuntu 18.10 64bit
Renderer used: OpenGL

Game version info:
Version: 0.4.8.0-RC3-90c279el
Game was downloaded from Itch.io

**Comment by tritonas00** [comment]
its fixed in master
