### ISSUE TITLE
Changing a map won't change the reflections

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#224]
When you're on map A, get back to the menu and go on map B, the reflections on your car 8or whatever your vehicle is) will still be the ones from map A.

http://www.rigsofrods.com/attachment.php?attachmentid=534607&d=1433071920
 As you see in the middle mirror there's still the reflections from LaPaz, the last place I've been there. The position of the reflection didn't change with the car moving, too. Same goes for the exterior reflections. The mirrors with videocamera worked though.

RoR.log:
www.rigsofrods.com/attachment.php?attachmentid=534611&d=1433072264

**Comment by Max98** [comment]
#57 Please, try to look if the bug is already reported!

**Comment by DirtGamer301** [comment]
Sorry, I tried looking through all of them but might've missed that (I haven't seen it at all).
