### ISSUE TITLE
Wheel (swaps) problems

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#225]
There seems to be a bigger problem with wheel swaps and wheels genuarly.

Sometimes the meshes don't shop up, sometimes the whole n/b is gone with the meshes, or there's the meshes only.

1.
Rims not showing up, no n/b for the tires, tires doing strange things when turning, RoR standard steering wheel somewhere, oversized, BMW steering wheel nowhere
Pics:
http://www.rigsofrods.com/attachment.php?attachmentid=534618&d=1433075287
http://www.rigsofrods.com/attachment.php?attachmentid=534619&d=1433075295
http://www.rigsofrods.com/attachment.php?attachmentid=534620&d=1433075303
RoR.log:
www.rigsofrods.com/attachment.php?attachmentid=534621&d=1433075334

2.
Wheel of modificed Burnside Coupe won't show up, works in other versions and original Burnside
Pics:
http://www.rigsofrods.com/attachment.php?attachmentid=534588&d=1433059682http://www.rigsofrods.com/attachment.php?attachmentid=534589&d=1433059692
RoR.log:
www.rigsofrods.com/attachment.php?attachmentid=534590&d=1433059714

3.
Not only on the burnside Coupe, also on my Gavril G2 one swapped wheel doesn't show up. Other than the Burnside, the n/b for the wheel is there, the rim shows up, only the wheel wich was already there as standard is gone. It works for the normal G2R.
Pics:
http://www.rigsofrods.com/attachment.php?attachmentid=534608&d=1433072226
http://www.rigsofrods.com/attachment.php?attachmentid=534609&d=1433072232
http://www.rigsofrods.com/attachment.php?attachmentid=534610&d=1433072241
RoR.log:
www.rigsofrods.com/attachment.php?attachmentid=534611&d=1433072264

**Comment by Max98** [comment]
2/
The line is clearly invalid, it's missing a coma;
>0.3, 0.223 0.25, 12, 66, (...)  hayashi5_2w.mesh tracks/trans

try with this instead.
> 0.3, 0.223, 0.25

**Comment by DirtGamer301** [comment]
Ouch yeah!

**Comment by DirtGamer301** [comment]
So...
For every mentioned car/mod there was a mistake done in the truck file.
1. ".5" instead of "0.5" used.
2. missing commatra " " instead of ","
3. two commatras behind each other ",," instead of ","
