### ISSUE TITLE
Large spark particles

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2256]
#2095 did make them less frequent, but they still occasionally happen unfortunately:
![particlebug](https://user-images.githubusercontent.com/46073351/52833315-34ce0000-30aa-11e9-9a54-231c1f8cf584.gif)

**Comment by ulteq** [comment]
They're much easier to reproduce when you enable slow motion. But I have no idea why they occur.

**Comment by only-a-ptr** [comment]
I couldn't reproduce this - is it still a problem?

**Comment by CuriousMike56** [comment]
Seems its been fixed at some point, I'll close this.
