### ISSUE TITLE
Particle key conflicts with CTRL+G

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2257]
Spawn anything with a particle cannon (such as the [KME](http://forum.rigsofrods.org/resources/2008-kme-predator.254/)) and open the selector window with CTRL+G.
![image](https://user-images.githubusercontent.com/46073351/52834528-4c0fec00-30b0-11e9-83a1-4612adc84835.png)

**Comment by disloyalpick** [comment]
Can confirm. 

![wsgddfp 1](https://user-images.githubusercontent.com/13305403/52834623-c50f4380-30b0-11e9-8c38-50db555ec15b.jpg)
