### ISSUE TITLE
Custom material no longer receiving shadows

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2258]
A few objects from some maps I've converted use an alpha splatting material which supports normal maps, vehicle lights, and PSSM.
As of the recent Ogre update, they no longer receive shadows:

[RoR Compound](http://forum.rigsofrods.org/resources/ror-compound.226/):
![image](https://user-images.githubusercontent.com/46073351/52834837-ba08e300-30b1-11e9-9f19-8b159756c50e.png)
[Badlands Rally](http://forum.rigsofrods.org/resources/badlands-rally.157/):
![image](https://user-images.githubusercontent.com/46073351/52834847-c42ae180-30b1-11e9-83b0-b157dd0151c3.png)
How they should look (RC3):
![image](https://user-images.githubusercontent.com/46073351/52835768-e0308200-30b5-11e9-9789-d963736ecde5.png)
![image](https://user-images.githubusercontent.com/46073351/52835772-e32b7280-30b5-11e9-9838-44f89c0586a6.png)
Material files:
[RoR Compound](https://pastebin.com/raw/JUwJEEhQ)
[Badlands Rally](https://pastebin.com/raw/VmzAhVcz)

@ulteq told me they apparently work fine for him on OpenGL, though I can't test that for myself as the terrain shader fails to compile (causing a crash) with OpenGL on my Intel GPU.

**Comment by paroj** [comment]
AFAICS there was no Ogre upgrade, things are still at 1.11.5.

also the texture shadow materials typically use "content_type shadow" TUs somewhere:
https://github.com/OGRECave/ogre/blob/master/Samples/Media/materials/scripts/pssm.material#L265

but RoR seems to do this differently.

**Comment by only-a-ptr** [comment]
@CuriousMike56 Can you re-test with current upstream?

I just tested with both OpenGL and Dx9 on Windows 7, NVIDIA GeForce GTX 660 - PSSM is working just fine. I tried both highest and lowest detail.

Note: changing PSSM settings in Settings window has limited effect until the game is restarted (managedmaterials used by terrain load on startup). I'll change it to load them when loading terrain instead.

**Comment by CuriousMike56** [comment]
Still valid for me:
![image](https://user-images.githubusercontent.com/46073351/54853262-b9252b80-4cc5-11e9-9908-4faba7cee465.png)

**Comment by CuriousMike56** [comment]
This appears to be fixed for me:
![image](https://user-images.githubusercontent.com/46073351/66867029-792adc00-ef68-11e9-8299-fab8172f8034.png)
I did update my GPU drivers recently, so that might have helped.
