### ISSUE TITLE
Flashing flares

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#226]
On some vehicles, I have noticed, like the Mercedes-Benz Citaro MitCity bus, the brake lights and reverse lights flash whenever they are on. I am using 0.4.5 Test Build 3.

**Comment by only-a-ptr** [comment]
@gigapouch : Please post download links for those vehicles.

**Comment by Max98** [comment]
@only-a-ptr You can use the default Agora bus, it has the same type of bug, but happens when you turn on the front lights for example.
