### ISSUE TITLE
Regression bug? Zoom after play game

### ISSUE THREAD

**Issue by KinG-InFeT** [RigsOfRods/rigs-of-rods#2278]
Hi all,
i try game from itch on my fedora 29 system and after play game the zoom is wrong
![image](https://user-images.githubusercontent.com/193969/52961914-49591380-339c-11e9-9c63-8c6ae7b476e2.png)

It seems that at the first start you are wrong to set the size of the starting screen, but in the other pages remains that resolution.
![image](https://user-images.githubusercontent.com/193969/52961938-57a72f80-339c-11e9-93da-4337f925e0c2.png)

My laptop has 2 screens (main laptop) and a monitor in HDMI connected. can this be the problem?

i'm here for any test

**Comment by CuriousMike56** [comment]
This issue was fixed when MyGUI was reverted to an earlier commit. Perhaps RC4 was built with a newer MyGUI by mistake? @AnotherFoxGuy

**Comment by KinG-InFeT** [comment]
other screen after run game (in game)
![image](https://user-images.githubusercontent.com/193969/54020706-b0453d80-418e-11e9-89d2-76b293757b69.png)

**Comment by tritonas00** [comment]
@AnotherFoxGuy did you tag mygui to `07da0620e0d835346452b02b7b1ba7c583429736`?

**Comment by KinG-InFeT** [comment]
i confirm this issue with latest version (Edge version from itch)

**Comment by tritonas00** [comment]
@KinG-InFeT it should be fixed on the latest dev build
![kk](https://user-images.githubusercontent.com/2660424/56383263-21fab780-6222-11e9-88bb-0084773b96d3.png)

**Comment by KinG-InFeT** [comment]
hi @tritonas00 i try with latest dev release and confirm this bug:
![image](https://user-images.githubusercontent.com/193969/58811958-1b34d200-8621-11e9-8805-6d4b07584921.png)
![image](https://user-images.githubusercontent.com/193969/58811972-2425a380-8621-11e9-9907-a1b1f45b7db1.png)
![image](https://user-images.githubusercontent.com/193969/58812014-39023700-8621-11e9-9078-177e84c42305.png)

**Comment by tritonas00** [comment]
did you resize the window manually?

**Comment by KinG-InFeT** [comment]
ror starts in a small window (like in screen) then I try to enlarge the window but in reality the content remains "small" I will try to make a video to try to explain better.

**Comment by CuriousMike56** [comment]
You can't resize the window manually. You must set the window size by going to Settings -> Render System -> Video Mode.

**Comment by KinG-InFeT** [comment]
Yes but it's ery difficult change setting from small window
![image](https://user-images.githubusercontent.com/193969/58868182-1a9d4980-86bc-11e9-954c-0d86e6b37368.png)
Can you change default setting and set window mode to 1024x768 resolution?

**Comment by tritonas00** [comment]
yes `/home/babis/.rigsofrods/config/ogre.cfg`

in the `Video Mode=` line

**Comment by KinG-InFeT** [comment]
if possible add default configuration in master?

**Comment by tritonas00** [comment]
ogre writes that file automatically

**Comment by KinG-InFeT** [comment]
mhmm if possibiel detect first start application and set automatically video mode? it would be very useful to solve this annoying problem.

**Comment by tritonas00** [comment]
>detect first start application and set automatically video mode
it already sets the minimum resolution, if you cant change it inside the game the just change it in `ogre.cfg`
it will keep it

**Comment by KinG-InFeT** [comment]
forgive me maybe I explained myself wrongly, after changing the resolution from system (or even from the configuration file) from the second start the window was 1024x768 big. my question was whether at least 1024x768 could be set as the first configuration otherwise it could give my own problem to someone else.

**Comment by tritonas00** [comment]
well that's strange because even with the lowest resolution (640x480) i can change it inside RoR
![kk](https://user-images.githubusercontent.com/2660424/58907555-2538fc80-8717-11e9-8044-ff306d1ecd01.png)

**Comment by KinG-InFeT** [comment]
yes yes i change it, but with first resolution (first screenshot) it's very difficult

**Comment by tritonas00** [comment]
>but with first resolution (first screenshot)

and what resolution is that?

**Comment by KinG-InFeT** [comment]
yes, my first resolution is: 320x180
![image](https://user-images.githubusercontent.com/193969/58952592-67545380-8794-11e9-9535-a103e59dcf79.png)

**Comment by tritonas00** [comment]
that explains it haha

**Comment by tritonas00** [comment]
this is now fixed on master

**Comment by KinG-InFeT** [comment]
Thank you
