### ISSUE TITLE
mods.cache written into current directory (Linux)

### ISSUE THREAD

**Issue by schmatzler** [RigsOfRods/rigs-of-rods#228]
I've just built the latest code 91ae45dc6e7ca6e265c26cce7c5f5f8704267c4a and I've noticed a strange behaviour. When there is no config on the system (no ~/.rigsofrods/cache folder) I can only start up RoR if I create the directory ~/.rigsofrods/cache and run the RoR binary directly from there. Otherwise it can't find the file mods.cache.

What apparently happens is that RoR writes mods.cache into the directory it is started from. Reproducing that is very simple: I've put a test folder on my desktop and ran it from there and that one was filled with various .dds and .png files.

**Comment by Max98** [comment]
@Hiradur You might take a look at this.

**Comment by Hiradur** [comment]
You are supposed to run the configurator first which does the initialization.

**Comment by schmatzler** [comment]
It happens with the configurator, too. Because when I add new vehicles and terrains they only get loaded when the game itself is running.

**Comment by Hiradur** [comment]
Are you talking about this error?

```
Fatal Error: Unable to write cache to disk: Unable to write file.
Please ensure the parent directories exists and that you have write access to this location:
/home/hiradur/.rigsofrods/cache/mods.cache
```

**Comment by schmatzler** [comment]
No, when I start RoR from my home directory, this happens:

```
Cache updated, enumerating all resource groups...
                Autodetect
                Bootstrap
                General
                General-100
                General-16
                General-25
                General-42
                General-64
                General-76
                General-95
                Internal
                Packs
                Scripts
                TerrainFolders
                VehicleFolders
                Wallpapers
                cache
loading cache...
unable to load config file: mods.cache


No content installed: You have no content installed
```

And then I end up with my home directory full of cache files.

**Comment by Hiradur** [comment]
So what exactly do I have to do to reproduce this?

**Comment by schmatzler** [comment]
1. Delete $HOME/.rigsofrods/cache
2. Run RoR from some directory
3. Watch the directory get filled with mods.cache, RoR crashes because it can't find the content.

**Comment by Hiradur** [comment]
I did exactly this and get the error from above. Hm. Are you using Slackware?

**Comment by schmatzler** [comment]
Yes, still using Slackware.

My binary resides in /usr/games/rigsofrods/RoR if that makes a difference.

**Comment by Hiradur** [comment]
Slackware is a black box for me, never used it.

What happens if you run RoR from your home directory?

**Comment by schmatzler** [comment]
Then my home directory gets filled with .dds files and mods.cache.

When I run RoR the first time from ~/.rigsofrods/cache I can run it afterwards from any directory I want and it will work without spamming my folders. But when I add new vehicles, packs or terrains, I have to re-run it again from the cache folder.

**Comment by Hiradur** [comment]
This shouldn't happen. Do you happen to know any significant difference between Slackware and Debian/Ubuntu which could be related to this (i.e. user permissions are different)?

**Comment by schmatzler** [comment]
Slackware isn't really different from other distributions, as far as I know.

It worked in older commits. I will try to pinpoint the exact commit later, but it will take a while since my machine is pretty old.

**Comment by Hiradur** [comment]
@schmatzler Sorry, I was working with my debug build which I didn't fast forward to the latest commit. I now did that and got the same problem as you so it's not Slackware related.
Before I was on commit 04d44dd
So the regression came between 04d44dd and 91ae45dc6e7ca6e265c26cce7c5f5f8704267c4a

@Max98 and @only-a-ptr: Any ideas which of your changes could cause this?

**Comment by Max98** [comment]
I have quickly checked all of the commits between 04d44dd2e568c1e8f48e91dd41e04ca5ea193f6c & 91ae45dc6e7ca6e265c26cce7c5f5f8704267c4a and I didn't see any new/deleted code about the cache manager. I will take a deep look tonight.

**Comment by tritonas00** [comment]
Same here (Archlinux).

Compiled today with clean config, same behaviour as schmatzler's.

**Comment by Hiradur** [comment]
@Max98 Does it happen on Windows, too?

**Comment by Max98** [comment]
@Hiradur Nope: http://i.imgur.com/kF7pfEL.jpg

**Comment by Hiradur** [comment]
@schmatzler @tritonas00 Can you confirm this bug is gone with the latest revision?

**Comment by tritonas00** [comment]
Just compiled, nope same thing happens.

**Comment by Hiradur** [comment]
Weird, i can no longer reproduce it with the latest revision, only if I revert to an older commit

**Comment by tritonas00** [comment]
Well i dont know. I removed .rigsofrods, started RoRConfig from ~/Downloads, made settings and save then start RoR from that folder and writes the cache there.

If i run it from ~/.rigsofrods/cache then starts ok

**Comment by Hiradur** [comment]
Yes, latest commit from master

**Comment by tritonas00** [comment]
Which commit is supposed to fix this?

**Comment by Hiradur** [comment]
None, I wanted to look into it and realized it doesn't happen anymore.

**Comment by tritonas00** [comment]
:P

Well, once the cache is written properly in ~/.rigsofrods/cache then it starts from everywhere.

**Comment by Hiradur** [comment]
If I do ```rm ~/.rigsofrods/cache/*``` and then run it from anywhere else it works as expected.

**Comment by Hiradur** [comment]
Oops, I just realized I only synced my personal repo's ogre2 branch but not the master branch. That explains everything...

**Comment by Max98** [comment]
@tritonas00 A quick and hacky fix would be to go to RoR.cfg, you'll find 2 vars: 'CachePath' and "Cache Path"
Just direct both to your cache's directory and it should work.
This is indeed a bug and the source needs some clean up.

**Comment by Hiradur** [comment]
Using binary search I quickly discovered that this bug was introduced with https://github.com/RigsOfRods/rigs-of-rods/commit/ab206a4669293574e5f4dd6bc05768d8717a3fe0
I'll take a deeper look later
