### ISSUE TITLE
T813 Material/texture issues

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2280]
- Spawn [Tatra T813 Dakar](https://forum.rigsofrods.org/resources/tatra-t813-dakar.145/)
- Then spawn this after: [Tatra_T813_Kolos.zip](https://github.com/RigsOfRods/rigs-of-rods/files/2877264/Tatra_T813_Kolos.zip)
![screenshot_2019-02-18_12-01-01_1](https://user-images.githubusercontent.com/46073351/52974566-0729d500-3390-11e9-81ee-a0c72740b5e1.png)
It's mainly the pink texture that's the issue.

**Comment by ulteq** [comment]
This started to happen when you modified the Tatra T813 Dakar. Could you paste what you changed?

**Comment by CuriousMike56** [comment]
I converted most of the materials from `t813.material` to `managedmaterials`:
```
managedmaterials
;new_material   effect   base_texture   damage_texture   specular_texture
t-813-mirror flexmesh_standard t813-black.dds t813-black.dds t813-white.dds
;MainColor/SOLID/TEX/t813wheel.tga mesh_standard t813wheel.dds t813-black2.dds
MainColor/SOLID/TEX/t813wheel.tga mesh_standard t813wheel.dds -
Crome/SOLID/TEX/t813.tga mesh_standard t813.dds t813-crome-spec.dds
Crome/SOLID/TEX/t813body-race.tga mesh_standard t813body-race.dds t813-crome-spec.dds
MainColor2/SOLID/TEX/t813body-race.tga flexmesh_standard t813body-race.dds t813body-race-dmg.dds t813body-race-spec.dds
MainColor/SOLID/TEX/t813body-race.tga flexmesh_standard t813body-race.dds t813body-race-dmg.dds t813-black2.dds
window/SOLID/TEX/t813window.tga flexmesh_transparent t813window.dds t813window-dmg.dds t813window-spec.dds
MainColor/SOLID/TEX/t813doors.tga flexmesh_standard t813doors.dds t813doors-dmg.dds t813-black.dds
Crome/SOLID/TEX/t813bumper.tga mesh_standard t813bumper.dds t813-crome-spec.dds
MainColor/SOLID/TEX/t813light_material_0.tga mesh_standard t813light_material_0.dds t813-black2.dds
MainColor/SOLID/TEX/t813.tga flexmesh_standard t813.dds t813-dmg.dds t813-black.dds
Black/SOLID/TEX/t813bumper.tga flexmesh_standard t813bumper.dds t813bumper-dmg.dds t813-black.dds
Crome/SOLID/TEX/t813light_material_0.tga mesh_standard t813light_material_0.dds t813-crome-spec.dds
set_managedmaterials_options 1
MainColor2/SOLID/TEX/t813seats-race.tga/TWOSIDE mesh_standard t813seats-race.dds t813body-race-spec.dds
set_managedmaterials_options 0
Crome/SOLID/TEX/t813doors.tga mesh_standard t813doors.dds t813-crome-spec.dds
MainColor/SOLID/TEX/t813bumper.tga flexmesh_standard t813bumper.dds t813bumper-dmg.dds t813-black.dds
```

**Comment by only-a-ptr** [comment]
The bright pink is a managedmaterial-placeholder. It means the managedmaterial was defined, but for some reason it could not be set up on the target mesh. Look for anything unusual in RoR.log

**Comment by ulteq** [comment]
> I converted most of the materials from `t813.material` to `managedmaterials`

And both trucks are using the same managed material, right?

**Comment by only-a-ptr** [comment]
It doesn't happen with the stock mods linked above. I'll try to re-apply @CuriousMike56 's changes

**Comment by only-a-ptr** [comment]
We're dealing with an OGRE issue. Material name conflict can't be resolved using resource groups. In this case, Dakar generates the managedmaterial placeholders (in RG1) and the Koloss picks them up, even if created in RG2. Upstream doesn't handle this, so I added it, but it didn't help: https://github.com/only-a-ptr/rigs-of-rods/commit/1ad65317df4fefdcded523c1e2d43f2633fcfade

**Comment by tritonas00** [comment]
is this related maybe? https://github.com/OGRECave/ogre/commit/5407613c6efa6167d164f42b4418923d3e701995
