### ISSUE TITLE
Feature Request: Repository Downloads

### ISSUE THREAD

**Issue by ghost** [RigsOfRods/rigs-of-rods#229]
A neat new feature for the next official release of RoR would be a built in repository downloader. So, the RoRConfig.exe checks for vehicles and terrains in the repository that you don't have and downloads them after it prompts you and you click Yes.

**Comment by only-a-ptr** [comment]
This would be nice to have, indeed.

Unfortunately, this would require the repository web application, and only TDev has sources and access to do that. Further, this would cause much more frequent downloads which means more server bandwidth and possibly (I don't know if it matters) more money for TDev to pay for hosting.

A simple + feasible improvement would be to add [download content] button to the selector, which would open web repository in player's default browser.

**Comment by vido89** [comment]
Why it needs to be on ror main site, and why we do not use more then one mirror/place for stuff like this

**Comment by only-a-ptr** [comment]
@vido89 : It doesn't, really, we may just as well set up an alternate repository, if we find a hosting with enough space and bandwidth. To be honest, I don't really like the current reposotory - it has bloated UI with rather amateur design and the search box doesn't really search.

@vido89 :However, new repository would also need new content. I'm not sure authors would agree with us to move their stuff, and a lot of stuff is abandoned, so there's nobody to move it. 

This requires wider discussion in the community. But I like the idea

**Comment by gigapouch** [comment]
It's OK if it won't work out, it was just a suggestion. ;)

**Comment by Hiradur** [comment]
@vido89 
The repository is mirrored according to http://www.rigsofrods.com/CdnNodes/
Also see how much traffic it generates: http://www.rigsofrods.com/repository/stats

**Comment by vido89** [comment]
@Hiradur yup some nice stats there, so there is need to mirror it on more places

**Comment by Dogy144** [comment]
Just a suggestion, but maybe integrate with steam? (Steam Workshop?)

**Comment by gigapouch** [comment]
No, not Steam! I'm not quite 13 yet! (I will be in September, though.)

**Comment by gigapouch** [comment]
Not Steam, because then the RoR fans that are under 13 (like me, I'm 12 1/2) won't get to download any mods!

**Comment by DirtGamer301** [comment]
By what I know, it's not that easy to release a game via Steam and it does cost money.

Also, I'm always happy to have something which I don't need to be logged in all time to play and which I don't need an account to get (I have a Steam Account, but it's nicer to have RoR as its own).
I think looking up the repository from time to time is no problem, and beside this, every modder would have to release their mods in the Repo, as at the moment, most just release them in the forums.

Just my two cent, I'd rather have RoR as its own and working without Steam, as also I think the multiplayer would only work with/without Steam. So for example if person A has RoR with Steam and person B without they wouldn't be able to play together as Steam Multiplayer runs on Steam servers (not much knowledge here but I think it's so).

**Comment by Dogy144** [comment]
I see where you are coming from, but it was just a thought :)

**Comment by Hiradur** [comment]
I don't like the idea of Steam because it's unpredictable due to its proprietary nature. The workshop may be superior to the current system but it could always change or be removed (although unlikely it's not impossible) which would lead to total chaos.
It also costs time and money to get the game on Steam. People already proposed the idea to move to Steam for other open source games but AFAIK every project said no because it trades some benefits for limits. Limits are something which open source projects try to avoid.

**Comment by tylerhoot** [comment]
could the repos be done via github to deal with the bandwidth?

**Comment by only-a-ptr** [comment]
@tylerhoot Bandwidth no longer an issue, we have a generous webhost now.

The only thing left to do is to finish the implementation: https://forum.rigsofrods.org/thread-496-post-5446.html#pid5446

**Comment by tylerhoot** [comment]
sounds good. great to see a good thing come back.
