### ISSUE TITLE
MP issues with previously loaded terrains

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2303]
This happened during a MP session on `Debug_Server_MitCity`, causing all players to crash. I had to investigate. 

- Launch two RoR clients. (For one of the clients, I copied the install directory and created a `config` folder in it to prevent any conflicts with my Documents folder)
- On one client, click Single player and load Auriga Proving Grounds. 
- On the other client, join a server with a fixed terrain set (e.g. `Debug_Server_MitCity` or `Debug_Server_Neo`):
![image](https://user-images.githubusercontent.com/46073351/53661710-f51d2180-3c2e-11e9-9f8c-50e12264d5c7.png)
I will be calling the left window `Client A` and the right window `Client B`.
- Press `ESC` and click `Return to menu` on Client A, then join the same server Client B is on.
- All pre-spawned loads from the previous terrain Client A was on will attempt to spawn, causing Client A to get kicked for spawning too many actors:
![image](https://user-images.githubusercontent.com/46073351/53662167-41b52c80-3c30-11e9-8291-4ead63c49ca5.png)
![image](https://user-images.githubusercontent.com/46073351/53662181-4aa5fe00-3c30-11e9-9b30-c322285374b5.png)
The first couple of times I tried reproducing this crash, Client B crashed with a UTF-8 error:
![image](https://user-images.githubusercontent.com/46073351/53662291-8c36a900-3c30-11e9-8b48-9c68df12d745.png)
Loading a terrain without any pre-spawned vehicles (e.g. Simple Test Terrain) won't immediately cause a crash when joining, but if Client B has a vehicle spawned, then Client A will crash:
![image](https://user-images.githubusercontent.com/46073351/53662549-2565bf80-3c31-11e9-9748-db3aa500c022.png)
Here's another example, I loaded RaceMax on Client A and joined `Debug_Server_Neo` on Client B, then on Client A I returned to menu and joined the server:
![image](https://user-images.githubusercontent.com/46073351/53662691-8db4a100-3c31-11e9-810b-338121af0b0e.png)

**Comment by tritonas00** [comment]
Indeed
![kk](https://user-images.githubusercontent.com/2660424/53664374-02f39680-3c71-11e9-9420-82233a445aea.png)

**Comment by ulteq** [comment]
> it would be nice if instead of random characters on imgui error dialog we had "Auto-kicked for having too many vehicles"

We should open a separate issue for that bug.
