### ISSUE TITLE
Crash when cycling through skeleton views

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2305]
- Spawn the [2008 KME Predator](https://forum.rigsofrods.org/resources/2008-kme-predator.254/).
- Switch to first person view then cycle through the skeleton debug views with `CTRL+K`, the game should crash with a D3D9 error:
![image](https://user-images.githubusercontent.com/46073351/53666887-6368e080-3c3d-11e9-9317-a45b21893596.png)
I had the same crash happen once in third person, but I can't seem to reproduce it again.

**Comment by ulteq** [comment]
Do you get the same error message when you enable 'Rotator details' and then turn the camera away from the truck?

**Comment by CuriousMike56** [comment]
Yes:
![image](https://user-images.githubusercontent.com/46073351/53688484-9e891380-3d12-11e9-90a7-ddb65b3def0d.png)

**Comment by ulteq** [comment]
I get a slightly different error message:
```
InternalErrorException: Vertex Buffer: Out of memory in GLHardwareVertexBuffer::lock at ~/ror-dependencies/Source/ogre/RenderSystems/GL/src/OgreGLHardwareVertexBuffer.cpp (line 126)
```
