### ISSUE TITLE
Plane wings lag behind when backspacing

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2306]
While moving with backspace, plane wings will lag behind:
![planewingbug](https://user-images.githubusercontent.com/46073351/53667945-7e891f80-3c40-11e9-945e-c9adc897df7b.gif)
This is especially noticeable if you hold CTRL or SHIFT.

**Comment by tritonas00** [comment]
That happened after async introduced iirc
