### ISSUE TITLE
Issues on server kick

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#2309]
If the server kicks you (eg for spawning too many vehicles) there are some issues:

- The imgui message `disconnected: remote side closed the connection` is empty on linux.
if i put a small message [here](https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/network/Network.cpp#L388) (like `NetFatalError(_L("disconnected:"));` it works, so maybe the issue is the message length?
![kk](https://user-images.githubusercontent.com/2660424/53694995-94bcea00-3dbe-11e9-82d0-a87ee4d7894c.png)

- If you click `Multiplayer` and try to connect again you get `Could not create connection`

- Pressing `Exit game` causes the game to crash or hang

**Comment by CuriousMike56** [comment]
I get `disconnected: remote side closed the connection`:
![image](https://user-images.githubusercontent.com/46073351/53697305-3f70e080-3d9e-11e9-978d-bcb8dc4fc154.png)
Pressing `Exit game` after though does result in a crash.

**Comment by tritonas00** [comment]
Also when a server admin kicks me i get:
![kk](https://user-images.githubusercontent.com/2660424/53697426-92b45480-3dd9-11e9-90a5-00ae865b88c0.png)

**Comment by tritonas00** [comment]
@only-a-ptr any suggestions about making it play nice with linux also?

**Comment by tritonas00** [comment]
@CuriousMike56 
>Pressing Exit game after though does result in a crash.

this seems to be fixed now can you confirm?

**Comment by tritonas00** [comment]
if put a small message here https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/network/Network.cpp#L388 (like `NetFatalError(_L("disconnected:"));` it works, so maybe the issue is the message length?

**Comment by tritonas00** [comment]
commenting 
https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/network/Network.cpp#L179
fixes 2 and 3

**Comment by tritonas00** [comment]
@only-a-ptr is this an easy one for 0.4.8?

**Comment by only-a-ptr** [comment]
@tritonas00 I'm afraid not, but I'll give it another try. Can you re-test the above issues with rorserver running on your machine?

Regarding 'Network.cpp#L179': Lately I'm always baffled by the hacks you're able to find. This line is supposed to _prevent_ hangs/crashes by stopping all network communication when 'fatal error' happens. If it actually causes such problems, it means some of the 'fatal errors' are not _that_ fatal and proper disconnect needs to be done. But it might behave differently on Windows. Eh, I dislike SocketW.

Regarding the NetFatalError message: totally not message length, probably multithreading but maybe also memory corruption.

**Comment by tritonas00** [comment]
Thanks for looking on this!

>Can you re-test the above issues with rorserver running on your machine?

Already do that, thats how i test

>it means some of the 'fatal errors' are not that fatal

Yes, server kicking should not be a fatal error

>NetFatalError message:

probably it feeds garbage here https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/gameplay/RoRFrameListener.cpp#L2284

- if you add the text there it works
- if you always show that imgui dialog in the loop (https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/network/Network.cpp#L337), you can see random characters changing all the time

**Comment by only-a-ptr** [comment]
*Related*: I closed the rorserver console window while connected. Environment: Win10 x64, RoR + rorserver built as Debug+x64.
![image](https://user-images.githubusercontent.com/491088/62252249-997bdd80-b3f2-11e9-9374-24f7605081c5.png)
[server.log](https://github.com/RigsOfRods/rigs-of-rods/files/3454128/server.log)
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/3454130/RoR.log)

**Comment by tritonas00** [comment]
at least you get more than 15 characters :laughing:
