### ISSUE TITLE
Default sounds defined in the soundscript file will make the vehicle disappear from the vehcles list all two times after cache regeneration

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#231]
I'm sorry for this long headline, I don't know how to describe it with less words.

But here's with more words:

If you define a RoR default soundscript in your soundscript file, for example

 tracks/default_break
{
trigger_source creak
pitch_source creak
pitch_factors 1.0 0.2
gain_source creak
gain_factors 0.3 1.0
start_sound 1.0 default_break.wav
}

the vehicle will disappear from the vehicles list in RoR after regenerating cache. If you regenerate it again, the vehicle will be back on the list and so on.

Original thread: http://www.rigsofrods.com/threads/119602-SOLVED-Car-disappears-from-vehicle-list-every-two-times-after-regenerating-cache

**Comment by Max98** [comment]
I don't think it's related with sounds, because it happens with terrains also. (Which in my case, happened when testing PSSM shadows on terrains)

**Comment by DirtGamer301** [comment]
But atleast I didn't get this problem anymore (I deleted, re-added, added mod, regenerated cache and all, the Taunus is ingame all time after I removed these lines, atleast yet)

**Comment by Max98** [comment]
Still, this bug happened many times to me and I think we should find a solution.

**Comment by DirtGamer301** [comment]
Sure that, it was more related to 
"I don't think it's related with sounds"

**Comment by Aivar-RoR** [comment]
Check this post for a solution: http://www.rigsofrods.com/threads/119602-SOLVED-Car-disappears-from-vehicle-list-every-two-times-after-regenerating-cache?p=1381587&viewfull=1#post1381587

**Comment by only-a-ptr** [comment]
I'll tackle this.

**Comment by only-a-ptr** [comment]
Resolved in my repo.
RoR will only skip duplicate soundscript entries and load the rest.
