### ISSUE TITLE
Trucks with spaces in filename cannot be used in MP

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2314]
Truck files that have spaces in the file name (e.g. [Jeep TJ](http://forum.rigsofrods.org/resources/tatangjoses-jeep-tjs.3/)) cannot be seen by other players in MP.
![image](https://user-images.githubusercontent.com/46073351/53986811-2e510800-40ed-11e9-9e93-846a3c2cf7b0.png)
![image](https://user-images.githubusercontent.com/46073351/53986599-a2d77700-40ec-11e9-8b10-93a60f5e14fe.png)

**Comment by only-a-ptr** [comment]
I confirm - for filename `Some Name.truck`:
```
13:56:30: [RoR] Creating remote actor for 5:13
13:56:30: [RoR] Cannot create remote actor (not installed), filename: 'Some'
```
