### ISSUE TITLE
Skins window resets section selection

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2316]
If a vehicle with sections has a skinzip, the section selection will be reset when the skin selection window is opened:
![image](https://user-images.githubusercontent.com/46073351/53988167-dcaa7c80-40f0-11e9-9449-a53417d24e93.png)
![image](https://user-images.githubusercontent.com/46073351/53988172-e03e0380-40f0-11e9-90b7-934c328154e7.png)

**Comment by KinG-InFeT** [comment]
i can confirm the problem (fedora, linux)
