### ISSUE TITLE
Game Crash RC3

### ISSUE THREAD

**Issue by Mountfeeres** [RigsOfRods/rigs-of-rods#2318]
Game crash while playing tuanga challenge log is attached.
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/2943419/RoR.log)

**Comment by CuriousMike56** [comment]
Try [RC4](http://forum.rigsofrods.org/threads/test-build-version-0-4-8-rc4.1217/) or the latest development build instead.

**Comment by Mountfeeres** [comment]
I attached the log correction it is Rc4.

**Comment by Mountfeeres** [comment]
I managed to resolve the issue it was a problem with a mod i was using. Thank you for your time.
