### ISSUE TITLE
Caelum clouds missing in 0.4.5

### ISSUE THREAD

**Issue by Hotrod55** [RigsOfRods/rigs-of-rods#232]
When you have sightrange set to Unlimited in 0.4.0.7, clouds are rendered in the sky. 
![screenshot_106](https://cloud.githubusercontent.com/assets/11002490/7965672/fb7cc7e2-09ec-11e5-9200-0013a7644bba.png)
However, using the exact same settings (both 0.4.0.7 and 0.4.5 are run off the same documents folder), in 0.4.5, clouds are not rendered. 
![screenshot_107](https://cloud.githubusercontent.com/assets/11002490/7965721/5fa016de-09ed-11e5-9e57-594b25f2a913.png)
This is the config settings for both versions:
![rigs_of_rods_version_0 4 0 7_configuration_2015-06-03_12-39-22](https://cloud.githubusercontent.com/assets/11002490/7965785/c775a54e-09ed-11e5-85d2-ff6d35765019.png)
![rigs_of_rods_version_0 4 5 0-dev_configuration_2015-06-03_12-40-07](https://cloud.githubusercontent.com/assets/11002490/7965786/c9511e16-09ed-11e5-9635-96a45360783f.png)
Note:Turning off PSSM makes no difference.

It's not really a big deal, but Caelum looks way better with clouds.

**Comment by Hiradur** [comment]
I can still see them but sight range determines how far they are visible:

![screenshot_1](https://cloud.githubusercontent.com/assets/6960065/8649635/6fb6ef7c-296c-11e5-885b-e19fbb38c37c.jpg)
*sight range = 4800m*

fully visible with sight range = unlimited

**Comment by Max98** [comment]
Actually, this was a bug, that I fixed and I forgot to close this.
