### ISSUE TITLE
[itch-DEVEL]  error while loading shared libraries: libXaw.so.7

### ISSUE THREAD

**Issue by KinG-InFeT** [RigsOfRods/rigs-of-rods#2321]
Hi all,
latest build ( 5 days later) from itch devel out this error to first run

REPORT: https://dale.itch.ovh/VdxvaFUvD7Q2Ok8DnnmJgRkGxmHx7x3v80jZkPZSUQ9Ccqof2Kkx1HSBdKPMgFCl

i'm here for any test

**Comment by tritonas00** [comment]
how do you run ror?
