### ISSUE TITLE
[itch] last update 7 days ago

### ISSUE THREAD

**Issue by KinG-InFeT** [RigsOfRods/rigs-of-rods#2322]
Hi ,
trying the new fixes, there are no updates on itch, the last build is 7 days ago
![image](https://user-images.githubusercontent.com/193969/54131569-e561c200-4412-11e9-8b6a-9556e8e0c3a8.png)

**Comment by tritonas00** [comment]
whats the issue?

**Comment by KinG-InFeT** [comment]
I apologize, I had not seen that the repo had not been updated for more than 7 days, so there is no mistake. I close the ticket.
