### ISSUE TITLE
Large character net labels

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2326]
Sometimes when a player spawns a vehicle with a visible driver (e.g. DAF Semi, Agora, etc) the net label that appears above the driver will be quite large.
I can't seem to reproduce the issue reliably, but I have screenshots of it:
![image](https://user-images.githubusercontent.com/46073351/54236107-37751700-44e9-11e9-9eb6-4230d6648c52.png)
![image](https://user-images.githubusercontent.com/46073351/54236141-49ef5080-44e9-11e9-88f9-abb793a85cfa.png)
![image](https://user-images.githubusercontent.com/46073351/54236149-4eb40480-44e9-11e9-888e-78c4dbbb18c8.png)
![image](https://user-images.githubusercontent.com/46073351/54236500-077a4380-44ea-11e9-9de3-39b189f8134b.png)

**Comment by only-a-ptr** [comment]
I also see that the labels are duplicate and showing different distance, i.e. in last screenshot:
* Jesse (1.1km) - huge label
* Jesse (158m) - regular label

**Comment by CuriousMike56** [comment]
By a "visible driver" I meant vehicles that have the default seat mesh, which RoRBot sits in if it's a prop. The Desperado uses a custom driver model, so that isn't affected by this issue.

**Comment by tritonas00** [comment]
>A simple solution would be to just hide the character label if the player is inside a vehicle, IMO it's unnecessary as a label already appears above the vehicle.

Yep, this

**Comment by tritonas00** [comment]
adding `xc_movable_text->setVisible(false);` right after https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/gameplay/Character.cpp#L646 fixes the issue (hides character label when `HasDriverSeatProp`

![kk](https://user-images.githubusercontent.com/2660424/56464564-27f4c200-63f5-11e9-8ccb-41c69594a294.png)
