### ISSUE TITLE
Some server-sided objects not spawning

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2337]
Doesn't have to be fixed in time for 0.4.8, just was wondering if a developer could shed some light on this.

The [server scripts](https://github.com/CuriousMike56/Official-RoRNet238-scripts) allow you to load extra terrain objects via a file. As of 0.4.7.0, there is a chance that not all the objects will spawn. 

To see what I mean, download [N-Labs](http://forum.rigsofrods.org/resources/n-labs-testing-facility.68/) and join the `Debug_Server_NLabs_Modded`  (password: `nlabstest`) server.  Sometimes all the objects will spawn, other times some will be missing:
![image](https://user-images.githubusercontent.com/46073351/55199805-af05a000-5191-11e9-9b0a-7d0cd2a7741e.png)
![image](https://user-images.githubusercontent.com/46073351/55199812-b3ca5400-5191-11e9-9bb4-2dfbff70c914.png)
![image](https://user-images.githubusercontent.com/46073351/55199834-d5c3d680-5191-11e9-920f-ff1699008ce3.png)
The map should look like this if everything spawned correctly:
![image](https://user-images.githubusercontent.com/46073351/55200019-b0839800-5192-11e9-8203-dc29361e8096.png)
![image](https://user-images.githubusercontent.com/46073351/55200023-b2e5f200-5192-11e9-83d5-0193615f7d5c.png)

This also happens to the old [Nhelens objects](https://github.com/CuriousMike56/Official-RoRNet238-scripts/blob/master/scripts/storage/a1da0UID-nhelens.asdata), where a few roads may be missing from spawn:
![image](https://user-images.githubusercontent.com/46073351/55200211-8383b500-5193-11e9-916d-291740427fb1.png)

If I use the `!reloadterrain` command (admin-only) all the objects will spawn just fine.

**Comment by tritonas00** [comment]
Is it possible to load those objects a little later? A bit of delay may help

**Comment by tritonas00** [comment]
@only-a-ptr want to :nauseated_face: some more? :laughing:

How about this? Would be nice to have those terrain objects on servers again.

And also there is another AS issue, like this, sometimes happens some not
