### ISSUE TITLE
Bugs started with #2294

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#2338]
- [x] ~~767 AA airliner air brakes~~ fixed https://github.com/RigsOfRods/rigs-of-rods/pull/2341
Before
![before](https://user-images.githubusercontent.com/2660424/55327955-e3c86e80-5493-11e9-8779-3c1bdcad4555.png)
After
![after](https://user-images.githubusercontent.com/2660424/55327963-e88d2280-5493-11e9-81c1-19dd0f0dddd9.png)

- [x] ~~kurzhauber dumper~~ fixed https://github.com/RigsOfRods/rigs-of-rods/pull/2341
Before
![before](https://user-images.githubusercontent.com/2660424/55328015-170afd80-5494-11e9-8654-dbfb0d5f8ab8.png)
After
![after](https://user-images.githubusercontent.com/2660424/55328029-1c684800-5494-11e9-8192-433b37172d7c.png)

- [ ] Mercedes Actros 8x8 dumper dashboard is not animated any more (started with this commit https://github.com/RigsOfRods/rigs-of-rods/commit/14f824ac5f2215103e7b76f04f54b1a395cfbe93)

http://forum.rigsofrods.org/resources/767-aa-airliner.96/
[48606a416418bdbcee4c8325136959c1c0db8fd1_10bb3UID-rundhauber-dumper.zip](https://github.com/RigsOfRods/rigs-of-rods/files/3029389/48606a416418bdbcee4c8325136959c1c0db8fd1_10bb3UID-rundhauber-dumper.zip)
[45fc291a9d2aa5faaa36cca6df9571cd6d1f1869_Actros_8x8-englisch.zip](https://github.com/RigsOfRods/rigs-of-rods/files/3044343/45fc291a9d2aa5faaa36cca6df9571cd6d1f1869_Actros_8x8-englisch.zip)

**Comment by tritonas00** [comment]
@only-a-ptr want me to find the exact commits which cause the issues?

**Comment by only-a-ptr** [comment]
All should be fixed now.

**Comment by tritonas00** [comment]
indeed :heart:
