### ISSUE TITLE
Configurator fails to create settings file

### ISSUE THREAD

**Issue by Bluejet007** [RigsOfRods/rigs-of-rods#2339]
I have tried using configurator several times, however it fails to create files in onedrive. It creates the RoR folder but then isn't able to create the 'cache' folder and beyond. When it fails, it continues to work with no problem until you click save and then it says it couldn't create a save file. I have tried removing the RoR directory from onedrive but it didn't work. Also, I manually created the 'cache' folder but after creating 'empty' it gave another error saying it couldn't create 'categories.cfg'. I have noticed it seems to give opening error before actually creating it.

When opening:
14:54:28: can't open file 'C:\Users\rachi\OneDrive\DOCUME~1\Rigs of Rods 0.4\\cache\empty' (error 3: the system cannot find the path specified.)
14:54:28: Can not create file 'C:\Users\rachi\OneDrive\DOCUME~1\Rigs of Rods 0.4\\cache\empty'.

After clicking save:
![Capture](https://user-images.githubusercontent.com/49189777/55391938-ec827880-5557-11e9-95e1-38e67658bf42.JPG)

OS: Windows 10

**Comment by tritonas00** [comment]
configurator no longer exists on 0.4.8

**Comment by only-a-ptr** [comment]
Hi.

What version are you using? In the latest master, RoRConfig is deprecated and RoR can deploy the config  files/dirs by itself.

The problem is most definitely the DOS path format `OneDrive\DOCUME~1` - The actual path is `OneDrive\Documents`, right? RORConfig uses DOS paths, I'm not sure why and it shouldn't matter anymore. IIRC RoR handles paths correctly, try it.

**Comment by Bluejet007** [comment]
When I click download at the RoR website, it gives me 0.4.7 version, where can I get 0.4.8?

**Comment by tritonas00** [comment]
https://rigs-of-rods.itch.io/rigs-of-rods-dev

**Comment by Bluejet007** [comment]
Ok thank you for helping me. I am closing the issue.
