### ISSUE TITLE
division by zero in Turbojet::updateForces

### ISSUE THREAD

**Issue by paroj** [RigsOfRods/rigs-of-rods#2342]
line 240:
```
exhaust_velocity = enginethrust * 5.6 / area;
```
area = 0 in https://github.com/OGRECave/ogre/issues/1154

**Comment by tritonas00** [comment]
is this still valid?

the mig seems to work fine here

**Comment by only-a-ptr** [comment]
I just checked - it's valid, we're always dividing by zero 😱 The result is only used for particles, though. I don't know why it's working for you.
