### ISSUE TITLE
Missing gear indicator on renderdash dashboard

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#2343]
Repost from https://github.com/RigsOfRods/rigs-of-rods/pull/2341#issuecomment-480420285

0.4.7.0:
![image](https://user-images.githubusercontent.com/46073351/55656196-1c35b880-57c4-11e9-861f-70deb198e321.png)
latest master:
![image](https://user-images.githubusercontent.com/46073351/55656221-2d7ec500-57c4-11e9-9ad6-6a41ca5ca195.png)

**Comment by tritonas00** [comment]
which overlay is used in this case?
https://github.com/RigsOfRods/rigs-of-rods/blob/master/resources/overlays/3d_dashboard_needles.overlay
or
https://github.com/RigsOfRods/rigs-of-rods/blob/master/resources/overlays/needles.overlay?

**Comment by CuriousMike56** [comment]
They appear on an old build I have (34e760bc):
![image](https://user-images.githubusercontent.com/46073351/55675501-9ed87980-5891-11e9-8f41-b6d17613d55f.png)

**Comment by tritonas00** [comment]
it probably broke with ogre 1.11 update
https://github.com/RigsOfRods/rigs-of-rods/pull/1537#issuecomment-438031880
