### ISSUE TITLE
Spawning vehicle with existing custom particle crashes

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2344]
- Download [DAF-95XF-4x2-semi-air-suspension.zip](https://github.com/RigsOfRods/rigs-of-rods/files/3050951/DAF-95XF-4x2-semi-air-suspension.zip) and [DAF-95XF-6x4-semi-air-suspension.zip](https://github.com/RigsOfRods/rigs-of-rods/files/3050952/DAF-95XF-6x4-semi-air-suspension.zip)

- Spawn both trucks, doesn't matter in what order

- Game will crash with this error:
![image](https://user-images.githubusercontent.com/46073351/55675305-a21e3600-588e-11e9-98ba-f4af04c34a1d.png)

**Comment by only-a-ptr** [comment]
Until now I didn't have a mod with custom particles, thanks!

**Comment by tritonas00** [comment]
Spawn [PittsSpecial.zip](https://github.com/RigsOfRods/rigs-of-rods/files/3144727/PittsSpecial.zip) twice. Press `g` on both. Particles work only on the one spawned first

```
22:20:29: ItemIdentityException: An object of type 'ParticleSystem' with name 'cparticle-0-PittsSpecial' already exists. in SceneManager::createMovableObject at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreSceneManager.cpp (line 3894)
```

**Comment by only-a-ptr** [comment]
Current upstream will just show ingame notification instead of crashing, but the error remains.

**Comment by tritonas00** [comment]
https://github.com/RigsOfRods/rigs-of-rods/issues/2344#issuecomment-489357708 heavily affects multiplayer, only the first spawned actor can use particles (another example 2008 KME predator - use `g` to throw water)

**Comment by tritonas00** [comment]
is now fixed on master
