### ISSUE TITLE
Black gauge texture

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2346]
Using this vehicle: https://forum.rigsofrods.org/resources/coronado-sd.422/
![image](https://user-images.githubusercontent.com/46073351/56096271-13c03a80-5eb4-11e9-9687-26dfd5a7813d.png)
The gauge's material has its texture set to `dashtexture`, which was removed in https://github.com/RigsOfRods/rigs-of-rods/commit/39ed82855d78548380a01b28157c5abafc0f33f8:
```
material coronadosd-guages
{
    technique
    {
        pass
        {
            texture_unit
            {
                texture dashtexture
            }
        }
    }
}
```

**Comment by only-a-ptr** [comment]
Nice spot. I need to substitute "dashtexture" with the generated name here: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/physics/RigSpawner.cpp#L6412
