### ISSUE TITLE
Textures blacked when in interior views

### ISSUE THREAD

**Issue by TheBoxGamer41** [RigsOfRods/rigs-of-rods#2355]
In almost every vehicle I spawn, the interior views have everything blacked. I am using version 0.4.8. This happens on every map as well.
Chevy S10, Gavril MV4, Subaru Impreza Sedan.
![screenshot_2019-05-04_18-59-27_1](https://user-images.githubusercontent.com/50280904/57187116-464fc880-6e9f-11e9-8ba5-151a472cd4bd.png)
![screenshot_2019-05-04_18-59-43_1](https://user-images.githubusercontent.com/50280904/57187118-4bad1300-6e9f-11e9-8eb1-dfa3d3227767.png)
![screenshot_2019-05-04_18-59-53_1](https://user-images.githubusercontent.com/50280904/57187121-4f409a00-6e9f-11e9-826d-405c7c3444f7.png)

**Comment by CuriousMike56** [comment]
Upload your RoR.log (in Documents\Rigs of Rods 0.4\config)

**Comment by TheBoxGamer41** [comment]
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/3145055/RoR.log)

**Comment by CuriousMike56** [comment]
It's caused by texture shadows. Either disable them or use PSSM.
We need to just remove Texture shadows, they haven't worked since 0.3x.
