### ISSUE TITLE
Pink objects????

### ISSUE THREAD

**Issue by SuperMario93GD** [RigsOfRods/rigs-of-rods#2360]
Literally as it says. The Game either crashes or loads with a lot of pink textures. Is my hardware outdated??? Are my drivers dead?? Please help

**Comment by CuriousMike56** [comment]
Please upload your `RoR.log` (Located in Documents\Rigs of Rods 0.4\logs)

**Comment by only-a-ptr** [comment]
Hi @SuperMario93GD

Pink textures mean texture processing failed in RoR.

Please try it again and then go to 'Documents\Rigs of Rods 0.4\logs' and post 'RoR.log' here. Ideally, also post a screenshot.

**Comment by tritonas00** [comment]
related? https://forum.rigsofrods.org/threads/why-are-most-of-my-new-mods-pink.1476/

**Comment by CuriousMike56** [comment]
It's been almost 3 months without a reply. I think this can be closed.
