### ISSUE TITLE
actors wont spawn inside garage

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#2363]
Load nhelens go straight to the spawner door and spawn an actor. It should spawn inside the garage, instead it spawns in the door.

Because of this commit https://github.com/RigsOfRods/rigs-of-rods/commit/ab45d3d1e8c22882d6284b404c72e55ab3020ed4

**Comment by CuriousMike56** [comment]
Confirmed:
![image](https://user-images.githubusercontent.com/46073351/58202626-0c0b6700-7ca6-11e9-858e-e09b03498374.png)
![image](https://user-images.githubusercontent.com/46073351/58202640-1299de80-7ca6-11e9-9e56-e807892f3f76.png)
Also happens with the other spawners:
![image](https://user-images.githubusercontent.com/46073351/58202653-1cbbdd00-7ca6-11e9-9c4a-3e9b7da5c535.png)
![image](https://user-images.githubusercontent.com/46073351/58202668-22b1be00-7ca6-11e9-8f36-070be47b3dfb.png)
![image](https://user-images.githubusercontent.com/46073351/58202675-27767200-7ca6-11e9-92db-863774ef44c2.png)

**Comment by only-a-ptr** [comment]
> Because of this commit ab45d3d

THAT one? :flushed:

**Comment by tritonas00** [comment]
>THAT one?

lol, i was wrong, i will find the correct one

**Comment by tritonas00** [comment]
>THAT one?

Yep
