### ISSUE TITLE
Game crashes when opening the ingame settings

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#237]
When opening the ingame settings, the game will crash. It'll just "stay" in the menu and give me this error:

http://i.imgur.com/iPj9M6H.png

Wich log should I add or just all?

**Comment by Max98** [comment]
Didn't you say that this was fixed by itself? What's your computer's language?

**Comment by DirtGamer301** [comment]
Nope, the problem of going back into the menu game crash was solved by itself.

My PC language is german.

**Comment by only-a-ptr** [comment]
@DirtGamer301 / "crash was solved by itself" : Do you mean the crash no longer occurs? If yes, then please close this issue.
Anyway, it looks like a localization issue - what language are you using in RoR? Does language support even work in 0.4x?

Localization needs to be resolved after 0.4.5 is out.

**Comment by DirtGamer301** [comment]
Yes, the problem no longer occurs for no reason, I haven't changed anything it just was gone.
I use german in all RoR versions except NextStable because there's only "English (US)" avaible in RoRConfig and I can't go into the ingame settings.

**Comment by only-a-ptr** [comment]
The "Bad UTF-8 continuation byte" is a message coming from MyGUI. MyGUI uses wide strings (UCS-2) internally and converts+checks all strings to be displayed. In case there are invalid characters (can happen anytime, the game should sanitize inputs), it crashes like this.

This same issue keeps popping out again and again: 
* https://github.com/RigsOfRods/rigs-of-rods/issues/664
* https://github.com/RigsOfRods/rigs-of-rods/issues/385

**Comment by AdamCZ2** [comment]
why i cant even start a game maybe this game should go into trash...

**Comment by AdamCZ2** [comment]
what? i cant start a game and it pops that error
nobody can help me i knew that..
