### ISSUE TITLE
item clash error?

### ISSUE THREAD

**Issue by KinG-InFeT** [RigsOfRods/rigs-of-rods#2372]
![image](https://user-images.githubusercontent.com/193969/58982850-b7073f00-87d5-11e9-8177-79d00a817d25.png)

On Windows 10

**Comment by tritonas00** [comment]
describe please

**Comment by KinG-InFeT** [comment]
Excuse me I believed and described alone, essentially (I don't know if it is correct at this point) and not entering one inside the other

**Comment by tritonas00** [comment]
some actors do collide some not

**Comment by KinG-InFeT** [comment]
oh ok sorry for the false alert
