### ISSUE TITLE
Position logging doesn't output rotation 

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2379]
Pressing `h` normally will log the current coordinates:
```
Position: 875.549, 67.6607, 1155.26, 0, 366.073, 0
```

Now, however, the rotation output is always `0.0`:
```
Position: 1394.840,    0.201, 1306.390,    0.0,    0.0,    0.0
```

**Comment by tritonas00** [comment]
https://github.com/RigsOfRods/rigs-of-rods/blob/db39d08169e4b560ca7c59903cabf565ac927298/source/main/gameplay/RoRFrameListener.cpp#L1487-L1504
