### ISSUE TITLE
Cannot change time in Rigs of Rods

### ISSUE THREAD

**Issue by speiry2002** [RigsOfRods/rigs-of-rods#2384]
Ever since I updated to 4.8 I cannot change my time on my desktop. I have the same version on my laptop but I can change the time on that. I'm very confused.

**Comment by CuriousMike56** [comment]
Is the sky type set to Caelum or SkyX?

**Comment by tritonas00** [comment]
any update? @speiry2002

**Comment by speiry2002** [comment]
Yes the sky wasn’t set to Caelum it was set to Sandstorm.
