### ISSUE TITLE
Remove user token from RoR.log

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2386]
When a user token is set, this line is logged:
```
22:30:30: [RoR|GVar]       mp_player_token:  SetActive(), new: "token", old: ""
```
This poses a security risk as all someone would have to do is acquire the `RoR.log` (from e.g. our support channel) and paste that token into their settings in order to impersonate someone (or, even worse, a staff member). You're essentially handing out a password.
The line should either be removed from the log or a hashed version be logged instead.

**Comment by only-a-ptr** [comment]
Right away.

**Comment by tritonas00** [comment]
@only-a-ptr https://github.com/RigsOfRods/rigs-of-rods/pull/2387

**Comment by CuriousMike56** [comment]
Valid again:
```
[RoR|CVar]       mp_player_token:  SetPending(), new: "token", old: ""
```
