### ISSUE TITLE
Triggers cause a crash with OpenGL, not extending with DirectX

### ISSUE THREAD

**Issue by Aivar-RoR** [RigsOfRods/rigs-of-rods#239]
When the render system is set to DirectX, triggers cannot be extended nor retracted with commands/commands2. 
The command extends by a key press (you can hear sound playing), but the trigger doesn't.
When OpenGL rendering is used, the vehicle with triggers causes a crash as soon as it is spawned.
With both cases there are no errors in the log file.
Example vehicle: http://www.rigsofrods.com/repository/view/4812
This problem happens also with a vehicle I'm modding.

How to reproduce:
1. Download the vehicle from the link.
2. Select either Directx or OpenGL as the renderer, start RoR.
3. Spawn the vehicle, see what happens. 
4. If RoR doesn't crash, start the engine, select neutral gear. Press ALT+L to unlock the hook. Then press CTRL+F1/F2 to start the assembly process. 
Pressing this key combination should extend a command, that extends a trigger, which should trigger another command at its longbound, that should extend another trigger etc. Basically a key press should trigger a domino effect of triggers and commands.

Using Windows 7 64-bit

**Comment by only-a-ptr** [comment]
Umm... Using Win7, dx9, downloaded the vehicle, spawned it OK, entered it ... and then RoR melted down, I could only see the sky, HUD was going crazy and I couldn't exit the vehicle.
RoR.log didn't show anything suspicious.

I'm onto this....

**Comment by only-a-ptr** [comment]
@Aivar-RoR : Can you confirm this is actually an 0.4.0.7 bug? I tested with 0.4.0.7 release from Ulteq and the triggers didn't work - but I possibly missed something.

**Comment by Aivar-RoR** [comment]
On my machine the vehicle works fine in 0.4.0.7. (Build from this thread: http://www.rigsofrods.com/threads/105734-Version-0-4-0-7)
ALT+L to unlock the hook
press CTRL+F2 once to assemble the crane

**Comment by only-a-ptr** [comment]
@Aivar-RoR : Newbie question: how do I start engine and select gear with the crane? (per your instructios in initial post)
Anyway, I followed your last instructions - spawn, enter, ALT+L, CTRL+F2. I could hear the servo sound but nothing moved.
