### ISSUE TITLE
Hiding the "notice" window

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#240]
Just as the whole HUD can be hidden with "u" it'd be nice to hide the "notice" window, too.

**Comment by ulteq** [comment]
Do you want to prevent them pop up? Or do you only want to hide visible ones?

**Comment by DirtGamer301** [comment]
I honestly don't know, now that you ask that way. I first only thought about hiding after they popped up, but I think it'd make more sence to entirely not let them pop up when the Hud is hidden, too.

**Comment by disloyalpick** [comment]
@ulteq  Would it not be better to just make the HUD "invisible to screenshots?

**Comment by ulteq** [comment]
> Would it not be better to just make the HUD "invisible to screenshots?

That's already the case: https://github.com/RigsOfRods/rigs-of-rods/pull/669

But what if you want to record a video?

> I think it'd make more sence to entirely not let them pop up when the Hud is hidden, too.

I agree.
