### ISSUE TITLE
OIS.dll segfault after PMM 'update'

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#2407]
Since https://github.com/RigsOfRods/rigs-of-rods/pull/2402 I can't run RoR in Debug configuration... it will segfault when calling `OIS::InputManager::createInputSystem()`. 
```
Exception thrown at 0x00007FFACF58B391 (OIS.dll) in RoR.exe: 0xC0000005: Access violation reading location 0x0000000000000019.
```

Release configuration works OK. 

I'm baffled why and how it's hapenning. The libs used are the same as before. I made a clean cmake setup and collected all the logs I thought of. Platform: Windows10 x64, Visual Studio 2015, cmake 3.14.5, conan 1.16.0 (installed via PiP)
[Logs.zip](https://github.com/RigsOfRods/rigs-of-rods/files/3477352/ror.PMM.fail.zip)

**Comment by AnotherFoxGuy** [comment]
Same issue here: https://forum.rigsofrods.org/threads/rigs-of-rods-wont-start-on-windows-10-complied-from-source.1795/#post-7790

**Comment by AnotherFoxGuy** [comment]
The odd thing is that if you use Ninja it builds fine with the same libs

**Comment by AnotherFoxGuy** [comment]
The issue seems to be caused by using a release OIS.dll in debug (and the other way around)

**Comment by only-a-ptr** [comment]
> The issue seems to be caused by using a release OIS.dll in debug (and the other way around)

I checked that as a first thing and no, it links correctly:
```
>> Release: C:\Users\po185021\.conan\data\OGREdeps\2018-07\anotherfoxguy\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\lib\OIS.lib (conaninfo.txt: Release, x86_64)
>> Debug  : C:\Users\po185021\.conan\data\OGREdeps\2018-07\anotherfoxguy\stable\package\8cf01e2f50fcd6b63525e70584df0326550364e1\lib\OIS.lib (conaninfo.txt: Debug, x86_64)
```

**Comment by only-a-ptr** [comment]
With updated dependencies it seems to work fine. I'll reopen this if I observe anything unusual.

Still, let's avoid further updates to the build system until v0.4.8 is done.
