### ISSUE TITLE
I cannot find the opening file

### ISSUE THREAD

**Issue by hi123343** [RigsOfRods/rigs-of-rods#2411]
the game downloaded fine I just cannot seem to find the .exe or other opening file anywhere, so I cannot get into the game at all
<img width="839" alt="hi" src="https://user-images.githubusercontent.com/52575100/62833548-f2196900-bc83-11e9-8b06-3a6276f4498b.PNG">

**Comment by CuriousMike56** [comment]
You downloaded the source code. Download the installer from the home page instead: https://www.rigsofrods.org/
