### ISSUE TITLE
Switch from semver to rolling releases

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#2415]
Currently, we use the semver release format (0.38, 0.4)
I think it would be better to switch to date based, so we can release a new version when we think that it is stable enough
The reason I think it would be better is that the last "official" stable release was back in 2016 and that we now use the release candidates a stable releases 

Example of the new release format:

Old | New
---|---
0.37.126 | 2010-12
0.38.64 | 2011-10
0.4.5.0 | 2015-08
0.4.7.0 | 2016-11
0.4.8 RC5 | 2019-07

Thoughts?

**Comment by only-a-ptr** [comment]
I like it - it's a honest and straightforward match for the development style of RoR, where plans and schedules keep changing due to availability/fitness of (volunteer) devs and new/discovered bugs.
Also, it's not clear what 'RoR v1.0' should be like, so the numbers don't really mean anything. And I dislike when a feature-rich and pretty stable project still carries immature 'v0.x' version.
Also, all @AnotherFoxGuy's points above.

👍

**Comment by tritonas00** [comment]
Sounds good!

**Comment by only-a-ptr** [comment]
I figured we'll need to reflect this change in our 'home directory' on MS Windows, currently "MyDocuments\Rigs of Rods 0.4". The minimum we can do is to remove the '0.4' part.

However, we may also further re-think our data management for improved portability, see [SDL_filesystem.h / SDL_GetPrefPath()](http://hg.libsdl.org/SDL/file/default/include/SDL_filesystem.h#l65)

**Comment by AnotherFoxGuy** [comment]
> The minimum we can do is to remove the '0.4' part.

Removing the 0.4 will break older versions (0.38, 0.37, 0.36)

**Comment by AnotherFoxGuy** [comment]
There is also https://ogrecave.github.io/ogre/api/latest/class_ogre_1_1_file_system_layer.html#a0e606f77e2deb5961b8001cbdfe35e22

**Comment by only-a-ptr** [comment]
> Removing the 0.4 will break older versions (0.38, 0.37, 0.36)

RoR 0.3x used `MyDocuments\Rigs of Rods 0.38` IIRC

> Maybe move the folder to `My Games/Rigs of Rods`?

Windows has system directory `User\Myself\Saved Games`, is that what you mean? There's also `MyDocuments\My Games`, which I understand to be created by Steam, and thus we shouldn't mess with it.

**Comment by AnotherFoxGuy** [comment]
> `MyDocuments\My Games`, which I understand to be created by Steam, and thus we shouldn't mess with it.

The `My Games` isn't generated by steam, it is a common directory used to save games to (it is also used by Bethesda and Giant).

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy What's your source of information? Where is the screenshot from? I only found scattered mentions that "My Games" is some unspoken de-facto standard, but there is crazy confusion about it, some believe it's Windows builtin, others claim it's Steam.

I'm fine with using it, tho, there's no better alternative. I'm just disappointed how badly it's communicated by the game dev community (to my knowledge, anyway).

**Comment by AnotherFoxGuy** [comment]
> Where is the screenshot from?
The screenshot is from the My Games folder on my PC

**Comment by CuriousMike56** [comment]
I'm fine with `My Games/Rigs of Rods` as long the old folder can still be used for backwards compatibility with existing installs.

**Comment by only-a-ptr** [comment]
@CuriousMike56 How about RoR detecting if `MyDocuments\Rigs of Rods 0.4` is present, and if not, creating and using `MyGames\Rigs of Rods`?

@AnotherFoxGuy Can you code it in please?

**Comment by AnotherFoxGuy** [comment]
> @only-a-ptr  How about RoR detecting if `MyDocuments\Rigs of Rods 0.4` is present, and if not, creating and using `MyGames\Rigs of Rods`?
> 
> AnotherFoxGuy Can you code it in please?

Done: https://github.com/RigsOfRods/rigs-of-rods/pull/2422/commits/934868c9bcf079784df7ea94738b1d4e72200a60

**Comment by AnotherFoxGuy** [comment]
Personally, I find it a bad idea because we have changed a lot of things(Moved everything to mods, the config folder needs to be renamed) 
I think it is better to notify the user in the installer about the change

**Comment by CuriousMike56** [comment]
After some more thought, I agree. We've used `Documents\Rigs of Rods 0.4` for nearly 7 years now, I think it's time for a change. 
IMO the directory should be configurable - let the user decide where mods/configs should be stored.

**Comment by only-a-ptr** [comment]
Good! I also prefer to have only the `MyGames\Rigs of Rods` location from now on.

> @AnotherFoxGuy   (Moved everything to mods, 

I missed the moment it hapenned, but I like it. Modcache scans it recursively, so I can create whatever more dirs under it.

> @AnotherFoxGuy   the config folder needs to be renamed)

[This one?](https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/main.cpp#L83) Absolutely! I'm thinking "profile" or "user" ... ideas?

Also, final question: [merge now or release 0.4.8 first?](https://github.com/RigsOfRods/rigs-of-rods/pull/2422#issuecomment-529868193)

**Comment by AnotherFoxGuy** [comment]
> the config folder needs to be renamed

What I meant by this is that the 0.4.7 config folder isn't compatible with 0.4.8, so the 4.8 RC installers renamed the config folder to config.old  

> merge now or release 0.4.8 first?

I would say merge now
