### ISSUE TITLE
CMake generation fails

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2416]
(Win10 1903 x64, VS 2017, CMake 3.15.2, fresh `.conan` folder & RoR source)
Configuring seems to go ok. Clicking generate, however, fails with:
```
CMake Error at source/main/CMakeLists.txt:297 (add_executable):
  Cannot find source file:
 
    plugins/pagedgeometry/include/BatchPage.h
 
  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
 
 
CMake Error at source/main/CMakeLists.txt:297 (add_executable):
  No SOURCES given to target: RoR
```
Full log: https://pastebin.com/3T7H0nBZ

**Comment by tritonas00** [comment]
You did 'git clone --recursive' right?

**Comment by CuriousMike56** [comment]
> 
> 
> You did 'git clone --recursive' right?

No, just `git clone <url>`. I'm guessing the `--recursive` is required?

**Comment by tritonas00** [comment]
yes, paged geometry is a git submodule

**Comment by CuriousMike56** [comment]
Cloned again and now everything works, thanks!
