### ISSUE TITLE
Last selection ignoring sectionconfig

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2417]
* Download https://forum.rigsofrods.org/resources/unlimited-class-trophy-truck.89/ (Any vehicle with sections can be used, but this will appear as fresh in the selector)
* Open the vehicle selector, browse to the vehicle (not by searching) and spawn it, should spawn normally.
* Press ` CTRL+G` to open the selector again, the truck should already be highlighted.
* When you spawn it again, the body will be missing and the wheels are pink:
![image](https://user-images.githubusercontent.com/46073351/63196696-dd522200-c043-11e9-8e71-e50dc8b21909.png)
If you highlight another vehicle then go back to the truck,, it'll spawn normally.
Remembering the last selection was added by ulteq in https://github.com/RigsOfRods/rigs-of-rods/commit/65c1009039d3ae304ed5eec76e1d51b5fe801617

**Comment by only-a-ptr** [comment]
Selector again :frowning_face: I'm fed up with it's convoluted way of invading game state and re-launching itself for skins and whatnot. I'll just directly remake it with DearIMGUI and sensible architecture. Now that it looks like [there won't be a 'v0.4.8' but rather '2019-MM'](https://github.com/RigsOfRods/rigs-of-rods/issues/2415), I feel it's the best route to take.

Also there's couple things to decide:
* Should the last sectionconfig be remembered in ModCache (persistent between game sessions)? It's not hard to code.
* Same question for skin.

I checked how 'COMMON_RESPAWN_LAST_TRUCK' behaves - it will use both last skin and sectionconfig (only remembered until the map is unloaded), so this is fine.

**Comment by tritonas00** [comment]
> I'll just directly remake it with DearIMGUI and sensible architecture

:metal:

**Comment by CuriousMike56** [comment]
Appears to be fixed now
