### ISSUE TITLE
Upgrade imgui to OGRECave/ogre-imgui

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#2418]
See: https://github.com/RigsOfRods/rigs-of-rods/issues/2385#issuecomment-508946598

**Comment by only-a-ptr** [comment]
Closing as obsolete. OGRE 1.x now has an integrated ImGui support: https://www.ogre3d.org/2019/11/05/ogre-1-12-3-released
