### ISSUE TITLE
[Request] Rig Editor: Editing nodes on axle and undo steps

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#243]
Very helpful functions in other n/b or 3d editors are the function of changing the nodes position on only one axis and not freely in the world (Blender: G X/Y/Z) and undoing steps, for example if they're mistaken or something went wrong (CTRL+Z pretty much everywhere). They'd also be nice to be in the Rig Editor.

**Comment by only-a-ptr** [comment]
@DirtGamer301 : N/B editing in RigEditor is unfinished, it needs a lot more work
1. Axis-constrained moving: Quite easy to implement, expect soon
2. Undo (CTRL+Z): This will be hard, but it's a must to implement. Will take time.

Other stuff I'm going to add:
1. 3D cursor (Blender-like) to define plane on which new nodes are added
2. Function to add (not just delete) beams between existing nodes.
