### ISSUE TITLE
Default aircraft lights don't work anymore on 0.4.8

### ISSUE THREAD

**Issue by smo68** [RigsOfRods/rigs-of-rods#2430]
On the 0.4.7 version, every aircraft had default red and green navigation lights as well as flashing white strobe lights, but since I updated to 0.4.8, I figured out that these don't work anymore on any aircraft. You can try it on the default an12 : only the red flashing lights (these were added by the author I think) will turn on. Tell me how I can help more if needed

**Comment by only-a-ptr** [comment]
@tritonas00 Can you take a look please?
@smo68 Please post `RoR.log` so that I can see your hardware info and settings. Also, check you have flares enabled 😉

**Comment by tritonas00** [comment]
pressing `n` i can see the white lights above the whell
pressing `m` i only see the red flare above the plane blinking

**Comment by smo68** [comment]
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/3569931/RoR.log)
Here is my ror.log

**Comment by tritonas00** [comment]
@only-a-ptr this commit broke it https://github.com/RigsOfRods/rigs-of-rods/commit/59656d53c95a0984ae51f8452add796e8134751e
