### ISSUE TITLE
Strange hydro behavior with set_inertia_defaults

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2435]
Using this vehicle: https://forum.rigsofrods.org/resources/terex-rt-130.106/

When `set_inertia_defaults` is applied to hydros, if you steer full lock, let go of the key then reset the vehicle while the hydros are extending/contracting they will "snap" back to their previous position.

Video: https://streamable.com/6aoo2 (activated slow motion to easily see the problem)

This also affects [animators](https://docs.rigsofrods.org/vehicle-creation/fileformat-truck/#animators).
Possibly caused by https://github.com/RigsOfRods/rigs-of-rods/pull/2425

**Comment by only-a-ptr** [comment]
It's caused by 39a6b046d2a83ecd4cdececb39011c3573694b28, working on it
