### ISSUE TITLE
Not able to play RoR

### ISSUE THREAD

**Issue by DodgyRacer788** [RigsOfRods/rigs-of-rods#2437]
I have a issue with RoR not wanting to start and instead just crashing.

1. When opening RoR, it automaticly/instantly logs me into multiplayer (Neo queretaro)

2. Trying to reinstall the game isn't working because it will save my previous game. (options, multiplayer name etc.)

3. Only able to play when I'm disconnected from the internet.

**Comment by Zentro** [comment]
Close this. It's not bug related, he just didn't read the instructions on receiving the support.
