### ISSUE TITLE
Pic up/Pic down doesn't move the free camera anymore

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#244]
In 0.38, if you was in free camera and pressed pic up/down the camera moved straight up/down.
Since 0.4 this doesn't work anymore, including NextStable.

**Comment by only-a-ptr** [comment]
What exactly is Pic-up / Pic-down?
Anyway, this doesn't seem critical to me, labeling as POST-NextStable

**Comment by DirtGamer301** [comment]
https://upload.wikimedia.org/wikipedia/commons/f/f0/Bijoy_Keyboard_image.jpg
"Page up" "Page down" (Sorry, says "Bild" on my german keyboard and I just translated the word)
it's nothing critical just something I noticed.

**Comment by only-a-ptr** [comment]
@DirtGamer301 Thanks for the clarification.

I'll take a look at it, those controls seem useful.

**Comment by DirtGamer301** [comment]
It seems to work without problems in the latest release (0.4.5.1).
