### ISSUE TITLE
0.4.8.x Managed Materials Issues

### ISSUE THREAD

**Issue by 4x4convoy** [RigsOfRods/rigs-of-rods#2444]
Hello, today i am bringing this problem to github so it can hopefully be resolved. The issue is that the managed materials were changed after version 0.4.0.7 to support pssm shadows on vehicles and it kinda pretty much ruined the look of the things that use managed materials (so ALOT of mods lol). I propose to revert back to the managed materials used on 0.38.x versions (aka the nicemetal shaders) but with pssm support. Here are some examples of the differences.

![example #1](https://user-images.githubusercontent.com/19738859/64747219-5bd39f80-d4dc-11e9-8a50-5bc0578b90cd.png)
![example #2](https://user-images.githubusercontent.com/19738859/64747220-5bd39f80-d4dc-11e9-880d-38b20ce09f54.png)
![example #3](https://user-images.githubusercontent.com/19738859/64747222-5bd39f80-d4dc-11e9-8a7e-62b0a238c109.png)

**Comment by only-a-ptr** [comment]
What a well-formed issue ticket, thanks!

I have only very basic knowledge of shaders, so I'll be learning on-the-go here. I'll keep you posted.

**Comment by CuriousMike56** [comment]
I have successfully got Managedmaterials to use the 'NiceMetal' shader again:
https://github.com/CuriousMike56/rigs-of-rods/commit/3eb198ff2caf9fd700ebad4d89f27744fa237d4b
![screenshot_2019-09-16_22-30-44_1](https://user-images.githubusercontent.com/46073351/65007036-dc2a4400-d8d2-11e9-9238-31e7251dafa4.png)
Currently it works exactly the same as it did in 0.38-0.4.0.7, just doesn't receive shadows. 

If you want to try it out, download this zip:
[managed_materials_revert.zip](https://github.com/RigsOfRods/rigs-of-rods/files/3618992/managed_materials_revert.zip)

Browse to `C:\Program Files\Rigs of Rods\resources` (or wherever RoR is installed) and replace the `managed_materials` folder with the one inside the zip, deleting the old one first. I'd also recommend removing `managed_materials.zip` just to make sure.

**Comment by tritonas00** [comment]
love it!!
![kk](https://user-images.githubusercontent.com/2660424/65008776-23d0c000-d913-11e9-9e0e-00e62d885452.png)

**Comment by tritonas00** [comment]
> just doesn't receive shadows

@only-a-ptr 
![](https://media.giphy.com/media/cmrWcwC3A4ryH437Ru/giphy.gif)

**Comment by only-a-ptr** [comment]
@tritonas00 allright, allright!

@CuriousMike56 Please don't comment-out stuff, just delete it - it will remain in Git history anyway so you're basically just duplicating it.

**Comment by CuriousMike56** [comment]
@only-a-ptr I left those for reference - I'll  clean it up when I have time.

**Comment by CuriousMike56** [comment]
Updated original comment - should be ready for your magic now 😄

**Comment by only-a-ptr** [comment]
Darn! Such a simple revert and Mike beats me to it! 😄 
@CuriousMike56 👍 
https://github.com/only-a-ptr/rigs-of-rods/commit/b0bf362764094f595fd7f57411a1f06414ba88cb
![image](https://user-images.githubusercontent.com/491088/65292503-ffb1f080-db57-11e9-87f9-c063fa1b94f0.png)
