### ISSUE TITLE
[Request] adding command information back to the vehicles information

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#245]
Again, something I liked in the preview versions and has been removed, simply the commands information in the "T" menu wich makes using vehicles and commands much easier as you'll see wich commands exist for this vehicle and wich key(s) have to be pressed.

**Comment by Max98** [comment]
It's there.
Simulation -> Show vehicle description

**Comment by Hiradur** [comment]
It would be nice to have a hotkey for that.

**Comment by only-a-ptr** [comment]
I don't see any reason to remove such hotkey; labeling this BUG.
