### ISSUE TITLE
Content installation - user experience.

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#2450]
Currently RoR mods are in plain .ZIP archives and installing them means to manually put them to `MyDocuments\MyGames\Rigs of Rods\mods` - ideally without unzipping.

I got inspired to improve the process; when you open any [Rainmeter Widget page on DeviantArt](https://www.deviantart.com/rainmeter) and click download, you'll see:
![image](https://user-images.githubusercontent.com/491088/65637902-4f276f00-dfe5-11e9-89f1-48cdb0641727.png)

Further:
![image](https://user-images.githubusercontent.com/491088/65638535-9eba6a80-dfe6-11e9-8b83-60e2a890f30e.png)

The .rmskin is an ordinary .ZIP (deflate-mode), just renamed.

I'd like to install RoR mods like this, too: decide on a file extension like ".ror-pak" or ".rrpak" and add necessary bindings for the desktop environments.

END public note to self.

**Comment by disloyalpick** [comment]
The file extension could also be name like `.mod` or something like that?

**Comment by only-a-ptr** [comment]
@disloyalpick Nope, taken: https://en.wikipedia.org/wiki/MOD_(file_format)

**Comment by tritonas00** [comment]
i would like to see an in game "store"

an imgui panel that shows all content fron the official repo with thumbnails, with two buttons:
install -> download the selected mod zip into mods dir and update cache
remove ->  delete the zip and update cache

in my dreams lol

**Comment by CuriousMike56** [comment]
@tritonas00 Exactly what I think. The XenForo API allows for this.
