### ISSUE TITLE
On start: failed to generate list of installed content

### ISSUE THREAD

**Issue by WolkIlya2020** [RigsOfRods/rigs-of-rods#2458]
![Снимок](https://user-images.githubusercontent.com/51931512/66871859-422ae980-efad-11e9-84a3-3c1ec1d7bbec.PNG)
This pops up after loading.
I installed all additional trucks, cars, aircrafts, terrains, sea from the installer.
Version: 0.4.8
Windows : 7

**Comment by CuriousMike56** [comment]
You have special characters in your Windows username. See this workaround: https://docs.rigsofrods.org/gameplay/general-faq/#failed-to-generate-list-of-installed-content

**Comment by WolkIlya2020** [comment]
Thanks!
I changed the username before installation, but forgot to reboot the pc.

**Comment by tritonas00** [comment]
close this please, duplicate https://github.com/RigsOfRods/rigs-of-rods/issues/2353
