### ISSUE TITLE
Bring back 'help' panel

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2461]
Since the full ImGui transition is well underway, I figure now would be the best time to create this.

With the old dashboard (pre-0.39) you could set a 'help' texture to display controls/tips otherwise not shown, for example on the T813 DAKAR:
![t813_help](https://user-images.githubusercontent.com/46073351/67904692-838ecd80-fb45-11e9-93c6-d46086844c70.png)
https://docs.rigsofrods.org/vehicle-creation/fileformat-truck/#help

It would be nice to have this texture displayed again on the vehicle description (CTRL+T) window. Something like this (Obviously with ImGui instead):
![image](https://user-images.githubusercontent.com/46073351/67905369-7bd02880-fb47-11e9-8d21-1f59ef64dc7b.png)

**Comment by only-a-ptr** [comment]
👍 I absolutely intend to do this - precisely this way using the 'description' window - you beat me to present the idea by just few days. 😄

**Comment by only-a-ptr** [comment]
How's this?
![image](https://user-images.githubusercontent.com/491088/68231993-6aca6000-fffc-11e9-8857-4f633ce93b1a.png)
