### ISSUE TITLE
RoRBots arms don't move with the steering wheel

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#247]
As in 0.4 the arms of RoRBot move if you steer, they won't in NextStable.

![screenshot_3288](https://cloud.githubusercontent.com/assets/12358849/8024242/4ecb97a0-0d2d-11e5-8894-797cdab3f53b.jpg)
![screenshot_3289](https://cloud.githubusercontent.com/assets/12358849/8024244/526ef942-0d2d-11e5-826b-d073c16152eb.jpg)

**Comment by Hiradur** [comment]
The new RoRBot model may lack the animation for that

**Comment by DirtGamer301** [comment]
It works in 0.4.0.7.

**Comment by Hiradur** [comment]
We replaced it with another one
https://github.com/RigsOfRods/rigs-of-rods/commit/8218206afcc0aad20101392ce97f652fb2b494d0

**Comment by DirtGamer301** [comment]
Oh, it looked same so I just thought it's the same ^^

**Comment by only-a-ptr** [comment]
The RoRbot/vehicle interaction needs a complete overhaul.
* More options to control position/shape: Legs angle, arms angle, back lean angle.
* Options to tweak angle/rotation angle of the wheel. Currently, the hands never really match.
* RigEditor should provide visual handles to setup this.

I'm planning to do all this after 0.4.5

**Comment by only-a-ptr** [comment]
Handled by #1111
