### ISSUE TITLE
Custom Ground Model Settings for Meshes

### ISSUE THREAD

**Issue by danmackey** [RigsOfRods/rigs-of-rods#2471]
I would like to be able to add custom ground models that could be applied to meshes on terrains.

In the same way you would have a `name-landuse.cfg` and `name-groundmodel.cfg` to define custom ground models for the terrain itself, you would have the ability to use these defined ground models in an `.odef` file.  Custom ground models would be used as a variable in `stdfriction` or as a new tag, maybe `customfriction`?  I would expect this to apply the ground model across the entire mesh, just as `stdfriction` already does.

This would provide the same customization to large meshes as it would for entire terrains.

**Comment by CuriousMike56** [comment]
According to the source, It is possible to load a custom groundmodel/friction config: https://github.com/RigsOfRods/rigs-of-rods/blob/8bdbf723beb5e69dea7d7445f938dec8d30ff237/source/main/terrain/TerrainObjectManager.cpp#L909-L914
It's not documented anywhere and I haven't tried it myself, so I can't confirm if it works.

**Comment by danmackey** [comment]
Yeah this worked as intended. I used `frictionconfig name-groundmodel.cfg` and it loaded and work exactly as hoped.  Well that settles that, thanks!
