### ISSUE TITLE
Is there a way to prevent performance loss when coliding with other vehicle?

### ISSUE THREAD

**Issue by TheUnknownGuyFromRoR** [RigsOfRods/rigs-of-rods#248]
The issue is very well known- a massive performance loss when two vehicles are coliding. Is there a way to limit it? And will it need massive re-programming to work?

**Comment by Max98** [comment]
only_a_ptr found out that a vehicle A checks if it collides with B, but also B checks if it collides with A which is a problem. 
I believe that this is going to be fixed.

**Comment by only-a-ptr** [comment]
@TheUnknownGuyFromRoR : Yes, there is a way to limit it, and yes, it will need massive re-programming. I haven't analyzed the simulation code in depth, but here are some rough notes:
* Physics simulation in RoR is generally slow, the more N/B, the worse.
* When 2 vehicles get close, RoR launches detailed collision-detection, which takes it's toll.
* The bounding-box collision detection (detects whether vehicles are close) is pretty badly coded. This might be the reason why putting 3+ vehicles next to each other causes painful FPS death.
I'm preparing to improve performance in this area, but right now I'm busy with 0.4.5

**Comment by ulteq** [comment]
This should be much less of a problem after: https://github.com/RigsOfRods/rigs-of-rods/pull/466
