### ISSUE TITLE
Change the speedometer from the vehicles speed, to the wheel speed

### ISSUE THREAD

**Issue by 4x4convoy** [RigsOfRods/rigs-of-rods#2480]
Whenever the new GUI update happens I am suggesting to edit the speedometer on screen to display the vehicles actual wheel speed instead of the the vehicles speed. As of right now it acts like a gps would display speed irl, which is how fast the entire vehicle is moving along. Say while in game you put your vehicle up against the wall and start pressing the gas, the wheels will turn but the speedometer will still read 0 since the vehicle isn't moving. If you want to see how fast the wheels are turning you have to go into the "T" menu and look at the "Wheel Speed" number. This is kind of annoying when you're stuck in mud for example with the wheels spinning but the GUI is just reading 0 mph.

**Comment by only-a-ptr** [comment]
Agreed, the speedometer should be based on wheel speed rather than vehicle (actually cinecam#0) motion vector.
