### ISSUE TITLE
DearIMGUI feedback/bug reporting 

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2489]
With #2460 merged, I think it would be best to have one issue ticket for reporting bugs and providing feedback for the new UI. Feel free to post anything you might find or have general feedback/suggestions.

Selector:
- ~~Vehicle selector mouse scrolling doesn't work~~ fixed https://github.com/RigsOfRods/rigs-of-rods/pull/2499
- ~~Crashed when attempting to load (apparently) an invalid mini image for the Dodge Viper:
![image](https://user-images.githubusercontent.com/46073351/75124713-fedd3780-567e-11ea-84c9-85f2e79b5089.png)
Redownloading the mod fixed it, so can't reproduce it now, but still worth looking into?~~ fixed https://github.com/RigsOfRods/rigs-of-rods/pull/2536
- ~~If a vehicle has skins available, the default skin isn't an option. You have to select one.~~ fixed https://github.com/RigsOfRods/rigs-of-rods/pull/2496

Multiplayer:
-  ~~Pressing Y should display the full chat history (with scrolling). If someone says something to you while AFK, you won't see it.~~ https://github.com/RigsOfRods/rigs-of-rods/pull/2549

The following two are feature requests, could have their own separate ticket but since its UI related I think its fine here:

- When on an 'any terrain' server, possibility of displaying the terrain name in chat when a player joins and display it on the player list? This would prevent the constant "what map are you on" messages in any servers. Might require ror-server changes.
- When spawning a new vehicle, the game should display in your chat if others have the same mod installed. The arrows next to names in the player list show this, but most players don't know what they mean.

Overview map:
- ~~The map isn't scaled correctly, causing teleports to not work and icons to not appear correctly:~~ fixed https://github.com/RigsOfRods/rigs-of-rods/pull/2504 and https://github.com/RigsOfRods/rigs-of-rods/pull/2563/commits/cc17e33029fe274c34693d7d28e9a4582c4177d1
- ~~Terrains with no heightmap displays nothing on the large map:
Example terrain: http://sim-monsters.com/files/file/3300-anaheim-2020-red-show-1/~~ fixed https://github.com/RigsOfRods/rigs-of-rods/pull/2504

Other:
- Angelscript log should be hidden:
![image](https://user-images.githubusercontent.com/46073351/75307789-9a56df80-581a-11ea-9640-a4dee27928c1.png)
- CTRL+T window command underscores should be replaced with spaces
- ~~Vehicle weight in T-menu always displays 0~~ fixed https://github.com/RigsOfRods/rigs-of-rods/pull/2505

> 
> 
> ~~@CuriousMike56: I don't want colorized mod names (or server names, nicknames or any other user-controlled strings). It's disruptive and liable to conflict with built-in coloring (actor list in multiplayer for example).~~
> 
> ~~I didn't even know it was possible before - I'll just strip the tags from mod names in the parser.~~

~~@only-a-ptr That's fine by me, but Sim-Monsters probably isn't going to be very happy ¯\_(ツ)_/¯~~
fixed https://github.com/RigsOfRods/rigs-of-rods/pull/2614

**Comment by tritonas00** [comment]
I can fix some of these here https://github.com/RigsOfRods/rigs-of-rods/pull/2488
> Hide warnings/errors by default

They already hidden in chat. Do you mean in console also?

**Comment by CuriousMike56** [comment]
> 
> 
> > Hide warnings/errors by default
> 
> They already hidden in chat. Do you mean in console also?

@tritonas00 Not all errors are hidden:
![image](https://user-images.githubusercontent.com/46073351/75172743-b9ab1b00-56fb-11ea-9f1b-29f9cf33e715.png)

**Comment by tritonas00** [comment]
fixed (hopefully) in https://github.com/RigsOfRods/rigs-of-rods/pull/2488

**Comment by CuriousMike56** [comment]
> > Pressing Y should display the full chat history (with scrolling). If someone says something to you while AFK, you won't see it.
> 
> You can see them in console

I know, but the average player doesn't know about or will be using the console. That's not user friendly at all. The 0.38-era chatbox displays the full chat history.

**Comment by CuriousMike56** [comment]
Post updated.

**Comment by tritonas00** [comment]
@CuriousMike56 how does those look?

![kk](https://user-images.githubusercontent.com/2660424/75335943-fd845880-5892-11ea-8502-ef855d304cf4.png)
![kk](https://user-images.githubusercontent.com/2660424/75336006-12f98280-5893-11ea-8dfd-153922b0b633.png)
![kk](https://user-images.githubusercontent.com/2660424/75336065-27d61600-5893-11ea-9b9c-7e46a5a5e601.png)
![kk](https://user-images.githubusercontent.com/2660424/75336187-59e77800-5893-11ea-9123-c096bdb9f16f.png)
![kk](https://user-images.githubusercontent.com/2660424/75336225-6d92de80-5893-11ea-960f-9c8462dba963.png)

Is it too much?

**Comment by CuriousMike56** [comment]
The server list and settings are a bit too much, others look great 👍

**Comment by tritonas00** [comment]
Ok 0.85 seems ok for all windows, done https://github.com/RigsOfRods/rigs-of-rods/pull/2488/commits/0884e4ef9224a07d338ff74a064dcb2bf06cffa0

**Comment by only-a-ptr** [comment]
Thanks for all the attention guys 👍 Misc notes:

* I'll fix the mousewheel-scrolling after OGRE upgrade - OGRE 1.12.3+ has built-in imgui, so input handling will change anyway.

* I'll add a CVar 'gfx_colored_names' to enable or disable (just remove the tags) colored mod names in selector.

* I'll look at #2488 on weekend

**Comment by tritonas00** [comment]
> Angelscript log should be hidden:

apparently we need it for the races

**Comment by tritonas00** [comment]
Hiding the UI should permanently hide the chat. The main complaint about the current chat box is that it reappears for every new message.

done https://github.com/RigsOfRods/rigs-of-rods/pull/2488/commits/b1ba7cd90d8429e277e40531830537e5baa974c3

**Comment by tritonas00** [comment]
> If you type a console command (e.g. help) then close the console, the output will be displayed as a notification instead. It should stay in the console.

https://github.com/RigsOfRods/rigs-of-rods/pull/2495

and 

> If you don't have the mod a player spawned, the "Mod not installed: name.truck" message isn't displayed

is already fixed in master

**Comment by tritonas00** [comment]
Everything is resolved now, feel free to open a new issue with the requests.
