### ISSUE TITLE
cycling through cameras broken in snap environment

### ISSUE THREAD

**Issue by paroj** [RigsOfRods/rigs-of-rods#2491]
```
sudo snap install rigs-of-rods --edge
```
![version](https://user-images.githubusercontent.com/4941802/75987520-589bf800-5ef0-11ea-8264-5fa72b0293e0.png)

1. start a game
2. press c to cycle through cameras
3. after first person view image becomes permanently black

2020.01 tag (--stable) works fine

**Comment by tritonas00** [comment]
Strange, works fine here (archlinux, latest master)

**Comment by paroj** [comment]
some more details:
- while in car cycling back to first person view is possible, with the ror guy camera stays black
- getting a new vehicle from first person view, properly resets the camera

**Comment by paroj** [comment]
> Strange, works fine here (archlinux, latest master)

maybe its the combination with the deps. Do you have the chance to test the snap?

**Comment by tritonas00** [comment]
no, sorry but you can try https://rigs-of-rods.itch.io/rigs-of-rods-dev (run the RunRoR script, its a precompiled RoR with bundled dependencies.

**Comment by paroj** [comment]
according to the stats there were 2 arch users active in the past 30 days, so maybe it works.

I tried the itch build and the issue is not present there. To narrow down the difference I replaced all shipped deps by the libs from the snap and the issue only appeared after swapping the main executable.

The core difference here is that the snap is built with `-DUSE_PACKAGE_MANAGER=FALSE` and hence without discord rpc.

**Comment by tritonas00** [comment]
> The core difference here is that the snap is built with -DUSE_PACKAGE_MANAGER=FALSE and hence without discord rpc.

hm, i build it like that also. Must be a compiler flag or something

**Comment by paroj** [comment]
@tritonas00 maybe this: https://github.com/RigsOfRods/rigs-of-rods/pull/2570

**Comment by tritonas00** [comment]
@paroj i can take a look on missing includes, but i don't see how that could be related

**Comment by paroj** [comment]
> i can take a look on missing includes, but i don't see how that could be related

I dont know what *cotire* is doing exactly, but it can influence the semantics of the source code. E.g. the unity build combines multiple source files into one which extends the scope of `static` and also influences template resolution (SFINAE). Similar things can also happen with precompiled headers.

The itch build works, as we already discussed earlier. However, it would be nice if ror could be also built on machines that do not resemble the CI exactly..

**Comment by paroj** [comment]
I brought this up here again as I did a snap rebuild of the `2020.01` tag where I noticed missing includes. So some change inside snap must have broken `cotire`. This in turn made me suspicios what else cotire might be hiding..

**Comment by tritonas00** [comment]
@paroj https://github.com/RigsOfRods/rigs-of-rods/pull/2572 allowed me to build RoR under Arch without cotire

**Comment by tritonas00** [comment]
Want to try out the snap package but

```
error: too early for operation, device not yet seeded or device model not acknowledged
```

**Comment by tritonas00** [comment]
I tried the snap package, and yes i got the black camera issue.

**Comment by paroj** [comment]
I was hesitant to compile without snapcraft, as getting all the dependencies right is a PITA without the container-like environment or conan. But now that I have run out of other ideas..

- actually compiling RoR that way works with no issues.
- also copying out the binary out of the snap and using it works
- same for copying Ogre and the other RoR deps from the snap

is there some environment variable or something?

what is even more strange, is that:

```
sudo snap install rigs-of-rods --stable
```

works. So that must have been introduced between january and march.

**Comment by tritonas00** [comment]
> getting all the dependencies right is a PITA
Not actually, also no conan needed. I use https://github.com/RigsOfRods/ror-dependencies, nice and simple

So the issue is snap only. Can you try to re compile the stable version with snap and check?
I also suspect an env variable.

**Comment by paroj** [comment]
> Maybe a snap update causes the issue?

the `--stable` (2020.01) and `--edge` (2020.06) snaps were built on the same day, as I had to fix a bug in --stable.

> I also suspect an env variable, but which one?

you can get into the snap container with

```sh
snap run --shell rigs-of-rods
# then
env # shows you all environment vars
```
however, I did not see anything suspicious there..

**Comment by tritonas00** [comment]
@paroj can you try with current master?

**Comment by paroj** [comment]
the initial local snap build seems to work. Lets wait for the buildserver to confirm.

However, could you drop the cmake requiremets to at leat 3.10 again and rather check the available version to set USE_PHC?

The snapcraft environment only has 3.10 and I have to patch ror to build it.. :cry:

**Comment by paroj** [comment]
snapcraft.io build works as well
