### ISSUE TITLE
[Bug] Test Build 4.5.0 Ties/Ropables Broken 

### ISSUE THREAD

**Issue by UCDHIUS** [RigsOfRods/rigs-of-rods#252]
Ties/Ropables broken in the current [Test Build 4.5.0] cannot tie down/lock down vehicles/loads on trailers.

**Comment by only-a-ptr** [comment]
@UCDHIUS: Please describe your test scenarios (detailed, including controls used) and post links to vehicles/loads you tested with. Thanks.

**Comment by only-a-ptr** [comment]
Ties/Ropables are working again in TestBuild 4
http://www.rigsofrods.com/threads/119110-Test-Build-Rigs-of-rods-0-4-5-0-dev?p=1384293&viewfull=1#post1384293
