### ISSUE TITLE
Conan install failed

### ISSUE THREAD

**Issue by pslat** [RigsOfRods/rigs-of-rods#2523]
Hi, I followed the instructions here https://github.com/RigsOfRods/rigs-of-rods/wiki/Compile-(Linux) 
and ran 
`cmake -GNinja -DCMAKE_BUILD_TYPE=Release`
(-also tried 'Debug', 'MinSizeRel', 'None', 'RelWithDebInfo' with the same results.)
but cannot get past the error:
`CMake Error at _pmm/1.9.2/conan.cmake:488 (message):
  Conan install failed [1]:

Call Stack (most recent call first):
  _pmm/1.9.2/conan.cmake:524 (_pmm_conan_run_install)
  _pmm/1.9.2/conan.cmake:690 (_pmm_conan_install)
  _pmm/1.9.2/main.cmake:36 (_pmm_conan)
  _pmm/1.9.2/main.cmake:57 (_pmm_project_fn)
  cmake/DependenciesConfig.cmake:20 (pmm)
  CMakeLists.txt:99 (include)

-- Configuring incomplete, errors occurred!
See also "/home/paul/dev/rigs-of-rods/CMakeFiles/CMakeOutput.log".
See also "/home/paul/dev/rigs-of-rods/CMakeFiles/CMakeError.log".
`
conan is installed and I can type conan from that directory and get the expected help output 
Can you help with this? None of the suggestions I have tried re conan have helped.

### System configuration
OS: e.g. Kubuntu 18.04 64-bit
Renderer used: OpenGL
[CMakeError.log](https://github.com/RigsOfRods/rigs-of-rods/files/4415470/CMakeError.log)
[CMakeOutput.log](https://github.com/RigsOfRods/rigs-of-rods/files/4415471/CMakeOutput.log)

**Comment by AnotherFoxGuy** [comment]
Could you post the full output of the cmake command?

**Comment by pslat** [comment]
Ok @AnotherFoxGuy , I thought that was in the attached log file, here it is:

`~/dev/rigs-of-rods$ cmake -GNinja -DCMAKE_BUILD_TYPE=Release
-- [pmm] Installing Conan requirements from /home/paul/dev/rigs-of-rods/conanfile.txt
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
CC=/usr/bin/cc
CXX=/usr/bin/c++
conanfile.txt: Installing package
Requirements
    AngelScript/2.32@anotherfoxguy/stable from 'ror-dependencies' - Cache
    MofileReader/1.0.0@anotherfoxguy/stable from 'ror-dependencies' - Cache
    MyGUI/3.2.3-OGRE-1.11.6-with-patches@anotherfoxguy/stable from 'ror-dependencies' - Cache
    OGRE/1.11.6-with-patches@anotherfoxguy/stable from 'ror-dependencies' - Cache
    OGREdeps/20.19.4@anotherfoxguy/stable from 'ror-dependencies' - Cache
    OpenSSL/1.1.1c@conan/stable from 'conan-center' - Cache
    SocketW/3.10.36@anotherfoxguy/stable from 'ror-dependencies' - Cache
    discord-rpc/3.4.0@AnotherFoxGuy/stable from 'ror-dependencies' - Cache
    libalsa/1.1.5@conan/stable from 'conan-center' - Cache
    libcurl/7.61.1@bincrafters/stable from 'conan-center' - Cache
    ogre-caelum/0.6.3-p1@anotherfoxguy/stable from 'ror-dependencies' - Cache
    openal/1.19.0@bincrafters/stable from 'conan-center' - Cache
    rapidjson/1.1.0@bincrafters/stable from 'conan-center' - Cache
    zlib/1.2.11@conan/stable from 'conan-center' - Cache
Packages
    AngelScript/2.32@anotherfoxguy/stable:9bfdcfa2bb925892ecf42e2a018a3f3529826676 - Cache
    MofileReader/1.0.0@anotherfoxguy/stable:9bfdcfa2bb925892ecf42e2a018a3f3529826676 - Cache
    MyGUI/3.2.3-OGRE-1.11.6-with-patches@anotherfoxguy/stable:9ba67900671fa6eb1347ecfd614c07fdbcf4d3b2 - Build
    OGRE/1.11.6-with-patches@anotherfoxguy/stable:9bfdcfa2bb925892ecf42e2a018a3f3529826676 - Build
    OGREdeps/20.19.4@anotherfoxguy/stable:9bfdcfa2bb925892ecf42e2a018a3f3529826676 - Build
    OpenSSL/1.1.1c@conan/stable:b781af3f476d0aa5070a0a35b544db7a3c193cc8 - Cache
    SocketW/3.10.36@anotherfoxguy/stable:c4f9c455510be85e79a0cca0c8ebab83e1327e56 - Build
    discord-rpc/3.4.0@AnotherFoxGuy/stable:9bfdcfa2bb925892ecf42e2a018a3f3529826676 - Build
    libalsa/1.1.5@conan/stable:bff9a7d5ab267a535181ec5b36392417340ff035 - Cache
    libcurl/7.61.1@bincrafters/stable:ce65897ce836adb3eb34ee8ea84017665908a349 - Cache
    ogre-caelum/0.6.3-p1@anotherfoxguy/stable:9ba67900671fa6eb1347ecfd614c07fdbcf4d3b2 - Build
    openal/1.19.0@bincrafters/stable:812e1deb664b70de9456fc54c225f826fbca36e7 - Cache
    rapidjson/1.1.0@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    zlib/1.2.11@conan/stable:d50a0d523d98c15bb147b18fa7d203887c38be8b - Cache

Installing (downloading, building) binaries...
AngelScript/2.32@anotherfoxguy/stable: Already installed!
MofileReader/1.0.0@anotherfoxguy/stable: Already installed!
OGRE/1.11.6-with-patches@anotherfoxguy/stable: Copying sources to build folder
OGRE/1.11.6-with-patches@anotherfoxguy/stable: Building your package in /home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676
OGRE/1.11.6-with-patches@anotherfoxguy/stable: Generator cmake_paths created conan_paths.cmake
OGRE/1.11.6-with-patches@anotherfoxguy/stable: Calling build()
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring OGRE 1.11.6
-- Check size of void*
-- Check size of void* - done
-- Performing Test OGRE_GCC_HAS_SSE
-- Performing Test OGRE_GCC_HAS_SSE - Success
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Search path: /home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676;/home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676/Dependencies;/home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676/Dependencies;/home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676/../Dependencies;/home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676/../Dependencies
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Looking for ZZip...
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'zziplib'
--   Found zziplib, version 0.13.62
-- Found ZZip: /usr/lib/x86_64-linux-gnu/libzzip.so
-- Looking for FreeImage...
-- Checking for module 'freeimage'
--   No package 'freeimage' found
-- Found FreeImage: /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.8.1") 
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Looking for Cg...
-- Cg_PREFIX_PATH changed.
-- Checking for module 'Cg'
--   No package 'Cg' found
-- Found Cg: /usr/lib/x86_64-linux-gnu/libCg.so
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.17") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR) 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Looking for Softimage...
-- Softimage_PREFIX_PATH changed.
-- Could not locate Softimage
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Warning at Components/Bites/CMakeLists.txt:130 (message):
  SDL2 not found - no input handling and reduced window creation capabilites


-- 
-----------------------------------------------------------------------------
-- The following external packages were located on your system.
-- This installation will have the extra features provided by these packages.
+ zlib
+ zziplib
+ freeimage
+ freetype
+ X11
+ Xaw
+ OpenGL
+ cg
+ Python
-----------------------------------------------------------------------------
-- The following OPTIONAL packages could NOT be located on your system.
-- Consider installing them to enable more features from this software.
+ OpenGL ES 2.x: Support for the OpenGL ES 2.x render system <http://www.khronos.org/opengles/>
+ OpenEXR: Load High dynamic range images <http://www.openexr.com/>
+ SDL2: Simple DirectMedia Library needed for input handling in samples <https://www.libsdl.org/>
+ Doxygen: Tool for building API documentation <http://doxygen.org>
+ Softimage: Softimage SDK needed for building XSIExporter <FALSE>
-----------------------------------------------------------------------------

-- 
----------------------------------------------------------------------------
  FEATURE SUMMARY
----------------------------------------------------------------------------

Building components:
  + Bites
  + HLMS [BETA]
  + MeshLodGenerator
  + Overlay
  + Paging
  + Property
  + RTShader System
  + RTShader System Core Shaders
  + RTShader System Extensions Shaders
  + Terrain
  + Volume
Building plugins:
  + BSP scene manager
  + Cg program manager
  + Octree scene manager
  + FreeImage codec (generic)
  + Portal connected zone scene manager
  + Particle FX
Building rendersystems:
  + OpenGL
Building executables:
  + Tools
Building core features:
  + Mesh Lod
  + DDS image codec (.dds)
  + ETC image codec (.pkm, .ktx) 
  + ZIP archives

Build type:                      shared
Thread safety:                   none
ResourceManager behaviour:       legacy [DEPRECATED]
Use double precision:            disabled
Nodes inherit transform:         disabled
Assert mode:                     release exceptions

----------------------------------------------------------------------------

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OPENGL_gl_LIBRARY (ADVANCED)
    linked by target "OgreGLSupport" in directory /home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676/RenderSystems/GLSupport
    linked by target "RenderSystem_GL" in directory /home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676/RenderSystems/GL

-- Configuring incomplete, errors occurred!
See also "/home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676/CMakeFiles/CMakeOutput.log".
See also "/home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676/CMakeFiles/CMakeError.log".
OGRE/1.11.6-with-patches@anotherfoxguy/stable: 
WARN: SocketW/3.10.36@anotherfoxguy/stable: requirement OpenSSL/1.1.1b@conan/stable overridden by your conanfile to OpenSSL/1.1.1c@conan/stable 
WARN: ogre-caelum/0.6.3-p1@anotherfoxguy/stable: requirement OGRE/1.11.6@anotherfoxguy/stable overridden by your conanfile to OGRE/1.11.6-with-patches@anotherfoxguy/stable 
OGRE/1.11.6-with-patches@anotherfoxguy/stable: WARN: Package is corrupted, removing folder: /home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/package/9bfdcfa2bb925892ecf42e2a018a3f3529826676
OGRE/1.11.6-with-patches@anotherfoxguy/stable: WARN: Build folder is dirty, removing it: /home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676
OGRE/1.11.6-with-patches@anotherfoxguy/stable: ERROR: Package '9bfdcfa2bb925892ecf42e2a018a3f3529826676' build failed
OGRE/1.11.6-with-patches@anotherfoxguy/stable: WARN: Build folder /home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676
ERROR: OGRE/1.11.6-with-patches@anotherfoxguy/stable: Error in build() method, line 79
        cmake.configure()
        ConanException: Error 1 while executing cd '/home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676' && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="7" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DCONAN_LIBCXX="libstdc++11" -DCMAKE_INSTALL_PREFIX="/home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/package/9bfdcfa2bb925892ecf42e2a018a3f3529826676" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DOGRE_BUILD_DEPENDENCIES="OFF" -DOGRE_BUILD_COMPONENT_CSHARP="OFF" -DOGRE_BUILD_COMPONENT_JAVA="OFF" -DOGRE_BUILD_COMPONENT_PYTHON="OFF" -DOGRE_BUILD_PLUGIN_STBI="OFF" -DOGRE_BUILD_COMPONENT_BITES="ON" -DOGRE_BUILD_SAMPLES="OFF" -DOGRE_BUILD_RENDERSYSTEM_D3D9="ON" -DOGRE_BUILD_RENDERSYSTEM_D3D11="ON" -DOGRE_BUILD_RENDERSYSTEM_GL3PLUS="OFF" -DOGRE_RESOURCEMANAGER_STRICT="0" -DOGRE_INSTALL_SAMPLES="OFF" -Wno-dev '/home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676'
CMake Error at _pmm/1.9.2/conan.cmake:488 (message):
  Conan install failed [1]:

Call Stack (most recent call first):
  _pmm/1.9.2/conan.cmake:524 (_pmm_conan_run_install)
  _pmm/1.9.2/conan.cmake:690 (_pmm_conan_install)
  _pmm/1.9.2/main.cmake:36 (_pmm_conan)
  _pmm/1.9.2/main.cmake:57 (_pmm_project_fn)
  cmake/DependenciesConfig.cmake:20 (pmm)
  CMakeLists.txt:99 (include)


-- Configuring incomplete, errors occurred!
See also "/home/paul/dev/rigs-of-rods/CMakeFiles/CMakeOutput.log".
See also "/home/paul/dev/rigs-of-rods/CMakeFiles/CMakeError.log".`

**Comment by tritonas00** [comment]
@pslat have you tried the the precompiled zip archive?

**Comment by pslat** [comment]
Yes @tritonas00, the precompiled archive works fine on the same machine.

**Comment by tritonas00** [comment]
`cmake -GNinja -DCMAKE_BUILD_TYPE=Release` seems to work fine in Arch

can you delete your `~.local/share/pmm` and `~.conan` and try fresh?

**Comment by pslat** [comment]
@tritonas00 sorry for the slow reply, I had switched to a new Linux install but I hadn't set up all development packages on it and didn't get a chance to try your suggestion. I will boot into the older system over the weekend and try this thank you. I'll let you know if that works.

**Comment by pslat** [comment]
Hi @tritonas00 I deleted ~.local/share/pmm and ~.conan and get the same results. I tried installing extra dev packages but cannot find Softimage. 
This seems to be an ogre problem but at this stage I'm ready to move on.

As a last attempt I notably get two messages from make ogre:
> CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
and
> /usr/bin/ld: cannot find -lpthreads


Here is the ogre CMakeError.log

> Determining if the pthread_create exist failed with the following output:
Change Dir: /home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_5f127/fast"
/usr/bin/make -f CMakeFiles/cmTC_5f127.dir/build.make CMakeFiles/cmTC_5f127.dir/build
make[1]: Entering directory '/home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_5f127.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_5f127.dir/CheckSymbolExists.c.o   -c /home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_5f127
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_5f127.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_5f127.dir/CheckSymbolExists.c.o  -o cmTC_5f127 
CMakeFiles/cmTC_5f127.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_5f127.dir/build.make:97: recipe for target 'cmTC_5f127' failed
make[1]: *** [cmTC_5f127] Error 1
make[1]: Leaving directory '/home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_5f127/fast' failed
make: *** [cmTC_5f127/fast] Error 2

File /home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_8e6f1/fast"
/usr/bin/make -f CMakeFiles/cmTC_8e6f1.dir/build.make CMakeFiles/cmTC_8e6f1.dir/build
make[1]: Entering directory '/home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_8e6f1.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_8e6f1.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_8e6f1
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8e6f1.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_8e6f1.dir/CheckFunctionExists.c.o  -o cmTC_8e6f1 -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_8e6f1.dir/build.make:97: recipe for target 'cmTC_8e6f1' failed
make[1]: *** [cmTC_8e6f1] Error 1
make[1]: Leaving directory '/home/paul/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/9bfdcfa2bb925892ecf42e2a018a3f3529826676/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_8e6f1/fast' failed
make: *** [cmTC_8e6f1/fast] Error 2

>

**Comment by tritonas00** [comment]
@pslat any update? Is it working now?

**Comment by pslat** [comment]
@tritonas00 I gave up in May last year and since then i have a different development pc with Kubuntu 20.04 so I'd have to start the process again. If I get a chance I might try compile it over the weekend and I'll let you know. I'd forgotten all about this..

**Comment by only-a-ptr** [comment]
Closing as outdated, see above comment
