### ISSUE TITLE
Option to disable the self-cancelling feature of turn signals

### ISSUE THREAD

**Issue by MarkROR** [RigsOfRods/rigs-of-rods#2527]
When driving any vehicle that requires constant steering inputs just to go straight, these minor inputs are enough to trigger the self-cancelling of turn signals/indicators, before taking the actual turn.

It would be nice to have a setting to disable this feature, or to improve it so it doesn't trigger unless the steering wheel is turned enough and then returned to center (I assume this is already in place, so maybe just increase the degrees of turn required, while keeping in mind wide turns are a thing)

**To see this in action**: any map, any car (St Helens, Honda Accord) - drive in a straight line without any steering input, turn either of the indicators on, perform the slightest steering input in that direction. The indicator will be cancelled when you return the wheel to center.

**What should happen**: the indicator should remain on until the steering angle reaches a certain (TBD) treshold, and when the steering is straightened again, only then it should cancel the indicator.

**Comment by tritonas00** [comment]
probably https://github.com/RigsOfRods/rigs-of-rods/blob/4f8658fcd653bda8f0ebea05760fc9adf05a13c7/source/main/physics/Beam.cpp#L3168

**Comment by CuriousMike56** [comment]
https://github.com/RigsOfRods/rigs-of-rods/blob/4f8658fcd653bda8f0ebea05760fc9adf05a13c7/source/main/physics/Beam.cpp#L3165-L3194

**Comment by tritonas00** [comment]
You can now adjust blinker lock range in Settings->Controls tab
