### ISSUE TITLE
Flextires broken in Multiplayer

### ISSUE THREAD

**Issue by Dogy144** [RigsOfRods/rigs-of-rods#253]
In multiplayer of versions 0.38.67 through 0.4.0.7, there is a bug with flextires. It is pretty indescribable as to what the bug is, so I have included a video of the bug. For recreation purposes, use grasonk95's HDX (http://www.rigsofrods.com/repository/view/4499) or any other vehicle with flextires in multiplayer. I am not really sure if this is fixed in 0.4.5.0 as multiplayer is disabled.

Video:
https://youtu.be/LTPTSwS5D3E

**Comment by Hotrod55** [comment]
Any plan on fixing this in time for the 4.0.6.0 release? :D
