### ISSUE TITLE
Import into Blender switches x and y axes

### ISSUE THREAD

**Issue by grahamjamesaddis** [RigsOfRods/rigs-of-rods#2531]
Using the Blender importer the X and Y axes are swapped.

https://github.com/RigsOfRods/rigs-of-rods/blob/master/tools/blender/ror_import.py

The exporter swaps them back so when used together there is no issue.

Is this done on purpose?

**Comment by grahamjamesaddis** [comment]
Actually it's a little more complex:
Blender X -> Truck Z
Blender Y -> Truck X
Blender Z -> Truck Y

To illustrate this I manually created a simple object in blender.

Nodes at the following locations:
0,0,0,0
1,1,0,0
2,0,2,0
3,0,0,3

When I export this the node file contains the following:

nodes
0,    0.000,    0.000,    0.000, n
1,    0.000,    0.000,    1.000, n
2,    2.000,    0.000,    0.000, n
3,    0.000,    3.000,    0.000, n

beams
0, 1, v
0, 3, v
1, 2, v
2, 0, v
3, 1, v
3, 2, v

cab
2, 1, 3, c
3, 1, 0, c
0, 2, 3, c
0, 1, 2, c

Blender file and truck file attached in the following zip.

[a.zip](https://github.com/RigsOfRods/rigs-of-rods/files/4473331/a.zip)

**Comment by CuriousMike56** [comment]
Is this solved? 
https://forum.rigsofrods.org/threads/confusion-with-blender-vs-ror-axes.2473

**Comment by tritonas00** [comment]
> in RoR x is front-back, y is up-down, z is side to side
in blender x is side to side, z is up-down, y is front-back
