### ISSUE TITLE
Low priority: Switch between MB to GB glitch

### ISSUE THREAD

**Issue by ereish64** [RigsOfRods/rigs-of-rods#2539]
![err](https://user-images.githubusercontent.com/24261026/79369873-4a8dbe00-7f17-11ea-9171-df5e2a7b113f.PNG)

Seems like there is a glitch of some kind when switching between MB to GB when running the installer. I was unable to fix the issue in the code, however it might be worth checking out FormatBytes at line 131 in Utils.cpp

Keep up the good work!

**Comment by tritonas00** [comment]
Hi. This has nothing to do with RoR, should be here https://github.com/CuriousMike56/ror-installer

**Comment by CuriousMike56** [comment]
This is a visual glitch introduced when the content packs moved to GitHub. I'll look into it eventually. As tritonas said, the installer is completely separate from RoR.

**Comment by ereish64** [comment]
My bad. Thanks for the info
