### ISSUE TITLE
Base keybindings limit certain keyboards.

### ISSUE THREAD

**Issue by Tazshelby2016** [RigsOfRods/rigs-of-rods#2541]
Currently in the Itch.io version, base keybindings assume all keyboards are the same, causing certain actions to be inaccessible.
Below, I have boxed the current keys that are not absolute using the following code:
- Red: major
- Yellow: minor
- Green: no problem
![input-map-general](https://user-images.githubusercontent.com/54291363/79613778-ce38dd80-80c4-11ea-9797-9502bffeaad3.png)
(image from the wiki)

**Comment by 4x4convoy** [comment]
The game is designed to be used on a full keyboard. You need the f1-f12 keys to use commands and the numpad for camera controls. If you don't have those keys on your keyboard then you're sol.

**Comment by Tazshelby2016** [comment]
My only limit is one page down. That is certain chromebooks, if they manage to load the thing.

**Comment by CuriousMike56** [comment]
There's really no way to "fix" this. RoR's keyboard bindings are designed for a full desktop keyboard. There are no other keys to remap functions to.

**Comment by Tazshelby2016** [comment]
You only use the `a` and `z` keys for changing gears. Since the key I am talking about was mapped for changing gears, it makes sense to move them to the same key because they do the same thing.

**Comment by 4x4convoy** [comment]
that makes literally zero sense.

**Comment by Tazshelby2016** [comment]
The `manual shift-automatic clutch` and the `automatic shift` gearbox mode change gears in the same way. However, they use different keys, making it possible to change gears in `manual shift-automatic clutch` mode, but not in the `automatic shift` mode on my keyboard. In short, because they use different keys for the same basic purpose, I cannot put the `automatic shift` gearbox mode into any other gear other than its default state.

**Comment by tritonas00** [comment]
I think he means make PageUp/Down keys -> a/z so both modes use the same keys

**Comment by Tazshelby2016** [comment]
Where is that?

**Comment by CuriousMike56** [comment]
```Documents\My Games\Rigs of Rods\config```
@tritonas00 I think this can be closed now.
