### ISSUE TITLE
it doesn't install

### ISSUE THREAD

**Issue by denk1** [RigsOfRods/rigs-of-rods#2543]
on the Ubuntu 19.10
 after executing cmake:
 

* Threads

-- Configuring done
**CMake Error at source/main/CMakeLists.txt:285 (add_executable):**
  Cannot find source file:

    plugins/pagedgeometry/include/BatchPage.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

**CMake Error at source/main/CMakeLists.txt:285 (add_executable):**
  No SOURCES given to target: RoR

What does it mean?

**Comment by tritonas00** [comment]
how did you cloned the repo?

**Comment by denk1** [comment]
I typed:
git clone https://github.com/RigsOfRods/rigs-of-rods.git

**Comment by tritonas00** [comment]
thats your problem, it should be

`git clone --recursive https://github.com/RigsOfRods/rigs-of-rods.git`

**Comment by denk1** [comment]
it has been compiled completely with this command. Thank you.
