### ISSUE TITLE
Screenshot crash

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2556]
![image](https://user-images.githubusercontent.com/46073351/81084174-86d38f00-8ec3-11ea-8352-21fdc916113a.png)
Not fixed by #2550

**Comment by tritonas00** [comment]
its fixed, 2 is old value
change it from the menu, or by hand

**Comment by CuriousMike56** [comment]
@tritonas00 Not quite "fixed" if it involves changing settings. This is going to be an issue for those upgrading.

**Comment by tritonas00** [comment]
> This is going to be an issue for those upgrading.

those are only dev build users

**Comment by CuriousMike56** [comment]
Ok, I understand now - the CVar PR changed the current `png` value to `2`, which caused the crash. I was thinking the `2` value was present in the current 2020.01 release. So I guess it its actually fixed, sorry if I seemed a bit too harsh.

**Comment by tritonas00** [comment]
> sorry if I seemed a bit too harsh.

lol not at all!
