### ISSUE TITLE
Broken savegames

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2565]
From Discord:

> Savegames seem to be very broken on master
> Loading a save that doesn't match the map you're currently on brings you back to the menu but doesn't actually load the new map, and loading a save results in everything being frozen, including the character
> it spams "scene loaded" and "physics paused", trying to unpause does nothing
> if I'm already on the map the save is on it loads fine

**Comment by tritonas00** [comment]
fixed https://github.com/RigsOfRods/rigs-of-rods/pull/2563

**Comment by WillyB1337** [comment]
On 2020.10-dev-777b743, whenever I click on **Resume Game** on Main Menu, I get this error.
When on a map, going thru the menu works all fine.
It even switches map when I load a save that was created in a different map.
```
15:36:14: Ogre::RuntimeAssertionException::RuntimeAssertionException: resourceName is empty string in Ogre::ResourceGroupManager::openResourceImpl at C:\Users\appveyor\.conan\data\OGRE\1.11.6-with-patches\anotherfoxguy\stable\build\78c6c4e2ea61dac8cba2360afd7746bec0f80872\OgreMain\src\OgreResourceGroupManager.cpp (line 657)
15:36:14: [RoR] Failed to open or read json file '' (resource group 'Savegames'), message: 'Ogre::RuntimeAssertionException::RuntimeAssertionException: resourceName is empty string in Ogre::ResourceGroupManager::openResourceImpl at C:\Users\appveyor\.conan\data\OGRE\1.11.6-with-patches\anotherfoxguy\stable\build\78c6c4e2ea61dac8cba2360afd7746bec0f80872\OgreMain\src\OgreResourceGroupManager.cpp (line 657)'
15:36:14: [RoR|Savegame] Could not load
```

**Comment by tritonas00** [comment]
I can't reproduce it, can you be more specific? What map/vehicle was loaded before closing RoR for example

**Comment by WillyB1337** [comment]
Let's say I have simple-test-map and a daf truck. 
I do a quicksave then go back to menu.
I try the button and it returns the same error message.

I tried the same steps but with exiting the game thru the Exit Game button.
Same result, the same error message.

I get it thru itch.io and put the program folder in My Games folder (not in Rigs of Rods content folder)
Last build, the save feature (the main menu button and scenes) would just freeze the game.

Could be something on Windows build.
I'm indeed running the latest stable build.
![image](https://user-images.githubusercontent.com/16364065/97356002-1738ce00-186e-11eb-973f-1ddb3fd0d25c.png)

**Comment by tritonas00** [comment]
What does your `savegames` directory in your RoR user directory contains?

**Comment by WillyB1337** [comment]
I've made it empty to test.
![image](https://user-images.githubusercontent.com/16364065/97358868-40f3f400-1872-11eb-916d-e28df0948d0e.png)
Now, I did the quick simple-test terrain and DAF combo, now I have an autosave.
![image](https://user-images.githubusercontent.com/16364065/97358955-67199400-1872-11eb-81e9-ae5b8cb9e4c6.png)
Now, whenever I try to load it thru the button that appears, I get the same error :
`16:36:28: Ogre::RuntimeAssertionException::RuntimeAssertionException: resourceName is empty string in Ogre::ResourceGroupManager::openResourceImpl at C:\Users\appveyor\.conan\data\OGRE\1.11.6-with-patches\anotherfoxguy\stable\build\78c6c4e2ea61dac8cba2360afd7746bec0f80872\OgreMain\src\OgreResourceGroupManager.cpp (line 657)
16:36:28: [RoR] Failed to open or read json file '' (resource group 'Savegames'), message: 'Ogre::RuntimeAssertionException::RuntimeAssertionException: resourceName is empty string in Ogre::ResourceGroupManager::openResourceImpl at C:\Users\appveyor\.conan\data\OGRE\1.11.6-with-patches\anotherfoxguy\stable\build\78c6c4e2ea61dac8cba2360afd7746bec0f80872\OgreMain\src\OgreResourceGroupManager.cpp (line 657)'
16:36:28: [RoR|Savegame] Could not load ''
`
I tried to make a quicksave from the 2020.01 in case the autosave was broken but it still don't want to load thru the main menu button.
![image](https://user-images.githubusercontent.com/16364065/97359378-0c346c80-1873-11eb-92b9-2df58bbfd239.png)

I also tried to load that quicksave on a map but it failed.
![image](https://user-images.githubusercontent.com/16364065/97359469-2e2def00-1873-11eb-9954-e323826422fb.png)

If I clear up the folder then try to load the autosave from a different map, I get this error 
`
16:41:38: Ogre::FileNotFoundException::FileNotFoundException: Cannot locate resource quicksave_18.sav in resource group Savegames. in ResourceGroupManager::openResource at C:\Users\appveyor\.conan\data\OGRE\1.11.6-with-patches\anotherfoxguy\stable\build\78c6c4e2ea61dac8cba2360afd7746bec0f80872\OgreMain\src\OgreResourceGroupManager.cpp (line 706)
16:41:38: [RoR|Savegame] Could not load 'quicksave_18.sav'
`

It seems it counts up the amount of quicksave made but don't account those which are not successful.

Even after restarting, whenever I'm on a different map, I still get the quicksave_18.sav not found error.
![image](https://user-images.githubusercontent.com/16364065/97359960-f1162c80-1873-11eb-9987-5a98c373560f.png)

Hope this is more clear.

**Comment by WillyB1337** [comment]
Also, it seems like I can make up to 10 saves even tho it does say up to 5.
![image](https://user-images.githubusercontent.com/16364065/97360408-8e716080-1874-11eb-84ae-69e6434b5c0a.png)

**Comment by tritonas00** [comment]
Ok. Can you temporarily rename you Rigs of Rods user directory and try with a fresh one? To exclude the situation of a bad setting.

**Comment by WillyB1337** [comment]
Indeed.
Tried but same results :
`
16:54:58: Ogre::RuntimeAssertionException::RuntimeAssertionException: resourceName is empty string in Ogre::ResourceGroupManager::openResourceImpl at C:\Users\appveyor\.conan\data\OGRE\1.11.6-with-patches\anotherfoxguy\stable\build\78c6c4e2ea61dac8cba2360afd7746bec0f80872\OgreMain\src\OgreResourceGroupManager.cpp (line 657)
16:54:58: [RoR] Failed to open or read json file '' (resource group 'Savegames'), message: 'Ogre::RuntimeAssertionException::RuntimeAssertionException: resourceName is empty string in Ogre::ResourceGroupManager::openResourceImpl at C:\Users\appveyor\.conan\data\OGRE\1.11.6-with-patches\anotherfoxguy\stable\build\78c6c4e2ea61dac8cba2360afd7746bec0f80872\OgreMain\src\OgreResourceGroupManager.cpp (line 657)'
16:54:58: [RoR|Savegame] Could not load ''
`

**Comment by tritonas00** [comment]
Ok, i cant reproduce it here at all, will ask Petr to take a look on it on windows.
