### ISSUE TITLE
Cinematic camera issues

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2566]
From Discord:

> something happened with the cinematic camera view, the distance between each camera change has increased
![image](https://user-images.githubusercontent.com/46073351/82511522-90701000-9adb-11ea-94f3-b495614d4013.png)
> 2020.01
![image](https://user-images.githubusercontent.com/46073351/82511541-9a920e80-9adb-11ea-82ba-a7d83823e520.png)
> both using a fresh user folder, so its not my settings

**Comment by CuriousMike56** [comment]
Skeleton view is also broken when in cinematic camera:
![image](https://user-images.githubusercontent.com/46073351/83095472-67b6c000-a071-11ea-95ed-8744988bb2f5.png)
![image](https://user-images.githubusercontent.com/46073351/83095485-6daca100-a071-11ea-9535-8dfd40404125.png)
![image](https://user-images.githubusercontent.com/46073351/83095410-4bb31e80-a071-11ea-892d-2054d9aa36d6.png)
(First two screenshots from WillyB1337)

**Comment by tritonas00** [comment]
first post caused by https://github.com/RigsOfRods/rigs-of-rods/commit/9b037a8a48ef8c08e7204e2752e15e4389aacc1f
