### ISSUE TITLE
the game doesn't work at all, always crashes at the starting 'loading rar files' thing

### ISSUE THREAD

**Issue by noclistt** [RigsOfRods/rigs-of-rods#2569]
i have no mods, no maps, i did no additions to the main game but it doesn't work at all.
![Screenshot_1](https://user-images.githubusercontent.com/67195684/85203729-4ff0f580-b318-11ea-92a5-092a8f877038.png)

**Comment by CuriousMike56** [comment]
This is a known issue with 2020.01: https://docs.rigsofrods.org/gameplay/general-faq/#failed-to-generate-list-of-installed-content. The GitHub issue tracker is only for the latest development build, not official releases. Please close this.
