### ISSUE TITLE
Null program bound

### ISSUE THREAD

**Issue by Morsfin** [RigsOfRods/rigs-of-rods#2582]
Hello,

It's my first time in RoR so I downloaded today game and in startup I've got a problem line 3640.
Propably it's not fix arleady so please fix it faster, because my pc is more than recommended settings XD.

Mors
![error](https://user-images.githubusercontent.com/69215606/89332861-666aca80-d694-11ea-806a-b10896196d70.png)
fin

**Comment by tritonas00** [comment]
See https://github.com/RigsOfRods/rigs-of-rods/issues/2385, already reported
