### ISSUE TITLE
Linux dev build not uploading 

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#2586]
Seem to be an issue with copying the libs to the redist folder

https://travis-ci.org/github/RigsOfRods/rigs-of-rods/builds/714417100#L1053

**Comment by tritonas00** [comment]
```
cp: cannot stat '/usr/lib/x86_64-linux-gnu/libraw.so.15': No such file or directory
```

probably the lib name changed?
