### ISSUE TITLE
beams / hydros disappear

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#26]
Sometimes beams / hydros disappear.

![ror_2015_01_14_22_16_27_028](https://cloud.githubusercontent.com/assets/1196375/5748112/a8976cf2-9c3d-11e4-8059-9e7517aada1f.png)
![ror_2015_01_14_22_16_29_391](https://cloud.githubusercontent.com/assets/1196375/5748113/a89e8406-9c3d-11e4-8346-aa50ed318a01.png)
![ror_2015_01_14_22_16_30_423](https://cloud.githubusercontent.com/assets/1196375/5748114/a8a526da-9c3d-11e4-92e7-8a0611bc85ad.png)

**Comment by Max98** [comment]
I believe that it's the same thing as here: 
https://github.com/RigsOfRods/rigs-of-rods/issues/34

**Comment by only-a-ptr** [comment]
@Speciesx : "Sometimes is vague". Give me testing instructions please.
* What vehicles? Download links please.
* What controls?

**Comment by Max98** [comment]
@only-a-ptr This is likely not a bug. It's simply that ogre's nodes are out of the camera view, so they become invisible. Aka camera culling mask.

**Comment by only-a-ptr** [comment]
@Max98 Even then it's still a visual glitch which we should address.

I guess it's caused by the beam entity's AABB bounding box vs. the view frustum intersection test. If the AABB is misplaced/outdated, Ogre leaves it out from rendering at wrong times.

**Comment by Speciesx** [comment]
I'm no longer able to reproduce that bug.
