### ISSUE TITLE
Turbo Update

### ISSUE THREAD

**Issue by Swindells** [RigsOfRods/rigs-of-rods#260]
Been looking at the turbo Max98 implemented and decided that my idea though older than Max's could improve his so to make it easier for him and just to put the idea out there to see what you guys think im putting it in my thread, Its similar to the first post but with a few additions such as bov's and wastegates (They are different before people start saying bovs and wastegates are the same)

For a large turbo you could have this:
> turbo
;idle rpm, max rpm, torque, inertia, max boost,  bov, wastegate
1800, 130000, 1000, 2.5, 40, n, 120000

> torquecurve
1800, 0.2
10000, 0.4
20000, 0.6
miss a few
120000, 1.0
130000, 0.8

That setup is a relatively low rpm turbo due to its size that only goes upto 130,000rpm with an exhaust wastegate that opens at 120000rpm limiting the boost built past that rpm and having no bov, wastegates still sometimes make a sound though its usually hard to hear unless you have a straight pipe but its the howl noise you hear on a lo of diesels when they let off the accelerator. max boost saying 40 is what it is, this turbo will put out 40psi at max. but having no bov means that the boost wont drop off as much when you let off the accelerator, it will just stop building boost. as the turbo will slow down but hold its pressure for that rpm

For a small turbo you could have this:
> turbo
;idle rpm, max rpm, torque, inertia, max boost,  bov, wastegate
1800, 250000, 300, 0.5, 23, y, 240000

> torquecurve
1800, 0.2
10000, 0.4
20000, 0.6
miss a few
240000, 1.0
250000, 0.8

This is basically the same as the large turbo but with a much faster spool up due to the smaller inertia and has a much higher rpm and a bov
the bov means that the boost will totally drop but the turbo rpm will stay high so once you punch the loud pedal boost comes back on and you go as long as you have kept the turbo in its higher boost rpm

With it having its own defined rpm, wastegates and bov's it will be much easier to set sounds for them rather than fighting with loads of numbers to do with the turbo rpm we currently have and still end up with the bov sound playing when you accelerate such as Kurus Scania R500. a simple Y and N in the turbos code says if it has a bov or not so its easy to get them to work, wastegate is set to open at a specific rpm rather than the maximum boost as they are meant to though it could be set to open at the boost pressure instead, i thought the rpm would be better as then you'd feel the drop off and it wouldnt open as soon as you hit the max boost so it could hold the max boost pressure, they are used for boost turning anyway so you could keep it closed for the full rpm range as if its not got the wastegate if you dont want to use it.

**Comment by Max98** [comment]
Because of how RoR simulate turbos, "idle rpm & max rpm" will not be editable by the user.
I've been reading around the net and I found out this:
Big turbo -> less rpm -> 30 psi (example)
Small turbo -> more rpm -> 30 psi

So it will work that way.
The BOV is now implemented in the game. The only missing feature is a waste-gate, which I should get done by tomorrow morning.

**Comment by Max98** [comment]
The turbo code is now nearly complete, all of the main features are done. Blow off valve and wastegate with their respect sounds.
