### ISSUE TITLE
Horizontal Navigation Indicator (HSI) airplane navigation not working (CIBuild-1064)

### ISSUE THREAD

**Issue by WillyB1337** [RigsOfRods/rigs-of-rods#2613]
**On latest build (CIBuild-1064), the HSI auto navigation / landing thing doesn't work.**
Here's a picture of what I mean.
![RoR 2020-10-23 21-31-53](https://user-images.githubusercontent.com/16364065/97064868-6a153b80-1577-11eb-9a62-aa6a6fa668dd.png)
Here's what's it's supposed to do (2020-01) :
![screenshot_2020-10-23_21-36-49_1](https://user-images.githubusercontent.com/16364065/97064941-e871dd80-1577-11eb-8e25-05da2c057e57.png)

Here's the log if there's any clue on why could that be happening. Maybe a feature being removed?
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/5432262/RoR.log)

**Comment by only-a-ptr** [comment]
No feature was removed, this is likely a bug in terrain loading. @tritonas00 already investigated it broke in #2563
