### ISSUE TITLE
MP : Crash when pressing L near another player's hook

### ISSUE THREAD

**Issue by WillyB1337** [RigsOfRods/rigs-of-rods#2620]
![image](https://user-images.githubusercontent.com/16364065/98158506-03621d00-1ea9-11eb-9438-ad69526eb334.png)
![image](https://user-images.githubusercontent.com/16364065/98158510-06f5a400-1ea9-11eb-8881-7af82ab5f7c3.png)
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/5490066/RoR.log)

**Tested with **Coronado-SD-6x4-dump.truck****

_I also tried with the official Western-Star from the repo that the remote player doesn't have and I can't reproduce it._

**Comment by only-a-ptr** [comment]
I couldn't reproduce it. Trucks: "Coronado dump" and "Volvo VHD crane".

What was the hooking vehicle in the original case? I tried figuring from RoR.log but there were too many players.

![screenshot_2021-01-02_17-17-16_1](https://user-images.githubusercontent.com/491088/103461446-b66ebb80-4d1e-11eb-97a8-de24cf4146cd.png)

**Comment by WillyB1337** [comment]
> I couldn't reproduce it. Trucks: "Coronado dump" and "Volvo VHD crane".
> 
> What was the hooking vehicle in the original case? I tried figuring from RoR.log but there were too many players.
> 
> ![screenshot_2021-01-02_17-17-16_1](https://user-images.githubusercontent.com/491088/103461446-b66ebb80-4d1e-11eb-97a8-de24cf4146cd.png)

it was the Coronado 10x4 wrecker and the Coronado dump truck.

I did attempt to reproduce on my end but couldn’t. 

I do recall that crash in a different context. I will update if I ever get the same message.

**Comment by only-a-ptr** [comment]
No luck with Terex, either. I'll try with both Coronados.
![image](https://user-images.githubusercontent.com/491088/103461763-0babcc80-4d21-11eb-8bc8-6d709828b1d3.png)

**Comment by only-a-ptr** [comment]
Not even 2 pairs of Coronados did the trick... I give up :)
![image](https://user-images.githubusercontent.com/491088/103462308-9641fb00-4d24-11eb-8dfd-82f2ed02cdb8.png)

**Comment by only-a-ptr** [comment]
@WillyB1337 Re-open the issue if you get the crash again.
