### ISSUE TITLE
Migrate travis from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#2623]
travis-ci.org will be shut down at the end of the year, so all of your CI builds on Travis need to be migrated to travis-ci.com

**Comment by paroj** [comment]
rather go for github actions. see: https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works
