### ISSUE TITLE
I have made a Cybertruck, and it flies apart.

### ISSUE THREAD

**Issue by singhamitoj** [RigsOfRods/rigs-of-rods#2639]
I have decided to make a Tesla Cybertruck from scratch. I know there is already a Cybertruck in the repository, but it is not fun to drive. Everything worked until I added the wheels. After that, the truck just flew apart. I tried changing the placement of the wheels, but no luck. Can anyone help me with the placement of the wheels?
[Cybertruck-incomplete.zip](https://github.com/RigsOfRods/rigs-of-rods/files/5778243/Cybertruck-incomplete.zip)

**Comment by AnotherFoxGuy** [comment]
Use the [Content creation category](https://forum.rigsofrods.org/forums/content-creation.15/) on the forums or the #modding channel on the [Discord](https://discord.gg/rigsofrods) for help with creating mods
