### ISSUE TITLE
Migrate from transifex to weblate

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#2643]
Benefits by using Weblate:
* Better GitHub integration, translation files can be stored in the repo
* Automatic .mo compilation, when a translation get updated Weblate will automatically compile the .mo file

TODO list:
- [X] Upload all translation files to git
- [X] Update the translation tool scripts
- [x] Create a Weblate project
- [x] Update links in the readme and other docs
- [ ] Delete the Transifex project

**Comment by AnotherFoxGuy** [comment]
@only-a-ptr Could you delete the Transifex organisation? 
After that, this issue can be closed.

**Comment by only-a-ptr** [comment]
![image](https://user-images.githubusercontent.com/491088/104442555-82ed2600-5595-11eb-841d-4fc39d453374.png)
