### ISSUE TITLE
Vehicles meshes and textures mess up when changing map

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#266]
If a vehicles material or mesh names are same, they will mess up when spawning both of the vehicles, so there will be meshes visible from the vehicle spawned before and/or textures visible from the vehicle spawned before.
Now if you get vehicle A with texture colour.png for example, change the map, get vehicle B with texture colourb.png, the colour of vehicle B will be the one from vehicle A if the material name is the same. Same happens if the mesh name is the same, just the meshes from vehicle A would be used.

In example:
I made a red and orange version of this Gavril mod, but didn't change the material name or meshes, only the texture in the .truck file.
1: Spawning the red one:
![screenshot_3848](https://cloud.githubusercontent.com/assets/12358849/8263012/6d09dd4a-16d7-11e5-8207-2002b33450f5.jpg)
2: Going into pause menu - change map - open map.
3: Spawning the orange one:
![screenshot_3849](https://cloud.githubusercontent.com/assets/12358849/8263027/7f2694fa-16d7-11e5-8f4c-bc25d44de6c8.jpg)
but it's red (+the material seems to be somehow different but idk if that's the same reason)

**Comment by Hiradur** [comment]
About the material: Is it related to #83?

**Comment by DirtGamer301** [comment]
@Hiradur Uh I'm not really sure but I think so. RoR btw now crashed re-trying this with the same vehicles, just spawning the orange one on a different map (map works in 0.4.5.0, so it's not the map crashing RoR).

10:53:23:  == RigSpawner: WARNING (Keyword managedmaterials) Managed material 'mv4' already exists (probably because the vehicle was already spawned before)
10:53:23:  == RigSpawner: WARNING (Keyword managedmaterials) Managed material 'Mesh' already exists (probably because the vehicle was already spawned before)
10:53:23:  == RigSpawner: WARNING (Keyword managedmaterials) Managed material 'MV4RSportFbumpB' already exists (probably because the vehicle was already spawned before)


Last lines:
10:53:24: static map icon not found: icon_truck.dds
10:53:24: EFL: beam instanciated
10:53:24: initTrucks done

**Comment by Hiradur** [comment]
The second issue looks exactly like #83 

Please put logs etc. in \`\`\` \<log output\> \`\`\` next time

**Comment by Hiradur** [comment]
Looks similar to https://github.com/RigsOfRods/rigs-of-rods/issues/90

**Comment by Max98** [comment]
Actually nope, this is far from a bug:
http://www.rigsofrods.com/wiki/pages/Truck_Description_File#GUID

The GUID is used in the file name, so if in 2 mods, there are 2 different files, with the same name, Ogre will pic the first one loaded because they have the same name, but using GUID, this won't happen anymore.

It's simply that modders forgot about this, because if you go back to old mods, (something around 0.36 and stuff) you'll see that most of them use the GUID system.

**Comment by DirtGamer301** [comment]
Mmh, yeah, I now also always use new guid but I didn't even think to that when finding this bug ^^

**Comment by only-a-ptr** [comment]
Fixed, see the purple [MERGED] icon above.
