### ISSUE TITLE
In-game vehicle switcher improperly displays vehicle names

### ISSUE THREAD

**Issue by TheDude53** [RigsOfRods/rigs-of-rods#2668]
### Steps to reproduce
1. Load any map
2. Load a vehicle with a long name (like the Rocket Booster)
3. Load a vehicle with a smaller name (like the Boeing 767)
4. Repeat step 3 using a vehicle with a smaller name every time

### Expected behavior
The vehicle names are displayed properly with no errors

### Actual behavior
The subsequent vehicle names appear to be overwritten over the previous one

### System configuration
OS: Windows 10 version 20H2 (2004)
Renderer used: DirectX9
GPU: Intel Iris Xe Graphics
Driver version: 27.20.100.9168

### Additional information
![Screenshot](https://user-images.githubusercontent.com/46414358/107128666-2247c500-6885-11eb-9e18-68a8ce97f1fe.png)

**Comment by AnimosusTheWolf** [comment]
Confirmed. Petr was discussing this in Discord a few days ago also.

**Comment by AnotherFoxGuy** [comment]
From the dev channel on discord:
![Discord_2021-02-06_21-22-04](https://user-images.githubusercontent.com/9480940/107128864-6c4e9c00-68c1-11eb-82c1-eba8d1422d15.png)
