### ISSUE TITLE
RoR Server Bot Does not Work

### ISSUE THREAD

**Issue by singhamitoj** [RigsOfRods/rigs-of-rods#2678]
I just set up a Rigs of Rods server bot, and it works, but it does not do anything, and it seems to be stuck in a mountain.

Edit: I tried simple test terrain, and the bot doesn't show at all.

**Comment by WillyB1337** [comment]
Does it responds to a chat message like -help?

**Comment by singhamitoj** [comment]
No, it doesn't seem to respond to messages. I did not use an irc server, and I ran everything on the same system, which runs Ubuntu 20.10.

**Comment by WillyB1337** [comment]
You have to download the updated source here
https://github.com/tritonas00/RoRServerBot

**Comment by tritonas00** [comment]
irrelevant to RoR, and RoRSserverBot works perfectly now

if you have problems open an issue here https://github.com/tritonas00/RoRServerBot
