### ISSUE TITLE
Multiplayer: Unused Vehicles Teleported to 0,0,0

### ISSUE THREAD

**Issue by graysonk95** [RigsOfRods/rigs-of-rods#27]
In multiplayer, as users leave the server, their vehicles are teleported to 0,0,0 and deactivated, rather than being removed.
After a while on one server, this pile of vehicles can become massive and really hurt performance.

![glitch2](https://cloud.githubusercontent.com/assets/10550037/5762155/35480a10-9cae-11e4-9003-67e059bfa55c.JPG)

Forum thread: http://www.rigsofrods.com/threads/118133-Vehicles-Teleported-to-0-0-0?p=1368918&viewfull=1#post1368918

**Comment by Max98** [comment]
I will take a look as soon as only_a_ptr will merge his multiplayer fixes into the main repo.

**Comment by Aperion** [comment]
Could this be a server issue ?

**Comment by Max98** [comment]
I don't think so, i still didn't take a look, will do so soon.

**Comment by only-a-ptr** [comment]
I'm not sure whether this is a bug or feature :( 

@graysonk95 When did you first observe this? Hasn't it always worked this way?

Anyway, sorry I've been overlooking this for so long

**Comment by Hiradur** [comment]
Isn't this client-side only? As in if you restart and log in again the trucks aren't there anymore?

**Comment by ulteq** [comment]
> Isn't this client-side only?

Yes it is.
