### ISSUE TITLE
Sight range system

### ISSUE THREAD

**Issue by TheUnknownGuyFromRoR** [RigsOfRods/rigs-of-rods#270]
My idea is to let terrain load, but make meshes loading when close to them. For eg. I set sight range to 3000 meters, and terrain that is 5000 meters from me is loaded, but small meshes (signs, toilets etc.) are not.

**Comment by Hiradur** [comment]
This would make models popping up which I find annoying. It should be an optional setting.

**Comment by TheUnknownGuyFromRoR** [comment]
I also thought about optional setting. How about making meshes coming out like from fog?

**Comment by Max98** [comment]
This is already happening if you enable fogs. Also, a better way would be to use LODs.

**Comment by CuriousMike56** [comment]
Can this be closed? Doesn't seem like a valid issue.

**Comment by only-a-ptr** [comment]
Good idea.
