### ISSUE TITLE
Custom dashboards

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#271]
Custom dashboards defined in the truck file worked back in RoR 0.38, since the new dashboard was used (0.39+) they're gone, as well as in NextStable. Is there the possibillity of re-adding them or is it too hard due to the new style of RoR?

**Comment by Max98** [comment]
Actually, last time I used custom dashboards in 0.4.0.7, it worked but it was fine. so it's not really gone.
We'll take a look at this.

**Comment by DirtGamer301** [comment]
Oh well, I only tried with vehicles having custom dashboards like Dodge Magnum for example and it showed 0.4 standard layout. Same in NextStable

**Comment by Max98** [comment]
Oh, the guisetting stuff? Some of it's functions are deprecated because of the new GUI,
 use these instead:
> dashboard dash_test.layout
dashboard dash_test2.layout
texturedashboard dashGauges.layout

**Comment by only-a-ptr** [comment]
I finally decided to just close this.

Most 'guisettings' customizations, like 'tacho/speedoMaterial', was related to the historic HUD based on OGRE overlays, which was completely removed somewhere around v0.4.6. The new dashboard system has all the needed features - it can display custom graphics and freely visualize the input data.
