### ISSUE TITLE
Dashboard warning lights state not set/loaded, when loading a save

### ISSUE THREAD

**Issue by MarkROR** [RigsOfRods/rigs-of-rods#2740]
When loading a saved game, the parking brake light will show as "off" even if the vehicle's parking brake is on.
Same with the lights indicator (lights activated with n key) - the lights themselves will be on, the flares are shown, but the indicator light is off. Also, the state of turn signals/hazard lights is not saved nor loaded (not sure if it should be? possibly not)

### Steps to reproduce
1. Enter any map, spawn any car (with working lights)
2. Turn ignition off (x) and turn it back on so the check engine/battery lights come on.
3. Turn the handbrake on (p) and the main lights (n) and the hazard lights (-)
4. Exit to main menu
5. Click "Resume game"

### Expected behaviour
- The state of the functions activated should be the same.
- The dashboard warning lights should reflect the state of the active functions.

### Actual behaviour
- The state of the functions activated is the same, except for the hazard lights (same result when using turn signals)
- The dashboard warning lights are off and so showing incorrect state of the active functions.

This isn't a big deal, they reset themselves after you toggle the functions again. Still, can be confusing when you're trying to drive and the handbrake is on when it appears to be off. It's the same situation when using the analog speedometer.

Again, I'm not sure if the state of hazard lights/turn signals should even be saved, but I decided to mention it.

**Comment by WillyB1337** [comment]
I can confirm what is going on.
> * The state of the functions activated is the same, except for the hazard lights (same result when using turn signals)
> * The dashboard warning lights are off and so showing incorrect state of the active functions.
For vehicles with animated props for the parking-brake, it would stay in the engaged position after loading the save. (I usually restart the game since it's for setting changes)

Probably a simple fix in the form of
if engaged in save, set parking brake state to true.

**Comment by WillyB1337** [comment]
> This isn't a big deal, they reset themselves after you toggle the functions again. Still, can be confusing when you're trying to drive and the handbrake is on when it appears to be off. It's the same situation when using the analog speedometer.

For dashboards with both an indicator light and a parking brake switch, they would be reverse. 
Like the light would be off but the prop is on. 
It requires me to hold the parking brake button to _glitch_ the state. 

I gotta say that the save feature is not utilized enough in the community. 

It would require a section for it in the official documentation.

**Comment by MarkROR** [comment]
I just want to clarify, by dashboard, I meant the GUI dashboard/speedometer, which is unrelated to any mod. Please feel free to change the title if it's misleading, I just don't know the proper terminology.

Testing it with the Thomas Saf-T-Liner, both its own dashboard light and the yellow parking brake pull lever thing are set to the correct state, when loading a game. 

Thank you for taking a look into this, I definitely agree this is low-priority
