### ISSUE TITLE
Game literally does not open for me

### ISSUE THREAD

**Issue by paytontech** [RigsOfRods/rigs-of-rods#2742]
I'll try to open the game, then the cursor has the blue loading circle (windows 10), then it just doesn't open. I might be doing something wrong here, though.
EDIT: Even reinstalled it to a different drive. Still nothing

**Comment by paytontech** [comment]
Here are the logs:
`21:24:53: [RoR] Rigs of Rods (www.rigsofrods.org) version 2021.04
21:24:53: [RoR] Current date: 2021-04-25
21:24:53: [RoR|CVar]        sys_config_dir:  "C:\Users\Payton Curry\Documents\My Games\Rigs of Rods\config" (was: "")
21:24:53: [RoR|CVar]         sys_cache_dir:  "C:\Users\Payton Curry\Documents\My Games\Rigs of Rods\cache" (was: "")
21:24:53: [RoR|CVar]     sys_savegames_dir:  "C:\Users\Payton Curry\Documents\My Games\Rigs of Rods\savegames" (was: "")
21:24:53: [RoR|CVar]    sys_screenshot_dir:  "C:\Users\Payton Curry\Documents\My Games\Rigs of Rods\screenshots" (was: "")
21:24:53: Ogre::FileNotFoundException::FileNotFoundException: Cannot open file: C:\Users\Payton Curry\Documents\My Games\Rigs of Rods\config\RoR.cfg in Ogre::_openFileStream at C:\Users\runneradmin\.conan\data\OGRE\1.11.6-with-patches\anotherfoxguy\stable\build\78c6c4e2ea61dac8cba2360afd7746bec0f80872\OgreMain\src\OgreFileSystem.cpp (line 388)
21:24:53: [RoR|CVar]     sys_resources_dir:  "C:\Program Files\Rigs of Rods\resources" (was: "")
21:24:53: Creating resource group General
21:24:53: Creating resource group OgreInternal
21:24:53: Creating resource group OgreAutodetect
21:24:53: SceneManagerFactory for type 'DefaultSceneManager' registered.
21:24:53: Registering ResourceManager for type Material
21:24:53: Registering ResourceManager for type Mesh
21:24:53: Registering ResourceManager for type Skeleton
21:24:53: MovableObjectFactory for type 'ParticleSystem' registered.
21:24:53: ArchiveFactory for archive type FileSystem registered.
21:24:53: ArchiveFactory for archive type Zip registered.
21:24:53: ArchiveFactory for archive type EmbeddedZip registered.
21:24:53: DDS codec registering
21:24:53: ETC codec registering
21:24:53: Registering ResourceManager for type HighLevelGpuProgram
21:24:53: Registering ResourceManager for type Compositor
21:24:53: MovableObjectFactory for type 'Entity' registered.
21:24:53: MovableObjectFactory for type 'Light' registered.
21:24:53: MovableObjectFactory for type 'BillboardSet' registered.
21:24:53: MovableObjectFactory for type 'ManualObject' registered.
21:24:53: MovableObjectFactory for type 'BillboardChain' registered.
21:24:53: MovableObjectFactory for type 'RibbonTrail' registered.
21:24:53: *-*-* OGRE Initialising
21:24:53: *-*-* Version 1.11.6 (Rhagorthua)
21:24:53: Loading library .\Codec_FreeImage
21:24:53: FreeImage version: 3.15.3
21:24:53: This program uses FreeImage, a free, open source image library supporting all common bitmap formats. See http://freeimage.sourceforge.net for details
21:24:53: Supported formats: bmp,ico,jpg,jif,jpeg,jpe,jng,koa,iff,lbm,mng,pbm,pbm,pcd,pcx,pgm,pgm,png,ppm,ppm,ras,tga,targa,tif,tiff,wap,wbmp,wbm,psd,cut,xbm,xpm,gif,hdr,g3,sgi,exr,j2k,j2c,jp2,pfm,pct,pict,pic
21:24:53: Loading library .\RenderSystem_Direct3D9
21:24:53: Installing plugin: D3D9 RenderSystem
21:24:53: D3D9 : Direct3D9 Rendering Subsystem created.
21:24:53: D3D9: Driver Detection Starts
21:24:53: D3D9: Driver Detection Ends
21:24:53: Plugin successfully installed
21:24:53: Loading library .\RenderSystem_GL
21:24:53: Installing plugin: GL RenderSystem
21:24:53: OpenGL Rendering Subsystem created.
`

**Comment by WillyB1337** [comment]
Is it fixed or still ongoing

What was the fix @paytontech ?
