### ISSUE TITLE
Rigs of rods keeps crashing when I try and open it

### ISSUE THREAD

**Issue by Sepheroth330** [RigsOfRods/rigs-of-rods#2754]
Hello,

I have the up to date version of rigs of rods and it was working fine a little bit ago but didnt have anything in the mod folder at the start and now for some reason it keeps crashing and popping up a "fatal error" can anyone help me figure out how to fix this issue and get it back to working again?

**Comment by tritonas00** [comment]
Please upload RoR.log

**Comment by tritonas00** [comment]
Well, any update?

**Comment by only-a-ptr** [comment]
@Sepheroth330 Hello. If you need help, help us first - go to "Documents\My Games\Rigs of Rods\logs" and upload RoR.log.
