### ISSUE TITLE
Command line "pos" does not work

### ISSUE THREAD

**Issue by Bob-Z** [RigsOfRods/rigs-of-rods#2758]
"`RoR -help`" command gives an example command:

`RoR.exe -map simple2 -pos '518 0 518' -rot 45 -truck semi.truck -enter`

This seems to work for every arguments except "-pos".

**Comment by only-a-ptr** [comment]
You're right, `-pos` is broken, thanks for reporting.

**Comment by Bob-Z** [comment]
I am using Linux (Ubuntu).
Log is interesting:

```
[RoR|CVar]    cli_preset_terrain:  "simple2" (was: "")
[RoR|CVar]  cli_preset_spawn_pos:  "518" (was: "")
[RoR|CVar]  cli_preset_spawn_rot:  "45" (was: "")
```
Both single and double quote fail the same way.
I also tried with different value for first and last value in the input string. I confirm that it is the first value that appear in the log.

**Comment by Bob-Z** [comment]
Do I miss something ? Why does this issue is closed ?

**Comment by only-a-ptr** [comment]
I closed the issue because I see no problem with the game itself.

I work on Windows so I can't help with Linux shell.

@tritonas00 Can you check this please?

**Comment by tritonas00** [comment]
Works fine here (Arch, urxvt)

`12:26:51: [RoR|CVar]  cli_preset_spawn_pos:  "518 0 518" (was: "")`

**Comment by Bob-Z** [comment]
You both are right.
It is a shell issue. I have just created a PR that fix it.
And "enter" seems broken too for me.
