### ISSUE TITLE
Physics freeze on certain vehicles

### ISSUE THREAD

**Issue by KruddyKamikaze** [RigsOfRods/rigs-of-rods#276]
this happened with most Gavrils and even the DAF Ampliroll.

Essentially, i would be driving or flying and when driven next to another vehicle (in my case i was going to tow the 767 with the ampliroll) the vehicle just resets and does not move, no throttle, can't shift gears, even if i try to frag the vehicle. I can can out of the vehicle and walk around with RoRBot but that is it, i can then get in and the same result. other vehicles may be frozen too or not.

**Comment by TheUnknownGuyFromRoR** [comment]
what version of the build do you use? Physics freezing was happening to me in 1st test build

**Comment by Olius** [comment]
This happens quite a bit with the turbocharged Lotus (max98's new turbo version).

**Comment by Max98** [comment]
@Olius 
That's actually just a bad configured engine. It happens on many RoR versions.
So it has nothing to do with this.

**Comment by Olius** [comment]
@Max98 
I see, will remember.
Physics freeze on spawn on some of the AI test maps with at least the DAF Semi and Lotus, too though.

**Comment by only-a-ptr** [comment]
@KruddyKamikaze Can you re-test this, please?

If it happens to you, I need you to help:
 1. Move away all your mods (terrains, vehicles, everything), only leave one map to test with and the vehicle(s) which exhibit this problem
 2. try again. Does it still happen? Try once more. Does it happen in the same situation? I need to know.
 3. Tell a developer about it with all details. What map? What vehicle(s)? What RoR version (is it a nightly build - which?). Also post your RoR.log, you'll find it in MyDocuments/Rigs of Rods 0.4/logs/

**Comment by Michael10055** [comment]
@only-a-ptr This issue is very old - 0.4.5.1 days. The "physics freezing" issue was fixed in 0.4.6RC3.
