### ISSUE TITLE
Flexbodies spawning up glitched

### ISSUE THREAD

**Issue by I-Dont-Exist-007** [RigsOfRods/rigs-of-rods#2766]
Often when I spawn a vehicle (literally any vehicle) that uses flexbodies, about 3/4 of the time, I need to reload the vehicle a few times before it will spawn without any spiky or otherwise glitched flexbodies.  As far as I've noticed, sometimes the mesh itself looks spiky or otherwise glitched, and sometimes the UVs are all messed up.  Some screenshots are attached.  I'm currently using 2020.03, however this has been an issue since I first started playing the game on 2020.04 and 2021.04.

I'm on Ubuntu 18.04 and my render system is OpenGL.
I believe this is a linux-only issue since this never happens to my friends on Windows.
![screenshot_2021-06-22_20-08-12_1](https://user-images.githubusercontent.com/85415347/123016308-4b7e7300-d398-11eb-937c-bd11169de010.png)
![screenshot_2021-06-22_20-08-17_1](https://user-images.githubusercontent.com/85415347/123016309-4b7e7300-d398-11eb-8afa-8652a11e5bcf.png)
![screenshot_2021-06-22_20-09-20_1](https://user-images.githubusercontent.com/85415347/123016321-53d6ae00-d398-11eb-9c8a-64dcc5f9f30e.png)
![screenshot_2021-06-22_20-10-35_1](https://user-images.githubusercontent.com/85415347/123016323-546f4480-d398-11eb-971a-83c76a522ab8.png)

**Comment by only-a-ptr** [comment]
Very interesting, I've never seen anything similar. 

@I-Dont-Exist-007 Please post RoR.log and describe what graphics hardware and (most importantly) drivers/versions you use.

I suspect this is a linux/driver issue. Flexbodies work by deforming the mesh in CPU/RAM and then uploading it to VRAM, each frame. It looks like something goes wrong on the trip from RAM to VRAM.

@paroj Does this look any familiar to you?

**Comment by I-Dont-Exist-007** [comment]
> Very interesting, I've never seen anything similar.
> 
> @I-Dont-Exist-007 Please post RoR.log and describe what graphics hardware and (most importantly) drivers/versions you use.
> 
> I suspect this is a linux/driver issue. Flexbodies work by deforming the mesh in CPU/RAM and then uploading it to VRAM, each frame. It looks like something goes wrong on the trip from RAM to VRAM.
> 
> @paroj Does this look any familiar to you?

I unfortunately do not know what my graphics hardware and drivers are, but here's my RoR.log from when this happened:
![screenshot_2021-06-23_12-26-41_1](https://user-images.githubusercontent.com/85415347/123134582-ef126680-d41e-11eb-9c55-7bd61796492e.png)
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/6703517/RoR.log)
I will try to find out my graphics hardware and drivers and tell you ASAP.

**Comment by only-a-ptr** [comment]
From RoR.log:
```
12:26:14: [RoR] Rigs of Rods (www.rigsofrods.org) version 2020.03

12:26:14: *-*-* OGRE Initialising
12:26:14: *-*-* Version 1.11.6 (Rhagorthua)

12:26:14: RenderSystem Name: OpenGL Rendering Subsystem
12:26:14: GPU Vendor: unknown
12:26:14: Device Name: AMD TURKS (DRM 2.50.0 / 5.3.0-45-generic, LLVM 9.0.0)
12:26:14: Driver Version: 3.1.0.0
```

No relevant error logs.

**Comment by tritonas00** [comment]
can you check 2020.01 also? 

https://github.com/RigsOfRods/rigs-of-rods/releases/download/2020.01/RoR_2020.01_Setup.exe

**Comment by I-Dont-Exist-007** [comment]
> can you check 2020.01 also?
> 
> https://github.com/RigsOfRods/rigs-of-rods/releases/download/2020.01/RoR_2020.01_Setup.exe

That's the Windows version.  I can't use it.  Can you send the linux version?

**Comment by Zentro** [comment]
> > can you check 2020.01 also?
> > https://github.com/RigsOfRods/rigs-of-rods/releases/download/2020.01/RoR_2020.01_Setup.exe
> 
> That's the Windows version. I can't use it. Can you send the linux version?

The Linux version can be found here.

https://files.rigsofrods.org/rigs-of-rods-linux-2020.01.zip

**Comment by tritonas00** [comment]
oops, sorry about that

**Comment by I-Dont-Exist-007** [comment]
> > > can you check 2020.01 also?
> > > https://github.com/RigsOfRods/rigs-of-rods/releases/download/2020.01/RoR_2020.01_Setup.exe
> > 
> > 
> > That's the Windows version. I can't use it. Can you send the linux version?
> 
> The Linux version can be found here.
> 
> https://files.rigsofrods.org/rigs-of-rods-linux-2020.01.zip
When I use that download link, I end up getting 2020.03, oddly enough.  I've cleared out the .rigsofrods folder.
![waitwhat](https://user-images.githubusercontent.com/85415347/123180077-9069de80-d458-11eb-9ee1-290f4df62545.png)

**Comment by tritonas00** [comment]
well it seems your amd gpu doesnt play well at least with opengl, cant think anything else except update your graphics driver/kernel, or try more recent version of ubuntu like 20.04

**Comment by I-Dont-Exist-007** [comment]
> well it seems your amd gpu doesnt play well at least with opengl, cant think anything else except update your graphics driver/kernel, or try more recent version of ubuntu like 20.04

I get reasonably good frame rates (usually 40-60 fps), so I think my gpu plays pretty well.  I have no idea how to update my graphics drivers, but I have been considering updating to ubuntu 20.04.
