### ISSUE TITLE
Tab map rendering black under "Bilinear" texture filtering.

### ISSUE THREAD

**Issue by WillMichals** [RigsOfRods/rigs-of-rods#2767]
Tab map renders full black with Bilinear texture filtering.

Screenshots attached and RoR log.

![image](https://user-images.githubusercontent.com/51508848/123206580-90320900-d481-11eb-8299-1fb6646c3071.png)
![image](https://user-images.githubusercontent.com/51508848/123206643-a8098d00-d481-11eb-9121-c5982e93c526.png)
[RoR (2).log](https://github.com/RigsOfRods/rigs-of-rods/files/6706434/RoR.2.log)

**Comment by tritonas00** [comment]
Can't reproduce it on linux. Other modes work? (none, trilinear, anisotropic - you need to restart the game to take effect)

**Comment by WillMichals** [comment]
> Other modes work? (none, trilinear, anisotropic - you need to restart the game to take effect)

Every other mode fixes the issue. Bilinear is the only mode that produces this.

**Comment by tritonas00** [comment]
we should just disable filtering in survey map, i will look into this

**Comment by tritonas00** [comment]
Cant reproduce it on windows either (vbox)

**Comment by tritonas00** [comment]
https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/gui/panels/GUI_SurveyMap.cpp#L153

For some reason it renders like
```
ImGui::Image(reinterpret_cast<ImTextureID>(tex->getHandle()), ImVec2(0, 0));
```
