### ISSUE TITLE
I can’t drive with pxn steering wheel 

### ISSUE THREAD

**Issue by Locusfan** [RigsOfRods/rigs-of-rods#2769]
I can’t drive with my pxn steering wheel is that steering wheel not compatible with rigs of rods? If not I think it should because it’s unfair to others that can’t drive with theirs if they wanted to

**Comment by tritonas00** [comment]
duplicate https://github.com/RigsOfRods/rigs-of-rods/issues/2770

**Comment by Locusfan** [comment]
> duplicate #2770

How do I fix the issue tho?

**Comment by tritonas00** [comment]
you opened a new issue here https://github.com/RigsOfRods/rigs-of-rods/issues/2770

**Comment by Locusfan** [comment]
But it won’t let me join ror discord.
