### ISSUE TITLE
Water in the sky on some terrains

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#277]
In 0.4.5 TB 3, some terrains have water in the sky instead of clouds:

![screenshot_9](https://cloud.githubusercontent.com/assets/7621364/8368323/9b3ccaee-1b5d-11e5-8097-0350e1c03560.jpg)

North St. Helens, for example.

**Comment by tritonas00** [comment]
Disable waves.

**Comment by gigapouch** [comment]
That removed the water from the sky, but it's still a bug that needs to be fixed.

**Comment by tritonas00** [comment]
Yeap, already reported -> https://github.com/RigsOfRods/rigs-of-rods/issues/174 :P

**Comment by gigapouch** [comment]
Oh, I didn't see #174

**Comment by Max98** [comment]
Duplicated.
