### ISSUE TITLE
I can’t connect my steering wheel 

### ISSUE THREAD

**Issue by Locusfan** [RigsOfRods/rigs-of-rods#2770]
I can’t drive with my pxn steering wheel is that steering wheel not compatible with rigs of rods? If not I think it should because it’s unfair to others that can’t drive with theirs if they wanted to.. So if I am able to connect it please tell me how

**Comment by Goetterescu** [comment]
Did you use the mapping tool in order to set uo your controller for RoR? Or did you install a map from the forum for your controller?

**Comment by Goetterescu** [comment]
> Did you use the mapping tool in order to set uo your controller for RoR? Or did you install a map from the forum for your controller?

I guess that we can close the issue. The user most likely didn't use a correct map for his wheel
