### ISSUE TITLE
Cruise Control

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#278]
It would be nice to have a cruise control function in RoR.

Not much else to say.

**Comment by only-a-ptr** [comment]
RoR has a cruise control: http://www.rigsofrods.com/wiki/pages/Truck_Description_File#Cruise_Control

However, it's broken at the moment: http://www.rigsofrods.com/threads/119110-Test-Build-Rigs-of-rods-0-4-5-0-dev?p=1382970&viewfull=1#post1382970

I'll look into it, it's likely another spawner bug.

**Comment by only-a-ptr** [comment]
Ok, it appears the CruiseControl feature is not currently present in RoR.
To be done after 0.4.5 is released.

**Comment by gigapouch** [comment]
Yay! 0.4.5 is released, but cruise control is not working yet. I'm guessing that is what you are working on since it is released...

**Comment by Max98** [comment]
@gigapouch 
> To be done after 0.4.5 is released.

**Comment by ulteq** [comment]
Fixed: https://github.com/RigsOfRods/rigs-of-rods/pull/633
