### ISSUE TITLE
Did you use the mapping tool in order to set uo your controller for RoR? Or did you install a map from the forum for your controller?

### ISSUE THREAD

**Issue by Locusfan** [RigsOfRods/rigs-of-rods#2791]
Did you use the mapping tool in order to set uo your controller for RoR? Or did you install a map from the forum for your controller?

What do you mean

**Comment by tritonas00** [comment]
> Did you use the mapping tool in order to set uo your controller for RoR? Or did you install a map from the forum for your controller?
> 
> What do you mean
