### ISSUE TITLE
Weird physics behaviour for certain vehicles with OpenGL renderer (DirectX for Ogre 2.0)

### ISSUE THREAD

**Issue by Hiradur** [RigsOfRods/rigs-of-rods#28]
The easiest way to test this is to use OpenGL, load simple2 terrain and spawn a Gavril MV4 and activate it.
Sometimes it breaks immediately, sometimes it requires some driving around, sometimes resetting it triggers it, sometimes time alone will trigger it. The higher the FPS the bigger the impact (I think).

**Comment by Hiradur** [comment]
Two things I noticed so far: 
CMakeLists.txt in source/main mentions that Angelscript may mess with the physics engine if it's not compiled with CLEAR_FPU_STACK defined. I rebuilt AS with CLEAR_FPU_STACK but this didn't solve it. Could be interesting for other things though.

If 'K' is pressed to show the skeleton of the vehicle it breaks apart immediately. So this may be related to the rendering of beams. So far it felt like the search for a needle in a haystack.

**Comment by Aperion** [comment]
Any chance this is due to the variable physics time step based on the frame
rate?

**Comment by Hiradur** [comment]
Could be. So far I thought that the frame rate is too high to have an impact. It's worth a look though. Maybe it's not the frame rate but the frame time jidder. Got to look into how this actually works.

**Comment by Max98** [comment]
Talking about frame rate and and physics time step, I tried last time doing some kind of slowmotion feature like BeamNG, and the first thing i noticed is when you slow down the simulation, beams get weaker and weaker until it all explodes for no reason.

Here's the code if you want to test. https://github.com/Max98/ror_nextstable_gui/tree/SimTimeManager

**Comment by Aperion** [comment]
@Max98 Most of the RoR slowmotion videos came from using the replay feature, I think Kitteh(or what ever his name is now, I swear he changes his name more than my wife changes shoes.) was one of the first to do it.

**Comment by Max98** [comment]
@Aperion I remember seeing one of the users use Cheatengine to slow down the simulation actually. The replay feature doesn't have the possibility to slowdown simulation if i'm not mistaken.

**Comment by Aperion** [comment]
@Max98 IIRC it does or can but I haven't used it in a long time. All it does is store node positions in some container with a time stamp, then on replay the nodes are set top the stored positions.

**Comment by Hiradur** [comment]
Today I found out that if the frame rate is below 20 FPS (forced by activating debug information for beams) then vehicles behave normally. So it may very well be related to the physics time step since its locked to 100 steps at <=20 FPS.

**Comment by Max98** [comment]
Nice discovery there, but why it doesn't do the same for DirectX then?

**Comment by Hiradur** [comment]
The answer to this question may be a part of the solution.

**Comment by Hiradur** [comment]
So I already spent many hours debugging this but got nowhere and ran out of ideas. Help would be appreciated.

This is what I know so far:
- 0.38 does not have this issue
-> 0.4 brought multi-threading and new terrain format, maybe the issue lies there

- If FPS are below 20 FPS vehicles seem to behave normally
-> may have to do something with the timestep but timestep detection seems to work correctly with OpenGL

Vehicles related to this issue:
MV4: http://www.rigsofrods.com/threads/84411-Gavril-MV4 (also most of the other cars from gabester)
Audi 80: http://www.rigsofrods.com/threads/87177-Audi-80-B2-CC-%28Download-link-on-page-17-post-327%29?p=1095982&viewfull=1#post1095982
BMW E39: http://www.rigsofrods.com/threads/114599-Update-Page-14-BMW-E39-%285-series-1995-2003%29

**Comment by Max98** [comment]
Last time I wanted to make a slowmotion system, and when I made it to slowdown the physics step, all vehicles began to act weird and explode. (This is one Windows w/ DirectX) So my theory is simply that the physics engine is in a pretty bad state and needs a total re-factoring.

**Comment by Max98** [comment]
I have an other theory also. I think that few simulated values are depending on "delta time" while others don't. Which can cause these types of glitches and bugs.

**Comment by Max98** [comment]
This problem now happens for both OpenGL and DirectX using Ogre 2.0

**Comment by only-a-ptr** [comment]
2 cents:

At the moment, timing in RoR simulation works like this:
1. Main thread calls invokes OGRE to render a frame.
2. Ogre invokes FrameListener::frameStarted(deltatime). Deltatime is seconds since last frame, and there is a smoothing mechanism in place: http://www.ogre3d.org/forums/viewtopic.php?f=1&t=28584. I think in RoR it stays at default, whatever that is.
3. Physics are simulated (threaded or not - same code) by slicing the deltatime into chunks of almost-constant size cca 500 microseconds (plus minus couple microseconds): 
> number of phys steps: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/physics/Beam.cpp#L1521 (deltatime)
> actual deltatime per step: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/physics/Beam.cpp#L1589
4. Repeat.

This design is not optimal and the code is a huge mess. However, it's not hopeless - the basic requirement of physics (constant time step) is satisfied pretty well. In fact, it works a lot better that I long feared.

**Comment by Hiradur** [comment]
What if the Direct3D 9 renderer in OGRE has a bug which has been fixed in Ogre 2.0? So that OpenGL actually is correct and RoR has been fine-tuned for a faulty D3D9 renderer?
I consider this to be unlikely though since older releases of RoR using older versions of Ogre also show this behaviour so it would have to be a long standing bug.

What's the situation like with D3D9 and Ogre 1.9 on Windows?

With OpenGL I made RoR output ```dt``` after every frame and it was always correct (16.6ms for constant 60FPS), perhaps it's different with D3D9.

**Comment by only-a-ptr** [comment]
@Hiradur Please investigate: 
* Does threading ON/OFF has any effect on this? 
* What OGRE_THREADING_LEVEL is our dependency-OGRE compiled with? Can it be determined? 

AFAIK Directx9 internally synchronizes it's operations, while OGL does not. RoR does some gfx right from the physics code, and unless OGRE explicitly synces those operations, then it's up to the underlying graphics API.

Further, RoR is heavy on draw calls (i.e. batches) and those are known to be more expensive under OGL 2x than DX9. This would cause different framerates and as a result, different physics behavior because under current RoR architecture, different FPS will yield slightly different results.

**Comment by Hiradur** [comment]
@only-a-ptr 

> I'm willing to test for you, just specify the scenario.

The easiest way to test this is to use OpenGL, load simple2 terrain and spawn a Gavril MV4.
Sometimes it breaks immediately, sometimes it requires some driving around, sometimes resetting it triggers it, sometimes time alone will trigger it. The higher the FPS the bigger the impact.

> Does threading ON/OFF has any effect on this?

Threading does not have an impact on this.


> What OGRE_THREADING_LEVEL is your OGRE 2.0 built with?

I can't find any information on that macro, are you sure it exists?
Anyway, I never set it so it should be the default value.

**Comment by only-a-ptr** [comment]
@Hiradur Sorry my bad, the macro is OGRE_THREAD_SUPPORT
