### ISSUE TITLE
Ability to pick up and place small loads

### ISSUE THREAD

**Issue by ghost** [RigsOfRods/rigs-of-rods#280]
It would be great to be able to place small to medium sized loads (Up to a certain size, like 200kg) and place them onto a trailer or the back of a pickup truck. Here's an example of what I was thinking of in terms of loads: http://www.rigsofrods.com/repository/view/4824

Also it would be nice to turn off the ability to walk through vehicles and loads, to make this easier.

**Comment by Hiradur** [comment]
It would be nice if RoRBot could pick up small loads and throw them. This way it would be more realistic and not too easy.
Is this what you mean?

**Comment by gigapouch** [comment]
Yes, kind of like the game Utility Vehicle Simulator. I found a good video that shows what I'm talking about in the first 30 seconds: https://www.youtube.com/watch?v=klRrvDkK_u4

**Comment by Hiradur** [comment]
Looks like what I had in mind. It would be a nice addition.

**Comment by gigapouch** [comment]
Cool!

**Comment by only-a-ptr** [comment]
Yes, this would be nice.
We'll get back to it after 0.4.5 is done.

**Comment by Hiradur** [comment]
I just had an idea: What if RoRBot's arm was controllable similar to how you can control Anne's arm in Jurassic Park Trespasser (https://youtu.be/qDygOyud2Xk?t=588 )?
This would open up a whole new world of interaction.

**Comment by CuriousMike56** [comment]
With the current "move anything with backspace" feature, I don't think this is necessary now and can be closed.

**Comment by tritonas00** [comment]
Yes, now is absolutely possible to do such things.
