### ISSUE TITLE
Resolution glitched

### ISSUE THREAD

**Issue by haydenwalker980** [RigsOfRods/rigs-of-rods#2800]
After launching the game on my system (Linux Mint 20, 64 bit, non-snap version) the resolution is bugged massively. It was originally 1440x900 but now it has been downscaled to 1024x768.
I even rebooted, the problem still exists, somehow. How would I fix this?

**Comment by tritonas00** [comment]
the resolution of your screen or RoR's?

**Comment by haydenwalker980** [comment]
The resolution of my screen. Trust me I wouldnt be making an issue if it was the games resolution.

**Comment by tritonas00** [comment]
well mint should have a gui utility to set the screen resolution im sure, in control panel or something (i use Arch)

did your run RoR at full screen or windowed?

**Comment by haydenwalker980** [comment]
Windowed
Yes Mint has a utility to change screen resolution but it wont let me go above the current one.
![image](https://user-images.githubusercontent.com/37120379/135194965-7c936147-417a-442e-84ce-f23b0ea262b7.png)

**Comment by tritonas00** [comment]
I cant think any possible way RoR could do this

@AnotherFoxGuy any idea?

**Comment by haydenwalker980** [comment]
I had just installed MitCity to the content folder...idk how that would be why but theres that info

**Comment by tritonas00** [comment]
are you sure mint didn't do any background updates?

also check /etc/X11/xorg.conf

**Comment by haydenwalker980** [comment]
Nonexistent according to terminal

**Comment by haydenwalker980** [comment]
Ok I genuinely have no idea how but its back at full resolution.
