### ISSUE TITLE
Parameter called worldViewProj does not exist.

### ISSUE THREAD

**Issue by mickeymgk** [RigsOfRods/rigs-of-rods#2823]
It crashes when initializing windows saying 
"Known names are: YFlipScale in GpuProgramParameters::_findNamedConstraintDefinition"

**Comment by tritonas00** [comment]
what gpu?

**Comment by mickeymgk** [comment]
Intel(R) Iris(TM) Graphics 5100
GL_VERSION 4.3.0.0 
Other ogre projects runs smoothly including the ogre samples.

**Comment by tritonas00** [comment]
This happens when you mixup latest Ogre / older MyGUI

https://github.com/RigsOfRods/rigs-of-rods/pull/2858/commits/056d9b5ea92b836dec1212526b0404d3772442ad#diff-822933377d220f36ec1139adfeaaca09c146b6fcee265552c587caca1428d3ee
