### ISSUE TITLE
Slow Motion

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#283]
I think slo-mo would be a great addition to RoR, to show crashes in detail. There could be 0.5x, 0.25x, 0.125x, so on.

**Comment by Max98** [comment]
I've worked on Slow motion before, and all I can say is that this will need a physics system refactor because synchronization with delta_time is not correct in there.

**Comment by ulteq** [comment]
https://github.com/RigsOfRods/rigs-of-rods/pull/581
