### ISSUE TITLE
a build error

### ISSUE THREAD

**Issue by denk1** [RigsOfRods/rigs-of-rods#2842]
While compiling on Linux why does FreeImage library try to build in C++17,
I am getting these errors:
Source/OpenEXR/Imath/ImathVec.h:228:41: error: ISO C++17 does not allow dynamic exception specifications
  228 |     const Vec2 &        normalizeExc () throw (IEX_NAMESPACE::MathExc);
      |                                         ^~~~~
Source/OpenEXR/Imath/ImathVec.h:232:48: error: ISO C++17 does not allow dynamic exception specifications
  232 |     Vec2<T>             normalizedExc () const throw (IEX_NAMESPACE::MathExc);
      |                                                ^~~~~
Source/OpenEXR/Imath/ImathVec.h:440:41: error: ISO C++17 does not allow dynamic exception specifications
  440 |     const Vec3 &        normalizeExc () throw (IEX_NAMESPACE::MathExc);
      |                                         ^~~~~
Source/OpenEXR/Imath/ImathVec.h:444:48: error: ISO C++17 does not allow dynamic exception specifications
  444 |     Vec3<T>             normalizedExc () const throw (IEX_NAMESPACE::MathExc);
      |                                                ^~~~~
Source/OpenEXR/Imath/ImathVec.h:622:37: error: ISO C++17 does not allow dynamic exception specifications
  622 |     const Vec4 &    normalizeExc () throw (IEX_NAMESPACE::MathExc);

**Comment by AnotherFoxGuy** [comment]
That seems to be a bug in the freeimage makefile, it can be fixed with this patch: https://github.com/AnotherFoxGuy/ror-conan-recipes/blob/main/freeimage/all/patches/3.18.0/cpp11.patch

**Comment by denk1** [comment]
Excuse me how can I do it if I take the FreeImage library from the Conan packet manager? I'm not able to fix the Makefile of that library?

**Comment by denk1** [comment]
I've tried building that with your build.py however I got the same errors

**Comment by AnotherFoxGuy** [comment]
What Linux distro are you using?

**Comment by denk1** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

**Comment by AnotherFoxGuy** [comment]
I just tried building RoR in a new Ubuntu 21.10 VM and got it to build without any issues
What method did you use to build? (with conan or with ror-dependencies or completely manual)

**Comment by denk1** [comment]
I use this command:
**cmake -GNinja -DCMAKE_BUILD_TYPE=Release ../**
Is it OK?
