### ISSUE TITLE
North St. Helens: Odd terrain color

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#285]
In 0.4.5, the terrain is kind of bluish while in 0.38.67 it is more brownish.

**Comment by tritonas00** [comment]
See max98 reply here-> https://github.com/RigsOfRods/rigs-of-rods/issues/174

**Comment by Hiradur** [comment]
If this is a conversion mistake it's not an issue with RoR itself so this should be closed.
