### ISSUE TITLE
Mercedes Benz Atego w/ Comax truck crashes game

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#286]
The MB Atego Comax truck with the red box in the back crashes the game, while the other Comax truck is missing a cab (except for the steering wheel). This is in 0.4.5 TB 3.

**Comment by only-a-ptr** [comment]
@gigapouch Please confirm I got the right links:

MB Atego Comax http://www.rigsofrods.com/repository/view/2497
the other Comax truck: http://www.rigsofrods.com/repository/view/1805

I'll check.

**Comment by gigapouch** [comment]
The trucks I'm using are in the first link. I haven't downloaded the trucks in the second link though.

**Comment by only-a-ptr** [comment]
Already fixed, should be working in next test build.
