### ISSUE TITLE
RoR crashes when pressing Ctrl+Del while holding Backspace

### ISSUE THREAD

**Issue by TheDude53** [RigsOfRods/rigs-of-rods#2860]
### Steps to reproduce
1. Open RoR
2. Pick a terrain and spawn something
3. While in whatever you spawned, hold Backspace and press Control+Delete.

### Expected behavior
The car would be removed and the Backspace keystroke would be disregarded.

### Actual behavior
RoR briefly freezes before crashing

### System configuration
OS: Windows 10 64-bit
Renderer used: DirectX 9

### Additional information, logs and screenshots
Reproducible with the current master branch  
RoR.log does not contain any error messages

**Comment by tritonas00** [comment]
Will check

**Comment by WillMichals** [comment]
I am able to reproduce with same system.
