### ISSUE TITLE
failed to build terrain.default.as

### ISSUE THREAD

**Issue by tigercoding56** [RigsOfRods/rigs-of-rods#2865]
on loading any map on a raspberry pi  4 b 8 gb ram with archlinuxarm as operating system having installed rigs of rods using snap  the expected behavior of me is that rigs of rods opens and it does not get a error 
but  i get the following error [Screenshot from 2022-03-10 20-48-28](https://user-images.githubusercontent.com/90169211/157575782-4a791518-5f96-4861-9b46-79133b10b520.png)

also the terrain appears white except parts of it on some maps like the racetrack map 
here is my ror.log

its using OPENGL as renderer (with rpi-liux kernel installed ) 
also i posted this because i think the white texture issue someone had earlier was a different error

[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/8219733/RoR.log)

**Comment by tritonas00** [comment]
> also the terrain appears white except parts of it on some maps like the racetrack map

you need nvidia-cg-toolkit for that to work

**Comment by tigercoding56** [comment]
i looked at what the packagebuild for it does it downloads binarys for x86 while the raspberry pi uses the ARM architecture
so that won't work

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

------- Original Message -------

**Comment by paroj** [comment]
there is no Cg for ARM

**Comment by tigercoding56** [comment]
ok then maybe the issue should be retitled better support for ARM64
i'll just close this and wait for someone to make a seperate issue
thx for explaining
------- Original Message -------

**Comment by HanoJing** [comment]
@tigercoding56 Hi, How did you even get an ARM64 binary that works? Did you compile it?

I guess I need to try and compile and older version of rigsofrods.
