### ISSUE TITLE
Polonez 1600 car spawns with 1 wheel

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#288]
In 0.4.5 TB 3, the Polonez 1600 only spawns with one wheel.
![screenshot_12](https://cloud.githubusercontent.com/assets/7621364/8466675/08fd0ca0-200a-11e5-8485-6b624055607b.jpg)
![screenshot_13](https://cloud.githubusercontent.com/assets/7621364/8466678/0c3c1294-200a-11e5-85c6-1463c243fdcb.jpg)

**Comment by Hiradur** [comment]
Download link for the vehicle, please.

**Comment by DirtGamer301** [comment]
Link: http://www.rigsofrods.com/repository/view/5561
+I can confirm this bug

**Comment by only-a-ptr** [comment]
Fixed in my repo.
