### ISSUE TITLE
Chevrolet P30 vans spawn without body

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#289]
I know, there's lots of spawning bugs. In the latest build of 0.4.5, P30 vans spawn without a body, but with just wheels, seats, and a steering wheel.
![screenshot_11](https://cloud.githubusercontent.com/assets/7621364/8466698/3a3b63d4-200a-11e5-933b-9f6aa70a5851.jpg)

**Comment by Hiradur** [comment]
Download link for the vehicle, please.

**Comment by DirtGamer301** [comment]
This one I think: http://www.rigsofrods.com/repository/view/948
+It seems to be a bug with the submesh only imo

**Comment by only-a-ptr** [comment]
Fixed in my repo

**Comment by only-a-ptr** [comment]
Released as part of test build 4.
