### ISSUE TITLE
I can't open RoR

### ISSUE THREAD

**Issue by Senpai-Zenith** [RigsOfRods/rigs-of-rods#2902]
Can anyone  help me with this
![Screenshot 2022-05-15 003441](https://user-images.githubusercontent.com/105559338/168441296-9847b9d0-c8dd-4a21-85ab-3545cdc0a66d.png)

**Comment by tritonas00** [comment]
Do you have an antivirus enabled?

**Comment by Senpai-Zenith** [comment]
> Do you have an antivirus enabled? It might be the case that it deletes the file once its created by RoR.

I don't have any antivirus

**Comment by tritonas00** [comment]
Does your windows username contain special characters?

**Comment by Senpai-Zenith** [comment]
yeah. it is why?

> Does your windows account username contain special characters?

**Comment by tritonas00** [comment]
Yep, see https://docs.rigsofrods.org/gameplay/general-faq/#errors-glitches for a workaround

It will be fixed when we update to OGRE 13

**Comment by Senpai-Zenith** [comment]
> Yep, see https://docs.rigsofrods.org/gameplay/general-faq/#errors-glitches for a workaround
> 
> It will be fixed when we update to OGRE 13

I saw this first when i debugging on it but theres no problem as mine

**Comment by tritonas00** [comment]
> > Yep, see https://docs.rigsofrods.org/gameplay/general-faq/#errors-glitches for a workaround
> > It will be fixed when we update to OGRE 13
> 
> I saw this first when i debugging on it but theres no problem as mine

It should work

**Comment by Senpai-Zenith** [comment]
its no good for me  i cant run it i even did change my name in username with normal and i did the task on but still no good at all

**Comment by tritonas00** [comment]
> its no good for me i cant run it i even did change my name in username with normal and i did the task on but still no good at all

Can you upload RoR.log?

**Comment by Senpai-Zenith** [comment]
were should i find that?

**Comment by tritonas00** [comment]
> were should i find that?

`Documents\My Games\Rigs of Rods\logs`

**Comment by Senpai-Zenith** [comment]
I dont have ror.log

**Comment by tritonas00** [comment]
> I dont have ror.log

check `C:\Program Files\Rigs of Rods\config/logs` then

**Comment by tritonas00** [comment]
> I dont have ror.log

Can you post the contents of `C:\Program Files\Rigs of Rods\config` ?

**Comment by Senpai-Zenith** [comment]
![image](https://user-images.githubusercontent.com/105559338/168555866-3590e2e0-7211-424d-8a82-0b77c7331b09.png)

**Comment by tritonas00** [comment]
Resolved in discord
