### ISSUE TITLE
[suggestion] Disable "Default Skin" option through skinzip

### ISSUE THREAD

**Issue by WillMichals** [RigsOfRods/rigs-of-rods#2909]
Hello all,

I am writing this request as it is a problem I am currently facing.

I think it would be useful to be able to disable the "Default Skin" option apparent when selecting a skin. This could be useful for people creating vehicles or things that require a skin to be selected and in that context having the "Default Skin" option may not make sense. 

This could just be defined inline in the .skin file, similar to how `disabledefaultsounds` works in the `.truck`. Ideally, you would just be able to place `disabledefaultskinoption` inside the .skin file and any vehicle that matches the GUIDs would be affected. Let me know what you think.

Will

**Comment by only-a-ptr** [comment]
Hello Will,

I don't like the feature you're suggesting - it gives too much power to the skin creator. There's always a default skin, it's just the textures and materials which come with the mod, and the player may ayways want to use it, regardless of what skinzips they have installed.

I think the base problem here is that the default skin cannot have name/description/authors, it's just "default" whatever it represents. Well, I could add a `; skin <name>, <description>, <author>` element to the .truck format to even the odds.
