### ISSUE TITLE
Minimap doesn't get unloaded with map change

### ISSUE THREAD

**Issue by Hiradur** [RigsOfRods/rigs-of-rods#292]
### Steps to reproduce
1. Load a map
2. Open minimap with Tab
3. Go back to menu
4. Load another map

### Expected behaviour
No minimap is shown after loading another map

### Actual behaviour
The minimap of the map that was loaded before is seen and doesn't disappear even when opening and closing the minimap for the current map

### System configuration
OS: Xubuntu 14.04
Renderer used: OpenGL

### Additional information, logs and screenshots (optional)
<a href="http://abload.de/image.php?img=map_bughqu80.jpg"><img src="http://abload.de/thumb/map_bughqu80.jpg" /></a>

**Comment by Max98** [comment]
Perfect example of how to report a bug.
