### ISSUE TITLE
FileNotFoundException spam in RoR.log

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#2956]
Load mitcity terrain (in game repo)

```
FileNotFoundException: Cannot locate resource icon_Truckshop.dds in resource group TexturesRG. in ResourceGroupManager::openResource at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreResourceGroupManager.cpp (line 704)
```

massively spams RoR.log resulting in hug text file. And i think it can hurt performance also.

**Comment by CuriousMike56** [comment]
My RoR.log only shows 4 `FileNotFoundException` errors, none of them relating to `icon_Truckshop.dds`. File size is also only 227 KB. Possibly an OpenGL issue?

**Comment by tritonas00** [comment]
Did you test with latest master?

**Comment by CuriousMike56** [comment]
Yes.

**Comment by tritonas00** [comment]
My cache was screwed up.
