### ISSUE TITLE
Game Crashed when opening

### ISSUE THREAD

**Issue by Yannickn228** [RigsOfRods/rigs-of-rods#2975]
I was playing ROR for 2 years and then it doesn't like me anymore. Can you fix it please?

**Comment by CuriousMike56** [comment]
Upload your RoR.log. Assuming you're on Windows, this is located at `Documents\My Games\Rigs of Rods\logs`

Also this is the development repo, please post on the forum next time: https://forum.rigsofrods.org/forums/game-support.8/

**Comment by CuriousMike56** [comment]
I think this can be closed, nearly two weeks without any response.
