### ISSUE TITLE
spawn vehicle flotilla with script event

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#298]
> I checked the scripting docs and did not find what I was looking for..
> It seems there is only a function to spawn an odef-object - but none for the vehicles!
> 
> so either I am blind, or we need a function to spawn a N/B-Object..
> 
> Why:
> 
> on a terrain, we could create one or more event box, that produces a set of vehicles if you enter..
> Flotilla-Spawning
> 
> => on a parking lot, there are Info-Plates like
> 
> "step in this area if you want truck A, the trailer B and a 20 foot container spawned"
> 
> the script that does this, will have a set of predefined coordinates, so all vehicles stand in the right position
> so the player can step in the truck and lock on to the trailer etc..
> the next event box, could create a train and 3 waggons on the track readdy to be connected..
> that would make a game session less complicated until you got all you need..
> 
> those vehicles do not have to be locked to each other - but just be all there..
> 
> so a train station could offer a complete passenger train or a short/long bulk train - depending on the event box you trigger..
> if that function is available, the script to do that is kind of simple..
> 
> Alternative for the train example: make 3 paralell tracks and preload dozens of vehicles => lag
> to be able to offer a flotilla spawn would be nicer and slimmer I think..
> 
> does that sound usefull?

*This was copied from the RoR forum. [Original thread.](http://www.rigsofrods.com/threads/96558-spawn-vehicle-flotilla-with-script-event-(feature-request))*

**Comment by only-a-ptr** [comment]
Sounds very useful. The scripting interface needs expansion.
However, it's not a priority at the moment.
