### ISSUE TITLE
[request] Add the ability to select individual gears in manual shift - auto clutch mode, instead of only having the option of sequential shifting.

### ISSUE THREAD

**Issue by sheetan22** [RigsOfRods/rigs-of-rods#2995]
I've run into an issue where I cannot map my Logitech g920 shifter the way I would like it. I would really like to set up my shifter like a power glide transmission. However, rigs of rods only gives me a sequential, shift up, and shift down option to use when it is in manual shift - auto clutch mode. The Logitech g920 is an h pattern shifter, I basically would like to have the ability to map the shifter to specific gears and be able to shift through them like in full manual-stick shift mode. but without having to use the clutch. Hopefully, I made a little bit of sense.

**Comment by only-a-ptr** [comment]
Hello @sheetan22,

sorry about the response lag and thanks for the request, it absolutely makes sense to have support for this type of controller.

I looked into the internal input events table and it looks like we already have everything you need: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/utils/InputEngine.cpp#L176-L194. I'm assuming the H-shifter hardware reports to the game as an array of `JoystickButton`-s, where each gear position is a button and possibly the neutral position is also a button. You should be able to get it working by just mapping these 'buttons' to these events.

I looked in our docs https://docs.rigsofrods.org/gameplay/controls-config and found no mention of shifting at all - the "all valid keypress events" table https://docs.rigsofrods.org/gameplay/controls-config/#keypress-events doesn't even list the shift-up/down events.

Let me know if this worked for you and we'll update our docs.

**Comment by sheetan22** [comment]
Hi there @only-a-ptr, I was able to assign the shift directly options to the h-shifter, and it works just fine when you are in "full manual stick shift mode". However, I don't think we are on the same page when it comes to what I'm asking for. I can easily set up the shift directly options on the h-shift by assigning them as a joysrickbutton. However, my issue is that I can only shift gears directly when I'm holding the clutch down in "full manual stick shift mode". I would like to have the option to shift directly to another gear, without having to hold the clutch down, just like a power glide transmission. Basically, the ability to directly shift to another specific gear while being in "manual shift, auto clutch mode". While using the h-shifter in "manual shift auto clutch mode", I am only given the ability to move the shifter up and down to shift gears. Hopefully I made more sense, or maybe I just didn't quite understand what you commented.

**Comment by only-a-ptr** [comment]
Hello again @sheetan22 and please excuse the delayed response.

Apparently I didn't pay attention to your post, it mentions the shift mode clearly (even in title!) but I got fixated on the input events.

Either way, I looked into the code and indeed, the direct shifting is not evaluated at all in "manual shift - auto clutch" mode. I'll try adding it.
