### ISSUE TITLE
Rotating camera with mouse shows vehicle buttons menu

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2998]
Currently the 'vehicle buttons' menu shown at the top left of the screen always appears when you hover over it with the mouse. If you are rotating the camera with the mouse (holding right click) and happen to move the mouse to the top left, the menu will appear regardless. It would be nice if this didn't happen.

**Comment by tritonas00** [comment]
Same with top menu. Should be easy to fix though.
