### ISSUE TITLE
Missing managedmaterials specular texture results in white meshes

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#3005]
Effected mods: 
[Lancaster Bomber](https://forum.rigsofrods.org/resources/lancaster-bomber.203/)
[M/V Nordia Express](https://forum.rigsofrods.org/resources/m-v-nordia-express.191/) (old version)

Similar issue as #2999. In previous versions, managed material lines with a missing or invalid specular image would simply ignore the error and load the material with no specular. Now in 2022.12+, the line(s) are ignored and you end up with solid white meshes.

2022.04:
![image](https://user-images.githubusercontent.com/46073351/211455488-adddfa7a-de66-427b-8d9b-3904f0f8c5e4.png)
![image](https://user-images.githubusercontent.com/46073351/211457282-5ca7ce91-fc7e-4de9-b574-2b1fc9d64155.png)

Master:
![image](https://user-images.githubusercontent.com/46073351/211457058-0c04ea23-4e8e-472d-abe5-5173348e25e0.png)
![image](https://user-images.githubusercontent.com/46073351/211457376-accf245c-2c76-4e40-81c9-533a50409783.png)

**Comment by only-a-ptr** [comment]
The new checks were introduced in https://github.com/RigsOfRods/rigs-of-rods/commit/0e8e64644c685ccdd1904c53260269d1473406a0
