### ISSUE TITLE
Blender 3.0 Heightmap Terrain Major Issues

### ISSUE THREAD

**Issue by The-Keystoner** [RigsOfRods/rigs-of-rods#3012]
I left a post on the forums about this about a month ago and decided to wait so I thought that this would be a reasonable time to reach out to the GitHub section. Anyway I am attempting to make a very detailed map, I followed only_a_ptr's tutorial and it was extremely helpful and actually taught me some things. However my terrain does not show up in Rigs of Rods at all, I put it in a positive position on the coordinate plane, exported it properly and I even tested the .mesh by pressing CTRL+Y followed by ENTER. On few occasions it has showed up and I went on further to start modeling terrain objects but to find out there was nothing there when I loaded on the map a second time. I also had to export it with the default axis because for some reason when I selected the OGRE Standard it did the opposite of what it should have and the terrain was sticking vertically through the default base. 

![screenshot_2022-12-17_21-00-45_1](https://user-images.githubusercontent.com/123614333/216312899-73768249-fa44-40c8-9ceb-7b5625560ed0.png)

![screenshot_2023-01-22_14-51-23_2](https://user-images.githubusercontent.com/123614333/216312929-e4162dc1-fdba-4c35-be48-ef4f2f17240a.png)
![screenshot_2023-02-02_06-27-50_1](https://user-images.githubusercontent.com/123614333/216313001-00c33ebb-3228-43a2-92fd-f664cf4638db.png)

**Helpful Information:**
Rigs of Rods 2022.04

Windows 11 PC

Intel i7-9700k/RTX 2060 Super/16 Gb of Ram

**Comment by only-a-ptr** [comment]
Hello,

I can't seem to find your post on the forum, please give me a link.

Anyway, a lot of things can go wrong here: the object origin in Blender, the object vs. mesh size in Blender, the ODEF file for the terrain mesh, the TOBJ placement of the ODEF, the TERRN2 referencing the TOBJ. To figure out anything, I need to have all these files, including the Blender project and RoR.log from your machine.

If you don't want to share the Blender project, you'll have to create a smaller test project with all the accessories and share that.

**Comment by The-Keystoner** [comment]
> Hello,
> 
> I can't seem to find your post on the forum, please give me a link.
> 
> Anyway, a lot of things can go wrong here: the object origin in Blender, the object vs. mesh size in Blender, the ODEF file for the terrain mesh, the TOBJ placement of the ODEF, the TERRN2 referencing the TOBJ. To figure out anything, I need to have all these files, including the Blender project and RoR.log from your machine.
> 
> If you don't want to share the Blender project, you'll have to create a smaller test project with all the accessories and share that.

Thank you, and yes I understand due to the fact that RoR is still working out bugs therefor there are lots of things that can go wrong with content creation. Here is the link to the thread as you asked and the pack itself, I attempted to put a road mesh on and it screwed up more.
https://forum.rigsofrods.org/threads/overview-tap-map-issue.3818/
[Indiana_County_PA.zip](https://github.com/RigsOfRods/rigs-of-rods/files/10610230/Indiana_County_PA.zip)

**Comment by The-Keystoner** [comment]
> Hello,
> 
> I can't seem to find your post on the forum, please give me a link.
> 
> Anyway, a lot of things can go wrong here: the object origin in Blender, the object vs. mesh size in Blender, the ODEF file for the terrain mesh, the TOBJ placement of the ODEF, the TERRN2 referencing the TOBJ. To figure out anything, I need to have all these files, including the Blender project and RoR.log from your machine.
> 
> If you don't want to share the Blender project, you'll have to create a smaller test project with all the accessories and share that.
[Heightmap.zip](https://github.com/RigsOfRods/rigs-of-rods/files/10637306/Heightmap.zip)
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/10637307/RoR.log)

**Comment by The-Keystoner** [comment]
> Hello,
> 
> I can't seem to find your post on the forum, please give me a link.
> 
> Anyway, a lot of things can go wrong here: the object origin in Blender, the object vs. mesh size in Blender, the ODEF file for the terrain mesh, the TOBJ placement of the ODEF, the TERRN2 referencing the TOBJ. To figure out anything, I need to have all these files, including the Blender project and RoR.log from your machine.
> 
> If you don't want to share the Blender project, you'll have to create a smaller test project with all the accessories and share that.

**Comment by The-Keystoner** [comment]
- [ ]

**Comment by The-Keystoner** [comment]
sorry I was having trouble with GitHub just wanted to reply and say everything is solved now my apologies

**Comment by CuriousMike56** [comment]
@The-Keystoner Please close the issue If it has been resolved.

**Comment by The-Keystoner** [comment]
> @The-Keystoner Please close the issue If it has been resolved.

I know thank you I was just having trouble finding the button
