### ISSUE TITLE
fails to compile on Linux ARM64

### ISSUE THREAD

**Issue by HanoJing** [RigsOfRods/rigs-of-rods#3051]
Hi all, 

Rigs of Rods fails to compile because of either 
syntax errors in the code 
or the compiler being the wrong version.

I followed the guide on https://github.com/RigsOfRods/rigs-of-rods/wiki/Compile-(Linux).

Logs:

cmake: [cmake-output.log](https://github.com/RigsOfRods/rigs-of-rods/files/11667788/cmake-output.log)
ninja: [ninja-output.log](https://github.com/RigsOfRods/rigs-of-rods/files/11667789/ninja-output.log)

My specs and versions of (possibly) involved programs:

Motherboard: SolidRun HoneyComb LX2K
CPU: NXP LayerScape LX2160A Cortex-A72 (16c, 16t @2Ghz)
GPU: AMD Radeon RX580 XFX
RAM: 64G ECC

versions:
cmake: 3.25.1
ninja: 1.11.1
git: 2.40.1
gcc: 12.2.0

Thanks for any help in advance!

**Comment by vido89** [comment]
Try https://github.com/RigsOfRods/rigs-of-rods/wiki/Compiling-release-version-of-RoR-(Linux)-without-conan

**Comment by HanoJing** [comment]
> Try https://github.com/RigsOfRods/rigs-of-rods/wiki/Compiling-release-version-of-RoR-(Linux)-without-conan

Thanks for the quick reply!

I also tried to build the dependencies and they failed to build with -Wnarrowing errors:
https://dpaste.com/6V2AKQR53

Building the game itself with the method in the link also fails with the same error message.

**Comment by HanoJing** [comment]
@vido89 Sadly, RigsOfRods fails to build again, this time I think it's because I'm on Debian Sid.

[cmake.log](https://github.com/RigsOfRods/rigs-of-rods/files/12337636/cmake.log)

[make.log](https://github.com/RigsOfRods/rigs-of-rods/files/12337639/make.log)

I've been trying to compile RoR for natively for ARM64 for a while now.

Do you know, by any chance, how the RigsOfRods dev team compile the release builds? Which distribution do they build them on? Which package version do they use?

Thanks in advance.

**Comment by CuriousMike56** [comment]
@HanoJing Not sure about release builds, but the GitHub Actions builds use Ubuntu 22.04.

**Comment by HanoJing** [comment]
Hey back, Debian Sid recently updated parts of the compiler toolchain, RigsOfRods now compiles fine, errorless. The game is running absolutely great!

**Comment by CuriousMike56** [comment]
@HanoJing Most vehicle materials require `nvidia-cg-toolkit` installed, which unfortunately is closed source and (AFAIK) doesn't have an ARM64 build.

**Comment by HanoJing** [comment]
Important notice: On Debian Sid, There is white texture on the map, but roads and buildings and all are visible on NeoQueretaro for example and also more maps.

On Gentoo however, the whole texture of the map is white and the game is unplayable.

The reason for this difference is the OIS version:
Debian: libOIS-1.3.0.so
Gentoo: libOIS-1.5.1.so

libOIS-1.3.0.so has to be used in order to fix this issue.

**Comment by CuriousMike56** [comment]
Could you please upload the RoR.log files (located at `~/.rigsofrods/logs`) from both systems?

**Comment by HanoJing** [comment]
> Could you please upload the RoR.log files (located at `~/.rigsofrods/logs`) from both systems?

Sure. 

I just tested OIS-1.4.0 which works
also tested OIS-1.5.0 which does not work.

Gentoo RoR.log (RoR built with OIS-1.5.0 and having the issue):
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/12755942/RoR.log)

Debian RoR.log (RoR built with OIS-1.3.0 and not having the issue):
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/12755956/RoR.log)
