### ISSUE TITLE
Nodes far away from actor origin result in huge fps drop

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#3058]
As the title says, any nodes that are far away from the actor origin (defined by cameras/cinecam/extcamera?) will eventually cause the frame rate to plummet, rendering the game unplayable. This can be reproduced in a variety of ways, such as flinging detachable parts using the node grabber or by driving the Lotus Esprit with its cinecam nodes that are left behind on spawn. 

Attached is a test vehicle with a node that's very far away:
```
;far away node - kills framerate 
21,  100000,  0.1,  0.0, l 4
```
[faraway-node-fps-drop-test.zip](https://github.com/RigsOfRods/rigs-of-rods/files/11779731/faraway-node-fps-drop-test.zip)

You will likely have to press backspace for the issue to occur as it seems to rarely happen on initial spawn or when pressing the `I` key.

![RoR_2023-06-17_14-08-51](https://github.com/RigsOfRods/rigs-of-rods/assets/46073351/8b5ad59d-15e0-478a-b26e-8481e76f00b7)

**This bug is not present on 2022.12.**

**Comment by tritonas00** [comment]
# This bug is not present on 2022.12.

QFE
