### ISSUE TITLE
Important glitch when repairing vehicles

### ISSUE THREAD

**Issue by YottaMxt** [RigsOfRods/rigs-of-rods#3062]
### Steps to reproduce
1.Start a game
2.Spawn two or more vehicles
3.Try repairing each vehicles at least twice

### Expected behaviour
Repair the car and let it fall to the ground.

### Actual behaviour
Note: this issue is frequent but random, so it might be because of the vehicle, idk. When the glitch occurs, the vehicle stays suspended in the air, and all truck controls are stuck (assigned keyboard keys just don't work). Throttle and brake keys just move the vehicle in "ghost" mode (like when repairing vehicles but even without holding the appropriate key, the vehicle floats in the air without collisions nor physics and about the sound, the current pitch is constant as long as the vehicle is like this).

### System configuration
OS: Fedora 38
Renderer used: OpenGL

### Additional information
Although I think the vehicle doesn't matter, the used vehicles were [Ford Windstar LX Tenzo](https://forum.rigsofrods.org/resources/2003-ford-windstar-lx.249/) and [Audi 1.6 FWD](https://forum.rigsofrods.org/resources/audi-80.474/)

Fresh RoR.log attached (even if I cleared it before the test, and closed RoR after the glitch it's too long to just paste if here).
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/11842105/RoR.log)

**Comment by CuriousMike56** [comment]
Holding the backspace key for one second enters 'interactive repair' mode, which it sounds like you're activating by mistake: https://forum.rigsofrods.org/threads/the-fabulous-flying-forty-nine.3883/#post-19449

**Comment by CuriousMike56** [comment]
The interactive repair feature could be improved:
- Increase the hold timer from 1s to 2s (I usually hold backspace the entire time)
- Tell the player they've entered repair mode, and show hotkeys for the feature with a notification or window

**Comment by only-a-ptr** [comment]
I'd rather introduce a separate hotkey like Alt+Backspace than to tweak the hold-Backspace mode.

Anyway I'll add a state box on the top, like the "physics paused/terrain editing" one.
