### ISSUE TITLE
Some terrains load under OpenGL a lot slower compared to DirectX

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#307]
Tested on Windows 8.1 x64.
DirectX vs OpenGL 
Auriga : 2s vs 6s
Brutal Valley: 6s vs 8s
North St Helens: 4s vs 19s
North St Helens Suspended Monorail System:  5 s vs 39 s

**Comment by Hiradur** [comment]
What are your system specs?
My laptop (i5 2520M, HD 3000, SSD) loads nhelens in 4s and Auriga in 2s.
I'm using Xubuntu 14.04 with OpenGL.

**Comment by Speciesx** [comment]
i5 4670, Radeon HD 7870, SSD

![ror_2015_07_19_19_13_43_594](https://cloud.githubusercontent.com/assets/1196375/8766912/68203754-2e4a-11e5-96a0-4bd55bece1e0.png)
![ror_2015_07_19_19_13_56_422](https://cloud.githubusercontent.com/assets/1196375/8766913/68223a22-2e4a-11e5-85d2-a958e21e2404.png)
![ror_2015_07_19_19_13_37_640](https://cloud.githubusercontent.com/assets/1196375/8766914/68229076-2e4a-11e5-8140-52c7c8e4a66a.png)

**Comment by Hiradur** [comment]
I copied your settings and nhelens still loads in 4s. Could you set everything to minimum to see if it makes a difference?

**Comment by Speciesx** [comment]
No difference with minimum settings.

**Comment by Hiradur** [comment]
It would be great to get some more input from other users, ideally with GPUs from Nvidia, Intel and AMD to see if it's vendor specific.

**Comment by Olius** [comment]
nVidia GeForce 9600 GT (Wineskin)
North St Helens
-openGL: 14s
-DirectX 9: 14s
It takes a long time probably because my HDD has only ~20 gigs free and/or my computer is 6 years old.
It loads a lot slower than older versions though, probably because of the new real-time shading (right?).

**Comment by Hiradur** [comment]
i5 4570, SSD, Nvidia GTX 760, Windows 8.1
- OpenGL: 4s
- Direct3D9: 4s

Maybe it's AMD specific?

**Comment by Speciesx** [comment]
On Windows 10 x64 even little bit worse.
Auriga : 2s vs 7s
Brutal Valley: 6s vs 8s
North St Helens: 4s vs 22s
North St Helens Suspended Monorail System: 5 s vs 43 s

**Comment by Hiradur** [comment]
I can now oberve this with Auriga on i7 6700, SSD, Nvidia GTX 760, Xubuntu 15.10

"saving terrain pages" takes forever now.

**Comment by Hiradur** [comment]
I think this is related to the generation of the terrain cache (map.bin), since #566 all maps load very fast on Linux with OpenGL.

**Comment by ulteq** [comment]
So we disable the `.mapbins` all together?

**Comment by Hiradur** [comment]
@Speciesx Can this be closed?
