### ISSUE TITLE
remove current vehicle in cabin view crash ror

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#309]
Load a vehicle change to cabin view and now click "remove current vehicle" and ror will crash.

**Comment by only-a-ptr** [comment]
@Speciesx : I assume this happens with any vehicle.

However, always write a list of vehicles you tested with please. Thanks.

**Comment by only-a-ptr** [comment]
Fixed in my working copy, will be pushed later today.
