### ISSUE TITLE
If a vehicle spawned two times, mirrors work only on the first vehicle.

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#310]
Spawn the same vehicle two times, only on the first vehicle the mirrors will work.

**EDIT by only_a_ptr**: To clarify: Mirrors on the first vehicle will work normally, but mirrors on all subsequent vehicles will be linked to the first vehicle.

**Comment by Max98** [comment]
I think this is related to OGRE and materials being loaded only once..

**Comment by only-a-ptr** [comment]
@Speciesx : Please provide download links to vehicles which exhibit this behavior.

**Comment by DirtGamer301** [comment]
http://www.rigsofrods.com/threads/74698-Gavril-MZ2-now-with-fixed-suspension-geometry-and-better-driving-position!

**Comment by only-a-ptr** [comment]
@DirtGamer301 Thanks, I'm on it.

**Comment by Michael10055** [comment]
Fixed in #1271
