### ISSUE TITLE
Paused actor physics resume when switching to another actor

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#3105]
- Spawn two actors
- Press `END` key to pause physics for current actor
- Switch to the other actor, previous actor's physics will resume

https://github.com/RigsOfRods/rigs-of-rods/assets/46073351/bc072281-e17c-45ce-9133-5c57becf54e8

Also recently noticed the skeleton debug view disables itself when switching actors, possibly related?

**Comment by ohlidalp** [comment]
Here is the culprit (and yes, skeletonview related): https://github.com/RigsOfRods/rigs-of-rods/blame/master/source/main/physics/ActorManager.cpp#L745-L746 - it broke in https://github.com/RigsOfRods/rigs-of-rods/commit/9431e1b508575c40498ed9becd8a0385a3b95463 - I needed to reset the paused/skeleton after decoupling from the player vehicle. Doesn't make big sense for paused state but it's important with skeleton view.
