### ISSUE TITLE
Rigs of rods repository 

### ISSUE THREAD

**Issue by CoolPeep2** [RigsOfRods/rigs-of-rods#3114]
My repository in game does not work when ever i try to download a mod or remove a mod the install nor the remove button work, please solve the issue

**Comment by CuriousMike56** [comment]
What exactly do you mean by "doesn't work"? The mod doesn't download when you press install?

**Comment by CoolPeep2** [comment]
Yup exactly

**Comment by CoolPeep2** [comment]
Is there a way to fix it

**Comment by CuriousMike56** [comment]
Please upload your RoR log file after trying to download a mod. The file is located at `Documents\My Games\Rigs of Rods\logs`

**Comment by CuriousMike56** [comment]
If nothing exists in that directory, then you're experiencing the "Failure writing settings file" error described here https://docs.rigsofrods.org/gameplay/common-issues/

**Comment by CoolPeep2** [comment]
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/13837658/RoR.log)

**Comment by CoolPeep2** [comment]
![IMG_0718](https://github.com/RigsOfRods/rigs-of-rods/assets/155698906/bfc2b236-8647-4524-9259-d62363877157)

https://github.com/RigsOfRods/rigs-of-rods/assets/155698906/7b34cdac-8be5-491f-88cf-3b97ff649a10

**Comment by CoolPeep2** [comment]
Uploading IMG_0720.mov…

**Comment by CoolPeep2** [comment]
https://github.com/RigsOfRods/rigs-of-rods/assets/155698906/0d77ae6a-a5be-42b5-a494-385ef5ce83be

**Comment by CoolPeep2** [comment]
![IMG_0721](https://github.com/RigsOfRods/rigs-of-rods/assets/155698906/222d8040-a7ea-48fd-b59e-d86c388c40ef)

This is what it also says when i try to download a mod

**Comment by CuriousMike56** [comment]
Try uninstalling OneDrive, it prevents the game from accessing the Documents folder.

**Comment by CoolPeep2** [comment]
alright done

**Comment by CoolPeep2** [comment]
but is there another way without disabling my control folder access i like to keep mine on for saftey reasons

**Comment by CuriousMike56** [comment]
You can try allowing the game: https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/customize-controlled-folders?view=o365-worldwide#allow-specific-apps-to-make-changes-to-controlled-folders

**Comment by CoolPeep2** [comment]
Thank you very much you are a very kind person for taking your time on me to help me out i really appreciate it!

**Comment by CuriousMike56** [comment]
No problem, glad to help. One question though, did you install the game using the installer (`RoR_2022.12_Setup.exe`) or did you download the zipped release/dev build?

**Comment by CoolPeep2** [comment]
I used the installer

**Comment by CuriousMike56** [comment]
Was controlled folder access enabled before you installed RoR? Ran some tests in a virtual machine, controlled folder access didn't block the already installed version in Program Files but blocked a freshly downloaded developer build zip.

**Comment by CuriousMike56** [comment]
This can be closed, same with the above 3116 issue.
