### ISSUE TITLE
in-game repository is not working

### ISSUE THREAD

**Issue by nuke5223** [RigsOfRods/rigs-of-rods#3116]
i installed mod from in-game repository, but i cant see any mods i downloaded. how can i fix it?

**Comment by CuriousMike56** [comment]
Check if controlled folder access is enabled in Windows Defender, and if it is, either disable or allow RoR through it: https://github.com/RigsOfRods/rigs-of-rods/issues/3114#issuecomment-1878137600

**Comment by nuke5223** [comment]
> Check if controlled folder access is enabled in Windows Defender, and if it is, either disable or allow RoR through it: [#3114 (comment)](https://github.com/RigsOfRods/rigs-of-rods/issues/3114#issuecomment-1878137600)

i did it but it still doesn't work what should I do?

**Comment by CuriousMike56** [comment]
Please upload your RoR log file from `Documents\My Games\Rigs of Rods\logs` after trying to install a mod.

**Comment by nuke5223** [comment]
> Please upload your RoR log file from `Documents\My Games\Rigs of Rods\logs` after trying to install a mod.

its empty
<img width="587" alt="화면 캡처 2024-01-10 152642" src="https://github.com/RigsOfRods/rigs-of-rods/assets/156163145/e1b41470-f7f7-4e3a-bcfb-aa371ee8a692">

**Comment by CuriousMike56** [comment]
You're experiencing the "Failure writing settings file" error described here https://docs.rigsofrods.org/gameplay/common-issues/
Follow either method #1 or #2.
