### ISSUE TITLE
Just a few things that shoud be addressed.

### ISSUE THREAD

**Issue by Erie-E8** [RigsOfRods/rigs-of-rods#312]
Ok, 1: In 0.4.5.0, the doppler effect for the sounds are broken. In case you don't know what that is: https://en.wikipedia.org/wiki/Doppler_effect

2: Also with this latest test build my modded Ford Falcon seems to crash the game as soon as it spawns for no apparent reason at all. Dunno if this is a cache issue, but, it's annoying.

3: Someone has to figure out how to reduce the specular shininess of maps. It's more of an annoyance than an issue, but, I just thought I'd throw it in.

4: It also seems that the latest test build of RoR only supports up to 15 speeds in a vehicle, whereas RoR 0.4.0.7, and all versions before that down until around 0.37.xxx, supported I think up to 50 speeds in a vehicle.

By the way, could someone add labels to this?

**Comment by Hiradur** [comment]
It would be great if you could close this and open one ticket per issue. This makes coordination easier.
Include a link to your vehicle please.

**Comment by Erie-E8** [comment]
How do I go about closing this and reopening it? Also, my vehicle is a modded semi truck that I put an 18 speed gearbox in.

**Comment by Hiradur** [comment]
Leave this issue closed and open one ticket per issue e.g.

one for "doppler effect not working"
one for "reduce shininess of terrains"
...
see what other tickets look like if unsure.

about the truck:  only_a_ptr is our .truck expert. He will take care of this. But to not waste his time searching for the exact truck you are talking about you have to post a link. If it's private then send it to him via PM.


> By the way, could someone add labels to this?

Only developers can add labels. We will add labels to every ticket once we see it.

**Comment by Erie-E8** [comment]
Ok.
