### ISSUE TITLE
Modded Falcon randomly crashes as soon as it spawns.

### ISSUE THREAD

**Issue by Erie-E8** [RigsOfRods/rigs-of-rods#314]
In the latest test build my modded Ford Falcon seems to crash the game as soon as it spawns for no apparent reason at all. Dunno if this is a cache issue, but, it's annoying.

**Comment by Max98** [comment]
It would be great if you send us your modded falcon so we can check what's crashing it.

**Comment by Erie-E8** [comment]
Will do.

**Comment by Erie-E8** [comment]
The latest test build also seems to be crashing in MP when it remotely loads either my modded semi, the Box5W900, or the 37 ton semi trailer. It doesn't even throw any error codes in the logs.

**Comment by Max98** [comment]
It would be great if you open an other issue for that.
And I tested your falcon, it doesn't crash here.
