### ISSUE TITLE
Terrain shininess should be reduced.

### ISSUE THREAD

**Issue by Erie-E8** [RigsOfRods/rigs-of-rods#315]
Someone should figure out how to reduce the specular shininess of terrains. It's more of an annoyance than an issue, but, I just thought I'd throw it in.

**Comment by Speciesx** [comment]
a example terrain?

**Comment by Erie-E8** [comment]
N Helens is shiny, I think Baker Ranch is.

**Comment by Speciesx** [comment]
not really
![78c22342-2e13-11e5-97ac-5af039f9c309](https://cloud.githubusercontent.com/assets/1196375/8781349/bc15ec4a-2f0e-11e5-85ad-6b41e7af2e45.png)

**Comment by Erie-E8** [comment]
Still a bit too bright, specular wise.

**Comment by Speciesx** [comment]
This caused by caelum.

**Comment by Erie-E8** [comment]
Oh. Is there any way to reduce the specular effect?

**Comment by Speciesx** [comment]
edit the RoRSkies.os

**Comment by Erie-E8** [comment]
Ok.

**Comment by gigapouch** [comment]
@Speciesx Did you get nhelens to the normal color in 0.4.5?

**Comment by Hiradur** [comment]
@gigapouch He did, see https://github.com/RigsOfRods/rigs-of-rods/issues/174

**Comment by Hiradur** [comment]
Closing as 3rd party content bug. If you disagree, reopen with examples.
