### ISSUE TITLE
Gearbox issue.

### ISSUE THREAD

**Issue by Erie-E8** [RigsOfRods/rigs-of-rods#316]
It also seems that RoR 0.4.5.0 only supports up to 15 speed gearboxes in a vehicles, whereas RoR 0.4.0.7, and all versions before that down until around 0.37.xxx, supported I think up to 50 speeds in a vehicle's gearbox.

**Comment by Max98** [comment]
I wonder who is going to use 15 gear changes nowadays.

**Comment by Erie-E8** [comment]
You mean like playing RoR?

**Comment by Erie-E8** [comment]
Semi trucks can have up to 20 speeds in real life.

**Comment by Max98** [comment]
Then let's make it 21 changes. :)

**Comment by Erie-E8** [comment]
Sounds good :D
