### ISSUE TITLE
[Suggestion] Ingame Input Maps

### ISSUE THREAD

**Issue by Goetterescu** [RigsOfRods/rigs-of-rods#3179]
We currently have the commands/actions TRUCK_SHIFT_HIGHRANGE, TRUCK_SHIFT_LOWRANGE & TRUCK_SHIFT_MIDRANGE. I would suggest to add a toggle command as well, since there are controllers which only have a trigger button to switch gear ranges. I would like to point out that it would also make sense to add a way to integrate a splitter to gear shifting, but that would require making way too many other changes to the game.

**Comment by ohlidalp** [comment]
So adding TRUCK_SHIFT_RANGE_SWITCH_LO_HI which would toggle between those two only - that would help?

About the splitter, I don't know how that's used on trucks IRL so I can't tell how much work ot would need.

**Comment by Goetterescu** [comment]
> So adding TRUCK_SHIFT_RANGE_SWITCH_LO_HI which would toggle between those two only - that would help?

That might cause issues with some mods. It would be better to have a function that cycles through the three ranges like Lo->Mi->Hi and back to Low. The next range would be engaged by a simple button press

**Comment by ohlidalp** [comment]
Cool, that's actually better, I just needed to know of it fits your bill.

**Comment by ohlidalp** [comment]
To be added here's https://github.com/RigsOfRods/rigs-of-rods/blob/48bd9d95ecccad0ee429c292c0480e35f772ad10/source/main/gameplay/EngineSim.cpp#L1455
