### ISSUE TITLE
Faster steering at high speed

### ISSUE THREAD

**Issue by Max98** [RigsOfRods/rigs-of-rods#318]
RoR's gameplay is designed in a way where if a car's speed is high, the steering wheel progressive steering (duh) gets slowed down.
I was a player of a game called LFS. This game had the same system, but with one advantage.
While holding a key "X", the steering procedure at high speed gets accelerated and thus, the front wheels turn faster. 

I have made a similar system which is in my repo, but I'd like to know if you people like it, or can give me suggestions to improve it.

**Comment by gigapouch** [comment]
Oh yeah I was thinking of buying LFS but when I saw Rigs of Rods I told myself "forget it".

**Comment by DirtGamer301** [comment]
This would only affect keyboard users, wouldn't it?
As when playing with a controler you "decide" about the steering speed.

**Comment by Max98** [comment]
We should actually put some kind of filters for joysticks and all, and this option for keyboard users.

**Comment by tritonas00** [comment]
@CuriousMike56 this seems to be fixed now no?

https://github.com/RigsOfRods/rigs-of-rods/pull/2530

**Comment by CuriousMike56** [comment]
Yes
