### ISSUE TITLE
n/b is visible

### ISSUE THREAD

**Issue by TheUnknownGuyFromRoR** [RigsOfRods/rigs-of-rods#321]
http://www.rigsofrods.com/threads/119110-Test-Build-Rigs-of-rods-0-4-5-0-dev?p=1384178&viewfull=1#post1384178
truck:
http://www.rigsofrods.com/threads/118329-Kenworth-T600-AeroCab?p=1375626&viewfull=1#post1375626
trailer:
http://www.rigsofrods.com/threads/113375-Ice-lowboy-trailer

**Comment by Max98** [comment]
I'm sorry but all the beams are visible in the truck file, how is this supposed to not be visible?

**Comment by Hotrod55** [comment]
Even though the beams are marked visible, The set_beam_defaults is using the material tracks/trans, which will make the beams invisible. The parser is ignoring the material and loading the default beam texture instead.

**Comment by Max98** [comment]
Oh, I didn't see that one.
But I hope that you know that the beams are still rendred that way, and it's a waste of GPU power, which could be used for something else.

**Comment by Hotrod55** [comment]
Yeah I know, Not sure why modders choose to do that instead of just marking the beams invisible.

**Comment by only-a-ptr** [comment]
Fixed.
