### ISSUE TITLE
Doublesided managedmaterials not working

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#323]
Using TB4 set_managedmaterials_options 1 (doublesided) will lose effect and won't make the material doublesided.

**Comment by Max98** [comment]
Can you link me to a mod that has this bug?

**Comment by DirtGamer301** [comment]
I haven't been trying out with many cars yet, but I can send you an example (Opel Corsa B WIP), or look for another mod having doublesided materials and then send the link (might both take some time).

**Comment by only-a-ptr** [comment]
@DirtGamer301 I need detailed testing instructions: What vehicle to spawn and where to look.

**Comment by Max98** [comment]
@only-a-ptr This is caused by the new managed materials I've done, but no one wanted to send me a mod where I can clearly see the problem.

**Comment by DirtGamer301** [comment]
It's best visible with WIP vehicles using double sided managedmaterials.

It also for example happens with those (and every other car using doublesided managedmaterials):
http://www.rigsofrods.com/threads/116386-1982-1984-Toyota-Hilux-Pickup?p=1383796&viewfull=1#post1383796
http://www.rigsofrods.com/threads/109451-1997-2002-Mercedes-Benz-CLK-%28C208%29

**Comment by DarthCainRor** [comment]
I believe that  "set_managedmaterials_options"  is causing the issue, as any vehicle I've used it on, now appear one sided as well.

**Comment by Hotrod55** [comment]
Since there is no vehicles no really see this bug with, I decided to make a simple cube with all backfaces to best demonstrate this bug.
0.4.0.7: 
![screenshot_9](https://cloud.githubusercontent.com/assets/11002490/9257417/72d5e6f8-41c3-11e5-8458-5768622f4064.png)
 0.4.5.0:
![screenshot_10](https://cloud.githubusercontent.com/assets/11002490/9257422/7c368464-41c3-11e5-8216-d0330f4e06b5.png)
Download for further testing: https://www.dropbox.com/s/y1qzzdlt1f0p9tu/Backface_Cube_Test.zip

**Comment by gigapouch** [comment]
@DirtGamer301 Why are you using TB 4 and not the official release?

**Comment by Hotrod55** [comment]
This issue was originally posted 23 days ago, It still happens in the released build.

**Comment by gigapouch** [comment]
Whoops, didn't notice the post date.

**Comment by graysonk95** [comment]
Screenshot moved from my duplicate issue.
The window glass should have a double-sided material:

![screenshot_492e](https://cloud.githubusercontent.com/assets/10550037/9881286/49627ab8-5b9d-11e5-91d8-3b992ca39408.png)

**Comment by DarthCainRor** [comment]
Hm. I believe this was forgotten about. Think it's a Parser issue

**Comment by Hotrod55** [comment]
It could also be a material issue since @Max98 remade the managedmaterials shader for PSSM.

**Comment by Hotrod55** [comment]
Anyone looked into this? Seems like a pretty big issue.
