### ISSUE TITLE
AI Police chase doing exactly the same mistakes as the one being chased

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#327]
So, I was chased by the AI cop, he hit me, my car slided into a building. The police car rolled back, I drove away. It took some time for the AI to notice I'm gone, so it took the same way I went: It drove forward into the building and stopped there.

This happens due to the way it's coded, but could it work to add something to make the AI notice me crashing, for example due to beam deformation or something (or see below), so it doesn't make the same mistake.
Plus, it was no heavy impact from any of us, so he could've easily driven away again, just some scratches. AI cop also stopped when hitting a curbstone, so it seems to notice the slightest crashs and therefore stops, would it maybe work to make it also notice me "crashing" by the same way it notices itself crashing?
And it shouldn't stop after impacts like these as they're really not too bad :P

Edit: I'm not sure how similar this is to BNGs police chases, but you might want to ask Nadeox1 for some help, afaik he has some experience with BNGs AI.

**Comment by Hiradur** [comment]
@AnotherFoxGuy should take a look at this.

**Comment by gigapouch** [comment]
Also the cops don't drive very fast.

**Comment by Michael10055** [comment]
Closing this as I don't think the reworked AI supports this feature yet.
