### ISSUE TITLE
Wheels And Gears Backwards On trucks Spawned in Truckshops Rotated Over 90° On The Y-Axis

### ISSUE THREAD

**Issue by graysonk95** [RigsOfRods/rigs-of-rods#33]
Posted by Aviar in the forum's improvised bug tracker thread:
http://www.rigsofrods.com/threads/111967-Bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1363187&viewfull=1#post1363187

I have also had this issue happen once in a blue moon when spawning using the drop-down spawner, but I can't reproduce it.

**Comment by Max98** [comment]
Also had this bug several times while making my own maps.

**Comment by fidoj** [comment]
this problem has been in ror since the beginning, i first encountered this bug when i was making http://www.rigsofrods.com/repository/view/1707
orientation of the truck shop determines how the truck spawns, the same bug happens with load spawned with controllable wheels.
