### ISSUE TITLE
Debug EnvironmentMapping crashing with OpenGL

### ISSUE THREAD

**Issue by Hiradur** [RigsOfRods/rigs-of-rods#332]
When enabling the 'Debug EnvironmentMapping / Chrome' setting and using OpenGL, RoR crashes when loading a map with the following output:

```
An exception has occured!: OGRE EXCEPTION(7:InternalErrorException): Buffer data corrupted, please reload in GLHardwareIndexBuffer::unlock at /home/hiradur/ogre_src_v1-8-1/RenderSystems/GL/src/OgreGLHardwareIndexBuffer.cpp (line 161) / url: http://wiki.rigsofrods.com/index.php?title=Error_7#GLHardwareIndexBuffer::unlock
```

Obviously originating from source/main/gfx/EnvironmentMap.cpp line 86 and following

**Comment by Max98** [comment]
This does't crash on Windows.

**Comment by Hiradur** [comment]
The problem is that before this unlock operation the buffer isn't locked. Do we need to lock it?
> In order to read or update a hardware buffer, you have to ’lock’ it

from http://www.ogre3d.org/docs/manual/manual_53.html

We don't read nor do we update the old data in the buffer (the 'true' at the end means discard old data) so I think locking is not required.
