### ISSUE TITLE
Triggered hooks not locking

### ISSUE THREAD

**Issue by Aivar-RoR** [RigsOfRods/rigs-of-rods#333]
Hooks that are locked with triggers don't lock. Pressing the key that should extend the trigger and lock the hook does nothing. No errors in the log.

Henschel train: http://www.rigsofrods.com/repository/view/4340
F7 should lock the hook in the rear, F9 in the front. Doesn't work. 

Instead of locking to the lockgroups that are defined in the truck/load/train file, the hooks lock to a closest node. They can be unlocked with ALT+L (however should be with F8 and F10); once unlocked they re-lock themselves in a second or two.

I also tried removing the self-lock option from the hooks (Henschel):
>hooks
  90, hookrange: 2, lockgroup: 33, hookgroup: -31
  82, hookrange: 2, lockgroup: 34, hookgroup: -32, **self-lock**, auto-lock
  77, hookrange: 2, lockgroup: 33, hookgroup: -33
  69, hookrange: 2, lockgroup: 35, hookgroup: -34, **self-lock**, auto-lock

Now the hooks don't lock to the closest node any more, but still don't lock to the lockgroups either.

This issue happens also with these train cars:
Sgnss: http://www.rigsofrods.com/repository/view/5295
Rbns641: http://www.rigsofrods.com/repository/view/4341

Win 7 Pro 64-bit, test build 4.1.

**Comment by KT827A** [comment]
The problem still seems to occur in my system, but maybe i just picked an old version. Cant find the new one in this repo?

**Comment by only-a-ptr** [comment]
@KT827A Hello. The latest release is at https://download.rigsofrods.org and the latest development version is in the `master` branch: https://github.com/RigsOfRods/rigs-of-rods
