### ISSUE TITLE
Remove unneeded text from "Notice: Please clear the place first"

### ISSUE THREAD

**Issue by Aivar-RoR** [RigsOfRods/rigs-of-rods#334]
Would it be possible to remove the "true" at the end of the sentence?

![notice_text](https://cloud.githubusercontent.com/assets/11720273/8894864/d3da0d84-33cd-11e5-8900-1f04c39ec16f.jpg)
Text appears once a vehicle is spawned from a spawner, isn't removed and the user tries to spawn another vehicle from the same spawner again.

**Comment by gigapouch** [comment]
This also happens when you switch the camera to free.

**Comment by Max98** [comment]
Fixed in my repo.
