### ISSUE TITLE
1995 Toyota 4Runner's wheels spawn incorrectly

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#336]
In 0.4.5 TB 2, 3, and 4.1, the wheels of this vehicle spawn incorrectly, on any terrain. In 0.38.67 and 0.4.0.7 this doesn't happen.
http://www.rigsofrods.com/threads/114585-1995-Toyota-4Runner-Final-Release?highlight=4runner

![screenshot_19](https://cloud.githubusercontent.com/assets/7621364/8941826/e1889da6-3526-11e5-802f-d1390c0f5975.jpg)
![screenshot_20](https://cloud.githubusercontent.com/assets/7621364/8941832/e587ac4e-3526-11e5-8c07-0f11525b4ed0.jpg)

This is the only vehicle that I've seen have this issue.

**Comment by only-a-ptr** [comment]
@gigapouch Please do the following:
1. Add this to RoR.cfg:
- RigImporter_PrintMessagesToLog = true
- RigImporter_PrintNodeStatsToLog = true
2. Load the vehicles again and post RoR.log

**Comment by DirtGamer301** [comment]
I know this shouldn't fix the vehicle, just so: bug confirmation, everything else works at the vehicle, I added these two lines at the very beginning of RoR.cfg, I hope it showed the right things in the log

RoR.log: http://www.mediafire.com/download/fua4zd123lh5qvo/RoR.log

**Comment by only-a-ptr** [comment]
@DirtGamer301 Thanks! The diagnosis is pretty obvious:
```
#FF3300 ERROR #FFFFFF (Section shocks)
	Line (1106): 65, 102, 30000, 3250, 0.6 0.4, 1.36, i
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section shocks)
	Line (1107): 66, 104, 30000, 3250, 0.6 0.4, 1.36, i
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section shocks)
	Line (1108): 17, 101, 12000, 2500, 0.4 0.5, 1.2, i
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section shocks)
	Line (1109): 17, 105, 12000, 2500, 0.4 0.5, 1.4, i
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section shocks)
	Line (1110): 18, 107, 12000, 2500, 0.4 0.5, 1.4, i
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section shocks)
	Line (1111): 18, 106, 12000, 2500, 0.4 0.5, 1.2, i
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section shocks)
	Line (1112): 127, 105, 20000, 2500, 0.5 0.6, 1.45, i
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section shocks)
	Line (1113): 128, 107, 20000, 2500, 0.5 0.6, 1.45, i
	Message: Invalid line, ignoring...
```
There are spaces instead of commas in the definitions, and my strict parser has a problem with it. Gotta loosen this rule.

**Comment by only-a-ptr** [comment]
Fixed in my repo. Will be available soon.

**Comment by vido89** [comment]
Well I have this on my mind for quiet a while ago, so understand it just as a suggestion, when ever parser discover error in truck/car file we modify the parser to it and not other way around, I think that in some point in time we need to make parse rock solid as much as possible and update venchiles to be in correct format, may be in this case its a bug but still, cheers
