### ISSUE TITLE
Classic Mini Cooper never spawns right

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#338]
In 0.38.67, the game crashed when you tried to spawn this car. in 0.4.0.7 and 0.4.5, the gears shift way too quickly, and in just 0.4.5 it spawns without a chassis.

![screenshot_23](https://cloud.githubusercontent.com/assets/7621364/8943105/dfb09626-352d-11e5-9a56-2bf4a368a63f.jpg)
RoR 0.4.0.7
![screenshot_21](https://cloud.githubusercontent.com/assets/7621364/8943038/734b811c-352d-11e5-83b9-bcbb3e3f484f.jpg)
RoR 0.4.5
Here's a link to RoR.log:

69.107.89.192/Uploads/mini/RoR.log

**Comment by DirtGamer301** [comment]
Link to the vehicle: http://www.rigsofrods.com/repository/view/5355
I haven't tried out, but if the gears shift too quick this might also be due to the mod and not a problem of RoR.
+You uploaded RoR.log wrong, all I can see is a text saying "69.107.89.192/Uploads/mini/RoR.log"

**Comment by gigapouch** [comment]
Just copy and paste it into your browser and hit enter.

**Comment by gigapouch** [comment]
Then why does it work in 0.4.0.7 and not 0.4.5?

**Comment by DirtGamer301** [comment]
Most likely strict parser/little mistake in the truck file. (Like many cars spawned without one wheel because the author forgot a comma and the parser in 0.4.0.5 is too strict to ignore that, but only_a_ptr said the parser will be less strict in the nextr update if I remember correct)

**Comment by Max98** [comment]
Just fix the parser errors on the flexbodies first. Then see if the bug is still there.

**Comment by Hiradur** [comment]
Closing as 3rd party content bug
