### ISSUE TITLE
Flexbodies Invisible From Some Positions

### ISSUE THREAD

**Issue by graysonk95** [RigsOfRods/rigs-of-rods#34]
Posted by Craneman in the forum's improvised bug tracker: http://www.rigsofrods.com/threads/111967-Bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1361170&viewfull=1#post1361170

**Comment by Max98** [comment]
http://www.rigsofrods.com/threads/118176-Disappearing-cable-mesh
This could be the fix. Can anyone try and see? If so, we close this and wikify that thread.

**Comment by Hiradur** [comment]
It's still a bug though, isn't it?

**Comment by Max98** [comment]
No. I believe that it's Ogre's way to optimize things. If not mistaken, it's called camera culling. It removes objects not in the FOV.

**Comment by Hiradur** [comment]
You are right, I thought once they disappeared they never reappear which is not the case.

**Comment by graysonk95** [comment]
I have noticed this happens with meshwheels too. The tire itself will vanish when it touches the edge of the screen.
I guess there's not a whole lot that can be done if Ogre is causing this...

**Comment by Max98** [comment]
So should this be closed or?

**Comment by Hiradur** [comment]
We can close it for now.
