### ISSUE TITLE
Unable to map controls in-game

### ISSUE THREAD

**Issue by ghost** [RigsOfRods/rigs-of-rods#341]
This is in 0.4.5.

When I try to map controls for anything in-game, I click Map and press a key but nothing happens. I hope this bug will be ironed out before I get my steering wheel I was going to play RoR with.

**Comment by Max98** [comment]
Control mapping isn't done yet.

**Comment by gigapouch** [comment]
Oh, OK.

**Comment by tritonas00** [comment]
this can be closed imo, duplicate https://github.com/RigsOfRods/rigs-of-rods/issues/1049
