### ISSUE TITLE
AI not working when going back to menu and reloading map with AI

### ISSUE THREAD

**Issue by ghost** [RigsOfRods/rigs-of-rods#342]
In the 4 bus follow terrain the buses don't move even with their engines on and switched to drive. It worked before in the same RoR session but the next sessions the buses didn't move.

**Comment by Max98** [comment]
What do you mean by next sessions?

**Comment by Hiradur** [comment]
next session = back to menu and reloading the map or
next session = shutdown RoR and restart it?

**Comment by Max98** [comment]
I believe it's the first one, because the AI does work when you shutdown and restart.

**Comment by DirtGamer301** [comment]
Yes, it's the first one. Same thing happens with any other AI map and any map loaded before.

**Comment by Max98** [comment]
Might be Angelscript not being reseted on back to menu.

**Comment by gigapouch** [comment]
Yep Dirtgamer is right.

**Comment by tritonas00** [comment]
AI works fine now on back to menu and reload, this is fixed.
