### ISSUE TITLE
"Creak" sound cannot be enabled

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#344]
I actually want the creak sound but when I uncheck "disable creak sound", click save, exit settings, then go back to settings, it is already checked again.

**Comment by only-a-ptr** [comment]
@gigapouch Did the creak sound work in 0.4.0.7? I thought the feature was abandonned and the creak-sound support was permanently removed.

**Comment by Hiradur** [comment]
The code to play the sound is commented out in BeamForcesEuler.cpp but the other than that everything is still there.

**Comment by Max98** [comment]
Guys.. This might just be a typo from me on the ingame setting. The creak sound is working fine from the RoRConfig.

**Comment by gigapouch** [comment]
Okay, I usually just launch the new version of RoR directly by double clicking RoR.exe.

**Comment by Max98** [comment]
Alright this is fixed now.
