### ISSUE TITLE
Shadows glitch in terrain Greece

### ISSUE THREAD

**Issue by ghost** [RigsOfRods/rigs-of-rods#345]
I recently upgraded to Windows 10 and installed the latest graphics drivers for my GTX 750 Ti card and when I go into the Greece terrain, whenever you are moving there are black triangles moving everywhere. When the camera is stopped they freeze.
![screenshot_27](https://cloud.githubusercontent.com/assets/7621364/8967656/0f1e470e-35ed-11e5-8319-0cdba12ef65c.jpg)

EDIT: This also happens in Starling Island.

**Comment by Hiradur** [comment]
Does it happen with shadows disabled?

**Comment by gigapouch** [comment]
No it does not.

**Comment by Max98** [comment]
I think that this is actually fixed in my repo, I had the same bug with PSSM shadows and I fixed it, so it should be gone for texture shadows too. But uhm, Who's going to use texture shadows anyway?

**Comment by nick149** [comment]
I can confirm, tested on newest install file and on a Geforce 320M
![screenshot_6](https://cloud.githubusercontent.com/assets/14813469/10270218/f32750c6-6ab8-11e5-8f94-451b802fea75.jpg)
![screenshot_7 - copy](https://cloud.githubusercontent.com/assets/14813469/10270219/f3322f6e-6ab8-11e5-8005-36b9fbace244.jpg)
![screenshot_8](https://cloud.githubusercontent.com/assets/14813469/10270220/f3349a06-6ab8-11e5-8de0-2f75b4c4a867.jpg)
