### ISSUE TITLE
Unrealistic weight

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#346]
I'm not sure if this is a mod issue or a RoR issue, but some cars have terribly unrealistic weight. A small box truck weighing 9 tons? The Nhelens monorail weighing 57 tons?

**Comment by DirtGamer301** [comment]
Caused by the mods.

**Comment by Max98** [comment]
As said by DirtGamer, it's up to the modder to make the weight realistic. Not our fault.
