### ISSUE TITLE
Partial Throttle

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#347]
To make RoR more realistic, there should be 25%, 50%, 75% and 100% throttle modes so you don't spin everywhere in a powerful car.

Then those with keyboards can drive normally without a controller.

**Comment by tritonas00** [comment]
Yeap, that would be very useful.

**Comment by Olius** [comment]
Don't know what the best way to implement this would be... either add a keyboard bind for each percentage or make a up/down throttle like on airplanes.
Of course another solution is to have a 'force TCS on all vehicles' option, if that's possible.

**Comment by gigapouch** [comment]
Maybe just an extra key that toggles between the different throttle modes.

**Comment by Hiradur** [comment]
What do you think of including a toggleable ESP feature? This could make driving easier in general and may also help keyboard users.

**Comment by TechGiga** [comment]
What exactly do you mean by that?

**Comment by Hiradur** [comment]
https://en.wikipedia.org/wiki/Electronic_stability_control

Thinking about this further, partial throttle should still be implemented for keyboard users though.

**Comment by TechGiga** [comment]
Oh, it's different from partial throttle. But yeah, I agree. Both of these are good features to implement.

**Comment by TechGiga** [comment]
Ooh, when will the next update com out?
