### ISSUE TITLE
Include old terrain loader?

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#349]
There were many great terrains for 0.38 that were never converted to 0.4, so maybe if RoR 0.4 detects an 0.38 terrain in packs, it still loads it with an included 0.38 terrain loader (or whatever it's called).

**Comment by skybon** [comment]
We are not going to accept this kind of maintenance burden. Old format is gone, upgrading to the new one is documented [here](https://rigsofrods.github.io/en/docs/terrain-system/index.html#upgrading_to_current_terrain_system).
