### ISSUE TITLE
Sounds Restart When Switching Cameras

### ISSUE THREAD

**Issue by graysonk95** [RigsOfRods/rigs-of-rods#35]
When you change from an exterior camera view to a cinecam, whatever sounds are playing restart from the beginning. This is particularly noticeable (and annoying) on vehicles with sirens.
The only camera change that doesn't restart sounds is switching from the "TV cam" view to the "chase cam".
I believe this bug was introduced in 0.39.0.

**Comment by Max98** [comment]
Best way to reproduce this bug is to take an airplane, start the engines and switch camera.

**Comment by only-a-ptr** [comment]
I'll tackle this in my "nextstable-X-soundmanager" branch. That's where I'm dealing with weird sound management.
It probably won't be included in NextStable,though,for stability.
