### ISSUE TITLE
Streaming gauge data to the Raspberry pi

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#350]
I saw this video: https://www.youtube.com/watch?v=Mlsw8ClBYik

How did they do that? I have a Raspberry Pi and a small 9 inch screen I could use for that. What program did they use?

**Comment by Hiradur** [comment]
Best to ask @therealshark but I think RoR sends some data via OutGauge protocol to the Pi.

**Comment by Max98** [comment]
Here we go: http://www.rigsofrods.com/entries/125-OutGauge-supported

Someone should wikify that.

**Comment by gigapouch** [comment]
@Max98 We're getting closer to what I was looking for, but still there should be a tutorial...

**Comment by Max98** [comment]
I think so, if you managed to get it running, it would be great if you wikify it.

**Comment by Hiradur** [comment]
Obviously you need to run software which can display OutGauge data on the Pi as well.

**Comment by gigapouch** [comment]
@Max98 I'll do that (if the site will let me make an account).

@Hiradur Oh, so I can't just use a browser and do that IP and port #?

**Comment by Hiradur** [comment]
@gigapouch I flew over the German post theshark wrote about this and he wrote a program in Python to display the data: http://www.rigsofrods.com/threads/97594-ROR-Server-auf-dem-Raspberry-Pi?p=1095852&viewfull=1#post1095852

However, this is not the version used for the video and Alex1796 said it didn't work for him.

**Comment by gigapouch** [comment]
I'll wait for a while and see if the original script is released, then.

**Comment by Hiradur** [comment]
I doubt it'll happen. This thread is 3 years old and theshark wrote that the original script is messy and not ready for a public release. He may have lost the code in the meantime.
I suspect the modifications required to get the code running are few. Perfect opportunity to get into Python. ;)

**Comment by gigapouch** [comment]
I know some Python, but the script looks like a foreign language! :/

**Comment by gigapouch** [comment]
By the way, does it use Python 2.7 or 3.4?

**Comment by Max98** [comment]
I'm not sure, but I can see around if I can get my Arduino to recognize the data sent by the outgauge system, then I'll try to wikify it so, who ever has a rasp, can remake this.

**Comment by gigapouch** [comment]
The only problem is that the power strip in my bedroom has only one plug left and the Raspberry Pi and screen setup uses 2. :P

**Comment by gigapouch** [comment]
How do I reopen this? I accidentally closed it.

**Comment by only-a-ptr** [comment]
Re-opened.

**Comment by Hiradur** [comment]
It's using Python 2 and it doesn't error on my x86 Linux machine but I can't test if it works because RoR doesn't send OutGauge data on Linux.

**Comment by therealshark** [comment]
Yeah, the linked source should still work with the current RoR. As Hirador thought i lost the original program, but the linked sourcecode is a good start. You just need to add some kind of visualization of the values and you're pretty much done. Should be a good introduction to graphical programming i guess :)

**Comment by gigapouch** [comment]
Or I could simply just program it to display the output in numbers only instead of gauges?

**Comment by therealshark** [comment]
@Hiradur Oh, so I can't just use a browser and do that IP and port #?
like that?: https://www.youtube.com/watch?v=hqKNgfba-1A
Thank's for the inspiration ^^

**Comment by gigapouch** [comment]
ooo... That looks pretty awesome. Could you teach us how to do that with RoR?

**Comment by therealshark** [comment]
That works with RoR, since RoR implements the same protocol.

**Comment by gigapouch** [comment]
OK, then. Let me try that. I'll post a picture if I'm successful.

**Comment by gigapouch** [comment]
On the same computer as I am playing on, I added/changed those settings in RoR.cfg and then go to localhost:4444 in my browser after getting in a car in RoR but it says connection refused.

**Comment by therealshark** [comment]
ah well, you misunderstood me there. I hacked together a little program to make this work, you'd need my code to use it.

**Comment by gigapouch** [comment]
This code: http://www.rigsofrods.com/threads/97594-ROR-Server-auf-dem-Raspberry-Pi?p=1095852&viewfull=1#post1095852 right?

**Comment by therealshark** [comment]
nope, i just wrote a new version completly from scratch today. But that code could be the base for something similar. I'll opensource the new code eventually, but at the moment its just an experiment.

**Comment by gigapouch** [comment]
Ok.

**Comment by gigapouch** [comment]
Will I run the code on the device displaying the data or my computer I am playing on?

**Comment by therealshark** [comment]
on the computer. This will start a webserver which can be accessed by other devices.

**Comment by therealshark** [comment]
i uploaded the code: https://github.com/therealshark/outgauge2html
you need to have node.js installed (for now)

**Comment by gigapouch** [comment]
So node.js only needs to be installed on my PC that I am playing on?

**Comment by therealshark** [comment]
yes.

**Comment by gigapouch** [comment]
When I run the command npm install, this happens:

![npmerror](https://cloud.githubusercontent.com/assets/7621364/9321078/877ba15a-4516-11e5-8622-acbc523fb78c.png)

And node server.js yields this:

![awfulerror](https://cloud.githubusercontent.com/assets/7621364/9321091/accf9eca-4516-11e5-96a1-60f6494645a7.png)

**Comment by therealshark** [comment]
you need to run the "npm install" command in the outgauge2html folder.

**Comment by gigapouch** [comment]
Whoops, OK, I'll do that.

**Comment by gigapouch** [comment]
Awesome! It works now. Only thing is the outgauge page seems a bit laggy even when viewing the page on the same PC via 127.0.0.1. I couldn't find a setting that adjusts this.

![outgauge](https://cloud.githubusercontent.com/assets/7621364/9343700/56d857bc-45b8-11e5-983a-c76b69e5dbf2.png)

**Comment by gigapouch** [comment]
I'd love to wikify this, but it'll be about 2 weeks before the site will let me make an account.

**Comment by therealshark** [comment]
You can change the rate the packets are set by RoR by changing the OutGauge Delay in Documents/Rigs of Rods 0.4/config/RoR.cfg to a small value like

    OutGauge Delay=0.01

**Comment by gigapouch** [comment]
Alright.

**Comment by gigapouch** [comment]
I'm writing an Instructable on this.

**Comment by gigapouch** [comment]
I've published a full length, in-depth tutorial in doing this! Here it is: http://www.instructables.com/id/Displaying-OutGauge-data-from-RoR-on-another-devic/

**Comment by gigapouch** [comment]
How do you guys like my tutorial?

**Comment by only-a-ptr** [comment]
@TechGiga The tutorial is great.

Anyway, I'm closing this issue because there's obviously no issue with OutGauge :)

**Comment by TechGiga** [comment]
Thanks!
