### ISSUE TITLE
No HDR with DOF enabled

### ISSUE THREAD

**Issue by Hiradur** [RigsOfRods/rigs-of-rods#353]
System: Xubuntu 14.04
Renderer: OpenGL

When enabling DOF the HDR effect (or rather the glitches which are visible with OpenGL, see #117) is not visible. I suspect this is because the DOF effect is initialized in MainThread.cpp before the terrain is loaded (where HDR gets initialized). DOF and HDR are both Compositors and HDR should be the very first in the chain - according to the Ogre Compositor demos.

**Comment by Max98** [comment]
The way the graphical effects are handled in RoR is very bad. I think refactoring the way they are handled, creating  a separate class just for compositors is something we should do.
