### ISSUE TITLE
Folder in game's root for official mods

### ISSUE THREAD

**Issue by Max98** [RigsOfRods/rigs-of-rods#354]
It would be great to make a folder in the game's root where we can store the official mods, so they can get updated with the updater as can the whole game. (Windows only for now obviously, until we find a way of doing that for Linux/Mac)

**Comment by only-a-ptr** [comment]
I don't see why the updater couldn't update items in the Users (windows) / home (linux) dir.

I like the current arrangement where all mods are made equal and living in Users directory. Making the "official mods" (what's that, anyway, Agora bus?) de-facto "built-in" (living in game root and needing admin access to modify) seems like a step back to me.

**Comment by Max98** [comment]
Official mods will be selected HQ mods that we will be adding to the game (With author permission) and thus, we will be maintaining them by ourselves (Mostly me if no one else can do it). Actually, we can make the updater updates them in the users directory. Didn't think about that.

**Comment by Hiradur** [comment]
That would bloat the download with something the user perhaps has no interest in. Not sure if I like it.

**Comment by gigapouch** [comment]
I agree with Hiradur. Maybe the repository should have an official homepage with featured mods (the selected HQ mods) and then also all mods (recent first).
