### ISSUE TITLE
"Reload current vehicle" breaks vehicle + GUI

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#359]
Load a vehicle and click "Reload current vehicle". After that, the vehicle GUI is now loaded two times and some vehicles like Audi 80 Quattro lose some parts. Also, why the reloaded vehicle spawns on the terrain corner and not on last place?

Audi 80 Quattro
![ror_2015_08_04_14_23_51_109](https://cloud.githubusercontent.com/assets/1196375/9060499/d010c132-3ab4-11e5-8cc9-cf4b03974351.png)
![ror_2015_08_04_14_24_27_445](https://cloud.githubusercontent.com/assets/1196375/9060500/d11575e6-3ab4-11e5-8ec9-9e772754f8a1.png)

And what is this?
![ror_2015_08_04_14_45_59_692](https://cloud.githubusercontent.com/assets/1196375/9060813/977a27f2-3ab7-11e5-81cd-74dc71774a50.png)

**Comment by ulteq** [comment]
The Audi 80 Quattro is still losing some parts.

**Comment by Hotrod55** [comment]
Reloading the vehicle seems to work about the same as "removing" one: The vehicle is teleported to 100000,100000,100000 (#27 and https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/physics/Beam.cpp#L4878) then the same vehicle is respawned at the original location.
This works okay for the first couple reloads; then after the 10th+ reload (depending on how strong your PC is) you will start to notice fps drops and longer reloading times. Eventually this will cause the game to crash.
![screenshot_102](https://cloud.githubusercontent.com/assets/11002490/12534579/0e15d32c-c22e-11e5-82e0-e51b0032fcfb.png)

**Comment by WillyB1337** [comment]
As you talk about the reload function...

In Multiplayer : If I reload a vehicle, it will actually **duplicate itself and get to a spot out of map.**
Sometime I can even exceed the vehicle limit on most of the servers.

**Comment by only-a-ptr** [comment]
> In Multiplayer : If I reload a vehicle, it will actually duplicate itself and get to a spot out of map.

Fixed already by Ulteq.

> Audi 80 Quattro lose some parts

The latest truckparser fixed that.
