### ISSUE TITLE
Screenshot key has long "cooldown"

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#360]
**Context:** When you take a screenshot (PrintScreen key by default), a notice box "Screenshot saved" appears, stays visible for a while and then fades out.

**Problem:** You cannot take another screenshot while the "screenshot saved" notice is visible. You must vait until the notice box fades out. Only then the PrintScreen key reacts again.

**Test setup**
RoR 0.4.5 test build 5
Windows 7
Map: auriga; Tested while driving a vehicle (Gavril MZ2R)
Parallel-split shadow maps enabled, maximum quality.

**Comment by Max98** [comment]
This can be easily fixed by reducing the fade out time.
https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/gui/panels/GUI_SimUtils.cpp#L128

**Comment by only-a-ptr** [comment]
That's only part of the problem. 
The primary issue is that the notification box blocks screenshotting at all.

**Comment by Max98** [comment]
Oh, so it blocks screenshoting? I thought that it just annoys the screenshot, I might take a look into this.

**Comment by DirtGamer301** [comment]
I haven't tried TB5 yet as I'm still browsing through the activity in the forum and here which happaned while I was gone, but atleast in TB 4.1 I can take screenshots when the notification box appears, but it annoys :p
![screenshot_4830](https://cloud.githubusercontent.com/assets/12358849/9154281/9d55fb64-3e87-11e5-959e-5fe0e1fd3339.jpg)
![screenshot_4831](https://cloud.githubusercontent.com/assets/12358849/9154282/9d5a02ea-3e87-11e5-96af-146055f66ea4.jpg)
![screenshot_4832](https://cloud.githubusercontent.com/assets/12358849/9154280/9d53f896-3e87-11e5-9c76-4ad6b643925f.jpg)

**Comment by ulteq** [comment]
Two possible solutions:
* Don't display the notification, but play a sound instead
* Auto hide the notification right before you take another screenshot

I would try the second one first.

**Comment by only-a-ptr** [comment]
@ulteq Go for the second one - straightforward and clean enough. Thanks.
