### ISSUE TITLE
PSSM glitch (see attached GIF)

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#361]
This issue occurs on DirectX when vehicle uses a specular map. See [this workaround](https://github.com/RigsOfRods/rigs-of-rods/issues/361#issuecomment-340221264).

![pssm-glitch](https://cloud.githubusercontent.com/assets/491088/9080567/15d0f6e2-3b55-11e5-8360-6709f7863887.gif)

RoR 0.4.5 test build 5
Map: auriga http://www.rigsofrods.com/threads/104845#post1183749
Vehicle: Gavril MZ2R http://www.rigsofrods.com/threads/74698
System spec: http://pastebin.com/n1xmWegF
RoR.cfg: http://pastebin.com/XgvxKRtu
RoR.log: http://pastebin.com/d17hjDU4

**Comment by Max98** [comment]
>08:59:39: Parsing script DepthShadowmap.material
08:59:39: Compiler error: reference to a non existing object in DepthShadowmap.material(387)
08:59:39: Compiler error: reference to a non existing object in DepthShadowmap.material(390)
08:59:39: Compiler error: reference to a non existing object in DepthShadowmap.material(435)
08:59:39: Compiler error: reference to a non existing object in DepthShadowmap.material(439)
08:59:39: Compiler error: reference to a non existing object in DepthShadowmap.material(473)
08:59:39: Compiler error: reference to a non existing object in DepthShadowmap.material(476)
08:59:39: Compiler error: reference to a non existing object in DepthShadowmap.material(535)
08:59:39: Compiler error: reference to a non existing object in DepthShadowmap.material(539)
08:59:39: Compiler error: reference to a non existing object in DepthShadowmap.material(387)
08:59:39: Compiler error: reference to a non existing object in DepthShadowmap.material(390)
08:59:39: Compiler error: reference to a non existing object in DepthShadowmap.material(435)
08:59:39: Compiler error: reference to a non existing object in DepthShadowmap.material(439)
08:59:39: Compiler error: reference to a non existing object in DepthShadowmap.material(473)
08:59:39: Compiler error: reference to a non existing object in DepthShadowmap.material(476)
08:59:39: Compiler error: reference to a non existing object in DepthShadowmap.material(535)
08:59:39: Compiler error: reference to a non existing object in DepthShadowmap.material(539)

There no such file in test build 5. :/

**Comment by Max98** [comment]
Can you try downloading test build 5 from the thread: http://www.rigsofrods.com/threads/119110-Test-Build-Rigs-of-rods-0-4-5-0-dev?p=1385090&viewfull=1#post1385090

And try again. If you updated using the updater, that might be the problem, because the updater does not check for old unused and conflicted files. I will work on that soon.

**Comment by only-a-ptr** [comment]
What I did:
0. Context: The PC had 0.4.0.7 installed.
1. Downloaded TB5 (separate directory) and ran it (shadows disabled)
2. Ran updater from TB5 directory, just to see if it also overwrites/updates RoR.cfg
3. Enabled PSSM in RoRConfig and ran RoR. The above bug manifested.

I suppose the problem is this line in RoR.cfg:
```
Resources Path=d:\software\rigsof~1.7\resources\
```
This line comes from 0.4.0.7 installation.

**Comment by Max98** [comment]
The updater still doesn't do anything to document files, that will be coming into the next version. Let's try something. Rename Documents/RoR04 back to it's original name, download only the updater (http://www.rigsofrods.com/threads/120032-Testing-Purposes-Updater-V2), and update your 0.4.0.7's installation. If it goes as planned, it should work correctly.

Could you also post the updater's log? That shouldn't happen. It's updater_log.txt in the game's root.

**Comment by only-a-ptr** [comment]
Updater log from TB5 download: http://pastebin.com/GMJfQRg2

Standalone updater + RoR 0.4.0.7 installation:
Log: http://pastebin.com/3NN2tAYX
Result: the glitch is still present.
RoR.log: http://pastebin.com/BNP6LGvq

**Comment by Max98** [comment]
Does the glitch happens only in the MZ2? I see that it is loaded before the base resource in the logs and it's also unpacked.
Can you try an other vehicle?

**Comment by Speciesx** [comment]
This glitch happens with every Gavril car, MAN TGX (on rims), Volvo VHD and 1st Generation BlueBird

**Comment by Max98** [comment]
@Speciesx Are you also using and AMD gpu?

**Comment by Speciesx** [comment]
Yes.

**Comment by gigapouch** [comment]
This is kind of like #345 .

**Comment by Max98** [comment]
So this seems like it's affecting only AMD/ATI users. :/ Need to take a deeper look into it.

**Comment by DirtGamer301** [comment]
Not sure, but might it be a managedmaterials bug as the glitch did not appear at managedmaterial vehicles for me (tested DAF Semi and a yellow trailer) and non-managedmaterials vehicle (Land Rover Defender 90)?

**Comment by Max98** [comment]
@DirtGamer301 You can't be serious. https://github.com/RigsOfRods/rigs-of-rods/issues/57

**Comment by DirtGamer301** [comment]
Well, it has no reflections now.

**Comment by DirtGamer301** [comment]
Whops, didn't see the connection... Atleast it proves the reflection thing :)

**Comment by Max98** [comment]
I might need to take a look into this on ogre's forum.

**Comment by Speciesx** [comment]
![ror_2017_03_03_21_36_35_184](https://cloud.githubusercontent.com/assets/1196375/23568443/cd472212-005a-11e7-87b2-37b8a1bfeaf5.jpg)
![ror_2017_03_03_21_43_53_622](https://cloud.githubusercontent.com/assets/1196375/23568444/cd70df4e-005a-11e7-8570-c95f66e6831c.jpg)

With my new Radeon RX 480 i don't get the PSSM glitch anymore.

**Comment by DarthCainRor** [comment]
I get this issue on my Nvidia GeForce gtx 1070, but I didn't on my GTX 550.

**Comment by Michael10055** [comment]
It appears the glitch only happens if the material has a spec file.

**Comment by only-a-ptr** [comment]
@Michael10055 Can you tell me more? How/where did you come to this conclusion?

**Comment by Michael10055** [comment]
No spec file -> No glitches
```
AudiWheel       mesh_standard  Quattro_Wheel.png  -
Quattro_Body   mesh_standard Audi_coupe_2048_red.png -
```
![screenshot_2017-06-21_09-35-07_1](https://user-images.githubusercontent.com/11002490/27387076-b01f0a04-5665-11e7-804b-d2a684b91cda.png)

Spec file -> glitches
```
AudiWheel       mesh_standard Quattro_Wheel.png Quattro_Wheel_s.png
Quattro_Body mesh_standard Audi_coupe_2048_red.png Audi_coupe_s_2048.png
```
![screenshot_2017-06-21_09-37-07_1](https://user-images.githubusercontent.com/11002490/27387169-f45dfc84-5665-11e7-99a8-014aa7255292.png)

This would explain why submesh vehicles are unaffected.

**Comment by only-a-ptr** [comment]
@Michael10055 Thanks, interesting! I'll check out what it does on my platform. What's your platform?

**Comment by Michael10055** [comment]
@only-a-ptr GTS 360M (old, I know) + DirectX.

**Comment by fidoj** [comment]
this happens with direct x. opengl is stable

**Comment by Michael10055** [comment]
For anyone having this problem a workaround would be to comment/remove [this line](https://github.com/RigsOfRods/rigs-of-rods/blob/master/resources/managed_materials/managed_mats_vehicles.material#L1).
Doing this will cause vehicles to not receive shadows though, which I don't care too much about myself.

**Comment by only-a-ptr** [comment]
Removing from v0.4.8 - time is up, and let's port to OGRE 1.10+ first.

**Comment by tritonas00** [comment]
Shadows/Materials will be redone in OGRE 13
