### ISSUE TITLE
Avast! thinks RoR updater is virus

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#366]
I tried using the RoR updater today because the zipped TB 5 wouldn't finish downloading, but although I put the updater as an exception in the antivirus, it created a ror-updater_new.exe which the antivirus thought was a virus.

**Comment by Max98** [comment]
Avast is the only AV thinking it's a virus. You can safely disabled it while updating, or white-list the whole folder until we find a fix with avast.

**Comment by gigapouch** [comment]
It also thinks that the zipped TB 5 is a virus as well.

**Comment by gigapouch** [comment]
RoR works after you remove it from the Virus Vault and add it as an exception. I've reported a false positive on this too. :)

**Comment by Hiradur** [comment]
@gigapouch great initiative, was going to propose that. ;)

**Comment by Hiradur** [comment]
@TechGiga Any news?
If it's still a problem, can you open a new issue at https://github.com/RigsOfRods/ror-updater please?

**Comment by TechGiga** [comment]
Well, Avast only detects it as a virus during the installation process, so I can't really say right now if it still persists.

**Comment by Hiradur** [comment]
@TechGiga I see. Should it still be a problem when the next update is out please open a ticket in the other repo.

**Comment by TechGiga** [comment]
Alright.
