### ISSUE TITLE
Removable parts

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#367]
Instead of crashing or dragging, there should be an easier way of removing single parts from a car like door, hood, and trunk. Like a menu where you select parts to remove or change. Modmakers could make it easy to customize your car with different color fenders, bodies, or skins using this menu as well.

**Comment by DirtGamer301** [comment]
In case you didn't know, at the moment you can remove parts in the .truck file in the props or flexbodies section, this doesn't work for all cars, but it does work for the cars which loose parts with dragging/crashing ;)

**Comment by gigapouch** [comment]
OK, I'll look into that. Would the Rig Editor be able to do that?

**Comment by gigapouch** [comment]
OK! Thank you dirtgamer I figured it out.
