### ISSUE TITLE
Avast! blocks new RoR test build before download finishes

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#368]
Why does Avast think that RoR is a virus?

**Comment by Max98** [comment]
Does this happen using the updater?

**Comment by Hiradur** [comment]
Are you sure it's not warning about a flash animation instead?

**Comment by Max98** [comment]
@Hiradur No it's not, other avast users are experiencing the same thing.

**Comment by skybon** [comment]
Duplicate of #366.
