### ISSUE TITLE
Special Characters in Material Names, cause any text behind said characters to be ignored.

### ISSUE THREAD

**Issue by DarthCainRor** [RigsOfRods/rigs-of-rods#370]
Ok, So I didn't see any bug reports for this..

If you have Special characters, such as an Apostrophe ' in your material name it causes RoR to ignore any text after said mark. for example one of my Texture names is "20'MickeyVanbody-tex" But all the parser is reading is "20" so it ignores the material as it is not defined as that and moves on.

System Config: 
Windows 8.1 64bit
DirectX 9

**Comment by Hiradur** [comment]
It should stay this way to ensure cross-platform compatibility.

**Comment by DirtGamer301** [comment]
I agree with Hiradur using a most likely less important argument:
You don't usually need those characters. In a material/texture name it doesn't matter of there's a " ' " or not, a " , " or not and so on. Reading over it won't make any difference.

Do you btw mean a material name in managedmaterials or just as, well, material in a material file? As if in a material file I think this would be nothing RoR related, more Ogre related.

**Comment by Hiradur** [comment]
Add: It should show an apropiate error message.

**Comment by DarthCainRor** [comment]
Ok, I mean I suppose that's fine as I understand the need for it. I'll just have to rename a whole lot of materials on all of my things lol

**Comment by DarthCainRor** [comment]
Ok so I know it's rather random, but I'm curious as to why it ignores them in the material names, but no where else really. I have a few meshes, and image files that also use apostrophe to denote feet, and they spawn fine, the only error I've encountered using it is in the material names themselves.

**Comment by only-a-ptr** [comment]
@DarthCainRor Which file are you reffering to? A truckfile / OGRE .material file / something else? If a truckfile, which section - managedmaterials? Wheels? Flares?

Also post RoR.log please.

If it's OGRE .material, then it's strange, AFAIK it should accept all special chars.
If it's a truckfile, then it's probably a bug caused by fault-tolerance: A lot of truckfiles have invalid text after definitions, and the parser must ignore that.

Anyway, NOT using special chars in mat-names is a safe bet

**Comment by DarthCainRor** [comment]
It's inside the managed_materials where they are ignored. Apostophes work fine in the image names in the managed materials, as well as the prop names, only the managed_material material name is where they are ignored.
 Error is around line 2662.
http://pastebin.com/U4mU66rT
![11a35611635b7da27f0014ded9410b59](https://cloud.githubusercontent.com/assets/10333582/11012647/c18f71e2-84bc-11e5-8148-8b32a9063ab3.png)

**Comment by only-a-ptr** [comment]
Strange. The parser reads material name as "anything but delimiter":
> https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/rig_file_input_output/RigDef_Regexes.h#L1786
> https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/rig_file_input_output/RigDef_Parser.cpp#L5475 

Which means "anything but space or comma" https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/rig_file_input_output/RigDef_Regexes.h#L108

The spawner grabs the name as-is and feeds it to OGRE.https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/rig_file_input_output/RigDef_Parser.cpp#L5475

At the moment, it seems as an OGRE limitation.

**Comment by only-a-ptr** [comment]
@DarthCainRor Can you re-test this please?

**Comment by only-a-ptr** [comment]
Tested by @Michael10055 in Gitter chat - works fine in current upstream :grinning:
