### ISSUE TITLE
Loads in pickup trucks fall when you get in vehicle

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#372]
Tested with 1980 Toyota pickup (4x4, longbed, flextires, http://www.rigsofrods.com/repository/view/1643)

and the new mod: Porta-Potty (http://www.rigsofrods.com/repository/view/5791).

When I first load it in manually by spawning it on the back, it looks fine:
![screenshot_4](https://cloud.githubusercontent.com/assets/7621364/9158974/9ff2e0e2-3ed4-11e5-834e-e0e767b96524.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/7621364/9158978/aeffdaa4-3ed4-11e5-9ce1-4146ee4aaba3.png)

But when you get into the truck, the load falls down (still in the back) as if there is nothing there:
![screenshot_6](https://cloud.githubusercontent.com/assets/7621364/9158986/db10f222-3ed4-11e5-86b8-c4df25806a6c.png)

Here's the RoR.log:
mrgiga.ydns.eu/Uploads/loadissue/RoR.log

**Comment by DirtGamer301** [comment]
I'm not sure how this vehicle is built but you should test it in an older version and if it doesn't work it's simply that the vehicle doesn't have a detectable submesh for this part. Therefore there's nothing for the object (Porta-Potty in this case) to stay on. Submesh is also needed for two vehicles colliding. If a vehicle doesn't have a submesh they'll drive through each other, similar to this.

So therefore this most likely isn't a bug.

**Comment by DarthCainRor** [comment]
Yeah. None of those vehicles have submeshes on them anywhere. Isn't a bug, but a problem with the way the truck was made.

**Comment by gigapouch** [comment]
I don't have time to test in a different version or truck right now, but I was thinking maybe RoR could automatically make a submesh if there are none, and/or make all the surfaces of the truck contactable no matter what.

**Comment by DirtGamer301** [comment]
You don't seem to know how this stuff works. 
Submeshes are triangles between 3 connected nodes. If RoR would submesh every three connected nodes it'd be a mess and quite useless. Also, making a submesh isn't too hard ;) and in this specific case it wouldn't even make sence because the n/b would have to go into the bed, but this vehicle only has connected nodes on the bed, therefore, if anything, the object wouldn't be in the bed, it would be on the bed, looking like if it'd be flying.

**Comment by gigapouch** [comment]
Unfortunately the trucks in the F-series pack by Soat_Muldoon don't have a submesh and the porta potty falls through the bed too.

**Comment by gigapouch** [comment]
I tested in 0.38.67 with the same truck and load, same results. Then I tried spawning a traffic cone in the back but it spawned below the truck on the ground. Now how do people load vehicles?

**Comment by Max98** [comment]
@gigapouch After loading the car, go into the truck, and press "L" (If i'm not mistaken, or "O") and it will lock the car in the trailer.

**Comment by gigapouch** [comment]
I think L secures the trailer, so O is probably for the car I guess.

**Comment by DirtGamer301** [comment]
L will attach the trailer to the truck, O will fasten the vehicle to the trailer.

**Comment by DarthCainRor** [comment]
Thanks. :)

Um. You can load stuff on the 4400. You just have to use a crane or lift like you would in real life.

![screenshot_18](https://cloud.githubusercontent.com/assets/10333582/9188629/dca22f46-3fa3-11e5-80e2-2bfc02c6b991.png)

As was stated before submeshes can't really be automatically generated from the N/b because of all the cross N/b that is hidden inside to keep things rigid. If every triangle has a submesh, then you still wouldn't be able to load anything because their would be so many submeshes everywhere.

**Comment by gigapouch** [comment]
Do you have a link to a good crane(s)? And is this really necessary even for small loads like cones?

**Comment by DarthCainRor** [comment]
It's necessary for anything really. And not really. The one on the 4400 is decent. I usually just use the Manitou and the truss boom.

**Comment by Hiradur** [comment]
Closing as 3rd party content problem

**Comment by TechGiga** [comment]
No. It happens with any 3rd party object you attempt to load into the truck.

**Comment by DirtGamer301** [comment]
Then it's because with any object, it doesn't matter. It's failing to stand in there due to the way the vehicle is built.

**Comment by TechGiga** [comment]
The problem with loading things into other vehicles is it spawns on the ground not on the truck bed.

**Comment by DirtGamer301** [comment]
You also opened an issue that some mods load in the air, so you don't want them to spawn on the ground and don't want them to spawn in the air?

**Comment by TechGiga** [comment]
Well, not mods generally. I mean that vehicles should spawn on the ground and loads should spawn slightly in the air.

**Comment by Hiradur** [comment]
This is difficult because the spawn height would obviously depend on the truck. RoR would have to calculate where the truck bed is on its own. IMO for now it's better (and more fun) to use a crane.

**Comment by DarthCainRor** [comment]
I agree with @Hiradur as I feel it would be almost impossible to spawn loads at a height to load into any truck. This is more of a simulator. Half the fun is trying to fit large loads on a vehicle.

**Comment by TechGiga** [comment]
Yea, lol. I guess I should learn how to use a crane.

**Comment by DarthCainRor** [comment]
Well, I don't really see that happening in the near future, nor is 50Kg a lot of weight in this simulator where, by default a single node weighs that much. :-/ And I'm not really sure of many loads off the top of my head that could really be loaded that way, by a single person

**Comment by TechGiga** [comment]
Here are some: Porta-potty, cones, traffic signals, traffic signs, computer, barricades, wooden crates, TVs, all of which are available on the repository.

**Comment by Hiradur** [comment]
#280 is a good idea and not from the table. But it's not a priority at the moment.
