### ISSUE TITLE
Pale textures

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#373]
Description:
Various textures are pale. You can slightly see them through the white. Bug doesn't appear in previous RoR versions or Test Builts.

How to reproduce:
Get this: http://www.rigsofrods.com/threads/71945-Mercedes-w460?p=801248&viewfull=1#post801248
Go to any map and look at the car.
It also happens with other vehicles.

![screenshot_26](https://cloud.githubusercontent.com/assets/12358849/9171290/9720bfd4-3f6a-11e5-953f-4b3d727574ca.jpg)
![screenshot_27](https://cloud.githubusercontent.com/assets/12358849/9171292/9725a774-3f6a-11e5-80df-b2558db23d76.jpg)
![screenshot_28](https://cloud.githubusercontent.com/assets/12358849/9171291/972521dc-3f6a-11e5-85f0-6356da49e33c.jpg)
![screenshot_29](https://cloud.githubusercontent.com/assets/12358849/9171295/972eea14-3f6a-11e5-937a-a2a90f125c64.jpg)
![screenshot_46](https://cloud.githubusercontent.com/assets/12358849/9171293/9726ab1a-3f6a-11e5-931a-478287efce5e.jpg)
![screenshot_47](https://cloud.githubusercontent.com/assets/12358849/9171294/9729d272-3f6a-11e5-9ce7-93d519cdfa3f.jpg)

**Comment by DarthCainRor** [comment]
I believe it has something do with missing specular images defined in the managedmaterials section.

**Comment by DirtGamer301** [comment]
Oh, that's possible. For the materials the bug appeared (on the Taunus) I didn't use any specular images because the materials are supposed to be matte. I can add a black image to the Taunus and use it as spe file, so it'd be an easy fix. Just, for backwards compabitility, [you can image what I will say] this should be fixed because as you can see it also happens with older (but good) vehicles whose author is inactive.

**Comment by DarthCainRor** [comment]
I believe that in previous versions it defaulted to something so that it didn't look white it was just super glossy.

**Comment by gigapouch** [comment]
I can confirm this as well, with a different truck too: 
![screenshot_17](https://cloud.githubusercontent.com/assets/7621364/9234733/64c6fbda-40ef-11e5-9110-17ab75c4cb97.png)

**Comment by DirtGamer301** [comment]
Yeah, happens with many vehicles. Finding them all, fixing and reuploading wouldn't work.

I added a texture black.png, being black and 1x1 pixel big, to the zip and used it as spec file for any fully matte material and it worked.

**Comment by DirtGamer301** [comment]
Bumping as I think it was being overseen by the devs.

**Comment by gigapouch** [comment]
Me too.

**Comment by only-a-ptr** [comment]
Spawner bug. I'm onto it.

**Comment by Michael10055** [comment]
This is caused by a missing spec texture:
```
wheel_b_01 flexmesh_standard Tire_02.jpg - Tire_02-s.jpg 
tire_b_01 mesh_standard Tire_02.jpg Tire_02-s.jpg
```
`Tire_02-s.jpg` should be `Tire_02_s.jpg` -> fixed  ![1](http://i.imgur.com/YndrxMS.png)

**Comment by only-a-ptr** [comment]
@Michael10055 So this was in fact a truckfile issue all the time?

**Comment by DirtGamer301** [comment]
@only-a-ptr It's fixed for every vehicle without specular file if you create a black 1x1px png/dds file, previous RoR version - I think - used a matte material as specular file (just what the black 1x1px image would do).
In case of the Mercedes, as Michael noticed, it was caused by a falsely named specular file which isn't existend in the zip with this name, so RoR threatened it as not specular file.

**Comment by Michael10055** [comment]
The old parser simply ignored the invalid file.

**Comment by ulteq** [comment]
I think we need to overwork this file in order to fix it properly: https://github.com/RigsOfRods/rigs-of-rods/blob/master/bin/resources/managed_materials/managed_mats_vehicles.material

**Comment by tritonas00** [comment]
> The old parser simply ignored the invalid file

@Michael10055 
![2016-10-19-123830_1366x768_scrot](https://cloud.githubusercontent.com/assets/2660424/19621279/145f4a2a-9897-11e6-9a44-6503337f9656.png)

Maybe this issue fixed later some how?

**Comment by DirtGamer301** [comment]
@tritonas00 That's when you use OpenGL as renderer, isn't it?

**Comment by tritonas00** [comment]
Yes
