### ISSUE TITLE
Ambient lights for Terrain use.

### ISSUE THREAD

**Issue by DarthCainRor** [RigsOfRods/rigs-of-rods#374]
This is more of a request, as I don't currently believe it's possible to do, but it would be nice to have a way to have "flares" per say be attached to meshes that actually cast light when it gets dark in RoR. Even a way to have textures change at dusk/dawn etc, to using light mapping would be quite nice as when you currently apply them, it appears lit at all times of the day.

**Comment by Hiradur** [comment]
:+1:

**Comment by DarthCainRor** [comment]
Ok. So as I've been working on things, terrain and otherwise, I realized that flares that are attached to meshes with "beacon-" at the start of their name, they emit light that actively effect surroundings, I.e, cast an orange light onto things nearby. Would it be anyway possible to maybe replicate this with some sort of "light-" prefix to cause a constant light cast on to objects? Just an idea, as I have no idea the coding behind it all, but it came to my mind today messing around with my barricades.
