### ISSUE TITLE
Engine sound and dust stay after removing vehicle

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#376]
After traveling at a high speed (>150 mph) then crashing, then removing the vehicle, the dust and sound continues. Tested with the low rider Chevy S10 truck in MitCity:

![screenshot_12](https://cloud.githubusercontent.com/assets/7621364/9181258/613819f0-3f59-11e5-87c2-a3593e8ce245.png)

**Comment by ulteq** [comment]
https://www.youtube.com/watch?v=kjMXxLlzxck&feature=youtu.be
