### ISSUE TITLE
Terrain question

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#378]
Is it possible for a RoR terrain to have underground stuff or caves?

**Comment by DirtGamer301** [comment]
Yes, just depends how you build your terrain ;)

Here are two cave maps:
http://www.rigsofrods.com/repository/view/4649
http://www.rigsofrods.com/repository/view/4628

**Comment by Hiradur** [comment]
You can't do that with a heightmap, instead you have to use a mesh for terrain, e.g. http://www.rigsofrods.com/threads/120454-Highway-Bridge-Mesh-only-map-project-in-Blender
