### ISSUE TITLE
No Admin/Mod flags in Multiplayer

### ISSUE THREAD

**Issue by Dogy144** [RigsOfRods/rigs-of-rods#382]
In multiplayer in the stable release of 0.4.5, the Administrator and Moderator flags do not show up next to the player names.

Pic:

![](http://i.imgur.com/f6ultp1.png)

**Comment by tritonas00** [comment]
Flags seems fine here.

Although it shows US flag for me, and i'm in Greece :)

**Comment by DirtGamer301** [comment]
^I think it shows the flag of whatever your RoR laguage setting is, and as there's only American English as selection in 0.4.5.1...

**Comment by AntoniD330** [comment]
@DirtGamer301 Yes, you're right. [Source](http://www.rigsofrods.com/threads/98926-How-to-get-Canadian-flag-in-multiplayer?p=1108161&viewfull=1#post1108161).

But I think @Dogy144 was refering to the staff flags like:
- "Blue" for Moderators, and
- "Red" for Administrators.

with this additionals flag:
- "Green" for Registred members (Only for the, now defunct, Official servers).

**Comment by DirtGamer301** [comment]
@AntoniD330 I forgot to put the @tritonas00 thing, as he said "it shows US flag for me, and i'm greece"

**Comment by Dogy144** [comment]
When I originally made the report (6 months ago) the admin/mod/normal flags and country flags were not showing up (as well as the loading local/remote arrows). But it seems to be fixed in the latest build. Not sure what fixed it.

**Comment by tritonas00** [comment]
So time to close this issue :+1:
