### ISSUE TITLE
The -dev is still in the configurator

### ISSUE THREAD

**Issue by Dogy144** [RigsOfRods/rigs-of-rods#384]
Is this supposed to still be there?

Pic:
![rigs_of_rods_version_0 4 5 0-dev_configuration_2015-08-11_23-26-15](https://cloud.githubusercontent.com/assets/11688685/9235563/712c339a-410d-11e5-9f0c-4fd1d65d8034.png)

**Comment by Max98** [comment]
Oh well Does it really bother you? hahah
I will fix it on 0.4.5.1

**Comment by Dogy144** [comment]
It doesn't bother me that much lol. Just thought it was worth mentioning.

**Comment by Hotrod55** [comment]
RoRConfig just needs to recompiled, that's all ;)

(p.s. I would remove/edit that picture as it shows most of your user token.)

**Comment by gigapouch** [comment]
Lol, when is 0.4.5.1 out?

**Comment by Max98** [comment]
No ETA for the moment.

**Comment by Hiradur** [comment]
I'm not sure if it's fixed for the Windows release of 0.4.5.1 but I'll close this because it's an issue with a release and not the codebase directly.
