### ISSUE TITLE
Crash when going into ingame settings (Bad UTF-8 continuation Byte)

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#385]
So, I had it since ingame settings were being added and yet none of the advices helped.

The problem is simple to explain, but you most likely won't be able to reproduce it.
I press the "settings" tab and then the game crashed, giving me an error message: "Bad UTF-8 continuation Byte"
RoR.log: http://www.mediafire.com/download/fua4zd123lh5qvo/RoR.log

Cache clearing, regenerating, deleting whole RoR 0.4 folder and running RoRConfig, deleting the stuff in RoR 0.4 folder and running RoRConfig didn't help.

**Comment by Hiradur** [comment]
Is 'bandit' your real Windows user name? What system locale do you use? Perhaps there is a setting in RoR.cfg using an Umlaut or other non-ASCII characters?

**Comment by DirtGamer301** [comment]
Yes, from "Smokey and the bandit" ^^ Couldn't think of anything better

I installed all RoR versions on C.

I found this in RoR,cfg:
Program Path=c:\progra~2\rigsof~1\
Replay mode=Yes
Resources Path=c:\progra~2\rigsof~1\resources\

And this:
plugins.cfg=C:\PROGRA~2\RIGSOF~1\plugins.cfg

It btw says it's a runtime error so I did what I always did when having a runtime error, too, but it didn't help either.

**Comment by Hotrod55** [comment]
This same error also happens in .truck files: #364

**Comment by Hiradur** [comment]
@DirtGamer301 Is that the correct log? It looks like a normal session to me without a crash.

**Comment by DirtGamer301** [comment]
Oh, are there any other information beside gameplay in RoR.log?
Idk, but maybe this RoR.log was created the session before and as I didn't play to get this log (only pressed on the "Settings" tab) it might not be created.
I'd then have to upload another file, but which one?

**Comment by Hiradur** [comment]
upload the whole logs folder, maybe there is something useful in one of the logs.

**Comment by DirtGamer301** [comment]
I'll do so tomorrow, I sadly have nomore time today.

**Comment by DirtGamer301** [comment]
There we go, I zipped the folder:
http://www.mediafire.com/download/pq344lrap5e5uep/logs.zip

**Comment by Hiradur** [comment]
hmm, I couldn't see anything suspicious. Can you upload your config folder, please?

**Comment by DirtGamer301** [comment]
If a video helps I can record one.
http://www.mediafire.com/download/a8w34jdu4gxgs5b/config.zip

**Comment by Hiradur** [comment]
Couldn't spot anything special here either. The only thing which puts me off are these weird Windows 8.3 abbreviations such as ``` c:\progra~2\rigsof~1\ ```. You could try to replace them with the full path instead. What version of Windows are you using?

I don't think a video could help here. A Remote session could do maybe.

**Comment by DirtGamer301** [comment]
I use Windows 7.
I'll give the file path renaming a try.
