### ISSUE TITLE
Cannot secure vehicle to flatbed trailer or truck

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#389]
There is currently no way to prevent a vehicle on a flatbed trailer or a flatbed truck from sliding around and eventually falling off the trailer/truck. Pressing 'o' does not secure it and the parking brake on the vehicle being towed does not necessarily fully secure it. In fact, the parking brake is not quite strong enough in smaller cars. Here's an animation I created of what I'm talking about:
![sliding](https://cloud.githubusercontent.com/assets/7621364/9240687/1ea5cf26-411e-11e5-98f3-5df0e07f111f.gif)

**Comment by DarthCainRor** [comment]
Ties work fine for me.
http://i.imgur.com/DWb1T2n.png

Vehicles need to have defined ropables in the .truck file in order to be ties down. What vehicle is that?

**Comment by gigapouch** [comment]
Ties? Whatever it is the trailer I'm using doesn't have it. The vehicle on the trailer is a stock 1995 Toyota 4Runner. http://www.rigsofrods.com/threads/114585-1995-Toyota-4Runner-Final-Release

**Comment by DarthCainRor** [comment]
Yes. Ties are the things that lock when you press "o." In this case neither the trailer, nor the 4runner have the appropriate ties/ropable sections defined. 

As classic as the submesh trailers are, I think it could be a good idea to slowly start replacing the default vehicles in RoR with newer, higher quality meshed ones. The devs could potentially do a modding competition among member who then vote on entries they would want to see replace the defaults.

**Comment by gigapouch** [comment]
What do you mean by default? The DAF truck and the agora buses? Neither the truck or trailer I used come with RoR by default. :/

**Comment by DarthCainRor** [comment]
That trailer does. It's in the DAF semi pack

**Comment by gigapouch** [comment]
Oh. Is there a way to define more powerful brakes in the .truck file?

**Comment by DarthCainRor** [comment]
It wouldn't really help, as it's how physics work. To get it to work you'll have to add rope-ables to the vehicle, and ties to the trailer.

**Comment by skybon** [comment]
Third party content bug. Closing.
