### ISSUE TITLE
Rigs of Rods will not accept the most basic node/beam structure

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#390]
I was trying to make my first vehicle (really just some sort of triangular thing with wheels) but Rigs of Rods will not accept it and will crash when I try loading it. Is this a strict parser thing and/or the tutorial (http://www.rigsofrods.com/wiki/pages/RoRBook) is bad?

Here's my truck file: 

megawert.ddns.net/Uploads/first.truck

Please don't lock this issue. :(

**Comment by Hotrod55** [comment]
You might want to take a look at other vehicles. Your truck file has a unfinished wheels(?) section under the title, no nodes, and a incorrect set_node_defaults section.
Please take a look at http://rigsofrods.github.io/en/docs/truck-description-file/index.html
