### ISSUE TITLE
Translations missing: Call for translators

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#391]
If you want to translate, follow this link to a convenient web interface: https://www.transifex.com/rigsofrods/rigs-of-rods/

Original post:

``````
I know, this bug might not be worth being posted here as it's pretty easy to detect and won't be "fixed" from today to tomorrow, but IMO it's still an issue and not to forget it I still post it here.

There's only one language, English (US), avaible in the languages tab as the new version wasn't translated into different languages yet.

(Tested with RoRConfig only but I think there's no difference in the ingame settings ;) )```
``````

**Comment by only-a-ptr** [comment]
@DirtGamer301  It definitely should be here, thanks for posting it.
Hiradur is currently exploring the localization subsystem.

**Comment by Hiradur** [comment]
Anybody interested in translating Rigs of Rods should take a look at our new page for translations: 
https://www.transifex.com/rigsofrods/rigsofrods/

**Comment by DirtGamer301** [comment]
@Hiradur I can give it a try the german translation if you don't want to as I think the english language (translation base) is more familar to you than to me.
Also, I'm not sure if I fully understand this system and therefore I might make big mistakes in there.
Are the files to translate updated? The last time I visited this website there were only the files for the old RoR version IIRC.

**Comment by TechGiga** [comment]
I could probably do parts of the Spanish translation but not the whole thing.

**Comment by Hiradur** [comment]
I'll reopen the issue until it's fully resolved.

@DirtGamer301 Feel free to take on the German translation. I think it's complete though. Other people can correct mistakes so don't be afraid of making them.
About the versions: Transifex was set up by @skybon and I'm now trying to get an overview of what we have there and how it works. It's possible that the template is outdated, how can you tell?

@TechGiga Every word helps.

**Comment by DirtGamer301** [comment]
Oh whops I didn't even notice I closed it until now :P That was an accident.
The german translation can't be complete because of the new stuff coming with RoR 0.4.5.1, noone took it, I was on transifex for quite some time now and there were no changes mentioned either.
It said the german translation is 100% done since ever, most likely that's due to the old sources.

**Comment by schmatzler** [comment]
I can proofread the German translation.

But it looks like the link to transifex is broken.

**Comment by Hiradur** [comment]
> But it looks like the link to transifex is broken.

Apparently skybon deleted it inbetween. Well I've got to set up a new project when I got time. 

> I was on transifex for quite some time now and there were no changes mentioned either.

Sorry about that, there was so much going on we didn't pay too much attention to that.

**Comment by Hiradur** [comment]
I created an up-to-date template at our new Transifex organization:
https://www.transifex.com/rigsofrods/rigs-of-rods/

It would be great if you could translate some words into multiple languages. Don't translate too much though because I'm still trying to find out how it works and your work could potentially get lost.

**Comment by Hiradur** [comment]
Before you proceed with translating I'll try to merge in the old translations. I'll report back when it's done.

**Comment by Hiradur** [comment]
Sorry for the delay, old translations have been merged in and you can now start to translate at https://www.transifex.com/rigsofrods/rigs-of-rods/

**Comment by DirtGamer301** [comment]
I just took a look into the new file, is there a way to find the non-translated parts?

**Comment by Hiradur** [comment]
next to the search bar you can switch between all, untranslated and unreviewed-

**Comment by DirtGamer301** [comment]
Oh, there's an edit mode on the website, I always downloaded ror.pot and edited manually...

**Comment by Hiradur** [comment]
Oh well, for anybody wondering: Once you gained translation permissions for your language you can click on view strings online and in the upper right corner on 'start translating' to use the convenient web interface.

**Comment by schmatzler** [comment]
You can also press TAB after a single translation and do a whole bunch of them easily that way.

**Comment by only-a-ptr** [comment]
@Hiradur I registered on Transifex separately, please approve my join request. 

Github integration failed me - my GH-username has dashes [github prohibits underscores] but transifex prohibits dashes and requires underscores :smile:

**Comment by Hiradur** [comment]
Just realized that the Configurator is not included in the translations templates. Will fix that soon.

**Comment by Hiradur** [comment]
The Configurator is now included in the translation template.

**Comment by TheRegistrar** [comment]
I'm willing to help on the Italian translation, as a translator, a proofreader or both, since 70+% of the job is done already. I can translate what's missing and proofread what was done by others.

**Comment by Hiradur** [comment]
I accepted you as a translator for Italian. I suggest you first translate the missing strings and then start proofreading if you like.

**Comment by TheRegistrar** [comment]
OK thanks.

**Comment by Hiradur** [comment]
Recent changes introduced new strings and I updated the Transifex source file to reflect that.

**Comment by Hiradur** [comment]
I updated the Transifex source file once again. This is hopefully the last update before the 0.4.6.0 release.

**Comment by KinG-InFeT** [comment]
+1

**Comment by KinG-InFeT** [comment]
it's possible add italian language?

**Comment by KinG-InFeT** [comment]
i can't join team for italian language, why?

**Comment by tritonas00** [comment]
translations now moved to weblate, this is very outdated
