### ISSUE TITLE
Too much smoke emitted for default smoke line

### ISSUE THREAD

**Issue by negativeice** [RigsOfRods/rigs-of-rods#392]
The default smoke line emits to much smoke to constantly blocking your view.

![screenshot_1](https://cloud.githubusercontent.com/assets/13782984/9251972/f626d73a-41a3-11e5-8b0e-d2d128e53842.png)

**Comment by gigapouch** [comment]
If you are using the first person camera then it shouldn't be a problem.

**Comment by Hotrod55** [comment]
Most people don't want to use the first person camera all the time...It's still a bug that should be looked into.

**Comment by gigapouch** [comment]
It is more realistic and more fun with lots of smoke, and 1st person view is the most realistic. I only leave 1st person view when connecting a trailer or loading something.

**Comment by DirtGamer301** [comment]
But not everyone and if you say "Everything you can't see from 1st person camera doesn't need to be fixed" you'd only have to create the front end and visible interior (from 1st person view straight forward) and say done the mod is. But that's not what it's about.

**Comment by Hiradur** [comment]
Is the amount of emitted smoke the same as in older versions?

**Comment by DarthCainRor** [comment]
No. The game emits a  lot more in .4.5 than it did on .38

**Comment by only-a-ptr** [comment]
@DarthCainRor That's curious, I didn't touch it at all. What about v 0.4.0.7. Can you test all versions and post screenshots for comparsion, pls?

**Comment by DarthCainRor** [comment]
Full throttle with Box5's W900.
0.38
![screenshot_193](https://cloud.githubusercontent.com/assets/10333582/11317143/a4776336-8fe7-11e5-9b5a-22b9f72134a0.jpg)
0.4.0.7
![2015-11-20_14-48-32](https://cloud.githubusercontent.com/assets/10333582/11317141/8f0b6cd6-8fe7-11e5-81ef-409ff7d9586a.jpg)
0.4.5
![screenshot_205](https://cloud.githubusercontent.com/assets/10333582/11317145/ad040446-8fe7-11e5-86ae-6c3bac4dc49e.png)

Also, on a side note from talking with others in the RoR Skype channel, vehicles using the new turbo code, smoke fine, ones without do not.

**Comment by only-a-ptr** [comment]
@DarthCainRor Oh, that's quite insane, indeed :smile: 
And thanks for the "side note", that's actually a very promising clue.

**Comment by only-a-ptr** [comment]
This is for Max98 to fix.
The problem is BeamEngine::curTurboRPM - 0.4.0.7 always udpates it. In 045, it's only updated when <engturbo> is used. With Box5's W900, it's zero all the time.

**Comment by only-a-ptr** [comment]
I changed my mind about the assignment ... I'll fix it. And clean the code in the process :relaxed:

**Comment by only-a-ptr** [comment]
Hmm... third thought :) ... I won't just fix the code as it is. Instead, I'll do THE THING :smiling_imp:

**Comment by negativeice** [comment]
what thing? :D also when can we expect a new version? :)

**Comment by Hiradur** [comment]
@only-a-ptr When doing that you should also look at #428 

@negativeice no eta, you can follow the progress on the 0.4.6 milestone here: https://github.com/RigsOfRods/rigs-of-rods/milestones/0.4.6.0

**Comment by only-a-ptr** [comment]
@Hiradur @Max98 Heh, just found a bug with "engoption: stallRPM" setting. "StallRPM" is used as "IdleRPM" and  "IdleRPM" is ignored. The bug was introduced by Ulteq when he extended "engoption" in 2013: https://github.com/RigsOfRods/rigs-of-rods/commit/fa1916e24365be8920ec32f4f6cf4fa450bf6bd1#diff-d47d357a254e0b1523e9a63fa4af7382R93
