### ISSUE TITLE
set_inertia is not working anymore 

### ISSUE THREAD

**Issue by negativeice** [RigsOfRods/rigs-of-rods#393]
all my mods use set_inertia to smooth out the commands so they don't start or stop abruptly, but that seems to be absent now.

**Comment by only-a-ptr** [comment]
@negativeice : Please give me specific testing scenario:
* A download link to a vehicle
* Controls to use for testing
* Description of desired and actual behavior

**Comment by only-a-ptr** [comment]
Investigation
---------------

Parser / Directive set_inertia_defaults: 
> Keywords
>> regex: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/rig_file_input_output/RigDef_Regexes.h#L268
>> enumeration: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/rig_file_input_output/RigDef_File.h#L2153
> Processing:
>>  https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/rig_file_input_output/RigDef_Parser.cpp#L4634

Parser / command[2]
> default inertia added OK: 
>> https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/rig_file_input_output/RigDef_Parser.cpp#L3489

**Comment by only-a-ptr** [comment]
Fixed

**Comment by negativeice** [comment]
Sorry for the late reply man, that thanks for fixing :) greatly appreciated

also another thing i noticed is that shocks are not as smooth as they should be.

And example is on my jcb when you curl the coupler all the way down and lift the front end, the couple jerks rapidly.

**Comment by Hiradur** [comment]
@negativeice please open a new ticket for that and always include links to the vehicles you are talking about.

**Comment by negativeice** [comment]
ok
