### ISSUE TITLE
Something black on Small Island

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#395]
Description:
There's something black "flying" on Small Island, the bug doesn't occur in RoR 0.4.0.7.
You can drive through it and, it's just the like if it would be a low cloud layer being all black.

How to reproduce:
Get Smallisland (I think this is the correct link, there's another one somewhere: http://www.rigsofrods.com/threads/104845-Version-0-4-0-6?viewfull=1#post1183749 if the roads aren't messed up it's this one)
Start RoR, open Small Island

![screenshot_3](https://cloud.githubusercontent.com/assets/12358849/9252566/4df8ae72-41d9-11e5-9492-b14ac8eaa578.jpg)
![screenshot_4](https://cloud.githubusercontent.com/assets/12358849/9252568/4dfd9540-41d9-11e5-96d3-e04cd6169c76.jpg)
![screenshot_5](https://cloud.githubusercontent.com/assets/12358849/9252571/4e0417f8-41d9-11e5-8ba1-deefbbab1e3d.jpg)
![screenshot_12](https://cloud.githubusercontent.com/assets/12358849/9252570/4e005b72-41d9-11e5-9a90-55e62c6fe3fa.jpg)
![screenshot_13](https://cloud.githubusercontent.com/assets/12358849/9252569/4dfe1bf0-41d9-11e5-98ae-d76173ad1df9.jpg)
![screenshot_14](https://cloud.githubusercontent.com/assets/12358849/9252567/4dfca158-41d9-11e5-8c0e-74cdc2eba590.jpg)
![screenshot_15](https://cloud.githubusercontent.com/assets/12358849/9252572/4e1114e4-41d9-11e5-9727-0eab21612420.jpg)

**Comment by gigapouch** [comment]
I can confirm this.
![screenshot_41](https://cloud.githubusercontent.com/assets/7621364/9315084/d9bfdd12-44e1-11e5-9383-88dfb6fa78df.png)

**Comment by tritonas00** [comment]
Enabling hydrax water fixes this.

**Comment by DirtGamer301** [comment]
I just tried, Hydrax fixes it here, too. (and god, that looks awesome!)

**Comment by Max98** [comment]
To fix this, just go to smallisland.terrn2 and remove the line "WaterBottomLine"

**Comment by DirtGamer301** [comment]
Fixed it, thanks. Is that an user error?

**Comment by Hiradur** [comment]
closing as 3rd party content bug.
