### ISSUE TITLE
Multiplayer texts are annoying

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#396]
So, I tried out some real MP in NextStable (means with other players) but the Chatbox and all the other information and notice and idk what boxes are quite annoying and confusing. I tried only to chat but I really didn't get what NextStable does. Sometimes my messages appeared in the normal chatbox, sometimes in the information window which also shows that you took a screenshot or changed to free cam. Also, taking screenshots didn't work with any of these windows being "open" while itworks in single player (also with the informaton windows open). Then after some seconds the cahtbox disappeared, no matter if I wrote something or not. It also disappears in 0.38/0.4.0.7 but not when writing.

**Comment by Max98** [comment]
Interesting, this never happened to me. :/
Can you post your logs?

**Comment by Hotrod55** [comment]
This always happens to me and any of my other friends. Quite annoying.
H.owever, You can disable the auto-hiding chatbox in settings. 
![2015-08-13_11-53-54](https://cloud.githubusercontent.com/assets/11002490/9254567/33d653b8-41b2-11e5-9af0-e7f54ade4676.png)
The chatbox won't hide anymore but it's better than it hiding while you're typing something.

**Comment by gigapouch** [comment]
IMO, I liked the 0.38 chatbox better, but it couldn't move around like the current one.

**Comment by DirtGamer301** [comment]
@Hotrod55 thanks but sadly I can't go into ingame settings ;(

@Max98 I sadly don't have the old logs anymore, I'd have to try recreating a MP session with 0.4.5.0 with chat and stuff, need to do that later with someone, I'm currently eating :P

**Comment by Hotrod55** [comment]
@DirtGamer301 add this to your ror.cfg:
```
ChatAutoHide=No
```

**Comment by DirtGamer301** [comment]
Test with ChatAutoHide to show, well, how it is with auto hiding :P Thanks for that.

I tried to record but sadly the video didn't save (thanks, Bandicam, for not working so often) so you'll have to live with the logs and this:
-This time none of my messages were in the place of the user names on the server, this worked.
-"Message censored by server" and stuff like that will be where the usernames and screenshot notice window is, should just be in the chatbox
-Chatbox disappears also while writing or having the mouse on it to write and stuff
-being in the chatbox and having "z" pressed to write doesn't mean you can write, sometimes RoR used it as commands like "e" (wireframe) or "n" (lights on) and so on.
-If the chatbox disappears while writing you have to press on the screen and press "z" again to keep writing

I think that's all

RoR.log: http://www.mediafire.com/download/wz7d077lykoo7f7/mygui.log
If you need any more logs, I saved the ones from this session.

**Comment by DirtGamer301** [comment]
NVM it did record, contact me on Skype if you'd like to see the video as I really don't feel like uploading it :P

**Comment by ulteq** [comment]
All of the mentioned issues should be fixed by now:
* https://github.com/RigsOfRods/rigs-of-rods/pull/966/commits/30a0aa1c120c8c489f055ab5658d90257c55d67f
* https://github.com/RigsOfRods/rigs-of-rods/commit/7ec20dc332980333f0e8ce347206f37e379b1ab8
* https://github.com/RigsOfRods/rigs-of-rods/commit/b3e721127f5e639be37e3fa289f0c19df597173f

If not just create a new issue.
