### ISSUE TITLE
some flexybody meshes dont work

### ISSUE THREAD

**Issue by negativeice** [RigsOfRods/rigs-of-rods#397]
![screenshot_1](https://cloud.githubusercontent.com/assets/13782984/9255398/0984e624-41b7-11e5-879c-029172cb75d7.png)

**Comment by gigapouch** [comment]
Some mods are designed to be rigid-bodied and not take a lot of damage. I don't think this is a RoR bug.

**Comment by Hotrod55** [comment]
This is a RoR bug. @negativeice is the creator of that truck.

**Comment by gigapouch** [comment]
How do you know what truck it is?

**Comment by Hotrod55** [comment]
It's released on the forums. http://www.rigsofrods.com/threads/114646-DAF-95XF-truck-pack

**Comment by DarthCainRor** [comment]
Can you post your log file?

**Comment by Max98** [comment]
I don't understand what's the problem. Can anyone explain?

**Comment by DarthCainRor** [comment]
I'm not exactly sure,  since he didn't really explain much, but with what he said and the picture he posted I'm assuming that the flexbodies on his airbags aren't working properly.

**Comment by Max98** [comment]
More info please.

**Comment by only-a-ptr** [comment]
Closing per PM from `negativeice` on rigsofrods forums:

    sorry, it seems to be a problem with my truck because some of my other trucks the flexybody
    bags  work fine
