### ISSUE TITLE
[Angelscript] setWaterHeight removes water 

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#4]
if you use [`void setWaterHeight(float value);`](http://ror.ezzg.be/docs/angelscript/classgame.html#a75ec644630c6719be90be6f2a733a403) the visible water will disappear.

[More info](http://www.rigsofrods.com/threads/111967-Bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1346528#post1346528)

**Comment by Max98** [comment]
I also have a similar bug on BackToMenu when not using Hydrax. The water plane simply doesn't not change from Height but the water simulation does. Which seems to be weird.
Working on this.

**Comment by Max98** [comment]
Annnd fixed! :)

**Comment by Max98** [comment]
Ugh, not fixed, it was an illusion that made me think it was fixed.

**Comment by Max98** [comment]
Now it's fixed for good and tested! :)
