### ISSUE TITLE
[Request] show beginning of vehicle name in "T" menu

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#401]
Atm, if you press "T" and the vehicles name is longer than the menu, the end of the name is shown. IMO it'd be better if the beginning of the name would be shown.

Example of how it's now (the whole name is "Mercedes Benz 508D Kastenwagen mb508Dkasten"):
![screenshot_33](https://cloud.githubusercontent.com/assets/12358849/9273652/ca933924-428e-11e5-8ae1-792d10d824d1.jpg)

**Comment by Hotrod55** [comment]
The original T-Menu used to stretch with long vehicle names. Not sure how the new one will handle that.

**Comment by gigapouch** [comment]
Then the T menu could spread out the name over 2 or 3 lines.
