### ISSUE TITLE
Videocameras & MaterialFlares not working with skinzips

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#402]
I didn't find something like that via search button, if it's already reported just close this please.

Description:
If you have a vehicle with videocamera (usually used for mirrors but also some other "real" cameras) and a skinzip, there's a little problem. If you just spawn it with the default skin, it'll all be ok. If you spawn a skin from the skinzip, the videocamera will be replaced by the texture used for it.
This also happens if the replaced texture and the replacing texture are the same.
If you now respawn the vehicle with another skin from the skinzip, the videocamera will work in it (but show the camera from the first vehicle, known bug).

How to reproduce:
-Get this: http://www.rigsofrods.com/threads/120099-Mercedes-Benz-L508-D-Bus-My-late-night-Show-D  Or another vehicle with videocameras and a skinzip
-spawn the standard skin
-leave the game, spawn a skin from the skinzip

v the car which you can see through the mirrors isn't green irl
![screenshot_39](https://cloud.githubusercontent.com/assets/12358849/9282123/7eb1cb24-42ca-11e5-8525-2bd2ef20d1af.jpg)
![screenshot_40](https://cloud.githubusercontent.com/assets/12358849/9282138/8a18d796-42ca-11e5-8618-b404b8def867.jpg)
![screenshot_53](https://cloud.githubusercontent.com/assets/12358849/9282141/8dc23112-42ca-11e5-8d89-29cb8b05472e.jpg)

**Comment by DirtGamer301** [comment]
Bumping to get a bug label (or something) as I think this bug was being overseen.

**Comment by only-a-ptr** [comment]
@DirtGamer301 Thanks for reporting, this wasn't known.

**Comment by Dogy144** [comment]
I would like to add that material flares are also broken with skinzips.

**Comment by Michael10055** [comment]
Fixed in #1271
