### ISSUE TITLE
Slower changing cinematic camera

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#403]
When flying ultra fast planes, like this one: http://www.rigsofrods.com/threads/71989-SU-37-HOT

The cinematic camera goes so fast that you can't look at the plane. Maybe make the cinematic camera switch with time instead of the distance the object has moved?

**Comment by tritonas00** [comment]
This happens with all planes, cinematic camera is too fast

https://www.dropbox.com/s/syh913bx7bdcg25/planecam.mp4?dl=0
