### ISSUE TITLE
Flares2: Parser too strict (enforces separation by space)

### ISSUE THREAD

**Issue by xTakedownJnR** [RigsOfRods/rigs-of-rods#408]
For some reason the truck parser doesn't recognize what the "flares2" section is and completely ignores it. flares2 link: http://www.rigsofrods.com/wiki/pages/Truck_Description_File#Flares2

-What happens-
The flares that use flares2 don't work.

How to reproduce
1.Spawn the vehicle
2. Turn on the lights (the flares that use flares2 don't show up.

<addr>Log
21:19:13:  ===== LOADING VEHICLE: Pete379Logger.truck
21:19:13:  == Parsing vehicle file: Pete379Logger.truck
21:19:13:  == Parsing done, report:

#FF3300 ERROR #FFFFFF (Section guisettings)
	Line (64): speedoMax 136.794
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section flares2)
	Line (1234): 87, 86, 90, 0.231, 0.713, 2.5, f, -1, 0, 0.40, tracks/brakeflare
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section flares2)
	Line (1235): 87, 86, 90, 0.284, 0.713, 2.5, f, -1, 0, 0.40, tracks/brakeflare
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section flares2)
	Line (1236): 87, 86, 90, 0.335, 0.713, 2.5, f, -1, 0, 0.40, tracks/brakeflare
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section flares2)
	Line (1237): 87, 86, 90, 0.661, 0.713, 2.5, f, -1, 0, 0.40, tracks/brakeflare
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section flares2)
	Line (1238): 87, 86, 90, 0.713, 0.713, 2.5, f, -1, 0, 0.40, tracks/brakeflare
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section flares2)
	Line (1239): 87, 86, 90, 0.764, 0.713, 2.5, f, -1, 0, 0.40, tracks/brakeflare
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section flares2)
	Line (1241): 29, 28, 30, 0.07, -0.5, 3, f, -1, 0, 1, tracks/brakeflare
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section flares2)
	Line (1242): 29, 28, 30, 0.90, -0.5, 3, f, -1, 0, 1, tracks/brakeflare
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section flares2)
	Line (1244): 29, 28, 30, 0.07, -0.10, 3, R, -1, 0, 0.6, tracks/flare
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section flares2)
	Line (1245): 29, 28, 30, 0.90, -0.10, 3, R, -1, 0, 0.6, tracks/flare
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section flares2)
	Line (1247): 29, 28, 30, 0.07, -0.5, 3, l, -1, -1, 1, tracks/brakeflare
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section flares2)
	Line (1248): 29, 28, 30, 0.90, -0.5, 3, r, -1, -1, 1, tracks/brakeflare
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section flares2)
	Line (1250): 29, 28, 30, 0.07, -0.5, 3, b, -1, 0, 1, tracks/brakeflare
	Message: Invalid line, ignoring...
#FF3300 ERROR #FFFFFF (Section flares2)
	Line (1251): 29, 28, 30, 0.90, -0.5, 3, b, -1, 0, 1, tracks/brakeflare
	Message: Invalid line, ignoring...<addr>
Link to truck: http://www.rigsofrods.com/repository/view/5400

**Comment by DarthCainRor** [comment]
No probem on my T800. Flares2 all work properly.
![screenshot_15](https://cloud.githubusercontent.com/assets/10333582/9296690/0c9594e6-4458-11e5-9223-748ab4539fe4.png)

**Comment by gigapouch** [comment]
Oh, the Ctrl+1,2,etc flares? Working fine here too.

**Comment by DarthCainRor** [comment]
No. He means flares that are coded as flares2, rather than flares. I do see this error on some of my things though. All have values larger than 1. So I wonder if the parser doesn't know what to do in that instance.

**Comment by DarthCainRor** [comment]
Found the Issue. Remove the comma between the last number, and the material for the flare. The old parser didn't mind if there was a comma there and ignored it, but the new one doesn't like the comma there, as it isn't there in the description.

**Comment by xTakedownJnR** [comment]
Thanks DarthCain :)

**Comment by only-a-ptr** [comment]
I'm going to loosen the parser rules anyway, just to avoid cases like this in the future.
