### ISSUE TITLE
Move all screenshots to a folder instead

### ISSUE THREAD

**Issue by Max98** [RigsOfRods/rigs-of-rods#41]
For the moment, all screenshots are saved at the root folder: My Documents/Rigs of rods 0.XX/
I believe that if we move them to: My Documents/Rigs of rods 0.XX/Screenshots/ 
It will be more organized and clearer.

**Comment by Aperion** [comment]
I agree, it would also be nice if numbering did not restart between instances. Perhaps use a timestamp instead of a count.

**Comment by Max98** [comment]
So you mean something like:
RoRScreenshot_VERSION_YEAR/MONTH/DAY_TIME.png/jpg?

**Comment by Aperion** [comment]
More like screenshot-<DateTimeFormat>.(png|jpg) where <DateTimeFormat> could be YYMMDDHHmmSS  or unix time(seconds since 1970-01-01), or YYYY-MM-DD-HH-mm-SS

**Comment by Max98** [comment]
Not that far from what i said. ;P

**Comment by Aperion** [comment]
I want sure if the slashes were folders.

**Comment by only-a-ptr** [comment]
Heh, I actually got the same idea while commenting #473
