### ISSUE TITLE
"-" in vehicle name will bug the search function

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#412]
If a vehicle has a "-" in the name (like "Mercedes-Benz" for example) the search function will be bugged. This bug also occurs in the older RoR versions 0.38.67 and 0.4.0.7.
If you type the name into the search function, everything will be fine, until you reach the "-". It'll remove everything written before in the search box.

**Comment by ulteq** [comment]
I can't reproduce it on linux.

**Comment by DirtGamer301** [comment]
![unbenannt10](https://cloud.githubusercontent.com/assets/12358849/18436962/2c4e0ae2-78fb-11e6-9f79-d6d34ae51fa5.png)
Adding an image since it was on the Gitter chat.

If I use the minus sign, this bug doesn't occurs, but if I use dash sign, the Mercedes word is erased. ~Ulteq from the Gitter chat.

**Comment by wilkgr76** [comment]
The / also clears the search bar.

**Comment by only-a-ptr** [comment]
I found the problem: as @wilkgr76 says, the "/" brings focus to the search bar and clears it.

But there's a catch: Apparently RoR doesn't detect the incoming "/" character (=keycode) but detects pressing a specific button on keyboard (=scancode). This one:
![image](https://user-images.githubusercontent.com/491088/31813444-ad9d6a20-b586-11e7-80ec-a1f530ea8779.png)

What now? Nothing much. Starting with https://github.com/RigsOfRods/rigs-of-rods/pull/1333 the loader UI is going to be remade anyway, so I'll take care of this in the process.

**Comment by disloyalpick** [comment]
Also the search bar is always activated when opening RoR. Which means you will have to click on a section of the terrain selector to be able to use the arrow keys.
