### ISSUE TITLE
semi automatic shift mode missing

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#413]
In 0.38, the automatic gearbox was more like a half-automatic one. If you wanted to you were able to shift, but RoR still shifted itself.
This for example was useful for going into reverse gear if you didn't want to use Arcade Control (which would make oyu go into reverse by pressing the brake). But also, if you wanted to up/downshift different then the automatic gearbox would.

**Comment by gigapouch** [comment]
Yep, it's the only thing I don't like about 0.4 is that it automatically shifts into reverse. I want to keep the brake down and not go in reverse unless I want to.

**Comment by DirtGamer301** [comment]
Disable Arcade Controls (remove the tick in RoRConfig). That's not exactly what I was talking about ^^

**Comment by gigapouch** [comment]
Oh, OK.

**Comment by Max98** [comment]
Stop using the [tags] on your issues titles.

**Comment by Hiradur** [comment]
Shifting is screwed up in general, is that correct? I can't get it to shift in most of the modes (use Q to switch between shifting modes)

**Comment by DirtGamer301** [comment]
I'm sorry, I can't give any information of fully manually shifting. I only use automatic and manual with automatic clutch.

**Comment by Hiradur** [comment]
Downshifting works in no mode for me. Shifting up/down is impossible in automatic mode in neutral.

**Comment by Hiradur** [comment]
My bad, downshifting is on 'z' but I pressed 'y' due to the German keyboard layout.

You can actually set semi automatic as default shift mode in RoRConfig->Gameplay

It should be the default value for the first start though.

What remains is this bug: 
With automatic shifting and being in Neutral gear the automatic doesn't shift nor can the player shift manually.

**Comment by DirtGamer301** [comment]
@Hiradur 
On a german keyboard it's y to downshift so you should've done correctly :p
A to up-, and Y to downshift.

**Comment by Hiradur** [comment]
Doesn't seem to be this way on Linux.

**Comment by only-a-ptr** [comment]
@Hiradur /RigSpawner: It's the same in 0.4.0.7: https://github.com/RigsOfRods/rigs-of-rods/blob/bd680916356ea033716c96582305a37347644b9a/source/main/physics/input_output/SerializedRig.cpp#L2737

**Comment by Hiradur** [comment]
fixed

**Comment by only-a-ptr** [comment]
@Hiradur "Fixed" by no commit? :smile: Details please.

**Comment by Hiradur** [comment]
Right, where are my manners :blush:
fixed in https://github.com/Hiradur/rigs-of-rods/commit/97a9aa0d673ad62e5bccceb552db1d94a24fdd0f

Didn't touch the enum, instead changed the logic to resemble the behaviour of 0.38
