### ISSUE TITLE
Rigs of Rods forums???

### ISSUE THREAD

**Issue by Erie-E8** [RigsOfRods/rigs-of-rods#417]
What happened to the forums? Why are they down? Will they ever come back?

**Comment by gigapouch** [comment]
They're probably moving to the new site. I thought you were banned, anyway.

**Comment by DirtGamer301** [comment]
You shouldn't be able to see them anyways because you're banned.

**Comment by Erie-E8** [comment]
I can still see them. I delete my browsing history and I could view them as a guest.

**Comment by gigapouch** [comment]
idk but I do know that the new address for the new site is rigsofrods.github.io.

**Comment by DirtGamer301** [comment]
rigsofrods.github.io
As it looks a plugin on the forum caused problems, attachments were being deleted andtdev currently restores them which will take some time.

**Comment by Erie-E8** [comment]
Oh, ok.

**Comment by gigapouch** [comment]
The main site is down too! I just clean installed my copy of Windows 7 and RoR and I can't download any mods! D:

**Comment by Hotrod55** [comment]
The site's backup is being restored, don't worry. Just takes a day or two due to all the files and attachments.

**Comment by skybon** [comment]
This is an issue tracker, not discussion forums. Closing
