### ISSUE TITLE
MSVCP100.dll is missing?

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#418]
I installed Visual Studio 2010 redist but I am still getting this error. Same with RoRconfig.
![error](https://cloud.githubusercontent.com/assets/7621364/9400091/fca3273e-4771-11e5-8252-d006b045d226.png)

**Comment by Max98** [comment]
Then you didn't install it correctly.

**Comment by gigapouch** [comment]
It said it installed correctly...

**Comment by gigapouch** [comment]
Never mind, the x86 version of VS 2010 Redist fixed the issue.

**Comment by robbyfine** [comment]
This pop-up is a very common error. To solve it, you have to download the missing msvcp100.dll file from http://fix4dll.com/msvcp100_dll . I`m 100% positive, it will help you. Anyway, good luck!
