### ISSUE TITLE
Fixed free cam goes away when entering a vehicle

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#419]
If this wasn't supposed to be like that, I'd like to report it as a bug because the way it behaved in older versions was better IMO.
If you're in fixed free cam, and enter a vehicle, the free cam will go away and you'll be in normal 3th person view at the vehicle.
Edit: The same thing happens when being in a vehicle, going into free cam, then into fixed free cam and leave the vehicle, just that the camera will be at RoRBot for sure.

**Comment by Hiradur** [comment]
I agree, the camera should still be in fixed free cam mode when entering a vehicle

**Comment by only-a-ptr** [comment]
I'll definitely get the old behaviour back as a config option.
However, I'm not quite sure whether to enable it by default. Personally, I prefer when the camera stays the way I switched it, that's more RoR-like. But at the same time, resetting camera on enter/exit is more "typical", and we need "typical" for new players. Even previous authors (Theshark + Ulteq) added "typical" features like arcade controls for leisure players.

Conclusion: I'm going to add these new config options:
```
    Camera_EnterVehicle_KeepFixedFreeCam     | bool, default false
    Camera_ExitVehicle_KeepFixedFreeCam      | bool, default false
```

**Comment by only-a-ptr** [comment]
Done
