### ISSUE TITLE
Most cars spin out too much

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#422]
When driving a lot of cars/small trucks (not semis), they like to turn to the side sometimes (well, actually  all the time) and spin out. This does not happen with heavier cars.

**Comment by skybon** [comment]
This may be mod creators' fault, not physics engine problem.

**Comment by gigapouch** [comment]
Not just a few, but a lot of small cars have this problem. All those mod creators made the same mistake?

**Comment by FTC7837** [comment]
I suppose the logical next step would be to try those small cars in 0.38 or earlier and see if they still perform the same way.

**Comment by Bendito999** [comment]
I suppose the logical next step would be to try those small cars in 0.38 or earlier and see if they still perform the same way.

**Comment by gigapouch** [comment]
Yep, the same cars do the same thing in 0.38. When upgrading to 0.4 I thought this was solved.

**Comment by DarthCainRor** [comment]
Are you talking about vehicles sliding side to side? If so I think it has to do with set_beam_defaults, as most of my lighter trucks and trailers exhibit the same phenomenon.

**Comment by gigapouch** [comment]
That happens a lot too, and is annoying, but not exactly what I meant. Some cars do spin out everywhere even when you try not to drive them so hard.

**Comment by Hiradur** [comment]
To clarify:
Are you talking about going straight and at higher speeds the cars turn slightly into one direction until they spin out?

**Comment by Hiradur** [comment]
@TechGiga Could you answer my question above and provide an example for a car where this happens?

**Comment by TechGiga** [comment]
Yep, that's what I'm talking about, most of the time. I guess the Gavril MZ2 is one of them. 

I think part of the problem is that RoR cannot map steering wheel controls, even with 0.37. If it could, I could drive with partial throttle and not lose control.

**Comment by Hiradur** [comment]
@TechGiga RoR supports steering wheels. It may just have an issue with the wheel you are using.

One reason why this could happen that just came to my mind is that one of the wheels looses contact to ground for some time due to n/b vs mesh collision.
Do the vehicles always steer to the same side?

**Comment by TechGiga** [comment]
My wheel works fine with ETS2, BeamNG, and a few other games, so I don't think it's my wheel.

No, the vehicles don't always steer to the same side. Sometimes even the buses by Atilla1992 steer slightly to one side.

**Comment by Hiradur** [comment]
It's possible that your wheel may be too new so OIS doesn't recognize it. OIS is the input system RoR uses and hasn't been updated for a long while.

**Comment by TechGiga** [comment]
Yep, just got it last month.

**Comment by Michael10055** [comment]
I'm closing this as the "vehicles spinning out" depends on how the mod is designed. Don't just floor it everywhere and you'll be fine. And in recent builds you can hold ctrl or alt + up key to decrease the increase of throttle:
```
TRUCK_ACCELERATE_MODIFIER_25   Keyboard             ALT+UP 
TRUCK_ACCELERATE_MODIFIER_50   Keyboard             CTRL+UP 
```
