### ISSUE TITLE
No turbo sounds or gauges

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#428]
http://www.rigsofrods.com/threads/120168-No-turbo-sounds-or-gauges?p=1386196#post1386196

**Comment by Speciesx** [comment]
Only Turbo v2 works.
![ror_2015_08_27_19_31_56_879](https://cloud.githubusercontent.com/assets/1196375/9527945/5c8b9692-4cf2-11e5-932f-80da38539516.png)
![ror_2015_08_27_19_31_09_247](https://cloud.githubusercontent.com/assets/1196375/9527946/5c8bbe38-4cf2-11e5-883b-bb0e038260b6.png)
![ror_2015_08_27_19_31_40_120](https://cloud.githubusercontent.com/assets/1196375/9527948/5c9187fa-4cf2-11e5-8eb1-76242a0e786e.png)

**Comment by gigapouch** [comment]
They also removed the pedal visualization. :(

**Comment by Max98** [comment]
Well, @Speciesx removed it. ;P

Taking a look into this.

**Comment by graysonk95** [comment]
The "turbo" source for add_animation does not work in 0.4.5.1 but works in 0.4.0.7.
