### ISSUE TITLE
Update setting file to use sections?

### ISSUE THREAD

**Issue by Max98** [RigsOfRods/rigs-of-rods#43]
One could say that INI config files (Or a Linux equivalent) are more organized, thus, we can organize graphics settings alone, physics settings alone, etc..

Edit: I didn't know that they actually were inis. What we should do here is use sections.

**Comment by only-a-ptr** [comment]
Which conf files do you mean exactly? Most of them use Ogre::Script, which is already INI, and whitespace-tolerant,which is an advantage.
I created rig_editor.conf for editor specifi stuff
We can split ror.conf when it gets too big. Right now it' small enough

**Comment by Max98** [comment]
I actually mean that we should use the sections. What I mean is something like this: http://pastebin.com/bCnFBcr2

**Comment by only-a-ptr** [comment]
Why not? Nice to have organized configs. Go ahead if you wish.
