### ISSUE TITLE
Beacon Issue

### ISSUE THREAD

**Issue by graysonk95** [RigsOfRods/rigs-of-rods#432]
Beacons seem to be messed up as of 0.4.5.1.
The lightbar.mesh beacons are now completely synchronized, and colored beacons on other vehicles now default to orange and don't seem to be unsynchronized either:
https://youtu.be/xQHHfAtYfqc

**Comment by only-a-ptr** [comment]
@graysonk95 I wasn't able to reproduce this. Please describe in detail how you tested it. For me, beacons are broken since 045 - the flares are stuck at the (0,0,0) corner of the map, only sound is working.
![screenshot_8](https://cloud.githubusercontent.com/assets/491088/9756324/92fa53da-56d9-11e5-84cf-734bf7d7c0c6.jpg)

Builds I tested: 
** 045TestBuild5 http://www.rigsofrods.com/threads/119110-Test-Build-Rigs-of-rods-0-4-5-0-dev?p=1385090#post1385090
** Official 0451 https://github.com/RigsOfRods/rigs-of-rods/releases/tag/0.4.5.1

My test scenarios:
* Clear cache (manually delete files)
* Run ror, select SimpleTestTerrain, load old Dodge Police (that's the vehicle you used, right?) http://www.rigsofrods.com/repository/view/3762
* Press 'H' (horn/police siren) to activate the lightbar.

**Comment by DarthCainRor** [comment]
M activates the light bar. H is just the horn. The beacons work in the correct collor for my, but they are synchronized.
![screenshot_70](https://cloud.githubusercontent.com/assets/10333582/9860422/b57d4842-5af1-11e5-894f-9c0e6a39a2a3.png)

**Comment by graysonk95** [comment]
I simply spawned the Dodge Police and pressed 'M' for the beacons as I would with any other version.
I used 0.4.5.1, built August 25th (I'm not sure where I can find the build number, the "About" tab in the Configurator doesn't have one so I won't be of much help here).

The beacons on the lightbar.mesh were the correct color, they were just synchronized.
Other vehicles that use individual beacons now only spawn with orange in the version I am using.
The ambulance in my test video has blue beacons, but they spawned as orange ones.

I know the non-orange colored beacon meshes were made/modified by Isaac.Eiland-Hall and were never built-in or pre-packaged with the game, but the beacon flare functionality was.
I would imagine something about the built-in orange beacon is overriding the added colored ones.
(Any vehicles that use a non-orange beacon must include the mesh for it in their zip).

**Comment by only-a-ptr** [comment]
@graysonk95 Post download link to the ambulance, please. I need to see the definitions of those beacon flares.

Technically, a flare is a billboard - geometry (two triangles) and a material (flare texture, transparent). To make new flares, modder must supply a new material, either using built-in flare tex with re-coloring rules in the material, or with new tex.

The problem may be that RoR fails to load the new material/texture and falls back to defaults.

**Comment by graysonk95** [comment]
The ambulance was made circa v0.34/0.35, I downloaded it in 2010, so I honestly have no idea where to find it individually.

I know it has been reskinned many times and a version is bundled with the map "Starling Island".
http://www.rigsofrods.com/threads/109425-Updated-terrains-for-0-4-0-7?p=1260243&viewfull=1#post1260243

**Comment by only-a-ptr** [comment]
@graysonk95 We need to find some publicly available vehicle to test with.

Try with old Dodge Police http://www.rigsofrods.com/repository/view/3762 (like I did in a post above) or suggest something else.

**Comment by graysonk95** [comment]
I believe this is the original vehicle:
http://www.rigsofrods.com/repository/view/2002

**Comment by only-a-ptr** [comment]
Flare coloring resolved - the vehicles from pack http://www.rigsofrods.com/repository/view/2002 now flash blue.

**Comment by only-a-ptr** [comment]
Resolved!
I still need to tackle the "corner flash" glitch tho.

**Comment by graysonk95** [comment]
The big flare in the corner of the map glitch has existed for the entire 5+ years I've been here.

I reported it in 0.37.126 on the Redmine... never got fixed.

**Comment by only-a-ptr** [comment]
@graysonk95 ...So it's not anything I broke, but something that's been missing. Thanks, that's a helpful note.

**Comment by Hiradur** [comment]
@only-a-ptr Just stumbled across this: https://github.com/RigsOfRods/rigs-of-rods/commit/bbcf51c53317474098b7229a86bff697153a3293
