### ISSUE TITLE
Chevy G20 does not work in 0.4.5

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#433]
The Chevy G20 does not work in 0.4.5 but did in 0.38: http://www.rigsofrods.com/threads/104676-1986-G20-Chevrolet-van

When I try loading it in 0.4.5, all I see are stars.

**Comment by Hotrod55** [comment]
I haven't tested/looked at the .truck file yet, however I'm pretty sure this is caused by fusedrag autocalc.
#134

**Comment by TechGiga** [comment]
Whatever that is... lol

**Comment by Aivar-RoR** [comment]
I can confirm that this is caused by the fusedrag autocalc bug. The vehicle works fine when the fusedrag section is commented out.

**Comment by Hiradur** [comment]
Closing as duplicate of #134
