### ISSUE TITLE
Trailer explodes

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#434]
Spawn and activate the trailer.

http://www.rigsofrods.com/repository/view/4823

== Parsing done, report:

 ERROR  (Section ropables)
	Line (6): fileinfo , 117, 2
	Message: Inline-section 'fileinfo' has invalid format, ignoring...
 ERROR  (Section managedmaterials)
	Line (13): IHwoodtrailerpartstex
	Message: Invalid line, ignoring...
 ERROR  (Section managedmaterials)
	Line (14): mesh_standard		IHWtrailerparts.dds
	Message: Invalid line, ignoring...
 ERROR  (Section slidenodes)
	Line (310): cab
	Message: Misplaced sub-section 'cab' (belongs in section 'submesh'), ignoring...

 == Validating done OK

 WARNING (Keyword managedmaterials)
	Managed material 'IHWtrailertex' already exists (probably because the vehicle was already spawned before)
 ERROR (Keyword globals)
	Material 'tracks/semi' defined in section 'globals' not found. Trying material 'tracks/transred'
 ERROR (Keyword slidenodes)
	No beam between nodes indexed '18' and '0'
 ERROR (Keyword slidenodes)
	No beam between nodes indexed '37' and '0'
 ERROR (Keyword slidenodes)
	No beam between nodes indexed '19' and '0'
 ERROR (Keyword slidenodes)
	No beam between nodes indexed '1' and '17'
 ERROR (Keyword slidenodes)
	No beam between nodes indexed '19' and '0'
 ERROR (Keyword slidenodes)
	No beam between nodes indexed '18' and '0'
 ERROR (Keyword slidenodes)
	No beam between nodes indexed '0' and '0'
 ERROR (Keyword slidenodes)
	No beam between nodes indexed '43' and '0'
 WARNING (Keyword ~Unknown~)
	vehicle uses no GUID, skinning will be impossible

**Comment by only-a-ptr** [comment]
Line (6): fileinfo , 117, 2
This is a piece of ***** ! :angry: http://www.rigsofrods.com/wiki/pages/Truck_Description_File#Fileinfo

But oh well, the old parser would swallow it, so I guess I'll have to "improve" my new parser...

**Comment by only-a-ptr** [comment]
Fixed the "fileinfo", still explodes. Now the slidenodes...
