### ISSUE TITLE
ror ignore terrains with PSSM shadow support

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#435]
STR:
- Add terrains with PSSM shadow support
- Clear cache
- Start ror

Terrains with PSSM shadow support will not listed in terrain loader.

>18:14:46: Adding archive c:\users\xxxx\docume~1\rigs of rods 0.4\terrains\d3_dega1.zip (hash: 7A77B0C5E12FC937694B9ECF178AB64FD69EEB46) (No Compression)
18:14:46: Loading c:\users\xxxx\docume~1\rigs of rods 0.4\terrains\d3_dega1.zip
18:14:46: Creating resource group General-102
18:14:46: Added resource location 'c:\users\xxxx\docume~1\rigs of rods 0.4\terrains\d3_dega1.zip' of type 'Zip' to resource group 'General-102'
18:14:46: Initialising resource group General-102
18:14:46: Parsing scripts for resource group General-102
18:14:46: Parsing script snow-alpha.program
18:14:46: Parsing script baja_gate1.material
18:14:46: OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource managed_mats.material in resource group General-102 or any other group. in ResourceGroupManager::openResource at C:\data\codehg\dependencies\src\Ogre\ogre_src_v1-8-1\OgreMain\src\OgreResourceGroupManager.cpp (line 756)
18:14:46: error while loading single Zip: OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource managed_mats.material in resource group General-102 or any other group. in ResourceGroupManager::openResource at C:\data\codehg\dependencies\src\Ogre\ogre_src_v1-8-1\OgreMain\src\OgreResourceGroupManager.cpp (line 756)
18:14:46: error opening archive 'c:\users\xxxx\docume~1\rigs of rods 0.4\terrains\d3_dega1.zip'. Is it corrupt? Ignoring that archive ...
18:14:46: trying to continue ...

**Comment by Hiradur** [comment]
can you link an example terrain?

**Comment by Speciesx** [comment]
https://www.mediafire.com/folder/69zgdbkz2i474/RoR_0.4.5.0_Terrains

**Comment by only-a-ptr** [comment]
@Speciesx Check that your RoR/resources/managed_materials directory contains managed_mats.material.

It does exist in upstream: https://github.com/RigsOfRods/rigs-of-rods/tree/master/bin/resources/managed_materials

Also, the upstream code does load it: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/main_sim/MainThread.cpp#L1509

Additionally, post whole RoR.log please, there's a part which lists all resource groups - I want to see if ManagedMats is in there.

**Comment by only-a-ptr** [comment]
Umm... I think I know where's the problem ... the cache gets refreshed before managed_materials is loaded. Upon cache refresh, the map is added to OGRE resource system -> materials are parsed, dependency on managed_mats is unresolved -> exception is thrown and RoR doesn't know it's normal -> BOOM.

**Comment by only-a-ptr** [comment]
Fixed.
