### ISSUE TITLE
Doxygen: remove obsolete "Todo List" + "Bug List" pages

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#439]
RoR's Doxygen documentation http://anotherfoxguy.github.io/RoRdocs/ contains two obsolete and useless sections (accessible from left navigation menu, right at the top):
* Todo List http://anotherfoxguy.github.io/RoRdocs/d2/da6/a01210.html
* Bug List http://anotherfoxguy.github.io/RoRdocs/dc/db6/a01212.html

These should be removed.

**Comment by AnotherFoxGuy** [comment]
This can be closed
http://developer.rigsofrods.org/doxygen/
