### ISSUE TITLE
Air_Purge triggered from Shock stability option L or R

### ISSUE THREAD

**Issue by graysonk95** [RigsOfRods/rigs-of-rods#442]
I've tried using the stability options (l/r) for Shocks in the past and I have always gotten this same issue. If the vehicle has a sound to be played by the air_purge trigger, it plays whenever the vehicle rocks left to right.
I'm not sure if this is a glitch, unfinished feature, or what, but I don't think this is the intended operation of that sound trigger.
Plus stability seems to have no impact on handling.
https://www.youtube.com/watch?v=FWEDlsFNySs&feature=youtu.be

I have thought of putting a creak sound as air_purge to make it sound like the suspension is creaking, but the trigger stutters way too much for that to work.

**Comment by only-a-ptr** [comment]
@graysonk95 I don't know how are the l/r flags supposed to work, but I suppose it's not very widely used and perhaps not configurable enough.

The AIR_PURGE trigger seems a little overused in general. 

I'll take care of this later when I introduce Lua scripting.

**Comment by graysonk95** [comment]
Like I said in the OP, I have never noticed the flags having any noticeable impact on handling.

Just by its name, "air_purge" implies it should play the sound of the air dryer purging (or spitting as some people call it), but since RoR doesn't simulate a truck's air system, it should just play randomly while the engine is running.
Currently the trigger "air" is what seems to more closely mimic the behavior of the air dryer.

Speaking of, that brings to mind another depreciated feature involving the air trigger.
I'll create a ticket for it since it involves the wheels2 section, but causes the air sound to play on vehicles regardless of the section used to define the wheels.

**Comment by only-a-ptr** [comment]
**There's a bug in spawning code (damn copy-pasting!)** :blush:
The left stability shock is registered as both right+left shock, while the right one is ignored. :blush:
>    RigSpawner::ProcessShock(RigDef::Shock & def) 
>    https://github.com/only-a-ptr/rigs-of-rods/blob/editor-python-dirty/source/main/physics/input_output/RigSpawner.cpp#L4158
    
>>    Left active shock: https://github.com/only-a-ptr/rigs-of-rods/blob/editor-python-dirty/source/main/physics/input_output/RigSpawner.cpp#L4179
>>    Right active shock: https://github.com/only-a-ptr/rigs-of-rods/blob/editor-python-dirty/source/main/physics/input_output/RigSpawner.cpp#L4185
