### ISSUE TITLE
Ability to interact with OS while in RoR

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#443]
When I play RoR, my mouse is stuck to that window and cannot move outside it or I can press the start menu button unless I close it. BeamNG has this capability and I think RoR should definitely have it too.

**Comment by DirtGamer301** [comment]
You might wanna add that if in RoR you switch to Windows (idk if it also happens on Linux) and then back to RoR the vehicle materials are screwed up.

**Comment by TechGiga** [comment]
Didn't notice that...

**Comment by DirtGamer301** [comment]
Just added it as it comes back to the same/similar topic ;)

**Comment by Hiradur** [comment]
RoRConfig -> Debug -> Input Grabbing = Dynamically should be would you are looking for.

**Comment by DirtGamer301** [comment]
I think we don't.

**Comment by Jb121212** [comment]
How do I download ror on a macbook pro? I have the latest software update, and I have safari as a web browser.

**Comment by TechGiga** [comment]
AFAIK RoR has not had a stable release for Mac in quite a while and may not be supported.

**Comment by Hiradur** [comment]
@Jb121212 See http://rigsofrods.github.io/en/download/

**Comment by Hiradur** [comment]
@DirtGamer301 Did you create the ticket yet?

Closing since there isn't much more to say.
