### ISSUE TITLE
Otter.airplane spawn error

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#447]
http://www.rigsofrods.com/threads/114853-Install-scripts-for-latest-snapshot-for-Debian-Ubuntu-Mint?p=1388123&viewfull=1#post1388123

**Comment by only-a-ptr** [comment]
It spawns well in the current upstream code.

**Comment by Hiradur** [comment]
Spawns under the surface on Auriga Proving Grounds with OpenGL for me. Heavy physic glitches afterwards. Works fine on simple2 terrain.

**Comment by only-a-ptr** [comment]
@Hiradur Thanks, I'll check it out

**Comment by Hiradur** [comment]
I think the problem is that when you spawn the plane on a mesh it seems to spawn in the ground because only the heightmap is taken into account for spawn height.
