### ISSUE TITLE
RoRbot's seating location.

### ISSUE THREAD

**Issue by DarthCainRor** [RigsOfRods/rigs-of-rods#448]
In the newer versions of the game, with the newer RORbot, when seated in a user defined -seat.mesh, it appears that he is off set, and not seated at the same origin as the old RoRbot.

Vehicles: Any vehicle with seats that rorbot sits in, either custom seats or standard ones.

Old position:
![screenshot_186](https://cloud.githubusercontent.com/assets/10333582/10977409/7dcf406a-83b6-11e5-8968-e501909d81d7.jpg)

New position:
![screenshot_181](https://cloud.githubusercontent.com/assets/10333582/10977414/8903a64c-83b6-11e5-8b6f-a5fa7b1a478f.png)

**Comment by only-a-ptr** [comment]
@DarthCainRor Thanks for reporting.
Please specify "newer versions of RoR" - which version was the first to introduce this issue? Was it 0.4.5 or 0.4.0.x?

**Comment by DarthCainRor** [comment]
I have no idea. I used .38 until .4.5 was release. As far as I can tell it probably has to do with the new model for RoRBot, but I don't know what version he was originally replaced in.

**Comment by DarthCainRor** [comment]
Well, after a bit of checking I can confirm that their origins are not identical. That may have something to do with it. New RoRbot is centered while old, is not.


![](https://i.gyazo.com/b30a8c8659ec367a62bd93dcec9248e4.png)

**Comment by DirtGamer301** [comment]
https://github.com/RigsOfRods/rigs-of-rods/issues/247
I'll add this as both issues have to do with RoRBot.

**Comment by only-a-ptr** [comment]
@DarthCainRor : Thanks for investigating the RoRbot mesh. I'll check the code.

**Comment by only-a-ptr** [comment]
@DarthCainRor : Version 0.4.0.7 works fine. I'll check what changed.

**Comment by Hiradur** [comment]
hagdervriese made the new RoRBot (or the animations at least, not sure). Maybe he can help out.

@only-a-ptr Are you sure the problem is not the different origin of the meshes?

**Comment by only-a-ptr** [comment]
@Hiradur Quite sure. It's a detail.

Furthermore, animations, by definition, move RoRBot's body parts around the origin, possibly moving the entire character around the origin. Even though oldbot's origin is off, the "driving" animation might be perfectly centered. And vice versa, even though newbot's origin is centered, the  "driving" animation might be off - possibly to the level where it places newbot to a different seat!

**Comment by only-a-ptr** [comment]
@DarthCainRor I just opened DAF's truckfile and this is what I found:
```
 props
...SNIP...
 1,4,50,  1.7, 0.1, 0.2, 0, 0, 0, seat.mesh
 49,51,0, 1.7, 0.9, 0.2, 0, 0, 0, seat.mesh
```
Try erasing the passenger seat and see what happens. I suspect old/new parser behave diffently when multiple seats are present.

**Comment by DarthCainRor** [comment]
I can test it when I get off work, but even the rorbot in my custom seat on one of the trucks I'm working on sits off centered.

**Comment by only-a-ptr** [comment]
@DarthCainRor It's true, the code compensates for old-rorbot's decentered origin. I'm working on it.

**Comment by only-a-ptr** [comment]
Fixed.

**Comment by DarthCainRor** [comment]
Awesome! Sorry I didn't test. I've been extremely busy as of late.
