### ISSUE TITLE
Weird vehicle materials after changing to Windows

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#452]
I don't know about a better title :P

![ad7aae44-7aa1-11e5-8c95-10821ce7fb15](https://cloud.githubusercontent.com/assets/12358849/11191889/3611de4a-8c9e-11e5-9d1b-c157cd9f728f.jpg)

If you're in RoR and change to any other window/a Windows window appears and you go back to RoR usually the vehicles materials are screwed up.

I should add I "tested" with DirectX9, Windows 7, RoR 0.38.67, 0.4.0.7, 0.4.5.1, I can only remember the bug happen on shiny materials/a material which has a spec file specified and not always on every material.
Usually, I experienced the vehicle look similar to the photo above, but once it was simply all brown, the shinyess was gone except when I re-entered the vehicle.

**Comment by Hiradur** [comment]
Can you link an example vehicle?

**Comment by Hiradur** [comment]
Doesn't happen with the GV3 on Linux with OpenGL. But the vehicle is grey, not red, did you mod it?

**Comment by DarthCainRor** [comment]
I've never noticed it with any other vehicles. Just tested this on Auriga, with the GV3. Windows 8.1, directx, and alt-tabing out of the full screen. Results in Black car when returning.

![screenshot_197](https://cloud.githubusercontent.com/assets/10333582/11236116/984f83ce-8d9c-11e5-8bd8-61da7bc423c1.png)

From checking the log, and not really knowing much coding, it looks like directX is doing weird things on window focus changes

http://pastebin.com/Pv43qpVX

**Comment by DirtGamer301** [comment]
@Hiradur 
Yes, the shown vehicle is indeed modded, it's simply the only pic I found, but it happens with aby other cars.
Also, it's the, for me, most common thing that it'll look as in my picture, but it can also look different like DarthCains picture shows.

**Comment by only-a-ptr** [comment]
@DirtGamer301 I develop on windows 7 64bit, I run windowed mode (DirectX9) and switch in/out all the time. I never observed this.

I'm at work right now, I'll check some more when I get home

**Comment by DirtGamer301** [comment]
Same here (Win 7, DX9 windowed mode, sometimes fullscreen).
I remember being asked to add/remove the tick at "Disable multi-threading" for this which I remember didn't change anything.
Also, this bug doesn't occur always, but nearly.

**Comment by Hiradur** [comment]
@only-a-ptr Did you use the Gavril GV3? It seems to be related to the material used by the vehicle.

**Comment by DirtGamer301** [comment]
I just did a quick test, Ford Windstar and Penguinville, RoR 0.4.5.1, everything worked fine in windowed mode, fullscreen gave me bugs though.
![screenshot_409](https://cloud.githubusercontent.com/assets/12358849/11281544/554c71c6-8efb-11e5-9dec-7bc917d63d41.jpg)
![screenshot_410](https://cloud.githubusercontent.com/assets/12358849/11281547/5553fdd8-8efb-11e5-8c43-7fcc78c4ef6f.jpg)
![screenshot_411](https://cloud.githubusercontent.com/assets/12358849/11281546/55532a70-8efb-11e5-9bde-86313440b7b8.jpg)
![screenshot_412](https://cloud.githubusercontent.com/assets/12358849/11281545/5551e19c-8efb-11e5-9b9f-db18aa0d3858.jpg)

On a side note, AltGr+Enter to switch windowed mode/full screen will crash the game.

**Comment by only-a-ptr** [comment]
@DirtGamer301 Download link, please! With all the mods of mods around, I'm never sure I'm using the right thing.

Anyway, thanks for the detailed scenario, will test tonight.

**Comment by DirtGamer301** [comment]
@only-a-ptr 
That's the vehicle shown right above (Ford Windstar):
http://www.rigsofrods.com/threads/106589-2003-Ford-Windstar-LX
It'd be a shame if you'd have always missed this vehicle, it's really nice ;)

But as I said, I don't think it's vehicle specific.

**Comment by Michael10055** [comment]
#746
