### ISSUE TITLE
Crash with D3D9 Alt+Enter window mode switch

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#454]
Edited by Hiradur: removed second bug descriptions since it already has a ticket: #412

-Alt Gr+Enter won't let you switch between windowed mode and fullscreen, it only let's the game crash and shoots an Error 3 message. It seems to be a problem with DirectX.

**Comment by Hiradur** [comment]
Please create only one ticket per bug. You already reported the "-" search bug here: https://github.com/RigsOfRods/rigs-of-rods/issues/412

**Comment by AnotherFoxGuy** [comment]
Duplicate of #780
