### ISSUE TITLE
Mod cache: Handling errors/warnings, invoking regen

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#458]
Currently, errrors during cache regen are handled in variety of ways:
- Reporting to RoR.log - decent solution, but not ideal - from newbie user perspective, mods just "don't appear".
- Showing error message and shutting down RoR - see https://github.com/RigsOfRods/rigs-of-rods/issues/457
- Crashing RoR - the cache regen process may trigger actions which should only happen on map start.

Ideal solution: Implement a "mod cache report" feature, much like the "Spawner report" feature. Draft: when any change to cache content is made, a notification box will appear somewhere in main menu screen, perhaps top right corner, informing that cache has been updated and eventually how many errors/warnings were yielded. The box will contain a button opening a report window showing all messages.

UPDATE 02/2018: I just clicked the [Regen cache] button in RoRConfig and got this:
![obrazek](https://user-images.githubusercontent.com/491088/36805783-8e032354-1cbe-11e8-9279-19cbf7e6b05c.png)
This is stupid... FATAL ERROR work finished?
Also, there's no technical reason for having a regen/clear buttons in RoRConfig instead of directly in RoR - the "General" tab of Settings window would be a good place.

**Comment by only-a-ptr** [comment]
To be researched (repost from Discord \#dev chat):
```
DISLOYALPICK - Today at 6:18 AM
@only_a_ptr im not sure if you are aware of this, and im not sure if i am the only one that experiences it or not.

when i use the in-game "regen cache" button, it will normally regen the cache, but if i switch over to another program like chrome or something until it finishes, it will finish regenning as normal, and say "cache has been regenerated successfully" or something like that. i usually just hover over the ror taskbar button for the preview window, but when i see the message, i click over to ror, and when i do it leaves the cache regenerated message on and starts regenerating the cache all over again. would be nice to have this fixed lol.
```

**Comment by tritonas00** [comment]
with no rorconfig, no regen cache button anymore and a nice new mod cache system, is this still valid?

**Comment by only-a-ptr** [comment]
Closing as no longer relevant.
