### ISSUE TITLE
Spawn garage dont work on Linux x86_64

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#462]
Archlinux x86_64.

Entering the garage does nothing, in both Single and Multi player.

Tested on nHelens, penguinville and NeoQueretaro.

**Comment by only-a-ptr** [comment]
@tritonas00 Post download links to all the maps and RoR.log, please.

**Comment by tritonas00** [comment]
nHelens: http://www.rigsofrods.com/repository/download/3742
penguinville: https://www.dropbox.com/sh/qn7dohdihj07zif/AACPcnx8izOBmO70UI7zFVKna/Penguinville_1.zip?dl=0
NeoQueretaro: http://www.rigsofrods.com/attachment.php?attachmentid=442308&d=1384975618

Loaded nHelens and walked through the spawn door

RoR.log: http://pastebin.com/3VzVKYAC

**Comment by AnotherFoxGuy** [comment]
I think it is caused by #174 because garage spawnpoints are using angelscript.
https://github.com/RigsOfRods/rigs-of-rods/blob/master/bin/resources/scripts/base.as

**Comment by tritonas00** [comment]
Well, probably you are right, it doesn't work in 0.38 x64_86 either. But it works in i686.
