### ISSUE TITLE
non-linear steering

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#464]
^Feel free to rename this, and if there's any wrong information in this post, correct me, too, I don't drive yet :p

In a real car, if you're driving 30 km/h and want to drove around a corner you have to move the steering wheel more than if you drive at 100 km/h and want to drive around a similar shaped corner.

In RoR, using a steering wheel atleast, the steering is fully linear, so you have to steer by the same amount for both speeds.
When using a keyboard, the faster you drive the harder it is to steer, you have to press on the key longer which is the exact opposite of the real world.

**Comment by Hiradur** [comment]
somewhat related to #318

**Comment by tritonas00** [comment]
@CuriousMike56 can we consider this fixed now?

https://github.com/RigsOfRods/rigs-of-rods/pull/2530

**Comment by CuriousMike56** [comment]
Yes, this is no longer an issue.
