### ISSUE TITLE
Ties in .4.5 extremely fragile.

### ISSUE THREAD

**Issue by DarthCainRor** [RigsOfRods/rigs-of-rods#465]
The ties used to tie objects down in RoR, appear to be super fragile in .4.5 as compared to .38.

Map: any, but I used simple map for last test.
Vehicles: any trucks, trailers, and loaded vehicles. I tested with this:
     default Dodge Ram http://www.rigsofrods.com/repository/view/1717
     Squishy skidsteer (mine only differs on the wheel mesh and texture) http://www.rigsofrods.com/repository/view/1962
trailer: Interstate 8st  http://www.rigsofrods.com/threads/100457-Interstate-Trailer-Pack 

When loading the bobcat, almost immediately after hitting "O" to tie it down, the rear ties break. Shortly after another breaks, and the last usually breaks after driving around. 

Log:http://pastebin.com/5giiMu3S
Two ties already broke:
![screenshot_227](https://cloud.githubusercontent.com/assets/10333582/11556695/1754d00c-996e-11e5-83ea-810982696dc4.png)
one more broken:
![screenshot_228](https://cloud.githubusercontent.com/assets/10333582/11556698/1c4aec5e-996e-11e5-82fc-9bd9ef1521d3.png)
after pretty normal driving the last one broke:
![screenshot_229](https://cloud.githubusercontent.com/assets/10333582/11556701/230b4d4a-996e-11e5-8b38-fc243ce4f4b3.png)

Same combination works fine in the old stable versions.

**Comment by only-a-ptr** [comment]
Looks like something I'm mis-calculating in the spawner. The spawn process does a *lot* of complicated post-processing and I don't understand half of it :worried:

**Comment by ulteq** [comment]
> Looks like something I'm mis-calculating in the spawner. 

The ```ParseTies``` function is not the issue. I've just verified that it correctly parses the tie parameters.

References:
https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/rig_file_input_output/RigDef_Parser.cpp#L4109-L4160
http://www.rigsofrods.com/wiki/pages/Truck_Description_File/#Ties

**Comment by ulteq** [comment]
> Looks like something I'm mis-calculating in the spawner.

The ```ProcessRopable``` function is not the issue. I've just verified that it parses the ropable parameters correctly.

References:
https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/physics/input_output/RigSpawner.cpp#L2924-L2934
http://www.rigsofrods.com/wiki/pages/Truck_Description_File/#Ropables
