### ISSUE TITLE
Error creating "mini" picture

### ISSUE THREAD

**Issue by Bob-Z** [RigsOfRods/rigs-of-rods#468]
After clearing cache, I launch RoR and I see the following traces

```C++
Adding archive /home/bobz/.rigsofrods/packs/Boats/HouseBoat.zip (hash: B6C5B59014316784A3D16F59E62433E864A5E87B) (No Compression)
Loading /home/bobz/.rigsofrods/packs/Boats/HouseBoat.zip
Creating resource group General-21
Added resource location '/home/bobz/.rigsofrods/packs/Boats/HouseBoat.zip' of type 'Zip' to resource group 'General-21'
Initialising resource group General-21
Parsing scripts for resource group General-21
Parsing script 4161UID-houseboat.material
Finished parsing scripts for resource group General-21
Creating resources for group General-21
All done
Preparing to add 4161UID-houseboat.boat
 -4161UID-houseboat.boat ...
error deleting file '4161UID-houseboat-mini.dds'
Unloading /home/bobz/.rigsofrods/packs/Boats/HouseBoat.zip
Removed resource location /home/bobz/.rigsofrods/packs/Boats/HouseBoat.zip
Clearing resource group General-21
Finished clearing resource group General-21
Unloading resource group General-21
Finished unloading resource group General-21
Destroying resource group General-21
Unloading resource group General-21
Finished unloading resource group General-21
```

Note the "error deleting file '4161UID-houseboat-mini.dds' " log.
When RoR has finished loading, I can't see any mini pics (either for maps or vehicule). And, indeed, the "cache" directory only contains "mods.cache" file.

After a bit of investigation I found that the following code cause this issue:

file: main/resources/CacheSystem.cpp
method: void CacheSystem::generateFileCache(CacheEntry &entry, Ogre::String directory)

```C++
                 FileInfoListPtr files = ResourceGroupManager::getSingleton().findResourceFileInfo(group, minifn);
                 if (files->empty())
                 {
                         deleteFileCache(const_cast<char*>(dst.c_str()));
                         return;
                 }
```

"files->empty" seems to be always true so the function returns before creating the mini.
Commenting out these lines fixes the issue.

I didn't make a pull request on this because I don't understand why "files->empty" is always true.

Some more info:
Built with Hiradur's latest scripts.
64 bits system

**Comment by Hiradur** [comment]
@only-a-ptr The lovely Ogre resource management system is the problem here, can you comment on this?

**Comment by Bob-Z** [comment]
Maybe related, maybe not:

I have a great number of vehicules with texture issues.
For instance this mod from http://www.rigsofrods.com/threads/120737-All-my-unreleased-unfinished-mods

![screenshot_35](https://cloud.githubusercontent.com/assets/5794246/11756537/dec76882-a05a-11e5-8624-b0bf94aa25a9.png)

Logs:

...
WARNING: impreza_97_body_22b.mesh is an older format ([MeshSerializer_v1.30]); you should upgrade it as soon as possible using the OgreMeshUpgrade tool.
**Error loading texture impreza_body_blue.psd. Texture layer will be blank. Loading the texture failed with the following exception: OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource impreza_body_blue.psd in resource group ManagedMats or any other group. in ResourceGroupManager::openResource at /home/bobz/rigs-of-rods/source/ogre/OgreMain/src/OgreResourceGroupManager.cpp (line 756)**
**Texture: impreza_glass.png: Loading 1 faces(PF_A8R8G8B8,185x185x1) with 5 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,185x185x1.**
FLEXBODY Vertices in mesh impreza_97_body_22b.mesh: 20650
FLEXBODY show mesh
FLEXBODY ready
...

Or this one from the same source:

![screenshot_38](https://cloud.githubusercontent.com/assets/5794246/11756596/4b05f6b2-a05b-11e5-9e33-18209bfc8ac8.png)

Logs:

...
WARNING: lancaster_wheel_tail.mesh is an older format ([MeshSerializer_v1.30]); you should upgrade it as soon as possible using the OgreMeshUpgrade tool.
**Error loading texture camo-spec.jpg. Texture layer will be blank. Loading the texture failed with the following exception: OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource camo-spec.jpg in resource group ManagedMats or any other group. in ResourceGroupManager::openResource at /home/bobz/rigs-of-rods/source/ogre/OgreMain/src/OgreResourceGroupManager.cpp (line 756)**
**Texture: lanc_belly.png: Loading 1 faces(PF_A8R8G8B8,30x28x1) with 4 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,30x28x1.**
**Texture: lanc_wheel.jpg: Loading 1 faces(PF_R8G8B8,14x16x1) with 4 hardware generated mipmaps from Image. Internal format is PF_X8R8G8B8,14x16x1.**
**Texture: lanc_gen-spec.jpg: Loading 1 faces(PF_R8G8B8,14x16x1) with 4 hardware generated mipmaps from Image. Internal format is PF_X8R8G8B8,14x16x1.**
Mesh: Loading lancaster_wheel_main.mesh.
WARNING: lancaster_wheel_main.mesh is an older format ([MeshSerializer_v1.30]); you should upgrade it as soon as possible using the OgreMeshUpgrade tool.
...



Finally, on some mods I have this type of errors:

![screenshot_39](https://cloud.githubusercontent.com/assets/5794246/11756895/581667cc-a05d-11e5-84ae-f26ea31a65c6.png)

...
Mesh: Loading beam.mesh.
Texture: RustySteel.dds: Loading 1 faces(PF_DXT1,256x256x1) with 8 custom mipmaps from Image. Internal format is PF_DXT1,256x256x1.
Texture: invis.dds: Loading 1 faces(PF_A8R8G8B8,8x8x1) with 3 custom mipmaps from Image. Internal format is PF_A8R8G8B8,8x8x1.
Mesh: Loading wheelF.mesh.
WARNING: wheelF.mesh is an older format ([MeshSerializer_v1.41]); you should upgrade it as soon as possible using the OgreMeshUpgrade tool.
Texture: nodamage2.png: Loading 1 faces(PF_A8R8G8B8,2048x2048x1) with 5 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,2048x2048x1.
**Error loading texture wheel.dds. Texture layer will be blank. Loading the texture failed with the following exception: OGRE EXCEPTION(2:InvalidParametersException): DDS header size mismatch! in DDSCodec::decode at /home/bobz/rigs-of-rods/source/ogre/OgreMain/src/OgreDDSCodec.cpp (line 651)**
Texture: wheel_s.dds: Loading 1 faces(PF_A8R8G8B8,512x512x1) with 9 custom mipmaps from Image. Internal format is PF_A8R8G8B8,512x512x1.
Mesh: Loading wheelR.mesh.
WARNING: wheelR.mesh is an older format ([MeshSerializer_v1.41]); you should upgrade it as soon as possible using the OgreMeshUpgrade tool.
Mesh: Loading hub.mesh.
WARNING: hub.mesh is an older format ([MeshSerializer_v1.41]); you should upgrade it as soon as possible using the OgreMeshUpgrade tool.
Mesh: Loading body.mesh.
WARNING: body.mesh is an older format ([MeshSerializer_v1.41]); you should upgrade it as soon as possible using the OgreMeshUpgrade tool.
Texture: nodamage.png: Loading 1 faces(PF_A8R8G8B8,1024x1024x1) with 5 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,1024x1024x1.
Texture: s2.png: Loading 1 faces(PF_A8R8G8B8,256x256x1) with 5 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,256x256x1.
**Error loading texture color_s.dds. Texture layer will be blank. Loading the texture failed with the following exception: OGRE EXCEPTION(2:InvalidParametersException): DDS header size mismatch! in DDSCodec::decode at /home/bobz/rigs-of-rods/source/ogre/OgreMain/src/OgreDDSCodec.cpp (line 651)**
Texture: color.png: Loading 1 faces(PF_A8R8G8B8,1024x1024x1) with 5 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,1024x1024x1.
Texture: damage2.png: Loading 1 faces(PF_A8R8G8B8,1024x1024x1) with 5 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,1024x1024x1.
Texture: s.png: Loading 1 faces(PF_A8R8G8B8,256x256x1) with 5 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,256x256x1.
Texture: grille1.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) with 5 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,64x64x1.
**Error loading texture under.dds. Texture layer will be blank. Loading the texture failed with the following exception: OGRE EXCEPTION(2:InvalidParametersException): DDS header size mismatch! in DDSCodec::decode at /home/bobz/rigs-of-rods/source/ogre/OgreMain/src/OgreDDSCodec.cpp (line 651)**
FLEXBODY Vertices in mesh body.mesh: 21948
FLEXBODY show mesh
FLEXBODY ready
Mesh: Loading windows.mesh.
WARNING: windows.mesh is an older format ([MeshSerializer_v1.41]); you should upgrade it as soon as possible using the OgreMeshUpgrade tool.
**Error loading texture color_s.dds. Texture layer will be blank. Loading the texture failed with the following exception: OGRE EXCEPTION(2:InvalidParametersException): DDS header size mismatch! in DDSCodec::decode at /home/bobz/rigs-of-rods/source/ogre/OgreMain/src/OgreDDSCodec.cpp (line 651)**
Texture: glass2.png: Loading 1 faces(PF_A8R8G8B8,16x16x1) with 4 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,16x16x1.
Texture: glass_d.png: Loading 1 faces(PF_A8R8G8B8,512x512x1) with 5 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,512x512x1.
Texture: glass.png: Loading 1 faces(PF_A8R8G8B8,32x32x1) with 5 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,32x32x1.
FLEXBODY Vertices in mesh windows.mesh: 972
FLEXBODY show mesh
FLEXBODY ready
Mesh: Loading trunk.mesh.
WARNING: trunk.mesh is an older format ([MeshSerializer_v1.41]); you should upgrade it as soon as possible using the OgreMeshUpgrade tool.
Texture: lights.png: Loading 1 faces(PF_A8R8G8B8,512x512x1) with 5 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,512x512x1.
Texture: damagelights.png: Loading 1 faces(PF_A8R8G8B8,512x512x1) with 5 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,512x512x1.
**Error loading texture color_s.dds. Texture layer will be blank. Loading the texture failed with the following exception: OGRE EXCEPTION(2:InvalidParametersException): DDS header size mismatch! in DDSCodec::decode at /home/bobz/rigs-of-rods/source/ogre/OgreMain/src/OgreDDSCodec.cpp (line 651)**
...


I forgot to say that I am using Ubuntu 15.10.

**Comment by Hiradur** [comment]
I don't think it's related. Without verifying it I guess the FileNotFound error is due to letter case issues (Windows is letter case insensitive while Linux isn't).

```
OGRE EXCEPTION(2:InvalidParametersException): DDS header size mismatch!
```
dds is a container format and unfortunately not all DXT codecs are supported on Linux. The author may have used a codec which isn't supported on Linux.

**Comment by Bob-Z** [comment]
Thank you Hiradur.

Indeed it seems unrelated with first issue reported:
 - PNG and PSD files were misspelled in truck file
 - DDS files issue is solved by converting them to no-compression DDS (with GIMP using gimp-dds package). I don't know which DXT codec is used for original files.

**Comment by Speciesx** [comment]
@Hiradur 
With Ogre 1.9 i experience the same issues now on Windows. #521

**Comment by Hiradur** [comment]
Thanks, perhaps the resource system of Ogre works a bit differently now. Since @tritonas00 built with Ogre 1.8 on Linux can he confirm that it works with Ogre 1.8?

**Comment by tritonas00** [comment]
yes, previews work in 1.8

they didn't show p in 1.9
