### ISSUE TITLE
MyGUI.log is created in cwd (Linux) or installdir (Windows)

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#471]
cd to a directory and run RoR.

The game creates that log in there, not in .rigsofrods/logs (i suppose that whould be the correct location)

**Comment by only-a-ptr** [comment]
This actually happens on windows, too, I noticed it when I test-ran the RC builds.
BTW, pwd = PrintWorkingDirectory, name of linux command. Current working directory is abbreviated CWD.

**Comment by AnotherFoxGuy** [comment]
It appears that you have to declare the log file in the [platform header](https://github.com/MyGUI/mygui/blob/master/Platforms/Ogre/OgrePlatform/include/MyGUI_OgreDiagnostic.h#L13).

> [void initialise(const std::string& _core, const std::string& _logFileName); is deprecated, use : void Gui::initialise(const std::string& _core) and set log filename in Platform](https://github.com/MyGUI/mygui/blob/f154c06563c64c3ac47d1b8d11b462c35bd26f04/MyGUIEngine/include/MyGUI_Gui.h#L42)
