### ISSUE TITLE
Screenshots saving is slow

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#473]
Description: The longer it took from the last time I've taken a screenshot and the more screenshots are saved in Own Documents/RoR the longer RoR needs to save a screeshot.

Reproducion (kinda hard to reproduce):
-Take a screenshot in RoR, let's say it took 1 second to save, you alredy had 1500 screenshots saved
-Wait 2 days without taking a screenshot (for example)
-Take a screenshot again, it took 60 seconds to save now
-Take another screenshot, it takes 1 second
-Exit RoR
-Delete your screenshots (or move them to somewhere else)
-Wait 2 days without taking a screenshot
-Take a screenshot, it'll take 30 second.

The numbers aren't real, I just needed them to explain that it'll take longer the longer you didn't save a screenshot and the more pics you have, maybe it can be better imagined with this:
There's a road which is being worked on by 1 meter a day -> 1 meter road will be finished every day. There's 1 meter added for every screenshot taken already. There's a man who has to walk the whole road when a new screenshot is taken. The more screenshots you have and the longer you wait, the more he has to walk.

I hope this explination is somewhat understandable :p
I'll try to give as much information as possible if needed, but as it's nothing you try to do, just something that happens I don't really know much either.

**Comment by only-a-ptr** [comment]
@DirtGamer301 Thanks for reporting.
Makes sense, screenshots are named "screenshot#" where # is a number starting from 1.
RoR doesn't save the number anywhere, so it must determine next one by scanning existing screenshots. According to your observation, this is likely done upon first screenshot in a RoR session.

Possible solutions:
 * Find the next screenshot number on startup.
 * Change screenshot naming scheme to "RoR Screenshot 2015-12-10 10:54:22 ###.jpg" Where ### is a number starting 001 and it's only increased if somebody makes multiple screenshots in one second (i.e. mashes the screenshot key like crazy)

**Comment by TheLonetrucker** [comment]
Could be due to the size of the screenshot I tested If you enable jpg It loads faster But Png is slower Might be just due to the Writing of the screenshot
