### ISSUE TITLE
Forum in Archive mode. 

### ISSUE THREAD

**Issue by Dogy144** [RigsOfRods/rigs-of-rods#474]
This isn't an issue with the game itself, but curiosity of the affect this will take on the development of it. Will this affect development at all? I was really looking forward to the new stuff you guys had planned.

**Comment by Hiradur** [comment]
It's surprising to us as it is to you. At least I didn't see this coming. In theory development of the software is not harmed but it throws up questions about the future of the project.

**Comment by mikadou** [comment]
I have to admit I never really came to grips with the inner workings of the ROR community. The behavior of certain members, the complaints about mesh theft, the infraction system, posts every other week that the project/forum is finally dead. This always alienated me. Actually I didn't even really understand the outrage concerning skybon. Sure, there were issues, that needed to be solved. I just wondered about how hysteric some reactions were.

So I read between the lines, that Jeepster (moderator) and TDev (maintainer of infrastructure) together made the decision that most parts of the forum should be made read-only. In my opinion this action should have been better communicated in advance. I'm not a particular friend of the moderation style of Jeepster and his attitude.

However, I agree that reducing the forum to a small active part is a good move. This brings everybody closer together and shows that ROR definitely isn't dying. Focus on the core community which has shown to be able to deliver outstanding content for the simulation. Just think of other opensource projects with much fewer active members which have also been keeping going on for years now.

Regarding development, I don't really see this affected. To me it actually seems as if development is gaining momentum. Unfortunately I'm quite busy right now, but I'm also still planning on reworking the input system. One thing that might be useful though, would be to ask for unlocking the development subforum again. Github is great for issues, but IMO a forum or mailinglist is better for discussing general ideas, coordination of efforts.

**Comment by DarthCainRor** [comment]
The biggest problem, and kind of a slap in the facd is that the sites owner and the one ultimately responsible for these changes hasn't even commented on his decision ultimately frustrating many people who've contributed for years.

**Comment by AnotherFoxGuy** [comment]
Can be closed since we have a new forum
