### ISSUE TITLE
OGRE EXCEPTION(7:InternalErrorException)

### ISSUE THREAD

**Issue by disloyalpick** [RigsOfRods/rigs-of-rods#476]
This is the first exception in my RoR.log. All I am trying to do is regen my cache and keep getting the Bad UTF-8 Continuation type.

If you need more info please dont hesitate to ask. I'll keep trying to figure something out

OGRE EXCEPTION(7:InternalErrorException): Could not load dynamic library .\RenderSystem_Direct3D10.  System Error: The specified module could not be found.

 in DynLib::load at C:\data\codehg\dependencies\src\Ogre\ogre_src_v1-8-1\OgreMain\src\OgreDynLib.cpp (line 93)
18:42:55: failed to load plugin: .\RenderSystem_Direct3D10: OGRE EXCEPTION(7:InternalErrorException): Could not load dynamic library .\RenderSystem_Direct3D10.  System Error: The specified module could not be found.

 in DynLib::load at C:\data\codehg\dependencies\src\Ogre\ogre_src_v1-8-1\OgreMain\src\OgreDynLib.cpp (line 93)

**Comment by Hiradur** [comment]
The D3D10 renderer is broken, you should use OpenGL or D3D9.

**Comment by only-a-ptr** [comment]
@Speciesx This had allways been happening and it's harmless. For some reason, RoR tries to load DX10 render system even if you're not using it. Happens on my desktop all the time.

Check your RoR.conf for entry "plugins.cfg", which contains a file path. Then check Plugins.cfg itself. You should see:
# Define plugins
Plugin=RenderSystem_Direct3D9
Plugin=RenderSystem_Direct3D10
Plugin=RenderSystem_GL

The second line is the problem.

**Comment by disloyalpick** [comment]
Oh, ok. Thanks for your reply.

**Comment by Hiradur** [comment]
Reopening because the entry should be removed for the next release.

**Comment by caseybug12** [comment]
so how do you remove that specific line?

**Comment by Hiradur** [comment]
> so how do you remove that specific line?

On Linux you could do it like this: 
```sh
 sed -i 's/Plugin=RenderSystem_Direct3D10//' plugins.cfg 
``` 

or just use your favorite text editor to open plugins.cfg, mark the corresponding line and hit backspace.
