### ISSUE TITLE
skeleton view creates "ghost" hydros 

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#477]
Spawn a airplane with hydros, enable and disable skeleton view

![ror_2015_12_11_20_15_55_195](https://cloud.githubusercontent.com/assets/1196375/11753232/47e94f22-a044-11e5-93df-ab5ec227b577.jpg)
![ror_2015_12_11_20_16_23_045](https://cloud.githubusercontent.com/assets/1196375/11753233/495330ee-a044-11e5-8655-23855f393a76.jpg)

Tested with spitfire_Vb
http://www.rigsofrods.com/threads/120737-All-my-unreleased-unfinished-mods

**Comment by only-a-ptr** [comment]
Spawner glitch. I'll deal with it.

**Comment by DirtGamer301** [comment]
I think it also happens with the Seat Ibiza (http://www.rigsofrods.com/threads/80407-1995-Seat-Ibiza-1-4-DO-NOT-POST-PICTURES-OF-YOUR-UGLY-MODS) on the trunk sometimes after respawning. Just wanting to put this here in case it helps to have more examples ;)

**Comment by only-a-ptr** [comment]
@DirtGamer301 Thanks, the more test cases, the better.
