### ISSUE TITLE
new physic limits?

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#478]
With ror 4.5.1 i could accelerate up to 600 km/h in fifth gear with modded Gavril MZ2R. Now with the latest changes my modded MZ2R explodes in fourth gear at ~270 km/h and in fifth gear at the same speed ror crashes.

My modded Gavril MZ2R
![ror_2015_12_11_20_56_24_331](https://cloud.githubusercontent.com/assets/1196375/11754306/b32dd02c-a04a-11e5-86f3-c4ad5877979c.jpg)

https://youtu.be/bkOfj2JxJ6k

**Comment by only-a-ptr** [comment]
@Speciesx We'll deliver a test build with some extra physics settings to find out what exactly causes this issue.

**Comment by only-a-ptr** [comment]
@Speciesx I guess this one is out of date, considering all the recent dev activity.
Please re-test and update/close.
