### ISSUE TITLE
Manually Added Fileformatversion "450" Crashes With "node not found" Errors.

### ISSUE THREAD

**Issue by graysonk95** [RigsOfRods/rigs-of-rods#480]
I recently noticed this entry on the Wiki and wanted to incorporate the new version flag since I am designing my vehicles for 0.4.5.1+.
http://www.rigsofrods.com/wiki/pages/Truck_Description_File#Fileformatversion

It specifies that version flag "450" is only for the Rig Editor. Manually adding "450" crashes 0.4.5.1 with numerous seemingly random "node not found" errors from the cinecam and meshwheels sections.

16:06:09:  == Spawning vehicle: Thomas Saf-T-Liner HDX
16:06:09:  == RigSpawner: ERROR (Keyword cinecam) Failed to resolve node-ref (node not found):Node::Ref(id:75, src line:917, import flags:[], regular flags:[ VALID NAMED])
16:06:09:  == RigSpawner: ERROR (Keyword cinecam) Failed to retrieve node from reference: Node::Ref(id:75, src line:917, import flags:[], regular flags:[ VALID NAMED])
16:06:09:  == RigSpawner: ERROR (Keyword cinecam) Failed to resolve node-ref (node not found):Node::Ref(id:75, src line:918, import flags:[], regular flags:[ VALID NAMED])
16:06:09:  == RigSpawner: ERROR (Keyword cinecam) Failed to retrieve node from reference: Node::Ref(id:75, src line:918, import flags:[], regular flags:[ VALID NAMED])
16:06:09:  == RigSpawner: ERROR (Keyword cinecam) Failed to resolve node-ref (node not found):Node::Ref(id:75, src line:919, import flags:[], regular flags:[ VALID NAMED])
16:06:09:  == RigSpawner: ERROR (Keyword cinecam) Failed to retrieve node from reference: Node::Ref(id:75, src line:919, import flags:[], regular flags:[ VALID NAMED])
16:06:09:  == RigSpawner: ERROR (Keyword meshwheels) Failed to resolve node-ref (node not found):Node::Ref(id:66, src line:923, import flags:[], regular flags:[ VALID NAMED])
16:06:09:  == RigSpawner: ERROR (Keyword meshwheels) Failed to resolve node-ref (node not found):Node::Ref(id:67, src line:923, import flags:[], regular flags:[ VALID NAMED])

I changed the file format version of Stoat's Mudd-Ox, and got a similar crash and errors.

16:09:05:  == Spawning vehicle: Mudd-Ox 8x8 ATV
16:09:05:  == RigSpawner: ERROR (Keyword cinecam) Failed to resolve node-ref (node not found):Node::Ref(id:0, src line:792, import flags:[], regular flags:[ VALID NAMED])
16:09:05:  == RigSpawner: ERROR (Keyword cinecam) Failed to retrieve node from reference: Node::Ref(id:0, src line:792, import flags:[], regular flags:[ VALID NAMED])
16:09:05:  == RigSpawner: ERROR (Keyword cinecam) Failed to resolve node-ref (node not found):Node::Ref(id:167, src line:793, import flags:[], regular flags:[ VALID NAMED])
16:09:05:  == RigSpawner: ERROR (Keyword cinecam) Failed to retrieve node from reference: Node::Ref(id:167, src line:793, import flags:[], regular flags:[ VALID NAMED])
16:09:05:  == RigSpawner: ERROR (Keyword cinecam) Failed to resolve node-ref (node not found):Node::Ref(id:167, src line:794, import flags:[], regular flags:[ VALID NAMED])
16:09:05:  == RigSpawner: ERROR (Keyword cinecam) Failed to retrieve node from reference: Node::Ref(id:167, src line:794, import flags:[], regular flags:[ VALID NAMED])
16:09:05:  == RigSpawner: ERROR (Keyword wheels) Failed to resolve node-ref (node not found):Node::Ref(id:189, src line:804, import flags:[], regular flags:[ VALID NAMED])
16:09:05:  == RigSpawner: ERROR (Keyword wheels) Failed to resolve node-ref (node not found):Node::Ref(id:190, src line:804, import flags:[], regular flags:[ VALID NAMED])
16:09:05:  == RigSpawner: ERROR (Keyword wheels) Error creating 'wheel': Some axis nodes were not found (Node1: Node::Ref(id:189, src line:804, import flags:[], regular flags:[ VALID NAMED]) => 1 (Node2: Node::Ref(id:190, src line:804, import flags:[], regular flags:[ VALID NAMED]) => 1
16:09:05:  == RigSpawner: ERROR (Keyword wheels) Failed to resolve node-ref (node not found):Node::Ref(id:190, src line:805, import flags:[], regular flags:[ VALID NAMED])
16:09:05:  == RigSpawner: ERROR (Keyword wheels) Failed to resolve node-ref (node not found):Node::Ref(id:189, src line:805, import flags:[], regular flags:[ VALID NAMED])
16:09:05:  == RigSpawner: ERROR (Keyword wheels) Error creating 'wheel': Some axis nodes were not found (Node1: Node::Ref(id:190, src line:805, import flags:[], regular flags:[ VALID NAMED]) => 1 (Node2: Node::Ref(id:189, src line:805, import flags:[], regular flags:[ VALID NAMED]) => 1
16:09:05:  == RigSpawner: ERROR (Keyword meshwheels) Failed to resolve node-ref (node not found):Node::Ref(id:22, src line:161, import flags:[], regular flags:[ VALID NAMED])
16:09:05:  == RigSpawner: ERROR (Keyword meshwheels) Failed to resolve node-ref (node not found):Node::Ref(id:21, src line:161, import flags:[], regular flags:[ VALID NAMED])

"450" will not crash 0.4.0.7, but always crashes 0.4.5.1.

The Wiki entry specifies 450 is only for the Rig Editor, so will there be any way to denote a file designed 'manually' for 0.4.5+?

**Comment by only-a-ptr** [comment]
Uhh... you got me to freak out for a second.

fileformatversion 450 is more than just a label. It disables legacy-truck importer and expects perfectly valid truckfile, i.e wheels defined after all beams/nodes, no indexing of named nodes by number, no indexing nodes before they're defined... Old truckfiles (fileformatversion 1/2/3) are full of these flaws because old spawner stupidly executed whatever the modder put in the truckfile. RoR 0.4.5 verifies validity of the truckfiles and so the old stuff must go through an importer which fixes it.

This specific vehicle defines cinecam and wheels before defining the nodes they link to.
