### ISSUE TITLE
Ability to set hydro contraction/extention speed

### ISSUE THREAD

**Issue by disloyalpick** [RigsOfRods/rigs-of-rods#482]
Maybe that would be useful to set steering sensitivity for a gamepad like xbox 360. Maybe if Max would do it, it could possibly be a setting in the menu.

**Comment by Hiradur** [comment]
somewhat related issue: #318

**Comment by ulteq** [comment]
See: https://github.com/RigsOfRods/rigs-of-rods/pull/2070
