### ISSUE TITLE
Compiling fails with the last changes

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#484]
I get this Error.
VS 2010 SP1, Windows 10 x64
![1](https://cloud.githubusercontent.com/assets/1196375/11872573/3da235e2-a4d6-11e5-832e-ad0d285916f0.PNG)

**Comment by only-a-ptr** [comment]
Already encountered this. Fix will be pushed in matter of days.

Workaround: there's a log2 function on the top of the PointColDetector.cpp file. Use it.

**Comment by Speciesx** [comment]
Fixed in the master branch.
