### ISSUE TITLE
Windows: There is no uninstaller

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#485]
Currently, RoR 0.4.5.1 cannot be uninstalled from Windows. 

It doesn't appear in "Control panel / add or remove software" and running the installer again doesn't provide the "reinstall/repair/remove?" menu known from MSI installers.

**Comment by wilkgr76** [comment]
Also, in the EXE installer versions, there is no "uninstall.exe" in the installer directory. In the RoR.nsi file used to create the NSIS installer is also no "create uninstaller" section, which has to be explicitly mentioned. As for "add or remove software", I believe that is stored in the depths of the registry.

> HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall

**Comment by AnotherFoxGuy** [comment]
This is fixed in the new installer

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy I know, but it's not in upstream yet and AFAIK there's not even a PR for it yet.
