### ISSUE TITLE
Add_Animation Source "shifterlin" is Broken

### ISSUE THREAD

**Issue by graysonk95** [RigsOfRods/rigs-of-rods#488]
Unlike the syntax-related issue with some add_animations (https://github.com/RigsOfRods/rigs-of-rods/issues/132), source "shifterlin" is completely broken with no errors given in RoR.log.

Last working version was 0.4.0.7.

**Comment by only-a-ptr** [comment]
@graysonk95
 * Can you link me to some vehicles which use it?
 * What is "shifterlin" supposed to do, anyway? The name isn't exactly self-explanatory.

**Comment by graysonk95** [comment]
I've used it in the past (and plan to continue to use it) for my Allison push-button shifter displays: http://www.rigsofrods.com/repository/view/5711
Here is how it is supposed to operate:
https://youtu.be/GdfDF0WLIUE
In 0.4.5.1, it just stays stuck on "D6". No errors in ror.log.

My guess is "shifterlin" is short for "linear shifter", because it animates gears in a linear fashion rather than in an H-pattern. Shifterlin is useful for making a display of the current gear.
You are right. Many animations are not well documented (or could use examples).
It took me until 2 weeks ago to notice there was an ignition "TRUCK_TOGGLE_CONTACT" animation event because it was in an example, rater than in the full list of events.

**Comment by only-a-ptr** [comment]
@graysonk95 Thanks for the details.
