### ISSUE TITLE
Save RoR screenshot in a folder

### ISSUE THREAD

**Issue by WillyB1337** [RigsOfRods/rigs-of-rods#489]
I never found an option to set where every screenshot from RoR are saved.
Right now, it's only in the compiled files.

I would really like that all the shots get into the folder "screenshot".

**Comment by Hiradur** [comment]
On Linux they are saved to ```~/.rigsofrods``` but ```~/.rigsofrods/screenshots``` would be better, I agree.

**Comment by only-a-ptr** [comment]
This fits nicely into my new system path management. I got this.

**Comment by ulteq** [comment]
-> https://github.com/RigsOfRods/rigs-of-rods/commit/824624849de70b98bf9e7cc997516881ef7399d5
