### ISSUE TITLE
[Angelscript] setCustomLightVisible crashes the game

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#5]
if you use [`void setCustomLightVisible(5, true);`](http://ror.ezzg.be/docs/angelscript/class_beam_class.html#a0dd40b2f76298ab32b050617dd58bb1b) the game will crash.

[More info](http://www.rigsofrods.com/threads/111967-Bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1346528#post1346528)

**Comment by Max98** [comment]
https://github.com/RigsOfRods/rigs-of-rods/commit/61ba51a9fa8c0ad75e7be2c28f0c89f460b84511
This should do the trick. :)
