### ISSUE TITLE
Parser too strict (and maybe buggy)

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#502]
http://www.rigsofrods.com/repository/view/5282
http://www.rigsofrods.com/repository/view/4886

![ror_2015_12_23_11_31_32_310](https://cloud.githubusercontent.com/assets/1196375/11974958/484864de-a969-11e5-9037-3ccaa6d32e42.jpg)
![ror_2015_12_23_11_32_00_166](https://cloud.githubusercontent.com/assets/1196375/11974959/484992b4-a969-11e5-932f-295e24ed5166.jpg)
![ror_2015_12_23_11_33_21_689](https://cloud.githubusercontent.com/assets/1196375/11974960/484d48aa-a969-11e5-8e59-c5fdbc52b562.jpg)
[rorlog.txt](https://github.com/RigsOfRods/rigs-of-rods/files/70622/rorlog.txt)

**Comment by only-a-ptr** [comment]
Many many syntax flaws in the truckfile....
And super-truper strict parser...

```23:17:51:  == Parsing vehicle file: volvo-EC140C.truck
#FF3300 ERROR #FFFFFF (Section contacters)
	Line (1966): 205,
	Message: Invalid line, ignoring...``` 
The trailing comma is invalid.

```23:18:11:  == Parsing vehicle file: volvofmx-6x6withcrane.truck
#FF3300 ERROR #FFFFFF (Section torquecurve)
	Line (46):  NOTGGLE
	Message: Invalid mode keyword, ignoring whole line...``` 
NOT!o!GGLE... I'm not sure what old parser would do here...

```#FF3300 ERROR #FFFFFF (Section rotators_2)
	Line (1867): 222,217,223,225,226,224,218,220,221,219,0.1,9,10,1000000,0.1   turning-grapple
	Message: Invalid line, ignoring...``` 
Hmm, probably a comma/space delimiter issue...

```#FFFF00 WARNING #FFFFFF (Section ties)
	Line (1967): 222,3,1,1,1,n,0,1
	Message: Ignoring invalid option: ,``` 
Now this looks like a bug...

```#FF3300 ERROR #FFFFFF (Section hooks)
	Line (1983): selflock
	Message: Invalid option of 'hooks', ignoring...``` 
Ignoring what?

```#FF3300 ERROR #FFFFFF (Section flares2)
	Line (2010): 5,4,1,-0.61,0.3,0.0,b -1,0,-1, default
	Message: Invalid line, ignoring...``` 
Dumb super-strict parser, this is already reported elsewhere.

```#FF3300 ERROR #FFFFFF (Section props)
	Line (2043): 137,135,141, ,0,0,0 ,90,0,0 ,vlvfmx48cabinS.mesh
	Message: Invalid line, ignoring...``` 
OK, this is an actual truckfile error: {141, ,0}

```#FF3300 ERROR #FFFFFF (Section flexbodies)
	Line (2199): forset256,255,254,253
	Message: Invalid line, ignoring...``` 
Truckfile error again, no space between forset and the number. But I guess the old parser would just ignore the '256' and happily process the rest. Needs investigation.

**Comment by Speciesx** [comment]
@only-a-ptr 
http://www.rigsofrods.com/threads/112719-volvo-EC140C
This is the correct excavator.

WARNING  (Section nodes)
	Line (465): 334, 3.031496, 0.424640, 2.897959, c  l 6000
	Message: Failed to parse using safe method, falling back to classic method.

**Comment by only-a-ptr** [comment]
@Speciesx Flawed syntax, it wouldn't work correctly in the old parser either
```
Line (465): 334, 3.031496, 0.424640, 2.897959, c l 6000
```
There's a space (valid separator) between c and l, which means:
 * c is 'options'
 * l is 'load weight override' (not a number -> parsed as 0 for compatibility)
 * 6000 is invalid trailing text, silently ignored for compatibility

**Comment by only-a-ptr** [comment]
Note to self:
 * improve the warning message, it should say "Syntax check failed, falling back to classic lenient parsing."
* add data breakdown for verification. It should say:
** ..snip..
** Options: c_CONTACTLESS (Input text: "c")
** Load weight override: 0 (input text: "l")
** Invalid trailing text: "6000"

**Comment by only-a-ptr** [comment]
Note to self:

Hooks: ```E_CAPTURE("selflock|self-lock|self_lock")```

Old: https://github.com/only-a-ptr/ror-legacy-svn-trunk/blob/master/source/main/physics/input_output/SerializedRig.cpp#L1735
