### ISSUE TITLE
'reset in place' aligns trailer and loads to SE

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#503]
After reset (Backspace key) trailer and loads should keep their previous alignment.

**Comment by ulteq** [comment]
I can't reproduce it. What are the steps to reproduce it?

**Comment by Speciesx** [comment]
https://youtu.be/Gq-2tGMcV5U

**Comment by Speciesx** [comment]
btw. train cars like Boxcar and Flatcar rotating fast when holding Backspace key.
http://www.rigsofrods.com/repository/view/4813
http://www.rigsofrods.com/repository/view/4392

**Comment by Hiradur** [comment]
The weasel boat also rotates with backspace

**Comment by Speciesx** [comment]
It's no really fixed. 
Train cars reset with Backspace key works correct now, but trailer and loads aligns now to NE.
