### ISSUE TITLE
skeleton view not limited to one vehicle

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#504]
Spawn at least two same vehicles and activate on a vehicle the skeleton view, the second vehicle will be wireframed too.

![111](https://cloud.githubusercontent.com/assets/1196375/12003507/06824e82-ab23-11e5-8cc2-7035f4cc983d.jpg)

**Comment by mikadou** [comment]
I just discovered, this already happened in Version 0.38.

**Comment by only-a-ptr** [comment]
I'm fairly sure this was already fixed by Ulteq about a year ago.

Can you re-test please?

**Comment by tritonas00** [comment]
Yes, it's fixed
![2017-09-11-141007_1920x1080_scrot](https://user-images.githubusercontent.com/2660424/30272034-4fe75d18-96fb-11e7-89d5-ee22fbbd0f31.png)
