### ISSUE TITLE
Change Map Videocamera Bug

### ISSUE THREAD

**Issue by graysonk95** [RigsOfRods/rigs-of-rods#506]
While in a vehicle with videocameras, if you change maps via the pause menu then respawn that same vehicle on a new map, the videocameras will be "frozen" on the last image they displayed on the previous map.

**Comment by TheLonetrucker** [comment]
Im thinking it might be a render window issue... The vechile is still loaded From the last terrain when you load the next terrain. I produced this bug with the kme On Neo then simple terrain and Does the same thing as when You spawn two of them on the same terrain Its not a bug its a conflicting material Being loaded twice

**Comment by DirtGamer301** [comment]
Just going to post two related issues:
https://github.com/RigsOfRods/rigs-of-rods/issues/402
https://github.com/RigsOfRods/rigs-of-rods/issues/57

**Comment by only-a-ptr** [comment]
Fixed, see link above.
