### ISSUE TITLE
Water brightness

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#513]
Using "reflection and refraction (speed optimised)" water and changing the time, it doesn't seem to get dark enough.

![screenshot_597](https://cloud.githubusercontent.com/assets/12358849/12065504/f0dd3de8-afd8-11e5-94c8-e1f7e0141d38.jpg)
![screenshot_598](https://cloud.githubusercontent.com/assets/12358849/12065505/f0e0ce9a-afd8-11e5-84a9-15fb8f98100e.jpg)

**Comment by Speciesx** [comment]
https://github.com/RigsOfRods/rigs-of-rods/issues/29

**Comment by Hiradur** [comment]
@DirtGamer301 please post these screens in #29 

Closing as duplicate of #29
