### ISSUE TITLE
Add Settings link to Pause menu

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#52]

**Comment by Max98** [comment]
I didn't put the Settings link to the Pause menu because you have to reload everything for the settings to apply, which mean you need to go back to the main menu.

**Comment by Speciesx** [comment]
But you can still look the controls. 
Changing the sightrange need also a restart?

**Comment by Max98** [comment]
Yes, because in RoR everything is loaded when the terrain loads. It is possible to make it work from pause menu but it will need a lot of work, and it won't happen for 0.4.5.

**Comment by Speciesx** [comment]
Enabling and disabling texture shadow and changing the sightrange works without reload ror.

**Comment by ulteq** [comment]
a) Most of the settings cannot be changed during the simulation
b) The new `Resume game` logic allows you to change any setting without losing state
c) Settings that can be changed, during the simulation, are now available via the top menu
