### ISSUE TITLE
Beams disappearing

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#522]
Sometimes when rotating the camera around a truck, the beams will disappear

![2016-01-04_12-49-00](https://cloud.githubusercontent.com/assets/9480940/12109058/8d6b2870-b37e-11e5-83b1-ca2b25a2c6c3.jpg)
![2016-01-04_12-49-10](https://cloud.githubusercontent.com/assets/9480940/12109059/8d6c05b0-b37e-11e5-965a-640ebea91e89.jpg)

Tested with http://www.rigsofrods.com/repository/view/3765

**Comment by disloyalpick** [comment]
I'll test to confirm.

**Comment by Hiradur** [comment]
Is this the same as #26?

**Comment by only-a-ptr** [comment]
Does this still happen? can somebody provide a test scenario where it occurs?

**Comment by disloyalpick** [comment]
I haven't ever been able to reproduce

**Comment by tritonas00** [comment]
me neither

**Comment by AnotherFoxGuy** [comment]
It seems to have been fixed
