### ISSUE TITLE
Unzipping terrain causes materials not to load

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#523]
If you unzip a terrain the materials will not load

zipped
![2016-01-05_08-20-34](https://cloud.githubusercontent.com/assets/9480940/12109754/63052a5c-b385-11e5-9abe-8c420d4a25b4.jpg)
![2016-01-05_08-29-58](https://cloud.githubusercontent.com/assets/9480940/12109931/3dc4f194-b387-11e5-9fa5-5605ac3fdf9d.jpg)
unzipped
![2016-01-05_08-20-08](https://cloud.githubusercontent.com/assets/9480940/12109753/6304e858-b385-11e5-9e91-ed3f1aa27ed9.png)
![2016-01-05_08-34-34](https://cloud.githubusercontent.com/assets/9480940/12109933/40c2d1cc-b387-11e5-9dc4-a20de0c57340.png)

**Comment by Max98** [comment]
Materials are actually loaded, this is more of a caeluim problem.

**Comment by DirtGamer301** [comment]
If you zoom in, you'll see that the materials are laoded perfectly, but there's some kind of fog laying over the terrain.
http://www.rigsofrods.com/attachment.php?attachmentid=510533&d=1414666648
http://www.rigsofrods.com/attachment.php?attachmentid=510534&d=1414666648
http://www.rigsofrods.com/attachment.php?attachmentid=510535&d=1414666648

**Comment by AnotherFoxGuy** [comment]
Here is an another example
zipped
![2016-01-05_10-37-14](https://cloud.githubusercontent.com/assets/9480940/12111803/6d0c11f6-b398-11e5-9ec2-303f1906b8eb.jpg)
unzipped
![2016-01-05_10-35-54](https://cloud.githubusercontent.com/assets/9480940/12111802/6d093e7c-b398-11e5-988c-92f18d383748.jpg)

**Comment by Speciesx** [comment]
@Max98 
This bug started after Real time shadows was added.

**Comment by only-a-ptr** [comment]
I re-discovered this bug recently. I can confirm the materials are not being loaded.

Steps to reproduce:
1. Pick any working map
2. Extract the map's ZIP into /terrains/whatever_subdirectory
3. Load the map - materials won't load, object will be light-gray. RoR.log indicate that the material files were never parsed (i.e. no Parsing script whatever.material entries)

**Comment by only-a-ptr** [comment]
Removing from v0.4.8 milestone... time is up.

**Comment by AnotherFoxGuy** [comment]
It is back

![screenshot_2019-09-07_22-15-46_1](https://user-images.githubusercontent.com/9480940/64479842-13a33d00-d1bd-11e9-9fb9-39c8141c79d0.png)
