### ISSUE TITLE
Ability to rotate the cameras position

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#525]
When creating a new vehicle, or generally adding a camer to a car, you need three reference nodes.
It's the node in the middle, a node on the left from it and one node behind it.
If any of these nodes doesn't match up correctly the camera will be rotated, for example if the reference node which is supposed to be positionized exactly at the left of the main reference node, isn't exactly left of it the camera will not be straight but point to the left or right, depending on where the node is placed.
This then also means that if you want a camera rotated up/down or to the left/right, the nodes need to be placed in the exact way to fit the right camera position.
Sadly though, in most of the cases, you don't have nodes matching these exact positions, so my request would be something like a camera rotation offset, maybe a section below the cameras section which could look like this:

camerarotation
;rotation x, rotation y, rotation z
20, 0, 0

The code shown above would point the camera up.

This way, cameras could be placed more freely and wouldn't require exact node positions which practically don't usually exist that much anymore.
Also, it allows easier camera editing and better palcment if you want to simulate a GoPro for a video for example.

**Comment by Hiradur** [comment]
Perhaps the camera should use a position and a direction vector instead.

**Comment by ulteq** [comment]
And how do you know which way is up?

**Comment by Hiradur** [comment]
+ an up vector :blush:

**Comment by ulteq** [comment]
> my request would be something like a camera rotation offset

Offset relative to what? Straight north, what happens if you drive east?

> This way, cameras could be placed more freely

I understand what you mean, but I'm afraid there is not easy solution for this problem.

> and wouldn't require exact node positions which practically don't usually exist that much anymore.

I would suggest to use invisible and contactless nodes for that purpose.
