### ISSUE TITLE
Trailer issue 

### ISSUE THREAD

**Issue by TheLonetrucker** [RigsOfRods/rigs-of-rods#528]
as per http://www.rigsofrods.com/threads/120837-4-5-1-trailer-problem?p=1390879#post1390879 There is a way to repair the problem. To enter the trailer via vechile menu. I think importcommands is broken in latest stable build

**Comment by TheLonetrucker** [comment]
try doing it with any trailer and a k3500 by brkillpack One .truck with importcommands and one without importcommands and see if it makes any difference

**Comment by DarthCainRor** [comment]
Uh, the truck needs forwardcommands, not importcommands
