### ISSUE TITLE
Particles created in pause mode

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#531]
When spreeing particles around and pressing esc to get to the pause menu, you'll notice the particles will keep flying around and be created over and over again.
This isn't much of a big deal though.

Here's something else related to the pause mode: https://github.com/RigsOfRods/rigs-of-rods/issues/222
The issue above was "created" to fix another bug, so this one might just be like this.

**Comment by TheLonetrucker** [comment]
it seems to do the same thing when you hit replay mode too... Might not be a bug  Unless it causes performance issues I think It should be okay

**Comment by mikadou** [comment]
Update of particles seems to be decoupled from physics time step. A while ago I messed around with the physics timestep: the entire simulation ran in slowmotion except for dust particles which were still moving fast.
