### ISSUE TITLE
Request Spawner log: display errors red and warnings yellow

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#54]
Something like this.
![ror_2015_02_13_23_54_12_438](https://cloud.githubusercontent.com/assets/1196375/6197028/61c6ccdc-b3df-11e4-881d-f60189d5db77.png)

**Comment by Max98** [comment]
Very easy to do, if @only-a-ptr would leave it to me, I will do it.

**Comment by only-a-ptr** [comment]
@Max98 : I'm leaving it to you. It's a nice, player-friendly feature which I was lazy to do myself.

**Comment by Max98** [comment]
![screenshot_10](https://cloud.githubusercontent.com/assets/4823878/6200871/2ef3bcd6-b48c-11e4-8ec5-ce32b096494f.png)

Like this? :)

**Comment by Max98** [comment]
Done.
