### ISSUE TITLE
manitou 731 loading problems

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#540]
Download http://www.rigsofrods.com/repository/download/2215

Load simple terrain and search for manitou. You can see only three items, loading any of these causes segfault.

> Program received signal SIGSEGV, Segmentation fault.
> 0x00007ffff73831d0 in Ogre::NedPoolingImpl::deallocBytes(void*) () from /opt/ror-next/lib/libOgreMain.so.1.8.1

Now load mitcity http://www.rigsofrods.com/repository/download/4932 and do the same. You can see seven items each one loading fine without crash.

**Comment by ulteq** [comment]
This line seems to be responsible for the crash: https://github.com/RigsOfRods/rigs-of-rods/blob/d1d3d0f3c626c80f49b745ef0636202334acdbff/source/main/utils/MeshObject.cpp#L188

**Comment by ulteq** [comment]
Possibly related with: https://github.com/RigsOfRods/rigs-of-rods/issues/602

**Comment by tritonas00** [comment]
With latest master, you can see all 7 items in simple terrain too. Now it crashes in mitcity, but not in NeoQueretaro

**Comment by only-a-ptr** [comment]
@tritonas00 please re-test with current upstream. The mesh handling changes might have fixed this.

**Comment by tritonas00** [comment]
nope still crashes

do you want a gdb output?

**Comment by only-a-ptr** [comment]
@tritonas00 can you get me a new download link? The one above is dead

**Comment by AnotherFoxGuy** [comment]
@only-a-ptr https://archives.rigsofrods.org/repo/repofiles-2nd-batch/9d02800e5d325a3340cd97b0bf0622ea59bbd60e_Manitou-MRT-Telehandler.zip

**Comment by only-a-ptr** [comment]
I tested the link above. I get just one item in the Loader window: "Manitou-MRT-Telehandler". It seems to spawn just fine:
![obrazek](https://user-images.githubusercontent.com/491088/29251577-6a19386a-8057-11e7-9c95-e81f4e4d0bda.png)

**Comment by tritonas00** [comment]
Telehandler.zip works, the problem is with Manitou_731.zip https://www.dropbox.com/s/285s0mu98uwfnwz/ff93af55fab716f036b74638f337f9945acf784c_Manitou_731.zip?dl=1

**Comment by only-a-ptr** [comment]
debugging shown it's the same error as I just fixed here: https://github.com/RigsOfRods/rigs-of-rods/pull/1365 😆 
![obrazek](https://user-images.githubusercontent.com/491088/29251726-92d164d2-805a-11e7-92c0-2d24767e4ad4.png)

**Comment by tritonas00** [comment]
Still valid for me: https://pastebin.com/RNdTgqcG

maybe an ogre 1.8 issue?

**Comment by only-a-ptr** [comment]
The trace you posted shows memory allocation issue (with OGRe's cusstom 'nedmalloc' allocator) when processing OpenGL texture from some prop. However, since everything worked smoothly for you so far, the custom allocator probably isn't the issue. I think this is something between Manitou731's textures and your graphics driver.

**Comment by tritonas00** [comment]
I don't think its the graphics driver because it crashes also in vbox using just vesa generic driver

**Comment by tritonas00** [comment]
Let me test with ogre 1.9

**Comment by only-a-ptr** [comment]
VBox on what host (your archlinux, I presume) and with acceleration disabled?

In my understanding, VBox with acceleration disable should be incapable of running anything 3D, unless the OS comes with a software OpenGL rasterizer. But I'm not certain.

try removing props from the vehicle and then add them back one by one to find out which one causes the issue. --- and yes, OGRE 1.9 is also a good option.

**Comment by tritonas00** [comment]
> VBox on what host (your archlinux, I presume) and with acceleration disabled?

Yes.

But why it loads fine in certain maps?

**Comment by tritonas00** [comment]
Removed props -> crash gone

I will locate the bad one

**Comment by tritonas00** [comment]
I get the same crash with ogre 1.9

**Comment by only-a-ptr** [comment]
The troublesome texture in Futurotrack was also DDS. I guess the only way forward is to install archlinux in a virtualbox machine and debug from there. But I won't have time for that in any close future.

**Comment by tritonas00** [comment]
i can create an image for you :smile:

**Comment by only-a-ptr** [comment]
@tritonas00 For a Win7-x64 host? I think I'll accept the offer 😄 

However, take your time, I won't be able to work with it until sunday 26 Aug, anyway.

**Comment by only-a-ptr** [comment]
Fixed in https://github.com/RigsOfRods/rigs-of-rods/pull/1365, closing.

@tritonas00 Regarding the crash you're getting: https://github.com/RigsOfRods/rigs-of-rods/pull/1365#issuecomment-322283414
