### ISSUE TITLE
Brightness hop at day/night change

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#544]
At a certain time, there'll be a huge visible hop from one lighting to another in just a few seconds.
![screenshot_714](https://cloud.githubusercontent.com/assets/12358849/12212806/97c40f88-b66e-11e5-9ddc-97529bc6f08d.jpg)
![screenshot_715](https://cloud.githubusercontent.com/assets/12358849/12212805/97c30728-b66e-11e5-9002-4366c813b601.jpg)

**Comment by Hiradur** [comment]
Perhaps it's due to the sun going under the horizon which leads to that drop in brightness because the direct light source is now gone.

**Comment by DirtGamer301** [comment]
I noticed that in the last Night Build this certain change was fixed, but it now appears that daylight might be a bit too stron, also at night.
Here's an imgur album showing the current day/night brightness, beginning with 8 o clock in the morning and ending with 8 o clock in the morning, +1 hour in each picture.You can see how short the night is, how bright it is and how early sun gives daylight again (4 o clock in the morning).

**Comment by Hotrod55** [comment]
The lag is caused by the removal of Boost AFAIK.
