### ISSUE TITLE
Some vehicle broke after spawning

### ISSUE THREAD

**Issue by WillyB1337** [RigsOfRods/rigs-of-rods#575]
Hello guys!

In the new 4.5, somes vehicles doesn't work at all when I spawn them.

One of thoses vehicles is Voulk's Thomas Bus.

What is happening?

**Comment by AntoniD330** [comment]
Well, I think it's related to this bug: https://github.com/RigsOfRods/rigs-of-rods/issues/134.

**Comment by Dogy144** [comment]
That is correct.

**Comment by Hotrod55** [comment]
#469

**Comment by tritonas00** [comment]
This bus works fine here.

**Comment by ulteq** [comment]
I can't reproduce it either.
