### ISSUE TITLE
[RoRBot] missing sidestep animation

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#577]
CHARACTER_SIDESTEP_LEFT        Keyboard             A 
CHARACTER_SIDESTEP_RIGHT       Keyboard             D

**Comment by Hiradur** [comment]
hagdervriese may be able to help out here, he animated RoRBot.

**Comment by Speciesx** [comment]
https://github.com/RigsOfRods/rigs-of-rods/pull/1111
