### ISSUE TITLE
old websites linking to the new abandoned website

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#588]
For example when looking for RoR downloads, the used forum links to Skybons abandoned, new forum while this in most of the cases links to the old forum. I think we should just put the downloads section back to the old forum and this way unlink the new one.

I'm posting this here as I think the website ticker isn't really watched anymore.

**Comment by Hiradur** [comment]
The thing about the download page is that before it was on the wiki where everyone could have replaced the download links with malicious software and now it's safe in the sense that a change of the download links would have to be approved by us.

**Comment by DirtGamer301** [comment]
Oh, I thought development and caring stopped after Skybon got banned and everyone forgot it :P

**Comment by AnotherFoxGuy** [comment]
Can be closed since rigsofrods.github.io redirects to rigsofrods.org
