### ISSUE TITLE
.material files not parsed if terrain is not ZIP-ed

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#603]
Steps to reproduce:
1. Pick any working map
2. Extract the map's ZIP into /terrains/whatever_subdirectory
3. Load the map - materials won't load, object will be light-gray. RoR.log indicate that the material files were never parsed (i.e. no ```Parsing script whatever.material``` entries)

**Comment by DarthCainRor** [comment]
Same error as this? https://github.com/RigsOfRods/rigs-of-rods/issues/523

**Comment by only-a-ptr** [comment]
@DarthCainRor Yes, it's the same error. Thanks for the note
