### ISSUE TITLE
Does not compile on ARM

### ISSUE THREAD

**Issue by Hubbitus** [RigsOfRods/rigs-of-rods#608]
```
/builddir/build/BUILD/rigs-of-rods-23c619a9010e375ea7357ef190ff683f2beac5d4/source/main/physics/BeamFactory.cpp:71:23: error: impossible constraint in 'asm'
    : "a" (i), "c" (0));
                       ^
source/main/main_sim/CMakeFiles/RoR.dir/build.make:3902: recipe for target 'source/main/main_sim/CMakeFiles/RoR.dir/__/physics/BeamFactory.cpp.o' failed
make[2]: *** [source/main/main_sim/CMakeFiles/RoR.dir/__/physics/BeamFactory.cpp.o] Error 1
```

Full log: https://kojipkgs.fedoraproject.org//work/tasks/6906/12586906/build.log

**Comment by Hiradur** [comment]
I compiled RoR on ARM before and it worked, this is a problem with the CPU core cound detection recently introduced by @ulteq 

Code here: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/physics/BeamFactory.cpp#L66

Instead of ```#else```  we need ```#elif defined(_X86_) || defined(__i386__) || defined(__386__)```and another ```#else``` path for non-x86 CPUs.

**Comment by Hubbitus** [comment]
Indeed it compiles now: http://koji.fedoraproject.org/koji/taskinfo?taskID=12667538
Thank you.
