### ISSUE TITLE
auriga terrain without trees and objects 

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#616]
Tested with Ogre 1.9
http://www.rigsofrods.com/threads/104845-Version-0-4-0-6?viewfull=1#post1183749
![ror_2016_01_18_21_08_45_026](https://cloud.githubusercontent.com/assets/1196375/12401814/4339c094-be29-11e5-8740-625a03bd9daf.jpg)

```

**Comment by ulteq** [comment]
Works fine on Linux.

**Comment by Speciesx** [comment]
also on North St. Helens

**Comment by Speciesx** [comment]
And it happens on North St. Helens too.

**Comment by Speciesx** [comment]
All terrains have on thing in common, all these terrain use angelscripts. Without angelscript everything loads fine.

**Comment by Hiradur** [comment]
Can you post angelscript.log?

**Comment by Speciesx** [comment]
```log
12:07:03: ScriptEngine initialized
12:07:03: ScriptEngine (SE) initializing ...
12:07:03: Type registrations done. If you see no error above everything should be working
12:07:09: saving script bytecode to file c:\users\anubis\docume~1\rigs of rods 0.4\cache\script127A8BD8FBBA9021D23ADE8D42E5C6518D6AC667_31-scripts.asc
12:07:09: Executing main()
12:07:09: The script finished successfully.
```
I have already a solution, upgraded angelscript to 2.22.2 has fixed this problem.

**Comment by DirtGamer301** [comment]
I see it's closed but just as a test it might be useful to k now I just got this bug on greece, atleast for a non-coder like me it looks like the same bug:
![screenshot_1236](https://cloud.githubusercontent.com/assets/12358849/14862008/f20fd278-0caf-11e6-9afc-841b066cbdee.jpg)
Just thought I should add this for completion (using 0.4.5.1, not the latest released build).

**Comment by AntoniD330** [comment]
As far as I know, in 0.4.5.1, PSSM Shadows broke some OGRE terrain layers.

A Quote from max98 [(Link to the post)](http://www.rigsofrods.org/old-forum/forums/172-Dev-Chat/119110/page-0017.html)
> _Shadows are very fps yumy &_ sometimes **screwup terrain's layers**. (Eg: **Auriga**, **Greece**..)

I wonder if this bug can be fixed.

**Comment by Hiradur** [comment]
> I wonder if this bug can be fixed.

not with Ogre 1.9 afaik
