### ISSUE TITLE
Parking and turn signal indicators overlap speedometer needle

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#619]
After spawn
![1](https://cloud.githubusercontent.com/assets/1196375/12426109/4159f0a0-bed8-11e5-951d-373320a39c9c.jpg)

turn signal indicator is active and start overlap speedometer needle
![2](https://cloud.githubusercontent.com/assets/1196375/12426110/415c02a0-bed8-11e5-80e3-c911c74ff440.jpg)

after the indicator was active
![3](https://cloud.githubusercontent.com/assets/1196375/12426111/415c3860-bed8-11e5-8d68-d555d4ba9e36.jpg)

But i don't know is this a RoR or MyGUI bug.

**Comment by Hiradur** [comment]
probably wrong z-order

**Comment by only-a-ptr** [comment]
The animation type of the turn signals is ["lamp"](https://github.com/RigsOfRods/rigs-of-rods/blob/86b6bc5f95b9abd937b270747b2c7e0137b65fe8/bin/resources/dashboards/default_dashboard7000.layout#L17), which is updated [here](https://github.com/RigsOfRods/rigs-of-rods/blob/86b6bc5f95b9abd937b270747b2c7e0137b65fe8/source/main/gui/DashBoardManager.cpp#L269-L297).

There's no obvious problem there - a call to MyGUI::ImageBox::setImageTexture() shouldn't modify Z-order or do anything else which affects overlap.
