### ISSUE TITLE
Garage spawn points triggering

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#643]
Load nHelens (happens in all maps). Go to garage door and will open the vehicles menu. Press cancel, go in again. Now the menu is not opening. Go to another spawn point do the same and return to the first which now can be triggered again.

It happens with all spawners (vehicles/loads/planes/boats).

Example video: https://www.dropbox.com/s/k2jqtm178ts652i/garage.mp4?dl=0

Shouldn't this be triggered every time you get in?

Sorry for bad english

**Comment by DirtGamer301** [comment]
IIRC that already happaned with 0.38, if that helps. I can't test it though,

**Comment by tritonas00** [comment]
> IIRC that already happaned with 0.38, if that helps. I can't test it though

I think so, but i cant test because 0.38's angelsctipt is broken in linux amd64

**Comment by DirtGamer301** [comment]
I can't test it either because my 0.38 is broken, it shoots me an error message when starting. Might be a mod, might be something else. But as I didn't use it for ages and kinda replaced it with 0.4 I didn't really bother fixing it.
