### ISSUE TITLE
Settings doesn't save anymore

### ISSUE THREAD

**Issue by WillyB1337** [RigsOfRods/rigs-of-rods#679]
For a really strange reason, The ingame settings doesnt save anymore, even when I press the save button.
**Tried to enable full screen, save, restart, go back in setting, and full screen was uncheck**

[RoR.txt](https://github.com/RigsOfRods/rigs-of-rods/files/111425/RoR.txt)

[configlog.txt](https://github.com/RigsOfRods/rigs-of-rods/files/111427/configlog.txt)

**Comment by WillyB1337** [comment]
Possibly something really wrong! 
`
12:58:02: D3D9 : RenderSystem Option: FSAA = 412:58:02: D3D9 : RenderSystem Option: Render System = Direct3D9 Rendering Subsystem
12:58:02: OGRE EXCEPTION(2:InvalidParametersException): Option named 'Render System' does not exist. in D3D9RenderSystem::setConfigOption at D:\ror\dev\ror_2012\dependencies\src\Ogre\ogre_src_v1-9\RenderSystems\Direct3D9\src\OgreD3D9RenderSystem.cpp (line 397)
12:58:02: Error setting Ogre Values
12:58:02: D3D9 : RenderSystem Option: Video Mode = 1920 x 1080 @ 32-bit colour
12:58:07: D3D9 : RenderSystem Option: FSAA = 4
12:58:07: D3D9 : RenderSystem Option: Fullscreen = Yes
12:58:07: OGRE EXCEPTION(2:InvalidParametersException): Option named 'Fullscreen' does not exist. in D3D9RenderSystem::setConfigOption at D:\ror\dev\ror_2012\dependencies\src\Ogre\ogre_src_v1-9\RenderSystems\Direct3D9\src\OgreD3D9RenderSystem.cpp (line 397)
12:58:07: Error setting Ogre Values
12:58:07: D3D9 : RenderSystem Option: Render System = Direct3D9 Rendering Subsystem
12:58:07: OGRE EXCEPTION(2:InvalidParametersException): Option named 'Render System' does not exist. in D3D9RenderSystem::setConfigOption at D:\ror\dev\ror_2012\dependencies\src\Ogre\ogre_src_v1-9\RenderSystems\Direct3D9\src\OgreD3D9RenderSystem.cpp (line 397)
12:58:07: Error setting Ogre Values
12:58:07: D3D9 : RenderSystem Option: Video Mode = 1920 x 1080 @ 32-bit colour
12:58:11: *** windowFocusChange
12:58:12: *** windowFocusChange
12:58:13: *** windowClosed
12:58:13: *** windowFoc
`

**Comment by only-a-ptr** [comment]
@WillyB1337 Thanks for reporting. I took the liberty to fix formatting in your last comment.

**Comment by only-a-ptr** [comment]
Closing as obsolete. Config subsystem has been completely reworked in current upstream.
