### ISSUE TITLE
Airplane dashboard overlap mouse cursor

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#697]
![ror_2016_02_02_11_59_08_523](https://cloud.githubusercontent.com/assets/1196375/12747471/7931433a-c9a4-11e5-90da-c616951087fc.jpg)

**Comment by Aivar-RoR** [comment]
Still relevant in the latest nightbuild (105).

**Comment by Aivar-RoR** [comment]
Would be nice to have this bug fixed for 0.4.7.

**Comment by Speciesx** [comment]
@only-a-ptr 
I think this should be also fixed  in Milestone 0.4.7.

**Comment by only-a-ptr** [comment]
I was hoping I can avoid this :blush:
This requires me to study Ogre's RenderQueues - basically to force OGRE to render the overlay after the scene, but before MyGUI is rendered. 
it _might_ require a little hack to MyGUI's OgreRenderer.

**Comment by only-a-ptr** [comment]
Bump!

I tried to fix it, but it's not working (no effect): https://github.com/only-a-ptr/rigs-of-rods/commits/overlays-vs-GUI-cursor

At this point, the best solution would be to ditch the old aerialHUD altogether and create a new HUD using our modern approach: http://docs.rigsofrods.org/vehicle-creation/making-custom-hud/

**Comment by Aivar-RoR** [comment]
@only-a-ptr 
Could be possible, but how would the autopilot functions be implemented? I mean automatic wing levelling (WLV), heading lock (HDG), altitude hold etc:

![aircraft_dash](https://cloud.githubusercontent.com/assets/11720273/19900310/b7a19cca-a06b-11e6-85a7-7d81a968d383.png)

Too important to ditch, in my opinion at least.

**Comment by only-a-ptr** [comment]
@Aivar-RoR All controls must be preserved. And you're right, the current HUD subsystem doesn't support controls. We'll need to extend it.

**Comment by Speciesx** [comment]
Fixed in 0.4.8.0
