### ISSUE TITLE
include more input maps

### ISSUE THREAD

**Issue by Hiradur** [RigsOfRods/rigs-of-rods#7]
I think it would be a good idea to include all input maps from this thread:
http://www.rigsofrods.com/threads/96556-Joystick-specific-Input-maps

This way it's easier for beginners to use their controllers. Since they are only text files they don't increase download size very much.

**Comment by Max98** [comment]
This is a great idea, we should do so, and make them select-able ingame. (or RoRConfig for this repo)

**Comment by Pfuu** [comment]
Hi,
i just saw the thread on the forum and as i want ROR not to die, I decide to give this a shot now when i opened the thread i saw some devices have multiple inputmappins what should be done with these?
Grzz Pfuu

**Comment by Hiradur** [comment]
Awesome!
Only one map can be delivered per input device with the game. 
If you want to, you can see which contains more keybindings. Otherwise I would just take the latest one, overwriting the previous one.

**Comment by Pfuu** [comment]
Maybe i can start a thread with a poll for each device that has multiple inputmaps and let the community test which one they like the most or which is broke,.....

**Comment by Hiradur** [comment]
Good idea but I'm unsure if it's worth the effort (ie if you get enough answers). I'm sure they will complain when the maps are delivered with the game though. This way we would have to fix them afterwards but it's probably the better option.

**Comment by graysonk95** [comment]
Has bringing back the old "Keymap" editor from pre-v0.38 ever been considered?

IMO editing input maps by hand or downloading a bunch of other people's maps is a heck of a lot less convenient than just doing it yourself using the automatic tool.
The Keymap editor always struck me as on of the more polished features of Rigs of Rods...

**Comment by Hiradur** [comment]
I don't think so but it is a good idea. Input maps also aren't consistent across platforms. 
It's not something that will make it into NextStable though. Except someone wants to work on it right now.

**Comment by Max98** [comment]
Actually, I've been looking at how other games (using ogre3d) made the key mapping ingame. Seems to be easy and can be implemented in NextStable.

**Comment by Max98** [comment]
We can do some kind of a system where all the keymaps are in a folder (for e.g: config/keymaps) and the default one is called default.map
The configurator will iterate through all files in that folder whom ends with ".map" and will give to the player the ability to change between them.
When a player makes a change using the ingame key mapping, a new ".map" file would be created with his edits. (Only one which is always updated, eg; userkeys.map)

**Comment by Hiradur** [comment]
So with the new configurator coming along, should this be closed?

**Comment by Max98** [comment]
Not yet, I still didn't think about how I should implement this. 
Just leave it open so I don't forget about it.

**Comment by only-a-ptr** [comment]
Closing this with conclusion:
- The link on the top is dead
- Whether we have a new inputmap thread or not (I'm not in the picture), we don't need an open ticket to link it - the documentation is the place for that.
- Regarding the control settings in RoRConfig, there's a separate ticket: https://github.com/RigsOfRods/rigs-of-rods/issues/1070
- Regarding the ingame mapping, that's the future, but the code is ugly already and I'd like to port us to SDL (that would also enable Mac compatibility). Stay tuned.
