### ISSUE TITLE
Unable to resize the ChatBox from top corners

### ISSUE THREAD

**Issue by ghost** [RigsOfRods/rigs-of-rods#725]
When you have RoR at a lower resolution, the ChatBox is way too big and takes up lots of space. It would be great if it was possible to resize it.

My monitor is 1080p, but this is what it looks like if RoR is at 1600x900:
![ror_2016-02-05_22-30-05](https://cloud.githubusercontent.com/assets/11002490/12864440/38f22724-cc58-11e5-92c8-3c85f3ca13c2.png)
As you can see, the ChatBox takes up a good amount of space.

**Comment by disloyalpick** [comment]
Would be nice to have it fade out like older RoR versions when there wasn't a message for so long.

**Comment by tritonas00** [comment]
chatbox is resizable and also auto-hides if you check the option in settings

http://s30.postimg.org/tu97wdhip/2016_02_06_151540_1366x768_scrot.png

**Comment by Hotrod55** [comment]
Well, I guess I was wrong. But you can only resize it from the bottom corners.
