### ISSUE TITLE
Cameras 'Jitter' While Turning

### ISSUE THREAD

**Issue by graysonk95** [RigsOfRods/rigs-of-rods#734]
I vaguely remember this issue from a few years ago, so perhaps this bug was just unearthed.
I just got around to testing the nightly build from Feb. 1 (build 30 I believe?), and it seems like the camera is very jittery for all vehicles.

The interior cameras are fine, but the chase and TV cams all have a noticeable jitter that wasn't present before for all vehicles I have tested on all maps I have tested.

It was mentioned in the nightly thread by another user too: http://www.rigsofrods.com/threads/120878-Rigs-of-Rods-NightBuild?p=1391586&viewfull=1#post1391586

**Comment by ulteq** [comment]
Most likely caused by this: https://github.com/RigsOfRods/rigs-of-rods/commit/059c8c92e556d321c8041efc1cb859a18429b449
