### ISSUE TITLE
Back to menu crash ror on some terrains

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#74]
Such as:
- Auriga Proving Grounds
- Minima
- Belgium

**Comment by Max98** [comment]
Can you tell me what graphic settings you have? (Stencil shadows? Skidmarks? Hydrax? ..)

**Comment by Speciesx** [comment]
![11](https://cloud.githubusercontent.com/assets/1196375/6219935/27531012-b630-11e4-9e82-5f9a9d1e581b.png)

**Comment by Max98** [comment]
Found the problem, destroying water reflection camera 2 times. :3
