### ISSUE TITLE
Henschel 0.4 train doesn't show up in train spawner

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#740]
Get http://www.rigsofrods.com/repository/download/4340 and load https://www.dropbox.com/sh/qn7dohdihj07zif/AABo4H0kP2PcBT6Me0PXGPrra/FlatMap%202013.zip?dl=0 (also happens with other maps) go to the train shop and search for 'hen'

You will see only the 0.38 versions

Now open the vehicles selector and do the same, you can see 0.4 versions also.

**Comment by Aivar-RoR** [comment]
The Henschel train uses the .train file extension that was introduced in 0.4.0.7. Regular truckshops/ load spawners do not support such file extension by default. The same is with train spawners that were made for RoR versions older than 0.4. 
Have a look at Train Valley 0.4 version: http://www.rigsofrods.com/repository/view/5118
You should be able to spawn the Henschel 0.4 version from there. 

Talking about the ability to spawn .train files, have a look at a474UID_trainspawner.odef from the Flatmap 2013 .zip file.
You will find the spawn box that is designed to spawn only .truck files when walked into: 
```
;virtualBox_2_avatar
beginbox
boxcoords 2.05, 4.25, -0.60, 4.00, 2.55, 3.85
virtual
event shoptruck avatar
endbox
```
The 0.4 version of Train Valley uses a modified version of the train spawner, that is included with RoR.
Have a look at trainspawner.odef located in Program Files\Rigs of Rods 0.4.x.x\meshes.zip
The event box that triggers spawning of only .train files:
```
;virtualBox_2_avatar
beginbox
boxcoords 1.00, 8.00, -0.60, 4.00, 2.50, 5.50
virtual
event shoptrain avatar
endbox
```
As you can see the train spawners have to be modified to spawn .train files: shoptruck vs shoptrain.
Other events that are used by other spawners include (just for info)
shopextension for .load and .trailer files
shopplane for .airplane files
shopboat for .boat files.

**Comment by tritonas00** [comment]
Great so not a game issue. Thanks for the info!
