### ISSUE TITLE
[NB 35] Configurator overwrite my sound setting

### ISSUE THREAD

**Issue by WillyB1337** [RigsOfRods/rigs-of-rods#742]
Everytime I get to the Configurator then Save and Exit, the Audio Device Option always reset to the default setting. 

In-game setting for Audio Device are fine.
It's annoying that I could not get to the Multiplayer server screen without having sound.

[configlog.txt](https://github.com/RigsOfRods/rigs-of-rods/files/120443/configlog.txt)

**Comment by Hiradur** [comment]
What version are you using?

**Comment by WillyB1337** [comment]
Since a few builds (20 to now)
