### ISSUE TITLE
engoption Issues

### ISSUE THREAD

**Issue by graysonk95** [RigsOfRods/rigs-of-rods#747]
I have yet to find a vehicle that is experiencing transmission problems other than my own, but the only thing I can narrow down is that my vehicles use non-default values in the engoptions line.

It seems as though clutchtime, shifttime, and/or postshifttime is not working like it should. It takes my transmissions multiple seconds to change gears now.
In 0.4.5.1 my shifts were quick, now they take forever, so something has changed.

**Comment by ulteq** [comment]
Please test again when the next nightly build is out. This might have already been fixed.

**Comment by ulteq** [comment]
Please test again when the next nightly build is out. This might have already been fixed.

**Comment by graysonk95** [comment]
Tested through build 36 (Feb. 7). Behavior is still present, however, I identified another vehicle impacted:
OnyxPL's Audi 80 also is suffering from the very slow and mushy auto trans.
(http://www.rigsofrods.com/threads/87177-Audi-80-B2-CC-%28Download-link-on-page-17-post-327%29?p=964781&viewfull=1#post964781)

It also uses non-default engoption values:
_engoption
;inertia, type, clutchforce, shifttime, clutchtime, postshifttime
0.05, c, 320.0, 0.30, 0.40, 0.30_

Here are my values, which are also non-default:
_engoption
;inertia, type, clutchforce, shifttime, clutchtime, postshifttime
2.5,     t,     3000.0,       0.40,     0.42,      0.01_

Additionally,  _stallRPM_, _idleRPM_, _maxIdleMixture_, and _minIdleMixture_ behave differently than 0.4

**Comment by ulteq** [comment]
I can't reproduce it, sorry.

**Comment by graysonk95** [comment]
I'll get a video when I get the chance...

**Comment by ulteq** [comment]
All of these work just fine for me:

* [Audi 80 B2 CC](http://www.mediafire.com/?tc927day8vat1q7)
* [Thomas Saf-T-Liner C2](http://www.rigsofrods.com/attachment.php?attachmentid=526553&d=1424042296)
* [Thomas Saf-T-Liner HDX](https://www.mediafire.com/?wp20s19jl6qooss)

**Comment by graysonk95** [comment]
Here's a video of the behavior on my HDX:
https://youtu.be/IjcUMIooylY

Pay attention to both the speedo and tacho needles.

**Comment by ulteq** [comment]
First of all, great video!

But, in both cases it takes ~20 seconds to reach 50 km/h.
And in both cases it takes ~13 seconds to reach the 4th gear.

The only difference I can see is the time it takes for the clutch to be fully released.

What exactly do you mean when you say "_mushy and slow_"?

I would really like to improve it, but I am not sure what exactly you dislike about the current version.

Do you only mind that the engine speed is not decreasing as much as it used to do, during shifting, or is it something else?
