### ISSUE TITLE
provide the ability to disable the spawner log window

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#75]

**Comment by Max98** [comment]
Well... Already discussed this with only_a_ptr, he said that he wants to keep it like that for the moment to show people how bad they are creating truck files. xD

**Comment by Speciesx** [comment]
This window is pretty annoying, it's like flash popup on a web page.

**Comment by Max98** [comment]
Yup it is hahah

**Comment by Hiradur** [comment]
I don't like it, too and it may turn off some who would still be using 0.38 then...

**Comment by Max98** [comment]
Alright, will work on it.

**Comment by Max98** [comment]
Done. Will work on the settings part an other time (Do we really need it anyway? You can press on RigSpawner at the simulation bar and it pops up.)
