### ISSUE TITLE
Truckfile: misbehaving set_beam_defaults_scale?

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#760]
Reported by derbymutt in Gitter chat:

> I realize the wiki was never really clear about this, but set_beam_defaults_scale was previously able to be used more than once; as well as it only affected set_beam_defaults lines below it until the next set_beam_defaults_scale, recent builds of RoR from github are ignoring any instances of it other than the first one
> 
> I feel like this is a pointer issue since its only being assigned once, even though the code looks like it should be parsing and assigning it each time
> 
> lines 1729, 1733, 1737 and 1741 of /rig_file_input_output/RigDef_Parser.cpp might be to blame

**Comment by derbymutt** [comment]
I've gone ahead and recorded a couple clips showing the issue visually, this n/b is based around 2 set_beam_defaults_scale, one at the top, and one at the custom generated tire shocks. 

When the second is assigned correctly, the tires break under lateral force as they are meant to.
When the second is not assigned, the tires fail to break.
https://youtu.be/K48mwy5Zykg <--- working (0.4.0.8)
https://youtu.be/3Ut5tACRsu8 <--- not working (0.4.6.0)

I've gone ahead and put the zip of the vehicle below to offer some kind of existing content which relies on multiple instances of set_beam_defaults_scale for testing.
https://www.dropbox.com/s/9f86xxbtce4xqvm/The%20Habanero.zip?dl=0

**Comment by ulteq** [comment]
All `set_beam_defaults_scale` lines in your example truck are identical.

**Comment by only-a-ptr** [comment]
Derbymutt:
> What happened to the helpful debug output, things saying how much a beam's defaults were scaled by set_beam_defaults_scale?

**Comment by only-a-ptr** [comment]
I still need to investigate the set_beam_defaults_scale

**Comment by only-a-ptr** [comment]
TODO: Re-implement the informative log message about set_beam_defaults + scale: https://github.com/RigsOfRods/rigs-of-rods/blob/bd680916356ea033716c96582305a37347644b9a/source/main/physics/input_output/SerializedRig.cpp#L1207-L1215
