### ISSUE TITLE
Multiple Player spawns per map

### ISSUE THREAD

**Issue by DarthCainRor** [RigsOfRods/rigs-of-rods#761]
As I've been working on the Community map lately, and just from using Brickman's Rockton County, I've discovered something that would be kind of handy for using terrains. At the moment, in order to have different spawn positions on a map, it requires separate terrains, as in Rockton. It would be nice if something similar to the "sections" code on a .truck file would work for a .terrn, to allow for one terrain, with multiple spawn locations, if defined.

**Comment by graysonk95** [comment]
To add, how about character teleportation between those spawn points once the map is already loaded?

**Comment by ulteq** [comment]
> how about character teleportation between those spawn points

:+1:
