### ISSUE TITLE
If you load another vehicle, vehicle stops working until reset of game.

### ISSUE THREAD

**Issue by RORLoverIDK** [RigsOfRods/rigs-of-rods#764]
#Bug (I only get this on ROR 0.4.5.1)
When i load one vehicle and load another one, the seconded one stops working if driven.
Please fix this, the only version i use to spawn multiple vehicles is 0.38.67.
Thanks,
RORLoveIDK

**Comment by Hotrod55** [comment]
Have you tried any of the NightBuilds from http://www.rigsofrods.com/threads/120878-Rigs-of-Rods-NightBuild ? I haven't encountered this issue in the upstream yet.

**Comment by RORLoverIDK** [comment]
How do i get the game running? i cant open the game up.

**Comment by Hiradur** [comment]
Did you follow the installation instructions in the first post?

**Comment by RORLoverIDK** [comment]
Got nightbuild to work finally

**Comment by Hotrod55** [comment]
It's been over a month since last reply; I would assume this issue is fixed.
