### ISSUE TITLE
'Reload current vehicle' spawn a second vehicle

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#765]
Load a vehicle and reload it and you get a second vehicle and the first loaded vehicle will be moved to x: 100002 y: 100001 z: 100001.

![ror_2016_02_09_17_16_41_987](https://cloud.githubusercontent.com/assets/1196375/12922367/6f5bcbb6-cf51-11e5-9b92-bc42b8b7e87f.jpg)

**Comment by Hotrod55** [comment]
#359
