### ISSUE TITLE
It crashes whenever i try entering a vehicle...

### ISSUE THREAD

**Issue by Xx00500xX** [RigsOfRods/rigs-of-rods#781]
Everything works fine until i try entering a vehicle...

**Comment by Speciesx** [comment]
OS? ror version?

**Comment by Xx00500xX** [comment]
I have Ror 0.4.5.1

Here's some info about my computer.
Windows 10 
AMD A6-3420M APU with Radeon(tm) HD Graphics
1.5 GHz

Video Card 1	AMD Radeon HD 6520G
Manufacturer	ATI
Chipset	AMD Radeon HD 6520G
Dedicated Memory	1.5 GB
Total Memory	4.0 GB
Pixel Shader Version	5.0
Vertex Shader Version	5.0
Hardware T & L	Yes

Video Card 2	AMD Radeon HD 7400M Series
Manufacturer	ATI
Chipset	Radeon HD 7450M
Dedicated Memory	1024 MB
Total Memory	1024 MB
Pixel Shader Version	5.0
Vertex Shader Version	5.0
Hardware T & L	Yes

Drive	
Size	697.8 GB
Free	439.0 GB

**Comment by Speciesx** [comment]
Maybe this is already fixed.
If you want, you can try the NightBuild.
http://anotherfoxguy.com/RigsofRods/NightBuild/43/

**Comment by Xx00500xX** [comment]
It dosent want to work for some reason.

**Comment by Speciesx** [comment]
@Xx00500xX 
http://www.rigsofrods.com/threads/120878-Rigs-of-Rods-NightBuild?p=1391499&viewfull=1#post1391499

**Comment by Xx00500xX** [comment]
Now, it dosent want to let me insert a vehicle anymore

**Comment by Xx00500xX** [comment]
and it used to work before i had windows 10

**Comment by AntoniD330** [comment]
Hello @Xx00500xX 

We need some references, by adding some links, such as:

- Download link for the vehicle in question;
- and your **RoR.log** (Found in this location: "\Documents\Rigs of Rods 0.4\logs").

By adding these useful files, we can in a quick way try to fix this bug.


More informations [here](https://github.com/RigsOfRods/rigs-of-rods/blob/master/CONTRIBUTING.md#reporting-bugs).

**Comment by Xx00500xX** [comment]
Hello @AntoniD330

For the vehicle i used, i tried both busses that come standard in the game, i also used 
these: 
http://www.rigsofrods.com/repository/view/3722
and 
http://www.rigsofrods.com/repository/view/2573

Here's the RoR.log:
[RoRlog.txt](https://github.com/RigsOfRods/rigs-of-rods/files/131746/RoRlog.txt)

**Comment by WillyB1337** [comment]
Only thing I found in the log is this : 
`20:48:14: OGRE EXCEPTION(5:ItemIdentityException): Cannot find section Scripts in ConfigFile::getSettingsIterator at C:\data\codehg\dependencies\src\Ogre\ogre_src_v1-8-1\OgreMain\src\OgreConfigFile.cpp (line 215)` 

I don't have this error in my latest log.

You could try to reinstall the game ;)

**Comment by Hiradur** [comment]
Can you post RoR.cfg from ```\Documents\Rigs of Rods 0.4\config```?

**Comment by Xx00500xX** [comment]
@WillyB1337 i tried reinstalling the game many times, 
 @Hiradur sure
[RoR - Copy.txt](https://github.com/RigsOfRods/rigs-of-rods/files/135466/RoR.-.Copy.txt)

**Comment by Hiradur** [comment]
RoR.cfg looks fine. No idea why it could crash. Did you play around with the settings a bit to see if it makes a difference?

**Comment by Xx00500xX** [comment]
@Hiradur i did play with the settings but it served nothing. it still crashes whenever i try entering anything

**Comment by WillyB1337** [comment]
What I would do at this point is deleting everything related to RoR.
The Rigs of Rods 0.4 of Programs Files than Rigs of Rods 0.4 in Document Folder 
(Make backup of the content & keymap settings if any)

**Comment by Speciesx** [comment]
@Xx00500xX 
Did you try to regen the cache?

**Comment by Xx00500xX** [comment]
@Speciesx  i did try to regen the cache but it didn't help

**Comment by Xx00500xX** [comment]
@WillyB1337 
with 0.4.6, it crashes whenever i try loading a vehicle...

**Comment by WillyB1337** [comment]
Possibly a hardware issue by now.

What you can try is to turn off one of your GPU

**Comment by AntoniD330** [comment]
@Xx00500xX 
Did you have a joystick connected to your PC?
If so, did you try to disconnect it?

**Comment by Xx00500xX** [comment]
@AntoniD330  i dont have a joystick
 @WillyB1337 How?

**Comment by WillyB1337** [comment]
@Xx00500xX You can turn off the GPU driver by going to the device manager, then Graphics Card.

As you have 2 GPU, you disable the one **that's not** connected to your monitor

**Comment by Xx00500xX** [comment]
@WillyB1337 how can know if it is connected to my monitor or not?

**Comment by ulteq** [comment]
@Xx00500xX, Please create a new issue if you still can't make it work.
