### ISSUE TITLE
Vehicle stats panel not localized.

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#785]
![screenshot_2016-02-18_23-25-59_1](https://cloud.githubusercontent.com/assets/491088/13202826/681d8780-d8a8-11e5-88bf-d9a2511defbd.png)

The panel is not localizable - the texts are hardcoded:
https://github.com/RigsOfRods/rigs-of-rods/blob/1b6c938d5f5e57d65f6793f7bafc4b75fe1557bd/source/main/gui/panels/GUI_SimUtils.cpp#L232-L235

**Comment by AnotherFoxGuy** [comment]
Already fixed #782

**Comment by only-a-ptr** [comment]
> Already fixed #782
:blush:
