### ISSUE TITLE
[Main menu / settings] Language selector is dummy.

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#786]
Apparently the language selector in settings dialog is an unfinished feature.

It always displays only U.S. English, no matter what languages are available.

It always displays U.S. English as active language, no matter what's the actual setting.

@Hiradur Does our language engine / gettext subsystem support runtime switching of languages at all?

**Comment by Hiradur** [comment]
Are you talking about the ingame settings menu or RoRConfig? RoRConfig language selection works fine for me. I don't think RoR supports runtime language switching yet, unless @Max98 implemented it.

**Comment by AnotherFoxGuy** [comment]
The in-game languages switcher isn't implemented yet
https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/gui/panels/GUI_GameSettings.cpp#L210

**Comment by only-a-ptr** [comment]
@Hiradur @AnotherFoxGuy Yup, I assumed it's not implemented yet, that's why I didn't add a [bug] label. Nonetheless, I completely forgot about it, so I made issue as a backlog task.

**Comment by tritonas00** [comment]
not anymore, right?

**Comment by AnotherFoxGuy** [comment]
Has been fixed with PR #1925
