### ISSUE TITLE
[RC1] commands/needsengine misbehavior?

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#787]
_Reported on forum: http://www.rigsofrods.com/threads/120909-Test-build-Version-0-4-6-RC1?p=1392023&viewfull=1#post1392023_

Even if a prop has needengine in commands2 set to 0, it will still give that prop a pump sound. Look at Graysonk95's Thomas HDX. When you open the signs, there should be no sound (as it was in 0.4.0.7-0.4.5.1), but in RC1, there is. And I've checked, needengine is set to 0.

**Comment by AnotherFoxGuy** [comment]
I don't think that is a bug because the needengine flag is only for that the command works without an engine.
From the wikipage http://www.rigsofrods.com/wiki/pages/Truck_Description_File#Commands2
> value of "true" means that the command only works with a running engine. "False" means engine is not needed.

**Comment by only-a-ptr** [comment]
Maybe not, but I'm interested to know whether there's a difference from 0.4.5.1.
I'd prefer the sounds behavior not to change, even if it was inaccurate in previous versions

**Comment by ulteq** [comment]
[Observations](http://www.rigsofrods.com/threads/104845-Version-0-4-0-6?s=43782adb74fc7e9b60207eee4c040e4b&p=1185699&viewfull=1#post1185699) from @graysonk95:
> * Command_1 operates normally with sound, however, when the engine is off the command doesn't move and the sound never stops.
* Command_2 only operates when the engine is on and there is no sound.
* Command_3 operates without the engine, but has no sound.

**Comment by only-a-ptr** [comment]
> As suggested by @fidoj, we could add a new optional parameter playsSound that overrides the default behavior.

Agreed with minor modification: Let's add a new option letter "s" into the existing options string.

**Comment by ulteq** [comment]
This commit: https://github.com/RigsOfRods/rigs-of-rods/pull/775 broke the `affect_engine`, `needs_engine` parsing.

**Comment by ulteq** [comment]
> Let's add a new option letter "s" into the existing options string.

Let's make a new github issue for it and postpone it to > 0.4.6

**Comment by graysonk95** [comment]
Likewise, could we also get a mute flag?

I would like to add a (working) high idle switch, but in order to do so, the high idle command beam must rev up the engine but not play the pump sound.
(A high idle switch is simulated through the use of a painfully slow command beam).

Voulk's high idle on his Thomas pack utilizes a command to rev up the engine, but he uses no pump sound at all, so his commands are effectively muted.
I use a pump sound on my HDX, so I have no way to do this without the high idle command hissing.
