### ISSUE TITLE
[RC2] Problem with "Greece" map under Direct3D9

### ISSUE THREAD

**Issue by AntoniD330** [RigsOfRods/rigs-of-rods#788]
### Steps to reproduce
1. Run the game with Direct3D9 render using RoRConfig;
2. Go to "Greece" map (Download link below);
### Expected behaviour

The "Greece" map loads houses, rocks and other miscellaneous mesh objects over the map along with vegetation.
### Actual behaviour

Under DirectX, "Greece" map won't load any meshes and vegetation. (Screenshot)
### System configuration

OS: Windows 7 Professional
Version of the game: Rigs of Rods 0.4.6 RC2
Renderer used: Direct3D9
Vegetation: Full (best looking, slower)
### Additional information, logs and screenshots

Note: If you try this with OpenGL render, the map load everything. This bug occures only with Direct3D9.

Downloads: 
[Map](http://www.rigsofrods.com/repository/view/4418);
[Game](http://www.rigsofrods.com/threads/120909-Test-build-Version-0-4-6-RC2?p=1392016&viewfull=1#post1392016);
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/139839/RoR.txt).

Screenshot: 
![screenshot_2016-02-21_20-31-04_1](https://cloud.githubusercontent.com/assets/15718991/13204908/95e684d6-d8db-11e5-9310-7f140dff4ebe.png)

**Comment by Speciesx** [comment]
Works for me.
![ror_2016_02_21_22_23_12_883](https://cloud.githubusercontent.com/assets/1196375/13205499/cc562842-d8e9-11e5-80dc-a28da7a86a46.jpg)
 
Works auriga-0.4 terrain correct?
http://www.rigsofrods.com/attachment.php?attachmentid=395793&d=1368901728

**Comment by AntoniD330** [comment]
@Speciesx 
> Works auriga-0.4 terrain correct?

No, unfortunately.

When I want to go in Auriga Proving Grounds, the game crash and pop-up this error message:

![error 0](https://cloud.githubusercontent.com/assets/15718991/13205678/c0bff1bc-d8ed-11e5-9911-792e2b7ec240.png)

I've searched anywhere, I can't find the requested .mapbin files in RoR document folder.

I've tried to clean and regen the cache, it didn't solve the problem.

**Comment by Speciesx** [comment]
It should be in Rigs of Rods installations folder.

**Comment by AntoniD330** [comment]
@Speciesx 
> It should be in Rigs of Rods installations folder.

Yes, I've found it. Cuted and pasted in cache folder. It works like a charm now. Thank you!  :+1: 
<hr>
Also, I've tried to run the game by disabling **DirectX9Ex**, this will resolve the problem with "Greece" map. (You can found this setting on RoRConfig: "Settings" and then "Render System" tab.)

In the RoR.log posted in the first post, I've enabled DirectX9Ex, the game prints multiple [Error 3](http://www.rigsofrods.com/wiki/pages/Error_3). (Who is related to the vegetaion system).

**Comment by Hiradur** [comment]
Could you delete all your .mapbin files in the cache directory and try again with the latest nightbuild?
http://rigsofrods.anotherfoxguy.com/forum/showthread.php?tid=4&pid=5#pid5
