### ISSUE TITLE
What happened to the whole website?

### ISSUE THREAD

**Issue by danielchim** [RigsOfRods/rigs-of-rods#796]
![default](https://cloud.githubusercontent.com/assets/12156547/13247216/33a6230c-da53-11e5-8838-d116f8a76371.PNG)
The whole website was down.

**Comment by Hiradur** [comment]
Closing as duplicate of #795

**Comment by danielchim** [comment]
why closed?
2016/2/23 下午7:09 於 "Hiradur" <notifications@github.com> 寫道：

**Comment by Hiradur** [comment]
Because one ticket to discuss this issue is enough, see #795
