### ISSUE TITLE
RoR 0.4.6 RC2 crashes when loading Rockton 16

### ISSUE THREAD

**Issue by Dogy144** [RigsOfRods/rigs-of-rods#799]
RoR Log error:

> ===== LOADING TERRAIN GEOMETRY RTBM16 rockton city.terrn2
> 16:28:05:   ## Loading Terrain Geometry
> 16:28:05: loading page config for page [0,0] : RTBM16-page-0-0.otc
> 16:28:05: done loading page: loaded 1 layers
> 16:28:05: OGRE EXCEPTION(1:InvalidStateException): Cannot determine endian mode because header is missing in StreamSerialiser::readHeader at D:\ror\dev\ror_2012\dependencies\src\Ogre\ogre_src_v1-9\OgreMain\src\OgreStreamSerialiser.cpp (line 238)
> 16:28:05: We failed to prepare the terrain at (0, 0) with the error 'OGRE EXCEPTION(1:InvalidStateException): Cannot determine endian mode because header is missing in StreamSerialiser::readHeader at D:\ror\dev\ror_2012\dependencies\src\Ogre\ogre_src_v1-9\OgreMain\src\OgreStreamSerialiser.cpp (line 238)

Link to terrain: http://www.rigsofrods.com/threads/120818-RELEASED-Rockton-County-2016

Use the "Rockton County 16 Rockton City" terrain.

**Comment by AnotherFoxGuy** [comment]
Delete all mapbin files from the Rigs of Rods 0.4/cache folder

**Comment by Dogy144** [comment]
That fixed it, thanks! What exactly do the .mapbin files do?

**Comment by Hiradur** [comment]
> That fixed it, thanks! What exactly do the .mapbin files do?

They serve as a cache to speed up map loading and other things. 
They needed to be deleted because older releases of RoR run on Ogre 1.8 and 0.4.6.0 runs on Ogre 1.9 and the mapbin files are incompatible between these versions.

**Comment by AnotherFoxGuy** [comment]
>0.4.6.0 should've created new *.mapbin files

It is fixed in RC3
