### ISSUE TITLE
Package Repository

### ISSUE THREAD

**Issue by ffsi** [RigsOfRods/rigs-of-rods#801]
In Issue #798 are given some ideas for the repository. To leave more focused discussion there. I leave here my suggestion for a repository like Flightgear.

Hosted .zip + .xml

http://fgfs.goneabitbursar.com/pkg/

http://fgfs.goneabitbursar.com/pkg/2016.1.0/catalog.xml

Where you put the catalog URL (Official or 3rd) at preferences catalog list, and the program takes care of downloading, and keep updated. 

Its nice because you have a full list to choose from, and do not need to look elsewhere, to download and install.

**Comment by only-a-ptr** [comment]
@ffsi Thanks for the inspiration.

**Comment by AnotherFoxGuy** [comment]
the static website I've made uses .xml files to generate the repository pages
http://rigsofrods.anotherfoxguy.com/repository/

http://rigsofrods.anotherfoxguy.com/repositoryFiles/lt/
http://rigsofrods.anotherfoxguy.com/repositoryFiles/lt/info.xml
