### ISSUE TITLE
make fails with "[...]/source/main/gui/LobbyGUI.h:34:19: error: expected class-name before ‘,’ token"

### ISSUE THREAD

**Issue by krichter722** [RigsOfRods/rigs-of-rods#802]
On Ubuntu 15.10 and 16.04 `cmake . && make` fails with

    In file included from /mnt/richtercloud/sources/rigs-of-rods/source/main/gui/LobbyGUI.cpp:23:0:
    /mnt/richtercloud/sources/rigs-of-rods/source/main/gui/LobbyGUI.h:34:19: error: expected class-name before ‘,’ token
      public IRCWrapper,
                       ^

experienced with 0.4.5.1-555-gd1d3d0f

**Comment by Hiradur** [comment]
> On Ubuntu 15.10 and 16.04 ./configure && make fails with

configure shouldn't work at all, you need to run CMake instead. See the scripts in https://github.com/RigsOfRods/ror-linux-buildscripts/tree/0.4.5.1 for commands to build 0.4.5.1.

**Comment by krichter722** [comment]
Of course, my bad. But that's what I did.

**Comment by Hiradur** [comment]
Can you try to build the master branch instead? It buils fine with Xubuntu 15.10 for me. It's also more stable than 0.4.5.1.

**Comment by krichter722** [comment]
> experienced with 0.4.5.1-555-gd1d3d0f

That is HEAD of the master branch.

**Comment by Hiradur** [comment]
> That is HEAD of the master branch. See man git describe for details.

Right, my bad.
I have no clue why it doesn't work. Have you done any changes to your setup (compiler, flags ...)?

**Comment by krichter722** [comment]
> I have no clue why it doesn't work.

Did you try a fresh clone? Maybe in a freshly installed VirtualBox VM?

> Have you done any changes to your setup (compiler, flags ...)?

No. I confirmed with fresh clones on Ubuntu 15.10 desktop and VirtualBox VM and 16.04 desktop.

**Comment by Hiradur** [comment]
> Did you try a fresh clone? Maybe in a freshly installed VirtualBox VM?

No, I'll see what I can do.
I have another idea though, are you building without SocketW?

**Comment by Hiradur** [comment]
@krichter722 I built RoR on a fresh install of Xubuntu 15.10 using https://github.com/RigsOfRods/ror-linux-buildscripts and encountered no problems.

**Comment by Hiradur** [comment]
No response for 3 months -> closing. Feel free to reopen if the issue still exists.

**Comment by krichter722** [comment]
fixed with 0.4.5.1-1064-g9c9a558 on Ubuntu 16.04
