### ISSUE TITLE
New website - static content (homepage, blog, docs)

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#804]
I'd like to compose the new website of mostly static content.

**Website overview**
- Homepage (with latest downloads) - static
- Blog - static pages
- Knowledge base - a set of static documents. I think having static official docs on the website + user-contributed guides in the forum is just fine. Wiki solutions tend to be heavyweight and complicated to maintain.
- Forum - dynamic, PHP+MySQL
- Repository - dynamic, PHP+MySQL (to be discussed)
- Development - static page: links to GitHub repo services + Doxy documentation. I'd like to put all developer documentation directly to Doxy docs rather than wiki/knowledgebase.

**Homepage**
- I want 3 download links on the main page: RoR itself, rortoolkit, and repo link. RoRtoolkit is signifficant - we want to encourage creativity and experimens.
-    The "sandbox full of toys" promo texts are just silly IMO. I want more serious phrasing. My vision of RoR isn't a child's toy, but hardcore simulator aimed to precise physics.
-    I'd like to formulate a "RoR manifesto" and publish it on the main page.
-    The top banner and bottom screenshots duplicate themselves IMO. Screenshots should be in the banner, and so should be ALL download links, with descriptions ( "DOWNLOAD!" is for mainstream)
-    We need to publis a LOT of docs (truckfile docs, map format docs, 3d graphics guides, rortoolkit manual, player manual...). To do all this, I want a comfortable and reliable authoring workflow.

Anyone got experience with static-web generators? Our github webpage http://rigsofrods.github.io uses a set of tools, described here: https://github.com/RigsOfRods/rigsofrods.github.io It works, but the sourcebase is not very well organized, page content is heavily fragmented into tiny textfiles.

**Comment by Hiradur** [comment]
> static Knowledge base

I'd like to mention that we had some static documents at rigsofrods.github.io but I removed them in a later commit in favor of the Wiki: https://github.com/RigsOfRods/rigsofrods.github.io/tree/761ea95a8609d6ff2471c0194dd6495da5deea93/content/source/docs

btw: I like the appearance of http://ethanschoonover.com/solarized which was generated with hakyll (info here: http://ethanschoonover.com/colophon). However, the website is rather simple and has more of an old skool style.

**Comment by Speciesx** [comment]
> Knowledge base - a set of static documents. I think having static official docs on the website + user-contributed guides in the forum is just fine. Wiki solutions tend to be heavyweight and complicated to maintain.

This is a pretty bad idea, this will end up in a mess. You will have to search in two different places and what will happen to translations?

**Comment by only-a-ptr** [comment]
> we had some static documents at rigsofrods.github.io but I removed them in a later commit in favor of the Wiki: https://github.com/RigsOfRods/rigsofrods.github.io

True. Motivation was to avoid fragmentation between old Wiki (majority of content) and github.io (popular content). Now that old wiki is gone, we'll be rebuilding the knowledgebase in some way.

> This is a pretty bad idea, this will end up in a mess. You will have to search in two different places and what will happen to translations?

Thanks for the comment, but I don't really understand your concern - this isn't anything new, the process of "wikifying good forum posts" has always been here. I'd simply like to continue this system.

**Translations**: good point. Historically, they were a mess. A translated wikipage was technically a separate document, and it showed. Most translated wikipages I've seen were copies of english with some parts translated. Or it was a complete translation of an outdated version of the original page.

An ideal solution would be true localized document, where texts are loaded from a resource, and if a translation is missing _or out of date_, it automatically falls back to english (possibly with some hint to translators: "this needs update!"). A visibly missing translation is better than outdated (possibly misleading) translation.

**Comment by nick149** [comment]
I dont have much experience with static generators however gitbook looks pretty easy to me

**Comment by jacobl1111** [comment]
so what about the repository? I just downloaded ROR but when I want to go to the repository I get an 404 error of Github. are there any other ways to acces the repository?

**Comment by AntoniD330** [comment]
@jacobl1111: The repository is located here: https://repofiles.avrintech.net/.
But you need to do manual research for mods.
