### ISSUE TITLE
Toolkit Roads

### ISSUE THREAD

**Issue by zacharylROR** [RigsOfRods/rigs-of-rods#805]
So i placed a bunch of roads in toolkit on Flatsville county and i got no collisions.
https://gyazo.com/bb3d33b8136de85a4701bca4586671c9 
I got collisions on the default roads just not the ones i added PLZ HELP!

**Comment by DirtGamer301** [comment]
Do they have correct .odef files?

**Comment by zacharylROR** [comment]
Its also with the roads i added ill double check

**Comment by zacharylROR** [comment]
Still does it

**Comment by zacharylROR** [comment]
Any other ideas?

**Comment by DarthCainRor** [comment]
Map may be over the default collision limit. What version are you using?

**Comment by zacharylROR** [comment]
I'm using .39.3

**Comment by zacharylROR** [comment]
We're would I find the Collison limit the terrorists file

**Comment by zacharylROR** [comment]
?

**Comment by Dogy144** [comment]
Solution would probably be to move to the latest version.

**Comment by zacharylROR** [comment]
Issue is this a company Map and I really need to use .39.3

**Comment by zacharylROR** [comment]
Anyone know what file to open so i can change the collision limit

**Comment by Aivar-RoR** [comment]
Open the .terrn file of the map.
Paste the following line into the .terrn file (on top of the file, e.g after fileinfo and before objects):

collision-tris **150000**

Adjust **the value** as necessary. Default is 100000.

**Comment by zacharylROR** [comment]
Thanks!

**Comment by Hiradur** [comment]
@zacharylROR Please close this issue if your problem was solved.

**Comment by zacharylROR** [comment]
How do i close it srry

**Comment by Hiradur** [comment]
There is a button "close issue" next to the "comment" button but I'll close it for you.

**Comment by zacharylROR** [comment]
Thank you
