### ISSUE TITLE
RoRConfig.exe CRASH! Can't Open Game

### ISSUE THREAD

**Issue by arezer** [RigsOfRods/rigs-of-rods#806]
Hi,
I recent download rigs of rods 0.4.5.1, and after finish installing,
When I first click ror.exe, I got an error but it just appear once,so I forgot what it say :D...
After that, when I click ror.exe, it ask to open rorconfig.exe first,
Clicking on rorconfig.exe goes to a crash...

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	RoRConfig.exe
  Application Version:	0.4.5.1
  Application Timestamp:	55dcce74
  Fault Module Name:	RoRConfig.exe
  Fault Module Version:	0.4.5.1
  Fault Module Timestamp:	55dcce74
  Exception Code:	c0000005
  Exception Offset:	0003a41e
  OS Version:	6.1.7600.2.0.0.256.1
  Locale ID:	17417
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Umm, My PC Specs...
Intel Pentium Dual Core E2160 1.80 GHz
2 GB RAM DDR2
Windows 7 Ultimate 32-bit
Intel Express Chipset Family Q35

Thanks, Hope you can solved the problem quickly :\ for me....

**Comment by nick149** [comment]
Can you run as a Admin (or even in comparability mode to Windows XP)?
Can you reinstall 4.5.1 for me? Because it sounds like the short cut is messed up or either rorconfig.exe, if it does not work try installing 0.4.5.0 and see if you get the same error.

**Comment by Hiradur** [comment]
@arezer Does it still happen with 0.4.6.0 Release candidate?
Download here: anotherfoxguy.com/RigsofRods/Rigs-of-Rods-0.4.6.exe

**Comment by arezer** [comment]
Nothing above work :\ ...
Help me please T-T....

**Comment by arezer** [comment]
Nah I just found the solution...Just change Region and Language format to English (US)
._.   ....can u fix this? and do you know SIMPLE 4x4 offroad vehicle? I download vehicle at http://www.rigsofrods.com/forums/110-Mods-Skins make my RoR lagg,seems that vehicle in good graphics, my spec just pass the low requirement...

**Comment by arezer** [comment]
Nah, just found the solution...
Just change Region and Language format to English (US) ._.
