### ISSUE TITLE
Button mapping in settings menu

### ISSUE THREAD

**Issue by lexman02** [RigsOfRods/rigs-of-rods#808]
So since the repo went down theres nowhere fo us to find input maps. There needs to be an easy way to make them or there has to be a way of getting the old ones back.

**Comment by Hiradur** [comment]
You may find some here https://web.archive.org/web/20160124054715/http://www.rigsofrods.com/repository/

**Comment by lexman02** [comment]
So I was able to find the input map but when I tried to download it, it didnt allow me to.

**Comment by Hotrod55** [comment]
I have the repo files uploaded here if you need something from it: http://ny.avrintech.net:81/repofiles/

**Comment by lexman02** [comment]
Lol maybe its just me but I couldnt find it on your website either

**Comment by lexman02** [comment]
I still cant remap buttons in 0.4.6

**Comment by Hiradur** [comment]
> I still cant remap buttons in 0.4.6

it's not implemented yet, this option should be grayed out or something.

**Comment by lexman02** [comment]
I can still select it in options, I just cant change anything.
