### ISSUE TITLE
Brakes Apply Too Suddenly

### ISSUE THREAD

**Issue by graysonk95** [RigsOfRods/rigs-of-rods#81]
Unless you drive with a controller you probably haven't noticed this, but the brakes apply much too quickly.
Simply tapping the brake pedal on most vehicles will bring them to a stop, if not lurch them to a stop.
In contrast, fully depressing the brake pedal struggles to stop some vehicles.

Finding a brake force value that is a happy-medium is difficult when creating a vehicle:
Setting the value too high means the vehicle can stop quickly, but tapping the brake even lightly could lock up the wheels.
Setting the value too low makes the brakes apply smoothy, but good luck coming to a complete stop.

I would expect as the brake pedal is depressed, brake force at least increases proportionately, but this is not the case.
For some reason too much force is applied too early.

![brake_force](https://cloud.githubusercontent.com/assets/10550037/6234819/b0fc861a-b6ab-11e4-9886-c824aaf304ed.png)

**Comment by ulteq** [comment]
https://github.com/RigsOfRods/rigs-of-rods/pull/646
