### ISSUE TITLE
Archive down?

### ISSUE THREAD

**Issue by zacharylROR** [RigsOfRods/rigs-of-rods#815]
For some reason when i get on the Archives "it says 404 there isn't a GitHub page here" what happend?. Also on Allied gaming i heard we found a new website owner is it true?

**Comment by AnimosusTheWolf** [comment]
@only-a-ptr is working on bringing a new website online.

**Comment by WillyB1337** [comment]
As there's something about a website down : The repo archive http://ny.avrintech.net:81/repofiles/ doesn't work. It says "ERR_CONNECTION_TIMED_OUT"

Wanna know the host of this website about that.

**Comment by Hotrod55** [comment]
http://ny.avrintech.net:81/repofiles/ is down because the server OS is currently being reinstalled. I'm currently uploading everything at http://repofiles.avrintech.net/. Will take a couple hours.
