### ISSUE TITLE
Skinzip skin selection unable to select default

### ISSUE THREAD

**Issue by AnimosusTheWolf** [RigsOfRods/rigs-of-rods#818]
When you select a vehicle that has a skinzip(s), if you select any of the skins that are part of a skinzip to preview it, and then select the 'default skin' and click ok it will not load the default skin but the first skin that is listed that is part of a skinzip.

**Comment by lexman02** [comment]
Have you tried a different .skinzip file and what version are you using?

**Comment by AnimosusTheWolf** [comment]
I've tried it on multiple vehicles with multiple skinzips. Once you click off default skin you can never spawn it with the default skin. This has happened since skinzips were introduced, still happens in 0.4.6

**Comment by DirtGamer301** [comment]
@lexman02 Just as TheWolf said, it happens with every single skinzip and since I used skinzips (just saying it, too, since there was some doubt whether he's right or not).

**Comment by lexman02** [comment]
@DirtGamer301 @AnimosusTheWolf Im going to have to try it because I know the .skinzips that I have work fine but let me check.

**Comment by DarthCainRor** [comment]
It works fine here. 
green one was spawned first.

![screenshot_2016-04-05_00-12-53_1](https://cloud.githubusercontent.com/assets/10333582/14271895/4a7ef0a0-fac3-11e5-9570-6eac41ef522a.png)

**Comment by DirtGamer301** [comment]
@DarthCainRor That's not the error. The problem isn't with spawning something and then spawning another one later, it's when spawning the first one.
For example:
-stock colour is white
-first colour in the skin selector is blue
-second one is green
-third is orange

Select the vehicle with the skinzip,  now you can select a skin. If you now spawn the stock skin right away it's alright.
If you however first press on the third skin (or any other one that's not the stock one) and then press on the stock one, spawn the stock one, the game will spawn the first one that's on the list and not stock, in this case blue.

**Comment by DarthCainRor** [comment]
Oh,that bug. >.< That ones been around since .38 at least. My bad.

**Comment by AnimosusTheWolf** [comment]
https://youtu.be/AVL3jsjwIHU

**Comment by ulteq** [comment]
Relevant code section: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/gui/panels/GUI_MainSelector.cpp#L649-L682
