### ISSUE TITLE
Localization doesn't work on ror next

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#82]
The localization files from ror 0.4.0.7 doesn't work on ror next.

**Comment by Max98** [comment]
I don't really understand this. What's the localization? Any pictures? Video?

**Comment by Speciesx** [comment]
http://en.wikipedia.org/wiki/Internationalization_and_localization

**Comment by Max98** [comment]
Oh, language selection? I see.

**Comment by Hiradur** [comment]
Closing as duplicate of #391
