### ISSUE TITLE
Skinzips break MaterialFlares

### ISSUE THREAD

**Issue by DODGEcharger** [RigsOfRods/rigs-of-rods#827]
Reproducable in 0.4.5.0 with the Dura-Built 176 semi trailer. Materialflares work as designed with the default skin, but when a skinzip is selected the material flares are forced to their on state.

**Comment by DarthCainRor** [comment]
Has been a problem since Skinzips were introduced I believe, but it is quite annoying.

**Comment by only-a-ptr** [comment]
Can anyone please test this with https://github.com/RigsOfRods/rigs-of-rods/pull/1271 ?
