### ISSUE TITLE
lockgroups not supporting nodes2

### ISSUE THREAD

**Issue by derbymutt** [RigsOfRods/rigs-of-rods#829]
In previous versions of RoR, nodes2 nodes could be used in lockgroups.
Example of how nodes2 would have been used

```
lockgroup_default_nolock

nodes2
HITCH0,	-12.100,	 0.875,	 0.000,	l 70 	

lockgroups
;lockgroup,  nodeIDs
        -1,   HITCH0
```

Changing HITCH0 in the lockgroup section to its node number in 0.4.6 will make the lockgroup function (in the case of the example changing HITCH0 to 0 would work.)

Existing content that implements nodes2 in lockgroups: https://www.dropbox.com/s/w615te2n4o1ykcr/DerbymuttRacingTransportSemiTrailer.zip?dl=0

**Comment by ulteq** [comment]
Relevant code sections:

https://github.com/RigsOfRods/rigs-of-rods/blob/1ebd359dbd467b4c3171dd6d054e7d8ec39f78ba/source/rig_file_input_output/RigDef_Regexes.h#L1731-L1746

**Comment by ulteq** [comment]
@derbymutt Can you test if this: https://github.com/RigsOfRods/rigs-of-rods/pull/833 fixes your issue?
