### ISSUE TITLE
Vehicle materials do not unload with vehicle and generate error messages

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#83]
I get this error, when i load the same vehicle on the next terrain.
![ror_2015_02_18_17_38_48_184](https://cloud.githubusercontent.com/assets/1196375/6251966/44d569f6-b797-11e4-8d05-ccc8c4b91bf0.png)

**Comment by Max98** [comment]
Interesting. @only-a-ptr Maybe the parser isn't destroying it's variables on the destructor function?

**Comment by only-a-ptr** [comment]
This is actually standard v0.4.0.7 behavior. These errors were always reported in RoR.log. The information is: Materials with these names are already loaded by OGRE engine. That means either the vehicle was already loaded in the current RoR session, or that some other vehicle has materials with the same names.

I suppose the materials should be unloaded from OGRE when the vehicle is unloaded (or when players selects another map/goes back to menu)

**Comment by only-a-ptr** [comment]
Fixed, see the [MERGED] link above.
