### ISSUE TITLE
 Big Black Square on left bottom side of screen

### ISSUE THREAD

**Issue by lrivard00** [RigsOfRods/rigs-of-rods#838]
There is a big black box on the side of the screen. It block the view of half the screen. And the speedometer shows up the upside down. Can someone fix this?

**Comment by Hiradur** [comment]
screenshot please.

**Comment by lrivard00** [comment]
![img_4623](https://cloud.githubusercontent.com/assets/18453476/14765000/8458b6ba-0993-11e6-8d50-487306d627a1.JPG)

**Comment by Hiradur** [comment]
What RTT mode is your renderer set to in RoRConfig?
