### ISSUE TITLE
Texture shadows bug

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#84]
Terrain: Auriga Proving Ground

![ror_2015_02_18_17_37_55_076](https://cloud.githubusercontent.com/assets/1196375/6252435/9943f72a-b79a-11e4-819d-9d991f9399a2.png)

**Comment by Hiradur** [comment]
And I thought it was Linux only.

**Comment by Max98** [comment]
Yes, it's not Linux only. And the thing is that it happens randomly.

**Comment by Max98** [comment]
With more random things I've done lately, found a bug that is similar to this one. Applying SkyX's Atmospheric scattering on few terrains ends up with the same problem.

This might be a problem coming from Ogre?

http://i.imgur.com/DabfaQx.jpg

**Comment by Michael10055** [comment]
Latest master: https://streamable.com/ox9u7

**Comment by only-a-ptr** [comment]
Just opened a random old bug.

I need more info on this - does it still happen? If yes, post a RoR.log and RoR.cfg and tell me if it happens always and if not, how often.

**Comment by Michael10055** [comment]
It's been happening ever since PSSM was fixed. Usually texture shadows don't render at all.

**Comment by tritonas00** [comment]
When i enable texture shadows i get

> OGRE EXCEPTION(2:InvalidParametersException): Requested options require too many texture samplers! Try reducing the number of layers. in generateFpHeader at /home/babis/Downloads/rigsofrods-next-build/rigsofrods/src/rigs-of-rods/source/main/terrain/OgreTerrainPSSMMaterialGenerator.cpp (line 1049)

**Comment by only-a-ptr** [comment]
@tritonas00 Looks like a consequence of https://github.com/RigsOfRods/rigs-of-rods/commit/dff13494f1dfada03a19a33d8c87123bbc454e19

**Comment by tritonas00** [comment]
Yes, reverting to 2.25f fixed the crash here

**Comment by only-a-ptr** [comment]
Removing from v0.4.8 - no time left to fix, and let's port to OGRE 1.10+ first.
