### ISSUE TITLE
Vehicule's destruktion >100%

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#85]
How is that possible?
btw: I know my English is bad, but is "Vehicule's" an English word?
![ror_2015_02_19_23_53_02_065](https://cloud.githubusercontent.com/assets/1196375/6277850/78e50e76-b892-11e4-8ca8-fc1c7c01e7ef.png)

**Comment by Max98** [comment]
My bad, "Vehicule" is indeed not English but French. Will fix the typo and the bug!
