### ISSUE TITLE
game loading

### ISSUE THREAD

**Issue by nosycrazy88** [RigsOfRods/rigs-of-rods#851]
Hey I got a question about version I think 0.4.2.1 will this game work on my windows vista? If not wats the lastest version that I can use on it cuase me and my lil bro really would Like it play this new version of RoR. I've been playing since 2012.

**Comment by Hiradur** [comment]
There is no version 0.4.2.1. I guess nobody tested newer versions of RoR on Windows Vista so you just have to try it, it will probably work.

**Comment by ulteq** [comment]
> If not wats the lastest version that I can use

0.4.6 -> http://rigsofrods.org/thread-3.html
