### ISSUE TITLE
Skinning

### ISSUE THREAD

**Issue by lexman02** [RigsOfRods/rigs-of-rods#854]
I am new to modding things in RoR like making skins and what not. So I just finished this huge skin pack and was wondering where could I put the GUID because on the backup of the wiki it gives me links to obtain an authors GUID but I cant click on it because its dead. Do I just use my personal GUID or is there another way to obtain an author GUID. The vehicle does not have a GUID so I need to give it one.

**Comment by graysonk95** [comment]
GUIDs are specific IDs used to identify the vehicle the skin is assigned to.
https://ror.avrintech.net/rorwikibackup/index.php/Truck_Description_File#GUID

If a vehicle does not have a GUID it cannot be skinned using a skinzip.
If the author is still active, you could try contacting them and asking if they could push an update with GUIDs.
But if they refuse, or if they are inactive, all you can do is release the texture files to overwrite the originals.

**Comment by DirtGamer301** [comment]
What you can do is edit the files yourself.
Simply use a guid generator (https://www.guidgenerator.com/ for example), create your guid and put it in the .skin file.
You have to add the guid to the vehicle, too. Open the vehicle(s) .truck file and add a line called
guid *insert your generated guid here*
It's usually somewhere at the top.

**Comment by lexman02** [comment]
I did all of that and compiled the .skinzip file and put it in my packs folder but when I went to load it in, it didnt give me the option to choose which skin I wanted. I am using 0.39.3 if that helps.

**Comment by Hiradur** [comment]
We don't offer any support for versions older than 0.4.5, please check if the issue still exists with 0.4.5 or newer.

**Comment by lexman02** [comment]
It does, it still doesnt give me the option of selecting the skin that I want.

**Comment by DirtGamer301** [comment]
Could you upload the files so that we can take a look at it and probably solve the problem?

**Comment by lexman02** [comment]
[Skinzips.zip](https://github.com/RigsOfRods/rigs-of-rods/files/253009/Skinzips.zip)

**Comment by DirtGamer301** [comment]
Check again whether you added the  guid correctly to the buses .truck files and make sure they're exactly the same.

**Comment by lexman02** [comment]
I did

**Comment by Chris7676** [comment]
I skinned the HDX Correctly. I would suggest that everything in the .skin file is correctly entered/and or spelled correctly. You have to make sure you are using the GUID for the version of the bus you are skinning.

**Comment by lexman02** [comment]
I know and I have successfully skinned the HDX but I'm having issues skinning GraysonK95's C2 and GCPS's 2016 Vision

**Comment by Chris7676** [comment]
Okay then, there should be a button that says Close Issue. You can press it and close the issue.

**Comment by Chris7676** [comment]
It is because GCPS Vision and Grayson's C2 were not created with a texture file like the HDX which had a PNG with all the body textures. You will have to edit the individual files like for example body.png for the body color. You can use skinzips. I might make a tutorial on that.

**Comment by lexman02** [comment]
Yeah thats what I did but for some reason the skinzip menu wont even load it only spawns the bus.

**Comment by Chris7676** [comment]
Did you generate a GUID (https://www.guidgenerator.com/) put it in the truck file were the GUID would be placed in the truck file (refer here: https://ror.avrintech.net/rorwikibackup/index.php/Truck_Description_File#GUID ) And match the GUID in the truck file that you added to the GUID in the skinzip.

**Comment by lexman02** [comment]
Yes

**Comment by Chris7676** [comment]
Then I am not sure what the issue would be. I am sorry, I might try it for myself and see if it works.

**Comment by timlee32** [comment]
My PC says msv.dll not found

**Comment by Chris7676** [comment]
timlee32. What?
