### ISSUE TITLE
rename current mass in vehicle mass

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#86]
Because it doesn't show the current mass. Here i ripped off the doors, bumper and hood and the current mass still show 1.83 tons and the same amount of beams.
![ror_2015_02_19_23_40_13_985](https://cloud.githubusercontent.com/assets/1196375/6278001/909f7488-b893-11e4-9089-fb0234441358.png)
![ror_2015_02_19_23_40_18_425](https://cloud.githubusercontent.com/assets/1196375/6278002/90c221ea-b893-11e4-9c87-493ca22d74e2.png)

**Comment by Max98** [comment]
Fixed.

**Comment by Max98** [comment]
My bad, closed the wrong one.

**Comment by Max98** [comment]
Done! :)
