### ISSUE TITLE
Vehicle info: gees unreadable

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#87]
The position of Saggital and Lateral should be locked, because they are unreadable through the fast movements.

**Comment by Max98** [comment]
What do you mean? You can it like, uhm, you press a button and it hold the latest value before the press?

**Comment by Hiradur** [comment]
I think he means they should always display the same amount of digits.

**Comment by Speciesx** [comment]
Was fixed.
