### ISSUE TITLE
[RoRBot] rotate left/right animation bug

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#887]
https://youtu.be/9QH1vOOtT14

**Comment by ulteq** [comment]
It seems to be an animation issue.

Relevant code section: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/gameplay/Character.cpp#L360-L380

**Comment by only-a-ptr** [comment]
Resolved by @Vido89's updated animations.
