### ISSUE TITLE
Little description of cpp/h files

### ISSUE THREAD

**Issue by Max98** [RigsOfRods/rigs-of-rods#91]
I think that if we add a little description of all the files on the source code, just to point out what is its function, it would make coding much easier.

How would we do this? Simple, each time you work on a file, and as soon as you understand it, you write a little summary of what it does.

**Comment by Hiradur** [comment]
:+1:

**Comment by only-a-ptr** [comment]
This effort only makes sense if someone periodically refreshes the online doxygen documentation.

Also, I think filenames and class names provide enough info about the file as a whole. It's more important to put comments to classes and functions.

Good example of doxygen documentation: http://stackoverflow.com/q/51667

**Comment by Hiradur** [comment]
Here is neorej16's doxygen server:
http://ror.ezzg.be/docs/

**Comment by AnotherFoxGuy** [comment]
The doxygen documentation is also available here;
http://anotherfoxguy.github.io/RoRdocs

**Comment by Hiradur** [comment]
Great, thanks!

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy :+1:
