### ISSUE TITLE
Crash when dragging the terrain selector menu 

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#917]
Steps to reproduce:
- Go to single player
- Try to move the terrain loader window

The game crashes with an Error 6: FileSystemArchive::open

**Comment by ulteq** [comment]
I can't reproduce it on linux.

**Comment by tritonas00** [comment]
>I can't reproduce it on linux.

neither do i

**Comment by mikadou** [comment]
Cannot reproduce on Windows with latest master. I can move the loader window around just as one would expect. No crashing.

**Comment by AnotherFoxGuy** [comment]
Here is a screenshot of it happening: 
![2016-05-15_16-55-13](https://cloud.githubusercontent.com/assets/9480940/15275189/ef237ed4-1ac4-11e6-833e-286d38c83019.jpg)

**Comment by tritonas00** [comment]
Same on linux

**Comment by disloyalpick** [comment]
Unable to reproduce. (Running Linux 16.04 Xenial)

**Comment by Michael10055** [comment]
Still happens for me with the current upstream:
![1](http://i.imgur.com/AJ8wYaz.png)

**Comment by tritonas00** [comment]
A certain map causes this crash. Try with the stock packs folder form resources/skeleton.zip

**Comment by only-a-ptr** [comment]
@tritonas00 @Michael10055 Maybe it's caused by maps which don't have a preview image? I'm wondering why would RoR try to open a resource with empty name.

**Comment by tritonas00** [comment]
Maybe you can reproduce it if the **first** (auto selected) map has no preview image

**Comment by only-a-ptr** [comment]
> Maybe you can reproduce it if the first (auto selected) map has no preview image

Yes, that's the scenario. Just reproduced.

**Comment by only-a-ptr** [comment]
Fix pushed to upstream manually. Problem solved.
