### ISSUE TITLE
rig_editor.cfg missing by default

### ISSUE THREAD

**Issue by schmatzler** [RigsOfRods/rigs-of-rods#95]
I just compiled the latest codebase on Linux here (Slackware64).

When I run the game the first time, it doesn't copy rig_editor.cfg into its own config directory and I can't start the Rig Editor because of that - this error happens:

An exception has occured!: OGRE EXCEPTION(6:FileNotFoundException): '/home/schmatzler/.rigsofrods/config/rig_editor.cfg' file not found! in ConfigFile::load at /tmp/SBo/ogre_src_v1-8-2/OgreMain/src/OgreConfigFile.cpp (line 88) / url: http://wiki.rigsofrods.com/index.php?title=Error_6#ConfigFile::load

**Comment by Max98** [comment]
I'm actually working on that. The RoRConfig used to make the folder where all these files are stored. But now RoR it self will make it.

https://gist.github.com/Max98/a4dad44455012de91a7a

**Comment by vido89** [comment]
Im also afected by this error

OGRE EXCEPTION(6:FileNotFoundException): '/home/slobodan/.rigsofrods/config/rig_editor.cfg' file not found! in ConfigFile::load at /home/slobodan/ror-deps/ogre/OgreMain/src/OgreConfigFile.cpp (line 88)

Im on linux and cant open rig editor, my version is up-to date with git hub.

**Comment by Max98** [comment]
Move resources/skeleton/config/rig_editor.cfg to "/home/slobodan/.rigsofrods/config/"

**Comment by vido89** [comment]
Tnx now everything seams ok :+1:

**Comment by Max98** [comment]
Actually this isn't much of a bug. rig_editor.cfg is supposed to be moved by the installer/RoR Config first start. 
For the moment you can just:
Move "resources/skeleton/config/rig_editor.cfg" to "/.rigsofrods/config/" (linux) or "Documents/Rigs of rods XX/config" (Windows)
